### ISSUE TITLE
I request for Steve.

### ISSUE THREAD

**Issue by steve-is-me** [FunkinCrew/Funkin#1000]

**Comment by VMGuy23** [comment]
Please make sense.

**Comment by nickpythonluajava** [comment]
happy 1000th issue

**Comment by VMGuy23** [comment]
This may be issue #1000 but it shouldn't exist

**Comment by prokube** [comment]
happy 1000th ninjamuffin this is what you get for being a troll about leaks lol

**Comment by Windows1Door2Daniel** [comment]
Thats gay

**Comment by Windows1Door2Daniel** [comment]
Thats trash
