### ISSUE TITLE
we need steve

### ISSUE THREAD

**Issue by steve-is-me** [FunkinCrew/Funkin#1002]
## What is your suggestion, and why should it be implemented?
![image](https://user-images.githubusercontent.com/83514968/116793833-143ec480-aac1-11eb-92e5-2abd22adf797.png)

**Comment by VMGuy23** [comment]
No. This is not Minecraft. Please, stop

**Comment by aflacc** [comment]
s

**Comment by nickpythonluajava** [comment]
https://youtu.be/BFL9hlNZx1o

**Comment by prokube** [comment]
> #### Please check for duplicates or similar issues before creating this issue.
> ## What is your suggestion, and why should it be implemented?
please stop doing this unless you have proof of you donating enough to receive the "you in-game" reward

this is funny but stop

**Comment by Nikostormkilla** [comment]
funny but nope
