### ISSUE TITLE
Bug Report: UNable to compile

### ISSUE THREAD

**Issue by lposrt** [FunkinCrew/Funkin#1004]
when running 'lime test html5 -debug' i recieve this error:
lime : The term 'lime' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lime test html5 -debug
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (lime:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Can anbody help?

**Comment by TheDrawingCoder-Gamer** [comment]
you didn't setup lime properly
run `haxelib run lime setup`

**Comment by VMGuy23** [comment]
You need to install lime.

**Comment by TheDrawingCoder-Gamer** [comment]
or that ;p;
