### ISSUE TITLE
The Bug Report: Cutscene of week 7 is not synchronized and the sound of 3 2 1 when starting a week is glitched

### ISSUE THREAD

**Issue by peter-in-reverse** [FunkinCrew/Funkin#1010]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by The-SGPT** [comment]
Please use the description for your issue next time.

**Comment by peter-in-reverse** [comment]
Yeah ok
