### ISSUE TITLE
Enhancement: Repeat current song in freeplay

### ISSUE THREAD

**Issue by ray1997** [FunkinCrew/Funkin#1013]
It woukd be a little nice addition to toggle repeat current song either on freeplay menu or pause menu.

**Comment by VMGuy23** [comment]
I think it would be a nice addition to the pause menu

**Comment by Kiffolisk** [comment]
how would this work? do you just mean once its completed it restarts?

**Comment by VMGuy23** [comment]
Yeah

**Comment by ray1997** [comment]
> how would this work? do you just mean once its completed it restarts?

Exactly!
