### ISSUE TITLE
Enhancement: Story Story Mode

### ISSUE THREAD

**Issue by VMGuy23** [FunkinCrew/Funkin#1015]
## What is your suggestion, and why should it be implemented?
There should be a story mode with the different difficulties that covers all weeks, cutscenes at the begginig, between weeks and after would be nice. Better for new players.

**Comment by aflacc** [comment]
thats something that they said would be planned in the kickstarter. we hit the goal so we getting it

**Comment by VMGuy23** [comment]
Nice
