### ISSUE TITLE
Question: Why does BeatBattle.hx exist?

### ISSUE THREAD

**Issue by ThePlank** [FunkinCrew/Funkin#1018]
I'm probally nitpicking a small thing but i hate it.
The file literaly isn't a state or a utility. It's just a blank file, the file exsisted in the initial commit and it was still blank. Why? Just why?
No file imports it so i choud just be deleted.

**Comment by aflacc** [comment]
thats actually a really good question

**Comment by JackOfAll64Trades** [comment]
Maybe it was a testing file, for you file diggers. A lot of developers leave things like that. For example, Undertale has hidden files, where some things were tested. They are left there to help the developers understand how things work, incase they decide to update it. Those having a blank page is weird.

**Comment by Nikostormkilla** [comment]
> Maybe it was a testing file, for you file diggers. A lot of developers leave things like that. For example, Undertale has hidden files, where some things were tested. They are left there to help the developers understand how things work, incase they decide to update it. Those having a blank page is weird.

Yeah, I thought it could have some standard haxe script shit but it's just blank.

**Comment by PurpleButNotALight** [comment]
My pull request for removing that file was merged so it dosent exist anymore.
