### ISSUE TITLE
Bug Report: Arrows freezing at beginning of song

### ISSUE THREAD

**Issue by AndresGreenboi** [FunkinCrew/Funkin#1025]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

dont know specifics but Windows 10 , 64 bit version

## What version of the game are you using? Look in the bottom left corner of the main menu.

most recent of the time

## Please describe your issue. Provide extensive detail and images if possible.

At first the game wouldn't open at all, but after doing some research, i opened it. but now the arrows stay still at beginning of song only bouncing up and down like maybe 10 pixels and everything else works. i cant still press buttons to miss and stuff.

**Comment by PurpleButNotALight** [comment]
This is a preformance issue. This may be because it needs 2 tracks to play at the same time.

**Comment by AndresGreenboi** [comment]
I dont understand what you mean by 2 tracks playing at the same time

**Comment by VMGuy23** [comment]
BG+Voices
