### ISSUE TITLE
Bug Report: Black Screen

### ISSUE THREAD

**Issue by 8868boyfriend** [FunkinCrew/Funkin#1027]
I have a windows seven notebook with 32 bits I have the problem that I open the normal game and as administrator but when I open it the haxeflixel logo appears and then it turns black but you  can hear the game and you can play but i se everything black I am not recording I did everything I tried using game boosters also use ccleaner i tested download optimized versions restart the pc please help

**Comment by PurpleButNotALight** [comment]
Did you click into the window?

**Comment by VMGuy23** [comment]
Did you download 32-bit version? Also send screen record

**Comment by 8868boyfriend** [comment]
@PurpleButNotALight yes

**Comment by 8868boyfriend** [comment]
@VMGuy23 http://sc.com.ly/show/2IKQvDfjlL0SZA4mHqaeFh9W3iXJEk7n
this is the screen record note: i speak Spanish

**Comment by PurpleButNotALight** [comment]
Did you compile the game yourself or is it the itch.io release?

**Comment by 8868boyfriend** [comment]
is a itch.io release

**Comment by 8868boyfriend** [comment]
@VMGuy23 I already did it but the same thing happens, it's still black

**Comment by VMGuy23** [comment]
Strange...
