### ISSUE TITLE
Bug Report: Week 6 icons 

### ISSUE THREAD

**Issue by SanGakuBoi** [FunkinCrew/Funkin#1028]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Newgrounds
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium-based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Google Chrome, version 90.0.4430.93 (Official Build) (x86_64)
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.8 (Newgrounds exclusive preview)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
you first hop into week 6 and then press 9 to change the icon on the health bar, and it changes to the old bf icon, then you press 9 again and it changes to the normal, non-pixelated bf icon and it stays like that until the end of the song
## Please describe your issue. Provide extensive detail and images if possible.
the icon on the health bar of week 6 after pressing 9 twice gets non-pixelated.
![image](https://user-images.githubusercontent.com/83707038/117140921-90f8c980-ad73-11eb-8a18-f1bc772114c1.png)

**Comment by Salladk-but-no-mo-flaged** [comment]
sus

**Comment by nickpythonluajava** [comment]
it's a debug feature, example when you hop into a normal song and press 9 it changes into the beta icon it's supposed to be like that

when you press 9 again it should change back

**Comment by SanGakuBoi** [comment]
yeah it should but it doesn't change to the pixel bf icon, it goes to the non pixel one

**Comment by Master811129** [comment]
> sus

a m o g u s

**Comment by SanGakuBoi** [comment]
Thanks, 2 years late though.
