### ISSUE TITLE
Typo in PlayState.hx

### ISSUE THREAD

**Issue by sqirradotdev** [FunkinCrew/Funkin#103]
Hi @ninjamuffin99 , in PlayState.hx, latest commit, you made a typo in line 138 where ```curState = "spooky";``` should have been ```curStage = "spooky";```.
I am not making a PR because it's a simple fix lol.
Sorry for tagging, mr developer

**Comment by ninjamuffin99** [comment]
oops yea i think i fixed dis one, heheh thanks!
