### ISSUE TITLE
how do you open the game

### ISSUE THREAD

**Issue by jmastermills** [FunkinCrew/Funkin#1030]
I can't open the game I'm trying to make a full week mod

**Comment by VMGuy23** [comment]
Do you mean the source code you downloaded from github? You need to follow instructions to build the game in the readme.

**Comment by jmastermills** [comment]
ok thanks :)

**Comment by VMGuy23** [comment]
No problem :)

**Comment by prokube** [comment]
reminder to close

**Comment by TentaRJ** [comment]
@jmastermills please close this issue now that it is fixed
