### ISSUE TITLE
Bug Report: my game crash when I run a week I play in 32bit in win 10 if I play on newgrounds or itch.io or if I play in 64bit it crashes

### ISSUE THREAD

**Issue by no-us** [FunkinCrew/Funkin#1033]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by actuallyasmartname** [comment]
You have a 32 bit computer then

**Comment by no-us** [comment]
> You have a 32 bit computer then

yes

**Comment by no-us** [comment]
and how to solve the problem pls

**Comment by VMGuy23** [comment]
Download the 32-bit version

**Comment by Salladk-but-no-mo-flaged** [comment]
> > Download the 32-bit version
> 
> but i said than it crashes when I run 32bit fnf

well u fkd

**Comment by no-us** [comment]
okay and how to fix bug

**Comment by GabrielPivot** [comment]
you don't.
32 bit version probably doesn't works so you need to buy a new pc.
