### ISSUE TITLE
download doesent work for chromebook

### ISSUE THREAD

**Issue by turnkeyson** [FunkinCrew/Funkin#1034]
it says its incombatable with chrome os

**Comment by VMGuy23** [comment]
Yeah that's because it is. You cant download on chrome os

**Comment by rxchiie** [comment]
er- duh. it is not compatible with chrome os. your biggest chance is to enable linux in settings if your chroembook supports that.

**Comment by JaidenTfsAlt** [comment]
Or play on Newgrounds if you really have to

**Comment by Nikostormkilla** [comment]
Because it's not. All you could probably do is play the game on Newgrounds or enable Linux in the settings.

**Comment by nickpythonluajava** [comment]
Linux Momentum

**Comment by ninjamuffin99** [comment]
funkin isnt supported on chromebook right now
