### ISSUE TITLE
so something wierd happened 

### ISSUE THREAD

**Issue by SUSSY-beep** [FunkinCrew/Funkin#1037]
i was playing fnf when a wierd noise happens and it happens when i complete a level. it dosent always happen when i win it happens randomly plz fix this im playing on newground on and im using a chromebook

**Comment by VMGuy23** [comment]
Screen record?

**Comment by hdboye** [comment]
It's probably the debug beep

**Comment by VMGuy23** [comment]
Yeah. Also I'm commenting from the past...
![image](https://user-images.githubusercontent.com/81651922/117484267-c6153f80-af5e-11eb-9bdb-430aa881e08f.png)

**Comment by nickpythonluajava** [comment]
are you looking for #1057?
