### ISSUE TITLE
Bug Report: Setting down scroll in settings doesn't persist between sessions

### ISSUE THREAD

**Issue by FigmentBoy** [FunkinCrew/Funkin#1038]
### If you are playing the game in a browser, what site are you playing it from?
Newgrounds
### If you are playing the game in a browser, what browser are you using?
Google Chrome
### If you are playing a downloaded version of the game, what operating system are you using?
N/A
## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.8
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Choose downscroll in preferences
## Please describe your issue. Provide extensive detail and images if possible.
Setting down scroll in settings doesn't persist between sessions

**Comment by EliteMasterEric** [comment]
Forgot to mark this as legacy somehow lol
