### ISSUE TITLE
Can't Play Week 7 On Newgrounds

### ISSUE THREAD

**Issue by Shronk69** [FunkinCrew/Funkin#1041]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Newgrounds

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Chrome

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Unsure, think Windows or macOS?

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.8 (Newgrounds exclusive preview)

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Open Game
Pick Week 7
that's it

## Please describe your issue. Provide extensive detail and images if possible.
I've been trying to play Week 7 on Newgrounds, but every time I do it's either just a straight black screen forever, or I only see the bar at the bottom to see who's "winning" and a black screen. Can't leave the week in game and have to refresh browser to escape. I've tried clearing cache and cookies but that doesn't seem to help. I just wanna try the new week but can't do that if the site doesn't let me :(

**Comment by Animelici804** [comment]
Mine is a lot worse; Newgrounds is banned in my country and I can only play it either with a VPN or in a mirror link Newgrounds doesn't support. The funnier fact is that even some of the VPN's are getting banned in my country as well.

**Comment by myst-rblx** [comment]
> Mine is a lot worse; Newgrounds is banned in my country and I can only play it either with a VPN or in a mirror link Newgrounds doesn't support. The funnier fact is that even some of the VPN's are getting banned in my country as well.

try going to http://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/

**Comment by VMGuy23** [comment]
@myst-rblx did you get that link from me in another issue?

**Comment by nickpythonluajava** [comment]
maybe it's a ram issue, how much ram do you have?

**Comment by Arsynist** [comment]
I've had this exact issue, and have only had it work once. The rest of the time it stays stuck on a black screen, same as described here.
