### ISSUE TITLE
Bug Report: Game won't run (Linux)

### ISSUE THREAD

**Issue by Rexyislive** [FunkinCrew/Funkin#1042]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

- Zorin OS 15.3 (Ubuntu 18.04)

## What version of the game are you using? Look in the bottom left corner of the main menu.
Not accessible

## Please describe your issue. Provide extensive detail and images if possible.

After unzipping and ensuring the 'Funkin' file can be executable, I drag the file into my terminal window. The following error appears:

`/home/stan/Downloads/funk/Funkin: /lib/x86_64-linux-gnu/libm.so.6: version  'GLIBC_2.29' not found (required by /home/stan/Downloads/funk/Funkin)`

**Comment by VMGuy23** [comment]
Zorin OS uses Ubuntu 18.04. The required GLIBC version is only available in 21.04. Get Ubuntu 21.04 because Zorin is a bunch of renamed software
