### ISSUE TITLE
Bug Report: Bouncing Black Square and Game Crash

### ISSUE THREAD

**Issue by kxau** [FunkinCrew/Funkin#1043]
Hello, I would like to bring attention to some _minor_ flaws.

Here's a video I recorded of my experience playing the game: [link](https://youtu.be/YptcihYxg7w)

First of all, when opening week one, Girlfriend and the speakers she sits on are missing and are substituted by a bouncing black square. Second, when I finish the first song of week 1, the game crashes without fail.

I don't know if the first issue is some kind of new art style choice, but it's a pretty minor flaw compared to the game crashing whenever you finish a song. The square only appears if you maximize the window before loading week 1. The crash happens every time. All the time.

I am running the 32-bit version of the game released on ninjamuffin99's itch.io page on February 15, 2021, on a 64-bit Windows desktop computer. There were no other programs running besides OBS at the time of the recording.

I really want to experience FNF in it's fullest, but I can't in my current situation.

Even if this is a unique issue, I still think it's pretty funny.

Signed, Twitter User [Xeebakou](https://twitter.com/Xeebakou)

**Comment by VMGuy23** [comment]
Use 64-bit version and also how much ram you have?

**Comment by kxau** [comment]
The 64-bit version works fine, I would just prefer to use the 32-bit version.

I have 8G of RAM.

**Comment by VMGuy23** [comment]
32-bit probably doesn't have the capability to use the RAM it needs.

**Comment by kxau** [comment]
Yeah
