### ISSUE TITLE
Week 7 lags so much is unplayable.

### ISSUE THREAD

**Issue by RDavidSK** [FunkinCrew/Funkin#1044]
I've tried to play week 7 from newgrounds since it came out but it just unplayable, the fps goes down to 8 fps and I have no idea why does this happends, I have tried other browsers (I use Google Chrome) I have tried cleaning the cookies, and even tried in a sh*tty school laptop and for some reason in the laptop the game ran at a solid 60 fps meanwhile at my more powerfull computer the game was running so DAMN slow, please help me I really want to play week 7 and I don't know when i will be able to download the game to my computer :(.

**Comment by RetroB** [comment]
use brave browser. (not advertising it works)

**Comment by RDavidSK** [comment]
> use brave browser. (not advertising it works)

I tried and it still lags the same way

**Comment by VMGuy23** [comment]
Maybe you have not got graphics drivers or you have too much open?

**Comment by RDavidSK** [comment]
> Maybe you have not got graphics drivers or you have too much open?

I'm pretty sure I have everything up to date and I played with everything closed, the game downloaded is fine, but the newgrounds version is the problem.

**Comment by RDavidSK** [comment]
> > Maybe you have not got graphics drivers or you have too much open?
> 
> I'm pretty sure I have everything up to date and I played with everything closed, the game downloaded is fine, but the newgrounds version is the problem.

I just found out it's not just newgrounds, it everything, help ;-;

**Comment by RDavidSK** [comment]
> What exactly are your PC specs?

It's really bad ok but here it is: AMD A6-5200 APU with Radeon(TM) HD Graphics 2.00GHz
8 GB RAM (7.43 usable) 64 bits 64x

I hope this is how it's suposed to be written I'm sorry if not.

**Comment by NotHyper-474** [comment]
Weird, I have an Intel Celeron E3400 (January 2010 CPU) and a Nvidia 9500 GT (2008 GPU, ~~doesn't runs DirectX 11 but that's irrelevant here~~) and 6 GB of RAM and runs the game at solid 60 FPS. From this comparison [here](https://www.cpubenchmark.net/compare/Intel-Celeron-E3400-vs-AMD-A6-5200-APU/678vs1975) your CPU is better than mine (except in single-threaded processing)

**Comment by RDavidSK** [comment]
> Weird, I have an Intel Celeron E3400 (January 2010 CPU) and a Nvidia 9500 GT (2008 GPU, ~doesn't run DirectX 11 but that's irrelevant here~) and 6 GB of RAM and runs the game at solid 60 FPS (but it drops in some songs).
> 
> From this comparison [here](https://www.cpubenchmark.net/compare/Intel-Celeron-E3400-vs-AMD-A6-5200-APU/678vs1975), your CPU is better than mine (except in single-threaded processing) so I guess it might be that your GPU is took weak to run the game (specially with the sprites being mostly in 8k)

But the game runs ok when I download it, it's when I play from the browser when it lags, does the browser version needs more power? If so, is there anything I can do to have less lag?

**Comment by VMGuy23** [comment]
if you use chrome, use the new ms edge bcause thats a bit better, or use firefox

**Comment by trayfellow** [comment]
yeah this happens to the browser version, your framerate their will probably dip from 120fps to 80 fps sometimes (my monitor is 120hz)

the desktop version seems to fix this issue so i guess we'll just have to wait for the desktop version to come out

**Comment by RDavidSK** [comment]
> if you use chrome, use the new ms edge bcause thats a bit better, or use firefox

I have tried Chrome. Edge, OperaGX, Brave, no improvements, 

> yeah this happens to the browser version, your framerate their will probably dip from 120fps to 80 fps sometimes (my monitor is 120hz)
> 
> the desktop version seems to fix this issue so i guess we'll just have to wait for the desktop version to come out

As he said, we'll have to wait until the desktop version comes out, and hopefully that's not in a long time.

**Comment by Boii1** [comment]
I have a 5950X/3080 so it's definitely not a spec issue. It also just seems to lag regardless on desktop and browser. So likely an issue in the game engine itself.

**Comment by hdboye** [comment]
idk if this is still relevant, but try enabling hardware acceleration. that bumped the fps up to 50 for me

**Comment by StyleCannotCodeForShit** [comment]
i have a 3700x/2070s and i'm not getting lag. on my shit laptop it runs absolutely fine. have you gone from the uploads.ungrounded link that got thrown around or just newgrounds?

**Comment by RDavidSK** [comment]
> i have a 3700x/2070s and i'm not getting lag. on my shit laptop it runs absolutely fine. have you gone from the uploads.ungrounded link that got thrown around or just newgrounds?

(srry for answering now btw) Just newgrounds
