### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by meganman** [FunkinCrew/Funkin#1045]
I'm on safari, and no matter how many times I reload the page, it always freezes during loading at 53%.
<img width="1285" alt="Screen Shot 2021-05-07 at 11 29 33 AM" src="https://user-images.githubusercontent.com/83830068/117473262-c219fb00-af27-11eb-86c4-a222be07bb1f.png">

**Comment by VMGuy23** [comment]
Use other browser
