### ISSUE TITLE
Bug Report: i tried hooking up a rockband guitar for xbox with controlls that fit but it didn't work and now the controlls are janked up so i can't press left and i can't pause and it doesn't look like there is a way to reset my controlls so maybe add a reset controls button so people want have to do it manually and so people dont get the same problem as me.

### ISSUE THREAD

**Issue by MTTXX** [FunkinCrew/Funkin#1046]

**Comment by myst-rblx** [comment]
the game might NOT be built to support that. ever thought about that?

**Comment by nickpythonluajava** [comment]
> the game might NOT be built to support that. ever thought about that?

maybe if you get some adapter idk

**Comment by VMGuy23** [comment]
Or use Windows' Game Controller settings to keymap it

**Comment by actuallyasmartname** [comment]
how many fucking times do I have to see these issues with nothing in the description
also this isn't a supported controller to the game
