### ISSUE TITLE
How i can do a question

### ISSUE THREAD

**Issue by Windows1Door2Daniel** [FunkinCrew/Funkin#1047]
how i do it

u got trolled

 why week 2 is so hard in normal dificulty
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by VMGuy23** [comment]
The Adidas ad saved me

**Comment by Salladk-but-no-mo-flaged** [comment]
> The Adidas ad saved me

dang my most powerful weapon

**Comment by VMGuy23** [comment]
Keep on forgetting to get uBlock Origin. This forgetfulness has saved me so many rickrolls

**Comment by Salladk-but-no-mo-flaged** [comment]
mmh

**Comment by nickpythonluajava** [comment]
**bold_italic_**

**Comment by Windows1Door2Daniel** [comment]
i didnt even get responded why week 2 is so hard af

**Comment by VMGuy23** [comment]
I can do 2 on hard

It;s second hardest week but yeah its hard
