### ISSUE TITLE
Bug Report: Game crashes when playing week 7 (MacOS)

### ISSUE THREAD

**Issue by Corgidude** [FunkinCrew/Funkin#1050]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by nickpythonluajava** [comment]
use the body next time

idk maybe it's your computer or a ram issue or something

**Comment by VMGuy23** [comment]
Would a mac not be powerful enough to handle that?
