### ISSUE TITLE
Question: how do I  fix this so can compile the game

### ISSUE THREAD

**Issue by SpeedyTheOne22** [FunkinCrew/Funkin#1051]
It says I need to install visual studio 2017 VsDevCmd and a bunch of other stuff, I’ll put a picture to explain.
![image](https://user-images.githubusercontent.com/83318334/117523268-8f025680-af7d-11eb-994a-42ea52611b58.jpg)

**Comment by VMGuy23** [comment]
Install the stuff it says in the readme

**Comment by VMGuy23** [comment]
Well, I have same issue.

**Comment by nickpythonluajava** [comment]
but if you wanna mod without knowing haxe i just use fnf modding plus

**Comment by VMGuy23** [comment]
I have got the 22GB of crap (was 15GB because I already have VS)

**Comment by OMGcheese997** [comment]
i have all the stuff (i think)

**Comment by VMGuy23** [comment]
Same. Still have the issue
