### ISSUE TITLE
32 bits problem

### ISSUE THREAD

**Issue by Mosespb** [FunkinCrew/Funkin#1054]
Sorry to bother, I suppose you will have a lot of reports on the 32 bit version for pc, but could you know if it is something that will be fixed? or is it just that latest version that is failing? or is it my computer? I have 2gb of ram, there should be no problem because I play it normally in browser in newgrounds

**Comment by Mosespb** [comment]
> Bueno, probablemente tengas TAN POCA RAM, quiero decir, ¿qué es lo que podrías tener al menos dos GB más?

probablemente, pero hay juegos con mucho más gráficos que el FNF y me corren normal

**Comment by wellsilver** [comment]
Could you close this, and create a new issue using the template?
