### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Pfoxy567** [FunkinCrew/Funkin#1055]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by garc302** [comment]
Week 7 runs in javascript, so maybe that's the problem

**Comment by VMGuy23** [comment]
Edge can do Javascript. I'm just not sure if the legacy one can do HTML5. New one works great.

**Comment by nickpythonluajava** [comment]
maybe he is stuck on the haxeflixel loading screen because the fnf version is definitely not 4.9.0

**Comment by VMGuy23** [comment]
haxeFlixel version 4.9.0 I think

**Comment by hdboye** [comment]
bc the flixel preloader with lots of files is shit in browser.

**Comment by charlesisfeline** [comment]
no they did not
