### ISSUE TITLE
Bug Report: Audio bug specific on my computer.

### ISSUE THREAD

**Issue by JPysus** [FunkinCrew/Funkin#1056]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
-->    funkin-windows-64bit.zip 
          windows 64-bit

## What version of the game are you using? Look in the bottom left corner of the main menu.
-->    0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
-->    By running the game.

## Please describe your issue. Provide extensive detail and images if possible.
-->    
There is no audio on main menu, nor on most song. 
I recorded a gameplay of the issue.

https://www.youtube.com/watch?v=zyiRn-buPTw
https://www.youtube.com/watch?v=hBy4bPJE3QU

I ran the game in a windows 7 virtual machine and it's working great.
I just don't understand why it is broken specifically on my laptop.

Do I need something pre-installed?

**Comment by JPysus** [comment]
The audio on "Senpai" song is abruptly stopping because of missing notes.

**Comment by Windows1Door2Daniel** [comment]
maybe something happened to the song files

**Comment by VMGuy23** [comment]
Redownload and **extract** the zip. Try again. Try 64bit.

**Comment by JPysus** [comment]
I've already done that and it's still the same, unfortunately.
This is my 2nd report of the same issue that persisted on previous update.

It also works on a windows 7 virtual machine so I don't think that's the issue
