### ISSUE TITLE
Bug Report: Audio horrible

### ISSUE THREAD

**Issue by VMGuy23** [FunkinCrew/Funkin#1057]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Newgrounds
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Ubuntu 21.04
## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.8
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Chrome. play through a week (MUST be freeplay) and it is broken at the end
## Please describe your issue. Provide extensive detail and images if possible.
Sound is horrible for about 30 seconds after finishing a week

https://user-images.githubusercontent.com/81651922/117570032-7484c600-b0c0-11eb-8e57-ab3c3895e71c.mp4

**Comment by nickpythonluajava** [comment]
super annoying

**Comment by NotHyper-474** [comment]
I also got this. Really annoying.
