### ISSUE TITLE
Girlfriend and Boyfriend sprites turn in black squares

### ISSUE THREAD

**Issue by mukinhass335** [FunkinCrew/Funkin#106]
In the menu, the sprites of the girlfriend, boyfriend and dad turned into black squares and in the music part the sprites of the girlfriend and boyfriend turned black squares swinging. The game over menu is completely black, but the music remains perfect throughout the game. I already played the game on another computer and it works perfectly, but in the notbook (which I'm using now) it doesn't work at all because of some sprites. PLEASE HELP ME, your game is perfect and has a very good vibe and I want to make the most of it.[
![GAME](https://user-images.githubusercontent.com/76416261/102735364-fc8c4e00-4320-11eb-952f-639763010a48.png)
![GAME](https://user-images.githubusercontent.com/76416261/102735394-22b1ee00-4321-11eb-98a5-9d61d07e00dd.png)
`Printscreens!!!

](url)

**Comment by dinkstr** [comment]
Can you try running the game in another browser on your computer? Firefox or Microsoft Edge, for example.

**Comment by DarkMatterVraxx** [comment]
> Can you try running the game in another browser on your computer? Firefox or Microsoft Edge, for example.

I already try and the same thing happened to me ;l
