### ISSUE TITLE
Question: are there any supportive methods in haxeflixel to play video files?

### ISSUE THREAD

**Issue by CooperJ-0** [FunkinCrew/Funkin#1060]
Howdy, and first off, sorry. I understand this isn't really the place to ask this type of question, but I have had just no luck anywhere else. 

So I'm working with a close friend and animator to create a mod with him. One of the goals he has set out for me is getting cut scenes between the songs. Not the type you'd see on week 6, but more along the lines of the animations in the intro to the Whitty mod or the transition of character models in smoke em out whatever mod. I've searched up and down the internet trying to figure out how they did it, to no avail. I either get how to animate the characters for separate videos, or how to do text-based cut scenes like the ones in week 6.

My only guess would be to add in an object that has it's assets be the animation, set up the xml appropriately, and have it play out in between songs, in the same way the senpaiCrazy assets are used in PlayState for the transition. Though for the length of animation we were looking at, it might be impractical to do such, as the asset file would be too large.

I know that it is possible; week 7 is very obviously a video of some kind. But, since that version of the src isn't public, I'm really at a loss. 

If anyone could point me in the right direction, that would be great. Thanks!

**Comment by Steviegt6** [comment]
Honestly, it wouldn't be wise to play raw video files. Differing screen resolutions, desyncs, etc. are all issues that can easily occur.
