### ISSUE TITLE
Bug Report: haxelib run lime setup windows error 

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1061]
Mkay i installed EVERYTHING,and it still says "In order to build native executables for Windows, you must have a
Visual Studio C++ compiler with "Windows Desktop" (Win32) support
installed. We recommend using Visual Studio Community, which is
available as a free download from Microsoft" BUT I ALREADY INSTALLED IT(quick little question can someone tell me what windows desktop win32 support is?)

**Comment by actuallyasmartname** [comment]
run `haxelib run lime setup`

**Comment by bigboie22** [comment]
still dos'ent work

**Comment by VMGuy23** [comment]
What is the exact error?

**Comment by bigboie22** [comment]
i did it but it says "In order to build native executables for Windows, you must have a
Visual Studio C++ compiler with "Windows Desktop" (Win32) support
installed. We recommend using Visual Studio Community, which is
available as a free download from Microsoft.

No additional configuration is required.

Would you like to visit the download page now? [y/n/a]" but i already got it

**Comment by actuallyasmartname** [comment]
> i did it but it says "In order to build native executables for Windows, you must have a
> Visual Studio C++ compiler with "Windows Desktop" (Win32) support
> installed. We recommend using Visual Studio Community, which is
> available as a free download from Microsoft.
> 
> No additional configuration is required.
> 
> Would you like to visit the download page now? [y/n/a]" but i already got it

Compiling game
Once you have all those installed, it's pretty easy to compile the game. You just need to run 'lime test html5 -debug' in the root of the project to build and run the HTML5 version. (command prompt navigation guide can be found here: https://ninjamuffin99.newgrounds.com/news/post/1090480)

To run it from your desktop (Windows, Mac, Linux) it can be a bit more involved. For Linux, you only need to open a terminal in the project directory and run 'lime test linux -debug' and then run the executible file in export/release/linux/bin. For Windows, you need to install Visual Studio Community 2019. While installing VSC, don't click on any of the options to install workloads. Instead, go to the individual components tab and choose the following:

MSVC v142 - VS 2019 C++ x64/x86 build tools
Windows SDK (10.0.17763.0)
C++ Profiling tools
C++ CMake tools for windows
C++ ATL for v142 build tools (x86 & x64)
C++ MFC for v142 build tools (x86 & x64)
C++/CLI support for v142 build tools (14.21)
C++ Modules for v142 build tools (x64/x86)
Clang Compiler for Windows
Windows 10 SDK (10.0.17134.0)
Windows 10 SDK (10.0.16299.0)
MSVC v141 - VS 2017 C++ x64/x86 build tools
MSVC v140 - VS 2015 C++ build tools (v14.00)
This will install about 22GB of crap, but once that is done you can open up a command line in the project's directory and run lime test windows -debug. Once that command finishes (it takes forever even on a higher end PC), you can run FNF from the .exe file under export\release\windows\bin As for Mac, 'lime test mac -debug' should work, if not the internet surely has a guide on how to compile Haxe stuff for Mac.

Taken from `README.md`

**Comment by bigboie22** [comment]
hey actuallyasmartname i installed indows 10 sdk and visual studio but how do i download MSVC v142 - VS 2019 C++ x64/x86 build tools (Latest)

**Comment by VMGuy23** [comment]
From the individual components section...

**Comment by bigboie22** [comment]
wat send me a link to dat

**Comment by bigboie22** [comment]
hey i installed it all it still says it

**Comment by ToyLopGo** [comment]
hey you write a "lime setup windows" if this to write "lime test windows". "lime setup windows" is a install haxe and haxelib.
Please dont ask me. I dont speak English
