### ISSUE TITLE
error: al dar a una opcion de story mode, kick starcher, opcion, free play; se vuelve a la pantalla de inicio

### ISSUE THREAD

**Issue by alexsamuel159156** [FunkinCrew/Funkin#1064]
al dar a una opcion de story mode, kick starcher, opcion, free play; se vuelve a la pantalla de inicio
ayuda que hago.?😭😭😭😭😭😭😭😭

**Comment by nickpythonluajava** [comment]
> al dar a una opcion de story mode, kick starcher, opcion, free play; se vuelve a la pantalla de inicio
> 
> ayuda que hago.?😭😭😭😭😭😭😭😭

> when you click on a story mode option, **kick starcher**, option, free play; you are returned to the home screen
> 
> help what do I do.?😭😭😭😭😭😭😭😭

what button did you press?
(too lazy to translate into Spanish)

**Comment by Windows1Door2Daniel** [comment]
> > al dar a una opcion de story mode, kick starcher, opcion, free play; se vuelve a la pantalla de inicio
> > ayuda que hago.?😭😭😭😭😭😭😭😭
> 
> > when you click on a story mode option, **kick starcher**, option, free play; you are returned to the home screen
> > help what do I do.?😭😭😭😭😭😭😭😭
> 
> what button did you press?
> (too lazy to translate into Spanish)

he litteraly pressed every menu button bruh
