### ISSUE TITLE
Enhancement: Use github CI to automate build for platforms such as Linux

### ISSUE THREAD

**Issue by miacate** [FunkinCrew/Funkin#1065]
I've noticed that the linux build is very outdated on the itch.io page, I can understand the reason why, since producing a linux build outside of linux can be hard. I think I possible fix to this and (#602) is to use some form a CI that would automatically build binaries and upload them to the github release page or even itch.io

**Comment by ThatGeekyWeeb** [comment]
I've made a fork and am working on setting up a CI, I'll submit it as a PR once it actually works!
