### ISSUE TITLE
Bug Report: Chromebook performance issues

### ISSUE THREAD

**Issue by wellsilver** [FunkinCrew/Funkin#1066]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Chrome (Chrome operating system)
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
N/A using browser
## What version of the game are you using? Look in the bottom left corner of the main menu.

Latest on itch.io

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

To reproduce the bug, use any low end device with a chromebook operating system. I've looked everywhere and it seems that this even happens on high end chrome books too.

## Please describe your issue. Provide extensive detail and images if possible.

FPS is extremely unstable, from freezing every second to the characters going really fast to catch up (0-8 fps)
just generally very slow performance

I dont know why, but with mods that remove alot of stuff it performs alot better.

## info

Anybody who reads this issue and has access to meta flixel please test it and see if this is a engine issue instead of a game issue.

**Comment by VMGuy23** [comment]
in the Newgrounds version the performance is way better, try there

**Comment by Steviegt6** [comment]
> Trust me, double performance i got when my graphics drivers werent working. ng has hugeperformance improvements

If @wellsilver has actually tested as well and saw no notable results, then it probably means it's more contextual/situational.

**Comment by catnotadog** [comment]
odd, I'm on Chromebook and it works fine, except for the characters being black square box voids it performs pretty well

**Comment by 4techguns** [comment]
> except for the characters being black square box voids it performs pretty well

That seems to indicate the game running out of memory. Pull request #1083 confirms this, but has yet to be merged into the main branch.
