### ISSUE TITLE
characters are black boxes as of last update

### ISSUE THREAD

**Issue by catnotadog** [FunkinCrew/Funkin#1077]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
both
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
I've tried chrome (64 bit chromebook) which worked fine, brave (emulated arm with arc on chromebook), and firefox (on an arm device)
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
its only been happening with the week 7 update
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
it seems to happen on both chrome os and linux, and i noticed the game uses fla files now, that might be the problem, chromebooks and linux may not be able to load the fla files
## Please describe your issue. Provide extensive detail and images if possible.
as of the last update on my raspi 4(arm) the characters became black boxes though the game worked fine
(its working again on chrome (64 bit))
its broken on both arm devices/containers.
so, the game is broken on arm devices. therews your answer, find a fix to make it work on arm

**Comment by VMGuy23** [comment]
Depends on the amount of RAM you have. A 4GB RAM Pi 4 won't work but a PC with 8GB or more should work fine.

**Comment by PurpleButNotALight** [comment]
Yes, this happens due to insufficent RAM. Try applying  #1083.
