### ISSUE TITLE
Bug Report: game cant compile and gives this message:

### ISSUE THREAD

**Issue by OMGcheese997** [FunkinCrew/Funkin#1081]
Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command

How do I fix?

**Comment by VMGuy23** [comment]
Have you unzipped the source code and navigated in the command prompt to the folder with the source code in?

**Comment by OMGcheese997** [comment]
yes?. i use powershell like the tutorials i watched. but i used it in the main folder.

**Comment by VMGuy23** [comment]
What do you mean "in the main folder"? You need it to be _in the source code folder_

**Comment by OMGcheese997** [comment]
like the folder with the readme, and the other folders. I resolved it, now it says "You must have a "project.xml" file or specify another valid project file when using the 'test' command".

**Comment by VMGuy23** [comment]
Try redownloading

And here is the only place, not itch

**Comment by DomixGit** [comment]
I ran into this quote and quote bug, but its actually about the name of the file in the source code. because its "Project".xml, but you have to rename that file to "project".xml
