### ISSUE TITLE
Bug Report:  i can't compile debug stuff.

### ISSUE THREAD

**Issue by sebby09559** [FunkinCrew/Funkin#1088]
it says it has done compiling and when i go to check it there is no htm debug or exe file debug

**Comment by ACrazyTown** [comment]
What exactly are you doing? Does the game launch in your browser with the url `localhost:3000` when you run `lime html5 -debug`?

**Comment by sebby09559** [comment]
it dose not open up in local host:300 becaus i go to the art folder to do compile the game my self it just dose not make a html fille

**Comment by sebby09559** [comment]
how am i even ment to do urn lime html5 - debug how do i do that?

**Comment by Steviegt6** [comment]
The README should detail all important details regarding compilation. Anything missing can be inferred given the context already provided.

**Comment by Steviegt6** [comment]
Furthermore, if you can't figure this all out, why do you need to compile manually? You can play vanilla FNF in your web browser and most mods are either out-of-the-box or rely on an out-of-the-box engine.

**Comment by sebby09559** [comment]
im trying to add mid song events to my fnf mods but i can't press f2 in debug menu to open somthing up

**Comment by sebby09559** [comment]
the error says 
![image](https://user-images.githubusercontent.com/42832765/118391129-4e819780-b665-11eb-86d7-d1a134ab53b3.png)

**Comment by ACrazyTown** [comment]
You're not supposed to run that command, I'm pretty sure that's just meant for ninjamuffin so compilation & uploading is easier.
All you have to do to compile it is open command prompt in the directory of the game (with the Project.xml) and run lime test html5 -debug
