### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by Windows1Door2Daniel** [FunkinCrew/Funkin#1097]
GG

can the game have a song progress bar to see your progress of the song

y'know like the youtube progress bar in a video

https://youtu.be/dQw4w9WgXcQ the progress bar in this video i mean

**Comment by B-Si** [comment]
Progress bar...
@Windows1Door2Daniel Yes i like Progress bar
ninjamuffin99: ok.

**Comment by Windows1Door2Daniel** [comment]
> Progress bar...
> @Windows1Door2Daniel Yes i like Progress bar
> ninjamuffin99: ok.

Yes i like Progress bar

**Comment by aflacc** [comment]
> > Progress bar...
> > @Windows1Door2Daniel Yes i like Progress bar
> > ninjamuffin99: ok.
> 
> Yes i like Progress bar

Yes i like Progress bar

**Comment by ACardboardBox1** [comment]
> 
> 
> Progress bar...
> @Windows1Door2Daniel Yes i like Progress bar
> ninjamuffin99: ok.

wtf

**Comment by GOOBOZA** [comment]
gometry dash. anyway it will have psych engine
