### ISSUE TITLE
Question: How to get Console off my screen

### ISSUE THREAD

**Issue by arthurmelton** [FunkinCrew/Funkin#1103]
## What is your question?
so I first want to say I am on Linux and I did manually compile from the newest release, so idk if that has anything to do with it but how can I get the console, log, watch, tools, and stats off my screen
![image](https://user-images.githubusercontent.com/29708070/118365049-172dc080-b569-11eb-8da6-e24e2cd09f01.png)

**Comment by windows10win7posreadywoeskio** [comment]
Press F2
Idk bout linux yet

**Comment by VMGuy23** [comment]
F2 everywhere. Linux has F keys too!

**Comment by trayfellow** [comment]
remove the -debug when compiling
