### ISSUE TITLE
Enhancement: Enable discussions

### ISSUE THREAD

**Issue by ThePlank** [FunkinCrew/Funkin#1104]
Title says it all. The reason for this is because there are too fucking many issues that arent reporting anything wrong with the game or source code. Here are many examples of this
#1090, #1102, #1099, #1093, #1100, #1098, #1094, #1092 
Literally made by the same person. This is really needed for pepole like this.

**Comment by VMGuy23** [comment]
Good idea

**Comment by B-Si** [comment]
FUCKIN' YOU'RE PERSON THEPLANK

**Comment by nickpythonluajava** [comment]
> FUCKIN' YOU'RE PERSON THEPLANK

oh ok

**Comment by prokube** [comment]
> FUCKIN' YOU'RE PERSON THEPLANK

oh ok
