### ISSUE TITLE
Question: New rule and its license conflict

### ISSUE THREAD

**Issue by htv04** [FunkinCrew/Funkin#1105]
## What is your question?
So, I noticed that in the latest commits, starting with [this one](https://github.com/ninjamuffin99/Funkin/commit/2918ad1aefafdd1450dd4e86f7a7795dfb8189fd), the following message was added to the README:
```
IF YOU MAKE A MOD AND DISTRIBUTE A MODIFIED / RECOMIPLED VERSION, YOU MUST OPEN SOURCE YOUR MOD AS WELL
```

However, the license Funkin's code is under, the Apache License, allows for closed source distribution, with the primary condition being that the license must be distributed with any derivative works.

I'm not saying I'm against forcing mod makers to distribute their source code but... can you?

First, if you're planning to enforce this rule, I would suggest changing the license to something like the GNU GPL v3, which prohibits closed-source derivative works.

Second, it's also worth noting that the previous commits before the one you change the license on can continue to be used without source distribution because they would still be under the Apache License.

So this rule doesn't make sense at all in its current state. Future mods based on later commits would of course have to confine to the new license (if you change it) and so forth, but commits before the license change could still be used for closed source works.

**Comment by bonkmaykrQ** [comment]
If they choose to keep the big Kickstarter update under a FOSS license, then the changes between versions might be significant enough that it warrants such a restriction. On top of that, the original author of the code still has full rights and can likely relicense existing code (I'm not a lawyer so take this with a grain of salt), however existing copies that have already been given out or downloaded will maintain those rights given by the Apache license and those copies can't be enforced upon.

**Comment by HTV04** [comment]
Ninjamuffin could relicense existing commits under a new license, but such commits would still be under the Apache license, just dual-licensed with the GPL. It wouldn't really change anything because those who would want to make a closed-source mod out of these commits could just choose the Apache license over the GPL.

I'm not a lawyer either though, but I believe this is it how it works. After all, what would happen to existing mods based off of Apache commits if the license could be swapped under their authors' noses?

**Comment by namazso** [comment]
@HTV04 correct, that is how it works. It's explicitly specified that rights granted are irrevocable:
https://github.com/ninjamuffin99/Funkin/blob/master/LICENSE#L68

**Comment by Hendicted** [comment]
why not GNU AGPLv3? its almost the same as GPLv3 except it has this:
>Network use is distribution

nothing too big but yeah

**Comment by HTV04** [comment]
> why not GNU AGPLv3? its almost the same as GPLv3 except it has this:
> 
> > Network use is distribution
> 
> nothing too big but yeah

@Hendicted ...Because FNF isn't typically hosted on a server (in the way the AGPL describes)? It's a useless requirement for the game's code.

Read this for more info: https://www.gnu.org/licenses/why-affero-gpl.en.html

**Comment by Hendicted** [comment]
oh, didnt read that part whoops

**Comment by RandomErrorMessage** [comment]
There are reasons to use AGPL even on non-networked software. Video game streaming is already a thing, in which case the GPL wouldn't secure user freedom. Companies like Google have a total ban on AGPL out of paranoia that it may result in unintentional freedom being granted to users.

There's no downside to using AGPL instead of GPL, I always use it in cases where I'm going to use a copyleft license.

**Comment by HTV04** [comment]
Closed for #1106

**Comment by bonkmaykrQ** [comment]
> Ninjamuffin could relicense existing commits under a new license, but such commits would still be under the Apache license, just dual-licensed with the new license. It wouldn't really change anything because those who would want to make a closed-source mod out of these commits could just choose the Apache license over the new license.
> 
> I'm not a lawyer either, but I believe this is it how it works. After all, what would happen to existing mods based off of Apache commits if the license could be swapped under their authors' noses?

I feared this, unfortunately, anybody can just pretend that the version they got was an Apache licensed release and that devalues any relicenses.

The only way, in my opinion at least, that FNF is going to be able to successfully maintain and enforce a GPL 3 or AGPL 3 license, is if there are big enough changes going forward and all of them are using the new license.

**Comment by HTV04** [comment]
> I feared this, unfortunately, anybody can just pretend that the version they got was an Apache licensed release and that devalues any relicenses.

@bonkmaykrQ The FNF GameBanana community is planning to enforce that future mods that involve recompiling the game must have their source code available, even if the mod only used Apache commits.
