### ISSUE TITLE
Bug Report: errors when trying to build game

### ISSUE THREAD

**Issue by Lexikyu** [FunkinCrew/Funkin#1109]
Im on a windows pc. Whenever I try to build my game with lime test windows I get these errors:

source/TitleState.hx:61: characters 16-28 : Type not found : APIStuff
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

I don't know what those are in reference to or how to fix them, sorry if this has been asked about before but I've looked for like an hour atleast and can't find anything specific on this.
![Screenshot_26](https://user-images.githubusercontent.com/84256893/118383659-6cd78c80-b5ac-11eb-9fa4-7cd95c0273e8.png)

**Comment by Rs232k** [comment]
Read instructions carefully

**Comment by Steviegt6** [comment]
![image](https://user-images.githubusercontent.com/27323911/118387617-3877c680-b5d4-11eb-99a9-71059073fbe1.png)

**Comment by BDMCGaming** [comment]
I have this same issue. I followed the instructions in the readme file. It didn't work though.

**Comment by nickpythonluajava** [comment]
Add a new file in `source` and name it `APIStuff.hx` and put this code in it:

```haxe

package;

class APIStuff
{
	public static var API:String = "";
	public static var EncKey:String = "";
}

```

**Comment by BDMCGaming** [comment]
I said that I already made the file. It still happens.

**Comment by VMGuy23** [comment]
> I said that I already made the file. It still happens.

Can you paste the exact output?

**Comment by BDMCGaming** [comment]
I can't do it right now because I'm on vacation. I can do it when I get
back.

**Comment by thebopee** [comment]
u can ignore them but i dont know how to

**Comment by ItzaNoobxd** [comment]
i try to build the game with the APIStuff.hx thing, and the game crashes when it finishes building
