### ISSUE TITLE
Enhancement: Separate all the icons into their own images

### ISSUE THREAD

**Issue by waspennator** [FunkinCrew/Funkin#1112]
## What is your suggestion, and why should it be implemented?
Currently at the moment, all the icons are glomped together in one big grid image, which works, but it leaves very little flexibility if one wanted to have multiple mods and had to either pick which character gets their icon or not, unless you'd rather try and manually do it yourself.

After seeing the Tankman Ugh Siivagunner mod and looking at how the icons are setup there (Only the two character specific icons in a single image), I feel as though it would be beneficial to split up the icons into their own separate image for each character (Winning and losing icons), not only to make it easier to specify icons for certain characters, but also making it so one doesn't have to choose which character icon to use mod wise.

**Comment by PrincessMtH** [comment]
this is already how it is in week 7 update

**Comment by waspennator** [comment]
> this is already how it is in week 7 update

Alright then, just wanted to confirm since I wasn't sure how the coding for week 7 was going along and I wanted to know for sure if the Siivagunner ugh mod was how the week 7 version was actually gonna be.

**Comment by GOOBOZA** [comment]
fucker
