### ISSUE TITLE
what do I do?

### ISSUE THREAD

**Issue by jmastermills** [FunkinCrew/Funkin#1114]
It says Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command what do I do

**Comment by EyeDaleHim** [comment]
You gotta run the command in the directory: "\Funkin-master"

or run the command where Project.xml is in.

**Comment by jmastermills** [comment]
ok thanks

**Comment by jmastermills** [comment]
do I put it in Windows PowerSell

**Comment by nickpythonluajava** [comment]
> do I put it in Windows PowerShell

you can do it in powershell or terminal but i use powershell

**Comment by jmastermills** [comment]
ok thanks
