### ISSUE TITLE
Bug Report: compile stuff 2

### ISSUE THREAD

**Issue by nickplj12** [FunkinCrew/Funkin#1115]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
github
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
edge
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
windows x86_64
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1 (idk actually probably not full release just working on it maybe idk ewfhdhfiuwhue)
## Please describe your issue. Provide extensive detail and images if possible.

when i compile using `lime test html5 -debug` it opens up `localhost:3000` and works fine.
<img width="960" alt="localhost" src="https://user-images.githubusercontent.com/78268270/118489267-a57d8000-b6ea-11eb-8914-8b90b271b838.PNG">

when i go to `\project\export\release (or debug)\html5\bin\index.html` it's stuck on the haxeflixel screen and the logo doesnt even appear

**Comment by VMGuy23** [comment]
Yeah probably HaxeFlixel/Lime issue

**Comment by NotHyper-474** [comment]
Had this same error after getting Week 7 files and trying to run it, if you go to Inspector mode (Ctrl+Shift+I on Windows) and look at the console you'll see some loading errors.

Looks like browsers don't like loading json files by opened html files, I managed to fix it by making a local server with Xampp. Hope HaxeFlixel/Lime fixes this

**Comment by nickpythonluajava** [comment]
well i managed to fix it by uploading to itch.io or  some other web hosting site works i guess
