### ISSUE TITLE
Tip to install the game without a file extractor app

### ISSUE THREAD

**Issue by Windows1Door2Daniel** [FunkinCrew/Funkin#1120]
1. Download the game at https://ninja-muffin24.itch.io/funkin. 
or if you want to download a mod. The best idea is download at https://gamebanana.com/games/8694

2. Search the file downloaded (Most people put the game at "Downloads" since is the default location

3. Rigth click the .Zip folder and select "Extract all" and select the location you want the files go

4. Open the folder extracted (It opens after the extraction ends)

Open the game after these useless instructions

PD: Your PC open a warning when you try to open the game and prevents to you start the game. press "More information" then "Open anyways" and the warning wont appear again

I just wasted my time to write a Tutorial that no one gonna read

I someone read this the that someone it sure have the game instalated

**Comment by VMGuy23** [comment]
Note: is "Extract Here" when using Nautilus (Ubuntu file manager/Files)

**Comment by NTS-YT** [comment]
I always do this when other youtubers flex their file extractor apps. I just avoid their instructions with winrar or something and use my infinite iq play, using the extract all tool

**Comment by VMGuy23** [comment]
Who needs WinRAR?
7-zip does pretty much the same job, and
on Linux there's plenty of choice.
