### ISSUE TITLE
adding custom character to the game 

### ISSUE THREAD

**Issue by SuperSpinDashGamer39** [FunkinCrew/Funkin#1121]
ok so when I used the free play menu to select my custom character and after it "loads" it crashes I edited the skid and pump assets  and coded them in  and they wont work can someone send me their version of their code

**Comment by hehehehehehehehehehehehehehehehehehe** [comment]
i have this problem too

**Comment by Rs232k** [comment]
What a free play menu? It's charting menu?

**Comment by nickpythonluajava** [comment]
> What a free play menu? It's charting menu?

Bruh

**Comment by SuperSpinDashGamer39** [comment]
> What a free play menu? It's charting menu?

yes ik typo

**Comment by nickpythonluajava** [comment]
anyways worked for me

- copy and paste your character in the game
- go to the .xml file and replace "spooky" with your character's name (or maybe "note" idk)
- go to healthicon.hx and copy and paste the dad icon to another line (or import an icon)
- go to character.hx and press ctrl+f to find your character's animation code
- once you found that you can copy and paste the code
- replace the "spooky" and probably "note" with the character name yet again

and everything should work fine

also, there's some extra code for skid and pump
- yeah copy and paste that and replace spooky with your characters name
