### ISSUE TITLE
I Cant Play

### ISSUE THREAD

**Issue by MarioEmbon** [FunkinCrew/Funkin#1122]
basically, i been playing for a long while, the original game and some mods, but today i woke up and i cant open the game, it opens for 2 seconds and then it closes, i rebooted/restarted the pc 6 times, i tried uninstalling my anti virus, can yall help me?

**Comment by foxsouns** [comment]
Elaborate. What version?

**Comment by MarioEmbon** [comment]
latest windows 10 version x64 bits

**Comment by VMGuy23** [comment]
FNF version?

**Comment by MarioEmbon** [comment]
> 
> 
> FNF version?

how do i check

**Comment by MarioEmbon** [comment]
> 
> 
> FNF version?

latest windows 10 version x64 bits

**Comment by MarioEmbon** [comment]
> 
> 
> Elaborate. What version?

latest windows 10 version x64 bits

**Comment by VMGuy23** [comment]
Top of changelog.txt - first release that shows up there

**Comment by MarioEmbon** [comment]
> Top of changelog.txt - first release that shows up there

0.2.7.1, also ty for trying to help i tried in other web sites and nobody helped

**Comment by foxsouns** [comment]
you have a x64 compatible system, right? you wouldnt happen to be using a 32 bit computer or anything?

**Comment by MarioEmbon** [comment]
> you have a x64 compatible system, right? you wouldnt happen to be using a 32 bit computer or anything?

Ofc my pc is 64 and ofc im using the x64 bits version of the game i tried using the other one but ofc didnt work

**Comment by foxsouns** [comment]
okay: maybe a bad download? try deleting the game and redownloading it from itch.

**Comment by MarioEmbon** [comment]
> okay: maybe a bad download? try deleting the game and redownloading it from itch.

I already redownloaded it like 7 times, also a recorded a vid imma add it as an answer of this

**Comment by MarioEmbon** [comment]
> > okay: maybe a bad download? try deleting the game and redownloading it from itch.
> 
> I already redownloaded it like 7 times, also a recorded a vid imma add it as an answer of this

https://youtu.be/wFL4Wu-oSqI

**Comment by foxsouns** [comment]
oh cool; that'll probably help us help you.

**Comment by foxsouns** [comment]
best i can offer is that maybe save data got corrupted or something
IDR the location off the top of my head, but ill look real quick

**Comment by MarioEmbon** [comment]
Alr, also in the video it didnt show cuz i had a problem recording the vid but i also tried running at as administrator, also when the problem started i was playing normally and the game crashed, then it stopped working as u know

**Comment by foxsouns** [comment]
sounds like save data broke; ik it's somewhere, possibly in %appdata%\
look around, im looking for anything in this repo that explicitly states where it's at

**Comment by foxsouns** [comment]
try looking for whatever folder has stuff named "FlxG.save.data" and the like, and (if it makes sense) delete the folder it's in, try running it again

**Comment by MarioEmbon** [comment]
> try looking for whatever folder has stuff named "FlxG.save.data" and the like, and (if it makes sense) delete the folder it's in, try running it again

Alr man tysm i really passed hours asking to people on other websites, ill try this tmrw cuz its 11 pm here im writing this on my phone but tysm

**Comment by foxsouns** [comment]
kk
good luck, ill check back tomorrow to see if you've got this fixed via my suggestion

**Comment by MarioEmbon** [comment]
> 
> 
> kk
> good luck, ill check back tomorrow to see if you've got this fixed via my suggestion

well man. i searched four around of an hour and im not finding it, i tried using an special program for finding specific files and nothing, any other idea?

**Comment by foxsouns** [comment]
I'm gonna install it myself later on a vm, and look for the file.

**Comment by MarioEmbon** [comment]
> 
> 
> I'm gonna install it myself later on a vm, and look for the file.

arl

**Comment by ItzRiotz** [comment]
how about you try to open it in cmd, so you'd cd to the directory that 'Funkin.exe' is in and run it by typing in the executable name (in this case, you'd type in Funkin.exe)
it should tell you at least something, maybe ;(

**Comment by MarioEmbon** [comment]
> 
> 
> how about you try to open it in cmd, so you'd cd to the directory that 'Funkin.exe' is in and run it by typing in the executable name (in this case, you'd type in Funkin.exe)
> it should tell you at least something, maybe ;(

its says, the file is not an executable file

**Comment by ItzRiotz** [comment]
> > 
> > 
> > how about you try to open it in cmd, so you'd cd to the directory that 'Funkin.exe' is in and run it by typing in the executable name (in this case, you'd type in Funkin.exe)
> > it should tell you at least something, maybe ;(
> 
> its says, the file is not an executable file

Well that's the reason the file isn't opening, now to fix it, why isn't it an executable 🤔

**Comment by MarioEmbon** [comment]
> > > how about you try to open it in cmd, so you'd cd to the directory that 'Funkin.exe' is in and run it by typing in the executable name (in this case, you'd type in Funkin.exe)
> > > it should tell you at least something, maybe ;(
> > 
> > 
> > its says, the file is not an executable file
> 
> Well that's the reason the file isn't opening, now to fix it, why isn't it an executable 🤔

It is

**Comment by VMGuy23** [comment]
Check you're allowed to execute it in its properties window.

**Comment by MarioEmbon** [comment]
> .

im in the properties window but where do i check

**Comment by MarioEmbon** [comment]
> 
> 
> I'm gonna install it myself later on a vm, and look for the file.

man u alive?

**Comment by VMGuy23** [comment]
> > .
> 
> im in the properties window but where do i check

Security or something like that. Make sure you have **full control**

**Comment by foxsouns** [comment]
> > I'm gonna install it myself later on a vm, and look for the file.
> 
> man u alive?

I haven't had a computer for a bit, sorry for leaving you in the dark. I believe I can check later today for sure, though.

**Comment by foxsouns** [comment]
@MarioEmbon it's in `%appdata%/ninjamuffin99/Funkin`.

**Comment by MarioEmbon** [comment]
> @MarioEmbon it's in `%appdata%/ninjamuffin99/Funkin`.

Alr, im not at home rn but ill check it, also dont worry for not being answering, its good to know that you're back

**Comment by MarioEmbon** [comment]
> `%appdata%/ninjamuffin99/Funkin`

it says, windows cant find %appdata%/ninjamuffin99/Funkin, check the orthography and try again

**Comment by foxsouns** [comment]
put it in run (windows+r)

**Comment by MarioEmbon** [comment]
> 
> 
> put it in run (windows+r)

same result

**Comment by redbluexe0** [comment]
> > put it in run (windows+r)
> 
> same result

type in the windows run program [Win+r] %AppData%

thats it.
you will be in the roaming one but the saves are saved at local app data sooo

type %LocalAppData%
