### ISSUE TITLE
Bug Report: instadeath upon clicking the Y button for an Xbox controller

### ISSUE THREAD

**Issue by cephalie** [FunkinCrew/Funkin#1123]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by VMGuy23** [comment]
Change your controller mapping. Y must be mapped to R, which is death

**Comment by Bloopsdoob** [comment]
![image](https://user-images.githubusercontent.com/77730957/118786183-e9cc7400-b8d4-11eb-9910-abeb252841b2.png)
unfortunately this is intentional

**Comment by Windows1Door2Daniel** [comment]
Configure the controllers

unfortunaly i dont know how

**Comment by ItzRiotz** [comment]
so basically the Y button is the reset button, who could've guessed
dont press it
