### ISSUE TITLE
Lime isn't recognised when building

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1124]
I'm trying to compile the game on Windows to start work on a mod idea, but whenever I try to build the game using Windows Powershell this error appears:

![image](https://user-images.githubusercontent.com/84391034/118655908-e73d2200-b7e1-11eb-9634-536d53f67c0e.png)

I've downloaded every prerequisite from the help page, and updated APIStuff as well, but it's still coming up with this error. Anyone know what this is and how to fix it?

**Comment by Beenzy** [comment]
Just found the issue! Immediately noticed I'd forgotten the Run Lime Setup command prompt - whoops!

It's all working OK now, so that's a relief.
