### ISSUE TITLE
MY KEYS KEEP MISSING EVEN WHEN IM HITTING THEM  CORRECTLY

### ISSUE THREAD

**Issue by Peachykat22** [FunkinCrew/Funkin#1125]
There is a bug in the game, when i  miss one key it will keep making me miss several other keys after it, even though i hit those keys at the right time, its now impossible to beat a level because it makes me miss so many keys that i die after 20 seconds or less of the song!! Please can you fix this!!

**Comment by ItzRiotz** [comment]
this can't be fixed just by you saying to fix it, yknow
do you get any input latency in other games?
