### ISSUE TITLE
Bug Report: When downloading the source code and extracting I don´t get the source folder.

### ISSUE THREAD

**Issue by justgadz** [FunkinCrew/Funkin#1126]
#![image](https://user-images.githubusercontent.com/82243833/118726787-cf749680-b7ff-11eb-9e3b-2be553f55f36.png)
I´m in Windows 10, I use 7Zip to extract the files.

**Comment by justgadz** [comment]
![imagen_2021-05-18_174707](https://user-images.githubusercontent.com/82243833/118727639-10b97600-b801-11eb-8ab8-e61ad4f9a5d1.png)
This says when it finishes extracting.

**Comment by Rs232k** [comment]
Better use git clone

**Comment by nickpythonluajava** [comment]
i just use windows built in unzip feature and everything works fine

**Comment by Rs232k** [comment]
> ![imagen_2021-05-18_174707](https://user-images.githubusercontent.com/82243833/118727639-10b97600-b801-11eb-8ab8-e61ad4f9a5d1.png)
> This says when it finishes extracting.

Your downloaded file corrupted. Use git clone (recommended) or redownload.

**Comment by VMGuy23** [comment]
Did you know: the `gh` command uses `git clone` in its internals so it's not worth using `gh`

**Comment by Windows1Door2Daniel** [comment]
> i just use windows built in unzip feature and everything works fine

I dont know why no one uses that

is very usefull that i used that to install FNF and FNF Mods
