### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by TomiokaGiyuGamer** [FunkinCrew/Funkin#1127]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## Please describe your issue. Provide extensive detail and images if possible.

![imagem_2021-05-18_192004](https://user-images.githubusercontent.com/68976448/118730467-0d78b700-b80e-11eb-8bd2-0d736c22dd3d.png)
D:/Hxe/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access                                                                                                 D:/Hxe/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access                                                                                                 source/PlayState.hx:150: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead                                                                                                  C:\Users\bielz\Desktop\Mods criados por mim\Funkin-master\export\debug\windows\obj>setlocal enabledelayedexpansion      Warning: Could not find Visual Studio 2017 VsDevCmd                                                                     Missing HXCPP_VARS                                                                                                      Error: Could not automatically setup MSVC

**Comment by foxsouns** [comment]
follow these instructions, if you already havent:

For Windows, you need to install Visual Studio Community 2019. While installing VSC, don't click on any of the options to install workloads. Instead, go to the individual components tab and choose the following:

* MSVC v142 - VS 2019 C++ x64/x86 build tools (Latest)
* Windows 10 SDK (10.0.19041.0)

This will install about 4GB of crap, but once that is done you can open up a command line in the project's directory and run `lime test windows -debug`. Once that command finishes (it takes forever even on a higher end PC), you can run FNF from the .exe file under export\debug\windows\bin

**Comment by VMGuy23** [comment]
Note: does not work
have installed more than required by the way

**Comment by Maurpilous** [comment]
@foxsouns the windows sdk doesn't install

**Comment by foxsouns** [comment]
@Maurpilous i dunno dude, i usually build on linux. [setup wsl](https://learn.microsoft.com/en-us/windows/wsl/install) and then [follow the linux instructions](https://github.com/FunkinCrew/Funkin#installing-the-required-programs) but build for windows instead with `lime test windows -debug`. or ask someone else to build it for you (i dont have a developer environment for funkin anymore, and dont feel like fucking with it again)
