### ISSUE TITLE
Tankman cutscene volume

### ISSUE THREAD

**Issue by Cmonster132** [FunkinCrew/Funkin#1128]
Im playing on Newgrounds on a chrome browser. The in game volume settings affect everything except for the tankman cutscene volume for week 7 so the cutscene will be blaring loud even at 0 volume, but the songs are still quieted/muted.

**Comment by foxsouns** [comment]
I'd assume that the cutscene system they've got right now is about the hackiest thing ever to be made in HaxeFlixel, and is just a simple oversight made by the devs when creating it. The whole idea of playing a video in Flixel was never done before just a few weeks ago, with the release of Week 7, AFAIK. Meanwhile, let us leave the devs to get to this after they figure out why there's 760 open issues lol.

**Comment by InfamousK40** [comment]
The week 7 cutscenes are just mp4s and not really part of the games code that much, that's why.

**Comment by foxsouns** [comment]
Yeah; I'd assume that "Playing an MP4 in HaxeFlixel" was higher in priority than "Making sure this very small detail works on everything". I know it's inconsistent within Funkin', but what is stopping you from using your computer's way of volume?

**Comment by Windows1Door2Daniel** [comment]
> Im playing on Newgrounds on a chrome browser. The in game volume settings affect everything except for the tankman cutscene volume for week 7 so the cutscene will be blaring loud even at 0 volume, but the songs are still quieted/muted.

Thats why you have a Volume option in your PC
