### ISSUE TITLE
Bug Report: I am unable to hear audio when starting the Game on Newgrounds

### ISSUE THREAD

**Issue by NewDeveloper911** [FunkinCrew/Funkin#1130]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

I am playing the game on the newgrounds site, using Mozilla Firefox updated to the latest version at the time of writing.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

I am using Mozilla Firefox.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.

v0.2.8

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

All that I have done is open up the site on Newgrounds and try to play it with a YouTube tab in the background. Apprarently, it's the YouTube tab in the background which causes the issue.

## Please describe your issue. Provide extensive detail and images if possible.

I can run the game at about 60FPS with no other problems other than the fact that I cannot hear audio.

**Comment by VMGuy23** [comment]
Check browser settings and that the tab is unmuted. also please try the latest version of Chrome as that almost always works
