### ISSUE TITLE
Game replays but with no notes when pausing at the VERY end

### ISSUE THREAD

**Issue by BurntRanch** [FunkinCrew/Funkin#1133]
Info:
Platform:
**Windows 64bit**
browser:
**Edge**

i accidentally paused at the last frame of the song and then it replayed and there were no notes, just the song, [Here is the video.](https://drive.google.com/file/d/1dHKJf0Dn8rT9Mywt6v7xkkKbm4Oq3DJ2/view?usp=sharing)

**Comment by VMGuy23** [comment]
I did that once.

**Comment by ninjamuffin99** [comment]
interesting
