### ISSUE TITLE
Bug Report: Missingo for characters in the newgrounds build.

### ISSUE THREAD

**Issue by GrumpyKitten2** [FunkinCrew/Funkin#1134]
The bug has appeared when pressing esc key on the restart screen when selecting restart.
When then going back to week 1 the screen is completely black apart from notes and a low frame rate.
After restarting the song, everything else became normal apart from the characters.

https://user-images.githubusercontent.com/84471283/118865778-39ad3a00-b8d9-11eb-9b54-73b7b2709ede.mp4

**Comment by brandoge91** [comment]
this happens to me when I build my engine mod for HTML5. it is annoying and I would love for this to be fixed.
