### ISSUE TITLE
You have not specified in your license that i cant sue you if you are liable for damages

### ISSUE THREAD

**Issue by Teh404Gal** [FunkinCrew/Funkin#1135]
i want 300 dollars for slow game
now

**Comment by VMGuy23** [comment]
BRO THIS ISN'T DAMAGE
I DIDN'T SUE EPIC GAMES FOR 45 FPS
SERIOUSLY
h

**Comment by teh404guy** [comment]
calm down retard, its just a joke

**Comment by VMGuy23** [comment]
Yeah  still tho dont clog up the issue tracker
like @B-Si did

**Comment by teh404guy** [comment]
ok thenks gonna close this

**Comment by VMGuy23** [comment]
Thanks
