### ISSUE TITLE
Bug Report: Corrupt Main Menu Song

### ISSUE THREAD

**Issue by SenorLing** [FunkinCrew/Funkin#1136]
[Newgrounds] https://www.newgrounds.com/portal/view/770371

### If you are playing the game in a browser, what browser are you using?
Chrome

## What version of the game are you using? Look in the bottom left corner of the main menu.
V.0.2.8(Newgrounds exclusive preview)

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

When changing the difficulty on any song and instantly going back to the main menu, the main menu song is corrupt.

Another bug I found was when idling in the main menu screen, eventually, the main menu song will get corrupt again. (After approximately 1 minute 50 seconds.) If waiting on the loading screen vvvv
![image](https://user-images.githubusercontent.com/65788589/118880891-500fc180-b8ea-11eb-9abd-6a2bbff45759.png)
The game will force the ending of week 7 (the cutscene) and when you try to skip it will restart the cutscene.

Update - I just went into a song, (Ugh) and when I came out of it without changing difficulties, the menu song was corrupt.

**Comment by s-zenmode** [comment]
Damn, i did it and it gave me the kickstarter ad. Interesting bug tbh.

**Comment by catte-cloud** [comment]
i feel like this is just haxeflixels code engine sucking major weenor and not a bug
