### ISSUE TITLE
Bug Report: Boyfriend animation frozen after holding single arrow

### ISSUE THREAD

**Issue by NTS-YT** [FunkinCrew/Funkin#1139]
Just thought I would casually play some Friday Night Funkin' just now and found a weird bug...

Once I hit the arrow, if I continue to hold the arrow, Boyfriend freezes in animation (with whatever arrow direction) and will only resume his idle animation if I let go.

Not really a "game damaging" bug but still pretty cool and weird.

Video of bug in action: https://drive.google.com/file/d/15gSpQk6ya5YnWmXps6x3VRZ6L_eLS8M4/view?usp=sharing

Edit: Bug works on any version (as I'm writing this, I'm using the Windows 0.2.7.1 release), Itch or Newgrounds, any Windows version, Mac, and Linux. IT ALL WORKS.

Thanks for a great game, Ninja Muffin, but I think my brain will keep making me do this until it is patched

**Comment by Windows1Door2Daniel** [comment]
its not a bug

its just you shouldnt hold a arrow that you shouldnt hold

**Comment by NTS-YT** [comment]
> its not a bug
> 
> its just you shouldnt hold a arrow that you shouldnt hold

@Windows1Door2Daniel if im still holding an arrow, and press another directional arrow (while still holding), it will change direction, but remain a frozen first-frame animation.

**Comment by NTS-YT** [comment]
It's almost as if I'm fighting my brain to not want to do this now that I found this.

Even if it was an arrow you should hold, the character performing the action always moves a section of their body while singing that note. Boyfriend just freezes in place in the direction it should go if it is a note you shouldn't hold, but you hold it anyway.

**Comment by Windows1Door2Daniel** [comment]
> It's almost as if I'm fighting my brain to not want to do this now that I found this.
> 
> Even if it was an arrow you should hold, the character performing the action always moves a section of their body while singing that note. Boyfriend just freezes in place in the direction it should go if it is a note you shouldn't hold, but you hold it anyway.

Yeah

i said that you shouldnt hold the normal arrows and thats intentional to the game (Maybe by NinjaMuffin being lazy)

**Comment by NTS-YT** [comment]
> Yeah
> 
> i said that you shouldnt hold the normal arrows and thats intentional to the game (Maybe by NinjaMuffin being lazy)

hmm, I guess that's why Mr. Dearest seems to freeze his face position in some points of the "Bopeebo" song.

**Comment by Windows1Door2Daniel** [comment]
> > Yeah
> > i said that you shouldnt hold the normal arrows and thats intentional to the game (Maybe by NinjaMuffin being lazy)
> 
> hmm, I guess that's why Mr. Dearest seems to freeze his face position in some points of the "Bopeebo" song.

Yah
