### ISSUE TITLE
Bug Report: plays instrumental instead of the normal song 

### ISSUE THREAD

**Issue by NoisyFoisy** [FunkinCrew/Funkin#1140]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by NTS-YT** [comment]
I need more context to see if I can help. What song are you trying to do anyway, and is it on a mod?

**Comment by NTS-YT** [comment]
Check the game files. If it is through chrome, I can't really help you with that. If it is a downloadable copy, check to see if the voices file is still somewhere in the games files. If it isn't, then that's your reason.

**Comment by NoisyFoisy** [comment]
it is in newgrounds itself the song i was specifically playing was pico and
not a mod
