### ISSUE TITLE
Bug Report: it crashes when i try to play ugh on easy

### ISSUE THREAD

**Issue by 07mmcgrath** [FunkinCrew/Funkin#1141]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
the newest one
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
just do ugh on easy

**Comment by Windows1Door2Daniel** [comment]
maybe the JSON file didnt load

**Comment by TheGamingTime** [comment]
how tf do you even get a downloadable version of week 7 or the source code itself

**Comment by 07mmcgrath** [comment]
it isnt working on newgrounds
