### ISSUE TITLE
My Screen White

### ISSUE THREAD

**Issue by FrostTaks** [FunkinCrew/Funkin#1142]
im having problem with my fnf.exe,first i download from idm and extracxt and i run it,but just show white screen but sound normal
im using windows 10 64bit and im download in firefox not chrome,im entirely trying to fix it but how?
im trying connect graphics card to the game but doesnt work
![bandicam 2021-05-20 12-22-22-329](https://user-images.githubusercontent.com/84491971/118923667-1e3c4080-b966-11eb-9a38-a2fca5226908.jpg)

specification:
Intel i7-2630QM 2.00 ghz
ram 4gb
graphics card:intel hd graphics and nvidia nvs 4200M
Product Lenovo thinkpad T420
type:laptop

**Comment by Windows1Door2Daniel** [comment]
where you downloaded the game

**Comment by VMGuy23** [comment]
Download from ninja-muffin99.itch.io/funkin and nowhere else

**Comment by FrostTaks** [comment]
im really download from real website

**Comment by FrostTaks** [comment]
But doesnt work

**Comment by VMGuy23** [comment]
Strange.

**Comment by flaying-toilet-seat** [comment]
i have the same problem

**Comment by VMGuy23** [comment]
how much ram do you have? also check how much is being used before running the game

**Comment by FrostTaks** [comment]
@VMGuy23 i have 4gb ram and i try 3 times yesterday

**Comment by actuallyasmartname** [comment]
> @VMGuy23 i have 4gb ram and i try 3 times yesterday

you need moar ram to run the game correctly I think

**Comment by VMGuy23** [comment]
> > @VMGuy23 i have 4gb ram and i try 3 times yesterday
> 
> you need moar ram to run the game correctly I think

Yep

**Comment by FrostTaks** [comment]
how much ram i need to play the fnf game

**Comment by VMGuy23** [comment]
Probably at least 8GB

**Comment by Windows1Door2Daniel** [comment]
> Probably at least 8GB

So

if i need 9 GB to play among us and Friday nigth funkin at the same time? (Well i cant play them at the same time but have runing the game yes) dang my RAM is 10 GB but my OS Processes are using 1 GB leaving 9 GB usable

**Comment by FrostTaks** [comment]
@Windows1Door2Daniel why you overclocking your ram?

**Comment by FrostTaks** [comment]
also can play fnf in 6144 mb? (2gb + 4gb)

**Comment by FrostTaks** [comment]
@Windows1Door2Daniel  i mean why you not overclocking your ram?

**Comment by Windows1Door2Daniel** [comment]
> @Windows1Door2Daniel i mean why you not overclocking your ram?

i didnt know i was doing that
