### ISSUE TITLE
Bug Report: Game crashes if I try to swap characters on Debug Menu

### ISSUE THREAD

**Issue by kesiag** [FunkinCrew/Funkin#1145]
I'm making a mod, and I tried to swap my character on the debug menu and the game crashed. At first I thought it was a problem with my character, but then I tried to swap other characters from the game and the game still crashes. No error message pops up, it just closes by itself.

The version I'm using is the downloaded version, the one from the source code, which is v2.7.1, on windows.

**Comment by VMGuy23** [comment]
Does trying to change into Pico crash?

**Comment by kesiag** [comment]
Yes, It crashes with any character

**Comment by Rs232k** [comment]
It's broken. Fixed in New week afaik.
