### ISSUE TITLE
source/PlayState.hx:298: characters 16-36 : Cannot rebind this method : please use 'dynamic' before method declaration

### ISSUE THREAD

**Issue by AshuraTheEchidna** [FunkinCrew/Funkin#1146]
i got another error, great, here ill put the file so anybody can tell me whats wrong, and yes, i tried to put dynamic and it didnt worked
[PlayState.txt](https://github.com/ninjamuffin99/Funkin/files/6518880/PlayState.txt)

**Comment by ItzRiotz** [comment]
could you please specify the method?

**Comment by VMGuy23** [comment]
```haxe
		FlxG.cameras.setDefaultDrawTarget = [camGame];
```

**Comment by AshuraTheEchidna** [comment]
> could you please specify the method?

FlxG.cameras.setDefaultDrawTarget = [camGame];

**Comment by VMGuy23** [comment]
Add `Dynamic ` to the start

**Comment by AshuraTheEchidna** [comment]
> Dynamic

now it says: `source/PlayState.hx:298: characters 11-15 : Missing ;`

**Comment by VMGuy23** [comment]
Use Haxe 4.1.5 or 4.2.1/later

**Comment by AshuraTheEchidna** [comment]
> Use Haxe 4.1.5 or 4.2.1/later

i used 4.1.5 then 4.2.1 and it still didnt worked

**Comment by VMGuy23** [comment]
Reinstall Haxe.

**Comment by AshuraTheEchidna** [comment]
> Reinstall Haxe.

ok, ill tell you if it works or not

**Comment by AshuraTheEchidna** [comment]
> Reinstall Haxe.

it didnt worked, it gave me the same error
