### ISSUE TITLE
Bug Report:  whenever I try to play week 7 on Friday night funkin it doesn't pop up its just all black I ve tried to reset it and retry but it does the same thing

### ISSUE THREAD

**Issue by ltizatl9** [FunkinCrew/Funkin#1147]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by s-zenmode** [comment]
uh you didn't exactly answer any of the questions given in the template??

**Comment by VMGuy23** [comment]
_Can_ be a RAM issue. I have 1GB of RAM on my secondary machine and it won't load FNF

**Comment by ltizatl9** [comment]
oh im sorry i apologize i didnt see them ill go and answer them
