### ISSUE TITLE
Enhancement: lime test neko

### ISSUE THREAD

**Issue by nickplj12** [FunkinCrew/Funkin#1148]
## What is your suggestion, and why should it be implemented?
Add support for Neko, I installed VS Community 2019 but the free trial ended before I could install the dependencies and I probably can reinstall it but the trial message would still be up so yeah that's the end of this completely useless paragraph this sounded a lot better in my head

**Comment by HTV04** [comment]
The 30-day trial period is only for users who didn't connect VS2019 to their Microsoft account if I recall correctly. Do you have a Microsoft account? Try signing in to VS with it.

**Comment by VMGuy23** [comment]
Yeah i was at first confused about license thing. That is the way.

**Comment by nickpythonluajava** [comment]
> The 30-day trial period is only for users who didn't connect VS2019 to a Microsoft account if I recall correctly. If you have a Microsoft account, try signing in to VS with it.

Ahhh ok
