### ISSUE TITLE
Bug Report: compiling

### ISSUE THREAD

**Issue by bacc-studio** [FunkinCrew/Funkin#1151]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below. I compiled

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify below.
Edge
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86-64
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Make a new week
2. That's it
## Please describe your issue. Provide extensive detail and images if possible.
When I compile with a new week the story menu only shows 2 songs but with Tutorial it doesnt show up at all

<img width="814" alt="tut" src="https://user-images.githubusercontent.com/83874068/119165624-b2241000-ba2b-11eb-89b1-1a07b4bfd74f.PNG">
<img width="814" alt="whadwf" src="https://user-images.githubusercontent.com/83874068/119165643-b6502d80-ba2b-11eb-9944-049b07c9dc6c.PNG">

**Comment by aflacc** [comment]
can you send the code of `StoryMenuState.hx` to a [PasteBin](https://pastebin.com/)? I have a idea on what could be happening

**Comment by aflacc** [comment]
I can try and help you if you put it in something I can use to read it

**Comment by bacc-studio** [comment]
@aflacc 


[Le code](https://pastebin.com/raw/yfeydr6t)

**Comment by Rs232k** [comment]
Try haze version 4.1.5

**Comment by ACrazyTown** [comment]
IIRC this issue was reported a few times, #761 and #932 to name a few. A workaround by @rifxii is to install OpenFL via git, `haxelib git openfl https://github.com/openfl/openfl`

**Comment by VMGuy23** [comment]
> Try haxe version 4.1.5

Not neccesary. 4.2.1 works fine.

**Comment by Rs232k** [comment]
> > Try haxe version 4.1.5
> 
> Not neccesary. 4.2.1 works fine.

4.2.2 too

**Comment by VMGuy23** [comment]
wait that exists?

**Comment by ACrazyTown** [comment]
> wait that exists?

yeah, 4.2.2 got released recently i think

**Comment by VMGuy23** [comment]
oh cool

**Comment by nickpythonluajava** [comment]
> IIRC this issue was reported a few times, #761 and #932 to name a few. A workaround by @rifxii is to install OpenFL via git, `haxelib git openfl https://github.com/openfl/openfl`

worked, closing

**Comment by bacc-studio** [comment]
> IIRC this issue was reported a few times, #761 and #932 to name a few. A workaround by @rifxii is to install OpenFL via git, `haxelib git openfl https://github.com/openfl/openfl`

this worked, closing
