### ISSUE TITLE
Bug Report: Black Freeplay Screen on source code version

### ISSUE THREAD

**Issue by flustix** [FunkinCrew/Funkin#1155]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

Browser

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

Chrome

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows (`x64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.

2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

Enter Freeplay on Source Code version

## Please describe your issue. Provide extensive detail and images if possible.

When trying to enter Freeplay on the source code version, i just get a black screen.
The Menu music is still playing in the Background
![image](https://user-images.githubusercontent.com/65369281/119223060-938b4b00-baf7-11eb-8fdb-553d0f96f085.png)

**Comment by VMGuy23** [comment]
It crashed. It's a bug with Freeplay, not much can be done.

**Comment by Flustix** [comment]
ok

**Comment by nickpythonluajava** [comment]
replace the ngio.hx file with this: https://gist.githubusercontent.com/jbmagination/caf9eb6a7ae8b415e8acd02962f851e1/raw/d76486854a7676a0ce16907dfa82bf804b155388/NGio.hx
