### ISSUE TITLE
Bug Report: A non-existent update is requested for the source code version.

### ISSUE THREAD

**Issue by creeper-0910** [FunkinCrew/Funkin#1157]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.

0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

Launch the game with the source code version.

## Please describe your issue. Provide extensive detail and images if possible.

Start the game with the source code version.
You will then be asked to update the version with no change in the version.
The other versions were not requested.
![Error](https://user-images.githubusercontent.com/56744841/119254231-1f809e00-bbf0-11eb-9a32-ac45e5e04fb6.PNG)

**Comment by VMGuy23** [comment]
In TitleState.hx, replace all NG_VER_NUMS with NG_VER

**Comment by creeper-0910** [comment]
Thanks, it worked!

**Comment by VMGuy23** [comment]
No problem. It's quite a well-known bug with the source and the fix is easy.
