### ISSUE TITLE
Bug Report: Softlock bug

### ISSUE THREAD

**Issue by Travdev24** [FunkinCrew/Funkin#1159]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
I'm playing the downloaded version
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Downloaded version lol
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x64
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1: Play week 6 from story mode
2: When the level Senpai starts, go to the debug menu
3: Try to skip to Thorns (by changing songs)
4: This should happen
![image](https://user-images.githubusercontent.com/83091442/119266928-f1786b00-bba9-11eb-9aef-c81aab9b920a.png)
## Please describe your issue. Provide extensive detail and images if possible.
It's supposed to display the normal dialogue and such but instead it's a softlock that doesn't even succeed at showing the dialogue at all.

**Comment by actuallyasmartname** [comment]
It's trying to load two dialogue TXT's at the same time which makes the game confused, which softlocks the game

BTW, this isn't a big issue due to people not really swapping songs via the debug menu
