### ISSUE TITLE
Bug Report: mashing enter on startup causes game to crash

### ISSUE THREAD

**Issue by s-zenmode** [FunkinCrew/Funkin#1160]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
[none]
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
[none]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 10 64-bit
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1 (newest release)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Open the game. As soon as the haxeflixel logo fades, spam enter and your game should crash. The reason I mash enter is so I can get through the intro text and I've done this on mods too.
## Please describe your issue. Provide extensive detail and images if possible.
If I mash enter while the game starts up, the game will crash.
![image](https://user-images.githubusercontent.com/83439414/119273752-577ce680-bbda-11eb-9e9c-155078e7aa5e.png)

**Comment by actuallyasmartname** [comment]
Duplicate of #942,  #656, #577, #491, #428, and many more to come (just realized there were more)

**Comment by s-zenmode** [comment]
Oh sorry about that. i searched but couldn't see similar ones. I will close this.
