### ISSUE TITLE
Bug Report: Custom song crashes after trying to open

### ISSUE THREAD

**Issue by ExpiredOats** [FunkinCrew/Funkin#1162]
All other songs work except for one specific one that I made. When I try to open it in Freeplay, it does the standard "3, 2, 1, Go!" thing it always does, and the music plays for like a second. After that though, the game freezes and crashes. Has anyone else experienced this issue and if so, know how to fix it.

**Comment by NTS-YT** [comment]
Did you leave the voices file in? Custom songs are okay as long as the audio is separated into voices and music.

**Comment by ExpiredOats** [comment]
> Did you leave the voices file in? Custom songs are okay as long as the audio is separated into voices and music.

Everything is in place, and this started happening as of yesterday. Before then, it played as normal with no problems.
