### ISSUE TITLE
Bug: exe file does not export

### ISSUE THREAD

**Issue by josiauh** [FunkinCrew/Funkin#1163]
`I am on Windows, and I have installed all necessary stuff.`
I try to use:
`lime test windows -debug`
but the exe does not export, why does this happen?

**Comment by Mar10Josh** [comment]
Wait hold on i am closing this-

**Comment by myst-rblx** [comment]
you need to put a - so do  lime test windows -debug instead of lime test windows debug or just do lime test windows

**Comment by ninjamuffin99** [comment]
please give more detail, or will remain closed!
