### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by SpringyToast** [FunkinCrew/Funkin#1171]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium-based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Chrome-based

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.8

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
It's quite easy, just don't press any buttons on tutorial

## Please describe your issue. Provide extensive detail and images if possible.
In the tutorial level, if you don't press any buttons the song still plays even though every other week the song stops. With that, every other song delays stopping even though the starting notes have already played

**Comment by VMGuy23** [comment]
Fact: there is no voices file for tutorial, this is intentional

**Comment by nickpythonluajava** [comment]
> Fact: there is no voices file for tutorial, this is intentional

i wonder why though

**Comment by VMGuy23** [comment]
in getting used to the game there's not much need for a voice cutting out
