### ISSUE TITLE
Bug Report: Game performance degrades slowly and then crashes computer - Ubunu Linux.

### ISSUE THREAD

**Issue by xenten9** [FunkinCrew/Funkin#1173]
## Preface
When playing the game from new grounds https://www.newgrounds.com/portal/view/770371.

## Jist:
On **Firefox**, on **Ubuntu Linux**. There is a slow degradation of performance which given enough time with go into the low 30's and into the 20's and eventually crash not only the browser but the computer itself and require a hard reboot in order to escape.

## Windows runs fine
I do not encounter this problem when running it on my Windows 10 installation.
In general the game runs much faster on my Windows 10 installation making me think it may be some form of performance issue.

## Replication
For replication I am using a very recent stable version of Ubuntu and running on Firefox. It usually takes around 3-6 songs before the performance starts to drop and by the time it gets unplayable it is usually mere moments from crashing. It will start to drop inputs and the visuals will be out of time and choppy.

## Hardware
I am also running on a Alien ware M15 laptop which needs the alien ware command center which only really works on windows to achieve most of the performance it has available so that may be why the performance difference is so great.

**Comment by actuallyasmartname** [comment]
It may be due to an overload of RAM or CPU usage. Does the laptop get hot when the performance degrades?

**Comment by xenten9** [comment]
> 
> 
> It may be due to an overload of RAM or CPU usage. Does the laptop get hot when the performance degrades?

That could be the case, I will check when I have the time and will get back to you with as much information as I can gather.

**Comment by xenten9** [comment]
While looking at the Ram and Memory usage inside of my system monitor, it showed a few moments before crashing a large gradual increase in memory swapping and memory nearly reaching its limit. Maybe a memory leak.

I was playing Week 1 after having played week 3-5 just before. It had a massive lag spike in Boopebo and then stayed kind a meh through Fresh although it did start dropping my inputs every once in while. It then took a long time to load Dad battle and while this was happening CPU usage was unusually low. After loading it played through the intro until the first line and then started hemorrhaging performance and dropping nearly all inputs. It eventually continued playing the song while the vocals disappeared for about a half a minute until i finally died, it then sat there for a minute my system no longer parsing my inputs in any meaningful way, eventually I was able to close the tab but it was so bad that I think it could have taken  hours if i weren't trying to before it crashed.

**Comment by gardenappl** [comment]
There's a memory leak that only happens in Firefox, but not Chromium. (no idea if it's the game's fault or Mozilla's fault...)

**Comment by gardenappl** [comment]
If it really is a memory leak then you should rename the issue.

**Comment by VMGuy23** [comment]
on Edge im fine
