### ISSUE TITLE
Bug Report: When i play Week 7 my pc slows down the cutscene and it annoys the crap out of me

### ISSUE THREAD

**Issue by LolMyPcSux** [FunkinCrew/Funkin#1176]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by 4techguns** [comment]
1. You didn't even fill out the issue template, you just filled out the title
2. Lag isn't a bug. The performance of this game depends on your computer.

**Comment by LolMyPcSux** [comment]
the first one idc and my pc is fine
