### ISSUE TITLE
Enhancement: Separate the enemy and bf voices for "duet" songs

### ISSUE THREAD

**Issue by Shrunktailor** [FunkinCrew/Funkin#1177]
If bf misses all the notes, the audio cuts in and out while the enemy does their part because the game tries to mute Voices.mp3 during the duet.

**Comment by LolMyPcSux** [comment]
good enhancement

**Comment by nickpythonluajava** [comment]
#1008 exacly what i said

**Comment by VMGuy23** [comment]
Duplicate of #1008
