### ISSUE TITLE
Bug Report: Arrows and notes don't show up on on freeplay and story mode

### ISSUE THREAD

**Issue by woolenCircle** [FunkinCrew/Funkin#1181]
Issues seems to be only showing up on the newgrounds website cause It doesn't seem to be happening on itch.io website browser either, The notes only show up on week 6 tho. Oh yeah the opening glitches by a lot and the menu select art is now half black too. This is probably because I play on my chromebook.

**Comment by LolMyPcSux** [comment]
yes being on chromebook is not recommended
