### ISSUE TITLE
Does boyfriend have hallucinations about the lemon demon?

### ISSUE THREAD

**Issue by KaidenOnYT** [FunkinCrew/Funkin#1184]
#### #1174 Hi NinjaMuffin my question was did boyfriend halation about the lemon Demon?

**Comment by KaidenOnYT** [comment]
sorry my grammar sucks

**Comment by aflacc** [comment]
why did you mention my issue

**Comment by nickpythonluajava** [comment]
boyfriend halation

**Comment by bonkmaykrQ** [comment]
Not sure this is worthy of a Github issue, but it _is_ a question, which meets the criteria. So.

Very interesting lore bit, I must say

**Comment by aflacc** [comment]
I honestly think the lemon demon could be another demon the spooky bois trapped like  molec or whatever his name is. They leave and he starts causing havoc. Just like in Unwanted Guest
