### ISSUE TITLE
Bug Report: whenever i try to play week 7 it stays at the black screen but doesn't load in all the way.  if I want to play week 7 I have to go into freeplay which doesn't have any of the extra scenes.  any help on how to fix this?

### ISSUE THREAD

**Issue by thee-lemon** [FunkinCrew/Funkin#1186]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by thee-lemon** [comment]
I also have to restart the game completely to get it back on the menu

**Comment by time-guy890** [comment]
maybe re-download the game because week 7 is updated and ur version is outdated

**Comment by VMGuy23** [comment]
> maybe re-download the game because week 7 is updated and ur version is outdated

Hi - Week 7 isn't downloadable currently. Stop offering unhelpful advice that does nothing to help.

**Comment by thee-lemon** [comment]
Alright thanks

**Comment by bonkmaykrQ** [comment]
Please use the template and fill out the appropriate information, instead of leaving it blank and typing the whole thing in the title.
