### ISSUE TITLE
source/DialogueBox.hx:109: characters 58-66 : Expected )

### ISSUE THREAD

**Issue by AshuraTheEchidna** [FunkinCrew/Funkin#1189]
here is the line 109, comment if you can help me:
if (PlayState.SONG.song.tolowerCase() -- 'senpai' || PlayState.SONG.song.tolowerCase() -- 'roses' || PlayState.SONG.song.tolowerCase() -- 'thorns')

**Comment by VMGuy23** [comment]
get latest haxe from website

**Comment by AshuraTheEchidna** [comment]
> get latest haxe from website

i already have it, and yes, i tried re-installing

**Comment by NotHyper-474** [comment]
Weren't the `--` supposed to be `==`? I've searched if Haxe has a `--` operator but couldn't find nothing about it.

**Comment by time-guy890** [comment]
Statement.''ninjamuffin99".company

**Comment by time-guy890** [comment]
> Weren't the `--` supposed to be `==`? I've searched if Haxe has a `--` operator but couldn't find anything about it.

its supposed to be  `==`  because `--` would make it break the game right?

**Comment by VMGuy23** [comment]
Hi - Try `==` instead of `--` and post the outcome here.

**Comment by nickpythonluajava** [comment]
> Weren't the `--` supposed to be `==`? I've searched if Haxe has a `--` operator but couldn't find nothing about it.

[there is a -- operator you dumb dumb](https://haxe.org/manual/expression-operators-unops.html)

**Comment by VMGuy23** [comment]
thats minus though
2 non-bool values will not make a bool when subtracted

**Comment by NotHyper-474** [comment]
> > Weren't the `--` supposed to be `==`? I've searched if Haxe has a `--` operator but couldn't find nothing about it.
> 
> [there is a -- operator you dumb dumb](https://haxe.org/manual/expression-operators-unops.html)

That one only works used as `insertNumberHere--` tho.
