### ISSUE TITLE
Bug Report: Gray Screen when i want to play this game

### ISSUE THREAD

**Issue by Peachtea222** [FunkinCrew/Funkin#1191]
Hello dear developers. I really wanted to play this game but I had such a very big problem. The problem is that when I start the game the game starts to lag and then when I click on "play" the game starts to load and then boom! A gray window on which the file with a face is abstracted. Please fix this bug! Please, please !!! I am playing on Windows 7 and in Google Chrome browser. I really wanted to play this game but I can't :( If you fix this bug I will be very grateful to you!

**Comment by VMGuy23** [comment]
Either a RAM issue or you have too old a browser version.

**Comment by time-guy890** [comment]
yes

**Comment by ACrazyTown** [comment]
Windows 7 is out of support, you should upgrade

**Comment by VMGuy23** [comment]
Chrome still suppports it
