### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by NepharCringe** [FunkinCrew/Funkin#1192]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below. I'm not playing in a browser.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
I'm not playing in a browser.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows.

## What version of the game are you using? Look in the bottom left corner of the main menu.
The main menu doesn't even open.

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No.

## Please describe your issue. Provide extensive detail and images if possible.
![image](https://user-images.githubusercontent.com/84894349/119772995-6b547100-be96-11eb-926e-9e605f3dc0a8.png)

**Comment by time-guy890** [comment]
hmm sorry we can't do anything you have to get a different device -_-||

**Comment by ACrazyTown** [comment]
> hmm sorry we can't do anything you have to get a different device -_-||

No? It's a permissions error. Try changing the permissions of the file. I'm pretty sure I've seen this error before but I'm unsure if anyone found a fix. If that doesn't work, try building for HTML5 or in the last resort, just play the game on NG/itch (if you're not trying to mod it)

**Comment by VMGuy23** [comment]
Hi - Try running Command Prompt as administrator, set up Haxe and lime, then see if it works.

**Comment by bonkmaykrQ** [comment]
> hmm sorry we can't do anything you have to get a different device -_-||

Don't say anything if you don't know what you're talking about.

OP, this isn't a bug with the game. This is an issue on your end with your compiler for your mod. Run the compiler as administrator and try again.
