### ISSUE TITLE
Bug Report: Neko builds crash the game when doing anything

### ISSUE THREAD

**Issue by kitkatwastaken** [FunkinCrew/Funkin#1195]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Using the desktop version of the game, compiled from the source
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
N/A
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Source build, macOS
## What version of the game are you using? Look in the bottom left corner of the main menu.
2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Create a neko build of the game, run it
## Please describe your issue. Provide extensive detail and images if possible.
I created a neko build (at the time, I was unable to get a standard Mac build running), and doing anything would crash the game. Entering free play, starting a song, etc.

**Comment by windows10win7posreadywoeskio** [comment]
I'm pretty sure you can't build Neko.

**Comment by dark279** [comment]
ah, well that makes a lot of sense now lol

**Comment by time-guy890** [comment]
> I'm pretty sure you can't build Neko.

I agree also it's my job to tell how to fix bugs Friday night funkin'

**Comment by ACrazyTown** [comment]
> > I'm pretty sure you can't build Neko.
> 
> I agree also it's my job to tell how to fix bugs Friday night funkin'

what?

**Comment by ACrazyTown** [comment]
> ah, well that makes a lot of sense now lol

Close this I guess?

**Comment by nickpythonluajava** [comment]
> > I'm pretty sure you can't build Neko.
> 
> 
> 
> I agree also it's my job to tell how to fix bugs Friday night funkin'

I agree also it's my job to tell how to fix bugs Friday night funkin'

**Comment by TheHENOOB** [comment]
I think is possible to build neko but requires to modify a load out of stuff mainly retire Discord RPC on the game code since it doesn't support the neko target, but i recommend to always test your game on the windows target just to not lose time making this (or use Mac and Linux if you are using other OS)

You can close this issue now
