### ISSUE TITLE
Bug Report: arrow

### ISSUE THREAD

**Issue by VMGuy23** [FunkinCrew/Funkin#1196]
### If you are playing the game in a browser, what site are you playing it from?
works everywhere

### If you are playing the game in a browser, what browser are you using?
Any

### If you are playing a downloaded version of the game, what operating system are you using?
Any

## What version of the game are you using? Look in the bottom left corner of the main menu.
Any
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Open debug and close it
## Please describe your issue. Provide extensive detail and images if possible.
mouse stays after closing debug
please fix is annoying

**Comment by Windows1Door2Daniel** [comment]
Maybe is for the any




IDK

**Comment by VMGuy23** [comment]
What do you mean?

**Comment by Windows1Door2Daniel** [comment]
> What do you mean?

Im just following that of Any

**Comment by time-guy890** [comment]
### you  got problems

**Comment by nickpythonluajava** [comment]
> ### you  got problems

# no

**Comment by VMGuy23** [comment]
I have no idea whether Windows1Door2Daniel's sentence is meant to mean something
