### ISSUE TITLE
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189

### ISSUE THREAD

**Issue by BeamMod** [FunkinCrew/Funkin#1197]
I am having trouble trying to test the game i keep running the command "lime run windows" and it come's up with the error message "C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access" is there any way i can fix this?

**Comment by VMGuy23** [comment]
`Warning` is not an error and the game should still compile

**Comment by aflacc** [comment]
I see this all the time and it doesn't really do anything.

**Comment by BeamMod** [comment]
> `Warning` is not an error and the game should still compile

ive been trying to compile it yet it still dose not compile

**Comment by bwbjustin** [comment]
export/release/windows/bin

**Comment by TNT-King** [comment]
It is happening to me too

**Comment by unkn0wnt3hkz** [comment]
just started to join in it happened to me first try and it wont run

**Comment by FNFboi22** [comment]
Could someone help me.
I get this error:
C:/Users//reporise/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/Users//reporise/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:150: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IC:/Users//reporise/discord_rpc/git/linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\\Desktop\FNF That works to be compiled\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/Users//reporise/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/flixel/input/actions/_FlxSteamController/FlxSteamControllerMetadata.cpp
 - src/sys/io/_Process/Stdout.cpp
 - src/openfl/display/_internal/Context3DElementType.cpp
Error: Stdout.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: FlxSteamControllerMetadata.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: Context3DElementType.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

PS C:\Users\\Desktop\FNF That works to be compiled> lime test windows
C:/Users//reporise/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/Users//reporise/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:150: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IC:/Users//reporise/discord_rpc/git/linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\\Desktop\FNF That works to be compiled\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/Users//reporise/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/openfl/display/_internal/Context3DElementType.cpp
 - src/flixel/input/actions/_FlxSteamController/FlxSteamControllerMetadata.cpp
 - src/sys/io/_Process/Stdout.cpp
Error: Stdout.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: FlxSteamControllerMetadata.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

PS C:\Users\\Desktop\FNF That works to be compiled>

**Comment by juanroman74454811** [comment]
Dialouge used in Rip And Tear: Sketchy:  53r2978t95 ry20qeut312o21rjhionsafjlsadihrt5j8023jifds  r34802yrhj208ADMIPDFKSApafvKFJSDPIIpKGJDFLGKJSFKLGJDKklgjf 
  gbfsdwtrewtgfsagb45t298fg023yujh8fp0ciHJfopih80POJOITO fdsuoafyhsadporwqeyh ruipo wqyhoruiwqeo D9I poyduhp C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access                                                                                                                                                                    Boyfriend: ...beep?
