### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by DippyFoxDerg** [FunkinCrew/Funkin#1198]
### If you are playing the game in a browser, what site are you playing it from?
https://www.newgrounds.com/portal/view/770371

### If you are playing the game in a browser, what browser are you using?
Mozilla Firefox

## Please describe your issue. Provide extensive detail and images if possible.
Both in newgrounds and the itch.io, the html5 version of the game does not work in Firefox.
I press play and it "loads", in my opinion it loads wayy too fast, then turns black and freezes, refreshed several times and the issue persists. incase it helps, Here are the page console logs. 

![ErrorFnF](https://user-images.githubusercontent.com/84971123/119979980-91236800-bfb3-11eb-98aa-b513331cf4c4.png)

**Comment by NotHyper-474** [comment]
See if clearing the browser's cache works

**Comment by DippyFoxDerg** [comment]
clearing the browser cache doesnt work. also i tried to see if it would work in Chrome instead, i dont usually use chrome, but for some reason the audio was super loud and distorted.

**Comment by time-guy890** [comment]
yea sompin' wrong with ur chrome book ten

**Comment by DippyFoxDerg** [comment]
my specs are as follows: https://pcpartpicker.com/user/DippyFoxDerg/saved/kv8XkL

**Comment by nickpythonluajava** [comment]
> yea sompin' wrong with ur chrome book then

ITSNOTACHROMEBOOK!!!!!!

**Comment by DippyFoxDerg** [comment]
Its suddenly started working again!!! not sure how but its all workin now.
![image](https://user-images.githubusercontent.com/84971123/121936467-91588d00-cd41-11eb-980f-571df94f8832.png)
