### ISSUE TITLE
Bug Report: whenever the songs starts, it makes an annoying static noise and the song starts slowing down and then the song just stops. then whenever i go to the week selection menu thing it makes the stating sound but this time really loud

### ISSUE THREAD

**Issue by GhostX4589** [FunkinCrew/Funkin#1199]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by VMGuy23** [comment]
1. use desc
2. video?

**Comment by GhostX4589** [comment]
i tried it on newgrounds on safari and chrome, and the bug is only on safari, apparently

**Comment by VMGuy23** [comment]
Safari was never a great browser for Funkin

**Comment by nickpythonluajava** [comment]
> Safari was never a great browser for Funkin

My iPad: Hold my beer

**Comment by VMGuy23** [comment]
I mean, Safari on iOS is fine. macOS Safari doesn't run great though.

**Comment by time-guy890** [comment]
> I tried it on Newgrounds on safari and chrome, and the bug is only on safari, apparently

fnf doest work good on safari
