### ISSUE TITLE
Often, exiting to the main menu can result in the girlfriend animation increasing to unintended speeds. 

### ISSUE THREAD

**Issue by MultiXIII** [FunkinCrew/Funkin#12]
This is just a small animation bug in the main menu when returning to the main menu at any time. The method I have found to reproduce the most reliably follows: Start the game. From the mode select menu return to the main menu and observe the bug.

**Comment by ninjamuffin99** [comment]
Ah yeah, known about this for a lil bit. It's cause of the weird way I programemd the beat-sync logic. I think I might have something in mind to fix it all up.

**Comment by ninjamuffin99** [comment]
fixed this wit ff649ae , coming Friday in 0.2.2 update!
