### ISSUE TITLE
Bug Report: game doesn't compile for windows

### ISSUE THREAD

**Issue by MoezTrigui** [FunkinCrew/Funkin#1200]
help when i try to compile the game for windows with "lime test windows" but it doesn't work it just give me this error "Sys_error("export/release/windows/obj/Options.txt: Permission denied")" but the wierd thing it works with html5 can someone help me pls
![Capture d’écran 2021-05-28 154809](https://user-images.githubusercontent.com/84923340/120001888-2894b500-bfcc-11eb-8069-730862c5e843.png)

**Comment by Steviegt6** [comment]
> help when i try to compile the game for windows with "lime test windows" but it doesn't work it just give me this error "Sys_error("export/release/windows/obj/Options.txt: Permission denied")" but the wierd thing it works with html5 can someone help me pls
> ![Capture d’écran 2021-05-28 154809](https://user-images.githubusercontent.com/84923340/120001888-2894b500-bfcc-11eb-8069-730862c5e843.png)

Anti-virus issue?

**Comment by MoezTrigui** [comment]
i have avast and windows defender no other
sould i turn them off?

**Comment by MoezTrigui** [comment]
i don't get any alert while compiling are you sure?

**Comment by Steviegt6** [comment]
> i don't get any alert while compiling are you sure?

What does this have to do with compilation? The error occurs at runtime, does it not?

**Comment by MoezTrigui** [comment]
wdym?

**Comment by MoezTrigui** [comment]
the game does not launch and i just get the  error but when i compile html5 i get firewall alert what you said may make sense

**Comment by Steviegt6** [comment]
> the game does not launch and i just get the error but when i compile html5 i get firewall alert what you said may make sense

So it's a runtime error? Try disabling Avast.

**Comment by MoezTrigui** [comment]
help pls

**Comment by MoezTrigui** [comment]
> > the game does not launch and i just get the error but when i compile html5 i get firewall alert what you said may make sense
> 
> So it's a runtime error? Try disabling Avast.

ok

**Comment by MoezTrigui** [comment]
mmmm how?
and is it safe
and how to turn it back

**Comment by MoezTrigui** [comment]
help
i just want to make fnf windows mod

**Comment by time-guy890** [comment]
its coming aready

**Comment by ZDrener** [comment]
I had exactly the same error, disabled avast for 10 minutes, and the lime test windows worked properly.

**Comment by LARA69060208** [comment]
Can confirm that this is caused by Avast, just disable it while you're compiling.

**Comment by pokevii** [comment]
This issue is caused by AVG Antivirus as well.

**Comment by redbluexe0** [comment]
this problem will not be caused if you used Kaspersky or other ones. Avast is kind of overreacting to some games.
