### ISSUE TITLE
Question: Why did you choose the name ninjamuffin99?

### ISSUE THREAD

**Issue by aflacc** [FunkinCrew/Funkin#1201]
I like to ask people why they chose their names on the Internet. I'll explain why I chose mine as well since I'm here.

If I remember correctly, I think I chose the name "aflac" coming from Discord, where I originally chose it because in the commercials, the duck would constantly scream "AFLAC" and I thought that fit me (obnoxious) so I did. The name stuck with me and I guess its just a part of me.

**Comment by VMGuy23** [comment]
I just kinda thought of something and it stuck. Made a name for the freenode IRC network

**Comment by Windows1Door2Daniel** [comment]
Maybe just randomly

like my name

i thinked a door with windows OS colors

**Comment by ThePlank** [comment]
i just thaught of a plank in my dream snd i changed to that
