### ISSUE TITLE
Bug Report: sometimes arrows are not detected in any song and it is very annoying in difficult songs (please fix)

### ISSUE THREAD

**Issue by lucazwolf** [FunkinCrew/Funkin#1202]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
 
Now I play more on NewGrounds but I have the same problem in the download version

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

Am using chrome

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

I use the Windows (x86) 

## What version of the game are you using? Look in the bottom left corner of the main menu.

I am using the newest version

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

As I said before, the bug appears in all the songs of the game

## Please describe your issue. Provide extensive detail and images if possible.

What happens is that sometimes I touch the arrows at the perfect moment and the game does not detect the arrow that I touch

**Comment by aflacc** [comment]
can you maybe actually use the description to explain the issue

**Comment by lucazwolf** [comment]
Es lo que estoy haciendo justo ahora/It's what I'm doing right now

**Comment by aflacc** [comment]
aight ok 👍

**Comment by aflacc** [comment]
Okay so does the issue happen if you immediately go straight into booting up a song from the game opening?

**Comment by lucazwolf** [comment]
What happens is that it depends on the difficulty of the song, if for example I start with an easy song, the bug will appear much later but if I play a difficult song, the bug will appear from the beginning of the song

**Comment by lucazwolf** [comment]
i put that in english now

**Comment by aflacc** [comment]
Yes I understood that but I don't know what your trying to say happens. Like is it something to do with the inputs?

**Comment by lucazwolf** [comment]
Yes, the problem is the input.

**Comment by time-guy890** [comment]
maybe making new code to make the arrows then import it into the game or just use the arrows code and then update it?

**Comment by time-guy890** [comment]
or make urself more frickin' mad by doing hours of coding

**Comment by time-guy890** [comment]
lucazwolf, podrias crear un nuevo codigo o pedir ayuda a ninjamuffin99 verdad?

**Comment by lucazwolf** [comment]
Am going to try

**Comment by lucazwolf** [comment]
I have a question, how do I message ninjamuffin99?
