### ISSUE TITLE
Question: Ok So I Seen A Couple Of Mods Have Multiple Icons Like When Boyfriend Smiles On Ugh Hig Effort When All To The Left How Do I Do That

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1206]

**Comment by ThePlank** [comment]
1. Use the body of your question
2. Just use FPS Plus because thats what High Effort Ugh was made in

**Comment by bonkmaykrQ** [comment]
Please don't write the entire question in the Issue title. It's very hard to read.

The title should be a brief summary of the actual question or problem, usually 7 words or less.

**Comment by VMGuy23** [comment]
> 1. Use the body of your question
> 2. Just use FPS Plus because thats what High Effort Ugh was made in

ProjectFNF might be better. Depends whether FPS Plus uses OG input.
