### ISSUE TITLE
Question: ¿¿¿BF POSE OF PEACE???

### ISSUE THREAD

**Issue by PROESSPESS** [FunkinCrew/Funkin#1207]
How can I get Bf to do the peace pose when I want him to do that pose?

**Comment by Windows1Door2Daniel** [comment]
onlly available on bopeebo

**Comment by PROESSPESS** [comment]
> onlly available on bopeebo

what i want to know is how i can do it

**Comment by xenten9** [comment]
The pose he does is unique to the song Bopeebo, on that song it is coded into the file itself what pose he does when you hit certain notes. As such you cannot do it anywhere else unless you figured out how to modify the other songs to do that and then went through and manually modified each pose.

**Comment by PROESSPESS** [comment]
> The pose he does is unique to the song Bopeebo, on that song it is coded into the file itself what pose he does when you hit certain notes. As such you cannot do it anywhere else unless you figured out how to modify the other songs to do that and then went through and manually modified each pose.

You would do me a great favor if you can figure out how to do the poses since I've been looking for a long time and I haven't found the result.

**Comment by ACrazyTown** [comment]
literally just make a switch case for the current beat and make play the HEY!! animation when youw ant

**Comment by PROESSPESS** [comment]
> literally just make a switch case for the current beat and make play the HEY!! animation when youw ant

I mean, the song has to have the same phrase as the pose's name?

**Comment by Windows1Door2Daniel** [comment]
> > literally just make a switch case for the current beat and make play the HEY!! animation when youw ant
> 
> I did not understand 😥

Also

You talk spanish?

**Comment by PROESSPESS** [comment]
> > > literally just make a switch case for the current beat and make play the HEY!! animation when youw ant
> > 
> > I did not understand 😥
> 
> Also
> 
> You talk spanish?

Yes

**Comment by Windows1Door2Daniel** [comment]
> > > > literally just make a switch case for the current beat and make play the HEY!! animation when youw ant
> > > 
> > > 
> > > I did not understand 😥
> > 
> > 
> > Also
> > You talk spanish?
> 
> Yes

Knew it since you used the flipped question mark

**Comment by PROESSPESS** [comment]
> Knew it since you used the flipped question mark

ok

**Comment by Windows1Door2Daniel** [comment]
I know Spanish

Me gusta el espanol

**Comment by PROESSPESS** [comment]
> I know Spanish
> 
> Me gusta 

Prefiero el ingles ya que para mi es el idioma que mas se puede usar mundialmente

**Comment by Windows1Door2Daniel** [comment]
> > I know Spanish
> > Me gusta
> 
> Prefiero el ingles ya que para mi es el idioma que mas se puede usar mundialmente

Yo tambien
