### ISSUE TITLE
Warning Message Preventing game startup 

### ISSUE THREAD

**Issue by BeamMod** [FunkinCrew/Funkin#1210]
I was using that command "lime test windows" and shortly after i put the command this warning popped up

"C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:168: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:168: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access" 

Is there any way to fix this? i've tried "lime test HTML5 -debug" aswel but the same warning pops up.

**Comment by VMGuy23** [comment]
Show full output. That's not a preventing message.

**Comment by BeamMod** [comment]
> Show full output. That's not a preventing message.

That is the full output, there is no message saying that the game cannot start its just that one warning.

**Comment by ACrazyTown** [comment]
Warnings shouldn't stop the game from building, you're probably doing something wrong. Try typing `localhost:3000` in your browser

**Comment by NotHyper-474** [comment]
Try building with `lime test html5 -verbose`. It might flood your cmd with text but you get some more build info. 
![image](https://user-images.githubusercontent.com/40342021/120227839-596d2800-c220-11eb-965c-56642616f0e0.png)
If this appears then it was built correctly and it will open your browser, if it doesn't, try what ACrazyTown guy said above.
