### ISSUE TITLE
Bug Report: Not loading.

### ISSUE THREAD

**Issue by JacobDoes** [FunkinCrew/Funkin#1214]
Every time I try and load to game on Newgrounds, the loading screen just freezes. I am using MacBook Pro, I am using Safari search engine and I am on version 4.9.0. Thank you.

**Comment by VMGuy23** [comment]
Reload (just with the button) or use Chrome
It takes a few reloads and Safari might not work
(note: it's HaxeFlixel 4.9.0, not game ver 4.9.0, ng game ver is v0.2.8)

**Comment by time-guy890** [comment]
yea
