### ISSUE TITLE
Question: How to go full screen?

### ISSUE THREAD

**Issue by JacobDoes** [FunkinCrew/Funkin#1215]
I want to record a video on Friday Night Funkin' and I don't know how to go full screen. I am using Newgrounds, not itch.io.

**Comment by VMGuy23** [comment]
During the credits or logo screens, press f once.

**Comment by Aktimoose** [comment]
alt+enter at any point

**Comment by Jrmcwicked** [comment]
Press Alt Enter

**Comment by VMGuy23** [comment]
f

**Comment by nickpythonluajava** [comment]
f

**Comment by Windows1Door2Daniel** [comment]
> Press Alt Enter

Thats only for downloaded version

**Comment by FNFPlayer101** [comment]
Press F.
