### ISSUE TITLE
Build swf?

### ISSUE THREAD

**Issue by mxlgv** [FunkinCrew/Funkin#1216]
I read that haxe is capable of collecting files for a flash player. Is it possible to build the game as SWF?

**Comment by VMGuy23** [comment]
Try looking at how Haxe builds like that and try it

**Comment by jbmagination** [comment]
I tried building as-is, doesn't work too well. Will see if I can pull it off but I doubt it

**Comment by nickpythonluajava** [comment]
ill do it later but im going somewhere and im using github for mobile this sucks

**Comment by Fefecomitre** [comment]
lime test swf

**Comment by TheHENOOB** [comment]
try `lime test flash` on any Command Line to run the game on flash, but you have to be aware that you probably gonna have to modify some lines of the game's code to run the game properly
