### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by BeamMod** [FunkinCrew/Funkin#1217]
A new problem has occurred for me, this message pops up when trying to compile the game using "lime test windows"

"source/TitleState.hx:61: characters 16-28 : Type not found : APIStuff
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access" 

is there anything thing i can do to fix this, its stopping the game from running and its getting really annoying.

**Comment by DjBRINE** [comment]
APIStuff is gitignored for a long time, read readme file how to add one

**Comment by NotHyper-474** [comment]
> Ignored files
> I gitignore the API keys for the game, so that no one can nab them and post fake highscores on the leaderboards. But because of that the game doesn't compile without it.
>
>Just make a file in /source and call it APIStuff.hx, and copy paste this into it
>
> ```
> package;
> 
> class APIStuff
> {
> 	public static var API:String = "";
> 	public static var EncKey:String = "";
> }
> ```
>
>and you should be good to go there.

**Comment by BeamMod** [comment]
> > Ignored files
> > I gitignore the API keys for the game, so that no one can nab them and post fake highscores on the leaderboards. But because of that the game doesn't compile without it.
> > Just make a file in /source and call it APIStuff.hx, and copy paste this into it
> > ```
> > package;
> > 
> > class APIStuff
> > {
> > 	public static var API:String = "";
> > 	public static var EncKey:String = "";
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and you should be good to go there.
> 
> It is named "Read me" for a reason.

I have everything installed and the code in for APIStuff.hx and yet it still comes up with that message.
