### ISSUE TITLE
?

### ISSUE THREAD

**Issue by BeamMod** [FunkinCrew/Funkin#1218]
When i try to run the game using "lime test windows" this message pop's up

"C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:150: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\Cruzc\Documents\Funkin-master00\Funkin-master\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC"

This is the third time something has happened stopping the game from running, it keeps adding more and more.

**Comment by VMGuy23** [comment]
https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe

**Comment by BeamMod** [comment]
> https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe

Whats this for?

**Comment by ThePlank** [comment]
> > https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe
> 
> Whats this for?

This is for compiling for HXCPP (AKA Windows). The needed components are MSVC (any version) and a Windows 10 SDK (also any version).

**Comment by VMGuy23** [comment]
It requires VsDevCmd 2017, or VS2017 build tools. That's a direct link to Microsoft Visual Studio 2017 Build Tools.

**Comment by time-guy890** [comment]
update the game that should fix it

**Comment by jbmagination** [comment]
> update the game that should fix it
maybe you need a bit of guidance here

they can't update the game because they're attempting to make an executable version of the game from the actual code, they're having trouble doing that. 

others have suggested it is because they do not have the visual studio 2017 build tools, which is a requirement for building games that use haxe such as friday night funkin
