### ISSUE TITLE
License Problem

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1219]
"if u make mods, open source them, lol!" doesn't tell me what I can do with the source and/or assets.

**Comment by VMGuy23** [comment]
It says you can modify the game as long as any public modifications have the source code to that mod avaliable

**Comment by ActualMandM** [comment]
this is being talked about in #1106

**Comment by bonkmaykrQ** [comment]
> 
> 
> It says you can modify the game as long as any public modifications have the source code to that mod avaliable

That doesn't make it a valid license.

**Comment by VMGuy23** [comment]
How does the license [here](https://github.com/ninjamuffin99/Funkin/pull/1175/commits/8bba94ffc36c149c451087826216dce7d80165e8) look?

**Comment by ActualMandM** [comment]
still not a valid license

**Comment by bonkmaykrQ** [comment]
> How does the license [here](https://github.com/ninjamuffin99/Funkin/pull/1175/commits/8bba94ffc36c149c451087826216dce7d80165e8) look?

It looks disgusting.

**Comment by bonkmaykrQ** [comment]
> It says you can modify the game as long as any public modifications have the source code to that mod avaliable

It's still not a valid license and holds absolutely not value in court, nor as an actual legal document for granting rights to users. It's either going to hurt ninjamuffin99, hurt us, or hurt both.

**Comment by VMGuy23** [comment]
> > It says you can modify the game as long as any public modifications have the source code to that mod avaliable
> 
> It's still not a valid license and holds absolutely no value in court, nor as an actual legal document for granting rights to users. It's either going to hurt ninjamuffin99, hurt us, or hurt both.

Go on then, make your own

**Comment by bonkmaykrQ** [comment]
> > > It says you can modify the game as long as any public modifications have the source code to that mod avaliable
> > 
> > 
> > It's still not a valid license and holds absolutely no value in court, nor as an actual legal document for granting rights to users. It's either going to hurt ninjamuffin99, hurt us, or hurt both.
> 
> Go on then, make your own

Or instead of being an idiot, you could just use GPL v3 which already has everything needed.

**Comment by RandomErrorMessage** [comment]
Just work on the last Apache license version of the code, there's been no real changes since then, and any future commits to this current repository would be a violation of contributor licensed code.

**Comment by ninjamuffin99** [comment]
reverted license epic win
