### ISSUE TITLE
Bug Report: Gamepad Option

### ISSUE THREAD

**Issue by Julius164** [FunkinCrew/Funkin#1220]
I'm not used to use the WASD and arrows, so I use my Switch Pro controller to play. First I remap the buttons so I can play like I was on the keyboard but it change that to a Xbox controller configuration (pretty expectable). But the real deal is that, when I tried to remap the buttons from the Controls>Gamepad option the left input disapear and I can't make it come back. And also I can't remap my buttons because the button I want to change go to Left insted and back (but left input don't come back to existence)

**Comment by time-guy890** [comment]
hmmm i think you should delete the game and re-download it
