### ISSUE TITLE
Bug Report: black squares are seen instead of characters

### ISSUE THREAD

**Issue by maury1** [FunkinCrew/Funkin#1222]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by nickpythonluajava** [comment]
this is a ram issue.

**Comment by VMGuy23** [comment]
I've had enough of these! It's not a game issue, it's your computer not being good enough

**Comment by NotHyper-474** [comment]
It might also be a lack of V-RAM

**Comment by time-guy890** [comment]
V-RAM?

**Comment by time-guy890** [comment]
its a whatever ur device is code messing up causing ur device to cover the characters

**Comment by NotHyper-474** [comment]
> V-RAM?

VRAM or Video RAM, basically it's the memory your GPU uses to store textures for the game sprites. Some older or integrated GPU have too small amount of VRAM so the game fails to render these cuz most sprites are 8k and take around 2-4 MB

**Comment by ACrazyTown** [comment]
> its a whatever ur device is code messing up causing ur device to cover the characters

What?
This is a RAM issue, it's been confirmed multiple times, it has nothing related to device code??

**Comment by Michael82548** [comment]
https://github.com/ninjamuffin99/Funkin/pull/1083 might fix it
