### ISSUE TITLE
Bug Report: browser FNF has broken audio

### ISSUE THREAD

**Issue by yeeter123456789** [FunkinCrew/Funkin#1224]
once I finished a song it made lots of annoying flickering noises that wouldn't stop! it is very annoying.

**Comment by yeeter123456789** [comment]
the video just played for the Kickstarter when I did control-R but it did not show up and was repeating the video over and over, I was going the song "stress"

**Comment by time-guy890** [comment]
HHHMMM WHERE YOU ON NEWGROUNDS OR DOWNLOADED IT ON ITCH.OI

**Comment by VMGuy23** [comment]
> HHHMMM WHERE YOU ON NEWGROUNDS OR DOWNLOADED IT ON ITCH.OI

ng
kickstarter isnt on itch

**Comment by nickpythonluajava** [comment]
> HHHMMM WHERE YOU ON NEWGROUNDS OR DOWNLOADED IT ON ITCH.OI

hmmm yes _**DOWNLOAD**_

**Comment by VMGuy23** [comment]
IT's a Week 7 song with Kickstarter, therefore meaning it's on Newgrounds.

**Comment by yeeter123456789** [comment]
ok
