### ISSUE TITLE
Bug Report: i can,t get in fnf so bad that i am mad and sad plss let me in the game

### ISSUE THREAD

**Issue by oreosister8532** [FunkinCrew/Funkin#1228]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by ACrazyTown** [comment]
?? Elaborate

**Comment by oreosister8532** [comment]
.,.

**Comment by ACrazyTown** [comment]
???

**Comment by VMGuy23** [comment]
Hi - Please fill in the required fields and give more information so we can help troubleshoot this issue. Thanks.

**Comment by prokube** [comment]
i am disappointed in the internet sometimes

**Comment by VMGuy23** [comment]
> i am disappointed in the internet sometimes

i know

**Comment by wdtflm** [comment]
> Bug Report: i can,t get in fnf so bad that i am mad and sad plss let me in the game

no

**Comment by FNFPlayer101** [comment]
what the hell is this

**Comment by prokube** [comment]
> what the hell is this

sadness

**Comment by AmazingCreeper13** [comment]
be more specific

**Comment by redbluexe0** [comment]
> #### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.
> ### If you are playing the game in a browser, what site are you playing it from?
> [Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
> 
> ### If you are playing the game in a browser, what browser are you using?
> Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
> 
> ### If you are playing a downloaded version of the game, what operating system are you using?
> Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
> 
> ## What version of the game are you using? Look in the bottom left corner of the main menu.
> ## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
> ## Please describe your issue. Provide extensive detail and images if possible.

hi there oreosister8532 please give us details why you can enter Friday Night Funkin. without the details, we cant solve it.
