### ISSUE TITLE
small meaningless visual oversight

### ISSUE THREAD

**Issue by Flowi320215** [FunkinCrew/Funkin#1229]
on week 6 if you press 9 to switch to the old sprite then 9 again instead of changing to the pixelated sprite it changes too the normal one

**Comment by nickpythonluajava** [comment]
not a glitch, this is intentional.

**Comment by jbmagination** [comment]
@nickpythonluajava No, it is a glitch, you're misunderstanding. Pressing 9 goes back to the normal sprite instead of the pixelated one, when it *should* be pixelated because it's Week 6.

**Comment by SpringyToast** [comment]
@nickpythonluajava But there is literally no pixelated beta bf icon this isn't a glitch at all

**Comment by jbmagination** [comment]
@SpringyToast Yes, there is no pixelated beta BF icon, that's correct-- but this refers to when you switch *back* to the normal one. Instead of being the pixelated normal one, it's the *actual* normal one

**Comment by Flowi320215** [comment]
> @jbmagination But there is literally no pixelated beta bf icon this isn't a glitch at all
I mean that when you go back too the normal sprite instead of returning too the pixelated one it returns too the normal non pixelated one
