### ISSUE TITLE
Mouse invisible on Debug Menu

### ISSUE THREAD

**Issue by Polytelus** [FunkinCrew/Funkin#123]
While it might work on the Browser version, the Windows version just gives a invisible cursor. Yeah, I don't know what i'm clicking.

System:
Windows 10 Home
Intel Pentium N3540 (Intel HD Graphics)
4GB RAM
Itch.io version of the game (39, week 3)

**Comment by gedehari** [comment]
I think it's because the cursor is disabled globaly, and the debug mode doesn't turn it on. It's an easy fix though, lets see what I can do.

**Comment by ninjamuffin99** [comment]
fixed in 0.2.5 update!

**Comment by gedehari** [comment]
oh whoops the creator already does it, lol
