### ISSUE TITLE
(Closed for now)

### ISSUE THREAD

**Issue by User198263321** [FunkinCrew/Funkin#1230]
Am I allowed to do this if I link the original PR link in the code?

Like:

//Credit
[Code goes here]
//Credit End

This will merge (As of me typing this):
https://github.com/ninjamuffin99/Funkin/pull/747
https://github.com/ninjamuffin99/Funkin/pull/1083
https://github.com/ninjamuffin99/Funkin/pull/941
https://github.com/ninjamuffin99/Funkin/pull/412

I just want to save people 4 hours of frustrating compiling to find that things crash, break, or otherwise do not work correctly.

I want to create a branch that is compilation friendly (Good for mod makers) and not be needing other resources (Such as Newgrounds) to function properly.

I merged the current PRs (Had to edit some of the code myself because they changed the same files), compiled it, and all of the fixes seem to work as intended. (No more broken update nagging and ram leaking!) (I can play finally play freeplay mode now!!)

This would be a hobby project so I don't know how often I would update it

**Comment by Michael82548** [comment]
Keep on running into more issues.

**Comment by Michael82548** [comment]
Fixed most of them

**Comment by Michael82548** [comment]
I have been breaking my back trying to get these fixes to work but the game is so enjoyable after finishing this first test build. I am very happy with it :)

**Comment by Michael82548** [comment]
Closing this for now

**Comment by nickpythonluajava** [comment]
you don't need to reopen and close to add comments lmao
