### ISSUE TITLE
Bug Report: Parts of game not working when built manually

### ISSUE THREAD

**Issue by scorbiclife** [FunkinCrew/Funkin#1234]
#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

~~### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.~~
~~### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.~~
~~### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.~~

### Environment
- OS: Windows 10 x86_64
- Affected Builds:
    - HTML5 builds on Firefox Developer Edition / Edge 
    - Windows builds
        Actually I built the windows ones with only the VS2019 SDK related things, so you might want to take Windows builds with a grain of salt.
        I am updating (and planning to rebuild) with the cursed Visual Studio components;
        Do I need all 3 pairs of compilers and Windows SDKs listed in the readme XD,
        or can I get install parts of it if it compiles okay?
- Branch: master

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7.1

~~## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.~~
~~Just Play it~~

## Please describe your issue. Provide extensive detail and images if possible.

So after some hiccups I compiled the game fine. I can run it the Windows and HTML5 builds.
I didn't navigate to the game as a whole but here are the issues I encountered:

- Intro screen:
    - warns me the version is outdated(v0.2.7.1) and I have to get v0.2.7.1
- **Free Play**
    - Screen just blackens and becomes unresponsive
- **Options**
    - Master Volume / Sound Volume: Nothing happens when selected
    - Controls: Goes to unresponsive blank pink screen when selected

Thanks for reading in advance.

**Comment by NightlyHerb** [comment]
Oh one more quirk, I used the portable distribution of Haxe, will post here again if it actually works on installed builds.

**Comment by VMGuy23** [comment]
These issues do appear when compiling. It's not just you.

**Comment by NightlyHerb** [comment]
Oh I see, thanks, which revision am I supposed to build to test and tweak stuff? (Alternatively latest working build?)

**Comment by VMGuy23** [comment]
I don't know. Something like ProjectFNF or Kade Engine would work for testing things (they both have their own additions but are still mainly the base game)

**Comment by Michael82548** [comment]
See #412
