### ISSUE TITLE
Bug Report: frame rate weirdly low all of a sudden 

### ISSUE THREAD

**Issue by clinicallynox** [FunkinCrew/Funkin#1237]
### If you are playing the game in a browser, what site are you playing it from? 
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
I'm playing straight from newgrounds
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
chrome

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.8
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
every time I start the game this happens
## Please describe your issue. Provide extensive detail and images if possible.
was playing two days ago, 6/2, and everything was fine. then all of a sudden I try to play milf and the frame rate drops like crazy. i got rid of all my tabs, restarted my computer, everything, and nothing worked, so I decided to just wait and hope it got better with time. flash forward to today, 6/4, and the issue is still happening. i press start, the frame rate is like, 8-10. then I try and start a week or do freeplay, and it jumps to around 40 (which is normal) while it's loading. then, once it's done loading, it'll drop back to 8-10 and just lags really bad. please, all i want to do is get freaky on a Friday night :/

**Comment by VMGuy23** [comment]
Hi - Have you installed anything new on your computer recently? Many pieces of software of software autostart on login.
Check the "Startup" tab of Task Manager and disable any you don't need.

**Comment by Windows1Door2Daniel** [comment]
Migth be a problem with your RAM

**Comment by VMGuy23** [comment]
> Migth be a problem with your RAM

Hi - Decrease in FPS isn't a RAM problem. Black sprites are, but slowness isn't.

**Comment by Windows1Door2Daniel** [comment]
> > Migth be a problem with your RAM
> 
> Hi - Decrease in FPS isn't a RAM problem. Black sprites are, but slowness isn't.

Well IDK

**Comment by gardenappl** [comment]
> Hi - Decrease in FPS isn't a RAM problem. Black sprites are, but slowness isn't.

You're absolutely going to get FPS issues if you run out of RAM and start swapping to disk.

**Comment by VMGuy23** [comment]
> > Hi - Decrease in FPS isn't a RAM problem. Black sprites are, but slowness isn't.
> 
> You're absolutely going to get FPS issues if you run out of RAM and start swapping to disk.

its probably not a RAM problem if its new

**Comment by Windows1Door2Daniel** [comment]
Migth be connection problem

or the website didnt load the sprites well
