### ISSUE TITLE
Enhancement: Discord Rich Presence

### ISSUE THREAD

**Issue by Yug1900** [FunkinCrew/Funkin#1239]
## What is your suggestion, and why should it be implemented?

Well, you see.

[this mod](https://gamebanana.com/mods/166531) for FNF is pretty cool and it has a feature that enables discord rich presence and i wold love if you put in the original game

*example*
Sorry for having it in spanish
![image](https://user-images.githubusercontent.com/84157407/120862837-98201c80-c557-11eb-97aa-874b6c0a343a.png)
In tiempo restante it says Time Remaining

Hope it gets added
thanks

**Comment by VMGuy23** [comment]
Hi - I'm pretty sure this is already in the game. Try it and see.

**Comment by Yuggg1900** [comment]
> Hi - I'm pretty sure this is already in the game. Try it and see.

I already tried

it hasn´t got the feature

**Comment by VMGuy23** [comment]
Hi - Is this not what the discord_rpc module is used for?
It's quite unlikely that SeoS would have it without the original game having it.

**Comment by ActualMandM** [comment]
Aldready implemented

**Comment by VMGuy23** [comment]
> Aldready implemented

Hi - Thanks for sharing this. this issue should be closed now.

**Comment by NotHyper-474** [comment]
> Aldready implemented

Yup, should work when v0.2.8 finally stops being Newgrounds exclusive

**Comment by ninjamuffin99** [comment]
its already implemented, just the update hasnt released on itch yet!

**Comment by ThePlank** [comment]
yea it worked fine when you put a aplication id in
