### ISSUE TITLE
Strange PNG file found over 30 - 40 versions of the game.

### ISSUE THREAD

**Issue by B1ackydecatty** [FunkinCrew/Funkin#124]
![image](https://user-images.githubusercontent.com/45589944/103172679-13d2ba80-4890-11eb-810d-f186603ef37f.png)
![zzzzzzzz](https://user-images.githubusercontent.com/45589944/103172680-17fed800-4890-11eb-8c51-b73e2326dda5.png)
you should able to find those files in your gamefiles, its very strange
who the fuck is joshua recording with mobizen on a youtube video that shows black and white boyfriend in flipaclip???
not an issue, only a curiousity

**Comment by B1ackydecatty** [comment]
between 39 or 38 to 40 version, you can find them there

**Comment by B1ackydecatty** [comment]
i think

**Comment by VMGuy23** [comment]
I think it's just a source code easter egg
