### ISSUE TITLE
Locking Weeks and Adding Dialouge.

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1243]
Hello everyone. I have two questions but please feel free to answer one at a time.

1. How can I lock weeks?

2. How can I add dialouge?

Thanks :)

**Comment by FNFPlayer101** [comment]
dialoguebox.hx or whatever it was called allows you to add portraits and all the stuff. Then you have to create ur text in a txt file using the same format as the senpai ones. that's only about adding dialogue tho

**Comment by nickpythonluajava** [comment]
How to lock weeks
go to storymodestate.hx and add another "false" to weekunlocked list or change "true" to "false" if you already put a true in there
