### ISSUE TITLE
Bug Report: HI, I cant play FnF Because if i play in any mode, theres is a grayish backround with a paper with a pixeled sad face, and how many tries to just play fnf, it cant be opened 

### ISSUE THREAD

**Issue by Duncanyounott** [FunkinCrew/Funkin#1244]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Duncanyounott** [comment]
oof bad grammar

**Comment by ACrazyTown** [comment]
Could you provide a screenshot maybe?

**Comment by Windows1Door2Daniel** [comment]
So you are playing on itch.io?

you can play on newgrounds too

try it

**Comment by ThePlank** [comment]
how much RAM do you have? (by the way, he's using the web version)

**Comment by PoketrainerMS** [comment]
are you on a chromebook? that happens to me on the itch.io version with a chromebook

**Comment by Windows1Door2Daniel** [comment]
> are you on a chromebook? that happens to me on the itch.io version with a chromebook

Question

**Comment by VMGuy23** [comment]
Chromebooks are not very good for fnf

**Comment by Windows1Door2Daniel** [comment]
> oof bad grammar

Help us to help you

Explain furter your problem

**Comment by Duncanyounott** [comment]
> are you on a chromebook? that happens to me on the itch.io version with a chromebook



> are you on a chromebook? that happens to me on the itch.io version with a chromebook

Hi, thanks for the response, i am using an windows laptop

**Comment by Duncanyounott** [comment]
> Chromebooks are not very good for fnf

im using an windows laptop

**Comment by Duncanyounott** [comment]
> how much RAM do you have? (by the way, he's using the web version)

i have 8 gis of ram

**Comment by Duncanyounott** [comment]
> So you are playing on itch.io?
> 
> you can play on newgrounds too
> 
> try it

i have used the two sites and i have the same problem

**Comment by nickpythonluajava** [comment]
> > how much RAM do you have? (by the way, he's using the web version)
> 
> 
> 
> i have 8 gigs of ram

8gb of ram works fine for me, i wonder why

**Comment by VMGuy23** [comment]
What laptop model? (Also, update Chrome or whatever your using. Don't use old Edge or Internet Explorer.)

**Comment by Duncanyounott** [comment]
> What laptop model? (Also, update Chrome or whatever your using. Don't use old Edge or Internet Explorer.)

my laptop is hp pavillion g6 with intel core 13

**Comment by VMGuy23** [comment]
It might be a RAM issue. 4GB isn't much

**Comment by TheDrawingCoder-Gamer** [comment]
Almost definetly preformance issue. this is deadass the google chrome "had to kill tab" screen
