### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by iliaGaming100** [FunkinCrew/Funkin#1248]
Hey guys who have a source code of a fnf mod starving artist and link of showcase https://youtu.be/-KD2qfQ_9Hg
Its this my suggestion

**Comment by ThePlank** [comment]
If you go to the gamebanana link and scroll to "Alternative File Sources" there will be a "Source Code" button.
If you dont know where is the button then look at the image below
![image](https://user-images.githubusercontent.com/75984453/121200230-dda05a80-c873-11eb-98dc-78cc1568829b.png)

**Comment by PoketrainerMS** [comment]
this is a repository about the base game, take this to the gamebanana comments or something, just not here. this is not an issue with the base game is it?

**Comment by ninjamuffin99** [comment]
we are not going to add in mods in base game, sorry !
