### ISSUE TITLE
ummm yeah my game is bass boosted XD help.... ;-;

### ISSUE THREAD

**Issue by Chirpysz** [FunkinCrew/Funkin#1251]
playing from:
[Newgrounds](https://www.newgrounds.com/portal/view/770371) 

on opera GX

v0.2.8

I have checked my computer and headphones and tv but on every other game my audio is fine but for some reason on newgrounds fnf is super bass boosted and loudddd ;-;

Bass boost, on week 7 , but it also was for all the other weeks X )

https://user-images.githubusercontent.com/85592350/121272776-b6bb4600-c8be-11eb-9271-394aa9a8e14c.mp4
(sorry if the vid is short) also plus the menu music was boosted too and also the sound effect when selecting story mode and all headings. basically everything was bass boosted
it later got fixed when I refreshed the page but earlier it was like this and I did refresh the page but it wasn't fixed, it was pretty funny tho getting my ears blasted XD , hope this can help others if they are unlucky to get this

**Comment by nickpythonluajava** [comment]
I have heard this happened, try https://nickpythonluajava.github.io/Funkin

**Comment by VMGuy23** [comment]
thats just a KBH Games wrapper

**Comment by nickpythonluajava** [comment]
> thats just a KBH Games wrapper

yeahimstupidlol

**Comment by VMGuy23** [comment]
At _least_ wrap the official uploads.ungrounded.com link!
