### ISSUE TITLE
Question: How do you add two enemy characters to the same song/make them sing at different times?

### ISSUE THREAD

**Issue by MartianBinonwangan** [FunkinCrew/Funkin#1256]
## What is your question? 

(Sorry for the slightly confusing title, I just want to know though). I've seen some mods online where people have added two or more enemy characters to a certain level and make them sing at different times. For example, (not a Mod but) in Cocoa and Eggnog, both the mom and the dad are in the song and sing at different times. When they sing, they have their own unique animations that play. As such, I know it's possible to add two characters to a level and make them sing at different times, playing a different animation depending on which of them is singing. However, I have no idea how to go about it. I've looked at the in-game charting system to see if there was a way to specify which of the two characters are singing. However, as usual, it only allows you to map out the notes for two characters ("bf" and "dad"). I looked at the code to see if there was a way to assign which character was signing what notes in the song. While I did find some information, I still don't understand how you're supposed to assign which characters sing what notes in the song (i.e, dad sings these notes and plays this animation, mom sings these notes and plays this animation). So far, all I've learned is that 1. both characters are considered to be one character and 2. alt animations are needed for each note of the song. As such, I really would like some help or at least some guidance on how I would go about doing this (as I said before, I've seen others do it so I know that the information on how to do it exists). Any ideas (sorry if this is poorly worded in advance)?

**Comment by Windows1Door2Daniel** [comment]
I saw the parents xml file appear as
dad0
dad1
dad2
dad3
mom0
mom1
mom2
mom3
mom4

somthing like that

maybe the XML file can be edited

**Comment by MasterGeorge090** [comment]
For the parents in week 5, inside the xml file has the animations for the parents. It has separate nodes for the note animations for the dad and mom and it can be switched on debug mode by enabling “Alternate animation”. Just note that this feature only affects the character the camera focuses on. If there is no alt animation for a character, the character will freeze.

**Comment by ninjamuffin99** [comment]
alt animation thingie in the charting editor
