### ISSUE TITLE
source/playstate.hx:665: characters 5-19 : Expected :

### ISSUE THREAD

**Issue by mrbabyzombie** [FunkinCrew/Funkin#1257]
I am using Kade engine
I tried removing and adding : and ; multiple times but nothing worked. 
Edit : here is the code im trying to use tell me if there is something wrong
			}
			case 'monkeystage1' | 'monkeystagehell':
			{
				defaultCamZoom = 0.9;
						curStage = 'monkey';
						var bg:FlxSprite = new FlxSprite(-600, -200).loadGraphic(Paths.image('monkeystage1/normal_stage', 'monkeystagehell/normal_stage'));
						bg.antialiasing = true;
						bg.scrollFactor.set(0.9, 0.9);
						bg.active = false;
						add(bg)
			}
I did a little more and now its saying source/PlayState.hx:673: characters 4-5 : Missing ;
the last thing is 673 am i doing anything wrong?

**Comment by ItzRiotz** [comment]
for line 673 I can only assume it's the add(bg) line, it's obviously missing a semicolon
for your original issue, I think it's something to do with you not adding the colon after doing case, anyways I don't have any experience with Haxe, but I do have experience in Java

**Comment by EyeDaleHim** [comment]
Please do not write issues for Kade Engine in the original source code repository. Please do it in the Kade Engine repository though.
