### ISSUE TITLE
Better Issue Organization: "Modding Help" tag. 

### ISSUE THREAD

**Issue by bonkmaykrQ** [FunkinCrew/Funkin#1260]
I see a lot of questions related to modding here, I feel like a new issue template and tag should exist for "Modding Help" with the description "For Haxe compiling errors, glitched sprites, or any other modding problems." 

Not everyone seems to wanna put their questions on Gamebanana for whatever reason and it's kind of inevitable that people are going to end up here, so it's best that we make organization of this extra stuff easier.

**Comment by Steviegt6** [comment]
> 
> 
> I see a lot of questions related to modding here, I feel like a new issue template and tag should exist for "Modding Help" with the description "For Haxe compiling errors, glitched sprites, or any other modding problems."
> 
> Not everyone seems to wanna put their questions on Gamebanana for whatever reason and it's kind of inevitable that people are going to end up here, so it's best that we make organization of this extra stuff easier.

More labels would be really nice, yeah. Thing is, if ninja were to clean up the tracker and sort it better, it'd be smarter to just open up Discussions. He already closed an issue bringing up the idea, though.

**Comment by aflacc** [comment]
A few complaints with this. First of all, this is GitHub and these issues are supposed to be for the source code. There are plenty of Discords that you can use for this kind of stuff like the [Friday Night Modding Community](https://discord.com/invite/YHTFvAEUVu) or [ProjectFNF's discord](https://discord.gg/fmxuXhRqMU) (shameless plug).

**Comment by aflacc** [comment]
Expanding on what I said 2 hours ago, if we had more tags for this stuff it would clutter the issues up with stuff that shouldn't belong in issues. If ninjamuffin99 was to do something like this, I'd suggest he use Discussions for it instead since those are more of a forum based thing that would be better for modding help.

And just like this ProjectFNF has a discussion board so you can ask questions.

**Comment by ninjamuffin99** [comment]
we cleanin up
