### ISSUE TITLE
I GOT A UPDATE IDEA'

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1261]

**Comment by time-guy890** [comment]
if u guys add week 8 cant you make all of the weeks more advance with the weeks graphics like west philly u can make that better

**Comment by nickpythonluajava** [comment]
very interesting

**Comment by VMGuy23** [comment]
What is said idea?

**_I DON'T NEED SLEEP, I NEED ANSWERS_**

**Comment by ACardboardBox1** [comment]
Very interesting idea.

**Comment by jbmagination** [comment]
this is such a good idea this should be in v0.2.9

**Comment by aflacc** [comment]
> #### Please check for duplicates or similar issues before creating this issue.
> ## What is your suggestion, and why should it be implemented?

holy crap this is amazing ninjamuffin why didnt you think of this sooner?

**Comment by VMGuy23** [comment]
ik

**Comment by Windows1Door2Daniel** [comment]
Holy jesus





Great idead

**Comment by HmAhYesTheFloorHereIsMadeOutOfFloor** [comment]
> #### Please check for duplicates or similar issues before creating this issue.
> ## What is your suggestion, and why should it be implemented?

HOLY SHIT YOUR A GENIUS!
