### ISSUE TITLE
I've been compiling for a night and a day 

### ISSUE THREAD

**Issue by ComicHB** [FunkinCrew/Funkin#1263]
I've used "like test windows -final" to compile and it has been building all yesterday and night..
 I know compiling takes long but this long ??? I don't dare to stop it because literally no other compiling method worked before this one (even tho it didn't work yet, it did open the game and works which is more then most of them)
Should I terminate task and try again? I'm using like html5 vs code and source code vanilla (not made engine or anything) 

Alright edit, i closed the game and it stopped building. It just opened the game. didn't creat an .exe. Would anyone know how to create an .exe

**Comment by VMGuy23** [comment]
Try removing -final

**Comment by george2781** [comment]
'lime build windows' I guess? IDK I haven't really tested this in a while

**Comment by VMGuy23** [comment]
Yeah
Is it showing any output at all?

**Comment by VMGuy23** [comment]
By the way there should be an exe in export/<release/debug/final idk which>/windows/bin

**Comment by ComicHB** [comment]
@VMGuy23 
When i try without the final it gives me the same sys error telling me access denied and crash 1. Also sorry if I'm slow but idk how to go to export/release/windows/bin

**Comment by VMGuy23** [comment]
In File Explorer go to the folder you are building from then go onto export, release, windows, bin

**Comment by ComicHB** [comment]
@VMGuy23  you are literally a life savior thank you so much, I'm so dumb I've been stuck on this for like 2 weeks

**Comment by VMGuy23** [comment]
No problem
