### ISSUE TITLE
License suggestion

### ISSUE THREAD

**Issue by Maniues** [FunkinCrew/Funkin#1264]
Hello,
I read why you, @ninjamuffin99  changed the license. I know that you don't want to use GPL, because of problem with platforms such as Nintendo Switch, Xbox, PlayStation and others. I wrote the license which is ideal in this situation.
Actually it's only draft, but if you want to use it, I will publish it as full license.
You can get license copy [here](https://docs.google.com/document/d/1s_jKR50xlz4qSAbBLfNI7qQI7uwiWYLtgdSU9HUCWMs/edit?usp=sharing). It have "later versions" feature, so you probably want to write "You can deal with this game under Open Game Public License version 1. If you contribute to this software, you allow ninjamuffin99 to re-license your contributions under any  version of Open Game Public License".
Currently I don't allow to use this license, because it's only draft.
What you think about this license?

**Comment by aflacc** [comment]
No

**Comment by Maniues** [comment]
> No

Why?

**Comment by aflacc** [comment]
> > No
> 
> Why?

Just no.

**Comment by Maniues** [comment]
> > > No
> > 
> > Why?
> 
> Just no.
any arguments or do you refuse because you don't like?

**Comment by aflacc** [comment]
> > > > No
> > > 
> > > 
> > > Why?
> > 
> > 
> > Just no.
> 
> any arguments or do you refuse because you don't like?

Nope.

**Comment by Maniues** [comment]
> > > > > No
> > > > 
> > > > 
> > > > Why?
> > > 
> > > 
> > > Just no.
> > 
> > any arguments or do you refuse because you don't like?
> 
> Nope.

So close this issue and ban me from all the Funkin repository for issue reporting and PR sending.

**Comment by Maniues** [comment]
@aflacc Oh, is this the moment when it turns out that you are not the owner of this repo and will not do what I wrote to you earlier? So how can you decline suggestions when you're not even a contributor to this game?

**Comment by aflacc** [comment]
> @aflacc Oh, is this the moment when it turns out that you are not the owner of this repo and will not do what I wrote to you earlier? So how can you decline suggestions when you're not even a contributor to this game?

I don't want to

**Comment by Maniues** [comment]
@aflacc So at least tell me why you are rejecting this proposal? If you write your own license, please tell me. If you have consulted an lawyer and he writes licenses, gives advice, write it. Why don't you have any arguments? I took the time to write this, knowing it might be rejected. I have no regret that you rejected it, but that you do not even give arguments or explanations.

**Comment by aflacc** [comment]
idk i just thought it was funny

**Comment by Maniues** [comment]
What's to be funny?

**Comment by Hans5958** [comment]
don't feed the trolls

**Comment by VMGuy23** [comment]
this look good

**Comment by Maniues** [comment]
@VMGuy23  I know that is good idea, but I'm waiting for @ninjamuffin99 comment

**Comment by VMGuy23** [comment]
yeah

**Comment by ninjamuffin99** [comment]
comment

**Comment by nickpythonluajava** [comment]
> comment

comment

**Comment by Maniues** [comment]
> 
> 
> > comment
> 
> comment

comment...

**Comment by VMGuy23** [comment]
> comment

sooooooooooooooooooooo.............. What do you think of it?

**Comment by waleed177** [comment]
the newest license (not legal advice) probably is very ambiguous to work, also open source licenses can't really be revoked so the previous license still applies in the code that was there before u removed it and the forks that have it. (NOT LEGAL ADVICE, I AM NOT A LAWYER) c:

**Comment by waleed177** [comment]
So this license:
https://docs.google.com/document/d/1s_jKR50xlz4qSAbBLfNI7qQI7uwiWYLtgdSU9HUCWMs/edit
allows you to close source your modifications if you port to a restricted platform? doesn't feel like a copyleft license.

Not a lawyer, not legal advice.

**Comment by Maniues** [comment]
> So this license:
> https://docs.google.com/document/d/1s_jKR50xlz4qSAbBLfNI7qQI7uwiWYLtgdSU9HUCWMs/edit
> allows you to close source your modifications if you port to a restricted platform? doesn't feel like a copyleft license.
> 
> Not a lawyer, not legal advice.

It allows to close source code of the game on switch or playstation if there are official port for Linux, windows or JavaScript

**Comment by Maniues** [comment]
> > So this license:
> > https://docs.google.com/document/d/1s_jKR50xlz4qSAbBLfNI7qQI7uwiWYLtgdSU9HUCWMs/edit
> > allows you to close source your modifications if you port to a restricted platform? doesn't feel like a copyleft license.
> > 
> > Not a lawyer, not legal advice.
> 
> It allows to close source code of the game on switch or playstation if there are official port for Linux, windows or JavaScript

Port must be open source

**Comment by Maniues** [comment]
License is unfinished, because @ninjamuffin99 don't want to approve idea or not. I will finish the license, but now I can provide you idea of the license:
You can use play distribute modify and do anything else, but all modified versions must be open source. If you provide game for restricted platforms ( platforms that require be approved developer) you may limit source code distribution, but you must provide port with all functions (except for platform-specific functions such as community functions, multiplayer, controls etc) to at least one non-restricted platform (windows is non-restricted, because you can develop apps without contacting with Microsoft), or offer source code without SDK or distribute public offer source code for other approved developers.
Additionally you can license binaries of the game (for non-restricted platforms) under any license that allow for at least for distributing unmodified binaries.
That is all!

**Comment by waleed177** [comment]
ok cool, but are you going to review it with the FSF or a lawyer or something. Custom licenses are scary in the sense as you don't know if they will hold up in court. so eh.

**Comment by Maniues** [comment]
Until @ninjamuffin99 accepts or rejects the idea, I will not take further steps to create and develop this license publicly for use in FNF, or consult with any lawyer or other person.

**Comment by Maniues** [comment]
@waleed177 I am planning to make a preamble for this license, so in court in USA this license will be interpreted with preamble.

**Comment by ninjamuffin99** [comment]
it gon be apache 2.0
