### ISSUE TITLE
Bug Report: boyfriend_assets XML generation isnt working properly 

### ISSUE THREAD

**Issue by keeganissmelly** [FunkinCrew/Funkin#1265]
Ok so I’m running on windows 10 , I believe its 64 bits but 32 also runs as well , but when. I tried making a custom bf sprite sheet wit adobe , the XML wouldn’t register the note presses , i could miss notes but when i press them bf would continue bobbing his head and not moving , I tested it with the regular bf using the sprite generator and it does the same thing , I’m sure this can be fixed but if anyone has a solution or can send me a better running bf open source assets i would really appreciate , I originally used the gf assets and that worked just fine ,but bf would just bob his head , but everything else works like the “HEY”part and when he gets scared. If theres a fix please let me know 
thank you 
Ps ill upload the sprite sheet and .XML stuff later

**Comment by aflacc** [comment]
You need to select all the stuff in adobe

tell me what shapes you selected when you generated the spritesheet

**Comment by aflacc** [comment]
You need to select this list of shapes in adobe animate to get it working as intended:

- BF Dead Loop
- BF Dead confirm
- BF HEY!!
- BF NOTE DOWN
- BF NOTE DOWN MISS
- BF NOTE UP
- BF NOTE UP MISS
- BF NOTE LEFT
- BF NOTE LEFT MISS
- BF NOTE RIGHT
- BF NOTE RIGHT MISS
- BF dies
- BF hit
- BF idle dance
- BF idle shaking
- bf pre attack
- boyfriend attack
- boyfriend dodge

**Comment by aflacc** [comment]
I don't think **bf pre attack**, **boyfriend attack**, or **boyfriend dodge** are needed atm but just to be safe

**Comment by keeganissmelly** [comment]
> I don't think **bf pre attack**, **boyfriend attack**, or **boyfriend dodge** are needed atm but just to be safe

Oh I did all of that I think I just selected it wrong ,

**Comment by keeganissmelly** [comment]
Yeah I selected it wrong damn it . Ok I think it will be fine now lol
