### ISSUE TITLE
Compiling help: how would one export to html5?

### ISSUE THREAD

**Issue by JavierHD608** [FunkinCrew/Funkin#1266]
i just need help man :(

**Comment by m-obeid** [comment]
To export the game as HTML5, use the following command in your source code path:

lime test html5

**Comment by time-guy890** [comment]
> To export the game as HTML5, use the following command in your source code path:
> 
> lime test html5

 no LIME TEST!!!!!!!!!!!!!

**Comment by nickpythonluajava** [comment]
> > To export the game as HTML5, use the following command in your source code path:
> 
> > 
> 
> > lime test html5
> 
> 
> 
>  no LIME TEST!!!!!!!!!!!!!

I DONT KNOW WHAT UR SAYING LIKE ALL OF THE TIME

**Comment by VMGuy23** [comment]
> > To export the game as HTML5, use the following command in your source code path:
> > lime test html5
> 
> no LIME TEST!!!!!!!!!!!!!

its lowrcase actually

```
****@****:~$ LIME TEST HTML5
LIME: command not found
****@****:~$ lime test html5
Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command
```

just did in my home dir not a funk dir

**Comment by ninjamuffin99** [comment]
`lime test html5`

add `-debug` if you want full debug
add `-final` if you want release version
