### ISSUE TITLE
Bug Report:

### ISSUE THREAD

**Issue by keeganissmelly** [FunkinCrew/Funkin#1268]
so I tested this with kade engine before and then tried using the base engine just to add context . But the open source art assets for bf his XML generation is bugged , when you hit a note he continues his idle animation , but everything else is fine , i then tried testing to see if the sprite sheet generation bugged the normal bf assets, they did the exact same thing he wouldn't move , the other sprites worked tho , him getting scared in week 2, the "hey" animation, everything but the note presses , the most annoying thing is when you miss press a note that shows the missing animation, I'm sure that this isn't a big issue but It would help my development of my mod.I hope this won't disturb the development of the game it's self.
Thank you

**Comment by EyeDaleHim** [comment]
This is not the Kade Engine repository.

**Comment by VMGuy23** [comment]
"and then tried using the bade engine just to add context"

> This is not the Kade Engine repository.

R=They said they tested with base game

**Comment by keeganissmelly** [comment]
> "and then tried using the bade engine just to add context"
> 
> 
> 
> > This is not the Kade Engine repository.
> 
> 
> 
> They said they tested with base game

Yeah I tried using it with the normal engine

**Comment by nickpythonluajava** [comment]
> "and then tried using the bade engine just to add context"
> 
> 
> 
> > This is not the Kade Engine repository.
> 
> 
> 
> They said they tested with base game

🅱️ade engine

🅱️ase game
