### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by treisdentess** [FunkinCrew/Funkin#1269]
Recently, my game has been a little weird, the stage ends before the music ends, and this happens both in the browser and in the program version. My version is 2.7.1 and 2.8, I tried to delete all files referring to the game in AppData but it didn't work.

https://user-images.githubusercontent.com/85908439/121968645-12ffe900-cd49-11eb-834d-db981b72de66.mp4

**Comment by VMGuy23** [comment]
Looks like serious lag.
The audio shouldn't be that speed.

**Comment by prokube** [comment]
speedrun man
