### ISSUE TITLE
Hold-Note Balance Change?

### ISSUE THREAD

**Issue by Squirrel-God** [FunkinCrew/Funkin#127]
Anyone who has played the game knows that hold-notes give back significantly more health than a regular note. This on its own is not a bad thing, however in my experience I believe that these notes give a little too much health back compared to the regular one, and while it does not ruin the game, it does make certain songs fairly easier than they should be, Spookeez is a good example, as many people will get to the ending sequence with a low amount of health and about 7 seconds later their entire health bar is filled up (in this example you are pretty much done with the song, but you get the idea). I believe that it may be a good idea to lower the amount of health hold notes do. Not by much, just enough so that they aren't as strong as they are now, and though I am not yet a game designer I think this can make the game slightly more challenging while keeping it fair.

**Comment by xChillax** [comment]
I dunno why but since the week 4 update, they seem to also take a lot of HP now. I remember at one point it was pretty much a win win situation.
But, I do agree it makes some songs cheaply balanced. It's like "time to beat you up" - "oh wait here is a hp potion". lol

**Comment by Squirrel-God** [comment]
I think that's for the better, since it's an easier note to hit so it should have a larger punishment for missing them.
