### ISSUE TITLE
Compiling help: why cant i test my mod??

### ISSUE THREAD

**Issue by idkwhatn** [FunkinCrew/Funkin#1272]
so i was trying to follow bbpanzu's tutorial and when i type "lime test windows" it shows this :

C:\Users\Home\Desktop\kade github\Kade-Engine-stable>lime test windows

source_val/Discord.hx:5: characters 8-30 : Type not found : discord_rpc.DiscordRpc

source_val/Discord.hx:14: characters 3-13 : Type not found : DiscordRpc

source_val/Discord.hx:24: characters 4-14 : Type not found : DiscordRpc

source_val/Discord.hx:29: characters 3-13 : Type not found : DiscordRpc

source_val/Discord.hx:34: characters 3-13 : Type not found : DiscordRpc

source_val/Discord.hx:39: characters 3-13 : Type not found : DiscordRpc

source_val/Discord.hx:75: characters 3-13 : Type not found : DiscordRpc

C:/Users/Home/Desktop/haxedev/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access

C:/Users/Home/Desktop/haxedev/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

 idk what to do any help is appreciated!! i installed discord_rpc already so im clueless lol

**Comment by ThePlank** [comment]
You're better of making an issue in the KE repo.

**Comment by nickpythonluajava** [comment]
> idk what to do any help is appreciated!! i installed discord_rpc already so im clueless lol

have you ran the setup for discord

**Comment by ThePlank** [comment]
> > > idk what to do any help is appreciated!! i installed discord_rpc already so im clueless lol
> > 
> > 
> > have you ran the setup for discord
> 
> okay so i added the discord_rpc.hx into my source and it shows this:
> 
> C:\Users\Home\Desktop\kade github\Kade-Engine-stable>lime test windows
> source_val/Discord.hx:5: characters 8-30 : Type not found : discord_rpc.DiscordRpc
> source_val/Discord.hx:14: character 3 : `package discord_rpc;` in source_val/DiscordRpc.hx should be `package;`
> C:/Users/Home/Desktop/haxedev/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> C:/Users/Home/Desktop/haxedev/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> 
> what do i do now:(

he said if you have discord installed

**Comment by maska228** [comment]
my god
why tf is this not on kade engine repo

**Comment by ThePlank** [comment]
> my god
> why tf is this not on kade engine repo

logic

**Comment by ninjamuffin99** [comment]
fnf mod
