### ISSUE TITLE
FRIDAY FUNKING IS VIOLENT!!!!! /j (yes /j means joke u idiots)

### ISSUE THREAD

**Issue by nickplj12** [FunkinCrew/Funkin#1274]
THE GaME FRIDAY FUNK NIGHT IS A VIOLENT CUS IT SWER WORD WEN YOU MIS!!! I HATE THIS STUPID GAME IT IS SO VIOLENT AND SWER WORD!!!!!!! FIX THIS OR I WIL STEQL YOUR ORGANS!!!!!!

**Comment by MenonPenguin89420** [comment]
no way swer in fridi nit fucking???? wtf?????

**Comment by jbmagination** [comment]
friday funkin night team should be in JAIL for this crime!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ACardboardBox1** [comment]
i know this is a joke but close so it doesnt fill up the issue tracker or whatever it's called.

**Comment by Zayne42** [comment]
yeah thats kinda the point dumbass

**Comment by nickpythonluajava** [comment]
> yeah thats kinda the point dumbass

welcome to github

**Comment by VSchris-code** [comment]
I swear this is a morbid joke that simulates a karen

**Comment by ACardboardBox1** [comment]
:sob

**Comment by Steviegt6** [comment]
> 
> 
> THE GaME FRIDAY FUNK NIGHT IS A VIOLENT CUS IT SWER WORD WEN YOU MIS!!! I HATE THIS STUPID GAME IT IS SO VIOLENT AND SWER WORD!!!!!!! FIX THIS OR I WIL STEQL YOUR ORGANS!!!!!!

You're required to be 13 years or older to use GitHub IIRC. :trollface:

**Comment by MagerRTF** [comment]
get out of github little kid its supposed to have cuss words

**Comment by jbmagination** [comment]
@Steviegt6 @MagerRTF i think you both are either trolling or dont know what a joke is, but either way it's very funny

**Comment by MagerRTF** [comment]
im ignoring the joke because theres a tone indicator

**Comment by Steviegt6** [comment]
> 
> 
> @Steviegt6 @MagerRTF i think you both are either trolling or dont know what a joke is, but either way it's very funny

![image](https://user-images.githubusercontent.com/27323911/123751278-6a837600-d86c-11eb-9d4a-27d79eef178f.png)

**Comment by ninjamuffin99** [comment]
word?
