### ISSUE TITLE
Bug Report: Audio does not play.

### ISSUE THREAD

**Issue by GreatWhiteTengu** [FunkinCrew/Funkin#1280]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
N/A

### If you are playing a downloaded version of the game, what operating system are you using?
Windows 10 (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
As it only requires me to play the game in order to reproduce the issue, I cannot specify steps.

## Please describe your issue. Provide extensive detail and images if possible.
I've noticed a bunch of people from itch.io and elsewhere are having issues with the game audio not playing when the game starts or throughout play. Adjusting the in-game volume, deleting AppData folders or removing any of the mods (re-installing the base game without mods) does not fix the issue. Any ideas why this might be happening?

**Comment by VMGuy23** [comment]
check your volume?

**Comment by GreatWhiteTengu** [comment]
This doesn't help. I've checked my volume both in game, in volume mixer, I've checked my speakers are working, I've checked which speaker the game is running through and even that one doesn't play audio, I've reinstalled my audio drivers, nothing works.

**Comment by GreatWhiteTengu** [comment]
> check your volume?

This doesn't help. I've checked my volume both in game, in volume mixer, I've checked my speakers are working, I've checked which speaker the game is running through and even that one doesn't play audio, I've reinstalled my audio drivers, nothing works.

**Comment by VMGuy23** [comment]
idk drivers? its probably not a game issue, mine works

**Comment by GreatWhiteTengu** [comment]
> idk drivers? its probably not a game issue, mine works

I already stated that I reinstalled my driver's and checked if they are updated. As far as I'm concerned it should be working.

Also to note; my computer can play the audio files on their own, just not while in game

**Comment by VMGuy23** [comment]
I'm saying: Maybe the adio drivers don;t work wtih HaxeFlixel

**Comment by GreatWhiteTengu** [comment]
> I'm saying: Maybe the adio drivers don;t work wtih HaxeFlixel

Could be? The strange thing is that it did work before a certain date. The other off thing is that it's specifically the downloaded version. All versions online that I've tried seem to work fine.

**Comment by VMGuy23** [comment]
A driver update probably broke the loading of audio in Flixel's sound engine. Web version uses the browser sound so should work

**Comment by GreatWhiteTengu** [comment]
> A driver update probably broke the loading of audio in Flixel's sound engine. Web version uses the browser sound so should work

I'm not sure if this is the case. I found out that changing the sampling rate of the audio on my PC to anything below 48000Hz allowed the game to play with audio. So while I have fixed the issue, I'm not sure why this is the case.

But yeah I guess it's fixed?

**Comment by VMGuy23** [comment]
Maybe it's a lack of support for above CD quality (44100hz)
