### ISSUE TITLE
Bug Report: the game is crashed

### ISSUE THREAD

**Issue by enzo684** [FunkinCrew/Funkin#1284]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371)

### If you are playing the game in a browser, what browser are you using?
Both Chrome and Firefox
### If you are playing a downloaded version of the game, what operating system are you using?
Windows 10
## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.8
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Honestly, i don't really know, programming perhaps?
## Please describe your issue. Provide extensive detail and images if possible.
every time i start playing with any week, when it finishes loading, the screen gets grey and it shows a sad white face with x's for eyes.

**Comment by ThePlank** [comment]
get more ram
