### ISSUE TITLE
Question: Direct download link for Funkin

### ISSUE THREAD

**Issue by RainbowTabitha** [FunkinCrew/Funkin#1285]
## What is your question?
Mind releasing a few binaries on Github Releases so we have a direct download link. This is benificial for software like Winget, Scoop and Chocolately

**Comment by VMGuy23** [comment]
[There's an itch.io page](https://ninja-muffin24.itch.io/Funkin)

**Comment by nickpythonluajava** [comment]
Just do `wget https://w3g3a5v6.ssl.hwcdn.net/build/355764/1359332-archive-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1625169466&Signature=Xuy3d9y3kbq1dekc9rro2Ywr7%2FzvJY16JET7juq5hDT%2BfEyoIzct5e73EPCgNbMtRDz9%2BL1Xnk78VudsC7JjkRVZDnjx2Sm6wErhOzpGQwIovjBBzFOUyJIaQMjqhjluQBLfWluNgEaO86pusmPcgih1BtnpLomaYcE5hkspwBmAn5pxXmkwfncYWo6a8C6%2BvrfsQWCZSYP5F%2B1gJ6YqtbM2h4%2FdbZq0tKJQ43sKhiUaTaXkROBuIicQ6CAKhPx39raj6Aa54sMQJmqfKRBVJPLCL0TzZBb138c%2BPxIbgAz27r%2BCCySb7qZ4dM3g9%2Fc4M9h%2F195LIflI93OMiWOvFA==&hwexp=1625169726&hwsig=4b59269e2d3a72af2b3183b45421d0ee`

**Comment by VMGuy23** [comment]
but does work winows?

**Comment by VMGuy23** [comment]
403 forbidden lol

**Comment by ninjamuffin99** [comment]
yeah, only downloads will be on itch, lol!
