### ISSUE TITLE
Bug Report: The game crashes after replacing any character with mine

### ISSUE THREAD

**Issue by ulisesoru** [FunkinCrew/Funkin#1286]
I compiled the game using cmd and typing "lime test windows" to test my character, the game compiled fine and the game opens normally, the problem is that when entering any of the levels and trying to replace any character with mine when pressing enter the game freezes and closes (I am only testing the sprites of the character, I have not done his week or his musics yet), any ideas of what the problem may be?

**Comment by ThePlank** [comment]
In what folder is your character spritesheet in?

**Comment by ulisesoru** [comment]
its in assets/shared/images/characters, with all the others characters

**Comment by ThePlank** [comment]
is your character added in Character.hx?

Here is a example on how you do this:

```haxe
case 'YourChar':
	tex = FlxAtlasFrames.fromSparrow('assets/images/characters/YourChar.png', 'assets/images/characters/YourChar.xml');
	frames = tex;
	animation.addByPrefix('idle', 'Idle name in Spritesheet', 24, false);
	animation.addByPrefix('singUP', 'Up note name in Spritesheet', 24, false);
	animation.addByPrefix('singDOWN', 'Down note name in Spritesheet', 24, false);
        animation.addByPrefix('singLEFT', 'Left note name in Spritesheet', 24, false);
	animation.addByPrefix('singRIGHT', 'Right name in Spritesheet', 24, false);

        // how much pixels you need to offset it (use it for fixing aligment)
	addOffset('idle', 0, 0);
        addOffset("singUP", 0, 0);
        addOffset("singRIGHT", 0, 0);
	addOffset("singLEFT", 0, 0);
	addOffset("singDOWN", 0, 0);

	playAnim('idle');
```

**Comment by HmAhYesTheFloorHereIsMadeOutOfFloor** [comment]
> is your character added in Character.hx?
> 
> Here is a example on how you do this:
> 
> ```hx
> case 'YourChar':
> 	tex = FlxAtlasFrames.fromSparrow('assets/images/characters/YourChar.png', 'assets/images/characters/YourChar.xml');
> 	frames = tex;
> 	animation.addByPrefix('idle', 'Idle name in Spritesheet', 24, false);
> 	animation.addByPrefix('singUP', 'Up note name in Spritesheet', 24, false);
> 	animation.addByPrefix('singDOWN', 'Down note name in Spritesheet', 24, false);
>         animation.addByPrefix('singLEFT', 'Left note name in Spritesheet', 24, false);
> 	animation.addByPrefix('singRIGHT', 'Right name in Spritesheet', 24, false);
> 
>         // how much pixels you need to offset it (use it for fixing aligment)
> 	addOffset('idle', 0, 0);
>         addOffset("singUP", 0, 0);
>         addOffset("singRIGHT", 0, 0);
> 	addOffset("singLEFT", 0, 0);
> 	addOffset("singDOWN", 0, 0);
> 
> 	playAnim('idle');
> ```

this isnt my issue, but I have the same. I already have it in the hx file. in fact, if i change any character it crashes
