### ISSUE TITLE
Bug Report: Hi! When i try to start the game, all that happens is that the little newgrounds loading screen thing shows and loads some, then stops around half way..

### ISSUE THREAD

**Issue by BrewRaccoon** [FunkinCrew/Funkin#1288]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Hop1337** [comment]
You did not type any useful information, only the "newgrounds loading screen loads then stops half way".

**Comment by Windows1Door2Daniel** [comment]
Did you tried to refresh the page?

There is a rocket for you because why not?

**Comment by AstrobStasis** [comment]
both, and that happened to me once
