### ISSUE TITLE
Bug: Week 6 Icon

### ISSUE THREAD

**Issue by CodeMan98038** [FunkinCrew/Funkin#1289]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by nickpythonluajava** [comment]
what button

**Comment by CodeMan98038** [comment]
hitting 9 on the keyboard to change to icon

**Comment by ThePlank** [comment]
> hitting 9 on the keyboard to change to icon

The 9 icon change is hard-coded so if its disabled it changes to the deafult bf icon
