### ISSUE TITLE
the song M.I.L.F is ending in the middle of the song

### ISSUE THREAD

**Issue by GabrielSSBr** [FunkinCrew/Funkin#129]
![Image11](https://user-images.githubusercontent.com/76743630/103299836-3a057100-49dc-11eb-9ff4-5289b64624d9.jpg)
the music is stopping a little after half, and this is making it impossible for me to pass the music, besides the Bf disappearing in the idle animation.

**Comment by AntonPetrochenko** [comment]
I can confirm. Not sure what exactly is triggering it, I've played through the song a few times and it was fine, now it's ending too early even in freeplay. Some global state messing up?
