### ISSUE TITLE
can add week 7 all assets? i wanna animate week 7

### ISSUE THREAD

**Issue by BitchL** [FunkinCrew/Funkin#1293]
pls

**Comment by ACrazyTown** [comment]
Be patient till the Week 7 source code comes out.

**Comment by fnffanspritemaker** [comment]
ok

**Comment by StyleCannotCodeForShit** [comment]
> Be patient till the Week 7 source code comes out.

OoOooOoh bE pATIeNt it's been 2 fucking months you dipshit

**Comment by ACrazyTown** [comment]
> > Be patient till the Week 7 source code comes out.
> 
> OoOooOoh bE pATIeNt it's been 2 fucking months you dipshit

So? ninjamuffin has a life other than FNF y'know? He shouldn't work on the game non-stop. He's stated himself that the only reason Week 7 source hasn't released is because it's overwhelming and I don't blame him. It's gonna be a big update with lots of new features both for the vanilla game and modders. If anyone's a dipshit here it's you.

**Comment by VMGuy23** [comment]
> > Be patient till the Week 7 source code comes out.
> 
> OoOooOoh bE pATIeNt it's been 2 fucking months you dipshit

DId you know? The Newgrounds link is not yet the first result. That is the requirement. You are the dipshit.

**Comment by StyleCannotCodeForShit** [comment]
Well idk about you, waiting for google to get off it's ass acting like you and google are best buds or sum shit is pretty fucking stupid so I'd deflect that dipshit adjective back on to you

**Comment by StyleCannotCodeForShit** [comment]
> > > Be patient till the Week 7 source code comes out.
> > 
> > 
> > OoOooOoh bE pATIeNt it's been 2 fucking months you dipshit
> 
> So? ninjamuffin has a life other than FNF y'know? He shouldn't work on the game non-stop. He's stated himself that the only reason Week 7 source hasn't released is because it's overwhelming and I don't blame him. It's gonna be a big update with lots of new features both for the vanilla game and modders. If anyone's a dipshit here it's you.

THE WEEK IS LITERALLY FINISHED, I DONT GET WHATS SO OVERWHELMING AND STRESSFUL FOR UPLOADING THE WEEK SOURCE CODE BEING THAT ITS **RIGHT THERE** and I get why it could be overwhelming, but when it comes to literal tiny ass updates that a modder could do in like a week and then release i don't get how it's overwhelming. Being that I suck at modding I'm probably not in the full know of how everything works, but its not like this is my first time knowing wtf the phrase "game development" means.

**Comment by prokube** [comment]
> > > > Be patient till the Week 7 source code comes out.
> > > 
> > > 
> > > OoOooOoh bE pATIeNt it's been 2 fucking months you dipshit
> > 
> > 
> > So? ninjamuffin has a life other than FNF y'know? He shouldn't work on the game non-stop. He's stated himself that the only reason Week 7 source hasn't released is because it's overwhelming and I don't blame him. It's gonna be a big update with lots of new features both for the vanilla game and modders. If anyone's a dipshit here it's you.
> 
> THE WEEK IS LITERALLY FINISHED, I DONT GET WHATS SO OVERWHELMING AND STRESSFUL FOR UPLOADING THE WEEK SOURCE CODE BEING THAT ITS **RIGHT THERE** and I get why it could be overwhelming, but when it comes to literal tiny ass updates that a modder could do in like a week and then release i don't get how it's overwhelming. Being that I suck at modding I'm probably not in the full know of how everything works, but its not like this is my first time knowing wtf the phrase "game development" means.

1. Cutscenes currently do not work on Desktop platforms, as right now the cutscenes are stored as a webm file within the game's assets. Webm files don't work on desktop. **Webm files don't work on desktop.**
2. literally shut up lol

**Comment by StyleCannotCodeForShit** [comment]
1. Lmao they do, have you seen tricky? also they are stored as mp4, not webm

2. Nice argument dumbas

**Comment by StyleCannotCodeForShit** [comment]
Furthermore there is a plugin that allows webm to work

**Comment by ACrazyTown** [comment]
> > > > Be patient till the Week 7 source code comes out.
> > > 
> > > 
> > > OoOooOoh bE pATIeNt it's been 2 fucking months you dipshit
> > 
> > 
> > So? ninjamuffin has a life other than FNF y'know? He shouldn't work on the game non-stop. He's stated himself that the only reason Week 7 source hasn't released is because it's overwhelming and I don't blame him. It's gonna be a big update with lots of new features both for the vanilla game and modders. If anyone's a dipshit here it's you.
> 
> THE WEEK IS LITERALLY FINISHED, I DONT GET WHATS SO OVERWHELMING AND STRESSFUL FOR UPLOADING THE WEEK SOURCE CODE BEING THAT ITS **RIGHT THERE** and I get why it could be overwhelming, but when it comes to literal tiny ass updates that a modder could do in like a week and then release i don't get how it's overwhelming. Being that I suck at modding I'm probably not in the full know of how everything works, but its not like this is my first time knowing wtf the phrase "game development" means.

Pretty sure the week is NOT finished. The 0.2.8 update is simply just a preview or beta because people grew impatient. The actual desktop version of the update will have a shit ton of stuff thats not included in the NG version

**Comment by MrClogsworthYT** [comment]
> 1. Lmao they do, have you seen tricky? also they are stored as mp4, not webm
> 2. Nice argument dumbas

lmao they use spritesheets

**Comment by ADuckInBlack** [comment]
i know this post is completely dead, but god, reading that gave me a headache
