### ISSUE TITLE
Downloaded from sourse code

### ISSUE THREAD

**Issue by joshuaword2alt** [FunkinCrew/Funkin#1296]

**Comment by joshuaword2alt** [comment]
but i use kade

**Comment by ACrazyTown** [comment]
> but i use kade

Well then make an issue on the Kade Engine repository, not here. Close.

**Comment by GGGamesXDlol** [comment]
h

**Comment by nickpythonluajava** [comment]
> h

h?

**Comment by maska228** [comment]
> > h
> 
> h?

h

**Comment by ThePlank** [comment]
> > > h
> > 
> > 
> > h?
> 
> h

h.

**Comment by ACardboardBox1** [comment]
> > > > h
> > > 
> > > 
> > > h?
> > 
> > 
> > h
> 
> h.

i.

**Comment by nickpythonluajava** [comment]
> > > > > h
> 
> > > > 
> 
> > > > 
> 
> > > > h?
> 
> > > 
> 
> > > 
> 
> > > h
> 
> > 
> 
> > h.
> 
> 
> 
> i.

h

**Comment by VMGuy23** [comment]
h

**Comment by prokube** [comment]
h

**Comment by VMGuy23** [comment]
h
