### ISSUE TITLE
I run fnf but it shows only blank screen (Duplicate)

### ISSUE THREAD

**Issue by JorosTheModderPH** [FunkinCrew/Funkin#1297]
`
![20210621_165249](https://user-images.githubusercontent.com/83757828/122735097-4abee180-d2b1-11eb-9752-5a12b093996d.jpg)

System type:x64-based PC
32-bit
RAM:4GB

**Comment by ThePlank** [comment]
> System type:x64-based PC
> 32-bit
> RAM:4GB

For first, why are you using a 32-bit version of windows x64 based processor?
Anyways, it's probally because of having 4GB of RAM, i recommend getting 8GB of RAM.

**Comment by Fixthebug307** [comment]
Welp i guess i can't create fnf android mod,by the way thanks for info.

**Comment by Zayne42** [comment]
**Ok, well I recommend getting either a 64 bit install for windows, or getting a 32 bit processer, and then you might wanna get some ram, recommended is 8gigs to whatever the hell your limit is on ram.**
