### ISSUE TITLE
Bug Report: Problem with building Kade Engine

### ISSUE THREAD

**Issue by PerfectFeebas** [FunkinCrew/Funkin#1298]
Hi,  I haven't seen anyone report this issue so I'll do it :

I'm using Visual Studio 2019 and the version 1.5.2 of Kade Engine.
When I built the game the first, second and third time, everything worked fine, but after that, it only displays this message when I try to build FNF : 

```
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:306: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\XXXXX\Documents\Kade-Engine-stable\export\release\windows\obj>setlocal enabledelayedexpansion
C:\Users\XXXXX\Documents\Kade-Engine-stable\export\release\windows\obj>()
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

And that's not all, I also get this message when I start up the Command Prompt, I get this (written in red btw) : 

```
Enter-VsDevShell : C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat
Au caractère Ligne:1 : 134
+ ... Shell.dll'; Enter-VsDevShell -SetDefaultWindowTitle -InstallPath 'C:\ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [Enter-VsDevShell], FileNotFoundException
    + FullyQualifiedErrorId : DevCmdNotFound,Microsoft.VisualStudio.DevShell.Commands.EnterVsDevShellCommand
```

I don't understand where I messed up, any advice on how to fix that ?

**Comment by ThePlank** [comment]
This is about Kade Engine but install VSCode 2019 Community and include these packages:

MSVC v142 - VS 2019 C++ x64/x86 build tools
and
Windows 10 SDK (any version)

**Comment by SomeoneIsThere14** [comment]
I already have those packages installed, however I installed them again, and the error still occurs.

**Comment by sebby09559** [comment]
you need to create a replays folder in assest for kade engine

**Comment by SomeoneIsThere14** [comment]
> you need to create a replays folder in assest for kade engine

It didn't change anything, besides it doesn't look like the issue comes from that.

**Comment by VMGuy23** [comment]
Where did I put that link again...

https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe
