### ISSUE TITLE
The game seems to think you are winning when idle

### ISSUE THREAD

**Issue by HotSauceBurritos** [FunkinCrew/Funkin#13]
This bug does not occur all the time, but there is a bug that when you remain idle, the game thinks you are not missing any inputs and automatically win.

**Comment by ninjamuffin99** [comment]
I've def heard this before (while not encountering it myself), and I think issue #10 might also be the same issue. Basically don't touch anything, score doesn't go down. I'll peep

**Comment by ninjamuffin99** [comment]
fixed!
