### ISSUE TITLE
Bug Report: Selecting Story Mode or Freeplay just makes the screen go black

### ISSUE THREAD

**Issue by boston2029** [FunkinCrew/Funkin#1300]
Hi, I'm trying to mod FNF, but when I select story mode or freeplay, the screen just goes black and I can't select a song because I can't see anything.
How do I fix this?

**Comment by bwbjustin** [comment]
Check MainMenuState, StoryMenuState, and FreeplayState.

**Comment by boston2029** [comment]
It’s NGIO.hx

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bwbjustin** [comment]
#412

**Comment by boston2029** [comment]
Resolved long time ago
