### ISSUE TITLE
Bug Report: windows.h

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1302]
heya, I tried compiling the game with code sprite etc. but when I compile I get this error
<img width="960" alt="2021-06-22 (26)" src="https://user-images.githubusercontent.com/86324961/122994554-e2532b80-d3a8-11eb-8bb5-b718197ca6df.png">

**Comment by ACrazyTown** [comment]
Looking at the folder name you're compiling Kade Engine, please for the love of god make an issue on the **Kade** Engine repository. This is the original repository for the Vanilla version of the game maintaned by ninjamuffin, Kade Engine's maintained by KadeDev and its different from the Vanilla engine so we can't help you here

**Comment by flashintv** [comment]
> heya, I tried compiling the game with code sprite etc. but when I compile I get this error
> <img alt="2021-06-22 (26)" width="960" src="https://user-images.githubusercontent.com/86324961/122994554-e2532b80-d3a8-11eb-8bb5-b718197ca6df.png">

install Windows SDK 10.0.19041.0
