### ISSUE TITLE
Bug Report: No audio except for a few songs

### ISSUE THREAD

**Issue by GokHyujae** [FunkinCrew/Funkin#1303]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Itch.io

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
N/A

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I have no idea what could have caused this. Last time I played was about a month ago and it was working fine then.

## Please describe your issue. Provide extensive detail and images if possible.
Absolutely no audio would play whenever I try playing the game now. However if I preview the songs in Freeplay, all the songs for Week 4-6 would play except for Satin Panties and Winter Horrorland. The audio files themselves will play fine through media players. This is happening on modded and Kade versions too.

Solutions that I have tried:
-Adjusting the game's volume with 0, -, +
-Checking the sound mixer
-Switching audio devices
-Deleting AppData folders
-Running as admin
-Compatibility mode

I want to try rolling back my version of Windows 10, but I can't seem to roll back to a version that I had when the game was working.

**Comment by bwbjustin** [comment]
These are the only songs with hyphens in them. You might have messed with the file names. Would you check to see if you did? Is it the GitHub build or Itch.io build? Both are vastly different.

**Comment by GokHyujae** [comment]
Ran a fresh install of the itch.io build last night and the issue persisted.

**Comment by GokHyujae** [comment]
Update: Rolled back my Windows 10 updates to a build from early May and the issue still persisted. Asked a friend who was running an up-to-date version of W10 and they said that they were getting sound, so I'm back to having no clue what could be causing this.

**Comment by GokHyujae** [comment]
Update 2: I can get the sound to work on a VM running W10.

**Comment by GokHyujae** [comment]
FIX: Tried changing my sampling rate in the sound control panel to something below 48000 Hz and got the sound back.
