### ISSUE TITLE
Question: I have this error compilating funkin

### ISSUE THREAD

**Issue by TyricSatyric** [FunkinCrew/Funkin#1304]
## What is your question?
I have this error and i have a ApiStuff.hx file created (the black boxes is a privacity thing)
![Captura de pantalla 2021-06-23 171049](https://user-images.githubusercontent.com/63313393/123147831-cced0880-d45f-11eb-809b-94e8b490881d.png)

**Comment by ThePlank** [comment]
you posted this in the wrong repo because there is no line 98 in main.hx and line 311 in storymenustate.hx dosent have a switchstate function

**Comment by GGGamesXDlol** [comment]
srry i have to make this quesition on kade engine xd
