### ISSUE TITLE
HOW TO I COMPILE NOTHING EVEN HELPS

### ISSUE THREAD

**Issue by LiamJamesCortes** [FunkinCrew/Funkin#1306]
i was searching trough google and most of the search results KEEP SAYING "HOW TO MAKE FNF MODS" BUT IM NOT EVEN LOOKING FOR THAT I JUST WANNA LOCK WEEKS AND I KNOW HOW TO DO IT BUT I WANT TO COMPILE AND SOME OF THE RESULTS HAS A TUTORIAL BUT ITS CONFUSING AND DOES NOT EVEN WORK

just pls tell me a easier way and that works

heres a screenshot of the code 0-0
![Screenshot_98](https://user-images.githubusercontent.com/53684982/123176952-3d346380-d439-11eb-8c6f-88e4dd86dc53.png)

**Comment by maska228** [comment]
https://github.com/ninjamuffin99/Funkin/blob/master/README.md#build-instructions

**Comment by ninjamuffin99** [comment]
dont type all caps pls
