### ISSUE TITLE
¿When will the new source come out?

### ISSUE THREAD

**Issue by Xucaaaa** [FunkinCrew/Funkin#1311]
I would like to know a date or estimate of when they will release the new 0.2.8 source for Friday Night Funkin thank you!

**Comment by ACardboardBox1** [comment]
When the newgrounds fnf is top search when you search fnf I think

**Comment by bwbjustin** [comment]
i think muffin just gave up on that and is working on putting the latest source code up

**Comment by ninjamuffin99** [comment]
when its done
