### ISSUE TITLE
Error extension-webm

### ISSUE THREAD

**Issue by YousefTamer67** [FunkinCrew/Funkin#1313]
I was trying to compile it but look

![Screenshot (141)](https://user-images.githubusercontent.com/82932252/123551622-e26d7580-d772-11eb-8c40-f7e8ed6064c5.png)

**Comment by ThePlank** [comment]
mmm yes extention-webm totaly is needed for the base game
pls post in kadengine

**Comment by FacuXit0I** [comment]
I recommend you do not put cinematics, since only the tricky mod that I know has the cinematics configured and in a very rare code that a YouTube video or tutorial you will not find, better wait until week 8 to do your week without mistakes!

**Comment by FacuXit0I** [comment]
Or you can make your mod, based on the tricky source, with the menu, the fire notes and all that https://github.com/KadeDev/trickster/

**Comment by FacuXit0I** [comment]
Or also the kade engine default, which I saw that they already removed the support for Cutscenes https://github.com/KadeDev/Kade-Engine

**Comment by YousefTamer67** [comment]
Help me

**Comment by YousefTamer67** [comment]
I want to compile the game

**Comment by Fefecomitre** [comment]
uninstall extension webm and actuate.
Then at the same command prompt, run:
haxelib install actuate
haxelib git extension-webm
then run the rebuild command
if neko crashes or something, open a new command prompt and keep trying. If after like, 3 times of trying, open command prompt as admin and run in there, it worked for me
![image](https://user-images.githubusercontent.com/77512259/123789187-439c6280-d8b3-11eb-8665-77d007e6d9bb.png)
also make sure THIS Appears after running the command

**Comment by nickpythonluajava** [comment]
> if neko crashes or something, ...

"Neko"

**Comment by VMGuy23** [comment]
that's a build target
