### ISSUE TITLE
Bug Report: Freeze

### ISSUE THREAD

**Issue by fnffan1lol** [FunkinCrew/Funkin#1315]
so i dont know what happened but for some reason whe i was playing i paused on the song Satin Panties and the vocals went on but the notes were not moving and the beat wouldn't sync

**Comment by VMGuy23** [comment]
that happens sometimes.

its not a bug, just it being slightly slow

**Comment by time-guy890** [comment]
If you want it to stop `Play 'Debug mode`

**Comment by time-guy890** [comment]
> that happens sometimes.
> 
> its not a bug, just it being slightly slow

Nah DAT NONSENSE BOIIIIIIII

**Comment by VMGuy23** [comment]
stop

**Comment by ACardboardBox1** [comment]
> 
> 
> If you want it to stop `Play 'Debug mode`

that isnt a thing what

**Comment by ACardboardBox1** [comment]
> 
> 
> > that happens sometimes.
> > its not a bug, just it being slightly slow
> 
> Nah DAT NONSENSE BOIIIIIIII

it's B-Si all over again 😞

**Comment by ThePlank** [comment]
> > > that happens sometimes.
> > > its not a bug, just it being slightly slow
> > 
> > 
> > Nah DAT NONSENSE BOIIIIIIII
> 
> it's B-Si all over again 😞

oh no there will be another issue about me
