### ISSUE TITLE
Question: Why

### ISSUE THREAD

**Issue by YousefTamer67** [FunkinCrew/Funkin#1316]
why i want to compile it
![Screenshot (143)](https://user-images.githubusercontent.com/82932252/123600676-31f58500-d7f7-11eb-8342-ceacadd6da58.png)

**Comment by UserUNP** [comment]
are you trying to make an html5 build?

**Comment by UserUNP** [comment]
i think it means you don't have the "extension-webm" package

**Comment by YousefTamer67** [comment]
i am trying to make a windows build

**Comment by UserUNP** [comment]
then do `lime test windows -debug` or `lime test windows` if you don't want the debug screen

**Comment by siky112** [comment]
![forgod](https://user-images.githubusercontent.com/20342336/129977129-f979f8a9-34cb-427b-8c0e-9c7e1d52af46.png)
i am mr comedy

**Comment by ninjamuffin99** [comment]
fnf mod
