### ISSUE TITLE
Question: I do not know what to do

### ISSUE THREAD

**Issue by LunarHarvey** [FunkinCrew/Funkin#1318]
## What is your question?
Its saying 
```
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```
even though i have everything installed with visual studio 2019 and 2017 with all the induvidual components and that and Visual Studio Code installed with all the plugins necasary
so i dont know what to do anymore

**Comment by LunarHarvey** [comment]
I figured it out

**Comment by VMGuy23** [comment]
https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe
