### ISSUE TITLE
Bug Report: when i change anything, it crashes on loading the change

### ISSUE THREAD

**Issue by Supertube56** [FunkinCrew/Funkin#1319]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
compiling the source code for windows & html5

## What version of the game are you using? Look in the bottom left corner of the main menu.
source code
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
change anything song wise, if i add a song following all the steps, adding the data files and music files ect. or even if i move songs to other weeks.
## Please describe your issue. Provide extensive detail and images if possible.
im trying to make a mod, i followed ep1 and ep2 of BrightFyre's tutorial and even tried starting over a few times but when i change anything to do with weeks and songs if i try to run anything thats been changed it crashes and says null object reference, with html5 test it just freezes.. pls help
![Untitled](https://user-images.githubusercontent.com/57453031/123687854-4e221200-d849-11eb-819a-3c5a6cf36b3f.png)

**Comment by Supertube56** [comment]
![image](https://user-images.githubusercontent.com/57453031/123688884-7e1de500-d84a-11eb-8395-44c0d280e126.png)
this is what shows up in the thingy when it crashes

**Comment by time-guy890** [comment]
uhhhh..........  `Play 'DEBUG.js' To 'Friday Night Funkin' add 'DEVICE GAMEPAD  `

**Comment by VMGuy23** [comment]
> uhhhh.......... `Play 'DEBUG.js' To 'Friday Night Funkin' add 'DEVICE GAMEPAD `

thats not useful now shut up

**Comment by ACrazyTown** [comment]
Can't really do much without access to the codes, you should try asking in a modding discord serve or something

**Comment by time-guy890** [comment]
> > uhhhh.......... `Play 'DEBUG.js' To 'Friday Night Funkin' add 'DEVICE GAMEPAD `
> 
> thats not useful now shut up

SHUT UP IT IS USEFUL *CAN SOMEONE HELP ME PLS!?*

**Comment by VMGuy23** [comment]
> > > uhhhh.......... `Play 'DEBUG.js' To 'Friday Night Funkin' add 'DEVICE GAMEPAD `
> > 
> > 
> > thats not useful now shut up
> 
> SHUT UP IT IS USEFUL _CAN SOMEONE HELP ME PLS!?_

It isn't. One more thing and you're account's getting flagged

**Comment by nickpythonluajava** [comment]
> > > uhhhh.......... `Play 'DEBUG.js' To 'Friday Night Funkin' add 'DEVICE GAMEPAD `
> 
> > 
> 
> > thats not useful now shut up
> 
> 
> 
> SHUT UP IT IS USEFUL *CAN SOMEONE HELP ME PLS!?*

i went through your repos and you said your age was 7

**Comment by VMGuy23** [comment]
I flagged his account

**Comment by ACardboardBox1** [comment]
> 
> 
> uhhhh.......... `Play 'DEBUG.js' To 'Friday Night Funkin' add 'DEVICE GAMEPAD `

oh my fucking god 
shut up

**Comment by ACardboardBox1** [comment]
> 
> 
> > > > uhhhh.......... `Play 'DEBUG.js' To 'Friday Night Funkin' add 'DEVICE GAMEPAD `
> > 
> > 
> > > 
> > 
> > 
> > > thats not useful now shut up
> > 
> > 
> > SHUT UP IT IS USEFUL _CAN SOMEONE HELP ME PLS!?_
> 
> i went through your repos and you said your age was 7 and on your scratch profile it said you were "done with 2nd grade"

https://github.com/time-guy890/Dang-that-lil-crap/commit/aad39928bf3387959fe63f75ce31cbe36aa237f4 dang you were actually right
