### ISSUE TITLE
Bug Report: Charting menu going black

### ISSUE THREAD

**Issue by nickplj12** [FunkinCrew/Funkin#1320]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
x86_64
## What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.2 (but this problem **MAY** persist on itch.io release of main game)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
- Go in the charting menu
- Go to 'Section'
- Change the box under 'Change BPM' to 1 (it was set as default to 0 by a glitch possibly?)
- It opens the console and when I press enter, it just goes black 
## Please describe your issue. Provide extensive detail and images if possible.
<img width="960" aria-label="rip" src="https://user-images.githubusercontent.com/78268270/123708948-3e4f0180-d83a-11eb-8214-38c6d554d8bf.PNG">

(i'm using Vs. Shaggy)

**Comment by VMGuy23** [comment]
pr in kade

not here

**Comment by time-guy890** [comment]
Go to the game code And type in `Add 278666528` or `1001110011100000011011001010100101110011111111110000000000001111`

**Comment by time-guy890** [comment]
or its the device

**Comment by VMGuy23** [comment]
> Go to the game code And type in `Add 278666528` or `1001110011100000011011001010100101110011111111110000000000001111`

Shut up

**Comment by ACardboardBox1** [comment]
> 
> 
> Go to the game code And type in `Add 278666528` or `1001110011100000011011001010100101110011111111110000000000001111`

shut. the. FUCK. up

**Comment by nickpythonluajava** [comment]
> Go to the game code And type in `Add 278666528` or `1001110011100000011011001010100101110011111111110000000000001111`

I already reported you fam ![image](https://user-images.githubusercontent.com/78268270/124159682-6b352b80-da69-11eb-8026-5cc64f8d9c68.png)

**Comment by ACardboardBox1** [comment]
> 
> 
> > Go to the game code And type in `Add 278666528` or `1001110011100000011011001010100101110011111111110000000000001111`
> 
> I already reported you fam ![image](https://user-images.githubusercontent.com/78268270/124159682-6b352b80-da69-11eb-8026-5cc64f8d9c68.png)

👍 👍 👍 
🥇

**Comment by nickpythonluajava** [comment]
> pr in kade
> 
> 
> 
> not here

edited

> ## What version of the game are you using? Look in the bottom left corner of the main menu.
> KE 1.2 (but this problem **MAY** persist on itch.io release of main game)

**Comment by ACardboardBox1** [comment]
i've had this happen to me on the newgrounds version and itch io version of the main game so

**Comment by VMGuy23** [comment]
> > > Go to the game code And type in `Add 278666528` or `1001110011100000011011001010100101110011111111110000000000001111`
> > 
> > 
> > I already reported you fam ![image](https://user-images.githubusercontent.com/78268270/124159682-6b352b80-da69-11eb-8026-5cc64f8d9c68.png)

did too

**Comment by MichaelEpicA** [comment]
> Go to the game code And type in `Add 278666528` or `1001110011100000011011001010100101110011111111110000000000001111`

what does this actually do
