### ISSUE TITLE
i dunno if is only my PC but in the week 4 and 5 of FNF mom and dad does'nt are there Bug Report: 

### ISSUE THREAD

**Issue by T-Carrillo** [FunkinCrew/Funkin#1322]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by time-guy890** [comment]
ITS YOUR PC

**Comment by VMGuy23** [comment]
SHUT UP TIME GUY, NEXT TIME ACTUALLY BE USEFUL

IVE HAD ENOUGH OF YOU

**Comment by ACrazyTown** [comment]
> ITS YOUR PC

if youre gonna comment actually know what ur commenting about lmaoo

**Comment by ACardboardBox1** [comment]
> 
> 
> ITS YOUR PC

close your damn mouth

**Comment by nickpythonluajava** [comment]
> ITS YOUR PC

damn it shut up ur actually 7 in real life

**Comment by boston2029** [comment]
Brother you didn't even answer the questions

**Comment by Cheemsandfriends** [comment]
> 
> 
> ITS YOUR PC

shutup
