### ISSUE TITLE
Error: Could not find haxelib "polymod", does it need to be installed?

### ISSUE THREAD

**Issue by Rabla2z** [FunkinCrew/Funkin#1326]
Error: Could not find haxelib "polymod", does it need to be installed?
This is an error i have compiling the game. What's the command (if there's one) to install "polymod"?

**Comment by nickpythonluajava** [comment]
`haxelib install polymod`
`haxelib run setup polymod`

**Comment by VMGuy23** [comment]
you dont need to run setup everythimg

**Comment by Rabla2z** [comment]
haxelib install polymod
it does not work

**Comment by nickpythonluajava** [comment]
> haxelib install polymod
> 
> it does not work
> 
> 

I made mistake try:
`haxelib git polymod https://github.com/larsiusprime/polymod.git`

**Comment by Rabla2z** [comment]
i get this error when i attempt
Error: Could not use git, please make sure it is installed and available in your PATH.

**Comment by VMGuy23** [comment]
https://git-scm.com/ get git-scm

**Comment by Rabla2z** [comment]
did it!
now it shows this ; Error: Could not find haxelib "discord_rpc", does it need to be installed?

**Comment by VMGuy23** [comment]
install discord rpc as stated in the readme then

**Comment by EnergeticInkBlob** [comment]
it shows me Error: Could not find haxelib "hxCodec", does it need to be installed?

**Comment by TheKitBoi** [comment]
> it shows me Error: Could not find haxelib "hxCodec", does it need to be installed?

Mate ur using psych install it
