### ISSUE TITLE
Bug Report: source_FORMOD/StoryMenuState.hx:34: characters 10-11 : Expected ]

### ISSUE THREAD

**Issue by Smiley-official** [FunkinCrew/Funkin#1327]
Guys, can you help me? I have a one error when i want add new week: source_FORMOD/StoryMenuState.hx:34: characters 10-11 : Expected ] . If you can help me please add a comment. Pls.
[StoryMenuState.hx.txt](https://github.com/ninjamuffin99/Funkin/files/6750209/StoryMenuState.hx.txt)

**Comment by co4ekmc** [comment]
I use Kade-engine 1.5.2.

**Comment by nickpythonluajava** [comment]
> I use Kade-engine 1.5.2.

[Post here](https://github.com/KadeDev/KadeEngine/issues)

**Comment by VMGuy23** [comment]
[StoryMenuState.hx.txt](https://github.com/ninjamuffin99/Funkin/files/6750602/StoryMenuState.hx.txt)
Fixed it. You were missing a comma

**Comment by co4ekmc** [comment]
> [StoryMenuState.hx.txt](https://github.com/ninjamuffin99/Funkin/files/6750602/StoryMenuState.hx.txt)
> Fixed it. You were missing a comma
No, i have a new problem, source_FORMOD/StoryMenuState.hx:48: characters 8-9 : Expected ]

**Comment by co4ekmc** [comment]
> [StoryMenuState.hx.txt](https://github.com/ninjamuffin99/Funkin/files/6750602/StoryMenuState.hx.txt)
> Fixed it. You were missing a comma

You know what? I fixed them, i added commas (In the week names and week characters) and it worked!
