### ISSUE TITLE
Fake or real ninjamuffin's email report and ban 100 game GOOGLE PLAY?

### ISSUE THREAD

**Issue by Ted187** [FunkinCrew/Funkin#1328]
## What is your question?
Hi, I'm an Asian Dev. Our team has been creating some FNF vers on the Mobile Platform. However, we have some issues with the copyright. An email: **cameron.taylor.muffins@gmail.com** sent a report to Google and said that: 
He is the copyright owner or is authorised to act on behalf of the owner of an exclusive right that is allegedly infringed.
- The name of his video game "Friday Night Funkin'"
- Artwork of the main characters of the video game (Boyfriend, Pico, Sarvente, Daddy, Monster, Whitty, Senpai, and Girlfriend).
So, our game is banned.
I know that you let everyone use your data freely to create games and I don't think that mail is from you. You're trying to develop an open-source community. So I strongly believe that's not your mail. Can you help me to confirm that mail is real or fake? :((

**Comment by trayfellow** [comment]
i dont think thats the real ninjamuffin and isnt this his email?

![image](https://user-images.githubusercontent.com/48515908/124259246-803cb800-db58-11eb-81bd-2bdb77a50dfd.png)

**Comment by Ted187** [comment]
I think he will not spend time reporting other games like our game :)) just
someone wants to ban our game.

Vào Th 6, 2 thg 7, 2021 vào lúc 17:11 trayfellouch ***@***.***>
đã viết:

**Comment by Windows1Door2Daniel** [comment]
IDK if that Cameron E-Mail but in his Github account info is cameron.taylor.ninja@gmail.com

Pico and Sarvente aren't NinjaMuffin property

And i don't think his game Songs, Characters, Images, etc are copyrigthed

But the mobile games of FNF are so bad made that some people hate it

**Comment by nickpythonluajava** [comment]
i dont think any characters audio, images, or music of the game is copyrighted. thats why people make mods

i also see various fnf clones on app store as well

![image](https://user-images.githubusercontent.com/78268270/124289743-a6466600-db20-11eb-827f-cba01df83dc9.png)

**Comment by Windows1Door2Daniel** [comment]
Even so. If the Email is fake

That Gmail account owner is commiting 
a ilegal action

**Comment by Windows1Door2Daniel** [comment]
Pretend to be another person is a crime

Even on gamil

**Comment by mryakhont** [comment]
We have also got this issue with my Fnf mode game. Someone reported that it was Copyright infringement. 
But as I know, Fnf is an open-source project. Therefore all art and music are not copyrighted. 
@ninjamuffin99  could you please confirm about the copyright? 
I even can donate to use your Fnf art and music.

**Comment by ninjamuffin99** [comment]
thats not how copyright and open source works, AND you generally are NOT allowed to use trademarks (FNF, Friday Night Funkin) under the Apache 2.0 license (which the game is licensed under).

the games audio, art, music, etc. is generally still copyrighted. 

Right now its in a gray area where we allow use of it all for FAN MADE CONTENT, and not scummy mobile games trying to use our efforts for a quick dollar. The reason all of these other ones are up, is because its a lot of effort to go through to take each and every one down, and we are a tiny team, so we can easily get taken advantage of that way. But I think I'm going to stay more vigilant with this shit cuz u guys r being dumb.

**Comment by mryakhont** [comment]
Hi @ninjamuffin99 , 
Thank for your quickly feedback. 
I got it. 
Regards,

**Comment by Windows1Door2Daniel** [comment]
> thats not how copyright and open source works, AND you generally are NOT allowed to use trademarks (FNF, Friday Night Funkin) under the Apache 2.0 license (which the game is licensed under).
> 
> the games audio, art, music, etc. is generally still copyrighted.
> 
> Right now its in a gray area where we allow use of it all for FAN MADE CONTENT, and not scummy mobile games trying to use our efforts for a quick dollar. The reason all of these other ones are up, is because its a lot of effort to go through to take each and every one down, and we are a tiny team, so we can easily get taken advantage of that way. But I think I'm going to stay more vigilant with this shit cuz u guys r being dumb.

We are not lawyers, so we don't know

**Comment by Windows1Door2Daniel** [comment]
> > thats not how copyright and open source works, AND you generally are NOT allowed to use trademarks (FNF, Friday Night Funkin) under the Apache 2.0 license (which the game is licensed under).
> > the games audio, art, music, etc. is generally still copyrighted.
> > Right now its in a gray area where we allow use of it all for FAN MADE CONTENT, and not scummy mobile games trying to use our efforts for a quick dollar. The reason all of these other ones are up, is because its a lot of effort to go through to take each and every one down, and we are a tiny team, so we can easily get taken advantage of that way. But I think I'm going to stay more vigilant with this shit cuz u guys r being dumb.
> 
> We are not lawyers, so we don't know

So chill the f*ck up

**Comment by VMGuy23** [comment]
> under the Apache 2.0 license (which the game is licensed under). 

no it isn't

**Comment by nickpythonluajava** [comment]
> > under the Apache 2.0 license (which the game is licensed under). 
> 
> 
> 
> no it isn't

lmao

**Comment by muafakul** [comment]
**WOWOWOWOWOOWOWOOWO ,,,SOUNDS GREAT**

**Comment by VMGuy23** [comment]
> > > under the Apache 2.0 license (which the game is licensed under).
> > 
> > 
> > no it isn't
> 
> lmao

it sed to be

**Comment by Lgmrszd** [comment]
Pretty sure the license file was changed so modders won't have to wrap their head around all corner cases, but seeing all crappy mobile clones I'm pretty sure the license is going to be changed back.
