### ISSUE TITLE
Double Notes not working

### ISSUE THREAD

**Issue by beepcheap** [FunkinCrew/Funkin#133]
The only song I can really think of besides Monster which has two notes happening at the same time is Dadbattle, and the issue with it is only one note will be hit when going for both. I'm pretty sure it has something to do with membrane type keyboards, but basically all it does is kind of make it impossible to hit one of those except under extreme circumstances when it will miraculously  hit both.

**Comment by funnynin** [comment]
It's not due to your keyboard. As far as I can tell, jumps (2 notes at once) work fine on the desktop build, but not on ng.

Is this a problem with html5 inputs?
Doesn't seem to be related to dropping notes during fast streams, as that also happens on desktop.

**Comment by HumanDude** [comment]
This is also an issue with faster maps. On week 4 the notes are very fast and close together on some parts. This results in me missing some notes so its not just double notes. I'll try the downloaded version instead though, I just don't use it because it lacks a leaderboard and auto updates.
