### ISSUE TITLE
i wish there are unity project 

### ISSUE THREAD

**Issue by stickylabdev** [FunkinCrew/Funkin#1330]
## What is your question?
just it

**Comment by ThePlank** [comment]
> #### Please check for duplicates or similar issues before asking your question.
> ## What is your question?
> just it

hey there is something on the github page
![image](https://user-images.githubusercontent.com/75984453/124348853-ac097d80-dbec-11eb-89a3-98d9c342b044.png)

there is no way to convert haxeflixel projects to unity because haxe is not equal to c#

please close

**Comment by muafakul** [comment]
dang, ok ,

**Comment by Maniues** [comment]
in theory you can convert Haxeflixel functions to Unity, but it will take a long time and you will have to convert not only code but textures and assets as well.
If you are bored and want to take the challenge, check it out, it will help you to convert Haxe to C#. Next, convert API and functions: https://haxe.org/manual/target-cs-getting-started.html

**Comment by muafakul** [comment]
the problem is im too stupsldkjfls

**Comment by prokube** [comment]
> the problem is im too stupsldkjfls

mood :+1:

**Comment by polybiusproxy** [comment]
lol ninjamuffin closed
