### ISSUE TITLE
Bug Report: 32-bit is a pain in the ass to play

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1332]
Alright, for some reason when i use my 32-bit version of the game, my game crashes + spawns plenty of black boxes
I'm using the week 6 update downloaded on my windows 10 32-bit (pro edition) and it is a fucking pain in the ass to play.
Here's a screenshot: 
![image](https://user-images.githubusercontent.com/86873805/124349947-0c241200-dc35-11eb-8525-b45ad1990558.png)
Here are a few more problems with the 32-bit version: the tutorial has late timing
spookeiz south, blammed, and philly nice, DadBattle, and week 4 entirely crashes the game, along with the retry crashing the game. However, week 6 does work. In fact, it's the only week that works. Really hope in the downloadable week 7 update, this all gets fixed, however chances of this is unlikely. I would also really like to know why this accours in the first place, whatever it is, i would love to be fixed so i can get freaky on low-end friday nights.

**Comment by ThePlank** [comment]
How much RAM do you have?

**Comment by sametdze** [comment]
> How much RAM do you have?

4.00 GB

**Comment by sametdze** [comment]
> How much RAM do you have?

4.00 GB

**Comment by sametdze** [comment]
> How much RAM do you have?

4.00 GB

**Comment by ACrazyTown** [comment]
You probably dont have much available ram to use so it cant load all the textures. x86 is really outdated too, so much that Windows 11 wont have a 32bit version

**Comment by sametdze** [comment]
> You probably dont have much available ram to use so it cant load all the textures. x86 is really outdated too, so much that Windows 11 wont have a 32bit version

Should've said this in the actual post however I have seen multiple people have a similar problem to mine, (on the itch.io page) here are a few screenshots. I think that this probably debunks your ram theory 
![1](https://user-images.githubusercontent.com/86873805/124350911-b6eaff00-dc3a-11eb-8d75-0c171c1743ec.PNG)
![2](https://user-images.githubusercontent.com/86873805/124350913-bb171c80-dc3a-11eb-85f4-976cb21f5ba4.PNG)
![3](https://user-images.githubusercontent.com/86873805/124350920-c8340b80-dc3a-11eb-8152-90b8cea7ae6b.PNG)
![4](https://user-images.githubusercontent.com/86873805/124350923-cb2efc00-dc3a-11eb-8c6b-5dfa42cec6d9.PNG)
However i agree with you that x86 is outdated. However I do not have enough money to get a 64-bit processor.

**Comment by ACrazyTown** [comment]
If I remember correctly, the x86 (32bit) architecture supports up to 4GB ram, so it can either be:
a) Lack of available memory - People having too much programs open in the background + the system itself leaving a not enough big amount of ram to load the assets
or
b) FNF/Haxe simply isn't optimized for 32bit targets

**Comment by Fixthebug307** [comment]
Lol

**Comment by KitOdin** [comment]
try compressing the sprite sheets, and maybe crop out the empty spaces in said spritesheets. that will most definitely work

**Comment by ACrazyTown** [comment]
> try compressing the sprite sheets, and maybe crop out the empty spaces in said spritesheets. that will most definitely work

pretty sure that would just fuck up the sprites, as the spaces are generated by adobe animate and are linked to the xml

**Comment by KitOdin** [comment]
it works for me, no crashed nor anything, heck mid fight masses spritesheets are optimized via cropping and they work fine as fuck.
