### ISSUE TITLE
Let other languages players play FNF with their languages

### ISSUE THREAD

**Issue by Windows1Door2Daniel** [FunkinCrew/Funkin#1333]
Even tho i talk english and i know spanish

NinjaMuffin99 hizo un simulador de citas de Combate de Locura

I care about other people who don't talk english 

I find FNF mods that is only the game but ttranslated in many languages

Would be good if the game have different languages

**Comment by ninjamuffin99** [comment]
wrong repo

**Comment by polybiusproxy** [comment]
> Even tho i talk english and i know spanish
> 
> NinjaMuffin99 hizo un simulador de citas de Combate de Locura
> 
> I care about other people who don't talk english
> 
> I find FNF mods that is only the game but ttranslated in many languages
> 
> Would be good if the game have different languages

"i know spanish"

dont lie lmao
i can clearly see you used a translator

**Comment by Windows1Door2Daniel** [comment]
> > Even tho i talk english and i know spanish
> > NinjaMuffin99 hizo un simulador de citas de Combate de Locura
> > I care about other people who don't talk english
> > I find FNF mods that is only the game but ttranslated in many languages
> > Would be good if the game have different languages
> 
> "i know spanish"
> 
> dont lie lmao
> i can clearly see you used a translator

I seriously know spanish

**Comment by Windows1Door2Daniel** [comment]
> wrong repo

Cool

**Comment by polybiusproxy** [comment]
> > > Even tho i talk english and i know spanish
> > > NinjaMuffin99 hizo un simulador de citas de Combate de Locura
> > > I care about other people who don't talk english
> > > I find FNF mods that is only the game but ttranslated in many languages
> > > Would be good if the game have different languages
> > 
> > 
> > "i know spanish"
> > dont lie lmao
> > i can clearly see you used a translator
> 
> I seriously know spanish

"combate de locura"
lmao
translator 100%

**Comment by Windows1Door2Daniel** [comment]
I forgot la

Combate de la locura

**Comment by polybiusproxy** [comment]
> I forgot la
> 
> Combate de la locura

Actually, in Spanish, names aren't translated.

For example:

- If in English, the game you are referencing is called "Madness Combat", then in Spanish, it would be: "Madness Combat".

By the way, Madness Combat translated to Spanish would be "Combate demencial".
There are several traductions for "madness". It occurs on almost every word.

**Comment by polybiusproxy** [comment]
But your idea is actually good. "Localization".
If you live in Spain, FNF changes to the spanish language.
If you live in USA, FNF changes to the english language!

Sadly, this idea would require a lot of changing assets.

**Comment by VMGuy23** [comment]
> If you live in USA, FNF changes to the english language!

Or the UK. Or Australia

**Comment by Windows1Door2Daniel** [comment]
Or México where i live

Spanish

**Comment by upintheairsheep** [comment]
I wanted to contribute by adding support for Latin, Ancient Greek, Old English, Ancient Egyptian, and Proto Indo European but no language option exists.
