### ISSUE TITLE
Question: SNIFF in data files

### ISSUE THREAD

**Issue by Lamba2** [FunkinCrew/Funkin#1335]
## What is your question?

so basically i looked in the week7 files and then i found "generatedBy":"SNIFF ver.6"} im wondering what this is 
(Dont Read Part: also if it is a program you made could you release it ?)
![what0](https://user-images.githubusercontent.com/85110310/124361373-2ce96900-dc2f-11eb-8b09-609eaad40d63.PNG)

**Comment by pumpkinGithub** [comment]
What i believe that is, is the SiIva Note Importer For FNF by PrincessMtH\
https://github.com/PrincessMtH/SNIFF

**Comment by pandajustgaming** [comment]
Bruh

**Comment by ninjamuffin99** [comment]
yeah, its charts made with MtH's SNIFF tool, which pumpkinGithub nicely linked, thanks!

**Comment by pandajustgaming** [comment]
I'm confused on why you don't care that I searched In the week 7 files even though it isn't released yet

**Comment by pumpkinGithub** [comment]
no problemo
