### ISSUE TITLE
Question: Will there be a linux update anytime soon?

### ISSUE THREAD

**Issue by xenoxriar** [FunkinCrew/Funkin#1337]
## What is your question?
In the title. Self-explanatory.

**Comment by VMGuy23** [comment]
yeah we're stuck on v0.2.7

just saying, install q4wine and then download the windows build, then rrun it

**Comment by nickpythonluajava** [comment]
> yeah we're stuck on v0.2.7
> 
> 
> 
> just saying, install q4wine and then download the windows build, then rrun it

this works

**Comment by VMGuy23** [comment]
its what i do for fnf mods

**Comment by Noxellar** [comment]
Cool. Wish linux would get an update but that's alright. Thank you
