### ISSUE TITLE
Question??

### ISSUE THREAD

**Issue by Im-listening** [FunkinCrew/Funkin#1338]
I tried to keep up with this stuff I did the tutorials blah blah blah and im so fucking tired of the visual studio with the fucking expected shit and bracets and stuff when I clearly did those things yet it still acts like. a bitch and dosent let me compile the fucking game im so tired of this im just gonna give up on the mod and just do something new-

**Comment by ThePlank** [comment]
its probally because you aint addin semicolors after every line
