### ISSUE TITLE
Enhancement + Fix to Hardcoding Issue: 

### ISSUE THREAD

**Issue by mdluffy1234** [FunkinCrew/Funkin#1340]
Hey guys, I saw the video that Tech Rules made on you guys, And I found out that y'all had an issue on levels being hard-coded that prevented you from releasing week 7, and also making modding the game generally harder. My suggestion is to pretty much take all of the existing weeks and any future weeks and making them into their own "fnf" files, which the main FNF program could extract and play.

Also, to make it a bit easier and also to open up this new feature to the modding community, I suggest you base this "fnf" extension off of the 7z system.

I just want to say, that I am pretty much on the same level as Yandev at visual code (like UE4 Blueprint), let alone typed out code. Although, if I could actually reverse engineer 7zip to help implement the "fnf" extension thingy in my spare time from college (I'm studying game design at Full Sail University, and I'm on my last 4 months before graduation), I would.

P.S.

This solution would also allow you to do way more insane shit, like possibly making a week where everyone's an N64 style 3D model, and there's a camera flyover effect that gets more intense the higher your combo.

**Comment by VMGuy23** [comment]
just saying HaxeFlixel is 2D-only

**Comment by ACrazyTown** [comment]
> just saying HaxeFlixel is 2D-only

someone made a mod using 3d models

**Comment by ThePlank** [comment]
Well HaxeFlixel is 2D only but OpenFL has some classes for dsplaying 3D items.

Screenshot from HaxeFlixel's API:
![image](https://user-images.githubusercontent.com/75984453/124466203-ae0f4000-dd96-11eb-983a-056a4c43ccdb.png)

**Comment by prokube** [comment]
> Well HaxeFlixel is 2D only but OpenFL has some classes for dsplaying 3D items.
> 
> Screenshot from HaxeFlixel's API:
> ![image](https://user-images.githubusercontent.com/75984453/124466203-ae0f4000-dd96-11eb-983a-056a4c43ccdb.png)

let's gaming

**Comment by mdluffy1234** [comment]
nice
