### ISSUE TITLE
Question: can i use fnf asset for my game ? 

### ISSUE THREAD

**Issue by stickylabdev** [FunkinCrew/Funkin#1341]
maybe i will make similar game to fnf ,,, kinda diferent game mechanic
but kinda similar sprite asset or maybe pretty similar 
then maybe iwill put some ads then making money from that game

and and maybe iwill upload it to playstore
will i get copyright infringnment ?

**there are also many games on playstore about fnf, is this ok?**
https://play.google.com/store/search?q=friday%20night%20funkin&c=apps

**Comment by nickpythonluajava** [comment]
> maybe i will make similar game to fnf ,,, kinda diferent game mechanic

so, a rhythm game?

**Comment by nickpythonluajava** [comment]
also, are you talking about this?:
#1328

**Comment by muafakul** [comment]
DANG...OK GREAT ,
