### ISSUE TITLE
"Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead"

### ISSUE THREAD

**Issue by Awwi2** [FunkinCrew/Funkin#1345]
I am trying to make a mod and typed "lime test windows"and got this back:

`C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:329: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\Me\Desktop\Kade-Engine-stable\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC`

I tried to fix this or find anything about this on the internet and couldnt find anything, please help.

**Comment by zacksgamerz** [comment]
It's a warning, it doesn't affect anything at all tbh

**Comment by Awwi2** [comment]
Well it does effect something because it doesnt continue executing the code

**Comment by VMGuy23** [comment]
https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe

**Comment by Cheemsandfriends** [comment]
You need to download the things below because
instead C:\Users\Me\Desktop\Kade-Engine-stable\export\release\windows\obj>setlocal enabledelayedexpansion Warning: Could not find Visual Studio 2017 VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC
Abd you don't have that xd
(and two Why Kade Engine >:( )

**Comment by VMGuy23** [comment]
my download link solved the HXCPP_VARS problem
