### ISSUE TITLE
Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by axisdadev** [FunkinCrew/Funkin#1349]
## Please describe your issue. Provide extensive detail and images if possible.
Hello, I was trying to test Friday night funkin on the HTML5 Version.

If you don't know what I'm talking about ill try to describe it.

It's like testing it on windows. or mac. where you use the command lime test windows or whatever.

I used lime test html5

and I got this error.
![damndainel](https://user-images.githubusercontent.com/77366347/124682912-ccea0100-de80-11eb-890d-71548911955e.png)

It worked before perfectly I was editing the code but I only edited .hx files not .js files

I am confused please help me out.

Just for stats I am on windows 10. I belive I was using the current version on github
I have some experience with coding mainly roblox lua and HTML.

## Update
nvm i found out it was just my internet being funky.

**Comment by ThePlank** [comment]
close

**Comment by marshallward** [comment]
I'm also seeing this issue.  First time it ran, trying to run again always gives this error.

I know very little about Javascript, so unsure how to diagnose this.  I suspect it's something about my environment, though.

**Comment by marshallward** [comment]
Nevermind, it seems I had an `http-server` running that was taking over resources (I think).  Killing that processes fixed things.
