### ISSUE TITLE
Bug Report: Points missing

### ISSUE THREAD

**Issue by snaplu1** [FunkinCrew/Funkin#1351]
I was playing this game for months on end. And I went back to the website and all my points were gone.

![image](https://user-images.githubusercontent.com/79392194/124800785-0cb5f480-df24-11eb-8e60-235d20c8fafd.png)
![image](https://user-images.githubusercontent.com/79392194/124800808-13446c00-df24-11eb-9a49-843143678b29.png)

**Comment by ACrazyTown** [comment]
I don't think this is really a bug. I think the browser version saves your scores in cookies/temp or summin like that, so when those things get deleted, your save goes with them

**Comment by ninjamuffin99** [comment]
yeah prob sum cookie shit
