### ISSUE TITLE
No cutscenes play/stuck in windowed upon open

### ISSUE THREAD

**Issue by GamerViolet** [FunkinCrew/Funkin#1352]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows 64bit

## What version of the game are you using? Look in the bottom left corner of the main menu.

0.2.7.1

## Please describe your issue. Provide extensive detail and images if possible.
Upon opening the game and putting it to fullscreen it stays in windowed. Then when I play any week in storymode it wont play cutscenes at all. It just freezes and stutters between songs. Haven't found a way to fix it unless there is files missing from the DL link on the site?

**Comment by VMGuy23** [comment]
> it wont play cutscenes

there aren't any

**Comment by GamerViolet** [comment]
> > it wont play cutscenes
> 
> there aren't any

But I saw them when Jay from the Kubz Scoutz played. Unless as a semi big youtuber they get better versions till full release than us?

**Comment by VMGuy23** [comment]
> > > it wont play cutscenes
> > 
> > 
> > there aren't any
> 
> But I saw them when Jay from the Kubz Scoutz played. Unless as a semi big youtuber they get better versions till full release than us?

That probably wasn't the original game

**Comment by VMGuy23** [comment]
Can ypu link the video?

**Comment by ninjamuffin99** [comment]
please describe ur issue better
