### ISSUE TITLE
Bug Report: cutscene from week 7 constantly freezing and then returning to normal

### ISSUE THREAD

**Issue by Luchen10** [FunkinCrew/Funkin#1354]
Playing on newgrounds version on microsoft edge

**Comment by pandajustgaming** [comment]
get a new pc to play fnf only

**Comment by Luchen10** [comment]
> get a new pc to play fnf only

this problem appeared recently because a few months ago it was normal

and also im playing this on newgrounds because of week 7 still didn't release for download

**Comment by AbnormalPoof** [comment]
not entirely true, the video mp4s are actually in the game file

**Comment by Cheemsandfriends** [comment]
> not entirely true, the video mp4s are actually stored in the game files within `assets/music`

No. It Is actually true. All the assets are being loaded in real time and speed. Lol
