### ISSUE TITLE
Bug Report: Images not properly loading when tabbed out on web browser?

### ISSUE THREAD

**Issue by Jenova1sama** [FunkinCrew/Funkin#1358]
at times if you are in a different tab from newgrounds fnf will glitch out where sprites dont load and stuff continues... just visual 
![Screenshot (3)](https://user-images.githubusercontent.com/87213942/125147421-c6fa5700-e0f0-11eb-923d-486ad8299b2a.png) 
![Screenshot (2)](https://user-images.githubusercontent.com/87213942/125147453-0628a800-e0f1-11eb-9275-4917f855da42.png)

**Comment by ThePlank** [comment]
get more ram

**Comment by VMGuy23** [comment]
> get more ram

from my understanding, this is only when switching to another tab during loading

**Comment by ThePlank** [comment]
> > get more ram
> 
> from my understanding, this is only when switching to another tab during loading

oh
