### ISSUE TITLE
Desktop version has less fps

### ISSUE THREAD

**Issue by HumanDude** [FunkinCrew/Funkin#136]
Right as I made the switch to this game from newgrounds to the download I noticed right away something was wrong. I'm not fully sure if it is the fps that's capped at 63 or something else slowing the game down. I use a 144 hertz monitor so if this version is really capped at 63 then that makes a big difference mainly for faster songs. I'm not sure if its just on my end only so if anyone knows anything on this that would be nice to hear.

**Comment by JONTTM** [comment]
I experience the same issue
