### ISSUE TITLE
Hey Luckydog can you update the FNF Battle Royale android port to play with friends pls?

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1361]

**Comment by VovaGamesChips** [comment]
It's ninjamuffin99's repository. Better switch to [luckydog7's repository](https://github.com/luckydog7/Funkin-android).

**Comment by prokube** [comment]
GOD FUCKING

AFSDHIUFADSLHJAFSDLGUFSHUASD

**Comment by 4techguns** [comment]
You've got the wrong repository

**Comment by ninjamuffin99** [comment]
fnf mod
