### ISSUE TITLE
Question: What the problem?

### ISSUE THREAD

**Issue by CarGithubus** [FunkinCrew/Funkin#1364]
![image](https://user-images.githubusercontent.com/87308573/125272079-1cfb1480-e314-11eb-8d46-b661940fa712.png)

**Comment by YousefTamer67** [comment]
go to readme

**Comment by ThePlank** [comment]
https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe

**Comment by CarGithubus** [comment]
> https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe

Thank you

**Comment by nickpythonluajava** [comment]
> > https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe
> 
> 
> 
> Thank you

lol

**Comment by polybiusproxy** [comment]
> > https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe
> 
> Thank you

If the issue was resolved, please close it

**Comment by CarGithubus** [comment]
> > > https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe
> > 
> > 
> > Thank you
> 
> If the issue was resolved, please close it

Ok
