### ISSUE TITLE
Bug Report: When I try to enter in a week through newgorunds, it loads and gets this screen:

### ISSUE THREAD

**Issue by INKilNO** [FunkinCrew/Funkin#1365]
I'm want to play FNF, but my pc its no so good to play this game, so, i try in the newgrounds, but dosent works and have this screen: https://drive.google.com/file/d/1AquLBKhg6vhT5-1LWKneDfkgwsREJBuw/view?usp=sharing

Im play in pc with this capabilities:
classification: 2,4
processor: Intel Celeron CPU 847 1.10 GHz
installed memory(ram): 4,00GB
type of system: 32 bits

**Comment by ThePlank** [comment]
![image](https://user-images.githubusercontent.com/75984453/125486672-35e83eac-84f4-4363-a042-3a625a87c9bd.png)
im almost going crazy from this, buy a 64bit processor and 8 gb of ram

**Comment by JaredYoshi** [comment]
you need a better computer

**Comment by Windows1Door2Daniel** [comment]
Is necesary link a Drive file?

just, i think by doing that you expose your Gmail

but you can put a image rigth here

**Comment by VMGuy23** [comment]
> Is necesary link a Drive file?
> 

GitHub has image upload

**Comment by s-zenmode** [comment]
sorry buddy but basically im pretty sure its telling you that fnf crashed b/c your pc cant handle.
