### ISSUE TITLE
Question: chromebook support?

### ISSUE THREAD

**Issue by fnfhjbhbh** [FunkinCrew/Funkin#1369]
is there a way to do it on chromebook we'll use the source code to make mod's

**Comment by nickpythonluajava** [comment]
linux

**Comment by fnfhjbhbh** [comment]
thanks!

**Comment by ninjamuffin99** [comment]
haven't looked too much into compiling for chromebook yet, probably would moreso aim to either get android versions cooked (idk chromebooks support with those), get better HTML5 / web versions optimized, or just get an actual chromebook support if the linux bullshit isnt too painful

**Comment by AbnormalPoof** [comment]
already mentioned in [#1323 (Comment)](https://github.com/ninjamuffin99/Funkin/issues/1323#issuecomment-903330825), but chromeos has a toggleable linux feature in settings, meaning you can install haxe and compile fnf

the linux thing is more like a virtual machine kinda
