### ISSUE TITLE
Not playable?

### ISSUE THREAD

**Issue by FuntimeWolfy34** [FunkinCrew/Funkin#137]
So I was trying to play the game, and everything will start ok, then it crashes. I 've had this problem for a while now

**Comment by oldfag9001** [comment]
Does it stop right after the haxeflixel logo? I was having the same issue, and I found newgrounds was trying to serve a popup (which was blocked by the popup blocker) asking for account permissions. Issue was resolved by signing up for a newgrounds account, allowing popups, refreshing the page, and granting permissions
