### ISSUE TITLE
Bug Report: when I click the WASD or the ARROWS to click on a note the click I do to the ARROWS or the WASD they respond as if they had clicked it later

### ISSUE THREAD

**Issue by ZREAX** [FunkinCrew/Funkin#1371]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by VMGuy23** [comment]
This is an issue with your computer, close the issue. If others on the same version don't have it, it isn't a problem with Friday Night Funkin'.

**Comment by Windows1Door2Daniel** [comment]
Don't place the entire issue in the title

Thats why Github lets you write a

###DESCRIPTION###

**Comment by Windows1Door2Daniel** [comment]
Don't place the entire issue in the title

Thats why there is a

####Description

**Comment by Andreas010** [comment]
^
