### ISSUE TITLE
Bug Report: my balls hurt

### ISSUE THREAD

**Issue by MagnusStrom** [FunkinCrew/Funkin#1372]
my balls hurt
idk if i should itch them they might hurt more

**Comment by VMGuy23** [comment]
Hi - Please discuss this in a related place as this isn't where you should be  asking about it.

**Comment by Windows1Door2Daniel** [comment]
You have testicular infection

**Comment by MagnusStrom** [comment]
> Hi - Please discuss this in a related place as this isn't where you should be  asking about it.

see but like it happened while playing fnf

**Comment by VMGuy23** [comment]
> > Hi - Please discuss this in a related place as this isn't where you should be  asking about it.
> 
> see but like it happened while playing fnf

Hi - If a car crashed into my house while playing FNF I would not report it here as it is nothing that can be changed by the developers.

**Comment by obloovoo** [comment]
did they start hurting when you got a game over?

**Comment by VMGuy23** [comment]
pheph

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by josetzunun** [comment]
WTF CLOSE THIS SHIT

**Comment by MagnusStrom** [comment]
> did they start hurting when you got a game over?

they started thumping up and down?

**Comment by siky112** [comment]
can we close this please

**Comment by Windows1Door2Daniel** [comment]
What mean swag

**Comment by windows10win7posreadywoeskio** [comment]
what the fuck can we close this

**Comment by Windows1Door2Daniel** [comment]
> what the fuck can we close this

Hey Windows 10 Win 7

**Comment by PrincessMtH** [comment]
skill issue
