### ISSUE TITLE
Chromebooks aren't good to play in my opinion

### ISSUE THREAD

**Issue by Windows1Door2Daniel** [FunkinCrew/Funkin#1373]
There is so many issues of bugs and sh*t

I think

#### Chromebooks aren't good to play

**Comment by VMGuy23** [comment]
I totally agree

**Comment by cheat117** [comment]
Respectfully, this should be a place for bugs that are documented. I would ask that we change this ticket to be more productive...

Example:

When I play on a chromebook (Model: XXXX, Manufacturer: XXXX, ChromeOS ver: vXXXX [check the about section under settings]), I get intermittent stutters (give detail, level, song time, stage in level, etc) which drastically affects gameplay. It would be great to see some optimizations taken to address the number of loaded sprites here in order to play this.

Additionally, describe HOW you play. (Newgrounds? itch.io download? itch.io in-browser? How many tabs do you have open?)

Opinions of "this game sucks, git gud scrub" don't make for actionable tickets. 

IF YOU CAN UPDATE THIS, then you could get someone optimizing for you.

**Comment by VMGuy23** [comment]
> Respectfully, this should be a place for bugs that are documented. I would ask that we change this ticket to be more productive...
> 
> Example:
> 
> When I play on a chromebook (Model: XXXX, Manufacturer: XXXX, ChromeOS ver: vXXXX [check the about section under settings]), I get intermittent stutters (give detail, level, song time, stage in level, etc) which drastically affects gameplay. It would be great to see some optimizations taken to address the number of loaded sprites here in order to play this.
> 
> Additionally, describe HOW you play. (Newgrounds? itch.io download? itch.io in-browser? How many tabs do you have open?)
> 
> Opinions of "this game sucks, git gud scrub" don't make for actionable tickets.
> 
> IF YOU CAN UPDATE THIS, then you could get someone optimizing for you.

This is general advice saying that the game and/or game engine aren't optimised for low-end devices like chromebooks.

**Comment by cheat117** [comment]
Can you provide a Chromebook you specifically have attempted to play on?

**Comment by VMGuy23** [comment]
I can't, however, most problems with lag, missing assets, and crashes have either been low-end devices or chromebooks

**Comment by Steviegt6** [comment]
> 
> 
> Respectfully, this should be a place for bugs that are documented. I would ask that we change this ticket to be more productive...
> 
> Example:
> 
> When I play on a chromebook (Model: XXXX, Manufacturer: XXXX, ChromeOS ver: vXXXX [check the about section under settings]), I get intermittent stutters (give detail, level, song time, stage in level, etc) which drastically affects gameplay. It would be great to see some optimizations taken to address the number of loaded sprites here in order to play this.
> 
> Additionally, describe HOW you play. (Newgrounds? itch.io download? itch.io in-browser? How many tabs do you have open?)
> 
> Opinions of "this game sucks, git gud scrub" don't make for actionable tickets.
> 
> IF YOU CAN UPDATE THIS, then you could get someone optimizing for you.

While I completely agree with this, I'd recommend you don't waste your time detailing with problematic users like Daniel. They're active here and do nothing but post random, unrelated stuff on the issue tracker.

**Comment by cheat117** [comment]
> I can't, however, most problems with lag, missing assets, and crashes have either been low-end devices or chromebooks

Examples would really go a long way. Until then, nonsensical remarks like "kekw, get better scrub" don't really fly on a site like GitHub.

**Comment by cheat117** [comment]
> > 
> > 
> > Respectfully, this should be a place for bugs that are documented. I would ask that we change this ticket to be more productive...
> > 
> > Example:
> > 
> > When I play on a chromebook (Model: XXXX, Manufacturer: XXXX, ChromeOS ver: vXXXX [check the about section under settings]), I get intermittent stutters (give detail, level, song time, stage in level, etc) which drastically affects gameplay. It would be great to see some optimizations taken to address the number of loaded sprites here in order to play this.
> > 
> > Additionally, describe HOW you play. (Newgrounds? itch.io download? itch.io in-browser? How many tabs do you have open?)
> > 
> > Opinions of "this game sucks, git gud scrub" don't make for actionable tickets.
> > 
> > IF YOU CAN UPDATE THIS, then you could get someone optimizing for you.
> 
> While I completely agree with this, I'd recommend you don't waste your time detailing with problematic users like Daniel. They're active here and do nothing but post random, unrelated stuff on the issue tracker.

Sadly, looking to contribute but yes,  starting to get that this is a brick wall

**Comment by Windows1Door2Daniel** [comment]
> > Respectfully, this should be a place for bugs that are documented. I would ask that we change this ticket to be more productive...
> > Example:
> > When I play on a chromebook (Model: XXXX, Manufacturer: XXXX, ChromeOS ver: vXXXX [check the about section under settings]), I get intermittent stutters (give detail, level, song time, stage in level, etc) which drastically affects gameplay. It would be great to see some optimizations taken to address the number of loaded sprites here in order to play this.
> > Additionally, describe HOW you play. (Newgrounds? itch.io download? itch.io in-browser? How many tabs do you have open?)
> > Opinions of "this game sucks, git gud scrub" don't make for actionable tickets.
> > IF YOU CAN UPDATE THIS, then you could get someone optimizing for you.
> 
> While I completely agree with this, I'd recommend you don't waste your time dealing with problematic users like Daniel. They're active here and do nothing but post random, unrelated stuff on the issue tracker.

Im only active when i receive a maik
