### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by 0parrot0** [FunkinCrew/Funkin#1375]
#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

Chrome 

 Windows (64`)

v0.2.8(NewGrounds exclusive preview)

when i try to get in to a song it just doesn't wanna load it just stay's on the loading screen both in story mode and free play

**Comment by Andreas010** [comment]
How much memory do you have? That might be the problem
