### ISSUE TITLE
Bug Report: After doing some coding in "Character.hx" and running the Lime Test, I got these errors

### ISSUE THREAD

**Issue by spoo-gle** [FunkinCrew/Funkin#1377]
SOLUTION: I FORGOT TO PUT TWO 's AROUND THE "idle", "singUP," etc. IN THE BOTTOM PART

![Screenshot 2021-07-20 234854](https://user-images.githubusercontent.com/86542153/126427779-c5ae9229-f317-4a4a-b562-bdadfe567a88.png)

**The Coding I did in Character.hx:**

case 'hank':
	frames = Paths.getSparrowAtlas('Hank/Hank');
	animation.addByPrefix('idle', 'HankIdle', 24, false);
	animation.addByPrefix('singUP', 'HankUp', 24, false);
	animation.addByPrefix('singDOWN', 'HankDown', 24, false);
	animation.addByPrefix('singLEFT', 'HankLeft', 24, false);
	animation.addByPrefix('singRIGHT', 'HankRight', 24, false);
					
	addOffset(idle);
	addOffset(singUP);
	addOffset(singDOWN);
	addOffset(singLEFT);
	addOffset(singRIGHT);
					
	playAnim('idle');

**Comment by Steviegt6** [comment]
This is your fault, not ninja's. Why are you posting this here?

**Comment by spoo-gle** [comment]
> This is your fault, not ninja's. Why are you posting this here?

I needed help with an issue that I didn't know how to solve. Is there anywhere else I can request help with this? If so, I'd like to know. I really want to fix it.
