### ISSUE TITLE
Bug Report: black box issue

### ISSUE THREAD

**Issue by punchAnt** [FunkinCrew/Funkin#1378]
fnf is a good game but i cant see any of the people! all i see is a black box ware they are suppose to be! if you have any way to fix this pleas help ! i also asked my friends and they are not haveing the same issue. so please help

**Comment by ThamesDev** [comment]
Have you tried uninstalling and reinstalling?

**Comment by KlavierGayming** [comment]
1. Get a better PC
2. Profit

**Comment by KlavierGayming** [comment]
1. Get a better PC
2. Profit

**Comment by KlavierGayming** [comment]
Fun fact:
This bug happens on phones a lot.

**Comment by ThePlank** [comment]
> 1. Get a better PC
> 2. Profit

what why did you post this 2 times

just get more ram and done

**Comment by ninjamuffin99** [comment]
known issue, wit da black boxes

**Comment by AbnormalPoof** [comment]
my idea is maybe compressing the sprites a lil bit and then rescale them to their og resolution
