### ISSUE TITLE
Bug Report: So when i was playing week 6 on hard with the dating app, everything was fine until i got to the third song. Whenever the guy turned into the red face thingy, it started slowly going out of sync with the notes, then started overlapping the song onto itself over and over again. (I'll be honest it was pretty funny.) But even after i let myself die, it stared looping my dead screen over and over again. Overall, it wasn't a big deal, i just couldn't concentrate on the song. I've reloaded the page now to see if it will work. Thanks for reading!!

### ISSUE THREAD

**Issue by SupersweettartXP-on-YT** [FunkinCrew/Funkin#1380]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by ThePlank** [comment]
what, i need videos of it happening and and also dont type your whole issue into the title of the issue, type it in the body.
