### ISSUE TITLE
Resolution is messed up when moving to an empty workspace i3wm

### ISSUE THREAD

**Issue by z3roco01** [FunkinCrew/Funkin#1382]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Im on arch linux 

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Run the game in a workspace with at least 1 other tiled window open
2. Move the game to an empty workspace 

## Please describe your issue. Provide extensive detail and images if possible.

An image of what happens:
[![funkin.png](https://i.postimg.cc/mkvBFWdF/funkin.png)](https://postimg.cc/WqwQQCc2)

**Comment by VMGuy23** [comment]
In the source code, go into Main.hx, change the scale from -1 to 1

**Comment by Unknown-User2** [comment]
what do you mean by scale i cant find it

**Comment by KitOdin** [comment]
whats the workspace name?

**Comment by Unknown-User2** [comment]
i moved it from just a numbered one to one called "3: games"

**Comment by KitOdin** [comment]
link
