### ISSUE TITLE
Bug Report: my laptop can't read lime.ndll

### ISSUE THREAD

**Issue by JorosTheModderPH** [FunkinCrew/Funkin#1383]

**Comment by polybiusproxy** [comment]
That's not a bug. The file "lime.ndll" is a Neko Dynamic Library, and it's used by the game.
Trying to read that file is like reading the game's executable.

**Comment by josetzunun** [comment]
Ha

**Comment by josetzunun** [comment]
Lol

**Comment by Andreas010** [comment]
Just execute the game
