### ISSUE TITLE
Custom stage crashes the game

### ISSUE THREAD

**Issue by TheRealArsonist** [FunkinCrew/Funkin#1387]
I don't know if this is common or not, but whenever i try to swap a character in the debug menu the game crashes. So i tried making a custom stage first so i don't have to swap the character but the game still crashes. I've checked the source code and everything looked fine, no typos or anything.

**Comment by ThePlank** [comment]
Crash log?

**Comment by TheRealArsonist** [comment]
late reply. i got it all fixed now. reason it crashes because things were in the wrong folders

**Comment by Steviegt6** [comment]
> 
> 
> late reply. i got it all fixed now. reason it crashes because things were in the wrong folders

Would appreciate you closing the issue, then!
