### ISSUE TITLE
Really strange game crashes

### ISSUE THREAD

**Issue by RubixDude10** [FunkinCrew/Funkin#139]
I play this on a Raspberry Pi because I don't really have anything else. Friday Night Funkin' used to work before the week 4 update but after this update the game just doesen't work. It keeps crashing when it finishes loading. Occasionally it actually does work but that's very rare and when I try to play week 4 it crashes and then again I can't play because of the loading crash.

**Comment by tikycookies** [comment]
the games is builded for arm64

you need to buy a intel processor and then change the arm64 one
i think

**Comment by 4techguns** [comment]
How much memory does your Pi have? Usually these crashes are caused by running out of memory. At most, you would need around 4-8 GB of RAM. 2 GB isn't enough for FNF to load at all.

**Comment by 4techguns** [comment]
> the games is builded for arm64
> 
> you need to buy a intel processor and then change the arm64 one i think

The Raspberry Pi is not designed for components like this to be replaced. You cannot simply change the CPU to an Intel one.

**Comment by prokube** [comment]
why on a raspberry pi?

why not on a mcdonalds cash register?

**Comment by 4techguns** [comment]
Yeah that's probably a more viable option for playing lol

**Comment by RubixDude10** [comment]
hello it’s really me, the guy who wrote this stupid post a year ago. forgive me for being a caca face since this was my first computer do I didn’t really know what to do. I have a laptop now, silly moment

**Comment by 4techguns** [comment]
> How much memory does your Pi have? Usually these crashes are caused by running out of memory. At most, you would need around 4-8 GB of RAM. 2 GB isn't enough for FNF to load at all.

Actually, this can be related to how FNF handles asset loading. HaxeFlixel appears to not have any proper memory GC (garbage collection), which causes the game to run out of memory if you don't have enough RAM. *cough* *cough* ~~Java's memory heap~~
