### ISSUE TITLE
Bug Report: idk what this means lol

### ISSUE THREAD

**Issue by dartthe6th** [FunkinCrew/Funkin#1395]
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:\Users\Tdrsi\OneDrive\Desktop\Funkin-master\Funkin-master\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by ThePlank** [comment]
install the 22gb of shit in the readme and if there is still the HXCPP_VARS error then download this: https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe

**Comment by HmAhYesTheFloorHereIsMadeOutOfFloor** [comment]
> install the 22gb of shit in the readme and if there is still the HXCPP_VARS error then download this: https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe

thanks

**Comment by JimStanding** [comment]
I think the issue is actually that the Readme hints the HTML5 build is ready to go, before it tells you to install VS if you want to build desktop version.

It seems you need the build tools for either method.
