### ISSUE TITLE
Bug Report: Character Switch

### ISSUE THREAD

**Issue by dartthe6th** [FunkinCrew/Funkin#1397]
Whenever I try to switch a character, it just crashes.

**Comment by ThePlank** [comment]
This happpens because the characters are hard-coded into their weeks try applying #528 to your source code.

**Comment by HmAhYesTheFloorHereIsMadeOutOfFloor** [comment]
> This happpens because the characters are hard-coded into their weeks try applying #528 to your source code.

alrigth, ill try that. ill update you if it works/ if it breaks

**Comment by ninjamuffin99** [comment]
character switching is a debug mode thing, so lol not supported!
