### ISSUE TITLE
Main Character Sprite problem

### ISSUE THREAD

**Issue by gamermanjr** [FunkinCrew/Funkin#140]
Don't know if it's just me but when I load up the game he's kinda just gone. But when you hit the notes he re-appears, but then goes and disappears when you stop hitting notes.

**Comment by gedehari** [comment]
Please ignore the mention, I mistyped, sorry!

As for the issue, well I have not much to comment on. It has been reported multiple times. Can you state what version of the game you are running? (Web/Desktop)
