### ISSUE TITLE
My Compile is finished

### ISSUE THREAD

**Issue by YousefTamer67** [FunkinCrew/Funkin#1402]
i reseted my pc and install haxe 4.1.5 and the libraries also, and visual studio community 2019 again, and then my compile is now working
look at the image
![Screenshot (175)](https://user-images.githubusercontent.com/82932252/127343771-c0ad7597-2abf-4bf2-ae4a-3d82d5738c95.png)

**Comment by YousefTamer67** [comment]
install the components 
* Windows 10 SDK (Latest)
* Windows 10 SDK (10.0.17763.0)
* MSVC v141 - VS 2017 C++ x64/x86 build tools
* MSVC v142 - VS 2019 C++ x64/x86 build tools
* C++ Profiling tools
* C++ CMake tools for windows
* C++ ATL for v142 build tools (x86 & x64)

make sure to install visual studio community 2019 and use these components on Individual components and the workload named Desktop development with C++. have a nice day

**Comment by YousefTamer67** [comment]
it works

**Comment by YousefTamer67** [comment]
if it dosen't work for you, try reseting your pc ok

**Comment by VMGuy23** [comment]
reseting PC wont do anything

**Comment by polybiusproxy** [comment]
> if it dosen't work for you, try reseting your pc ok

this guy acting like a senior programmer because he built kade engine sucessfully

**Comment by FelipeBacana** [comment]
When i click my completed compile i open the game and won't work and says "This application can't be executed from your pc"

**Comment by Steviegt6** [comment]
> When i click my completed compile i open the game and won't work and says "This application can't be executed from your pc"

Ask the senior programmer for help. :trollface:

**Comment by MrClogsworthYT** [comment]
> > When i click my completed compile i open the game and won't work and says "This application can't be executed from your pc"
> 
> Ask the senior programmer for help. :trollface:

xddddddddddddd
