### ISSUE TITLE
Bug Report: ;

### ISSUE THREAD

**Issue by dartthe6th** [FunkinCrew/Funkin#1404]
Ive fixed everything I possibly can, but im not a coder, so i need help
![Screenshot (860)](https://user-images.githubusercontent.com/63616870/127421054-9f506d18-6bc4-4c78-8808-254d14f99191.png)

**Comment by Steviegt6** [comment]
This isn't the place to ask.

**Comment by HmAhYesTheFloorHereIsMadeOutOfFloor** [comment]
> This isn't the place to ask.
its a bug report... im asking hwo to fix it...?

**Comment by ThePlank** [comment]
![image](https://user-images.githubusercontent.com/75984453/127499315-b0c16587-9adb-4df3-8b49-d11cb2f4526b.png)
The antialiasing lines don't have semicolons at the end of the line, fix that and remember to put semicolons at the end of every line (unless it has special syntax or is a multiline, put a semicolon on the last line of the multiline.)

**Comment by HmAhYesTheFloorHereIsMadeOutOfFloor** [comment]
> ![image](https://user-images.githubusercontent.com/75984453/127499315-b0c16587-9adb-4df3-8b49-d11cb2f4526b.png)
> The antialiasing lines don't have semicolons at the end of the line, fix that and remember to put semicolons at the end of every line (unless it has special syntax or is a multiline, put a semicolon on the last line of the multiline.)

its still saying that
![Screenshot (862)](https://user-images.githubusercontent.com/63616870/127511408-abf7faa0-6eb6-4a7e-901d-60cf5b267cd6.png)

**Comment by Steviegt6** [comment]
> 
> 
> > This isn't the place to ask.
> > its a bug report... im asking how to fix it...?

It's not a bug. The issue is a result of changes you made.

**Comment by Steviegt6** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/75984453/127499315-b0c16587-9adb-4df3-8b49-d11cb2f4526b.png)
> > The antialiasing lines don't have semicolons at the end of the line, fix that and remember to put semicolons at the end of every line (unless it has special syntax or is a multiline, put a semicolon on the last line of the multiline.)
> 
> its still saying that
> ![Screenshot (862)](https://user-images.githubusercontent.com/63616870/127511408-abf7faa0-6eb6-4a7e-901d-60cf5b267cd6.png)

Did you save the file?

**Comment by ThePlank** [comment]
> > > ![image](https://user-images.githubusercontent.com/75984453/127499315-b0c16587-9adb-4df3-8b49-d11cb2f4526b.png)
> > > The antialiasing lines don't have semicolons at the end of the line, fix that and remember to put semicolons at the end of every line (unless it has special syntax or is a multiline, put a semicolon on the last line of the multiline.)
> > 
> > 
> > its still saying that
> > ![Screenshot (862)](https://user-images.githubusercontent.com/63616870/127511408-abf7faa0-6eb6-4a7e-901d-60cf5b267cd6.png)
> 
> Did you save the file?

![image](https://user-images.githubusercontent.com/75984453/128394730-b6a88834-0f4c-4598-8fe2-7cf44bc6e15d.png)
The white circle indicates that the file is not saved.
