### ISSUE TITLE
:Bug Report: 

### ISSUE THREAD

**Issue by Im-listening** [FunkinCrew/Funkin#1405]
I have this little problem I downloaded all the necasarry lirbaries for compiling the game I put lime test mac -debug but this keeps showing and it stops the compile process- 

Error: In file included from /Users/ashleygrimes/(/usr/local/lib/haxe/lib/discord_rpc/git/lib/discord-rpc/src/discord_register_osx.m:4:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:10:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:26:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSMeasurement.h:8:9: fatal error: 'Foundation/NSUnit.h' file not found
#import <Foundation/NSUnit.h>
        ^~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSMeasurement.h:8:9: note: did not find header 'NSUnit.h' in framework 'Foundation' (loaded from '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks')
1 error generated.

**Comment by ThePlank** [comment]
Did you install XCode from the app store?

**Comment by materthemo** [comment]
No, Installed visual studio tho
