### ISSUE TITLE
Enhancement: Play another track for the main menu after beating the game

### ISSUE THREAD

**Issue by ThePlank** [FunkinCrew/Funkin#1406]
Basically, after you beat every song in the game, instead of playing Gettin' Freaky playing in the main menu it will play Klaskii Romper. Self explanitory.

**Comment by Cheemsandfriends** [comment]
No...
Why?

**Comment by TheAlmightyShibe** [comment]
In the Newgrounds release, Klaskii Romper already plays after you beat Tankman as an advertisement to the kickstarter.  It also doesn't really fit as a background music.

**Comment by ninjamuffin99** [comment]
nah, it intended to play the songs it does normally. maybe for full game tho
