### ISSUE TITLE
Bug Report: week 2/5 , hard mode and the sprites thing

### ISSUE THREAD

**Issue by ADesperate14yoKid** [FunkinCrew/Funkin#1410]
So, I recently downloaded fnf on my computer (the 32-bit version) and it's kinda glitchy

•first: the game crashes when I select hard mode

•second: When starting week 5/2 the game crashes

•third: when starting a week (week 4 for example) and beating the first song in the week, the game crashes

•forth: literally almost everyone isn't even in the game, for example : when opening the tutorial week I can still hear the song and press buttons normally, BUT I CAN ONLY SEE THE BACKGROUND, BF AND GF ARE GONE

And it's kinda random though, in week 4 for example, bf and gf are there but the mom ISN'T

And in week 6 all of them are there for some reason

Even in the game over screen I don't get the blueballed bf , it's just a black screen with the game over music

And playing it on newgrounds also had missing sprites and showed me black squares in the places of everyone in the main menu

I had a mod that I downloaded it before downloading the original game and I deleted it 
I deleted every other mod that I had and  even deleted my own save file , and reinstalling the game again, and it's still the same

It showed me a massage though which reads "you're running an outdated version of the game "  but the one I have is 0.2.7.1

Which is the newest version

Can you please, tell me what should I do?

Thanks for reading :)

**Comment by nickpythonluajava** [comment]
ram issue im pretty sure

**Comment by Cheemsandfriends** [comment]
It's because of the RAM.

**Comment by TheAlmightyShibe** [comment]
Also it says you are not on the latest version since the newgrounds tankman release is technically the latest version but v0.2.7.1 is the latest version completely open for the public to download.  Just ignore that message.
