### ISSUE TITLE
Seperate voice files for enemy / BF

### ISSUE THREAD

**Issue by Cheemsandfriends** [FunkinCrew/Funkin#1412]
Ok..
So it would be cool to have a second voice. Because when you are not pressing the arrows and the enemy does it makes the bf Voice work, even tho he's not singing a Shit.

**Comment by TheGamingCat89** [comment]
making the enemy's voices in the instrumental could work too

**Comment by ThePlank** [comment]
its also annoying that the tutorial's voices are merged with the inst

**Comment by Cheemsandfriends** [comment]
@TheGamingCat89 That would not work because we also need that the modders can access the insts lol

**Comment by Cheemsandfriends** [comment]
@ThePlank Yeah... Guess Kawaii sprite is too lazy for separate them and NinjaMuffin for introduce them

**Comment by nickpythonluajava** [comment]
somewhat a duplicate of my issue

**Comment by ninjamuffin99** [comment]
will happen, way it is currently was just a thing from the gamejam version that we havent overhauled / redone just yet

**Comment by DeceptedParasite** [comment]
thank god, this will make things alot for modders, thank you!

**Comment by Cheemsandfriends** [comment]
> 
> 
> thank god, this will make things alot for modders, thank you!

Idk If I should say your welcome or say thanks to cam But yeah XD

**Comment by Windows1Door2Daniel** [comment]
Yoeah i think would be a good edition

**Comment by Cheemsandfriends** [comment]
I want my chocolate medal :(

**Comment by Windows1Door2Daniel** [comment]
> I want my chocolate medal :(

Here
![89004090_l](https://user-images.githubusercontent.com/81389527/130304671-11825b87-ed57-4966-839f-75b5b9e1bcce.png)
