### ISSUE TITLE
Question: Trying to add after images.

### ISSUE THREAD

**Issue by TheGamingCat89** [FunkinCrew/Funkin#1414]
im trying to add after images or "crossfades" but i dont know how to make the code check for the section because curSection doesnt work.
![image](https://user-images.githubusercontent.com/81439207/127762966-307ab1a3-0dcb-4f12-b349-28d90a4dd6d3.png)

**Comment by ThePlank** [comment]
CurSection is not a thing in the Song class. It's a int value in PlayState.hx, and curSong is just a String vakue of the song name, use SONG if you want the song. You shoud do `if (SONG.notes[curSection].crossfades == true)`. Remember to add the crossfades bool in the SwagSection typedef! (if it's not in there)

**Comment by TheGamingCat89** [comment]
> CurSection is not a thing in the Song class. It's a int value in PlayState.hx, and curSong is just a String vakue of the song name, use SONG if you want the song. You shoud do `if (SONG.notes[curSection].crossfades == true)`. Remember to add the crossfades bool in the SwagSection typedef! (if it's not in there)

thanks!
