### ISSUE TITLE
When i try "lime test windows"

### ISSUE THREAD

**Issue by Dusty1345** [FunkinCrew/Funkin#1416]
it shows me this message
"You must have a "project.xml" file or specify another valid project file when using the 'test' command"
the same thing with "lime test debug"

someone can help me? :(

**Comment by papercore-dev** [comment]
cd [Sourcecode path] && lime test windows

**Comment by JimStanding** [comment]
Here is the error report.

`C:\Users\dontt\Desktop\Funkin>lime test html5 -debug
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:150: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:287: characters 17-21 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:386: characters 17-21 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
Stdlib.Sys.Break`

**Comment by SweetBroGames** [comment]
project.xml the file name need to be (project.xml) not (Project.xml) Hope this helped!

**Comment by nickpythonluajava** [comment]
dont compile in source

**Comment by Dusty1345** [comment]
> cd [Sourcecode path] && lime test windows

How do i found the sourcecode?
