### ISSUE TITLE
Question: Last song doesn't show in Story Mode

### ISSUE THREAD

**Issue by flustix** [FunkinCrew/Funkin#1417]
uhm so i had this issue a time ago but i'm stupid and forgot how to fix it lol

can someone help me

![image](https://user-images.githubusercontent.com/65369281/127865826-6d1ba919-091a-429d-a697-e1ba3e2ad33a.png)

**Comment by Cheemsandfriends** [comment]
You have like the most Updated OpenFl thing.
Unupdate it to Idk to... 9.0.2?
Yeah

**Comment by ThePlank** [comment]
or git openfl

**Comment by josetzunun** [comment]
What

**Comment by Flustix** [comment]
thanks it worked by downgrading
