### ISSUE TITLE
Bug Report: Sound Bug on Week Selection Menu

### ISSUE THREAD

**Issue by DaGamingCore** [FunkinCrew/Funkin#1418]
I was in Week 7, exited during Guns, and the week selection menu was playing a strange droning sound instead of the normal music, It eventually fixed itself. I could still hear the sounds from moving the cursor to select other weeks.

**Comment by DeceptedParasite** [comment]
yeah, this is a bug in the browser version, this obviously will be fixed when fully released to the public
