### ISSUE TITLE
Bug Report: Closing FlxDebugger while paused forces song to play

### ISSUE THREAD

**Issue by ThePlank** [FunkinCrew/Funkin#1423]
Closing FlxDebugger while paused forces the song to play and time to progress. (i also tried this with the base game (i compiled with debug) and i can reproduce the bug)

https://user-images.githubusercontent.com/75984453/128547158-020446d8-7d6b-4d66-a7a3-abd9ed38f659.mp4

**Comment by ninjamuffin99** [comment]
game wont have debugger enabled, so non issue
