### ISSUE TITLE
Enhancement: 

### ISSUE THREAD

**Issue by destroy145** [FunkinCrew/Funkin#1429]
## What is your suggestion, and why should it be implemented?
I suggest maybe adding stuff similar to the Kade Modding Engine.

**Comment by Steviegt6** [comment]
If I recall correctly, a (potentially) more robust and official modding system in already planned according to the kickstarter.

**Comment by DeceptedParasite** [comment]
yeah, mod support is officially coming in the future, just like a mobile support, character creator ect. wont come in the week 7 update we'll be getting it'll come in the future

**Comment by ThePlank** [comment]
> yeah, mod support is officially coming in the future, just like a mobile support, character creator ect. wont come in the week 7 update we'll be getting it'll come in the future

yea it will come in the full-ass game
