### ISSUE TITLE
Error Report:  Compiling issue

### ISSUE THREAD

**Issue by Im-listening** [FunkinCrew/Funkin#1430]
I have this problem when I compile the game it stops the compiling process and shows this

Error: In file included from /usr/local/lib/haxe/lib/discord_rpc/git/lib/discord-rpc/src/discord_register_osx.m:4:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:10:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:26:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSMeasurement.h:8:9: fatal error: 'Foundation/NSUnit.h' file not found
#import <Foundation/NSUnit.h>
        ^~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSMeasurement.h:8:9: note: did not find header 'NSUnit.h' in framework 'Foundation' (loaded from '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks')
1 error generated.
I tried re installing every library, haxe, the source folder, yet it keeps happening

**Comment by DotWith** [comment]
I think discord-rpc might not be supported for MacOS
