### ISSUE TITLE
It's been months

### ISSUE THREAD

**Issue by YousefTamer67** [FunkinCrew/Funkin#1432]
it's been months since week 7 is not on windows, i want it on windows

**Comment by TheKitBoi** [comment]
Wait it's not that hard

**Comment by DeceptedParasite** [comment]
it'll come soon enough, just wait, we all want it, we can't get what we want when we want, cause if we did life wouldn't be fun now would it?

**Comment by ThePlank** [comment]
my own engine will release after week 7 relases out of newgrounds probally
