### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1436]
What if you made this so this game works on any device? please because it dosent work for iPad and I really wanted to play it

**Comment by MisterAlexanderB** [comment]
I think that is a good idea too 
But it might be hard... Who knows, I am not the developer

**Comment by polybiusproxy** [comment]
heya girl
sorry, but making fnf work for every single device is not possible.

there are ios ports of fnf tho
just search for them

**Comment by josetzunun** [comment]
Even if you think it not possible it can still be possible idk
