### ISSUE TITLE
Question: wheres the logobumpin.fla?

### ISSUE THREAD

**Issue by CoolDoctorAidan** [FunkinCrew/Funkin#1439]
Where in the world is the LogoBumpin.fla file?
Or just how do you make a custom logo in fnf

**Comment by Cheemsandfriends** [comment]
Inside your dreams babe

**Comment by ThePlank** [comment]
its Start_Screen_Assets.fla

**Comment by Cheemsandfriends** [comment]
@ThePlank Haha You're wrong
it's in your dreams

**Comment by ThePlank** [comment]
ok

**Comment by ninjamuffin99** [comment]
ye its start_screen_assets.fla
