### ISSUE TITLE
Bug Report: Fail Music playing after retrying and going back to menu

### ISSUE THREAD

**Issue by DDev247** [FunkinCrew/Funkin#1441]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Newgrounds.com

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Brave

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
2.8 (Newgrounds Demo)

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Play any song with tankman and fail
2. Hit Enter with a delay to start the tankman saying something
3. After he finishes talking press escape
4. When you load into the menu the fail music will start.

## Please describe your issue. Provide extensive detail and images if possible.
The fail music starts in the main menu after failing in week 7 and going back to the menu when tankman finishes talking.

https://user-images.githubusercontent.com/87225187/129688531-84bdb240-e0ac-4646-a033-2f22770027c3.mp4

**Comment by ThePlank** [comment]
how do you even retry and go back to the fp menu at the same time

**Comment by Cheemsandfriends** [comment]
@ThePlank Simple
Press the enter and then you press the back button lol

**Comment by ThePlank** [comment]
> @ThePlank Simple
> Press the enter and then you press the back button lol

thaught you choudnt do that

**Comment by Vrobocio** [comment]
> Ok... So let me explain because I think I know why is it.
> So when the talk finishes the music fades in the increase the volume right?
> So HaxeFlixel Does like
> "Mmh... There's no music. Let's add some lol" And adds the gameover thing

even if you don't go back you can hear the music starting, kind of,
and it is a "bug" or maybe something that is not written in the code to prevent that.
