### ISSUE TITLE
Bug Report: Week 7 Secret Message

### ISSUE THREAD

**Issue by IdkIdkIdkIdkIdkIdkIDKIDKIDid** [FunkinCrew/Funkin#1442]
One time, I finished a normal Week 7 level and then some menu sounds overlapping with an interval of 1ms and then multiple secret messages appear when the first one finished

Can you fix it
v 0.2.8 (Newgrounds exclusive preview)

**Comment by ninjamuffin99** [comment]
multiple sounds overlapping spam is known issue
