### ISSUE TITLE
Question: WHAT THE FUCK IS THIS ERROR 

### ISSUE THREAD

**Issue by jukeliv** [FunkinCrew/Funkin#1443]
I whas compiling Friday Night Funkin with Visual Studio Code and i resive this error "Sys_error("export/debug/windows/obj/Options.txt: Permission denied")" how the fuck i can fix this shit guys???

thx for reading

PD: guys, i  fix this, you just need to deactivate your anti virus when you are compiling, thads the thing, after deactivate thad shit you will be resive the error, and after it alone just start to compile in C++ as normally do the comand "lime build windows" , thads the thing

**Comment by ThePlank** [comment]
i think you need admin perms or you need more disk space

**Comment by siky112** [comment]
are you running the game in the programs folder
if so move it out then compile
if not idk what to tell you

**Comment by susyboy23** [comment]
> i think you need admin perms or you need more disk space

ok but how can i do thad with Visual Studio Code????


cheers

-SusBoi

**Comment by SixBeeps** [comment]
> how can i do thad with Visual Studio Code????

You don't. VSC doesn't handle file management. You'll have to get rid of the files yourself if it's a disk space issue, or you'll have to run VSC as an administrator (how you do this depends on how you'd prefer to run it in the first place)

**Comment by susyboy23** [comment]
> > how can i do thad with Visual Studio Code????
> 
> You don't. VSC doesn't handle file management. You'll have to get rid of the files yourself if it's a disk space issue, or you'll have to run VSC as an administrator (how you do this depends on not only your OS, but also how you'd prefer to run it in the first place)

thx
