### ISSUE TITLE
Bug Report: Graphical Issues in Chrome

### ISSUE THREAD

**Issue by skullbite** [FunkinCrew/Funkin#1446]
Browser: Chrome
Platform: Any browser instance of FNF
Description: Certain Graphics (Haxeflixel loading assets, overlay behind intro text, etc.) don't show. This seems to happen on any engine/mod hosted online.
Version: ??? Version text doesn't even show, I can't tell.
![image](https://user-images.githubusercontent.com/20869262/129934839-ca16b8a8-1cf2-4a0e-a425-5a912fcbadec.png)
![image](https://user-images.githubusercontent.com/20869262/129933527-a0458694-d9d9-4a4b-9df2-23bbd94c4885.png)
![image](https://user-images.githubusercontent.com/20869262/129934209-8c547f03-1e73-480c-a55a-9cd27a80486b.png)
![image](https://user-images.githubusercontent.com/20869262/129934487-88749329-b3e7-4db9-9f56-024ca72042a4.png)
(Screenshots came from the itch.io version)

**Comment by AbnormalPoof** [comment]
works fine for me, its just your computer

**Comment by cuckydev** [comment]
this seems like it might be a gpu and/or driver incompatibility of sorts? maybe screwed up webgl2?

**Comment by Skullbite** [comment]
I can't resolve the issue but it doesn't seem to be effecting anyone else.
