### ISSUE TITLE
[Repository Feature Proposal] [Enhancement] Proper Discussions Proposal + Explanation

### ISSUE THREAD

**Issue by steviegt6** [FunkinCrew/Funkin#1456]
### Known duplicates:
#1104 
#1260 

# Background Information
The Funkin' repository has long had issues of off-topic issues, general discussion, and children without a proper grasp of the purpose of GitHub. The entire functionality of Discussions provides a solution—or at least band-aid fix—to many of these.

## What *are* discussions?
GitHub Discussions are basically a forum limited to a single repository, where the repository managers have control over categories/topics, etc. The important part is these are separated from the issue tracker, allow other users to easily answer people, allow original posters to mark responses as valid answers, and have a proper commenting/replying system.

## What about the moderation?
GitHub Discussions are relatively self-sufficient and take very little effort to take care of. Not only this, but they don't pile up and clutter in the same way issues on the issue tracker do. If you have a bunch of unanswered Q&A discussions, it won't shove a gross, large, and daunting number in your face.

Overall, Discussions can serve to redirect much of the clutter that fills the current issue tracker, and make it easier for people to answer each other for non-programming/technical questions. They also take care of the random "what's your favorite x"-esque questions.

If you need any more actual information, please comment instead of closing the issue without much real prior consideration. I'll be happy to provide.

**Comment by Windows1Door2Daniel** [comment]
I understand we acted dumb

So a warning is https://youtu.be/CRrZWoBc860

**Comment by shibest** [comment]
Yes thank you.
