### ISSUE TITLE
Bug Report: Entering freeplay crashes the game

### ISSUE THREAD

**Issue by AbnormalPoof** [FunkinCrew/Funkin#1459]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Running the html5 version locally
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
Latest version compiled from source code

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
1. Compile the game
2. Open it and enter freeplay
3. crash
## Please describe your issue. Provide extensive detail and images if possible.
Pretty self explanatory, entering freeplay on a compiled version (not 0.2.8 or 0.2.7.1 from itch and newgrounds) crashes the game.

Heres the console log

```
Uncaught TypeError: Cannot read properties of null (reading 'calls')
    at FreeplayState.changeSelection (Funkin.js:15636)
    at FreeplayState.create (Funkin.js:15535)
    at flixel_FlxGame.switchState (Funkin.js:26841)
    at flixel_FlxGame.update (Funkin.js:26878)
    at flixel_FlxGame.step (Funkin.js:26869)
    at flixel_FlxGame.onEnterFrame (Funkin.js:26803)
    at openfl_display_Stage.__dispatchEvent (Funkin.js:4850)
    at openfl_display_Stage.__dispatch (Funkin.js:5663)
    at openfl_display_Stage.__broadcastEvent (Funkin.js:116699)
    at openfl_display_Stage.__onLimeRender (Funkin.js:117726)
```

**Comment by ThePlank** [comment]
remove this line from freeplaystate
https://github.com/ninjamuffin99/Funkin/blob/f7c4a7bd82005fa9822206b8678d4a736c2163b5/source/FreeplayState.hx#L260-L262

**Comment by AbnormalPoof** [comment]
forgot to close it lmao
