### ISSUE TITLE
Game crashing at the Newgrounds screen

### ISSUE THREAD

**Issue by Saraistupid** [FunkinCrew/Funkin#146]
I'm trying to open the game on my Arch Linux installation, the game seems to crash after the Newgrounds screen

Here's a log in debug mode:
```
AL lib: (EE) GetLoadedHrtf: Invalid header in /usr/share/openal/hrtf/Default HRTF.mhr: "MinPHR03"
AL lib: (EE) GetLoadedHrtf: Failed to load /usr/share/openal/hrtf/Default HRTF.mhr
source/NGio.hx:35: INIT NOLOGIN
io/newgrounds/objects/events/Response.hx:40: [Newgrounds API] :: Error: Call unseccessful: #200 - Invalid app_id: ""
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleApplicationEvent lime/_internal/backend/native/NativeApplication.hx line 173
Called from lime._internal.backend.native.NativeApplication::updateTimer lime/_internal/backend/native/NativeApplication.hx line 585
Called from io.newgrounds.utils.AsyncHttp::update io/newgrounds/utils/AsyncHttp.hx line 176
Called from io.newgrounds.utils.AsyncHttp::handleMessage io/newgrounds/utils/AsyncHttp.hx line 125
Called from io.newgrounds.utils.AsyncHttp::handleMessage io/newgrounds/utils/AsyncHttp.hx line 114
Called from io.newgrounds.Call::onData io/newgrounds/Call.hx line 188
Called from io.newgrounds.utils.TypedDispatcher::dispatch io/newgrounds/utils/Dispatcher.hx line 113
Called from NGio::noLogin NGio.hx line 44
Error : Null Object Reference
```

**Comment by gedehari** [comment]
Same, mine is a Manjaro system, which is basically Arch. Did you compile this game or download the precompiled ones?

**Comment by E404NNF** [comment]
> Same, mine is a Manjaro system, which is basically Arch. Did you compile this game or download the precompiled ones?

i compiled it from https://aur.archlinux.org/packages/funkin-git/ (after adding the APIStuff file manually ofc...)

**Comment by gedehari** [comment]
Hmm.... Let me try to compile it on Windows and see if it has the same problem.

**Comment by E404NNF** [comment]
> Hmm.... Let me try to compile it on Windows and see if it has the same problem.

aight

**Comment by E404NNF** [comment]
if it works for you, i'll try compiling too, i have a windows 10 installation just for special cases™

**Comment by gedehari** [comment]
Yep.... Same thing here

![image](https://user-images.githubusercontent.com/10368254/103540874-64bc6180-4ed5-11eb-9856-153b8b715c33.png)

**Game and system information:**
Friday Night Funkin e1af25b35e3bfc194cd520c9935346c21b930473
Windows 10

**Console log:**
```
source/NGio.hx:35: INIT NOLOGIN
io/newgrounds/objects/events/Response.hx:40: [Newgrounds API] :: Error: Call unseccessful: #200 - Invalid app_id: ""
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleApplicationEvent lime/_internal/backend/native/NativeApplication.hx line 173
Called from lime._internal.backend.native.NativeApplication::updateTimer lime/_internal/backend/native/NativeApplication.hx line 585
Called from io.newgrounds.utils.AsyncHttp::update io/newgrounds/utils/AsyncHttp.hx line 176
Called from io.newgrounds.utils.AsyncHttp::handleMessage io/newgrounds/utils/AsyncHttp.hx line 125
Called from io.newgrounds.utils.AsyncHttp::handleMessage io/newgrounds/utils/AsyncHttp.hx line 114
Called from io.newgrounds.Call::onData io/newgrounds/Call.hx line 188
Called from io.newgrounds.utils.TypedDispatcher::dispatch io/newgrounds/utils/Dispatcher.hx line 113
Called from NGio::noLogin NGio.hx line 44                                                                                              
```

**Comment by E404NNF** [comment]
maybe that's the issue, which commit didn't need the APIStuff requirement? since on the AUR package the maintainer said that there was a commit that added the APIStuff requirement later

**Comment by gedehari** [comment]
The APIStuff requirement was always there since Newgrounds was implemented. Before the workaround in the README, I made my workaround, commenting this specific line of code:

https://github.com/ninjamuffin99/Funkin/blob/e1af25b35e3bfc194cd520c9935346c21b930473/source/TitleState.hx#L54-L59

The game compiles succesfully, but I can't access Freeplay for some reason, only Story Mode works. Playing from it works too.

**Comment by E404NNF** [comment]
ah ok, i'll try it now

**Comment by E404NNF** [comment]
it works!
![image](https://user-images.githubusercontent.com/37207067/103542824-396e4e00-4ea6-11eb-93de-be5d636517a0.png)

**Comment by gedehari** [comment]
Yes... But it's not a proper fix since Freeplay doesn't work.

Still, I'm not sure if this is a library issue or the game issue. I think library makes more sense. I really don't wanna read Haxe code lol.

Any ideas?

**Comment by E404NNF** [comment]
Imo it's a library issue, since it's giving an error about an invalid API key, maybe from library side they should make it so it ignores empty values?

Also, yeah the html5 version works without any changes

**Comment by E404NNF** [comment]
I found a workaround for Freeplay

**Comment by E404NNF** [comment]
Just comment these lines
https://github.com/ninjamuffin99/Funkin/blob/e1af25b35e3bfc194cd520c9935346c21b930473/source/FreeplayState.hx#L214-L216

**Comment by gedehari** [comment]
Works for me! Playing also works.
![image](https://user-images.githubusercontent.com/10368254/103591953-8f85d480-4f2c-11eb-81b8-9f74ffb6b9fa.png)

**Comment by E404NNF** [comment]
Nice

**Comment by gedehari** [comment]
Hi @Geokureli , you might wanna take a look at this issue.

**Comment by Geokureli** [comment]
can I get the gist of the issue? cus it sounds like none of you want Newgrounds stuff in your version of the game and the compile constants aren't cutting it

**Comment by gedehari** [comment]
We tried to compile the game and followed the empty APIStuff.hx workaround on README, but doing so also won't compile the game because the compiler complains that it has invalid app_id. Is that normal?

**Comment by Geokureli** [comment]
for short-term, I made a dummy NG project that you can all point to. use this APIStuff.hx

```hx
package;

class APIStuff
{
	public static var API:String = "51348:TtzK0rZ8";
	public static var EncKey:String = "5NqKsSVSNKHbF9fPgZPqPg==";
}
```

long term lets wrap NGio stuff in `#if newgrounds` compile conditions so people can just exclude the lib when they don't need it

**Comment by gedehari** [comment]
Excellent!

**Comment by E404NNF** [comment]
@ninjamuffin99 you might want to look into the "long term" fix

**Comment by Kiffolisk** [comment]
> The game compiles succesfully, but I can't access Freeplay for some reason, only Story Mode works. Playing from it works too.

Probably happens because of the NG requests it makes?

**Comment by gedehari** [comment]
Oh you are already here, anyways

> Probably happens because of the NG requests it makes?

I think so, thats why commenting stuff NGio related works, then the game makes zero contact with newgrounds, which is what the developer probably want.

**Comment by Geokureli** [comment]
I'm not Cam, but it looks like he wants NG.io features like event logging and more, even when there is no NG log in. I can understand wanting this. you guys can just use the secondary api key I posted above since you're likely not intersted in API features, and ninjamuffin doesn't want to log your personal version's events

**Comment by Geekume** [comment]
@E404NNF im curious us there anyway to tell me the log when it successfully compiles I noticed something very interesting in my log the polymod lib has some warnings that you guys didn't and that is the library that they use with haxe to get their uis which inessentially is practically the only thing that is not working (under the presumption they use the same thing for in game)

**Comment by lolBoi9696** [comment]
lol this happend to me once but that was because newgrounds was down then

**Comment by XuelDev** [comment]
> for short-term, I made a dummy NG project that you can all point to. use this APIStuff.hx
> 
> ```hx
> package;
> 
> class APIStuff
> {
> 	public static var API:String = "51348:TtzK0rZ8";
> 	public static var EncKey:String = "5NqKsSVSNKHbF9fPgZPqPg==";
> }
> ```
> 
> long term lets wrap NGio stuff in `#if newgrounds` compile conditions so people can just exclude the lib when they don't need it

Thanks dude
