### ISSUE TITLE
Question: Open source rule applies to mods?

### ISSUE THREAD

**Issue by AbnormalPoof** [FunkinCrew/Funkin#1462]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

## What is your question?
Does the open source rule apply to all mods after it was implemented, or does it also apply to mods before it was implemented

**Comment by napstaa967** [comment]
i think it applies to all mods

**Comment by ninjamuffin99** [comment]
open source your mods or else I will hate you

**Comment by polybiusproxy** [comment]
> open source your mods or else I will hate you

oh shit

**Comment by KitOdin** [comment]
why tho?

**Comment by napstaa967** [comment]
> why tho?

the main game is open source and free for everyone to modify, its not fair that then someone grabs it, modifies it and then rereleases it without opening it too for others to also modify

**Comment by Maniues** [comment]
> 
> 
> > why tho?
> 
> the main game is open source and free for everyone to modify, its not fair that then someone grabs it, modifies it and then rereleases it without opening it too for others to also modify

Additionally, mod can be removed, so source code is usefull to fix errors when author don't work on it.
