### ISSUE TITLE
Week 7 Cutscene Volume Issue

### ISSUE THREAD

**Issue by StarlightChronix96** [FunkinCrew/Funkin#1463]
When the cutscenes play for week 7 no matter what volume you put it at you could still hear the cutscene as if you never turned it down at all. You could mute or put it up all the way and it stays at the same volume.

https://user-images.githubusercontent.com/89290478/130311685-e02b9f2d-0737-4806-bf0c-afb25f91b855.mp4

**Comment by ACrazyTown** [comment]
I think that's because of the way cutscenes are played in the 0.2.8 NG preview, I'm sure this'll be fixed with the new way cutscenes work in the itch release of Week7

**Comment by ThePlank** [comment]
probally because the cutscene shit uses openfl sounds and its not gonna apply the haxeflixel volume

**Comment by Cheemsandfriends** [comment]
The best solution is mute the video and then load the sound separated from the video... I guess lolol

**Comment by ACrazyTown** [comment]
> The best solution is mute the video and then load the sound separated from the video... I guess lolol

or maybe just to sync together flixel's sound and openfl's sound

**Comment by s-zenmode** [comment]
theoretically wouldnt that be a haxeflixel issue and not with the game...?

**Comment by MAJigsaw77** [comment]
This can fix this issue I guess
```haxe
netStream.soundTransform = new SoundTransform(FlxG.sound.volume);
```
