### ISSUE TITLE
Question: .FLA Flash files

### ISSUE THREAD

**Issue by Maniues** [FunkinCrew/Funkin#1466]
What are .fla files? How to open/edit/convert them without Adobe Animate? How do you convert them at compilation time (library)? Why flash files?

**Comment by ThePlank** [comment]
i think they used flash because they needed sparrow spritesheets or thats what phantomarcade or evilsk8r where used to

**Comment by Maniues** [comment]
@susyboy23 I understand that people can choose the programs, but in this case, the only way to make mods/edit fnf is to buy commercial license. I cannot make any modification on Linux system, I cannot use AE, because I don't have a license. 7-days trial give me an option to make convert them to mp4, but after 7 days I must stop my work, ask friends or make second Adobe account. Using fileformat that there are no open-source opener/editor is bad.

**Comment by AbnormalPoof** [comment]
buy animate and run the exe via wine

**Comment by Maniues** [comment]
> 
> 
> buy animate and run the exe via wine

Buying AE only for modding FNF, without any earning is waste of money. I don't want to do that. But I know, that you cannot help me with it. I got an answer - I cannot use flash files. I know that you won't do more (you will not help me with buying Animate :) ). Thanks for the answer!
