### ISSUE TITLE
source_red/Character.hx:510: characters 25-26 : Unexpected )

### ISSUE THREAD

**Issue by Zcragus** [FunkinCrew/Funkin#1471]
Hello, I would like someone to help me because when I launch the cmd and I use the windows test file, I get the following message

source_red/Character.hx:510: characters 25-26 : Unexpected ) 

And I don't have anything changed I don't understand ...

If someone could help me more 

Fank

**Comment by shibest** [comment]
Do u mind telling us what is on line 510 in Character.hx
