### ISSUE TITLE
Question: is there an iconGrid.fla?

### ISSUE THREAD

**Issue by gamerbross** [FunkinCrew/Funkin#1473]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

## What is your question?

iconGrid.fla?

**Comment by napstaa967** [comment]
there's no need for a flash file for the icon grid

**Comment by Bloopsdoob** [comment]
> there's no need for a flash file for the icon grid

One would be needed if we were to swap colors, or modify expressions, these will also help provide a size reference.

**Comment by KlutchDj** [comment]
there wont be any need for this. Ninjamuffin changed the way how icon grids work by separating each character icon grid into its own seperate PNG's. As posted on his twitter if i can find it.

**Comment by Bloopsdoob** [comment]
> there wont be any need for this. Ninjamuffin changed the way how icon grids work by separating each character icon grid into its own seperate PNG's. As posted on his twitter if i can find it.

That still wouldn't solve the issue I pointed out, editing fnf assets is already hard enough as is with the Anti Aliasing applied from flash.

**Comment by ninjamuffin99** [comment]
icons are made by evilsk8r in just pure PNG. it's not flash art!

**Comment by Bloopsdoob** [comment]
oh well that's nice to know!

**Comment by MrClogsworthYT** [comment]
> icons are made by evilsk8r in just pure PNG. it's not flash art!

ayo you talking to a guy who recoded week 7 to mobile with ugh animation and heh pretty good animation AND notesplash

**Comment by napstaa967** [comment]
> > icons are made by evilsk8r in just pure PNG. it's not flash art!
> 
> ayo you talking to a guy who recoded week 7 to mobile with ugh animation and heh pretty good animation AND notesplash

you're talking to the original game creator.
