### ISSUE TITLE
The game soft locks when the pause key is pressed right when the song end transition appears

### ISSUE THREAD

**Issue by sqirradotdev** [FunkinCrew/Funkin#15]
The pause menu appears, but I cannot restart the song or exiting to menu. Resuming the game works, but with no notes, the characters doesn't follow the beat. When I purposely lose, the game over screen brought up, pressing Escape stops the music, pressing enter only plays the game over end, fades out, and does nothing.

**Comment by ninjamuffin99** [comment]
I thiiiiink i fixed with 5b46515 , 0.2.2 update should roll out real soon!
