### ISSUE TITLE
Audio bug in menus

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#16]
If you go to the Free Play menu, music for the level you're hovered over will play but if you back out of the Free Play menu, it will continue to play in the other menus. Also, when exiting a level, the audio will be dead silent in the menus until you hover over a song in Free Play or go to the Story Mode menu.

.

**Comment by gedehari** [comment]
> If you go to the Free Play menu, music for the level you're hovered over will play but if you back out of the Free Play menu, it will continue to play in the other menus.

I think this is intentional by the developer

> Also, when exiting a level, the audio will be dead silent in the menus until you hover over a song in Free Play or go to the Story Mode menu.

This here, I don't know if it's intentional or not, probably not, I am gonna make a simple pull request.
