### ISSUE TITLE
Crashes on Chromebook plz fix this or make a chrome os build

### ISSUE THREAD

**Issue by PGCALVAN** [FunkinCrew/Funkin#162]

**Comment by gedehari** [comment]
Have seen this issue multiple times, I don't have Chrome OS so I can't really experiment what the heck is wrong, maybe wacky WebGL implementation?


I don't think HaxeFlixel (the game engine this game runs) support deploying to Chrome OS, however you can try running the Linux build on Chrome OS. If you tried it, let me know!

**Comment by fidbro237** [comment]
surprisingly, for me it works

**Comment by SPostClp** [comment]
you can only play on this one :{  [(https://ninja-muffin24.itch.io/friday-night-funkin)]
