### ISSUE TITLE
Could not load module lime@lime_application_create_prime

### ISSUE THREAD

**Issue by Arvha256** [FunkinCrew/Funkin#166]
I have tried reinstalling and it still won't let me in. I am also downloading it from Itch.io.

**Comment by Arvha256** [comment]
Nevermind, I got it to work on the 32 Bit version, please still tell me what this means.

**Comment by Orangecyndaquil15** [comment]
how did you fix it. i'm still having problems with psych engine

**Comment by MemeHovy** [comment]
> Nevermind, I got it to work on the 32 Bit version, please still tell me what this means.

corrupted lime.ndll

**Comment by MemeHovy** [comment]
> how did you fix it. i'm still having problems with psych engine

your lime.ndll is corrupted
