### ISSUE TITLE
(MacOSX) gf was a curtain all along?!?!?

### ISSUE THREAD

**Issue by TAKfsg** [FunkinCrew/Funkin#167]
Yes the gf is a curtain. This is the problem.
![Screen Shot 2021-01-07 at 10 43 18 PM](https://user-images.githubusercontent.com/73729536/103983234-c41aab80-5139-11eb-8482-810988b6fd7e.png)

**Comment by gedehari** [comment]
lmao how???

Anyways, does this happen only on the tutorial, or all of the songs?

**Comment by Noelnoel07** [comment]
It happens on all songs.
