### ISSUE TITLE
Enhancement: Add repository "about"

### ISSUE THREAD

**Issue by Morphclue** [FunkinCrew/Funkin#1685]
## What is your suggestion, and why should it be implemented?
I would like to suggest to fill in the `About`-section in the repository.
This has several benefits:
* Social preview would have a description (when sending repo-link to others)
* Short description for users that find this project via [Github Explore](https://github.com/search?q=funkin)
* Generated Profile-Readmes would have a description
* etc.

**Comment by Punkinator7** [comment]
You forgot the github related label, but apart from that its pretty sound

**Comment by Morphclue** [comment]
@Punkinator7 It is not possible to add labels. 
The label `enhancement` for example was added automatically by using the `Issue-Template`.
