### ISSUE TITLE
what is crtdbg.h?

### ISSUE THREAD

**Issue by DomixGit** [FunkinCrew/Funkin#1694]
so basically i was trying to compile the game but it showed this message, "C1083: Cannot open include file: 'crtdbg.h': No such file or directory"
![help](https://user-images.githubusercontent.com/82989111/131203074-e9cb9e6d-ef9e-4c1e-9c2c-b6e02161c720.PNG)

**Comment by napstaa967** [comment]
its a header file for cplusplus

if you get the "no such file or directory" error it means you're probably missing something from visual studio community's package setup

make sure you have everything required for building to windows, its on the bottom of the readme

**Comment by DomixGit** [comment]
thx
