### ISSUE TITLE
Whenever I try compiling the game, it shows this: source/Discord.hx:4: characters 8-30 : Type not found : discord_rpc.DiscordRpc source/Discord.hx:13: characters 3-13 : Type not found : DiscordRpc source/Discord.hx:23: characters 4-14 : Type not found : DiscordRpc source/Discord.hx:28: characters 3-13 : Type not found : DiscordRpc source/Discord.hx:33: characters 3-13 : Type not found : DiscordRpc source/Discord.hx:38: characters 3-13 : Type not found : DiscordRpc source/Discord.hx:74: characters 3-13 : Type not found : DiscordRpc source/TitleState.hx:61: characters 16-28 : Type not found : APIStuff C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access and i dont know what to do.

### ISSUE THREAD

**Issue by toopvr1** [FunkinCrew/Funkin#1701]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

**Comment by ThePlank** [comment]
install discordrpc and create apistuff.hx and paste the stuff in the readme

**Comment by siky112** [comment]
please put the issue in the body of the issue and not the name

**Comment by teh404guy** [comment]
^

**Comment by Andreas010** [comment]
Just redo the steps, you need to do to compile... It's simple
