### ISSUE TITLE
Compiling help: [BRIEF DESCRIPTION / ERROR MESSAGE OUTPUT]

### ISSUE THREAD

**Issue by kinoko87** [FunkinCrew/Funkin#1705]
I'm trying to mess around with vanilla FNF source code, but whenever I run FNF, I get into this error

source/TitleState.hx:33: lines 33-429 : Defined in this class

How do I prevent this? Is it something from MusicBeatState and if so how do I fix it? Thanks.

I am using Windows, and I'm building the game on Windows.

**Comment by ThePlank** [comment]
uhhh
there shoud be a line above that
because this dosent show what is the problem

**Comment by ahazywinter** [comment]
> uhhh
> there shoud be a line above that
> because this dosent show what is the problem

I did find the issue, I think so atleast. It's because I currently use Kade Engine libraries which have updated versions of libraries FNF uses. Since there hasn't been any pushes to the code with update libraries, I can't code with vanilla FNF nor Kade Engine at the same time.
