### ISSUE TITLE
download not opening

### ISSUE THREAD

**Issue by livqz** [FunkinCrew/Funkin#171]
i downloaded the game and when i click to open it, it doesnt open.

**Comment by DaWreker** [comment]
Where did you download it from? What system?

**Comment by livqz** [comment]
https://ninja-muffin24.itch.io/funkin if you scroll down a bit it gives you downloads. i downloaded the 64 bit one

**Comment by gedehari** [comment]
Hi, have you already extracted the .zip to a folder? Let me know if it works, thanks

**Comment by livqz** [comment]
yes i extracted it and when i click on the funkin application file it just doesnt open

**Comment by gedehari** [comment]
Hmm... Is there a debug.log file on the extracted folder? If so, can you send it here?

**Comment by livqz** [comment]
i don't see a debug.log file on the extracted folder

**Comment by devin503** [comment]
are you on Linux? if so, open your game folder in a terminal and type "./Funkin", then press enter.

**Comment by Whatisbehindu** [comment]
I have the same issue but on windows. same steps as OP

**Comment by livqz** [comment]
> 
> 
> are you on Linux? if so, open your game folder in a terminal and type "./Funkin", then press enter.

i am on windows

**Comment by devin503** [comment]
open a command prompt (in the game folder, click the path and type "cmd") and type Funkin.exe

**Comment by Whatisbehindu** [comment]
Nope. Didn't seem to solve the problem.
