### ISSUE TITLE
Bug Report: Week 5 story mode sprites are way, WAY too small

### ISSUE THREAD

**Issue by AbnormalPoof** [FunkinCrew/Funkin#1710]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.2.8(Newgrounds exclusive preview)

## Please describe your issue. Provide extensive detail and images if possible.
Self explanatory, the sprites for daddy and mommy mearest on week 5 are way too small (story mode menu only!!!!!!!)
![Screenshot 2021-08-29 3 33 55 PM](https://user-images.githubusercontent.com/86753001/131264643-88ab9113-17cf-4d22-a0e5-bd0aaf0db4ca.png)
My guess is that someone fucked up the xml file lol

**Comment by DotWith** [comment]
You can change the size at [StoryMenuState](https://github.com/ninjamuffin99/Funkin/blob/e8231247b78ffbca7d2cd677c2665ee9088c831e/source/StoryMenuState.hx#L410)

**Comment by Windows1Door2Daniel** [comment]
> You can change the size at [StoryMenuState](https://github.com/ninjamuffin99/Funkin/blob/e8231247b78ffbca7d2cd677c2665ee9088c831e/source/StoryMenuState.hx#L410)

It says it was in Chrome

**Comment by s-zenmode** [comment]
i would label this an 'enhancement' ngl

**Comment by Windows1Door2Daniel** [comment]
Yo want to see yo momma deez nuts?
