### ISSUE TITLE
ADD FNF WEEK 7 FILES & FLA'S

### ISSUE THREAD

**Issue by BitchL** [FunkinCrew/Funkin#1727]
im asking it again about im ANNOYED whit week 7 not being added here
i want the fla's to animate
bc do my own tankman assets its hard to do
so pls NINJAMUFFIN se this and add it

**Comment by napstaa967** [comment]
week 7 isn't out yet, they will prob be added once week 7 is released

**Comment by s-zenmode** [comment]
he said that he will release the source code for week 7 release when week 8 comes out since apparently its kinda a lot of work to release the two source codes seperately and he will just release it with week 8 or something like that

**Comment by HiroOfc** [comment]
he'll probably say "no"

**Comment by ninjamuffin99** [comment]
will happen eventually, dont need an open issue for it tho

**Comment by KitOdin** [comment]
good.
