### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1732]
[Deleted]

**Comment by FNFboi22** [comment]
Thank you. I will try this.

**Comment by FNFboi22** [comment]
But. I have not installed visual studio 2019.
Could someone please link me the download?

**Comment by Cheemsandfriends** [comment]
> But. I have not installed visual studio 2019.
> Could someone please link me the download?

It is necessary since you need to download the sdk and stuff. Download it [Here](https://visualstudio.microsoft.com/es/vs/community/).

**Comment by FNFboi22** [comment]
Ok. I am trying on a different pc.
The thing i need help is that:
I know its compiling but i really dont get where to install ctdbg.h
 @Cheemsandfriends

**Comment by AbnormalPoof** [comment]
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\`
Better yet, just reinstall visual studio

**Comment by FNFboi22** [comment]
Hey, @AbnormalPoof, Thanks for the message,
But this is sorta my problem but, My computer is a MSI and it says it does not support the type of computer I have.
Do you think it is my computer or me not getting the "setup.bat" file.

**Comment by FNFboi22** [comment]
Here is the transcript:
Compiling haxe...
Error: 64bit is not your computer, and continuing will make it not work, so we have blocked the command "lime test windows"

**Comment by FNFboi22** [comment]
That is not the actual transcript, its just saying it does not support my computer.

**Comment by Cheemsandfriends** [comment]
You can compile it for 32bit tho,

**Comment by FNFboi22** [comment]
Hey, @AbnormalPoof and @Cheemsandfriends, My pc is 64Bit, Do you think it will still compile, because i dont think haxe supports 64bit.

**Comment by FNFboi22** [comment]
Only one one computer it works

**Comment by FNFboi22** [comment]
> Only one one computer it works

**Comment by FNFboi22** [comment]
Also, if someone could help, I cannot compile kade-engine, do you know why? It gives me a error like "you need extension-webm" Once i actually already have extension-webm.

**Comment by Cheemsandfriends** [comment]
> Hey, @AbnormalPoof and @Cheemsandfriends, My pc is 64Bit, Do you think it will still compile, because i dont think haxe supports 64bit.

It works for 64 bits and for 32 bits.

> Only one one computer it works

Huh? What do you mean??

>Also, if someone could help, I cannot compile kade-engine, do you know why? It gives me a error like "you need extension- 
> webm" Once i actually already have extension-webm.

This is funkin Master, Not KE

**Comment by FNFboi22** [comment]
Hey everyone, so i have two computers.


> > Hey, @AbnormalPoof and @Cheemsandfriends, My pc is 64Bit, Do you think it will still compile, because i dont think haxe supports 64bit.
> 
> It works for 64 bits and for 32 bits.
> 
> > Only one one computer it works
> 
> Huh? What do you mean??
> 
> > Also, if someone could help, I cannot compile kade-engine, do you know why? It gives me a error like "you need extension-
> > webm" Once i actually already have extension-webm.
> 
> This is funkin Master, Not KE

Hey, so You may not understand this but:
1 I have two computers.
2.Kade Engine? Sorry i will post a new issue on kade engine.

**Comment by Cheemsandfriends** [comment]
> 
> 
> Hey everyone, so i have two computers.
> 
> > > Hey, @AbnormalPoof and @Cheemsandfriends, My pc is 64Bit, Do you think it will still compile, because i dont think haxe supports 64bit.
> > 
> > 
> > It works for 64 bits and for 32 bits.
> > > Only one one computer it works
> > 
> > 
> > Huh? What do you mean??
> > > Also, if someone could help, I cannot compile kade-engine, do you know why? It gives me a error like "you need extension-
> > > webm" Once i actually already have extension-webm.
> > 
> > 
> > This is funkin Master, Not KE
> 
> Hey, so You may not understand this but: 1 I have two computers. 2.Kade Engine? Sorry i will post a new issue on kade engine.

1. I don't care if you have one, two or seven million
2.  You shouldn't post Kade Engine issues, If you have a issue with KE post it in KE github.

**Comment by FNFboi22** [comment]
Nevermind
