### ISSUE TITLE
Enhancement: Pixel note splashes

### ISSUE THREAD

**Issue by sawyer400** [FunkinCrew/Funkin#1734]
so, when i was playing week 6, and i thought to myself, wouldn't it be more accurate if there was pixel note splashes? so uh... pixel note splashes would be super accurate.

**Comment by sawyer400** [comment]
(also the splashes look like c*m lol)

**Comment by Steviegt6** [comment]
> 
> 
> (also the splashes look like c*m lol)

Are you 10?

**Comment by Windows1Door2Daniel** [comment]
> > (also the splashes look like c*m lol)
> 
> Are you 10?

Well he is rigth, look like C*m

**Comment by prokube** [comment]
> > > (also the splashes look like c*m lol)
> > 
> > 
> > Are you 10?
> 
> Well he is rigth, look like C*m

Are you 10?

**Comment by AbnormalPoof** [comment]
Well he is rigth, look like c-.....uhhh, *ahem*. Magic yogurt

**Comment by Windows1Door2Daniel** [comment]
> > > > (also the splashes look like c*m lol)
> > > 
> > > 
> > > Are you 10?
> > 
> > 
> > Well he is rigth, look like C*m
> 
> Are you 10?

If i were 10, i wouldnt even know what c*m is

**Comment by Windows1Door2Daniel** [comment]
> Well he is rigth, look like c-.....uhhh, _ahem_. Magic yogurt

That doesnt exist

cum

**Comment by BamSchoolGithub** [comment]
> im not 10, im 36

no way your 36 and censoring cum

**Comment by Michu0204** [comment]
Added in 0.6.0
