### ISSUE TITLE
Compiling help: [Powershell cant find "project.xml" / Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command]

### ISSUE THREAD

**Issue by KIvanRuiz** [FunkinCrew/Funkin#1735]
So when i do the command "`Lime test windows`" in powershell i get this error "`Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command`" even tho i have installed all of the dependencies
[Image of the error](https://imgur.com/a/1fW4JWW)

Can somebody help me?

- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

**Comment by ThePlank** [comment]
go to the folder

**Comment by Cheemsandfriends** [comment]
You haven't opened Windows PowerShell the to correct folder or you deleted Project.xml

**Comment by ThePlank** [comment]
> You haven't opened Windows PowerShell the to correct folder or you deleted Project.xml

its the former because you can see the directory in the powershell window

![chrome_Oxal1jgvY4](https://user-images.githubusercontent.com/75984453/132505615-84a51bd0-0ce4-4085-8900-e3ee7e533eda.png)

**Comment by Cheemsandfriends** [comment]
> > You haven't opened Windows PowerShell the to correct folder or you deleted Project.xml
> 
> its the former because you can see the directory in the powershell window
> 
> ![chrome_Oxal1jgvY4](https://user-images.githubusercontent.com/75984453/132505615-84a51bd0-0ce4-4085-8900-e3ee7e533eda.png)

Yes. But Idk what was his problem really exactly. So I told the possible two problems

**Comment by AbnormalPoof** [comment]
cd to the project directory?

**Comment by UNSTOP4BLE** [comment]
> cd to the project directory?
exacly

**Comment by redbluexe0** [comment]
if its in a different drive then 

cd /D drive letter [D:\ is probably u had]\lead\it\to\the\source\code\is
