### ISSUE TITLE
Enhancement: Change the arrow colors 

### ISSUE THREAD

**Issue by AbnormalPoof** [FunkinCrew/Funkin#1736]
#### Please check for duplicates or similar issues before creating this issue.
The ability to change arrow colors based on hue and brightness

## What is your suggestion, and why should it be implemented?
It would be beneficial for colorblind people, and it's nice to have a new color every once in a while.

**Comment by ACrazyTown** [comment]
P sure ninjamuffin showed in a stream once that he's working on a way to change arrow colors by tweaking the rgb values in game or sum shit like that
