### ISSUE TITLE
Bug Report: Game crash/closes and Gameplay not working properly

### ISSUE THREAD

**Issue by shabman** [FunkinCrew/Funkin#1737]
Running the game on macOS.

When I press enter the game closes as soon as it switches to FreePlay and Story mode doesn't show any arrows or notes in any of the weeks. There's no errors in the console, not sure why this is happening.

Using v0.2.7.1 (latest) btw

**Comment by Cheemsandfriends** [comment]
Lack of loading note assets? or Lack of asset sprite?

**Comment by runkanrenchu** [comment]
> Lack of loading note assets? or Lack of asset sprite?

Don't think so. When it doesn't find a sprite with said ID/key, it sends an error on-screen instead of crashing directly. Have you modified the game in any way? Did you compile it from source?

**Comment by dakotath** [comment]
Its a pollymod problem. go to TitleState.hx, find 		
#if polymod
polymod.Polymod.init({modRoot: "mods", dirs: ['introMod']});
#end
and // out polymod.Polymod.init
