### ISSUE TITLE
fnf has a bug

### ISSUE THREAD

**Issue by OKTHENSOFNF** [FunkinCrew/Funkin#1741]
where if you umm well drag the tab and hold the game does not move

**Comment by Cheemsandfriends** [comment]
Be more specific

**Comment by s-zenmode** [comment]
im pretty sure thats a common occurrance with html5 games where if you unfocus it will probably autopause for your convenience and due to constraints with html5

**Comment by cuckydev** [comment]
this happens in every windows application ever

**Comment by ahazywinter** [comment]
That...is how most programs work when you drag them.

**Comment by Andreas010** [comment]
lmao, this is intentionall, to save memory. This is a feature most programs do. Moving/Dragging the Window is the same as not having it focused. It's the same system, as if you just open another program, while FNF is running. You can't change that and it's NOT a bug

Have a great day everyone

**Comment by HTV04** [comment]
Pretty sure this has something to do with SDL, so this can't be fixed.
