### ISSUE TITLE
Bug Report: Freeplay crashes the game

### ISSUE THREAD

**Issue by MRSomeone000** [FunkinCrew/Funkin#1742]
### If you are playing the game in a browser, what site are you playing it from?

- [x] Running both html5 and windows .exe file from source
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

I start up the game on desktop and every time I go to freeplay, It crashes.
I tried in browser and it just froze while still playing the main menu music.
I have already tried to fix it using the other bug report on the same issue and it did not help.

## Please describe your issue. Provide extensive detail and images if possible.

This is the windows .exe file attempt
![Screenshot 2021-09-09 114312](https://user-images.githubusercontent.com/90401516/132707980-c5176f4b-43e0-448b-bbfb-778f3b3c2bc5.png)

This is the browser attempt
![Screenshot 2021-09-09 114338](https://user-images.githubusercontent.com/90401516/132708424-002a87ce-f2e4-4f7d-bd43-6bd05a469d62.png)

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

![Screenshot 2021-09-09 114141](https://user-images.githubusercontent.com/90401516/132707917-8619b6f9-bad4-4b5a-a89d-cf6b1e906acc.png)

**Comment by ThePlank** [comment]
remove this line from freeplaystate
https://github.com/ninjamuffin99/Funkin/blob/f7c4a7bd82005fa9822206b8678d4a736c2163b5/source/FreeplayState.hx#L260-L262

**Comment by MRSomeone000** [comment]
I swear I had tried that earlier. It fixed it this time tho so thanks
