### ISSUE TITLE
Compiling help: [Warning: Could not find Visual Studio 2017 VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC/ ERROR MESSAGE OUTPUT]

### ISSUE THREAD

**Issue by ItzaNoobxd** [FunkinCrew/Funkin#1746]
pls help i can't compile my game 
![image](https://user-images.githubusercontent.com/89594524/132955318-8586ffa9-f182-466c-a26b-9554b377fb62.png)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

**Comment by jukru89** [comment]
same problem

**Comment by ThePlank** [comment]
https://github.com/ninjamuffin99/Funkin#compiling-game

**Comment by s-zenmode** [comment]
did u install visual studio community 2019 AND the required components as seen in the compiling help?

**Comment by runkanrenchu** [comment]
@ItzaNoobxd , modify your Visual Studio 2019 installation and install the following components:

`- MSVC v142 - VS 2019 C++ x64/x86 build tools
- Windows SDK (10.0.17763.0)`

And you should be good to go.

**Comment by MeekOnGithub** [comment]
> @ItzaNoobxd , modify your Visual Studio 2019 installation and install the following components:
> 
> `MSVC v142 - VS 2019 C++ x64/x86 build tools` `Windows SDK (10.0.17763.0)`
> 
> And you should be good to go.

I installed all followed components and that dosen't work

**Comment by YuyioYT** [comment]
how install visual studio 2019 component

**Comment by MemeHoovy** [comment]
when you install ```MSVC v142 - VS 2019 C++ x64/x86 build tools``` make sure it's **latest**

**Comment by MemeHoovy** [comment]
> how install visual studio 2019 component

![Screenshot 2022-09-20 191453](https://user-images.githubusercontent.com/97995998/191380990-4e308625-adf1-43cf-9e6d-b5147552e7ea.png)
![Screenshot 2022-09-20 191428](https://user-images.githubusercontent.com/97995998/191380993-90176e7c-c59b-4656-af03-2c8345f3ab30.png)

**Comment by ItzaNoobxd** [comment]
it worked, thx

> @ItzaNoobxd , modify your Visual Studio 2019 installation and install the following components:
> 
> `MSVC v142 - VS 2019 C++ x64/x86 build tools` `Windows SDK (10.0.17763.0)`
> 
> And you should be good to go.

thx
