### ISSUE TITLE
Enhancement: Long Hold Note Spam Arrows

### ISSUE THREAD

**Issue by s-zenmode** [FunkinCrew/Funkin#1748]
## What is your suggestion, and why should it be implemented?

When I spam pressed the long notes (if you know what i mean), it would make miss noises.
As far as I'm concerned, this was a way to play long notes in DDR or something
So i think maybe you can add code so that when someone spams it checks if it's the long note part thingy, and if it is then don't count it as a miss OR a hit. just make it affect the score and misses as if they normally held it

sorry if you had a stroke reading that

**Comment by DeceptedParasite** [comment]
I understand what you mean and I will shorten it down for you, like in osu when you miss a sustain note it would not count as constant misses so you want fnf to make it so when you miss a sustain note it only misses once and not constant
