### ISSUE TITLE
Numbers missing on credits screen

### ISSUE THREAD

**Issue by ActualMandM** [FunkinCrew/Funkin#175]
In [TitleState.hx](https://github.com/ninjamuffin99/Funkin/blob/d96e28e64eafc0a899b85161221a658e7ba5ed1a/source/TitleState.hx#L175), there are two names that have numbers in them, ninjamuffin99 and evilsk8er.

However in the game, the numbers do not appear.
<img width="641" alt="2021-01-09_22-09-46_Funkin" src="https://user-images.githubusercontent.com/15317421/104115765-95324000-52c7-11eb-98e2-7f9da86ff1e3.png">

**Comment by gedehari** [comment]
This is because the developer forgot to put the bold numbers on the font texture. Dunno if it's much of a problem, but it's there.
