### ISSUE TITLE
Question:how does the game read controls and where in the source code

### ISSUE THREAD

**Issue by UNSTOP4BLE** [FunkinCrew/Funkin#1752]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

**Comment by Maniues** [comment]
Reading Controls is not a part of Friday Night Funkin. It's low-level function, programmed in packages like HaxeFlixel, OpenFL, Lime, or Haxe itself. 
As declared in Controls.hx, FNF reads controls from:
`flixel.input.actions.*,
flixel.input.gamepad.*,
flixel.input.keyboard*
`
So reading controls from keyboard may be part of Operating System, but interpreter is part of FNF: [Controls.hx](https://github.com/ninjamuffin99/Funkin/blob/master/source/Controls.hx)

**Comment by UNSTOP4BLE** [comment]
So i cant just rebind them without external tools and engines?

**Comment by Maniues** [comment]
You can. You can bind up arrow as a other key, g as down arror and any another key. The only restriction is that applies only in game. You cannot rebind you keyboard (modify drivers) but in game - yes

**Comment by UNSTOP4BLE** [comment]
how?

**Comment by Maniues** [comment]
@UNSTOP4BLE Just modify the source, then compile the game. What you want to rebind?

**Comment by UNSTOP4BLE** [comment]
Dont ask why but i want A, S to be the same
And i want Z to be D, and X to be W, i also want W to be X and D to be Z

**Comment by Maniues** [comment]
@UNSTOP4BLE You want to keep old binds?

**Comment by UNSTOP4BLE** [comment]
No?

**Comment by Maniues** [comment]
Wait, I will tell you what I mean:

> Dont ask why but i want A, S to be the same

So, either A and S must work?

**Comment by UNSTOP4BLE** [comment]
![download](https://user-images.githubusercontent.com/88965856/133475641-5160ee28-957b-4d51-8934-703f7e1f4462.png)

**Comment by UNSTOP4BLE** [comment]
a and s stay default

**Comment by Maniues** [comment]
@UNSTOP4BLE You can choose only some parameters. 
If you you Kade Engine, you can rebind game (image)
If you use vanilla FNF, give me parameters from the image, and I will rebind FNF, and I will send you source and binaries
![image](https://user-images.githubusercontent.com/66561397/133488958-bd833cc4-c535-4182-896a-592a76e6525b.png)

**Comment by UNSTOP4BLE** [comment]
sry i didnt tell u this but im trying to do it for a ios port [FunkinIOS](https://github.com/hadobedo/FunkiniOS) (the source code is 99% the same)
so that explains the weird control scheme and wdym by parameters?

**Comment by Maniues** [comment]
> 
> 
> sry i didnt tell u this but im trying to do it for a ios port [FunkinIOS](https://github.com/hadobedo/FunkiniOS) (the source code is 99% the same)
> so that explains the weird control scheme and wdym by parameters?

Can you limit your scheme to above image or it's impossible? I can change Controls.hx for you, but I don't have Iphone/Mac so I won't compile it.

**Comment by UNSTOP4BLE** [comment]
i can compile it but make sure you get controls.hx from the funkinios link above, also what does limit the scheme mean. sry if its a stupid question

**Comment by Maniues** [comment]
@UNSTOP4BLE oh, thanks for updating. I will check it

**Comment by Maniues** [comment]
@UNSTOP4BLE "ACCEPT" means "ENTER" and "PAUSE" too?

**Comment by UNSTOP4BLE** [comment]
Yes

**Comment by UNSTOP4BLE** [comment]
actually i dont think so, it is bound to Z witch in the original game only means like advance through the menu, not pause

**Comment by UNSTOP4BLE** [comment]
@Maniues did you do it?

**Comment by Maniues** [comment]
@UNSTOP4BLE I'm going to try it at the moment.

**Comment by UNSTOP4BLE** [comment]
oh, cool. i made the sprites

**Comment by Maniues** [comment]
@UNSTOP4BLE I sent you invitation to get a copy of rebinded game on GitHub. If you compile it, may you make a release in repo?

**Comment by UNSTOP4BLE** [comment]
Ok, i will try it tomorow after school

**Comment by Maniues** [comment]
Okay

**Comment by UNSTOP4BLE** [comment]
Well, i somehow got a cold so i cant go to school. I will try to compile the game now

**Comment by UNSTOP4BLE** [comment]
@Maniues sadly it hasnt chaned anything, i think that there are controls in other files like mainmenustate.hx and others

**Comment by UNSTOP4BLE** [comment]
@Maniues what did you change in controls.hx?

**Comment by Maniues** [comment]
@UNSTOP4BLE Did you compile game from [this](https://github.com/Maniues/FunkiniOS-rebinds)?
See the [commit](https://github.com/Maniues/FunkiniOS-rebinds/commit/7b4cac0fe4163adc1d82fcf60f384307211f5960)

**Comment by UNSTOP4BLE** [comment]
yeah, i see what you chaned rn too, tryng to change other stuff too

**Comment by UNSTOP4BLE** [comment]
why do you have 
inline bindKeys(Control.UP, [W, FlxKey.UP]);
and
inline bindKeys(Control.UP, [X, FlxKey.UP]);
in the same section?

**Comment by Maniues** [comment]
@UNSTOP4BLE  I will check this

**Comment by UNSTOP4BLE** [comment]
no i didnt relise it was just in the commit, the source code is fine

**Comment by UNSTOP4BLE** [comment]
this is so wierd! no matter what i change in controls.hx nothing changes, maybe the dev just put it in another file?

**Comment by Maniues** [comment]
@UNSTOP4BLE vanilla FNF works with Control.hx. Maybe iOS port changed the file.

**Comment by Maniues** [comment]
Does the FNF allow you to port it to iOS without using that fork?

**Comment by UNSTOP4BLE** [comment]
Nope, this one has on screen controls

**Comment by UNSTOP4BLE** [comment]
maybe it is possible to port the [luckydog7's](https://github.com/luckydog7/Funkin-android/releases) android port to ios? i have seen it on web browsers and they do work but i wanna play mods

**Comment by Maniues** [comment]
@UNSTOP4BLE It is possible (probably). Haxe is CROSS-PLATFORM. Just type lime build/test ios and it should work.

**Comment by UNSTOP4BLE** [comment]
wow, thats not the answer i expected! gonna try it now

**Comment by Maniues** [comment]
> 
> 
> wow, thats not the answer i expected! gonna try it now

I think It should work, but the same applies for C/C++ Language. This port may use Android API (I didn't check), and it may don't work, but yea, try!

**Comment by UNSTOP4BLE** [comment]
ok!

**Comment by UNSTOP4BLE** [comment]
do i have to do it in mac os? if i do it gives me Error: Source path "/usr/local/lib/haxe/lib/extension-webm/git/ndll/iPhone/libextension-webm.iphoneos.a" does not exist

**Comment by UNSTOP4BLE** [comment]
@Maniues on windows it gives me error  Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/iPhone/libextension-webm.iphoneos.a"

**Comment by UNSTOP4BLE** [comment]
on xcode it gives me Command ExternalBuildToolExecution failed with a nonzero exit code
the build tool is "make"

**Comment by Maniues** [comment]
@UNSTOP4BLE It means that you must have Iphone version of "extension-webm".
Try to get it here: https://github.com/KadeDev/extension-webm

**Comment by UNSTOP4BLE** [comment]
ok

**Comment by UNSTOP4BLE** [comment]
how do i install it?

**Comment by Maniues** [comment]
@UNSTOP4BLE Using HaxeLib. But you must select version from KadeDev . I think "haxelib install" and link to github. You must have installed openfl

**Comment by UNSTOP4BLE** [comment]
so like haxelib install https://github.com/KadeDev/extension-webm

**Comment by Maniues** [comment]
yes

**Comment by UNSTOP4BLE** [comment]
it just said no project available

**Comment by Maniues** [comment]
so try haxelib install entension-webm

**Comment by UNSTOP4BLE** [comment]
ok

**Comment by UNSTOP4BLE** [comment]
same error

**Comment by UNSTOP4BLE** [comment]
@Maniues xcode says make: *** [build-haxe-x86_64] Error 1

**Comment by Maniues** [comment]
I think, it's not supported on Iphone. It's C code, so it may need modifying. Leave Android port. I will check the rebinds of FunkiniOS again

**Comment by UNSTOP4BLE** [comment]
Ok, i will also take a look, idk why it amazed me that xcode even loaded with the android one

**Comment by AbnormalPoof** [comment]
haxelib git and then the github link

**Comment by Maniues** [comment]
@AbnormalPoof Oh, yes you are right, thanks! @UNSTOP4BLE  Try this: 
`haxelib git https://github.com/KadeDev/extension-webm`

**Comment by AbnormalPoof** [comment]
also you can just edit controls.txt and then compile the game lmao

**Comment by UNSTOP4BLE** [comment]
Are you f**king kidding??!??! I will try it lmao

**Comment by UNSTOP4BLE** [comment]
@AbnormalPoof the controls.txt in the ios port just say "Gangsta spongebob"

**Comment by Maniues** [comment]
@UNSTOP4BLE Yea, it's look like ignoring that file. But, you may try compile it with changed file from another version of FNF (e.g. FNF, Kade, or other) Look [here](https://github.com/ninjamuffin99/Funkin/blob/master/assets/preload/data/controls.txt)

**Comment by UNSTOP4BLE** [comment]
It has a controlsold.txt so do i just rename it to controls.txt?

**Comment by Maniues** [comment]
> 
> 
> It has a controlsold.txt so do i just rename it to controls.txt?

Rename to controls.txt a change binds to your own

**Comment by UNSTOP4BLE** [comment]
Ok i will try

**Comment by Maniues** [comment]
And try to compile (see above comments about extension-webm)

**Comment by UNSTOP4BLE** [comment]
Ok

**Comment by UNSTOP4BLE** [comment]
the controls.txt didnt work and the extension webm download just asks me about the git path

**Comment by Maniues** [comment]
Can you send screenshot or logs from haxelib git (giturl)

**Comment by UNSTOP4BLE** [comment]
There is nothing it just says "git path:"

**Comment by UNSTOP4BLE** [comment]
kind of a update, there seem to be controls almost in every .hx file. i will try to change them all
