### ISSUE TITLE
I can't compile my Friday Night Funkin mod for html5

### ISSUE THREAD

**Issue by Mr-funkinguy** [FunkinCrew/Funkin#1753]
So when I try to compile my Mod I get this:

/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:135: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
/polymod/git/polymod/format/ParseRules.hx:287: characters 17-21 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.
/polymod/git/polymod/format/ParseRules.hx:386: characters 17-21 : Warning : haxe.Utf8 is deprecated. Use UnicodeString instead.

Please help

- [ ] Windows
- [ ] Mac
- [ ] Linux
- [X] HTML5

**Comment by AbnormalPoof** [comment]
It's just a warning, game compiles fine
