### ISSUE TITLE
Compiling help: [source/Controls.hx:411: characters 25-33 : Array<Int> has no field contains]

### ISSUE THREAD

**Issue by 6zjs** [FunkinCrew/Funkin#1756]
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5
 im getting this error
source/Controls.hx:411: characters 25-33 : Array<Int> has no field contains

**Comment by ACrazyTown** [comment]
I've built the source code from scratch just fine, did you mess with the Controls.hx file?

**Comment by 6zjs** [comment]
i think

**Comment by 6zjs** [comment]
nope i did not
