### ISSUE TITLE
Enhancement: Make Daddy Dearest have more than 1 frame for his left pose.

### ISSUE THREAD

**Issue by AbnormalPoof** [FunkinCrew/Funkin#1757]
## What is your suggestion, and why should it be implemented?
The dad only having one frame for left is kinda weird since he just instantly does his left pose, adding 1 or more frames to it can make the pose seamless like the rest of the characters

**Comment by cuckydev** [comment]
this is in the fla actually and in some of the earlier commits. not sure why it wasn't exported?
