### ISSUE TITLE
Bug Report: The Freeplay mode crashes every time!

### ISSUE THREAD

**Issue by Fulbion** [FunkinCrew/Funkin#1759]
Hi When I try to go in Freeplay menu, the game crashes and stops. I used the Git command prompt to download the source code _(to avoid problems)_.
I also tried on HTML5 version _(using Microsoft Edge)_, using the debug and release configuration, this is the same result.

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [X] Windows
- - [ ] Mac
- - [ ] Linux
- [X] [GitHub](https://github.com/ninjamuffin99/Funkin)

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [X] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
`v0.2.7.1`

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
1. Build and run the game
2. Go on Freeplay mode menu
And you will see that the game crashes.

## Please describe your issue. Provide extensive detail and images if possible.
The game becomes black for a few seconds, and the window closes.

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting
```
Uncaught TypeError: Cannot read properties of null (reading 'calls')
    at FreeplayState.changeSelection (Funkin.js:15635)
    at FreeplayState.create (Funkin.js:15534)
    at flixel_FlxGame.switchState (Funkin.js:26820)
    at flixel_FlxGame.update (Funkin.js:26857)
    at flixel_FlxGame.step (Funkin.js:26848)
    at flixel_FlxGame.onEnterFrame (Funkin.js:26782)
    at openfl_display_Stage.__dispatchEvent (Funkin.js:4826)
    at openfl_display_Stage.__dispatch (Funkin.js:5639)
    at openfl_display_Stage.__broadcastEvent (Funkin.js:116869)
    at openfl_display_Stage.__onLimeRender (Funkin.js:117896)
changeSelection @ Funkin.js:15635
create @ Funkin.js:15534
switchState @ Funkin.js:26820
update @ Funkin.js:26857
step @ Funkin.js:26848
onEnterFrame @ Funkin.js:26782
__dispatchEvent @ Funkin.js:4826
__dispatch @ Funkin.js:5639
__broadcastEvent @ Funkin.js:116869
__onLimeRender @ Funkin.js:117896
dispatch @ Funkin.js:96004
handleApplicationEvent @ Funkin.js:4024
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
requestAnimationFrame (asynchrone)
handleApplicationEvent @ Funkin.js:4034
```

**Comment by Vedery** [comment]
Edit: On Windows, there is a message box indicating that the loaded object is a `NullObject` instance.

**Comment by s-zenmode** [comment]
probably because you didnt make a blank apistuff.hx file because im pretty sure thats the main cause :P

**Comment by Vedery** [comment]
I'll close this issue 'cause I just see a closed one that telled me to delete 3 lines from `APIStuff.hx`. Thanks!
