### ISSUE TITLE
Option to replace current Tank Person cutscenes into Text scenes

### ISSUE THREAD

**Issue by Windows1Door2Daniel** [FunkinCrew/Funkin#1767]
An option to disable those scenes that crash a lot on old PCs and turn them into a text scene

The text scenes im talking about is those scenes that appear in **Week 6**

### E
[Drink](https://youtu.be/T28LyXf8MlU)

**Comment by teh404guy** [comment]
bruh if your computer cant handle a webm, maybe upgrade to those 50$ android boxes

**Comment by s-zenmode** [comment]
do they even exist anymore

**Comment by Windows1Door2Daniel** [comment]
Idk
