### ISSUE TITLE
source/TitleState.hx:69: characters 16-28 : Type not found : APIStuff

### ISSUE THREAD

**Issue by freddisgit** [FunkinCrew/Funkin#1768]
I get this error when compiling my game. I never encountered this when using kade engine but it happens here.  Just removing line 69 (nice) fixes the issue. But then going into freeplay crashes the game. Are these issues unrelated? is my repo clone corrupted? Am I just being stupid(probably)? I'd like to know since I don't like how kade engine determines score and want to build my mod from OG source code.

**Comment by AbnormalPoof** [comment]
Delete the line or add the apistuff.hx to source

**Comment by ACrazyTown** [comment]
> I get this error when compiling my game. I never encountered this when using kade engine but it happens here. Just removing line 69 (nice) fixes the issue. But then going into freeplay crashes the game. Are these issues unrelated? is my repo clone corrupted? Am I just being stupid(probably)? I'd like to know since I don't like how kade engine determines score and want to build my mod from OG source code.

![image](https://user-images.githubusercontent.com/47027981/133927059-bff139e0-7db5-4891-8a7e-9931fbe4e257.png)

**Comment by ahazywinter** [comment]
You should've read the README.md. It tells you how to avoid the APIStuff.hx error

**Comment by KitOdin** [comment]
BRUH READ THE README.md FILE YOU ABSOULTE FUCKING MORON!!!!!!!!!!!!!1
