### ISSUE TITLE
Compiling help: Null Object Reference *during* Compilation

### ISSUE THREAD

**Issue by DistilledVinegar** [FunkinCrew/Funkin#1770]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

Hey. I've been trying to compile FNF from source to learn how to make a mod, and I think I'm doing everything correctly except for the very last stages of compilation where I get a "Null Object Reference" in the Terminal before it continues like normal. The game finishes compiling, but when I try to launch the application, I get a completely black screen and just an error reading "Null Object Reference." Keep in mind this code has not been modified whatsoever yet, this is a direct mirror of what's on Github, save for APIStuff.hx. I hope this is a pretty trivial thing to fix, thanks anyone who can help.

Here's the output I get:

C:\Users\Zonk\Downloads\Funkin-master>lime test windows -debug
source/PlayState.hx:150: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -Od(optim-std) -Zi(optim-std) -FdC:\Users\Valerie\Downloads\Funkin-master\export\debug\windows\obj\obj/msvc1964-debug-nc/vc.pdb(optim-std) -Zi(debug) -FdC:\Users\Valerie\Downloads\Funkin-master\export\debug\windows\obj\obj/msvc1964-debug-nc/vc.pdb(debug) -Od(debug) -O2(release) -bigobj -Os(optim-size) -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/lime/utils/AssetCache.cpp  [haxe,release]
 - src/ApplicationMain.cpp
Link: ApplicationMain-debug.exe

Called from polymod.backends.LimeBackend.init (polymod/backends/LimeBackend.hx line 131)
Called from polymod.backends.PolymodAssets.init (polymod/backends/PolymodAssets.hx line 127)
Called from polymod.Polymod.init (polymod/Polymod.hx line 224)
Called from TitleState.create (TitleState.hx line 50)
Called from flixel.FlxGame.switchState (flixel/FlxGame.hx line 637)
Called from flixel.FlxGame.create (flixel/FlxGame.hx line 360)
Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)
Called from openfl.display.DisplayObject.__dispatchEvent (openfl/display/DisplayObject.hx line 1417)
Called from openfl.display.DisplayObject.__dispatchWithCapture (openfl/display/DisplayObject.hx line 1478)
Called from openfl.display.DisplayObjectContainer.addChildAt (openfl/display/DisplayObjectContainer.hx line 266)
Called from openfl.display.DisplayObjectContainer.addChild (openfl/display/DisplayObjectContainer.hx line 155)
Called from Main.setupGame (Main.hx line 70)
Called from Main.init (Main.hx line 49)
Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)
Called from openfl.display.DisplayObject.__dispatchEvent (openfl/display/DisplayObject.hx line 1417)
Called from openfl.display.DisplayObject.__dispatchWithCapture (openfl/display/DisplayObject.hx line 1478)
Called from openfl.display.DisplayObjectContainer.addChildAt (openfl/display/DisplayObjectContainer.hx line 266)
Called from openfl.display.DisplayObjectContainer.addChild (openfl/display/DisplayObjectContainer.hx line 155)
Called from Main.main (Main.hx line 25)
Null Object Reference (<-- this is where i think the problem is, Line 25 of Main)
Called from Main::main Main.hx line 25
Called from openfl.display.DisplayObjectContainer::addChild openfl/display/DisplayObjectContainer.hx line 155
Called from openfl.display.DisplayObjectContainer::addChildAt openfl/display/DisplayObjectContainer.hx line 266
Called from openfl.display.DisplayObject::__dispatchWithCapture openfl/display/DisplayObject.hx line 1478
Called from openfl.display.DisplayObject::__dispatchEvent openfl/display/DisplayObject.hx line 1417
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from Main::init Main.hx line 49
Called from Main::setupGame Main.hx line 70
Called from openfl.display.DisplayObjectContainer::addChild openfl/display/DisplayObjectContainer.hx line 155
Called from openfl.display.DisplayObjectContainer::addChildAt openfl/display/DisplayObjectContainer.hx line 266
Called from openfl.display.DisplayObject::__dispatchWithCapture openfl/display/DisplayObject.hx line 1478
Called from openfl.display.DisplayObject::__dispatchEvent openfl/display/DisplayObject.hx line 1417
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::create flixel/FlxGame.hx line 360
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 637
Called from TitleState::create TitleState.hx line 50`

**Comment by DotWith** [comment]
I looks like you don't have polymod installed because on TitleState.hx line 50 its `Polymod.init`.

**Comment by ACrazyTown** [comment]
> I looks like you don't have polymod installed because on TitleState.hx line 50 its `Polymod.init`.

Na it's cuz polymod broke their shit with a recent update, happens to me too, just comment out the polymod line and you should be good to go

**Comment by DistilledVinegar** [comment]
> > I looks like you don't have polymod installed because on TitleState.hx line 50 its `Polymod.init`.
> 
> Na it's cuz polymod broke their shit with a recent update, happens to me too, just comment out the polymod line and you should be good to go

Unfortunately, I don't think this worked, I just get the same error as last time. Which exact lines am I supposed to comment out?

**Comment by Dobby233Liu** [comment]
Try this https://github.com/KadeDev/Kade-Engine/issues/2291 or install MasterEric's Polymod fork

**Comment by DotWith** [comment]
> Try this https://github.com/KadeDev/Kade-Engine/issues/2291 or install MasterEric's Polymod fork

Ew kadedev :trollface:

**Comment by Dobby233Liu** [comment]
> > Try this [KadeDev#2291](https://github.com/KadeDev/Kade-Engine/issues/2291) or install MasterEric's Polymod fork
> 
> Ew kadedev :trollface:

Why not

**Comment by DotWith** [comment]
> > > Try this [KadeDev#2291](https://github.com/KadeDev/Kade-Engine/issues/2291) or install MasterEric's Polymod fork
> 
> > 
> 
> > Ew kadedev :trollface:
> 
> 
> 
> Why not

I made him angry with tricky mod. He said "Fuck you", he haven't been on discord in days.

**Comment by DotWith** [comment]
Do this to fix the issue, line 50 on titleState

```hx polymod.Polymod.init({modRoot: "mods", dirs: ['introMod']});```

**Comment by CBa08** [comment]
I did both update polymod and I put polymod.Polymod.init({modRoot: "mods", dirs: ['introMod'], framework: OPENFL}); on the 50th line. But it didn't work ._.

**Comment by Cheemsandfriends** [comment]
haha, I didn't update my polymod B) I kept my polymod and I Modified so I dont any deprecated warnings on windows anymore xd
Just on hl that it has some utf8 deprecated stuff only inside hl lol
