### ISSUE TITLE
How about adding custom keybinds

### ISSUE THREAD

**Issue by aDubbzAU** [FunkinCrew/Funkin#1776]
### Discussed in https://github.com/ninjamuffin99/Funkin/discussions/1775

<div type='discussions-op-text'>

<sup>Originally posted by **aDubbzAU** (Myself) September 23, 2021 (moments ago)</sup>
I've seen it in some mods, and to me DFJK is better than WASD (or I guess it's better to say ASWD here) or arrows
Example: in normal FNF I struggle with South on normal, but with the Big Brother Mod (it includes the entire base game 'cause it adds the F**k... difficulty) I set my keybinds to DFJK and managed to complete week 2 on HARD. (BTW, if anyone has tried the Big Brother mod, but deleted it because it crashed on week 1: Dadbattle is broken for whatever reason, the rest works. Also that exact mod doesn't render/ doesn't use sustain notes, only the start note for sustain notes appears (again, that part is for a SPECIFIC mod))
Anyway...
Custom keybinds?</div>

**Comment by ACrazyTown** [comment]
key rebinding has already been added in week 7 iirc

**Comment by aDubbzAU** [comment]
didn't know we had a new download release
sry

**Comment by ACrazyTown** [comment]
> didn't know we had a new download release
> sry

isn't a new download release, but the ng preview of 0.2.8 (week7) has rebindable keys so it's bound to come to PC as soon as they release week 8
