### ISSUE TITLE
Compiling help: It hits me with the source/NGio.hx:24: characters 44-51 : Expected }

### ISSUE THREAD

**Issue by CBa08** [FunkinCrew/Funkin#1778]
Does anyone know how to fix this?
Again, it said
source/NGio.hx:24: characters 44-51 : Expected }

**Comment by DotWith** [comment]
Did you modify the code?

**Comment by ahazywinter** [comment]
You probably messed with some code block and it expects a } because you haven't placed one, or theres a rogue if/switch statement/function/ "{" somewhere
