### ISSUE TITLE
Polymod dependency not found

### ISSUE THREAD

**Issue by Luk3M** [FunkinCrew/Funkin#178]
I'm having trouble building the game on Ubuntu.

I installed Haxe and haxeflixel, i also used `haxelib install` on every library in `Project.xml`, but both faxe and polymod give the same error: `Error: Failed with error: No such Project : polymod`.

I tried to ignore the error and build the project, but I get the error: `Error: Could not find haxelib "polymod", does it need to be installed?`. Commenting the line in Project.xml does not fixes, because Polymod is being used in the TitleScreen. Can someone help me build the game? Should I install polymod in another way?

**Comment by LucasCTN** [comment]
I just got into the Haxe discord and the answer was there. You install polymod using `haxelib git polymod https://github.com/larsiusprime/polymod` if you have git installed. Thanks to singmajesty#9682 .

I'll keep the answer here for reference. Sorry for any inconvenience!
