### ISSUE TITLE
Compiling help: 

### ISSUE THREAD

**Issue by Cookie-Developer** [FunkinCrew/Funkin#1785]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
 0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
using [this](https://gamebanana.com/tuts/13798) game bannana tutorial, in step 1.3, following these steps just crashes when loading it using debug mode.

## Please describe your issue. Provide extensive detail and images if possible.
when i try to make a character crashes. maybe its the week chomp it doesnt understand?
![image](https://user-images.githubusercontent.com/91225097/134589134-d002d000-4667-41f5-8dc1-a728658a9d4b.png)

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting
![image](https://user-images.githubusercontent.com/91225097/134589293-14af8787-e558-45e7-af12-646274b42b9f.png)

**Comment by Cookie-Developer** [comment]
idk if this is the right place to put this..

**Comment by Windows1Door2Daniel** [comment]
Has his own label

**Comment by ahazywinter** [comment]
I don't know whats in Line 545 of Character.hx because it depends on what you've added and whatnot, but I'm guessing its animations - They have to start with some prefixes if you're making your own character, or it crashes afaik.

**Comment by ahazywinter** [comment]
> can you upload a screenshot of the lines specified? (Character.hx, 554)

It's better if they give us the code in text (code-formatter) form. Also it's better if the send the code block it is in because sometimes it might not be an issue with the line only.

**Comment by runkanrenchu** [comment]
> It's better if they give us the code in text (code-formatter) form. Also it's better if the send the code block it is in because sometimes it might not be an issue with the line only.

Eh, code formatters are a bit weird. But whatever suits their needs is fine. I thought ab a screenshot cause of the red marks in VSCode.

> im probably gonna switch to andromeda engine so ill see if i can fix it in andromeda engine and hopefully it will work then

It can't read a property, which might be just as simple as a non-instantiated variable or a mistyped name. But hopefully it'll work. Good luck!

**Comment by redbluexe0** [comment]
compiling help is label is compiling help.
