### ISSUE TITLE
Notes are sometimes hard to distinguish

### ISSUE THREAD

**Issue by ParzivalWolfram** [FunkinCrew/Funkin#180]
Notes can be hard to distinguish from some week's backgrounds. I've personally modified my copy to have different arrows, but it's a very slapped-together fix on my end, so i'd prefer some better _quality_ alternate arrows if possible.

**Comment by devin503** [comment]
there are a few mods over on gamebanana that change the appearance/colours of the arrows, and it's also possible to modify the arrows yourself.
[Club Penguin Dance Contest Arrows](https://gamebanana.com/guis/36287)
[Clearer Arrows](https://gamebanana.com/guis/36289)

**Comment by ParzivalWolfram** [comment]
Yes, but getting this fixed at the source of the issue would be most
beneficial for everyone.
