### ISSUE TITLE
Compile issues on Linux

### ISSUE THREAD

**Issue by ParzivalWolfram** [FunkinCrew/Funkin#181]
Installing all listed dependencies and attempting to compile on Linux results in the following error:
`Error: Could not find haxelib "polymod", does it need to be installed?`
Trying to install given lib fails, as it's unknown. No Google results either.

**Comment by caleb39411** [comment]
Just run `haxelib git polymod https://github.com/larsiusprime/polymod.git`

**Comment by ParzivalWolfram** [comment]
> Just run `haxelib git polymod https://github.com/larsiusprime/polymod.git`

That worked, thanks. Maybe that should be added to the compilation instructions?
