### ISSUE TITLE
Question: compilation error friday night funkin kade engine 

### ISSUE THREAD

**Issue by timoshaplay** [FunkinCrew/Funkin#1814]
Please help me, I can't compile friday night funkin I'm writing haxelib git discord_rpc code https://github.com/Aidan63/linc_discord-rpc the inscription You already have discord_rpc version git installed pops up.
Updating discord_rpc version git ... I think it's okay, I have to wait, I wait for about an hour and nothing happens, what should I do???

**Comment by ACrazyTown** [comment]
this is not the kade engine repo

**Comment by ACrazyTown** [comment]
> this is not the kade engine repo, try making an issue there instead

**Comment by Windows1Door2Daniel** [comment]
![ye](https://user-images.githubusercontent.com/81389527/135216898-02ac4b21-e5c6-4f10-91b8-d82c9205c3e1.jpg)

**Comment by prokube** [comment]
![](https://user-images.githubusercontent.com/81389527/135216898-02ac4b21-e5c6-4f10-91b8-d82c9205c3e1.jpg)

**Comment by PoketrainerMS** [comment]
please open this issue in the [kade engine page](https://github.com/KadeDev/Kade-Engine) instead.

**Comment by AbnormalPoof** [comment]
@ninjamuffin99 fnf mod

**Comment by ThePlank** [comment]
![image](https://user-images.githubusercontent.com/75984453/144256819-876e70da-905c-4c67-a23d-2dbe563ec120.png)
