### ISSUE TITLE
Enhancement: Ability to change player 2 as a song event via chart editor + alt anims for player1 

### ISSUE THREAD

**Issue by AbnormalPoof** [FunkinCrew/Funkin#1817]
## What is your suggestion, and why should it be implemented?
Player 2 change would be extremely beneficial for characters that have more than 1 set of alt animations + it would help with creating stupid meme songs

Alt anims for player 1 will help a lot with playable characters that have alt animations

**Comment by DotWith** [comment]
For week5 there was unused animations(There now broken) but both the mom and dad would sing at the same time

**Comment by Windows1Door2Daniel** [comment]
> For week5 there was unused animations(There now broken) but both the mom and dad would sing at the same time

I think they are actually used

**Comment by DotWith** [comment]
> > For week5 there was unused animations(There now broken) but both the mom and dad would sing at the same time
> 
> I think they are actually used

No

**Comment by Windows1Door2Daniel** [comment]
> > > For week5 there was unused animations(There now broken) but both the mom and dad would sing at the same time
> > 
> > 
> > I think they are actually used
> 
> No

First of all

What animations?

**Comment by DotWith** [comment]
> > > > For week5 there was unused animations(There now broken) but both the mom and dad would sing at the same time
> 
> > > 
> 
> > > 
> 
> > > I think they are actually used
> 
> > 
> 
> > No
> 
> 
> 
> First of all
> 
> 
> 
> What animations?


Did Windows Danial Edition stop working?

**Comment by Windows1Door2Daniel** [comment]
> > > > > For week5 there was unused animations(There now broken) but both the mom and dad would sing at the same time
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I think they are actually used
> > 
> > 
> > > 
> > 
> > 
> > > No
> > 
> > 
> > First of all
> > What animations?
> 
> Did Windows Danial Edition stop working?

yes

**Comment by Windows1Door2Daniel** [comment]
> > > > > For week5 there was unused animations(There now broken) but both the mom and dad would sing at the same time
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I think they are actually used
> > 
> > 
> > > 
> > 
> > 
> > > No
> > 
> > 
> > First of all
> > What animations?
> 
> Did Windows Danial Edition stop working?

Did DotWith stopped working?

**Comment by s-zenmode** [comment]
> #### Please check for duplicates or similar issues before creating this issue.
> ## What is your suggestion, and why should it be implemented?
> Player 2 change would be extremely beneficial for characters that have more than 1 set of alt animations + it would help with creating stupid meme songs
> 
> Alt anims for player 1 will help a lot with playable characters that have alt animations


Just use psych engine, you can add change character events mid-song. Very easy too, you can do it in the chart editor.

**Comment by Cheemsandfriends** [comment]
> 
> 
> > #### Please check for duplicates or similar issues before creating this issue.
> > ## What is your suggestion, and why should it be implemented?
> > Player 2 change would be extremely beneficial for characters that have more than 1 set of alt animations + it would help with creating stupid meme songs
> > Alt anims for player 1 will help a lot with playable characters that have alt animations
> 
> Just use psych engine, you can add change character events mid-song. Very easy too, you can do it in the chart editor.

Shut it this is not PSE This FM

**Comment by s-zenmode** [comment]
> > 
> > 
> > > #### Please check for duplicates or similar issues before creating this issue.
> > > ## What is your suggestion, and why should it be implemented?
> > > Player 2 change would be extremely beneficial for characters that have more than 1 set of alt animations + it would help with creating stupid meme songs
> > > Alt anims for player 1 will help a lot with playable characters that have alt animations
> > 
> > Just use psych engine, you can add change character events mid-song. Very easy too, you can do it in the chart editor.
> 
> Shut it this is not PSE This is FM

I was just recommending the use of another, easy to use, lots of features engine. Is there a problem ??

**Comment by Cheemsandfriends** [comment]
> 
> 
> > > > #### Please check for duplicates or similar issues before creating this issue.
> > > > ## What is your suggestion, and why should it be implemented?
> > > > Player 2 change would be extremely beneficial for characters that have more than 1 set of alt animations + it would help with creating stupid meme songs
> > > > Alt anims for player 1 will help a lot with playable characters that have alt animations
> > > 
> > > 
> > > Just use psych engine, you can add change character events mid-song. Very easy too, you can do it in the chart editor.
> > 
> > 
> > Shut it this is not PSE This is FM
> 
> I was just recommending the use of another, easy to use, lots of features engine. Is there a problem ??

Yes, It's like requesting a pokemon artist digimon art
Doesn't make any sense at all and doesn't help

**Comment by DotWith** [comment]
> > 
> 
> > 
> 
> > > > > #### Please check for duplicates or similar issues before creating this issue.
> 
> > > > > ## What is your suggestion, and why should it be implemented?
> 
> > > > > Player 2 change would be extremely beneficial for characters that have more than 1 set of alt animations + it would help with creating stupid meme songs
> 
> > > > > Alt anims for player 1 will help a lot with playable characters that have alt animations
> 
> > > > 
> 
> > > > 
> 
> > > > Just use psych engine, you can add change character events mid-song. Very easy too, you can do it in the chart editor.
> 
> > > 
> 
> > > 
> 
> > > Shut it this is not PSE This is FM
> 
> > 
> 
> > I was just recommending the use of another, easy to use, lots of features engine. Is there a problem ??
> 
> 
> 
> Yes, It's like requesting a pokemon artist digimon art
> 
> Doesn't make any sense at all and doesn't help

Yes, we care about the main game not Fat Green Angry Frog on Twitter.

**Comment by s-zenmode** [comment]
> > > > > #### Please check for duplicates or similar issues before creating this issue.
> > > > > ## What is your suggestion, and why should it be implemented?
> > > > > Player 2 change would be extremely beneficial for characters that have more than 1 set of alt animations + it would help with creating stupid meme songs
> > > > > Alt anims for player 1 will help a lot with playable characters that have alt animations
> > > > 
> > > > 
> > > > Just use psych engine, you can add change character events mid-song. Very easy too, you can do it in the chart editor.
> > > 
> > > 
> > > Shut it this is not PSE This is FM
> > 
> > 
> > I was just recommending the use of another, easy to use, lots of features engine. Is there a problem ??
> 
> Yes, It's like requesting a pokemon artist digimon art Doesn't make any sense at all and doesn't help

I was recommending someone use another engine **because of ease of access.** It's easier on Psych. Your comparison is kind of... irrelevant?? Ehh, I dunno.

**Comment by DotWith** [comment]
> > > > > > #### Please check for duplicates or similar issues before creating this issue.
> > > > > > ## What is your suggestion, and why should it be implemented?
> > > > > > Player 2 change would be extremely beneficial for characters that have more than 1 set of alt animations + it would help with creating stupid meme songs
> > > > > > Alt anims for player 1 will help a lot with playable characters that have alt animations
> > > > > 
> > > > > 
> > > > > Just use psych engine, you can add change character events mid-song. Very easy too, you can do it in the chart editor.
> > > > 
> > > > 
> > > > Shut it this is not PSE This is FM
> > > 
> > > 
> > > I was just recommending the use of another, easy to use, lots of features engine. Is there a problem ??
> > 
> > 
> > Yes, It's like requesting a pokemon artist digimon art Doesn't make any sense at all and doesn't help
> 
> I was recommending someone use another engine **because of ease of access.** It's easier on Psych. Your comparison is kind of... irrelevant?? Ehh, I dunno.

You have a hank pfp you probably get involved in drama stfu.

**Comment by DotWith** [comment]
> Twitter argument moment

Sorry, I was quite angry at the time.

**Comment by s-zenmode** [comment]
> > Twitter argument moment
> 
> Sorry, I was quite angry at the time.

So is this finally over? 🤝

**Comment by AbnormalPoof** [comment]
whoops idk why

**Comment by Cronvier** [comment]
> > > > > > > #### Please check for duplicates or similar issues before creating this issue.
> > > > > > > ## What is your suggestion, and why should it be implemented?
> > > > > > > Player 2 change would be extremely beneficial for characters that have more than 1 set of alt animations + it would help with creating stupid meme songs
> > > > > > > Alt anims for player 1 will help a lot with playable characters that have alt animations
> > > > > > 
> > > > > > 
> > > > > > Just use psych engine, you can add change character events mid-song. Very easy too, you can do it in the chart editor.
> > > > > 
> > > > > 
> > > > > Shut it this is not PSE This is FM
> > > > 
> > > > 
> > > > I was just recommending the use of another, easy to use, lots of features engine. Is there a problem ??
> > > 
> > > 
> > > Yes, It's like requesting a pokemon artist digimon art Doesn't make any sense at all and doesn't help
> > 
> > 
> > I was recommending someone use another engine **because of ease of access.** It's easier on Psych. Your comparison is kind of... irrelevant?? Ehh, I dunno.
> 
> You have a hank pfp you probably get involved in drama stfu.

im offended
