### ISSUE TITLE
Bug Report: Note splashes sometimes freeze in place

### ISSUE THREAD

**Issue by AbnormalPoof** [FunkinCrew/Funkin#1818]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux
- [x] Running the HTML5 version internally

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.2.8

## Please describe your issue. Provide extensive detail and images if possible.
Sometimes, when playing a song with lots of arrows, the note splashes freeze in place (namely the green one)
It appears to happen with songs that have a high BPM

**Comment by Cheemsandfriends** [comment]
Running the HTML5 internally?
So it isn't a `vanilla` coding stuff?
I don't understand

**Comment by AbnormalPoof** [comment]
it is vanilla lol
basically running html5 ver locally via python (not sending dl because it goes against ninjamuffin's wishes)

**Comment by AbnormalPoof** [comment]
You prob decompiled the week 7 js file

**Comment by DotWith** [comment]
> You prob decompiled the week 7 js file

I've decompiled the mainMenu, videoPlayer, noteSpashes, noteColors, Modding, HealthIcons, PicoSpeaker, DialogueBox, downscroll, week7, some cutscene code, smooth lerping, loadingState Bar, PlayState, and your mom lol weed.
![image](https://user-images.githubusercontent.com/52358442/137562971-aa160004-a104-49c4-bfab-cde94a86095f.png)

**Comment by DotWith** [comment]
> ~~mind sending the video code-~~

Hol up

**Comment by DotWith** [comment]
> ~~mind sending the video code-~~

Only works on web [oh](https://gist.github.com/DotWith/2685fcb68aa8eb3e72309c4ab781b139) if you need help ask

**Comment by ThePlank** [comment]
> > ~mind sending the video code-~
> 
> Only works on web [oh](https://gist.github.com/DotWith/2685fcb68aa8eb3e72309c4ab781b139) if you need help ask

so thats why week 7 was delayed

**Comment by justamole** [comment]
> > ~mind sending the video code-~
> 
> Only works on web [oh](https://gist.github.com/DotWith/2685fcb68aa8eb3e72309c4ab781b139) if you need help ask

how did you even get week 7 code

**Comment by ThePlank** [comment]
> > > ~mind sending the video code-~
> > 
> > 
> > Only works on web [oh](https://gist.github.com/DotWith/2685fcb68aa8eb3e72309c4ab781b139) if you need help ask
> 
> how did you even get week 7 code

http://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/Funkin.js

do not share too much of the code that you decompile, because **he** will wake up

**Comment by DotWith** [comment]
> > > > ~mind sending the video code-~
> 
> > > 
> 
> > > 
> 
> > > Only works on web [oh](https://gist.github.com/DotWith/2685fcb68aa8eb3e72309c4ab781b139) if you need help ask
> 
> > 
> 
> > how did you even get week 7 code
> 
> 
> 
> http://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/Funkin.js
> 
> 
> 
> do not share too much of the code that you decompile, because **he** will wake up

I shared too much code already

**Comment by ThePlank** [comment]
> > > > > ~mind sending the video code-~

oh right

**Comment by ThePlank** [comment]
> > > > > ~mind sending the video code-~
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Only works on web [oh](https://gist.github.com/DotWith/2685fcb68aa8eb3e72309c4ab781b139) if you need help ask
> > 
> > 
> > > 
> > 
> > 
> > > how did you even get week 7 code
> > 
> > 
> > http://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/Funkin.js
> > do not share too much of the code that you decompile, because **he** will wake up
> 
> I shared too much code already

oh right
