### ISSUE TITLE
Debug mode: ChangeBPM problems

### ISSUE THREAD

**Issue by ILuvGemz** [FunkinCrew/Funkin#183]
I have discovered a bug with the ChangeBPM system. 

I recently found out that when I was charting a 240 BPM song and tried changing the BPM to 180 on section 72, my notes ended up being placed in 96000 instead of 72000.

From what I have gathered, the notes placement is in milliseconds, with this equation:

([Section number * 240 / Normal BPM + (240 / Normal BPM * y / 16)] * 1000) milliseconds, where y is 0 <= x <= 15

y is equal to the position of the note in steps, with the first being 0 and the last being 15.

Therefore, I found out when I use ChangeBPM, it overrides the normal BPM variable of the song, thus making me chart later or sooner than where I expected it to be.

I hope you are able to understand my problem and found a way to fix it!

-Zenokwei a.k.a ILuvGemz

**Comment by ninjamuffin99** [comment]
changing BPM is not supported yet.

**Comment by ILuvGemz** [comment]
Ummm... Okay. I'll wait.
