### ISSUE TITLE
Enhancement: Fix DiscordRpc compile issue

### ISSUE THREAD

**Issue by AndrewIdot** [FunkinCrew/Funkin#1830]
## What is your suggestion, and why should it be implemented?

My suggestion is adding this line next to the DiscordRpc line in Project.xml:
`	<haxelib name="discord_rpc.DiscordRpc" if="desktop"/>`

As well as adding this command in the compile tutorial:
`haxelib git discord_rpc.DiscordRpc https://github.com/Aidan63/linc_discord-rpc`

Some people had this bug (including me) and I found a good solution.
Basically, it fixes the below issue some people had with compilation:
`source/Discord.hx:4: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:13: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:23: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:28: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:33: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:38: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:74: characters 3-13 : Type not found : DiscordRpc`

**Comment by Jonnycatmeow** [comment]
ok. where you have the problem on there right do #if desktop  on there and at the bottom put #end
