### ISSUE TITLE
Compiling help: Null Object Reference error whenever game boots

### ISSUE THREAD

**Issue by WarpOverload** [FunkinCrew/Funkin#1832]
Hello, I am currently trying to compile Friday Night Funkin but I get this error whenever I boot up FNF:
![image](https://user-images.githubusercontent.com/92233545/136675111-ffddc8e2-7366-4a46-b70e-86eb38dab300.png)
Here is the compile log I copied from PowerShell:
[compilelog.txt](https://github.com/ninjamuffin99/Funkin/files/7316515/compilelog.txt)
If anyone can help me solve this, please comment!

**Comment by DotWith** [comment]
Duplicate of #1770

**Comment by WarpOverload** [comment]
I got everything fixed, turns out it was a polymod error, if you have the same error use` haxelib git polymod https://github.com/MasterEric/polymod` until Polymod PR #39 is merged. I am not closing this issue.
