### ISSUE TITLE
help

### ISSUE THREAD

**Issue by nintendoAsh** [FunkinCrew/Funkin#1839]
so I am making an FNF mod and I get this error 

PS C:\Users\user\Desktop\fnf john\john mod\Funkin-master> lime test windows
source/PlayState.hx:150: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\user\Desktop\fnf john\john mod\Funkin-master\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/sys/io/_Process/Stdout.cpp
 - src/flixel/input/actions/_FlxSteamController/FlxSteamControllerMetadata.cpp
 - src/openfl/display/_internal/Context3DElementType.cpp
Error: Context3DElementType.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

PS C:\Users\user\Desktop\fnf john\john mod\Funkin-master>

plz help

**Comment by idragons962** [comment]
it is because you forgot to download the visual studio commutity 2019 installer
