### ISSUE TITLE
Bug Report: Note Splash Bug

### ISSUE THREAD

**Issue by gamerbross** [FunkinCrew/Funkin#1846]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
- 0.2.8

## Please describe your issue. Provide extensive detail and images if possible.

when you enter a song, a note splash appears in the left corner

![image](https://user-images.githubusercontent.com/55158797/138432258-0556e46e-c7b8-4356-8b28-61694982305a.png)

how to fix this:

change this:
``` haxe
grpNoteSplashes = new FlxTypedGroup<NoteSplash>();
var noteSplash = new NoteSplash(100, 100, 0);
noteSplash.alpha = 0.6;
grpNoteSplashes.add(noteSplash);
```

to this:
``` haxe
grpNoteSplashes = new FlxTypedGroup<NoteSplash>();
var noteSplash = new NoteSplash(100, 100, 0);
noteSplash.alpha = 0;
grpNoteSplashes.add(noteSplash);
new FlxTimer().start(1.5, function(tmr:FlxTimer)
{
	noteSplash.alpha = .6;
});
```
(I don't think your code is the way it is, since I tried to read the code from the funkin.js, and its obfuscated)

**Comment by FrancescoPipino** [comment]
how i add splash note to fnf?
I create a NoteSplash.hx??
Please help me lol
