### ISSUE TITLE
Compiling help: [BRIEF DESCRIPTION / ERROR MESSAGE OUTPUT]

### ISSUE THREAD

**Issue by ZEkA10000** [FunkinCrew/Funkin#1851]
- [#] Windows

I don't understand what I should do for compiling engine.

P.S. Why you just don't have a compiled version of engine instead manual with thousands steps where you install so much useless software?

**Comment by AbnormalPoof** [comment]
> Without link on the engine - in't solved.

...
https://ninja-muffin24.itch.io/funkin

https://www.newgrounds.com/portal/view/770371
