### ISSUE TITLE
Support windows 11?

### ISSUE THREAD

**Issue by zwl1619** [FunkinCrew/Funkin#1860]
Support windows 11?

**Comment by DotWith** [comment]
My stats lag windows11
![image](https://user-images.githubusercontent.com/52358442/139523477-99d7b3fb-c051-4e0e-9f3f-2d90b67b2914.png)

**Comment by ThePlank** [comment]
how do you guys have windows 11?

**Comment by DotWith** [comment]
> how do you guys have windows 11?
> 
> edit: nvm just polish peopel dont have upgrade to windows 11
> 
> editoer edit: for some reason everything is in polish so i guess they just hidin the good stuff?

Get download [here ](https://www.microsoft.com/en-us/software-download/windows11?ranMID=24542&ranEAID=nOD/rLJHOac&ranSiteID=nOD_rLJHOac-b0y7Yfyf1AuFszdodqPXFQ&epi=nOD_rLJHOac-b0y7Yfyf1AuFszdodqPXFQ&irgwc=1&irclickid=_wvzr0kx1twkf61xbfovyfej9y32xrcsjpmqcfvag00) they broke it in updates & security.

**Comment by ThePlank** [comment]
> Get download [here ](https://www.microsoft.com/en-us/software-download/windows11?ranMID=24542&ranEAID=nOD/rLJHOac&ranSiteID=nOD_rLJHOac-b0y7Yfyf1AuFszdodqPXFQ&epi=nOD_rLJHOac-b0y7Yfyf1AuFszdodqPXFQ&irgwc=1&irclickid=_wvzr0kx1twkf61xbfovyfej9y32xrcsjpmqcfvag00) they broke it in updates & security.

![image](https://user-images.githubusercontent.com/75984453/140164079-6245353b-a7e2-4ec0-8ade-bdc111cc4716.png)
