### ISSUE TITLE
Version of the game (? I need help)

### ISSUE THREAD

**Issue by FroggieTransBoi** [FunkinCrew/Funkin#1861]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

## What is your question?
So I recently got FNF and I had downloaded it from ninjamuffin, when I go to launch it, it says, and I quote "HEY! You're running an outdated version of the game! Current version is v0.2.7.1 while the most recent version is v.0.2.7.1! Press Space to go to itch.io, or ESCAPE to ignore this!" Now im not a techy person and im not that smart when it comes to programing and computers and what not, but im PRETTY SURE I have the most recent version of the game, so why would it be saying this?

**Comment by LrgeAlvaro8882** [comment]
Yeah, it's just broken cuz technically the Week 7 came out but it didn't came out for desktop so it's broken. If you're trying to delete it, just go to TitleState.hx and delete:
// Check if version is outdated

var version:String = "v" + Application.current.meta.get('version');

if (version.trim() != NGio.GAME_VER_NUMS.trim() && !OutdatedSubState.leftState)
{
	FlxG.switchState(new OutdatedSubState());
					trace('OLD VERSION!');
					trace('old ver');
	trace(version.trim());
	trace('cur ver');
	trace(NGio.GAME_VER_NUMS.trim());
}
else
{
	FlxG.switchState(new MainMenuState());
}

And just leave:
	FlxG.switchState(new MainMenuState());
	
That's an easy fix.

**Comment by Cheemsandfriends** [comment]
> 
> #### Please check for duplicates or similar issues before asking your question.
> ## What is your question?
> 
> So I recently got FNF and I had downloaded it from ninjamuffin, when I go to launch it, it says, and I quote "HEY! You're running an outdated version of the game! Current version is v0.2.7.1 while the most recent version is v.0.2.7.1! Press Space to go to itch.io, or ESCAPE to ignore this!" Now im not a techy person and im not that smart when it comes to programing and computers and what not, but im PRETTY SURE I have the most recent version of the game, so why would it be saying this?

This is basically cos there's no NG project linked to the thing, It just looks for the Application version.
Just remove the version checker or if you wanna be some weird dude, make your own version checker idk
