### ISSUE TITLE
What are the steps of adding a character?

### ISSUE THREAD

**Issue by zwl1619** [FunkinCrew/Funkin#1863]
What are the steps of adding a character?

**Comment by ahazywinter** [comment]
There are so many tutorials for this

**Comment by DotWith** [comment]
> What are the steps of adding a character?

I don't prefer using vanilla to add a character it's harder.

**Comment by AshoXD** [comment]
BBPanzu made a tutorial, you could give it a try

**Comment by DotWith** [comment]
> BBPanzu made a tutorial, you could give it a try

The mistook man
