### ISSUE TITLE
Bug Report: Linux version doesn't like Tiling Window Managers

### ISSUE THREAD

**Issue by ioletsgo** [FunkinCrew/Funkin#1864]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [x] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
Most recent version, this is an issue on all versions.

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
If you use a Window Manager like i3, Friday Night Funkin will automatically resolve the aspect ratio and screen resolution to the window on bootup, attempting to fix this will lead to issues with layering and displaying the full resolution.
## Please describe your issue. Provide extensive detail and images if possible.
Having an option to set the resolution/aspect ratio might fix this issue on linux setups, as the auto-scaling is unreliable on certain Window Managers.

**Comment by Playertrip777** [comment]
I think you can change it by going to Main.hx, then going to "var zoom" variable and change -1 to 1.

**Comment by Skunkynator** [comment]
I have been having this same issue on i3, and have no clue how to circumvent it, other then using the windows version through wine, and having a different window set to full-screen while launching the game, until music can be heard.

having in-game settings for aspect ratio or resolution would definitely make it way easier to manage,
