### ISSUE TITLE
Question: umm.. why don't you put week 7 sauce..? maybe?

### ISSUE THREAD

**Issue by NikRetaNCAM** [FunkinCrew/Funkin#1865]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

## What is your question?
sorry to ask that, im just interesting

**Comment by AbnormalPoof** [comment]
Week 7 source will be out along with week 8’s

**Comment by DotWith** [comment]
Never

**Comment by Cheemsandfriends** [comment]
Gonna

**Comment by CubixL** [comment]
Give

**Comment by pizzapastapest** [comment]
You

**Comment by pizzapastapest** [comment]
Up

**Comment by Im-listening** [comment]
Never

**Comment by Im-listening** [comment]
Gonna

**Comment by AshoXD** [comment]
Let

**Comment by CubixL** [comment]
You

**Comment by Igorgames3000** [comment]
Down

**Comment by ThePlank** [comment]
Never

**Comment by Steviegt6** [comment]
This really isn't the place.

**Comment by FuseIsHere813** [comment]
> This really isn't the place.

It feels like spam but with multiple people.

Or it could be "Rickroll, but github users sing it."

**Comment by Cheemsandfriends** [comment]
> 
> 
> > This really isn't the place.
> 
> It feels like spam but with multiple people.
> 
> Or it could be "Rickroll, but github users sing it."

Yeah, I feel the urge to put `Gonna` on `Never` but I never thought that many ppl would join honestly XD

**Comment by Windows1Door2Daniel** [comment]
> Never

Gonna

**Comment by DotWith** [comment]
Run

**Comment by polybiusproxy** [comment]
Around

**Comment by Cheemsandfriends** [comment]
And

**Comment by AbnormalPoof** [comment]
Chain broken

**Comment by Sanscode1937** [comment]
Desert you.

**Comment by Igorgames3000** [comment]
Never

**Comment by Steviegt6** [comment]
Sometimes I forget how young FNF's fanbase is.

**Comment by Cheemsandfriends** [comment]
> 
> 
> Sometimes I forget how young FNF's fanbase is.

Shut up XD

**Comment by s-zenmode** [comment]
> Sometimes I forget how young FNF's fanbase is.

not all but sure that definitely is true

**Comment by KitOdin** [comment]
Gonna

**Comment by FuseIsHere813** [comment]
Children™

**Comment by Windows1Door2Daniel** [comment]
Hurt you

**Comment by Steviegt6** [comment]
> > Sometimes I forget how young FNF's fanbase is.
> 
> not all but sure that definitely is true

My bad, meant to specify how young the *average* member of the community is. There'll always be outliers.

**Comment by prokube** [comment]
> Chain broken

no care lol

**Comment by Windows1Door2Daniel** [comment]
> > > Sometimes I forget how young FNF's fanbase is.
> > 
> > 
> > not all but sure that definitely is true
> 
> My bad, meant to specify how young the _average_ member of the community is. There'll always be outliers.

Agree

**Comment by HiroOfc** [comment]
> Gonna

u know the rules, and so do ninjamuffin99...
**say goodbye?**

**Comment by MrClogsworthYT** [comment]
We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching but you're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give, never gonna give
(Give you up)
We've known each other for so long
Your heart's been aching but you're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye

**Comment by Steviegt6** [comment]
They had already shut up for two weeks.

**Comment by HiroMizuki** [comment]
lol

**Comment by MrClogsworthYT** [comment]
> They had already shut up for two weeks.

idc

**Comment by AshoXD** [comment]
> Sometimes I forget how young FNF's fanbase is.

youre just mad you got rickrolled

**Comment by Steviegt6** [comment]
> > Sometimes I forget how young FNF's fanbase is.
> 
> youre just mad you got rickrolled

Jokes on you, I just didn't read everything. Can't get rick-rolled if I refuse to look at it.

**Comment by Cheemsandfriends** [comment]
> > > Sometimes I forget how young FNF's fanbase is.
> > 
> > 
> > youre just mad you got rickrolled
> 
> Jokes on you, I just didn't read everything. Can't get rick-rolled if I refuse to look at it.

But, you looked some of it so it counts as a rickroll, like it or not

**Comment by themysticsavages** [comment]
@NicklGames To answer your question, ninjamuffin99 is planning to keep it on Newgrounds and some other few sites for quite some time. Maybe the source will be uploaded when Week 8 comes out. In the meantime, you can use the HTML5 source.

<sub>by the way did you mean the binary source or the html5 source</sub>

**Comment by themysticsavages** [comment]
@Windows1Door2Daniel @KitOdin @ThePlank @Cheemsandfriends you guys messed up the rickroll when you said desert you too early ._. also go do it somewhere else

**Comment by HiroMizuki** [comment]
let's just wait to ninjamuffin close this shit guys

**Comment by MrClogsworthYT** [comment]
yee yee

> let's just wait to ninjamuffin close this shit guys

**Comment by KitOdin** [comment]
dont ping me, or i cut your spleen in half.

**Comment by MrClogsworthYT** [comment]
> dont ping me, or i cut your spleen in half.

@KitOdin 
I dare you

**Comment by KitOdin** [comment]
thats it.
*grabs a giant axe*
be prepared

**Comment by themysticsavages** [comment]
I am slowing losing all my brain cells in this discussion and from now on, I refuse to both be a part of this discussion or ever look and message either regarding me or ANYONE else in this discussion. You all can kill each other, as shown by @KitOdin 's message.

**Comment by AbnormalPoof** [comment]
ass drinking

**Comment by MrClogsworthYT** [comment]
> thats it. _grabs a giant axe_ be prepared

a @KitOdin  continue I ain't scared

**Comment by KitOdin** [comment]
run.

**Comment by MrClogsworthYT** [comment]
> run.

no

**Comment by windows10win7posreadywoeskio** [comment]
what the FUCK

**Comment by windows10win7posreadywoeskio** [comment]
wtf

**Comment by windows10win7posreadywoeskio** [comment]
lol

**Comment by NokioPyro** [comment]
Hey kids!
Have you heard of the newgrounds video "Friday night splunkin"?
Yes very good
very sfw
very funny
monkey
dont fucking cancel me kids or i'll run into your house and rip out your intestines and cook it like a saussage on a barbeque lmao

**Comment by s-zenmode** [comment]
> Hey kids! Have you heard of the newgrounds video "Friday night splunkin"? Yes very good very sfw very funny monkey dont fucking cancel me kids or i'll run into your house and rip out your intestines and cook it like a saussage on a barbeque lmao

Aw hell nah aint no way that video gonna see the light of day ever again

**Comment by MrClogsworthYT** [comment]
> > Hey kids! Have you heard of the newgrounds video "Friday night splunkin"? Yes very good very sfw very funny monkey dont fucking cancel me kids or i'll run into your house and rip out your intestines and cook it like a saussage on a barbeque lmao
> 
> Aw hell nah aint no way that video gonna see the light of day ever again

ikr

**Comment by MrClogsworthYT** [comment]
> Hey kids! Have you heard of the newgrounds video "Friday night splunkin"? Yes very good very sfw very funny monkey dont fucking cancel me kids or i'll run into your house and rip out your intestines and cook it like a saussage on a barbeque lmao

you made me traumatized for life

**Comment by Cheemsandfriends** [comment]
> Hey kids! Have you heard of the newgrounds video "Friday night splunkin"? Yes very good very sfw very funny monkey dont fucking cancel me kids or i'll run into your house and rip out your intestines and cook it like a saussage on a barbeque lmao

Uhm,
Please don't

**Comment by NokioPyro** [comment]
> > Hey kids! Have you heard of the newgrounds video "Friday night splunkin"? Yes very good very sfw very funny monkey dont fucking cancel me kids or i'll run into your house and rip out your intestines and cook it like a saussage on a barbeque lmao
> 
> Aw hell nah aint no way that video gonna see the light of day ever again

Ah thank god i fucking hate it.

**Comment by MrClogsworthYT** [comment]
> > > Hey kids! Have you heard of the newgrounds video "Friday night splunkin"? Yes very good very sfw very funny monkey dont fucking cancel me kids or i'll run into your house and rip out your intestines and cook it like a saussage on a barbeque lmao
> > 
> > 
> > you made me traumatized for life
> 
> dont tell me you fucking watched it

2 seconds of it curiosty got me

**Comment by NokioPyro** [comment]
oh my god

**Comment by Windows1Door2Daniel** [comment]
Jeez

**Comment by XavierCodes99** [comment]
The FitnessGram PACER Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The test is used to measure a student's aerobic capacity as part of the FitnessGram assessment. Students run back and forth as many times as they can, each lap signaled by a beep sound.

**Comment by Windows1Door2Daniel** [comment]
> The FitnessGram PACER Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The test is used to measure a student's aerobic capacity as part of the FitnessGram assessment. Students run back and forth as many times as they can, each lap signaled by a beep sound.

[What](https://youtu.be/XAk5rV-hHV4?t=11)

**Comment by XavierCodes99** [comment]
[How do i do this](www.youtube.com/watch?v=sck2H8r-Zag&list=PLT1RSs9syxP4pIqedoB9ZcWad9KWNj9ss&index=15&t=21s)

**Comment by XavierCodes99** [comment]
[Turi ip ip ip](https://youtu.be/FToT_a0ZIaE)

**Comment by Paidyy** [comment]
> How do I remove the extra zeros in the combo thingy?
> 
> (Like forever & andromeda engine)
https://github.com/ninjamuffin99/Funkin/discussions/new

**Comment by NokioPyro** [comment]
Hey remember when you wafched newgrounds porn
That was funny

**Comment by Cheemsandfriends** [comment]
> Hey remember when you wafched newgrounds porn That was funny

Who said they aren't to this day?? 😈

**Comment by Windows1Door2Daniel** [comment]
> > Hey remember when you wafched newgrounds porn That was funny
> 
> Who said they aren't to this day?? 😈

[What](https://youtu.be/XAk5rV-hHV4?t=11)

**Comment by KitOdin** [comment]
what the fuck did i just find aaaaaaa-
