### ISSUE TITLE
So i used the command "lime test windows" and it seem worked.

### ISSUE THREAD

**Issue by BasmaRuto** [FunkinCrew/Funkin#1870]
So i used the command "lime test windows" and it seem worked.
I waited until the end and, got to the end, it didn't work and it put me this :

Error: serialization.cpp C:\HaxeToolkit\haxe\lib\discord_rpc\git\lib\discord-rpc\src\serialization.h(13): fatal error C1083: Impossible d'ouvrir le fichier include : 'rapidjson/document.h' : No such file or directory   - C:/HaxeToolkit/haxe/lib/discord_rpc/git/lib/discord-rpc/src/rpc_connection.cpp Error: discord-rpc.cpp C:\HaxeToolkit\haxe\lib\discord_rpc\git\lib\discord-rpc\src\serialization.h(13): fatal error C1083: Impossible d'ouvrir le fichier include : 'rapidjson/document.h' : No such file or directory

And i don't know why, i swear when I manage to solve a problem, another one appears...
Any help would be appreciated !

_Originally posted by @BasmaRuto in https://github.com/ninjamuffin99/Funkin/discussions/1868_

**Comment by pafuent** [comment]
I'm not 100% sure but that file should be in C:\HaxeToolkit\haxe\lib\discord_rpc\git\lib\rapidjson\include\rapidjson\document.h, please check if you have it.
The rapidjson library is handled as Git submodule in https://github.com/Aidan63/linc_discord-rpc, so if that file is not in the path mentioned above, you should check/file an issue on https://github.com/Aidan63/linc_discord-rpc

**Comment by Cheemsandfriends** [comment]
sometimes Git Downloads on haxelib are kinda broken,
I suggest to remove the discord rpc and install it again cos It isn't updated the discord rpc for a goddamn ass long time

**Comment by redbluexe0** [comment]
C:\HaxeToolkit is the Haxe 4.1.5 and i dont think discord_rpc and all the funkin things stay in there. make a new folder then install all of those funkin things.

this might work but im not 100% sure it will. but its ok to test it
