### ISSUE TITLE
Question: Why does `bf.json`  have "0" but  `dad.json` not have "0"?

### ISSUE THREAD

**Issue by zwl1619** [FunkinCrew/Funkin#1871]
`FNF-PsychEngine-main\export\release\windows\bin\assets\characters\bf.json`

![Snipaste_2021-11-05_20-42-41](https://user-images.githubusercontent.com/13177997/140511933-bd25dfe5-7ce8-4c41-9575-012d8fcd9c7c.png)

`FNF-PsychEngine-main\export\release\windows\bin\assets\characters\dad.json`

![Snipaste_2021-11-05_20-36-27](https://user-images.githubusercontent.com/13177997/140511935-15a3c948-b425-417c-827f-6d10ff59a7e2.png)

Why does `bf.json`  have "0" but  `dad.json` not have "0"?

**Comment by LrgeAlvaro8882** [comment]
Fisrtly, you gotta post that inside the Psych Engine repository. Secondly, it's the engine stuff. Don't worry about it.

**Comment by KitOdin** [comment]
bf miss animations and sing animations share the exact same name(albeit miss animation have a "MISS" prefix added to them) so if there was no 0, the game would play the miss animation after the normal sing animation when you hit a note.
