### ISSUE TITLE
Kade engine dont wont compil

### ISSUE THREAD

**Issue by GregBruh** [FunkinCrew/Funkin#1873]
After the compilation Kade engine finishes . FNF starts, black screen and immediately crashes. Without any error message. And during compilation, the following text appears:

Compiling group: hxcpp_ssl
cl.exe -IC:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/include -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdD:\Games\Kade engine bruh\Kade-Engine-1.3-KE\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/rsa.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ssl_ticket.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/cmac.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/src/hx/libs/ssl/SSL.cpp
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/md_wrap.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/sha1.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/aesni.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ecp.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/bignum.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/version.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/base64.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/pk.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/pkcs11.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/pkcs5.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/x509_crl.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/pkwrite.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/asn1parse.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/net_sockets.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/x509_create.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ssl_cache.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/blowfish.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/camellia.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ssl_tls.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ecjpake.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/xtea.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/gcm.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/x509_csr.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ssl_cli.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ecdsa.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/timing.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/cipher.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/x509write_crt.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/pk_wrap.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/dhm.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ecp_curves.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/entropy.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/havege.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/platform.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ssl_cookie.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/version_features.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ecdh.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/error.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/pem.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/sha512.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/aes.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/hmac_drbg.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/certs.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/cipher_wrap.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/x509_crt.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ccm.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/des.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/oid.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/pkcs12.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/entropy_poll.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/x509.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/sha256.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/debug.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/rsa_internal.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ctr_drbg.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ripemd160.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/md5.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/padlock.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ssl_ciphersuites.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/memory_buffer_alloc.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/pkparse.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/threading.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/x509write_csr.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/ssl_srv.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/md.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/asn1write.c
 - C:/HaxeToolkit/haxe/lib/hxcpp/4,1,15/project/thirdparty/mbedtls-2.9.0/library/arc4.c
Link: ApplicationMain.exe

And there is a lot of such text, with a change in this file path.
(Maybe this text doesn't affect anything, but it didn't exist before, or was it? And I'm using Kade Engine 1.3)

**Comment by DotWith** [comment]
This is not Kade Engine

**Comment by GregBruh** [comment]
What

**Comment by DotWith** [comment]
This is Funkin not Kade Engine

**Comment by Cheemsandfriends** [comment]
Now the real question is:
Can you pls ask it on:
The FNF Modding Discord server or ask it on the KE repo?
It's so simple and yet so complicated for ppl to ask it in the correct repo

**Comment by GregBruh** [comment]
Thanks of course, but this is not the answer to my question.

**Comment by DotWith** [comment]
> Thanks of course, but this is not the answer to my question.

I have lost multiple brain cells

**Comment by Cheemsandfriends** [comment]
> 
> 
> Thanks of course, but this is not the answer to my question.

Well, It's just compilation shit, don't worry I guess

**Comment by s-zenmode** [comment]
Look. This is Ninjamuffin99/Funkin. If you have a problem with KADE ENGINE, then go to the KADE ENGINE REPOSITORY.

**Comment by Windows1Door2Daniel** [comment]
Hey there, would you like to sign my petition?

**Comment by DotWith** [comment]
> Hey there, would you like to sign my petition?

No

**Comment by ThePlank** [comment]
:feelsgood:

**Comment by Windows1Door2Daniel** [comment]
> > Hey there, would you like to sign my petition?
> 
> No

You gotta be f*cking kidding me

Look just sign this st*pid pettition, i got stuff to do

**Comment by Spongeyboi** [comment]
KadeDev/KadeEngine is Kade Engine -_-
This is the vanilla fnf, the og. the sexy one. Open an issue in Kade Engine instead of here.

**Comment by KitOdin** [comment]
> > > Hey there, would you like to sign my petition?
> > 
> > 
> > No
> 
> You gotta be f*cking kidding me
> 
> Look just sign this st*pid pettition, i got stuff to do

ok.

**Comment by IndigoDarkw0lf** [comment]
> > > Hey there, would you like to sign my petition?
> > 
> > 
> > No
> 
> You gotta be f*cking kidding me
> 
> Look just sign this st*pid pettition, i got stuff to do

did you... just censor "stupid"?

**Comment by Windows1Door2Daniel** [comment]
> > > > Hey there, would you like to sign my petition?
> > > 
> > > 
> > > No
> > 
> > 
> > You gotta be f*cking kidding me
> > Look just sign this st*pid pettition, i got stuff to do
> 
> did you... just censor "stupid"?

I got banned before when i said that

i deleted that account and made this account

**Comment by ThePlank** [comment]
> > > > > Hey there, would you like to sign my petition?
> > > > 
> > > > 
> > > > No
> > > 
> > > 
> > > You gotta be f_cking kidding me
> > > Look just sign this st_pid pettition, i got stuff to do
> > 
> > 
> > did you... just censor "stupid"?
> 
> I got banned before when i said that
> 
> i deleted that account and made this account

stpid hitgub

**Comment by Reycko** [comment]
This is f*c*ing `ninjamuffin99/Funkin` AKA the vanilla / unmodded one.
Go to the [Kade Engine repository](https://github.com/KadeDev/Kade-Engine) and ask there.

**Comment by Jonnycatmeow** [comment]
bruh if it says LINK:  application.exe that means the building is finished

**Comment by Gavman69** [comment]
stop using kade engine

**Comment by Sylveondev** [comment]
kade = chad

**Comment by Cheemsandfriends** [comment]
> kade = chad

Nah

**Comment by Sylveondev** [comment]
I still use 1.5.4 😎

**Comment by Sylveondev** [comment]
Finally lol

**Comment by TechnikTil** [comment]
peak issue

**Comment by Reycko** [comment]
Lmao why'd you necro this

**Comment by Hundrec** [comment]
> Lmao why'd you necro this

Probably because of https://github.com/FunkinCrew/Funkin/issues/3946
