### ISSUE TITLE
Compiling help: [This thing always haunts me in my dreams... / C:\Users\K1\Downloads\Funkin\export\debug\windows\obj>setlocal enabledelayedexpansion Warning: Could not find Visual Studio 2017 VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC]

### ISSUE THREAD

**Issue by Filename99** [FunkinCrew/Funkin#1884]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

I'm so tired of this abuse... Okay, let me explain. When I try to compile FNF or FNF mod engines, I always get this:
![image](https://user-images.githubusercontent.com/71535927/142726709-53bcd8a2-f37c-4075-9724-57c62690d446.png)
I don't know what to do. I installed everything that said "MSVC" and "Windows SDK" but I still get this error. Can somebody help me out?

**Comment by redbluexe0** [comment]
@Filename99 install visual studio 2019 with MSBuild and Windows sdk [version on readme]. then try again.

**Comment by Filename99** [comment]
@redbluexe0 Can you please rewatch the issue? I said "I installed everything that said "MSVC" and "Windows SDK"." That means I downloaded Visual Studio 2019 Community, downloaded MSVC build tools and Windows SDK. But I still get this error. I tried downloading it several times with the pack of individual components that was in README.md but still no results.

**Comment by redbluexe0** [comment]
> @redbluexe0 Can you please rewatch the issue? I said "I installed everything that said "MSVC" and "Windows SDK"." That means I downloaded Visual Studio 2019 Community, downloaded MSVC build tools and Windows SDK. But I still get this error. I tried downloading it several times with the pack of individual components that was in README.md but still no results.

_you need to install Visual Studio Community 2019. with 

MSVC v142 - VS 2019 C++ x64/x86 build tools
Windows SDK (10.0.17763.0)_

if you actually did it then re install it i guess

**Comment by DotWith** [comment]
MSVC v143 - VS 2022 C++ x64/x86 build tools
    Windows 10 SDK (10.20348.0)

If on windows 11 install

    Windows 11 SDK (10.0.22000.0)

**Comment by redbluexe1** [comment]
> ```
> MSVC v143 - VS 2022 C++ x64/x86 build tools
> Windows 10 SDK (10.20348.0)
> ```
> 
> If on windows 11 install
> 
> ```
> Windows 11 SDK (10.0.22000.0)
> ```



> ```
> MSVC v143 - VS 2022 C++ x64/x86 build tools
> Windows 10 SDK (10.20348.0)
> ```
> 
> If on windows 11 install
> 
> ```
> Windows 11 SDK (10.0.22000.0)
> ```

ninjamuffin didnt verify if it can compile it on windows 11 yet

**Comment by ProjectHSI** [comment]
> ninjamuffin didnt verify if it can compile it on windows 11 yet
I don't think it should be an issue, Haxe is a cross-platform scripting language anyway.
I'm still on Win10 Anyways so I can't confirm.

**Comment by 4techguns** [comment]
> > ```
> > MSVC v143 - VS 2022 C++ x64/x86 build tools
> > Windows 10 SDK (10.20348.0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If on windows 11 install
> > ```
> > Windows 11 SDK (10.0.22000.0)
> > ```
> 
> > ```
> > MSVC v143 - VS 2022 C++ x64/x86 build tools
> > Windows 10 SDK (10.20348.0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If on windows 11 install
> > ```
> > Windows 11 SDK (10.0.22000.0)
> > ```
> 
> ninjamuffin didnt verify if it can compile it on windows 11 yet

I can confirm compiling on Win 11 works without issue. 11 uses the same kernal version as 10, so there shouldn't be that much difference

**Comment by BernardoGP4504** [comment]
install visual studio 2017 (they share the same installer btw) and search for `VC` and then install:

- VC++ 2017 version 15.9 v14.16 latest v141 tools
- VC++ 2017 version 15.9 v14.16 Libs for Spectre (ARM)
- VC++ 2017 version 15.9 v14.16 Libs for Spectre (ARM64)
- VC++ 2017 version 15.9 v14.16 Libs for Spectre (x86 and x64)
