### ISSUE TITLE
this is not a question (fast fnf compile🥺😓😳😳😳😳😳😳)

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1885]
fast fnf compile 😳😳😳😳😳
![image](https://user-images.githubusercontent.com/94598301/142798891-53e74ded-daec-4461-bf12-cbec1e05b891.png)

**Comment by Hafimieh** [comment]
this is not a issue🥴😓🥺

**Comment by ThePlank** [comment]
fast compile becuz you already built the gaem (btw use discussions instead)
