### ISSUE TITLE
WinRAR Extracting issues

### ISSUE THREAD

**Issue by SkeldTheDiscordDev** [FunkinCrew/Funkin#1894]
I have an issue when extracting the funkin' master.zip file. When I use WinRAR to extract it, it says this 
`! C:\Users\blank\Documents\Shain\Funkin-master.zip: The archive is corrupt`
Idk if this is Github's fault or ninjamuffin's fault but I don't know what to do since it's impossible to extract and use the source code. I hope you can help me with this problem.

Thanks

**Comment by SkeldTheDiscordDev** [comment]
Btw, when i go to the archive some folders are missing, only art and github folders are there, other folders are missing idk why.

**Comment by ThePlank** [comment]
prob your pc. never had this issue.

**Comment by DotWith** [comment]
Ew WinRar.

**Comment by AbnormalPoof** [comment]
7-zip better + ratio + cope + skull issue + ew winrar

**Comment by SkeldTheDiscordDev** [comment]
Thanks for helping, I recently downloaded kade engine's GitHub and it had fully downloaded and WinRAR had no issue exporting so I guess GitHub has some issues with the repl. also, wtf with the ratio stuff...  not funny Poof.
