### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by omadfjk** [FunkinCrew/Funkin#1899]
(I'm Korean, so I may not be able to speak correctly using a translator.)
I'm from Wardo mode, starting state, play state.
I put the source code together to create and compile an attack event for the last song, but there was an error. Source/Playstate.hx:2753:characters 4-8:expected} I don't know why there's such an error. The code is this.
![image](https://user-images.githubusercontent.com/94978264/144425865-10c95770-227a-4806-bf03-e74b8bfd3953.png)
![image](https://user-images.githubusercontent.com/94978264/144425971-a956ed5a-a87e-4956-b3a2-1811cd913758.png)
![image](https://user-images.githubusercontent.com/94978264/144426117-4b24f15f-fd83-4472-847b-a846691064b5.png)
![image](https://user-images.githubusercontent.com/94978264/144426168-8a8254ab-5090-4fa5-a9f8-e70f67c8668e.png)
Windows version = 8 64 bit psych engine version = 0.4.2

**Comment by AbnormalPoof** [comment]
ask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repoask on the psych repov
