### ISSUE TITLE
Missing HXCPP_VARS | Error: Could not automatically setup MSVC

### ISSUE THREAD

**Issue by calicokatsu** [FunkinCrew/Funkin#190]
I'm trying to build the executable of this game by running `lime test windows -debug`. But I keep running into the error in the title. I  have all the requirements from the readme. Here's my My install of VSC:
![image](https://user-images.githubusercontent.com/62923115/104504529-96f25100-55b0-11eb-975e-f1e34e81512a.png)
and here's error: 
```C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:201: characters 31-37 : Warning : This typedef is deprecated in favor of sys.thread.Thread
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:72: characters 14-20 : Warning : This typedef is deprecated in favor of sys.thread.Thread
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:77: characters 13-19 : Warning : Usage of this typedef is deprecated
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:183: characters 31-37 : Warning : Usage of this typedef is deprecated
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:174: characters 32-38 : Warning : Usage of this typedef is deprecated
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:96: characters 32-38 : Warning : Usage of this typedef is deprecated
source/NGio.hx:44: characters 16-52 : Warning : Use currentVersion
F:\Coding\Funkin\export\release\windows\obj>setlocal enabledelayedexpansion
F:\Coding\Funkin\export\release\windows\obj>()
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

Edit: HTML5 Works

**Comment by LunarHarvey** [comment]
I have the same problem

**Comment by VMGuy23** [comment]
https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe

I really need to save that link somewhere

**Comment by Sincere1224** [comment]
Fnf

**Comment by ibyxlz** [comment]
redownload haxelib stuff
haxelib install lime 7.9.0
haxelib install openfl
haxelib install flixel
haxelib run lime setup
haxelib run lime setup flixel
haxelib install flixel-tools
haxelib run flixel-tools setup
haxelib install flixel-addons
haxelib install flixel-ui
haxelib install hscript
haxelib install newgrounds
haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit.git
haxelib git faxe https://github.com/uhrobots/faxe
haxelib git polymod https://github.com/larsiusprime/polymod.git
haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
haxelib install actuate
haxelib git extension-webm https://github.com/KadeDev/extension-webm
lime rebuild extension-webm <ie. windows, macos, linux>``

**Comment by Reycko** [comment]
[LOCATION]>lime rebuild extension-webm windows
D:\Haxe\haxe\lib\extension-webm\git\project>setlocal enabledelayedexpansion 
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by DybaTubeYT1** [comment]
Someone haves a windows solution?

**Comment by Blobby1002** [comment]
> redownload haxelib stuff haxelib install lime 7.9.0 haxelib install openfl haxelib install flixel haxelib run lime setup haxelib run lime setup flixel haxelib install flixel-tools haxelib run flixel-tools setup haxelib install flixel-addons haxelib install flixel-ui haxelib install hscript haxelib install newgrounds haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit.git haxelib git faxe https://github.com/uhrobots/faxe haxelib git polymod https://github.com/larsiusprime/polymod.git haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc haxelib install actuate haxelib git extension-webm https://github.com/KadeDev/extension-webm lime rebuild extension-webm <ie. windows, macos, linux>``

I cant install polymod? it says "Error: Could not clone Git repository." need help

**Comment by Baconyy** [comment]
Thanks!
