### ISSUE TITLE
Question : Could you upload HTML5 code so I can copy and paste it and create a file that I can play from my computer

### ISSUE THREAD

**Issue by MLGamer011** [FunkinCrew/Funkin#1900]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

**Comment by AbnormalPoof** [comment]
compile it

**Comment by MrClogsworthYT** [comment]
> 

step 1:fork
step 2:create a folder called .github
step 3:create a new one called workflows
step 4:make a file called Html.yml
step 4:copy kade engine windows code
step 5:edit it to become html5
step 6:wait for workflows to finish
step 7:download it in the Actions tab
step 8:profit

**Comment by AbnormalPoof** [comment]
um, ke has an html5 yml too lol

**Comment by MrClogsworthYT** [comment]
> um, ke has an html5 yml too lol

i forgor 💀
