### ISSUE TITLE
Game Crashes whenever I try to test it

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1914]
So i'm tryna do some shit, and when I run `lime test windows`, it loads the game, but it crashes like right after the application opens and the command prompt doesn't log an issue

anybody know how to solve this?

**Comment by CUBEkid04** [comment]
I'm running into the same exact issue, I had just got a new computer and reinstalled everything needed to build the source code, but when it opens the application is immediately closes with no error logged.

**Comment by Bigmancozmo** [comment]
Do `lime test windows -debug` not just `lime test windows`

**Comment by jaketheidiot38** [comment]
the same exact thing happens with me on kade but not on psych, for some reason

**Comment by NokioPyro** [comment]
@jaktheidiot38 Lad, this is the base game, not psych engine or kade engine.
@FireKoopaX It might be caused by something in Titlestaste.hx, maybe an xml file is missing.

**Comment by CUBEkid04** [comment]
I actually fixed it, mine was the version of Haxe I was using, so I copied the version I had on my old drive and did it on the new one and it worked like a charm.
