### ISSUE TITLE
pls delete this i accidently posted this on wrong engine

### ISSUE THREAD

**Issue by kotsergey2** [FunkinCrew/Funkin#1916]

**Comment by 12beesinatrenchcoat** [comment]
(Quick note: not a contributor or developer or anything.)
Assuming you're talking about https://github.com/ninjamuffin99/Funkin/issues/1915, you *might* be able to delete your own issue (there *might* be a delete issue button).
![image](https://user-images.githubusercontent.com/25379179/147371819-b582849f-0b8e-4f50-ae23-131c2522239c.png)

If there isn't one, you're probably better off just closing the issue.

**Comment by AbnormalPoof** [comment]
Only ninjamuffin can delete issues

**Comment by Windows1Door2Daniel** [comment]
> Only ninjamuffin can delete issues

Rad
