### ISSUE TITLE
Compiling help: [BRIEF DESCRIPTION / ERROR MESSAGE OUTPUT]

### ISSUE THREAD

**Issue by Rifmario** [FunkinCrew/Funkin#1918]
I already downloaded the individual components, but when I compiled it, the .exe is not in the folder.

![image](https://user-images.githubusercontent.com/96704561/147422295-7b6689f1-a038-4f64-a30d-8eaa09587acd.png)

**Comment by DotWith** [comment]
This isn't the Funkin repo

**Comment by ACrazyTown** [comment]
not the right repo, vanilla fnf does not use libvlc
