### ISSUE TITLE
NULL OBJECT REFERENCE HELP

### ISSUE THREAD

**Issue by Bigmancozmo** [FunkinCrew/Funkin#1928]
aaaaaaaaaaaaaaaaaaaaaa
IT JUST SAYS NULL OBECT REFERENCE
EVERYONE IS LIKE "oH yOu nEeD pOlYmOd" WHEN GUESS WHAT!?!?!??! I ALREADY HAVE IT INSTALLED!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by TheDisabledKid** [comment]
use this version of [polymod](https://github.com/TheDisabledKid/old-polymod) 
commands for installing the old one  
haxelib remove polymod  
haxelib git polymod https://github.com/TheDisabledKid/old-polymod.git

**Comment by MrClogsworthYT** [comment]
``use haxelib remove polymod
and then use the offical version of polymod on haxelib
haxelib install polymod 
if it doesnt work somehow
remove the 
```hx
#if polymod
polymod.Polymod.init({modRoot: "mods", dirs: ['introMod']});
#end
```
on titlestate which is on line 49-51
