### ISSUE TITLE
After installing Windows 11 i cant build game

### ISSUE THREAD

**Issue by Tr1NgleDev** [FunkinCrew/Funkin#1929]
After installing Windows 11. When i tried to build my mod, it builded without any error. but when it tried to run game, its just crashing right after it runned.

**Comment by TheRealJake12** [comment]
are you using this engine?

**Comment by Tr1NgleDev** [comment]
im using my own engine, but it based on original fnf source. but are you sure that its polymod issue? i didnt have that problem on windows 10. but im gonna try to install older version of polymod.

**Comment by Tr1NgleDev** [comment]
nah. thats not helping

**Comment by MrClogsworthYT** [comment]
update vs code to be windows 11 sdk instead of 10

**Comment by Tr1NgleDev** [comment]
> update vs code to be windows 11 sdk instead of 10

it should be windows 10 sdk. and i already fixed that shit. i just asked one of my friends to give me HaxeToolkit folder and now it working. The same problem was for my other friend so we just used the same HaxeToolkit folder rn.
