### ISSUE TITLE
[x] somethings wrong with my game I full combo'ed a full week (the week was week 1 and it was on hard) and its making terrifying noises I feel uncomfortable

### ISSUE THREAD

**Issue by Anaveragerythmgamefan** [FunkinCrew/Funkin#1937]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

**Comment by Rabbitual** [comment]
With very little information on the issue and no video capture of it, I doubt anybody will be able to successfully reproduce it. If it were caused simply by FC'ing the week, then it would be a known issue.

**Comment by NokioPyro** [comment]
Its an odd bug in the newgrounds week release, i get it often after finishing a week or freeplay song.
Just wait for the itch.io release.

**Comment by 0-skid** [comment]
it might be the menu song repeatedly starting, just exit freeplay then go back into it that might stop it

**Comment by NokioPyro** [comment]
It is the getting freaky song repeating often.
