### ISSUE TITLE
HOW DO I FIX THIS ERROR I KEEP GETTING THIS ERROR EVERY TIME even though i have the visual studio components

### ISSUE THREAD

**Issue by YellowNotSus** [FunkinCrew/Funkin#1939]
source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead.
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
E:\Documents\FNF Vs. PJ n' Drake\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by DotWith** [comment]
First, this isn't base FNF. I prefer you making a issue on that repo.

**Comment by YellowNotSus** [comment]
i have no expirience in modding. i don't know what i should do here. do i need the base fnf source or not

> First, this isn't base FNF. I prefer you making a issue on that repo.

**Comment by s-zenmode** [comment]
> i have no expirience in modding. i don't know what i should do here. do i need the base fnf source or not
> 
> > First, this isn't base FNF. I prefer you making a issue on that repo.

what they are saying is that ur not having a problem with friday night funkin, ur having a problem with haxe or something. make sure you followed everything just as stated and if it still persists, report that in the haxe repository or whatever it may be
