### ISSUE TITLE
Refresh Rate Issue

### ISSUE THREAD

**Issue by CyberGamerly** [FunkinCrew/Funkin#194]
I downloaded the game and I'm getting ~65 fps. Every time I played on Newgrounds I got 144 fps. Also, is there a fullscreen option or resolution setting? I bet all of this are in a .json file but I'm not having any luck here.

**Comment by ninjamuffin99** [comment]
if u press F on the title screen, u can fullscreen. Secret right now!

refresh rate might just be like, some option i forgot to fully enable maybe

**Comment by gedehari** [comment]
Don't have a 144hz monitor, but from the reports, HTML5 version can go to 144 fps, but the Desktop version locks to 60 fps. Maybe that's something to do with vsync? But then again, vsync is turned off in `Project.xml`, so I dunno.
