### ISSUE TITLE
Bug Report: most assets aren't drawn and rendered when loading into PlayState.hx on week 5 easy mode

### ISSUE THREAD

**Issue by approachcircle** [FunkinCrew/Funkin#1949]
### If you are playing the game in a browser, what site are you playing it from?

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [x] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.2.8(Newgrounds exclusive preview)

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
this bug happens every time i play week 5 on easy mode, so that's the only step there is to reproduce

## Please describe your issue. Provide extensive detail and images if possible.
i'll link a video to show what happens, but when i play week 5 on easy mode, the only assets that actually get drawn and rendered are the notes, but nothing else (no gf, player, mom, dad, bg)

the video is [here](https://drive.google.com/file/d/1vZki-cvBmo1W3W0JGKflnettXbJe2Miz/view?usp=sharing). (you may have to download it, but hopefully google will just let you watch it within your browser)

i just tested this in chrome, and the game just straight up unloads after it tries to switch state from LoadingState to PlayState (week 5), so maybe my pc just sucks. i can tell it's unloaded/completely broken because the FPS counter disappears, and an instance of the FPS counter is added as a child to the main openfl sprite in Main.hx, meaning that if that disappears, then the main openfl sprite (which FlxGame is added as a child to) has also probably broken.

## If your game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting
i don't have a copy of the js logs right now, but if you need them, just ask.

**Comment by ACrazyTown** [comment]
works fine for me, its probably a ram issue on your end? how much ram do you have

**Comment by approachcircle** [comment]
i have 8GB of ram, but surely that should be enough to run a HTML5 game, and all the other weeks load every asset fine?

**Comment by approachcircle** [comment]
## reproduced this bug on another computer
i also tested this on another computer with the same amount of ram, but with a different cpu, and a different gpu, and it did the exact same thing.
