### ISSUE TITLE
Compiling help: [help im trying to make a fnf mod and i get this error haxe/lib/polymod/git/polymod/fs/PolymodFileSystem.hx:19: characters 16-18 : Expected )]

### ISSUE THREAD

**Issue by JacksRobotics** [FunkinCrew/Funkin#1956]
when i type lime build windws debug or stuff like that i get this C:/haxelibstuff/haxe/lib/polymod/git/polymod/fs/PolymodFileSystem.hx:19: characters 16-18 : Expected )

im using
Windows x64 and latest version of the vanilla engine. i tried to reinstall polymod. and yes. i folloed the tutorial correctly

**Comment by Flanik** [comment]
it seems like polymod has a problem you might think

nope
its haxe update your haxe to the lastest release and the bug is fixed

**Comment by SpiralAnims** [comment]
@Flanik Do we update the application?

**Comment by imnotluis38** [comment]
@Flanik i updated to haxe 4.2.4 but it didnt work

**Comment by BeanCoderz** [comment]
when I tried this it still says the same thing
HaxeToolkit/haxe/lib/polymod/1,5,2/polymod/fs/PolymodFileSystem.hx:19: characters 16-18 : Expected )
