### ISSUE TITLE
Cant Load a song when compiled with lime test html5 -debug

### ISSUE THREAD

**Issue by test0082345** [FunkinCrew/Funkin#1962]
i am trying to load my song in my compiled html5 build it stays stuck on the loading screen

**Comment by Flanik** [comment]
> > i am trying to load my song in my compiled html5 build it stays stuck on the loading screen
> 
> There's something going on, press F12 to open the Chrome Dev Tools and go to the console and try to figure out what's going on from there

i dont use chrome

**Comment by ThePlank** [comment]
> > > i am trying to load my song in my compiled html5 build it stays stuck on the loading screen
> > 
> > 
> > There's something going on, press F12 to open the Chrome Dev Tools and go to the console and try to figure out what's going on from there
> 
> i dont use chrome

then what do you use

**Comment by Flanik** [comment]
> > > > i am trying to load my song in my compiled html5 build it stays stuck on the loading screen
> > > 
> > > 
> > > There's something going on, press F12 to open the Chrome Dev Tools and go to the console and try to figure out what's going on from there
> > 
> > 
> > i dont use chrome
> 
> then what do you use

Mircroshoft Edge

**Comment by BLJMan** [comment]
it's probably because you need both .mp3 and .ogg inst and voices when compiling
