### ISSUE TITLE
adding more keys to fnf

### ISSUE THREAD

**Issue by test0082345** [FunkinCrew/Funkin#1963]
so 

i wanna add more keys to fnf base game but idk how to

i have the source code of a kade engine with extra keys mod
idk what to copy and were to put it

can someone help me?

**Comment by KyleOliverDeveloper** [comment]
dude
this isnt Kade Engine's Github page

**Comment by Flanik** [comment]
> dude this isnt Kade Engine's Github page

i said "base game" i didnt mention kade engine

**Comment by Caleb8Cameron** [comment]
BUT 
I NEED TO KNOWWWWWWWWWWWWWWWWWWWWWWWWWW
