### ISSUE TITLE
can you help me with this issue of friday night funkin psych engine 

### ISSUE THREAD

**Issue by blazingcody** [FunkinCrew/Funkin#1966]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory

**Comment by KcTec90** [comment]
go to the psych engine github

**Comment by Gibberditoslumber** [comment]
oh another linux user
