### ISSUE TITLE
Enhancement: Fixing unintentional resets on controller.

### ISSUE THREAD

**Issue by BlubParadox** [FunkinCrew/Funkin#1968]
## What is your suggestion?
Changing line 633 in Controls.hx from 'Control.RESET => [Y]' to 'Control.RESET => [6]'

### Why should it be implemented?

This is going to sound a little stupid, but I play on a Guitar Hero Controller, in which the frets correspond to A,B,Y,X. The suggestion I am putting forward is to change the Y button to the Select button on controller. I am not the only person who plays the game on a Guitar Hero Controller, and I feel like it shouldn't have been set to Y in the first place, as some people would probably prefer to use A,B,Y,X instead of the D-Pad on a normal controller.

Select is a button that also wasn't in use to begin with, and would probably be a better fit for resetting.

### Why is it [6] and not [BACK] or [SELECT]?
This is the ID for the select button, as trying to use either [BACK] or [SELECT] simply won't work and the game won't compile.

#### why do you care
because i just wanna play the base game on a guitar hero controller (because im shit on a keyboard)

**Comment by CPPxfnfmodsmaker** [comment]
hi bitch

**Comment by CPPxfnfmodsmaker** [comment]
@CPPxfnfmodsmaker
