### ISSUE TITLE
Compiling help: [BRIEF DESCRIPTION / ERROR MESSAGE OUTPUT]

### ISSUE THREAD

**Issue by Pandaprogaming** [FunkinCrew/Funkin#1972]
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/fs/PolymodFileSystem.hx:19: characters 16-18 : Expected ) is the error i get how do i fix it?

**Comment by s-zenmode** [comment]
did you download the correct haxeflixel version

**Comment by Paidyy** [comment]
> did you download the correct haxeflixel version

this is not a haxeflixel problem 💀

**Comment by s-zenmode** [comment]
> > did you download the correct haxeflixel version
> 
> this is not a haxeflixel problem 💀

it looks like a haxe library issue, and when i followed the instructions precisely it worked for me. its probably not haxeflixel, but just haxe

**Comment by byemc** [comment]
> > > did you download the correct haxeflixel version
> > 
> > 
> > this is not a haxeflixel problem 💀
> 
> it looks like a haxe library issue, and when i followed the instructions precisely it worked for me. its probably not haxeflixel, but just haxe

It’s a library issue. I opened [a PR](https://github.com/larsiusprime/polymod/pull/114) about three weeks ago now but it hasn’t been merged yet. I think it’s just a waiting game now.
