### ISSUE TITLE
I need a composer!

### ISSUE THREAD

**Issue by DabbinDude316B** [FunkinCrew/Funkin#1978]
(Use soft girl voice for Opponent)

Song 1: Slow, Calm and nothing really happens
Song 2: Super slow, but gets suddenly fast near the end.
Song 3: A mix of Slow, Fast, And super fast
Song 4: Fast and Super fast song

**Comment by ACrazyTown** [comment]
I think the discussions would be better for this, issues are supposed to be related to FNF

**Comment by s-zenmode** [comment]
> (Use soft girl voice for Opponent)
> 
> Song 1: Slow, Calm and nothing really happens Song 2: Super slow, but gets suddenly fast near the end. Song 3: A mix of Slow, Fast, And super fast Song 4: Fast and Super fast song

this is the friday night funkin' github repository bug report tab. not gamebanana. please don't do that here thanks

**Comment by s-zenmode** [comment]
> I think the discussions would be better for this, issues are supposed to be related to FNF

i don't think so, the discussions tab is highlighted by ninjamuffin as being for discussing the code on this repo

**Comment by PoketrainerMS** [comment]
Go ask this on gamebanana instead. The github page, specifically the issues tab is meant for bug reports and such.
