### ISSUE TITLE
Bug Report: source/Character.hx:528: characters 13-14 : Expected , or )

### ISSUE THREAD

**Issue by CPPxfnfmodsmaker** [FunkinCrew/Funkin#1981]
source/Character.hx:528: characters 13-14 : Expected , or )

**Comment by Paidyy** [comment]
did you touched anything in Character class? it's just line with "{"

**Comment by ItsGaboch** [comment]
I have the same problem, and the only thing i changed is `PolymodScriptClass.hx:75: characters 87-91 : hscript.Error has no field line`
