### ISSUE TITLE
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/FlixelBackend.hx:50: characters 25-30 : openfl.utils.IAssetCache has no field cache

### ISSUE THREAD

**Issue by Eullim** [FunkinCrew/Funkin#1987]
Help me, i cant compile my game bc of this error help me
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/FlixelBackend.hx:50: characters 25-30 : openfl.utils.IAssetCache has no field cache

**Comment by Paidyy** [comment]
update polymod
