### ISSUE TITLE
Compiling help: [BRIEF DESCRIPTION / ERROR MESSAGE OUTPUT]

### ISSUE THREAD

**Issue by BeanCoderz** [FunkinCrew/Funkin#1989]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
HaxeToolkit/haxe/lib/polymod/1,5,2/polymod/fs/PolymodFileSystem.hx:19: characters 16-18 : Expected )

What am I doing wrong????> PLZ HELP

**Comment by byemc** [comment]
You’re not doing anything wrong, it’s a problem with the Polymod (is it library? I don’t use haxe lol)

You’re just gonna have to wait for an update there, because I don’t know where Haxe saves it’s libraries (or is it packages?) on windows.

**Comment by Gibberditoslumber** [comment]
he tested it on a older version of haxe

**Comment by byemc** [comment]
> he tested it on a older version of haxe 

It's a [problem with Polymod](https://github.com/larsiusprime/polymod/pull/114) though.
