### ISSUE TITLE
Missing character(s)

### ISSUE THREAD

**Issue by Stordoy** [FunkinCrew/Funkin#199]
a few days ago the main character didn't appear before singing, where his animated sprite would appear then disappear untill the next button appeared, but now it's gotten worse. This has happened to other characters but reverse. when the female tutorial sings her sprite goes away, and now there is a delay bewteen when you're supposed to press a button and when the sound comes with around one second. This is delay is around a second or so before you press a button, so the sound comes before you've done anything.

**Comment by gedehari** [comment]
Never experienced the first issue, but I experienced the second one. I think it has to do with the game doesn't preload all the assets (note hit sprite and some other things). Very noticable when playing with slow hard drive.
