### ISSUE TITLE
Question: how i add ghost tapping?

### ISSUE THREAD

**Issue by MrIncredible1037** [FunkinCrew/Funkin#1990]
please :(

**Comment by XavierCodes99** [comment]
> please :(

yea me too pls :(

**Comment by the-funky-lad** [comment]
steal- oh i meant _**borrow**_ the code from kade

**Comment by XavierCodes99** [comment]
> steal- oh i meant _**borrow**_ the code from kade

what (also i dont know how to code haxe)

**Comment by Caleb8Cameron** [comment]
OK SMARTY TRYN TO GET ME TO STEAL Thats No Good

**Comment by the-funky-lad** [comment]
no, its very good, because it saves time, and you need to give credit if you steal from the interwebs

**Comment by ThePlank** [comment]
> OK SMARTY TRYN TO GET ME TO STEAL Thats No Good

that.... removes the whole point of giving pepole source code access

**Comment by SpunBlue** [comment]
just remove any reference to the badnotecheck function lol (or just have a if statement thats either true or false that doesnt allow badnotecheck to do anything)

**Comment by XavierCodes99** [comment]
> please :(

https://github.com/ninjamuffin99/Funkin/discussions/new

**Comment by XavierCodes99** [comment]
> please :(

https://github.com/ninjamuffin99/Funkin/discussions/new
