### ISSUE TITLE
help meeeehhhhhhhhhhhhhhh

### ISSUE THREAD

**Issue by Mooonshiney** [FunkinCrew/Funkin#1992]
Called from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 1703
Called from lime/tools/ProjectXMLParser.hx line 21
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 50
Called from lime/tools/ProjectXMLParser.hx line 2043
Called from lime/tools/ProjectXMLParser.hx line 1528
Called from lime/tools/ProjectXMLParser.hx line 608
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 709
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 69
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 60
Uncaught exception - std@sys_file_type
yeah that happen when trying to export, v0.2.1.7 btw

**Comment by SomeDudeMod** [comment]
have you download anything? if you haven't it wont work

**Comment by J0nathan550** [comment]
Current version of Engine by NinjaMuffin is not stable. Better if you would just installed blank psych engine in releases section.

LINK: **https://github.com/ShadowMario/FNF-PsychEngine**
