### ISSUE TITLE
Give bonus score increasing by the combo

### ISSUE THREAD

**Issue by Windows1Door2Daniel** [FunkinCrew/Funkin#1995]
Give extra points when in a combo, the bigger the combo the more extra score you get

A combo of 5 would give 50 extra points per note
A 10 combo a extra 100 points and so it goes

**Comment by Gibberditoslumber** [comment]
Ninja Muffin Doesn't Update This Repostory Last Update Was In 2021

**Comment by Windows1Door2Daniel** [comment]
> Ninja Muffin Doesn't Update This Repostory Last Update Was In 2021

God yes i saw

I didn't played the game like months

**Comment by Windows1Door2Daniel** [comment]
> 

Your rigth
