### ISSUE TITLE
Compiling help: Getting a HUGE error message when trying to compile

### ISSUE THREAD

**Issue by VoncheyK** [FunkinCrew/Funkin#1996]
Called from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 1703
Called from lime/tools/ProjectXMLParser.hx line 21
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 50
Called from lime/tools/ProjectXMLParser.hx line 2043
Called from lime/tools/ProjectXMLParser.hx line 1528
Called from lime/tools/ProjectXMLParser.hx line 608
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 709
Called from /usr/share/haxe/std/neko/_std/sys/FileSystem.hx line 68
Called from /usr/share/haxe/std/neko/_std/sys/FileSystem.hx line 59
Uncaught exception - std@sys_file_type

Im on Windows 10 [Haxe Version 1.4.5] and when trying to compile i get this.

**Comment by ACrazyTown** [comment]
Haxe 1.4.5 doesn't exist, I'm guessing you meant 4.1.5
Update to the latest version of Haxe (4.2.5 rn) and try a clean build:
`lime test windows -debug -clean`

**Comment by VoncheyK** [comment]
@ACrazyTown It happens when i try to compile. Like instantly when i press enter it just shows that message, even with 4.2.5
