### ISSUE TITLE
Question: Could you make Week 7 available to download on itch.io?

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#1997]
I'm currently playing Week 7 on Newgrounds but going to https://www.newgrounds.com/portal/view/770371/Funkin.exe wont give me the executable or anything lol

**Comment by Igorgames3000** [comment]
The Week 7 executable will come out along with week 8

**Comment by Windows1Door2Daniel** [comment]
It has been like a year of no update

**Comment by ThePlank** [comment]
> going to https://www.newgrounds.com/portal/view/770371/Funkin.exe wont give me the executable

this is a folder of a built OpenFL HTML5 game
![image](https://user-images.githubusercontent.com/75984453/171986386-afdf8a44-1b1c-4ae3-9b7e-e4280bc25655.png)
no wonder that trying to get Funkin.exe didn't work

**Comment by BraydenAnimati0ns** [comment]
> > going to https://www.newgrounds.com/portal/view/770371/Funkin.exe wont give me the executable
> 
> this is a folder of a built OpenFL HTML5 game ![image](https://user-images.githubusercontent.com/75984453/171986386-afdf8a44-1b1c-4ae3-9b7e-e4280bc25655.png) no wonder that trying to get Funkin.exe didn't work

that on ur github page?

**Comment by HackersLOLwskasdhq3ew** [comment]
Because it is an exclusive for Newsground, Dumbass.

PSYCH ENGINE HAS FUNI WEEK 7
