### ISSUE TITLE
Bug Report: fnf crashes when loading into a custom song

### ISSUE THREAD

**Issue by CPPxfnfmodsmaker** [FunkinCrew/Funkin#1998]
[weed]: <fnf crashes when loading into custom song> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?
ayo im playing it from source compiled verson

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ x] Windows
- - [ ] Mac
- - [ ] Linux

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [x ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
the newest verson

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
no

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting
![bandicam 2022-06-04 15-49-14-062](https://user-images.githubusercontent.com/101651840/172003659-092f360d-84f3-4c33-b8e7-835d7940722b.jpg)

**Comment by ACrazyTown** [comment]
If it's a custom song, it's not a Friday Night Funkin' issue. This should go in the discussions.
From the error, you've tried to reference something that has not been initialized yet (so it's null.)
