### ISSUE TITLE
I downloaded the game. Sprite issue.

### ISSUE THREAD

**Issue by loopzoop99** [FunkinCrew/Funkin#200]
I downloaded the game. The enemy and backgrounds load in just fine. But boyfriend and girlfriend are black squares and I don't know how to fix it.  What do I do? Do I redownload? I am on a pc.

**Comment by loopzoop99** [comment]
the only background that doesnt load is for the spookeez map

**Comment by Tatamaxter** [comment]
> I downloaded the game. The enemy and backgrounds load in just fine. But boyfriend and girlfriend are black squares and I don't know how to fix it. What do I do? Do I redownload? I am on a pc.

me too.
