### ISSUE TITLE
Enhancement: Song Lock & Song Visible

### ISSUE THREAD

**Issue by Swapper1** [FunkinCrew/Funkin#2002]
The Freeplay menu would use Song Locks (like in Story Mode's Week locks) & Song Visible in the game, so the player can't go into this song until they beat the song in story mode. Unlike Weeks lock, Song lock will have Lock Icon instead of the Character Icon, while Song visible will hide their song.

Example: If you beat Week 2 song South, a current song will be unlocked. If you beat the Week 3, Week 4 songs will be shown but it still locked.

**Comment by J0nathan550** [comment]
In the alpha version of FNF, that system was being. But later was being removed. Maybe on the final release this feature will be available.
