### ISSUE TITLE
i cant compile the game

### ISSUE THREAD

**Issue by marcitosero** [FunkinCrew/Funkin#2004]
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:71: characters 52-56 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:74: characters 87-91 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:357: characters 17-18 : hscript.Error has no field e 
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:373: characters 70-74 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:379: characters 70-74 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:384: characters 70-74 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:388: characters 69-73 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:392: characters 69-73 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:396: characters 69-73 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodInterpEx.hx:134: characters 9-15 : hscript.Interp has no field setVar
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodInterpEx.hx:115: characters 20-26 : Field setVar is declared 'override' but doesn't override any field

**Comment by Sonicwithtophat** [comment]
same C:\Users\Owner\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main>lime test windows
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:365: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead.
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\Owner\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

**Comment by J0nathan550** [comment]
Guys, currently the original Engine is not stable. Better if you would just installed best and stable version of Psych Engine to make own mods. 

**Link:https://github.com/ShadowMario/FNF-PsychEngine**

**Comment by ThePlank** [comment]
> Guys, currently the original Engine is not stable. **Better if you would just installed best and stable version of Psych Engine to make own mods.**

bruhhhhhhhhh 💀

**Comment by HarithHkm08** [comment]
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:71: characters 52-56 : hscript.Error has no field line
> 
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:74: characters 87-91 : hscript.Error has no field line
> 
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:357: characters 17-18 : hscript.Error has no field e 
> 
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:373: characters 70-74 : hscript.Error has no field line
> 
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:379: characters 70-74 : hscript.Error has no field line
> 
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:384: characters 70-74 : hscript.Error has no field line
> 
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:388: characters 69-73 : hscript.Error has no field line
> 
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:392: characters 69-73 : hscript.Error has no field line
> 
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:396: characters 69-73 : hscript.Error has no field line
> 
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodInterpEx.hx:134: characters 9-15 : hscript.Interp has no field setVar
> 
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodInterpEx.hx:115: characters 20-26 : Field setVar is declared 'override' but doesn't override any field

reinstall all of the libraries

**Comment by MemeHoovy** [comment]
Use polymod 1.3.1, don't use the git version it doesn't work.
```
haxelib install polymod 1.3.1
```
