### ISSUE TITLE
Compiling help: TitleState and Note.hx Polymod error

### ISSUE THREAD

**Issue by STIk-3807** [FunkinCrew/Funkin#2013]
I've tried to install polymod many times and i always get this error all the time and it really annoys me. Can some1 help me fix this error?

source/Note.hx:11: characters 8-33 : Type not found : polymod.format.ParseRules
source/TitleState.hx:120: characters 3-18 : Type not found : polymod.Polymod

**Comment by BLJMan** [comment]
you should be able to just remove that code without any problem
