### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by Lightcritical** [FunkinCrew/Funkin#2014]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

## What is your question?
Its possible to build the game without polymod?

**Comment by itsDARK768** [comment]
Yes, you just take the plugin out of the project.xml file and remove the polymod thing in TitleState.hx and I think you should be good to go.
