### ISSUE TITLE
"Null Object Reference" when loading Custom Character

### ISSUE THREAD

**Issue by CPPxfnfmodsmaker** [FunkinCrew/Funkin#2016]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1950
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1166
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 551
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 747
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 203
Called from PlayState::update PlayState.hx line 1365
Called from MusicBeatState::update MusicBeatState.hx line 41
Called from flixel.addons.ui.FlxUIState::update flixel/addons/ui/FlxUIState.hx line 212
Called from flixel.group.FlxTypedGroup::update flixel/group/FlxGroup.hx line 175
Called from Character::update Character.hx line 546

https://user-images.githubusercontent.com/101651840/175929896-ac65e75a-7982-4ffe-8777-fb4728393e63.mp4

https://user-images.githubusercontent.com/101651840/175930160-49b40ac4-e8fd-481d-a028-a182fb17088e.mp4

**Comment by CPPxfnfmodsmaker** [comment]
- [x] no

**Comment by BLJMan** [comment]
did you write the code for the new character's icon in HealthIcon.hx?
if not the game will search for an icon animation called the name of the character, and won't find it.
