### ISSUE TITLE
Compiling help: APIStuff doc not turning into .hx

### ISSUE THREAD

**Issue by baessqq** [FunkinCrew/Funkin#2021]
Hi! To start off, I'm extremely tired rn so if anything doesn't make sense then that's why.
This is my first time trying to make a fnf mod and there's some type of issue with the APIStuff.tx thing. The API.stuff text doc will not convert into .tx file no matter what I try. I think this is the main issue since when I was trying to load the game it said something about how there was no type of APIStuff.tx. I'm following a tutorial on YouTube about this so idk if there's new info that they didn't mention or something.
I have a windows 11 btw.
Here's some screenshots
![Screenshot (47)](https://user-images.githubusercontent.com/108809416/177553370-3f41dd9b-9f47-4f74-8ba1-3f2174fd733c.png)
![Screenshot (48)](https://user-images.githubusercontent.com/108809416/177553403-6215768f-7ba8-410d-91e9-72655742e0fe.png)

**Comment by CrusherMods** [comment]
File > Save As > Save as type: > All Files

**Comment by Dominicthecodingenuis** [comment]
#2025

**Comment by s-zenmode** [comment]
if ur making a fnf mod then dont use base engine lmao use some fanmade engine

**Comment by XuelDev** [comment]
What if he doesn't wanna use "fanmade engine".

**Comment by HackersLOLwskasdhq3ew** [comment]
> if ur making a fnf mod then dont use base engine lmao use some fanmade engine

Dumbass, what if he's building a fucking engine?
