### ISSUE TITLE
Compiling help: [BUILDING ISSUE]

### ISSUE THREAD

**Issue by Lightcritical** [FunkinCrew/Funkin#2023]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] Windows
- [X] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

When i go to the export folder and try to run the Funkin app it closes

**Comment by BushTrain460615** [comment]
go in to title state and delete this line of code

```
#if polymod
		polymod.Polymod.init({modRoot: "mods", dirs: ['introMod']});
#end
```
