### ISSUE TITLE
Question: PolyMod Error

### ISSUE THREAD

**Issue by nebniywolf** [FunkinCrew/Funkin#2025]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

## What is your question?
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:418: characters 69-73 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:72: characters 52-56 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:75: characters 87-91 : hscript.Error has no field line

Its my error ;-;

**Comment by Dominicthecodingenuis** [comment]
in command prompt type haxelib remove polymod
when its done type haxelib install polymod 1.5.1

**Comment by nebniywolf** [comment]
uhm

**Comment by nebniywolf** [comment]
![2022-07-23_133811](https://user-images.githubusercontent.com/104686407/180601665-f24fe5b9-9a77-42be-b7b5-05b23ad3db4c.jpg)
___*( ￣皿￣)/#____

**Comment by Dominicthecodingenuis** [comment]
https://github.com/larsiusprime/polymod/files/8237049/PolymodFileSystem.zip

**Comment by Dominicthecodingenuis** [comment]
and dont compile html5 for tricky
