### ISSUE TITLE
Story menu and Freeplay gives error when entering!?

### ISSUE THREAD

**Issue by Hayak0** [FunkinCrew/Funkin#2031]

**Comment by TheKitBoi** [comment]
Mate this is a Funkin GitHub not a Psych Engine GitHub
Just go there https://github.com/ShadowMario/FNF-PsychEngine

**Comment by TheKitBoi** [comment]
You can now close this issue

**Comment by nizqwp** [comment]
> Mate this is a Funkin GitHub not a Psych Engine GitHub
> Just go there

brother, if he is in the original fnf code it is because he is not looking to use a different engine

**Comment by nizqwp** [comment]
> 

Remove references to Ngio in the states
