### ISSUE TITLE
Compiling help: [Compiling error won't let me compile / polymod.hscript._internal.ErrorEx has no field line]

### ISSUE THREAD

**Issue by BernardoGP4504** [FunkinCrew/Funkin#2032]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
when i type `lime test windows` these errors come up:
```
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:60: characters 52-56 : polymod.hscript._internal.ErrorEx has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:63: characters 87-91 : polymod.hscript._internal.ErrorEx has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:366: characters 69-73 : polymod.hscript._internal.ErrorEx has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : For function argument 'e'
```

**Comment by MemeHoovy** [comment]
Use an old version of Polymod.
haxelib install polymod 1.3.1
After installing it, you can switch back to git version (if you want to) by using
haxelib set polymod git

**Comment by BernardoGP4504** [comment]
> Use an old version of Polymod. haxelib install polymod 1.3.1 After installing it, you can switch back to git version (if you want to) by using haxelib set polymod git

thanks
