### ISSUE TITLE
Compiling help: [polymod / polymod issue]

### ISSUE THREAD

**Issue by GreenSoupDeveloper** [FunkinCrew/Funkin#2034]
hello, I've been trying to fix this for weeks but I can't fix it, can help me?

C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:60: characters 52-56 : polymod.hscript._internal.ErrorEx has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:63: characters 87-91 : polymod.hscript._internal.ErrorEx has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:366: characters 69-73 : polymod.hscript._internal.ErrorEx has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : For function argument 'e'

:(

**Comment by MemeHoovy** [comment]
Use polymod 1.3.1 haxelib install polymod 1.3.1
And when you wanna switch back to the git version use
haxelib set polymod git

**Comment by GreenSoupDeveloper** [comment]
thanks

**Comment by Stilic** [comment]
run this in a terminal:
```
haxelib remove hscript
haxelib install hscript
```

and put this in the project.xml:
```xml
<!-- Enable HScript fine error reporting at parsing time -->
<haxedef name="hscriptPos" if="hscript" />
```

**Comment by MemeHoovy** [comment]
> run this in a terminal:
> 
> ```
> haxelib remove hscript
> haxelib install hscript
> ```
> 
> and put this in the project.xml:
> 
> ```
> 
> <haxedef name="hscriptPos" if="hscript" />
> ```

how does that help?

**Comment by GreenSoupDeveloper** [comment]
> run this in a terminal:
> 
> ```
> haxelib remove hscript
> haxelib install hscript
> ```
> 
> and put this in the project.xml:
> 
> ```
> 
> <haxedef name="hscriptPos" if="hscript" />
> ```

Thanks!

it worked :)

**Comment by alexandrucn** [comment]
where?

**Comment by MemeHoovy** [comment]
> where?

run this in a _terminal_:

```
haxelib remove hscript
haxelib install hscript
```

and put this in the _Project.XML_:
```
<!--Enable HScript fine error reporting at parsing time-->
<haxedef name="hscriptPos" if="hscript" />
```

**Comment by GreenSoupDeveloper** [comment]
thanks

**Comment by Djsnow21** [comment]
in which part of the ''Project.XML do I have to put ''
<haxedef name="hscriptPos" if="hscript" />''?

**Comment by MemeHoovy** [comment]
> in which part of the ''Project.XML do I have to put the command

...are you literally braindead? you put this in Project.XML
```
<!--Enable HScript fine error reporting at parsing time-->
<haxedef name="hscriptPos" if="hscript" />
```
underneath this
```
	<!--Enable this for Nape release builds for a serious peformance improvement-->
	<haxedef name="NAPE_RELEASE_BUILD" unless="debug" />
```
you don't put the fucking command in Project.XML you dumbass, you put it in a **Terminal**

**Comment by Paidyy** [comment]
> in which part of the ''Project.XML do I have to put the command

put it anywhere as long as it is inside <project>

**Comment by BamSchoolGithub** [comment]
> in which part of the ''Project.XML do I have to put the command

these god dang kids keep being stupid

**Comment by dripbacon72-ui** [comment]
reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
