### ISSUE TITLE
Compiling help: Error when I did everything the compiling tutorial said

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#2035]
## Please describe your issue. Provide extensive detail and images if possible.
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by MemeHoovy** [comment]
If you haven't already, you need to install Visual Studio Community 2019.

And install this component. It **must** be latest **specifically**.
* MSVC v142 - VS 2019 C++ x64/x86 build tools (Latest)
