### ISSUE TITLE
Compiling help: Crashing

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#2037]
When I open the game it crashes.

When I open it with a bat no errors are shown it just closes, the fps counter doesn't even show up.

**Comment by MemeHoovy** [comment]
Are there any errors when you open it without a bat?
And have you tried to compiling to debug to see the error?

**Comment by SpookyMan16** [comment]
> Are there any errors when you open it without a bat? And have you tried to compiling to debug to see the error?

Well everytime I recompille it takes as long as the 1st time ever

**Comment by SpookyMan16** [comment]
It goes Null Object Refrence

**Comment by SpookyMan16** [comment]
the full error in cmd is 

Called from polymod.backends.LimeBackend.init (polymod/backends/LimeBackend.hx line 127)
Called from polymod.backends.PolymodAssets.init (polymod/backends/PolymodAssets.hx line 133)
Called from polymod.Polymod.init (polymod/Polymod.hx line 252)
Called from TitleState.create (TitleState.hx line 50)
Called from flixel.FlxGame.switchState (flixel/FlxGame.hx line 637)
Called from flixel.FlxGame.create (flixel/FlxGame.hx line 360)
Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)
Called from openfl.display.DisplayObject.__dispatchEvent (openfl/display/DisplayObject.hx line 1417)
Called from openfl.display.DisplayObject.__dispatchWithCapture (openfl/display/DisplayObject.hx line 1478)
Called from openfl.display.DisplayObjectContainer.addChildAt (openfl/display/DisplayObjectContainer.hx line 266)
Called from openfl.display.DisplayObjectContainer.addChild (openfl/display/DisplayObjectContainer.hx line 155)
Called from Main.setupGame (Main.hx line 70)
Called from Main.init (Main.hx line 49)
Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)
Called from openfl.display.DisplayObject.__dispatchEvent (openfl/display/DisplayObject.hx line 1417)
Called from openfl.display.DisplayObject.__dispatchWithCapture (openfl/display/DisplayObject.hx line 1478)
Called from openfl.display.DisplayObjectContainer.addChildAt (openfl/display/DisplayObjectContainer.hx line 266)
Called from openfl.display.DisplayObjectContainer.addChild (openfl/display/DisplayObjectContainer.hx line 155)
Called from Main.main (Main.hx line 25)
Null Object Reference
Called from Main::main Main.hx line 25
Called from openfl.display.DisplayObjectContainer::addChild openfl/display/DisplayObjectContainer.hx line 155
Called from openfl.display.DisplayObjectContainer::addChildAt openfl/display/DisplayObjectContainer.hx line 266
Called from openfl.display.DisplayObject::__dispatchWithCapture openfl/display/DisplayObject.hx line 1478
Called from openfl.display.DisplayObject::__dispatchEvent openfl/display/DisplayObject.hx line 1417
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from Main::init Main.hx line 49
Called from Main::setupGame Main.hx line 70
Called from openfl.display.DisplayObjectContainer::addChild openfl/display/DisplayObjectContainer.hx line 155
Called from openfl.display.DisplayObjectContainer::addChildAt openfl/display/DisplayObjectContainer.hx line 266
Called from openfl.display.DisplayObject::__dispatchWithCapture openfl/display/DisplayObject.hx line 1478
Called from openfl.display.DisplayObject::__dispatchEvent openfl/display/DisplayObject.hx line 1417
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::create flixel/FlxGame.hx line 360
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 637
Called from TitleState::create TitleState.hx line 50
Called from polymod.Polymod::init polymod/Polymod.hx line 252
Called from polymod.backends.PolymodAssets::init polymod/backends/PolymodAssets.hx line 133
Called from polymod.backends.LimeBackend::init polymod/backends/LimeBackend.hx line 127

**Comment by MemeHoovy** [comment]
Use an older version of Polymod.
```
Haxelib install polymod 1.3.1
```
Newer versions don't work.
