### ISSUE TITLE
Question: Why do I only have Update-5 or 4 for the game and not the real update twenty something?

### ISSUE THREAD

**Issue by TrollingPhaseYt** [FunkinCrew/Funkin#2038]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

**Comment by TheKitBoi** [comment]
What do you mean

**Comment by MemeHoovy** [comment]
> What do you mean

exactly

**Comment by nizqwp** [comment]
maybe it is that Project.xml refers to another version than in NGio.hx
