### ISSUE TITLE
game doesn't load in Newgrounds

### ISSUE THREAD

**Issue by juantoPro123** [FunkinCrew/Funkin#204]
I want to play the game in Newgrounds, but it doesnt load, pls fix this. Thank you

**Comment by Blizzardo01** [comment]
It works for me! Maybe try reloading the page or restarting your device? Make sure your browser is up to date as well.

**Comment by FireyAlex12** [comment]
read the description for Newgrounds verison_

**Comment by cesarioMartinez** [comment]
> It works for me! Maybe try reloading the page or restarting your device? Make sure your browser is up to date as well.

i did it and still dose the same thing
