### ISSUE TITLE
Question: I want to make a FNF mod but I don't know with wichone I should use

### ISSUE THREAD

**Issue by marcusWeb04** [FunkinCrew/Funkin#2041]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

**Comment by WuffGaming** [comment]
which of what

**Comment by ThePlank** [comment]
i guess he means engine? [funkin-resources has a lot of engines to choose from](https://github.com/FunkinCrew/funkin-resources#engines-and-forks)
