### ISSUE TITLE
Bug Report: [I die every time I make a mistake]

### ISSUE THREAD

**Issue by kcm454** [FunkinCrew/Funkin#2042]
I die every time I make a mistake

**Comment by ThePlank** [comment]
....whaaaaaaat?

**Comment by MemeHovy** [comment]
skill issue @kcm454 close this

**Comment by JovadinoDev** [comment]
bro, you probably just TRASH at the game! Please make a REAL bug report! cuz i think ninjamuffin99 is fucking confused i bet lol (or maybe is a real bug, but ik its not :|)

**Comment by HackersLOLwskasdhq3ew** [comment]
skill issue 🖕
