### ISSUE TITLE
Building for Switch as NSP

### ISSUE THREAD

**Issue by regulad** [FunkinCrew/Funkin#205]
# Building for Switch as NSP
* `.nsp` homebrew is is a very poor practice since it cannot be safely used on sysNAND CFW, and it can be malicious.
* `.nro` is a much better format and also much safer for distribution and launching using conventional tools like [hbmenu](https://github.com/switchbrew/nx-hbmenu). Therefore, it would be greatly appreciated if there was an easy way to build the game as `.nro`. 
* Thank you for reading!

**Comment by regulad** [comment]
~~also can someone explain to me where the fuck `lime-switch` is~~

**Comment by ninjamuffin99** [comment]
lime-switch is a version of lime made for Nintendo Switch, and since it uses Nintendo SDKs, you need to be an approved nintendo dev and have signed NDAs with them. I myself dont even have that access! BUT if you happen to be a dev, u can contact Lars Doucet!

**Comment by regulad** [comment]
welp, there goes my hopes of a way to get it as an `nro`
