### ISSUE TITLE
A little help here?

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#2053]
So, when I try to compile the game instead of ACTUALLY COMPILING like it's supposed to, it just throws this random spaghetti shit at me :

 C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:60: characters 52-56 : polymod.hscript._internal.ErrorEx has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:63: characters 87-91 : polymod.hscript._internal.ErrorEx has no field line
source/NGio.hx:12: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:13: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:45: characters 61-75 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:45: characters 103-126 : Type not found : GetCurrentVersionResult
source/NGio.hx:96: characters 25-39 : Void -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:96: characters 25-39 : For optional function argument 'callback'
source/NGio.hx:99: characters 30-45 : Void -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:99: characters 30-45 : For optional function argument 'callback'
source/NGio.hx:85: characters 25-34 : Void -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:85: characters 25-34 : For optional function argument 'callback'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:366: characters 69-73 : polymod.hscript._internal.ErrorEx has no field line      
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : polymod.hscript._internal.ErrorEx should be hscript.Error    
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:442: characters 16-41 : polymod.hscript._internal.ErrorEx should be hscript.Error   
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:442: characters 16-41 : For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error   
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : polymod.hscript._internal.ErrorEx should be hscript.Error   
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error   
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : For function argument 'e'

I have no idea how to fix this, so I need help from someone who can speak spaghetti. Any help is appreciated.

**Comment by ACrazyTown** [comment]
> So, when I try to compile the game instead of ACTUALLY COMPILING like it's supposed to, it just throws this random spaghetti shit at me :
> 
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:60: characters 52-56 : polymod.hscript._internal.ErrorEx has no field line C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:63: characters 87-91 : polymod.hscript._internal.ErrorEx has no field line source/NGio.hx:12: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult source/NGio.hx:13: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult source/NGio.hx:45: characters 61-75 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler) source/NGio.hx:45: characters 103-126 : Type not found : GetCurrentVersionResult source/NGio.hx:96: characters 25-39 : Void -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void> source/NGio.hx:96: characters 25-39 : For optional function argument 'callback' source/NGio.hx:99: characters 30-45 : Void -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void> source/NGio.hx:99: characters 30-45 : For optional function argument 'callback' source/NGio.hx:85: characters 25-34 : Void -> Void should be Null<io.newgrounds.LoginOutcome -> Void> source/NGio.hx:85: characters 25-34 : For optional function argument 'callback' C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:366: characters 69-73 : polymod.hscript._internal.ErrorEx has no field line C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : polymod.hscript._internal.ErrorEx should be hscript.Error C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : For function argument 'e' C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:442: characters 16-41 : polymod.hscript._internal.ErrorEx should be hscript.Error C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:442: characters 16-41 : For function argument 'e' C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : For function argument 'e' C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : polymod.hscript._internal.ErrorEx should be hscript.Error C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : For function argument 'e' C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : For function argument 'e'
> 
> I have no idea how to fix this, so I need help from someone who can speak spaghetti. Any help is appreciated.

Both the Newgrounds haxelib and the polymod haxelib were updated so the FNF source isn't up to date, either install an older version or remove references to polymod and newgrounds

**Comment by lordp78ng** [comment]
okay i'll test when i get the chance then i'll close

**Comment by lordp78ng** [comment]
fixed it thanks!
