### ISSUE TITLE
Compiling problems. How to fix pls?

### ISSUE THREAD

**Issue by XavierCodes99** [FunkinCrew/Funkin#2055]
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:60: characters 52-56 : polymod.hscript._internal.ErrorEx has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:63: characters 87-91 : polymod.hscript._internal.ErrorEx has no field line
source/NGio.hx:12: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:13: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:45: characters 61-75 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:45: characters 103-126 : Type not found : GetCurrentVersionResult
source/NGio.hx:96: characters 25-39 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:96: characters 25-39 : ... For optional function argument 'callback'
source/NGio.hx:99: characters 30-45 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:99: characters 30-45 : ... For optional function argument 'callback'
source/NGio.hx:85: characters 25-34 : () -> Void should be Null<io.newgrounds.LoginOutcome -> Void>       
source/NGio.hx:85: characters 25-34 : ... For optional function argument 'callback'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:366: characters 69-73 : polymod.hscript._internal.ErrorEx has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : ... For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : ... For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : ... For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : ... For function argument 'e'

**Comment by ClirXX** [comment]
go to your command prompt and do the following:
haxelib remove newgrounds
haxelib install newgrounds 1.1.5
to fix polymod do:
haxelib remove polymod
haxelib install polymod 1.3.1

**Comment by XavierCodes99** [comment]
But when running "haxelib remove polymod" in the terminal, i get

'attrib' is not recognized as an internal or external command,
operable program or batch file.
'attrib' is not recognized as an internal or external command,
operable program or batch file.
Error: std@sys_remove_dir

Is this normal?

**Comment by ClirXX** [comment]
> But when running "haxelib remove polymod" in the terminal, i get
> 
> 'attrib' is not recognized as an internal or external command, operable program or batch file. 'attrib' is not recognized as an internal or external command, operable program or batch file. Error: std@sys_remove_dir
> 
> Is this normal? Also I got new errors. Here's the new output when i run "lime test windows":
> 
> source/PlayState.hx:170: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead C:/HaxeToolkit/haxe/lib/newgrounds/1,1,5/lib/Source/io/newgrounds/components/ScoreBoardComponent.hx:55: characters 24-44 : Warning : Std.is is deprecated. Use Std.isOfType instead. C:/HaxeToolkit/haxe/lib/newgrounds/1,1,5/lib/Source/io/newgrounds/components/ScoreBoardComponent.hx:55: characters 49-66 : Warning : Std.is is deprecated. Use Std.isOfType instead.
> 
> Compiling group: haxe cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\LENOVO SLIM 3\Desktop\sapphire-engine\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
> 
> * src/flixel/system/debug/interaction/tools/Pointer.cpp
> * src/lime/media/openal/ALC.cpp  [haxe,release]
> * src/openfl/display/DOMRenderer.cpp  [haxe,release]
> * src/__ASSET__flixel_fonts_nokiafc22_ttf.cpp
> * src/openfl/display/Stage3D.cpp  [haxe,release]
> * src/sys/thread/NextEventTime.cpp
> * src/lime/_internal/backend/native/TextEventInfo.cpp
>   Error: Pointer.cpp
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
> 
> Error: ALC.cpp C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
> 
> Error: __ASSET__flixel_fonts_nokiafc22_ttf.cpp C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
> 
> Error: NextEventTime.cpp C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
> 
> Error: DOMRenderer.cpp C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

you forgot to install some of the components in visual studio 2019

**Comment by XavierCodes99** [comment]
I installed the components and installed Haxe 4.1.5 and I got this error

source/Main.hx:11: character 1 : Build failure

**Comment by VMGuy23** [comment]
dont use 4.1.5

**Comment by XavierCodes99** [comment]
Oh yeah I installed the latest version of Haxe but it still didn't compile.

**Comment by SketchEggYT** [comment]
I have this crtdbg.h error as well!
I use Psych Engine but I actually have this **EXACT** error!
