### ISSUE TITLE
Question: wiggleeffect bg stuff

### ISSUE THREAD

**Issue by mentallyobnoxious** [FunkinCrew/Funkin#2058]
I'm trying to import the 'VS Bambi: Strident Crisis' wavy background shaders into Psych Engine using WiggleEffect as a shader.frag file and I need help making the background move like this in the stage's lua file.
![wavythingy](https://user-images.githubusercontent.com/117485689/200110256-fa9b1fba-94a3-4224-ac25-61edb208e8dd.png)

**Comment by Paidyy** [comment]
if you need help with shaders in flixel go to haxeflixel repo
if you need help with lua shaders then go to psych engine repo

but the easiest way to add shaders is:
`[FlxSprite].shader = [FlxShader]`
you can also check this demo's source code

**Comment by mentallyobnoxious** [comment]
> if you need help with shaders in flixel go to haxeflixel repo if you need help with lua shaders then go to psych engine discord server
> 
> but the easiest way to add shaders is: `[FlxSprite].shader = [FlxShader]` you can also check this demo's source code

thanks for the info

**Comment by mentallyobnoxious** [comment]
> if you need help with shaders in flixel go to haxeflixel repo if you need help with lua shaders then go to psych engine discord server
> 
> but the easiest way to add shaders is: `[FlxSprite].shader = [FlxShader]` you can also check this demo's source code

but i meant what would be the wave amplitude, speed and frequency for the other wiggle effect shaders like "DREAMY" or "WAVY"

**Comment by Paidyy** [comment]
WiggleEffect has variables to determine the speed (`wavespeed`) etc.
idk what are you looking for

**Comment by mentallyobnoxious** [comment]
> WiggleEffect has variables to determine the speed (`wavespeed`) etc. idk what are you looking

wait nvm, i see what it is

**Comment by cuti24** [comment]
give me video
;-;

**Comment by Pan010** [comment]
how do you do to test the shaders

**Comment by DendyGG** [comment]
> how do you do to test the shaders

https://haxeflixel.com/demos/BlendModeShaders/
