### ISSUE TITLE
i have a error, what is this?

### ISSUE THREAD

**Issue by cyklusiguess** [FunkinCrew/Funkin#2069]
source/PlayState.hx:224: characters 87-95 : Class<TitleState> has no field soundExt
source/PlayState.hx:898: characters 70-78 : Class<TitleState> has no field soundExt
source/PlayState.hx:916: characters 70-78 : Class<TitleState> has no field soundExt
source/PlayState.hx:933: characters 70-78 : Class<TitleState> has no field soundExt
source/PlayState.hx:952: characters 71-79 : Class<TitleState> has no field soundExt
source/PlayState.hx:990: characters 92-100 : Class<TitleState> has no field soundExt
source/PlayState.hx:720: characters 67-75 : Class<TitleState> has no field soundExt
source/PlayState.hx:817: characters 66-74 : Class<TitleState> has no field soundExt
source/PlayState.hx:742: characters 57-65 : Class<TitleState> has no field soundExt
source/PlayState.hx:973: characters 76-84 : Class<TitleState> has no field soundExt
source/PlayState.hx:1622: characters 65-73 : Class<TitleState> has no field soundExt
source/PlayState.hx:1662: characters 67-75 : Class<TitleState> has no field soundExt
source/PlayState.hx:2043: characters 82-90 : Class<TitleState> has no field soundExt
source/PlayState.hx:2157: characters 80-88 : Class<TitleState> has no field soundExt
source/PlayState.hx:2223: characters 81-89 : Class<TitleState> has no field soundExt

**Comment by ACrazyTown** [comment]
Are you using the vanilla FNF engine? Have you made any changes?

**Comment by alvaroxddd** [comment]
yea i'm using fnf vanilla xd

**Comment by alvaroxddd** [comment]
yeah i'm using vanilla fnf lol

**Comment by ACrazyTown** [comment]
> yea i'm using fnf vanilla xd

Well did you edit the source code? Because the lines referenced in your error here have nothing to do with soundExt

**Comment by alvaroxddd** [comment]
yes, i added a character and then that error appeared

**Comment by FunkoDev** [comment]
Show me the character code.
