### ISSUE TITLE
Compiling help: [BRIEF DESCRIPTION / ERROR MESSAGE OUTPUT]

### ISSUE THREAD

**Issue by Foxy-Studio** [FunkinCrew/Funkin#2075]
source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:78: characters 61-65 : ... For function argument 'child'
Someone can help me with this ?

**Comment by ACrazyTown** [comment]
Revert back to Flixel 4.11 or replace 
```haxe
addChild(new FlxGame(gameWidth, gameHeight, initialState, zoom, framerate, framerate, skipSplash, startFullscreen));
``` 
in `Main.hx` with 
```haxe
addChild(new FlxGame(gameWidth, gameHeight, initialState, #if (flixel < "5.0.0") zoom, #end framerate, framerate, skipSplash, startFullscreen));```

**Comment by Foxy-Studio** [comment]
i think it helped me thanks you so much
