### ISSUE TITLE
i have a lot of errors while compilling

### ISSUE THREAD

**Issue by Foxy-Studio** [FunkinCrew/Funkin#2076]
source/NGio.hx:12: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:13: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:47: characters 62-76 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)

**Comment by ACrazyTown** [comment]
Run `haxelib set newgrounds 1.1.5`

**Comment by Foxy-Studio** [comment]
its fixed
i just have a last one :
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodExprEx.hx:75: characters 5-9 : Expected }
what do i need to do?

**Comment by ACrazyTown** [comment]
> its fixed i just have a last one : C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodExprEx.hx:75: characters 5-9 : Expected } what do i need to do? edit : C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:366: characters 69-73 : polymod.hscript._internal.ErrorEx has no field line

`haxelib set polymod 1.3.1`

**Comment by Baconyy** [comment]
HOW DO I FIX source/NGio.hx:12: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:13: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:47: characters 62-76 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:47: characters 104-127 : Type not found : GetCurrentVersionResult
source/TitleState.hx:61: characters 16-28 : Type not found : APIStuff
source/NGio.hx:96: characters 25-39 : Void -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:96: characters 25-39 : For optional function argument 'callback'
source/NGio.hx:99: characters 30-45 : Void -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:99: characters 30-45 : For optional function argument 'callback'
source/NGio.hx:85: characters 25-34 : Void -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:85: characters 25-34 : For optional function argument 'callback'

**Comment by ACrazyTown** [comment]
> Run haxelib set newgrounds 1.1.5, as the newgrounds haxelib was updated and the Funkin' repo is out of date

**Comment by Baconyy** [comment]
what about 

source/TitleState.hx:61: characters 16-28 : Type not found : APIStuff

**Comment by Baconyy** [comment]
**respond please**

**Comment by Baconyy** [comment]
### a
