### ISSUE TITLE
READ THIS IF YOU HAVE COMPILING ISSUES!

### ISSUE THREAD

**Issue by ACrazyTown** [FunkinCrew/Funkin#2077]
Opening this because a lot of people have similar issues. So it's easier to just redirect them here instead of answering in every issue.

### Issues in Main.hx (`...For optional function argument 'updateFramerate'`)
You're most likely using the latest version of HaxeFlixel. It was recently updated and has some breaking changes, meaning repositories that have not been updated (like Funkin) will not work out of the box.

You can fix this by either:
 - Reverting to HaxeFlixel 4.11.0 by running `haxelib set flixel 4.11.0` in a command prompt.
 - Replacing the `addChild(new FlxGame(...))` line with:
     ```haxe
    addChild(new FlxGame(gameWidth, gameHeight, initialState, #if (flixel < "5.0.0") zoom, #end framerate, framerate, skipSplash, startFullscreen));
    ```

### Errors regarding `newgrounds`/`NGio.hx`
The `newgrounds` haxelib was updated, and the Funkin' repo wasn't meaning it's out of date.

Simply just revert newgrounds to a compatible version: `haxelib set newgrounds 1.1.5`

### Errors regarding `polymod`
Just like newgrounds, polymod got updated and the Funkin' repo is out of date.

Revert the polymod to a compatible version: `haxelib set polymod 1.3.1`

### `Error: Could not automatically setup MSVC`

You need to install MSVC and Windows 10 SDK.
To do this, open Visual Studio Installer and click "Modify" on your Visual Studio install.

Select "Individual components" and select the following:
- MSVC C++ x64/x86 build tools (Latest)
- Windows 10 SDK (latest)

### Issues with `flixel-addons` and Flixel 5.0+

Update flixel-addons to the latest version:
`haxelib update flixel-addons`

### Errors with `ModMenu.hx`
Make sure your `hscript` is up to date and comment out line 113 in `ModMenu.hx`.
If you don't know to do that, just add `//` before the line.

#
Leave more errors (and if possible solutions) in the replies, and I'll update this issue.

Last updated: February 1st 2023 (FNF Week7 source code)

**Comment by Foxy-Studio** [comment]
source/NGio.hx:47: characters 34-57 : io.newgrounds.components.AppComponent has no field GetCurrentVersionResult
source/NGio.hx:98: characters 3-7 : Null is not a value
source/NGio.hx:102: characters 3-7 : Null is not a value
source/NGio.hx:86: characters 5-9 : Null is not a value
but what I need to do on that?
it always say this

**Comment by ACrazyTown** [comment]
> source/NGio.hx:47: characters 34-57 : io.newgrounds.components.AppComponent has no field GetCurrentVersionResult source/NGio.hx:98: characters 3-7 : Null is not a value source/NGio.hx:102: characters 3-7 : Null is not a value source/NGio.hx:86: characters 5-9 : Null is not a value but what I need to do on that? it always say this

Have you reverted newgrounds? What version of Kade Engine are you using?

**Comment by CatMaster8232** [comment]
It's still giving me the "Could not automatically setup MSVC" error even though I have installed Windows 10 SDK (version 10.0.20348.0) and MSVC (version v14.29-16.11).

**Comment by XavierCodes99** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

**Comment by ACrazyTown** [comment]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\yvals.h(12): fatal error C1083: Cannot open include file: **'crtdbg.h'**: No such file or directory

Did you install Visual Studio 2019 and the individual components?

**Comment by perry389** [comment]
I tried the main.hx problem, but it doesn't work.
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
E:\Download\FNF-PsychEngine-perry-origin\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

**Comment by ACrazyTown** [comment]
> I tried the main.hx problem, but it doesn't work. source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead E:\Download\FNF-PsychEngine-perry-origin\export\release\windows\obj>setlocal enabledelayedexpansion Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

It did work, you're having a different issue. You need to install MSVC as mentioned in my original post

**Comment by AlexRoblox24** [comment]
Can anyone help me this 

source/Main.hx:78: characters 59-63 : Float should be Int
source/Main.hx:78: characters 59-63 : For optional function argument 'updateFramerate'
source/PlayState.hx:4656: characters 30-31 : Warning : This pattern is unused

**Comment by MemeHovy** [comment]
> Can anyone help me this
> 
> source/Main.hx:78: characters 59-63 : Float should be Int source/Main.hx:78: characters 59-63 : For optional function argument 'updateFramerate' source/PlayState.hx:4656: characters 30-31 : Warning : This pattern is unused

use flixel 4.11.0 and flixel-addons 2.11.0

**Comment by XavierCodes99** [comment]
Creating C:/Users/LENOVO SLIM 3/Desktop/Funkin-master/export/release/windows/obj/obj/msvc64-nc/__pch/haxe/hxcpp.pch...
'cl.exe' is not recognized as an internal or external command,
operable program or batch file.
Error: Could not create PCH

**Comment by XavierCodes99** [comment]
```
Creating C:/Users/LENOVO SLIM 3/Desktop/Funkin-master/export/release/windows/obj/obj/msvc1964-nc/__pch/haxe/hxcpp.pch...
hxcpp.cpp
C:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include\hxcpp.h(17): fatal error C1083: Cannot open include file: 'typeinfo': No such file or directory
Error: Could not create PCH
```

**Comment by ShotgunJ0ker** [comment]
`source/NGio.hx:64: characters 13-25 : Type not found : APIStuff
source/NGio.hx:106: characters 26-41 : Type not found : APIStuff`

I for some reason received this after attempting to compile after checking everything on this post that they works, this just keeps happening
