### ISSUE TITLE
so everytime i try compilling it create a error

### ISSUE THREAD

**Issue by Foxy-Studio** [FunkinCrew/Funkin#2078]
source/NGio.hx:13: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:47: characters 34-57 : io.newgrounds.components.AppComponent has no field GetCurrentVersionResult
source/NGio.hx:47: characters 110-133 : Type not found : GetCurrentVersionResult
source/NGio.hx:98: characters 3-7 : Null is not a value
source/NGio.hx:102: characters 3-7 : Null is not a value
source/NGio.hx:86: characters 5-9 : Null is not a value
source/NGio.hx:87: characters 25-34 : Void -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:87: characters 25-34 : For optional function argument 'callback'
yea i use kade engine

**Comment by ACrazyTown** [comment]
Look at #2077
