### ISSUE TITLE
Bug Report: Why everytime i compile the game and start it appears this window error??

### ISSUE THREAD

**Issue by Lokitot** [FunkinCrew/Funkin#2090]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [X] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
v0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
no
## Please describe your issue. Provide extensive detail and images if possible.
Every time i compile the game, it window appears and crash the game:

![Captura de pantalla 2022-12-20 142551](https://user-images.githubusercontent.com/99614368/208678399-41677e70-524e-4782-ae7c-ed391651d7dc.png)

**Comment by Lokitot** [comment]
before you ask, no, i didn't modify the source code

**Comment by Lokitot** [comment]
also, got this error on the visual studio: 

AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154
AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006
AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154
AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006

**Comment by Lokitot** [comment]
> > also, got this error on the visual studio:
> > AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006
> 
> why are you compiling this in visual studio

i always compile the game in visual studio

**Comment by Paidyy** [comment]
> > > also, got this error on the visual studio:
> > > AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006
> > 
> > 
> > why are you compiling this in visual studio
> 
> i always compile the game in visual studio

use visual studio code instead, i don't think there's support for haxe in visual studio

**Comment by Lokitot** [comment]
> > > > also, got this error on the visual studio:
> > > > AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006
> > > 
> > > 
> > > why are you compiling this in visual studio
> > 
> > 
> > i always compile the game in visual studio
> 
> use visual studio code instead, i don't think there's support for haxe in visual studio

BRO I COMPILE THE GAME ON VISUAL STUDIO CODE

**Comment by Paidyy** [comment]
> > > > > also, got this error on the visual studio:
> > > > > AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006
> > > > 
> > > > 
> > > > why are you compiling this in visual studio
> > > 
> > > 
> > > i always compile the game in visual studio
> > 
> > 
> > use visual studio code instead, i don't think there's support for haxe in visual studio
> 
> BRO I COMPILE THE GAME ON VISUAL STUDIO CODE

well they're different ide's, also did you compiled it with lime command?

**Comment by Lokitot** [comment]
> > > > > > also, got this error on the visual studio:
> > > > > > AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006
> > > > > 
> > > > > 
> > > > > why are you compiling this in visual studio
> > > > 
> > > > 
> > > > i always compile the game in visual studio
> > > 
> > > 
> > > use visual studio code instead, i don't think there's support for haxe in visual studio
> > 
> > 
> > BRO I COMPILE THE GAME ON VISUAL STUDIO CODE
> 
> well they're different ide's, also did you compiled it with lime command?
> 
> if yes then try reinstalling Visual Studio (not Visual Studio Code), and if that also will not work, try reinstalling the whole haxe and haxelibs

i used lime test windows   lime build windows  lime build windows -debug and nothing lol

**Comment by Paidyy** [comment]
> > > > > > > also, got this error on the visual studio:
> > > > > > > AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154 AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006
> > > > > > 
> > > > > > 
> > > > > > why are you compiling this in visual studio
> > > > > 
> > > > > 
> > > > > i always compile the game in visual studio
> > > > 
> > > > 
> > > > use visual studio code instead, i don't think there's support for haxe in visual studio
> > > 
> > > 
> > > BRO I COMPILE THE GAME ON VISUAL STUDIO CODE
> > 
> > 
> > well they're different ide's, also did you compiled it with lime command?
> > if yes then try reinstalling Visual Studio (not Visual Studio Code), and if that also will not work, try reinstalling the whole haxe and haxelibs
> 
> i used lime test windows lime build windows lime build windows -debug and nothing lol

well
> try reinstalling Visual Studio (not Visual Studio Code), and if that also will not work, try reinstalling the whole haxe and haxelibs

**Comment by TheKitBoi** [comment]
> i used lime test windows lime build windows lime build windows -debug and nothing lol

it supposed to be lime build windows or lime test windows
