### ISSUE TITLE
Bug Report: FNF stuck on black screen

### ISSUE THREAD

**Issue by guy-withThe-hat** [FunkinCrew/Funkin#2091]
Whenever I load FNF from the newgrounds website, I get a black screen with only FPS showing. The game loads like it normally does, but the main menu never shows up. I only see a black screen with FPS.

![bug](https://user-images.githubusercontent.com/43190491/208950371-bac31cd6-1e0e-4904-bd14-4e4f8283c857.png)

tried loading the game from multiple websites, getting the same result. the only website it does work is itch.
Probably an issue with my computer, but I don't know what to do. Could be an issue with week 7.

(itch)
![nobug](https://user-images.githubusercontent.com/43190491/208951328-5c4c308a-96a8-4392-95f7-941f64074965.png)

(some random website) (https://fnfonline.co/)
![randomwebsite](https://user-images.githubusercontent.com/43190491/208951677-7b24ad38-cb9a-4671-bf47-5fc76b946efd.png)

I tried turning off ad blocker, tried windows update, tried refreshing page, and tried using VPN (it's not a firewall issue for sure).

did not download flash player replacement, although I don't think it runs on flash player.

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [x] Firefox
- [ ] Safari

Here's every message in the console from newgrounds:

Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. 3 770371:724:2412
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. Funkin.js:2057:104
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. Funkin.js:3204:253
Use of the motion sensor is deprecated. Funkin.js:91:457
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
downloadable font: gasp: Changed the version number to 1 (font-family: "VCR OSD Mono" style:normal weight:400 stretch:100 src index:1) source: https://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/assets/fonts/vcr.woff
downloadable font: OS/2: Bad usWidthClass: 0, changing it to 1 (font-family: "Nokia Cellphone FC Small" style:normal weight:400 stretch:100 src index:1) source: https://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/flixel/fonts/nokiafc22.woff
XML Parsing Error: not well-formed
Location: https://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/assets/images/alphabet.xml?9553
Line Number 89, Column 20: alphabet.xml:89:20
DataCloneError: URL object could not be cloned. get-iframes.js:9
XML Parsing Error: not well-formed
Location: https://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/assets/images/fonts/bold.xml?9553
Line Number 17, Column 21: bold.xml:17:21
XML Parsing Error: not well-formed
Location: https://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/assets/images/fonts/default.xml?9553
Line Number 17, Column 21: default.xml:17:21
source/ui/PreferencesMenu.hx:167: set preference! 7 Funkin.js:719:495
source/NGio.hx:70: connecting to newgrounds Funkin.js:719:495
source/NGio.hx:83: found web session id Funkin.js:719:495
source/NGio.hx:113: attempting login Funkin.js:719:495
Partitioned cookie or storage access was provided to “https://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/?ngio_session_id=38479361.7388dda7a23a36ab55ef53bd4da4d7a09b81580dd3bb86&NewgroundsAPI_PublisherID=1&NewgroundsAPI_SandboxID=63a32d73667e2&NewgroundsAPI_SessionID=8as27sFEPDLFTKmbEjeZb92510a2e0ce953c433983f2db7869087c7d5fb7wAXz&NewgroundsAPI_UserName=Crisis-in-Progress&NewgroundsAPI_UserID=14155944&ng_username=Crisis-in-Progress” because it is loaded in the third-party context and dynamic state partitioning is enabled.
source/NGio.hx:165: logged in! user:Crisis-in-Progress Funkin.js:719:495
source/NGio.hx:223: shoulda got score by NOW! Funkin.js:719:495
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. Funkin.js:3167:343
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! 770371

Here's every message from the console from itch:

Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1hZ2UvNzkyNzc4LzQ1MjMzNTkucG5n/794x1000/mFua79.png mFua79.png
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1hZ2UvNzkyNzc4LzQ1MjMzNjEucG5n/794x1000/DKTKI1.png DKTKI1.png
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1hZ2UvNzkyNzc4LzQ1MjMzNTgucG5n/794x1000/vPqmMH.png vPqmMH.png
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1hZ2UvNzkyNzc4LzQ1MjMzNjAucG5n/794x1000/dH47mv.png dH47mv.png
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1hZ2UvNzkyNzc4LzQ5MDAxODMuanBn/794x1000/nAvA3K.jpg nAvA3K.jpg
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1hZ2UvNzkyNzc4LzQ5MDAxODYuanBn/794x1000/mMNTVM.jpg mMNTVM.jpg
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://www.google-analytics.com/analytics.js funkin:3:70
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzEwODMyNDMyLnBuZw==/25x25%23/7IHWdJ.png lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzEwODMyMjk2LmpwZw==/25x25%23/bakf7J.jpg lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzc4NzQyNjEucG5n/25x25%23/lrOraw.png lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzEwNjI5OTQxLnBuZw==/25x25%23/yrooG4.png lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzk5NzgzMTgucG5n/25x25%23/N3QWUQ.png lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzEwNzk3NjM3LmpwZw==/25x25%23/QW8NFF.jpg lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzkzNjM2MzMuanBn/25x25%23/VbtLD%2B.jpg lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzEwNzU0MTk0LnBuZw==/25x25%23/pd9zSz.png lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzk4MzIzODAuanBn/25x25%23/AnwEsq.jpg lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzEwODI4MDE0LmpwZw==/25x25%23/e9wK8N.jpg lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://i.ytimg.com/vi/VAGIFfA0Sb8/hqdefault.jpg lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzg5NDgxMDQucG5n/25x25%23/LfkFZS.png lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzk4MzE3OTMucG5n/25x25%23/Sl%2F9fO.png lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzEwMzg3Mzk3LnBuZw==/25x25%23/XsR4eU.png lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzEwNjE0OTA0LnBuZw==/25x25%23/2f1%2B9d.png lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzEwNTk0ODQxLmdpZg==/25x25%23/ipw8do.gif lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://i.ytimg.com/vi/pBL6xdNQJ5Q/hqdefault.jpg lib.js:2:51681
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://img.itch.zone/aW1nLzYxMDMzMzgucG5n/25x25%23/XM%2FenG.png lib.js:2:51681
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”. funkin:1:1
Some cookies are misusing the recommended “SameSite“ attribute 3
Loading failed for the <script> with source “https://static.doubleclick.net/instream/ad_status.js”. HMNKUo3CCpU:1:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at data:text/plain;base64,Cg==. (Reason: CORS request not http).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed). Status code: (null).
Partitioned cookie or storage access was provided to “https://www.youtube.com/embed/HMNKUo3CCpU” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Feature Policy: Skipping unsupported feature name “autoplay”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “midi”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “monetization”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “gyroscope”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “accelerometer”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “xr”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “autoplay”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “midi”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “monetization”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “gyroscope”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “accelerometer”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “xr”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “autoplay”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “midi”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “monetization”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “gyroscope”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “accelerometer”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “xr”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. lib.js:2:50992
Use of the motion sensor is deprecated. Funkin.js:91:11
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
XML Parsing Error: not well-formed
Location: https://v6p9d9t4.ssl.hwcdn.net/html/2876359-359162/assets/images/alphabet.xml?884968
Line Number 89, Column 20: alphabet.xml:89:20
DataCloneError: URL object could not be cloned. 2 get-iframes.js:9
downloadable font: OS/2: Bad usWidthClass: 0, changing it to 1 (font-family: "Nokia Cellphone FC Small" style:normal weight:400 stretch:100 src index:1) source: https://v6p9d9t4.ssl.hwcdn.net/html/2876359-359162/flixel/fonts/nokiafc22.woff
downloadable font: gasp: Changed the version number to 1 (font-family: "VCR OSD Mono" style:normal weight:400 stretch:100 src index:1) source: https://v6p9d9t4.ssl.hwcdn.net/html/2876359-359162/assets/fonts/vcr.woff
Partitioned cookie or storage access was provided to “https://v6p9d9t4.ssl.hwcdn.net/html/2876359-359162/index.html” because it is loaded in the third-party context and dynamic state partitioning is enabled.
source/NGio.hx:38: INIT NOLOGIN Funkin.js:684:319
source/NGio.hx:51: CURRENT NG VERSION: v0.2.7.1 Funkin.js:684:319
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.google.com/log?format=json&hasfast=true&authuser=0. (Reason: CORS request did not succeed). Status code: (null).

**Comment by FranzGsmer** [comment]
maybe try google chrome it works
