### ISSUE TITLE
Keeping dying without no reason

### ISSUE THREAD

**Issue by VegethYT** [FunkinCrew/Funkin#2093]
Hello, I've been havng this problem since I got my new pc. Basically everytime I play a song and when 23 seconds last until the song ends I die for no reason. I do have the R key disabled so that's not the case. This bug seems to happen on almost any engine. In Vanilla and Kade it seems to just go into the menu and give me score while in Psych I just die. I tried deleting the folders in AppData but still nothing.

**Comment by VegethYT** [comment]
I do actually have a video of the bug. Here's the link if you wanna see it: https://drive.google.com/file/d/1HoqaIItijwDRQk64zCZIROhzSn-8wkHh/view?usp=share_link The video  lags a bit but it's just some issues with my recording software.

**Comment by CodeKid0** [comment]
@VegethYT Could you provide more info about your pc? 
- Operating system (with build number)
- Your CPU (processor)
- RAM amount
- Graphics Card
- Version of the game you're currently running

and last, can you try to run the game with your command line (cmd, terminal) and post the logs?
It would be great if you could post the logs using a paste service (pastebin, hatebin) so its a little bit more readable

**Comment by VegethYT** [comment]
> @VegethYT Could you provide more info about your pc?
> 
> * Operating system (with build number)
> * Your CPU (processor)
> * RAM amount
> * Graphics Card
> * Version of the game you're currently running
> 
> and last, can you try to run the game with your command line (cmd, terminal) and post the logs? It would be great if you could post the logs using a paste service (pastebin, hatebin) so its a little bit more readable

* My Pc is a Purism Librem 15 v3
* My Operating System is Windows 10 22H2 19045.2486
* My CPU is Intel Core i7-6500U 
* My Ram is 8GB DDR4
* My Graphic Card is Intel HD Graphics 520
* The version is the one found in Itch.io but I also compiled the Github Version

Here's the log https://pastebin.com/evkqpPf7 (Note that in the OG Game, it seems to bring me in the main menu without finishing the song on time but still gives me a score. In Kade Engine it's the same thing while in Psych Engine it just dies. I tested this with the OG Game tho).

**Comment by CodeKid0** [comment]
@VegethYT This looks like a very unusual bug. 
Do you have any antivirus software that may be interfering in the game files?
If you can, could you create a live Linux (Ubuntu/Mint) USB, boot into it and launch Funkin' from there? (To detect if it's not a driver/OS/software issue)
Ffc, since it's a live usb there's no need to install it. There are many great tutorials to get a live linux usb if you don't know how to do it.

**Comment by VegethYT** [comment]
> @VegethYT This looks like a very unusual bug. Do you have any antivirus software that may be interfering in the game files? If you can, could you create a live Linux (Ubuntu/Mint) USB, boot into it and launch Funkin' from there? (To detect if it's not a driver/OS/software issue) Ofc, since it's a live usb there's no need to install it. There are many great tutorials to get a live linux usb if you don't know how to do it.

I don't have any antivirus software. I just have the basic Windows Defender. I'm not sure about making a linux flashable USB because I don't have anything to save my files and I can't loose them because I've got lots of work. I could try I just have to get an external hard disk for my files.
