### ISSUE TITLE
What happened i JUST WANT TO FREAKING COMPILE WITHOUT A HUNDRED THOUSAND ERRORS AAAAAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by Baconyy** [FunkinCrew/Funkin#2096]
what about 

source/TitleState.hx:61: characters 16-28 : Type not found : APIStuff

_Originally posted by @Baconyy in https://github.com/FunkinCrew/Funkin/issues/2076#issuecomment-1376586558_

**Comment by Baconyy** [comment]
THANKS MY BOI ALSO I HAVE ONE MORE THING:
`C:\Users\edoub\Downloads\BaconEngine0.05alpha\Funkin-0.2.7.1\export\release\windows\obj>setlocal` enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup  MSVC

**Comment by Baconyy** [comment]
well it might not be the last thing

**Comment by Snirozu** [comment]
https://github.com/FunkinCrew/Funkin#compiling-game

**Comment by ACrazyTown** [comment]
> THANKS MY BOI ALSO I HAVE ONE MORE THING: `C:\Users\edoub\Downloads\BaconEngine0.05alpha\Funkin-0.2.7.1\export\release\windows\obj>setlocal` enabledelayedexpansion Warning: Could not find Visual Studio 2017 VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC

https://github.com/FunkinCrew/Funkin/issues/2077
