### ISSUE TITLE
Question: tankTalkSong?

### ISSUE THREAD

**Issue by AbnormalPoof** [FunkinCrew/Funkin#2105]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

## What is your question?

Remember when Week 7 first came out?
Story Mode was broken, right?
Months after it came out, I decided to check the code. I saw that the ughCutscene function was not playing a video like Guns and Stress, but rather having it play ingame.
I also noticed that it tried loading a spritesheet called “tankTalkSong” in a folder named “cutsceneStuff” (which does not exist in the assets iirc).
My guess is that the game crashed since the spritesheet didn’t exist. (The sheet is tankman’s ugh cutscene animation… talking…. thing…)

So I’m wondering if that sheet would ever be released publicly. Wouldn’t be particularly useful since we have texture atlases, but it would at least be fun to have.

^ I hope this at least makes sense lol

**Comment by trayfellow** [comment]
the game crashed cause it tried to load a mp4 in desktop which doesnt work unless u use something like hxcodec, the tanktalksong code is commented out probably cause the cutscenes were meant to be realtime at one point but scrapped, btw u can find the unused sheets in the wipcutsceneshit folder inside the art folder of the source code

**Comment by AbnormalPoof** [comment]
Oh cool, ty!!!!
