### ISSUE TITLE
Compiling help: Game crashes when opening it

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/Funkin#2106]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
The game crashes when opening the game, no crash log or error message in the terminal, nothing.

**Comment by biomseed** [comment]
Update: When I run it with the debug configuration, it says "Null Object Reference" and says this in terminal:
`C:/Users/bioms/.vscode/extensions/vshaxe.hxcpp-debugger-1.2.4/hxcpp-debug-server/./hxcpp/debug/jsonrpc/Server.hx:86: Debug Server Started:
C:/Users/bioms/.vscode/extensions/vshaxe.hxcpp-debugger-1.2.4/hxcpp-debug-server/./hxcpp/debug/jsonrpc/Server.hx:592: Failed to connect to vsc debugger server at 127.0.0.1:6972
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 26
Called from ApplicationMain::create ApplicationMain.hx line 135
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleApplicationEvent lime/_internal/backend/native/NativeApplication.hx line 175
Called from lime.app._Event_Int_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from lime.system.ThreadPool::__update lime/system/ThreadPool.hx line 199
Called from lime.app._Event_Dynamic_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from lime._internal.backend.native.NativeHTTPRequest::localThreadPool_onComplete lime/_internal/backend/native/NativeHTTPRequest.hx line 450
Called from lime.app.Promise_haxe_io_Bytes::complete lime/app/Promise.hx line 108
Called from lime.net._HTTPRequest_Bytes::load lime/net/HTTPRequest.hx line 114
Called from lime.app.Promise::complete lime/app/Promise.hx line 108
Called from lime.app.Future::then lime/app/Future.hx line 282
Called from lime.app.Future::onComplete lime/app/Future.hx line 127
Called from lime.app.Promise::complete lime/app/Promise.hx line 108
Called from lime.utils.Assets::loadLibrary lime/utils/Assets.hx line 476
Called from lime.app.Promise_lime_utils_AssetLibrary::completeWith lime/app/Promise.hx line 126
Called from lime.app.Future::onComplete lime/app/Future.hx line 127
Called from lime.app.Promise_lime_utils_AssetLibrary::complete lime/app/Promise.hx line 108
Called from lime.utils.Preloader::updateProgress lime/utils/Preloader.hx line 289
Called from lime.utils.Preloader::loadedAssetLibrary lime/utils/Preloader.hx line 204
Called from lime.utils.Preloader::updateProgress lime/utils/Preloader.hx line 309
Called from lime.utils.Preloader::start lime/utils/Preloader.hx line 220
Called from lime.app._Event_Void_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from ApplicationMain::create ApplicationMain.hx line 116
Called from openfl.display.Preloader::start openfl/display/Preloader.hx line 61
Called from lime.app._Event_Void_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from ApplicationMain::create ApplicationMain.hx line 119
Called from ApplicationMain::start ApplicationMain.hx line 169
Called from Main::main Main.hx line 36
Called from openfl.display.DisplayObjectContainer::addChild openfl/display/DisplayObjectContainer.hx line 155
Called from openfl.display.DisplayObjectContainer::addChildAt openfl/display/DisplayObjectContainer.hx line 267
Called from openfl.display.DisplayObject::__dispatchWithCapture openfl/display/DisplayObject.hx line 1478
Called from openfl.display.DisplayObject::__dispatchEvent openfl/display/DisplayObject.hx line 1417
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from Main::init Main.hx line 60
Called from Main::setupGame Main.hx line 87
Called from openfl.display.DisplayObjectContainer::addChild openfl/display/DisplayObjectContainer.hx line 155
Called from openfl.display.DisplayObjectContainer::addChildAt openfl/display/DisplayObjectContainer.hx line 267
Called from openfl.display.DisplayObject::__dispatchWithCapture openfl/display/DisplayObject.hx line 1478
Called from openfl.display.DisplayObject::__dispatchEvent openfl/display/DisplayObject.hx line 1417
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::create flixel/FlxGame.hx line 360
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 637
Called from TitleState::create TitleState.hx line 73
Called from polymod.Polymod::init polymod/Polymod.hx line 252
Called from polymod.backends.PolymodAssets::init polymod/backends/PolymodAssets.hx line 133
Called from polymod.backends.LimeBackend::init polymod/backends/LimeBackend.hx line 127
Critical Error: Uncatchable Throw: Null Object Reference`

**Comment by biomseed** [comment]
Help ninjamuffin your thing is broken

**Comment by biomseed** [comment]
> update polymod. I help so many people who blame the repo owners when its the user who doesnt have updated libraries.

alr

**Comment by TmixRPG** [comment]
same problem for me

**Comment by biomseed** [comment]
Alright, now i'm getting somewhere, the git version of polymod is outdated so you install the haxelib version, `haxelib install polymod', and now i get this

![image](https://user-images.githubusercontent.com/73907153/216118471-5dac3165-1b69-4849-a61c-8c38c3cca911.png)

**Comment by Username2120** [comment]
for this i commented out that line to fix it. also make sure your hscript is up to date.

**Comment by biomseed** [comment]
#2109

**Comment by TheRealJake12** [comment]
ok actually, dont comment out the polymod scan. Just remove the MOD_ROOT and itll fix that. I'll send my own version that fixes these things.
