### ISSUE TITLE
Game instantly crashes

### ISSUE THREAD

**Issue by Rev2-Git** [FunkinCrew/Funkin#2107]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] Windows
- [ ] Mac
- [ ] Linux
- [x] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

The game instantly crashes upon compile/open without an error message or other error indicator. I am unsure of what causes this.

**Comment by biomseed** [comment]
Use 'lime build [platform] -debug' and see what I got

**Comment by MemeHovy** [comment]
@Rev2-Git https://github.com/FunkinCrew/Funkin/issues/2109
