### ISSUE TITLE
[2023/01/31] NOTICE REGARDING WEEK 7 SOURCE CODE RELEASE

### ISSUE THREAD

**Issue by EliteMasterEric** [FunkinCrew/Funkin#2108]
The source code is provided as-is and we will be providing no technical support for it.

The code may not work for you if you are using a bad dependency version, and it definitely won't work if you're trying to target desktop because it can't play the videos there.

Note also that this code is not distributed under any permissive license right now, this will be fixed soon.

If you want to play Week 7 in a stable way, go [to Newgrounds](https://www.newgrounds.com/portal/view/770371) or [to Psych Engine](https://github.com/ShadowMario/FNF-PsychEngine/releases/tag/0.6.3).

**Comment by alvaroxddd** [comment]
a

**Comment by trayfellow** [comment]
this source code is so realistic i can feel the week 7 coming inside of me

**Comment by BushTrain460615** [comment]
> Did you guys forget to remove the API keys?
> ![image](https://user-images.githubusercontent.com/47027981/216087383-6ef70f1c-1cf7-4dd3-87ea-21cbdfc6915a.png)

that is a dummy game that he made in #146 for the game not to crash at startup

**Comment by MemeHovy** [comment]
real
