### ISSUE TITLE
CHECK THIS ISSUE IF THE GAME CRASHES WHEN YOU OPEN IT!

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/Funkin#2109]
First, do what it says in #2077
Now, install the latest haxelib version of polymod, like `haxelib install polymod` and use it
After that, go to line 133 in source/ui/modmenu, the one that says `modList = Polymod.scan(MOD_PATH);` and replace it with `modList = Polymod.scan({modRoot: MOD_PATH});` or just comment it out.  Now the game is ready to compile.

**Comment by AltronMaxX** [comment]
It also can be fixed if you replace ``modList = Polymod.scan(MOD_PATH);`` to ``modList = Polymod.scan({modRoot: MOD_PATH});``

**Comment by biomseed** [comment]
> modList = Polymod.scan({modRoot: MOD_PATH});

Alright, i'll replace it with that

**Comment by biomseed** [comment]
> It also can be fixed if you replace `modList = Polymod.scan(MOD_PATH);` to `modList = Polymod.scan({modRoot: MOD_PATH});`

alright, i'll replace it with that

**Comment by AlvarroPewz24** [comment]
thx

**Comment by imdumlol** [comment]
source/ui/ModMenu.hx:113: characters 26-45 : { modRoot : String } should be String
source/ui/ModMenu.hx:113: characters 26-45 : ... For function argument 'modRoot'

**Comment by imdumlol** [comment]
i did it works

**Comment by imdumlol** [comment]
but now my screen freezes when i press enter

**Comment by imdumlol** [comment]
io/newgrounds/Call.hx:198: [Newgrounds API] :: Error: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
