### ISSUE TITLE
How do i enable Week 7 Video Cutscenes on Desktop

### ISSUE THREAD

**Issue by qdartheawesomeman** [FunkinCrew/Funkin#2115]
### Discussed in https://github.com/FunkinCrew/Funkin/discussions/2114

<div type='discussions-op-text'>

<sup>Originally posted by **qdartheawesomeman** February  3, 2023</sup>
I Started to Compile the FNF WEEK 7 Source Code When i started Story Mode The Cutscene didn't begin, It was Pitch Black. But the Healthbar and icons are still there. Is there a way to Fix it?</div>

**Comment by biomseed** [comment]
> ### Discussed in #2114
> Originally posted by **qdartheawesomeman** February 3, 2023 I Started to Compile the FNF WEEK 7 Source Code When i started Story Mode The Cutscene didn't begin, It was Pitch Black. But the Healthbar and icons are still there. Is there a way to Fix it?

Week 7 cutscenes use something that doesn't work on pc, they aren't videos they are animated in game, so you would have to change the cutscene code to use videos

**Comment by qdartheawesomeman** [comment]
ok. thanks for the help

**Comment by biomseed** [comment]
> ok. thanks for the help. but there's only one problem. I can't find the Cutscene Code. Where could i find it?

Try to look for something in PlayState.hx that triggers in ugh, guns, and stress if those songs are opened in story mode

**Comment by qdartheawesomeman** [comment]
ok i will try something. any tips to change the sprite cutscene to video?

**Comment by biomseed** [comment]
> ok i will try something. any tips to change the sprite cutscene to video?

I don't know how displaying video works, but I do know that [Codename Engine](https://github.com/YoshiCrafter29/CodenameEngine) has video versions of the cutscenes in assets/videos

**Comment by qdartheawesomeman** [comment]
thanks man!
