### ISSUE TITLE
Unfamiliar Source Code 

### ISSUE THREAD

**Issue by RevenEMortalios** [FunkinCrew/Funkin#2119]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

Every Time I download the source code It doesn't even look moderately the same to the source code shown. I'm trying to add my own song but I can't when the entire source code looks way different. Could you by chance tell me how I get the right one?

**Comment by MemeHovy** [comment]
.___.
because this is the vanilla source code

**Comment by MemeHovy** [comment]
you're looking at a modded engine

**Comment by RevenEMortalios** [comment]
I tried a lot of places to get the right source code, even the link it provided that took you to the game download. Yet I kept getting the same thing

**Comment by MemeHovy** [comment]
this is the vanilla source code

this is modded below:
https://github.com/ShadowMario/FNF-PsychEngine

**Comment by RevenEMortalios** [comment]
so, I got the source code but idk how to launch the game

**Comment by MemeHovy** [comment]
you have to compile it first

**Comment by HackersLOLwskasdhq3ew** [comment]
@RevenEMortalios 

Run one of these in the terminal, please.

Test Debug:
```Lime Test Windows -debug```
Test Normal:
```Lime Test Windows```

Normal Build:
```Lime Build Windows -release```
