### ISSUE TITLE
why do lime test windows not work???

### ISSUE THREAD

**Issue by ROCK201888** [FunkinCrew/Funkin#2125]
![image](https://user-images.githubusercontent.com/113576910/221409325-502d7163-a667-4436-885d-477e14188418.png)
why do it not work??????

**Comment by MemeHovy** [comment]
for 1, use flixel 4.11.0 and flixel addons 2.11.0 and use an older version of newgrounds

**Comment by biomseed** [comment]
#2109

**Comment by MemeHovy** [comment]
> #2109

ok I forgot what the issue for that was so that above was my excuse thanks

**Comment by ROCK201888** [comment]
![image](https://user-images.githubusercontent.com/113576910/221521133-56008bb0-f1a8-461c-bc35-c9679771985c.png)
still not work

**Comment by ROCK201888** [comment]
help!

**Comment by Wenzel0** [comment]
broo what's this error

addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:102: characters 65-78 : error: io.newgrounds.LoginOutcome should be io.newgrounds.objects.Error
source/NGio.hx:102: characters 65-78 : ... have: (io.newgrounds.objects.Error) -> ...
source/NGio.hx:102: characters 65-78 : ... want: (io.newgrounds.LoginOutcome) -> ...
source/NGio.hx:102: characters 65-78 : ... For optional function argument 'callback'

**Comment by biomseed** [comment]
Why did I get a notification for this today out of nowhere? You still need help?

**Comment by ROCK201888** [comment]
im done month ago but a new error come out
