### ISSUE TITLE
Compiling help: Trying to compile fnf without admin

### ISSUE THREAD

**Issue by Ayumi08** [FunkinCrew/Funkin#2126]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

I installed the binary version of Haxe 4.1.5 but when I navigate to the folder to download HaxeFlixel, I get a System Error that says: 

The code execution cannot proceed because neko.dll was not found. Reinstalling the program may fix this problem. 

This error shows every time I try to open and use haxelib.exe
This error also shows when I use Haxe 4.2.4.

Is there no way to get the file neko.dll without using the executable?

**Comment by MemeHovy** [comment]
🤦🏻‍♂️
you're supposed to use haxe 4.2.5 with the windows installer

**Comment by Ayumi08** [comment]
Oh i didnt know that lemme try it thanks

**Comment by MemeHovy** [comment]
you're welcome

**Comment by Ayumi08** [comment]
I get the same error :(

**Comment by Ayumi08** [comment]
![image](https://user-images.githubusercontent.com/79187097/221438295-dab6c390-b5a7-476a-aed8-e141d42c20cc.png)

**Comment by MemeHovy** [comment]
hm, maybe look at this? https://github.com/FunkinCrew/Funkin/issues/2109

**Comment by Ayumi08** [comment]
:( um i checked both things they seem to have to do with haxelib.exe already working

**Comment by Ayumi08** [comment]
Fixed, neko.dll is a file that gets automatically downloaded from the installer. I will need to manually install the file myself 

https://github.com/HaxeFoundation/haxe/issues/6130
