### ISSUE TITLE
Compiling help: [using linux to compile to html5/ ]

### ISSUE THREAD

**Issue by fnfgo** [FunkinCrew/Funkin#2127]
- [ ] Windows
- [ ] Mac
- [ ] Linux
- [x ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
source/Intro.hx:4: characters 8-22 : You cannot access the sys package while targeting js (for sys.FileSystem)
source/Main.hx:17: characters 37-42 : ... referenced here when run lime build html5

**Comment by Justine101213k** [comment]
hmm i think you have to replace this code in Intro.hx
```haxe
#if sys
import sys.FileSystem;
#end
```

so about the Main.hx error is I dont know

**Comment by ZoologistArctic** [comment]
if im correct "... referenced here" is related to the Intro.hx error, so that code Justine put should fix that aswell.
