### ISSUE TITLE
Compiling help: Errors in code

### ISSUE THREAD

**Issue by andersonpem** [FunkinCrew/Funkin#2128]
- [ ] Windows
- [ ] Mac
- [X] Linux (on Docker)
- [ ] HTML5

Ubuntu 22.04 LTS with Linux Kernel 6.1 (AMD64)

So, I'm offloading the load of compiling the game to Docker, because Haxe pollutes my entire system. I created a docker container to perform this task.

https://github.com/andersonpem/FunKompiler

I tried to compile the game in the container and also in my computer directly.

As instructed, I'm downloading Haxe v4.1.5

All the dependencies and configurations are in place.

Right on the lime test, it throws this back:

`
source/Main.hx:87: characters 61-65 : Float should be Int
source/Main.hx:87: characters 61-65 : For optional function argument 'updateFramerate'
source/NGio.hx:15: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:16: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:169: characters 25-39 : Void -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:169: characters 25-39 : For optional function argument 'callback'
source/NGio.hx:172: characters 30-45 : Void -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:172: characters 30-45 : For optional function argument 'callback'
source/NGio.hx:155: characters 24-33 : Void -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:155: characters 24-33 : For optional function argument 'callback'
source/ui/ModMenu.hx:113: characters 26-34 : String should be Null<polymod.ScanParams>
source/ui/ModMenu.hx:113: characters 26-34 : String has no field apiVersionRule
source/ui/ModMenu.hx:113: characters 26-34 : For optional function argument 'scanParams'
source/NGio.hx:53: characters 5-19 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:102: characters 65-78 : error: io.newgrounds.LoginOutcome should be io.newgrounds.objects.Error
source/NGio.hx:102: characters 65-78 :  have: (io.newgrounds.objects.Error) -> ...
source/NGio.hx:102: characters 65-78 :  want: (io.newgrounds.LoginOutcome) -> ...
source/NGio.hx:102: characters 65-78 : For optional function argument 'callback
`

Am I missing something in the compilation? Or is the main branch not the one used for compiling a stable version?

**Comment by Justine101213k** [comment]
replace this code to Main.hx
`addChild(new FlxGame(gameWidth, gameHeight, initialState, #if (flixel < "5.0.0") zoom, #end framerate, framerate, skipSplash, startFullscreen));`

and please reinstall newgrounds to fix
`haxelib remove newgrounds` // remove the latest of newgrounds
`haxelib install newgrounds 1.1.5`

**Comment by andersonpem** [comment]
I'm having this error in ModMenu.hx:
`source/ui/ModMenu.hx:113: characters 26-34 : String should be Null<polymod.ScanParams>
source/ui/ModMenu.hx:113: characters 26-34 : String has no field apiVersionRule
source/ui/ModMenu.hx:113: characters 26-34 : For optional function argument 'scanParams'`

**Comment by andersonpem** [comment]
That fixes it.
