### ISSUE TITLE
Question: How do i fix this

### ISSUE THREAD

**Issue by SoulkingBG** [FunkinCrew/Funkin#2135]
#### Please check for duplicates or ssource/Main.hx:87: characters 61-65 : Float should be Int
source/Main.hx:87: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:87: characters 61-65 : ... For function argument 'child'
source/NGio.hx:15: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:16: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:169: characters 25-39 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:169: characters 25-39 : ... For optional function argument 'callback'
source/NGio.hx:172: characters 30-45 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:172: characters 30-45 : ... For optional function argument 'callback'
source/NGio.hx:155: characters 24-33 : () -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:155: characters 24-33 : ... For optional function argument 'callback'
source/ui/ModMenu.hx:113: characters 26-34 : String should be Null<polymod.ScanParams>
source/ui/ModMenu.hx:113: characters 26-34 : ... String has no field apiVersionRule
source/ui/ModMenu.hx:113: characters 26-34 : ... For optional function argument 'scanParams'
source/NGio.hx:53: characters 5-19 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:102: characters 65-78 : error: io.newgrounds.LoginOutcome should be io.newgrounds.objects.Error
source/NGio.hx:102: characters 65-78 : ... have: (io.newgrounds.objects.Error) -> ...
source/NGio.hx:102: characters 65-78 : ... want: (io.newgrounds.LoginOutcome) -> ...
source/NGio.hx:102: characters 65-78 : ... For optional function argument 'callback'imilar issues before asking your question.

**Comment by Justine101213k** [comment]
`haxelib install newgrounds 1.1.5`
`haxelib set newgrounds 1.1.5`

**Comment by raymonable** [comment]
this fucking code needs to receive some updates

**Comment by ZonerPlayz** [comment]
> haxelib set newgrounds 1.1.5

I tried that and it did remove the newgrounds error but, I still recieve the rest of the error.
