### ISSUE TITLE
Question: How to make change stage event in kade engine?

### ISSUE THREAD

**Issue by alexandrucn** [FunkinCrew/Funkin#2141]
How to make change stage event?

**Comment by TheRealJake12** [comment]
ok so basically, iirc. 
in curStep function
make a case that is the step (the time the event does)
then do smth like
```
case 69420:
 Stage == null;
 Stage = new Stage("thestage");
```
I highly doubt that works, if you're using KE 1.8 or some [custom version](https://github.com/TheRealJake12/Kade-Engine-Community.git) [or something](https://github.com/BoloVEVO/Kade-Engine.git) then theres a chance.

**Comment by alexandrucn** [comment]
thank you
