### ISSUE TITLE
crash when trying to access a debug menu 

### ISSUE THREAD

**Issue by 7oltan** [FunkinCrew/Funkin#2146]
there is a menu that you can get to by pressing 8 in the title menu when your in debug that crash's , the error it gives is not understandable (uncatchable throw: invalid char 65279 at position 0) ive been debuging it and i found out in line (117) in script (FlxSprite) in folder (animate) is when the crash happens `data = cast Json.parse(json).ATLAS;` can someone help

**Comment by alexandrucn** [comment]
Download again the source code
