### ISSUE TITLE
Check the FLA files if the Actionscript is set to the latest version when OPEN IT!

### ISSUE THREAD

**Issue by Swapper1** [FunkinCrew/Funkin#2150]
For people who use 23.0.1.70 of Adobe Animate before the update, here what's happened.
![Screenshot 2023-05-10 212538](https://github.com/FunkinCrew/Funkin/assets/67173708/f914f197-ea61-4127-a410-de47621cf7a6)
If you try to open the flash file with Actionscript 2.0 staring the version **23.0.2.103 of Adobe Animate** or later,
it won't work. The only flash file since week 7 source code is in public, "_NOTE_assets-fixedSplashesANIMATEONLY_", "_RECOVER_NOTE_assets_desaturated_", and the fonts text were set to Actionscript 3.0.

Note that these fla files are not set to Actionscript 3.0, it will be fix soon.

------
If you want fla files, please download the fla file with the latest Actionscript [here](https://drive.google.com/file/d/1hz1d9kpKYgFjP0kDXwbr5ovgp_eUSB5z/view).

**OR**

To order to make fla file work, please follow these steps:
1. Open the fla file that has the Actionscript 2.0
2. Check if is set to Actionscript 3.0 or not.
3. Save and open the file again to view it if is set to Actionscript 3.0. Once you save the fla file, it will set to Actionscript 3.0.

------
If you have any problem, let me know.

Latest update: 5/21/2023

**Comment by SwickTheGreat** [comment]
still a bit confused, i cannot open the file and therefore i can't change the actionscript version. what do i do?

**Comment by Swapper1** [comment]
> still a bit confused, i cannot open the file and therefore i can't change the actionscript version. what do i do?

Have you set the fla file to Actionscript 3.0? What version did you use?

**Comment by itsoutchy-projects** [comment]
You can't save the FLA because you can't open them.

**Comment by CotardsSolution** [comment]
Files worked for me, thank you so much
