### ISSUE TITLE
Compiling help: Tons of errors

### ISSUE THREAD

**Issue by NULLSonic** [FunkinCrew/Funkin#2151]
#### Compiling to: 

- [ ] Windows
- [X] Mac
- [ ] Linux
- [ ] HTML5

## Description/Errors:

So, I'm gettin' tons of errors when compiling the game!
Here the errors:

/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/text/FlxTypeText.hx:78: characters 26-34 : Type not found : FlxSound
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:134: characters 18-33 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:135: characters 19-35 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:150: characters 50-65 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:150: characters 50-65 : ... For function argument 'v'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:151: characters 50-66 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:151: characters 50-66 : ... For function argument 'v'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:261: characters 23-32 : Unknown identifier : tileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:268: characters 22-32 : Unknown identifier : tileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:273: characters 31-46 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:274: characters 31-47 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:358: characters 63-78 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:358: characters 63-78 : ... For function argument 'v'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:359: characters 63-79 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:359: characters 63-79 : ... For function argument 'v'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:360: characters 77-92 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:360: characters 77-92 : ... For function argument 'v'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:361: characters 78-94 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:361: characters 78-94 : ... For function argument 'v'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:383: characters 19-34 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:383: characters 19-34 : ... For function argument 'Width'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:384: characters 20-36 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:384: characters 20-36 : ... For function argument 'Height'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:625: characters 30-46 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:625: characters 30-46 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:630: characters 35-50 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:643: characters 30-46 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:643: characters 30-46 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:649: characters 31-47 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:649: characters 31-47 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:655: characters 30-46 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:655: characters 30-46 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:553: characters 67-82 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:553: characters 67-82 : ... For optional function argument 'Max'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:554: characters 67-83 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:554: characters 67-83 : ... For optional function argument 'Max'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:669: characters 31-46 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:697: characters 30-46 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:697: characters 30-46 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:702: characters 35-50 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:715: characters 30-46 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:715: characters 30-46 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:721: characters 31-47 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:721: characters 31-47 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:727: characters 30-46 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:727: characters 30-46 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:741: characters 31-46 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:770: characters 35-50 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:781: characters 30-46 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:781: characters 30-46 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:785: characters 30-46 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:785: characters 30-46 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:789: characters 31-47 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:789: characters 31-47 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:797: characters 31-46 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:821: characters 58-73 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:821: characters 58-73 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:826: characters 35-50 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:837: characters 30-46 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:837: characters 30-46 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:841: characters 30-46 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:841: characters 30-46 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:845: characters 31-47 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:845: characters 31-47 : ... For function argument 'Value'
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:853: characters 31-46 : Unknown identifier : scaledTileWidth
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/tile/FlxTilemapExt.hx:600: characters 28-44 : Unknown identifier : scaledTileHeight
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/DialogueBox.hx:143: characters 16-22 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:239: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:240: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/DialogueBox.hx:241: characters 16-32 : flixel.addons.text.FlxTypeText has no field completeCallback
source/DialogueBox.hx:224: characters 17-21 : flixel.addons.text.FlxTypeText has no field skip
/usr/local/lib/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
/usr/local/lib/haxe/lib/flixel-addons/3,1,1/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field

Possible way to fix this?

**Comment by MagelessMayhem** [comment]
flixel-addons 2.11.0 is the last version to work with the game's source code:

`haxelib install flixel-addons 2.11.0`
`haxelib set flixel-addons 2.11.0`

Versions 3.x are meant for HaxeFlixel 5.0+. The game uses HaxeFlixel 4.11.0.

**Comment by AceThePan** [comment]
> flixel-addons 2.11.0 is the last version to work with the game's source code:
> 
> `haxelib install flixel-addons 2.11.0` `haxelib set flixel-addons 2.11.0`
> 
> Versions 3.x are meant for HaxeFlixel 5.0+, which the game's source code is not compatible with (HF 4.11.0 is supported, however).

THX! It fixed it!
