### ISSUE TITLE
Compiling help: [NGio.hx error / source/NGio.hx:86: characters 38-45 : Class<APIStuff> has no field SESSION source/NGio.hx:89: characters 26-33 : Class<APIStuff> has no field SESSION]

### ISSUE THREAD

**Issue by ctrxl** [FunkinCrew/Funkin#2155]
I have a problem while compiling when I type "test lime windows -debug" it gives me this error 
![image](https://github.com/FunkinCrew/Funkin/assets/136636554/5101415f-74fb-4754-bbd1-b860f00701c1)

how do i fix this?

**Comment by uesleibros** [comment]
you forgot something. Check if you create a `APIStuff.hx` file and put this code into file:
```hx
package;

class APIStuff
{
	inline public static var API:String = "51348:TtzK0rZ8";
	inline public static var EncKey:String = "5NqKsSVSNKHbF9fPgZPqPg==";
	inline public static var SESSION:String = null;
}
```

On `NGio.hx` file the code try to get the `SESSION` variable into `APIStuff.hx` APIStuff class.
