### ISSUE TITLE
.zip file immediately deletes itself after download. (Windows)

### ISSUE THREAD

**Issue by KlumsyKraft** [FunkinCrew/Funkin#216]
Either that, or it denies my access into the game. I can only play on the browser version, which isn't too bad of a problem, I just wanna mod the game.
![Screenshot (130)](https://user-images.githubusercontent.com/68036292/105106250-b4795c00-5a83-11eb-90c3-39ee3864c5a6.png)

**Comment by gedehari** [comment]
This is weird, do you have any antivirus intervening?

**Comment by KlumsyKraft** [comment]
i don't think so, and if i do, i don't know how i'd disable it. my computer isn't telling me the problem. it's just saying it can't open the folder cuz it's not allowed to, then deletes it.

**Comment by gedehari** [comment]
probably windows defender? but I never experienced it myself. It should not do that in the first place.

If it's Windows Defender, then you can manually disable real time protection, but it will turn itself back on after restart.

**Comment by regulad** [comment]
> 
> 
> probably windows defender? but I never experienced it myself. It should not do that in the first place.
> 
> If it's Windows Defender, then you can manually disable real time protection, but it will turn itself back on after restart.

you can also temporarily whitelist your downloads folder.  have you tried using a program like 7zip or winrar?

**Comment by KlumsyKraft** [comment]
i'll try that. they added week 5 today, so maybe i'll try to download it with that new update first. thanks!

**Comment by KlumsyKraft** [comment]
> > probably windows defender? but I never experienced it myself. It should not do that in the first place.
> > If it's Windows Defender, then you can manually disable real time protection, but it will turn itself back on after restart.
> 
> you can also temporarily whitelist your downloads folder. have you tried using a program like 7zip or winrar?

no, i haven't. i'll also try that.

**Comment by KlumsyKraft** [comment]
Hey, update. I figured out the issue. I think there may be an issue with my computer when downloading .zips by browser. Luckily, I managed to get the game by the itch app rather than on the website. Thanks for the help. 😃

**Comment by gedehari** [comment]
Glad you solved this issue. We still didn't know what caused it, Imma keep an eye on this

**Comment by gedehari** [comment]
Ah okay, thanks for mentioning!
