### ISSUE TITLE
Compiling help: pls help me

### ISSUE THREAD

**Issue by XavierCodes99** [FunkinCrew/Funkin#2164]
Creating C:/Users/LENOVO SLIM 3/Desktop/Funkin-0.2.7.1/export/release/windows/obj/obj/msvc1964-nc/__pch/haxe/hxcpp.pch...
hxcpp.cpp
C:/haxelib/hxcpp/4,3,2/include\hxcpp.h(17): fatal error C1083: Cannot open include file: 'typeinfo': No such file or directory
Error: Could not create PCH

**Comment by Sword352** [comment]
Run `lime test windows -clean`

**Comment by XavierCodes99** [comment]
It still doesn't work

**Comment by Vortex2Oblivion** [comment]
Delete the export folder then try again

**Comment by XavierCodes99** [comment]
It also still doesn't work
