### ISSUE TITLE
MY OWN CUSTOM BF SPRITE WON'T LOAD IN!!!! (DETAILS IN DESC)

### ISSUE THREAD

**Issue by SOOONNN** [FunkinCrew/Funkin#2167]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
![Screenshot 2023-07-21 200201](https://github.com/FunkinCrew/Funkin/assets/140219626/61abb1f5-4eda-46c5-895b-c5c95da77d2a)
![Screenshot 2023-07-21 200215](https://github.com/FunkinCrew/Funkin/assets/140219626/b88e6522-c2c9-4556-8603-c3e9ced93236)
Hello!!! My issue is hopefully a simple one to you guys, but it's nearly impossible for me. I created a custom- made, my artstyled BF sprite in flash CS4. I then downloaded CS6 and made it into a spritesheet there. I'm not sure if a specific pattern is needed, so i just put it in order like this: (DOWN, DOWN MISS, IDLE, RIGHT, RIGHT MISS, LEFT, LEST MISS, UP, UP MISS.
I loaded it into psych engine, and it gave me the error message ( i pasted it above )

Thank you for your time!!!
-SOON

**Comment by Sword352** [comment]
This repo is NOT for psych engine 🗣🔥
https://github.com/ShadowMario/FNF-PsychEngine

Also its just an issue with your XML so just re-export your spritesheet

**Comment by Vovo4k** [comment]
This is not psych engine :skull:
