### ISSUE TITLE
Compiling help: newgrounds and polymod thing?

### ISSUE THREAD

**Issue by WallDotHX** [FunkinCrew/Funkin#2168]
I'm assuming it's something wrong with polymod and newgrounds library but uhh:

source/Main.hx:87: characters 61-65 : Float should be Int
source/Main.hx:87: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:87: characters 61-65 : ... For function argument 'child'
source/NGio.hx:15: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:16: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:169: characters 25-39 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:169: characters 25-39 : ... For optional function argument 'callback'
source/NGio.hx:172: characters 30-45 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:172: characters 30-45 : ... For optional function argument 'callback'
source/NGio.hx:155: characters 24-33 : () -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:155: characters 24-33 : ... For optional function argument 'callback'
source/ui/ModMenu.hx:113: characters 26-34 : String should be Null<polymod.ScanParams>
source/ui/ModMenu.hx:113: characters 26-34 : ... String has no field apiVersionRule
source/ui/ModMenu.hx:113: characters 26-34 : ... For optional function argument 'scanParams'
source/NGio.hx:53: characters 5-19 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:102: characters 65-78 : error: io.newgrounds.LoginOutcome should be io.newgrounds.objects.Error
source/NGio.hx:102: characters 65-78 : ... have: (io.newgrounds.objects.Error) -> ...
source/NGio.hx:102: characters 65-78 : ... want: (io.newgrounds.LoginOutcome) -> ...
source/NGio.hx:102: characters 65-78 : ... For optional function argument 'callback'

**Comment by Bigmancozmo** [comment]
I also think it's something wrong with polymod and newgrounds, this repo hasn't been updated in ages and last time I tried it compiled successfully.
