### ISSUE TITLE
When i try to compile psych engine i got this error

### ISSUE THREAD

**Issue by gold198** [FunkinCrew/Funkin#2171]
source/objects/Note.hx:28: characters 4-12 : Type not found : FlxColor
source/states/TitleState.hx:42: characters 26-40 : Type not found : MusicBeatState

**Comment by BocaIoachim** [comment]
this repo is not psych engine bro
this is the original fnf repo

**Comment by MemeHovy** [comment]
> source/objects/Note.hx:28: characters 4-12 : Type not found : FlxColor
> source/states/TitleState.hx:42: characters 26-40 : Type not found : MusicBeatState

this ain’t the psych repo dumbass

**Comment by Stefan2008Git** [comment]
> > source/objects/Note.hx:28: characters 4-12 : Type not found : FlxColor
> > source/states/TitleState.hx:42: characters 26-40 : Type not found : MusicBeatState
> 
> this ain’t the psych repo dumbass

Bahahaha
Nice failed issue

**Comment by VoidHong** [comment]
Did you find a solution? I'm having the exact same issue

**Comment by MemeHovy** [comment]
> Did you find a solution? I'm having the exact same issue

**this isn’t the fucking psych repo**

**Comment by Stefan2008Git** [comment]
> > Did you find a solution? I'm having the exact same issue
> 
> **this isn’t the fucking psych repo**

LMAO, i laughed

**Comment by elnexreal** [comment]
toxic ppl here smh, fuck you guys, be nice

**Comment by MemeHovy** [comment]
> toxic ppl here smh, fuck you guys, be nice

to dumbasses, no
