### ISSUE TITLE
Enhancement: Ability To Skip Cutscenes

### ISSUE THREAD

**Issue by MarMar925** [FunkinCrew/Funkin#2178]
### Enhancement: Ability To Skip Cutscenes

I suggest that you put in the ability to skip cutscenes. I say this is a good idea because when playing through weeks 5 - 7 I really want to skip the cutscenes but I can't and it takes up so much time. It doesn't have to be anything fancy, maybe just click the Enter key and it'll skip!

**Comment by piratabrasileiro1** [comment]
but what would it be like? the same as south park?

**Comment by ItzASecret** [comment]
They added this already for weekend 1, so it shouldn't be too hard to add for week 7
