### ISSUE TITLE
Compiling help: need help with compiling

### ISSUE THREAD

**Issue by AlvarroPewz24** [FunkinCrew/Funkin#2182]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
i already followed #2077 and all the instructions
(command: lime build windows -release)

source/NGio.hx:15: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:16: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:169: characters 25-39 : Void -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:169: characters 25-39 : For optional function argument 'callback'
source/NGio.hx:172: characters 30-45 : Void -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:172: characters 30-45 : For optional function argument 'callback'
source/NGio.hx:155: characters 24-33 : Void -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:155: characters 24-33 : For optional function argument 'callback'
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/text/FlxTypeText.hx:78: characters 26-34 : Type not found : FlxSound
source/HealthIcon.hx:7: lines 7-64 : Defined in this class
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/DialogueBox.hx:143: characters 16-22 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:239: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:240: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/DialogueBox.hx:241: characters 16-32 : flixel.addons.text.FlxTypeText has no field completeCallback
source/DialogueBox.hx:224: characters 17-21 : flixel.addons.text.FlxTypeText has no field skip
source/NGio.hx:53: characters 5-19 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:102: characters 65-78 : error: io.newgrounds.LoginOutcome should be io.newgrounds.objects.Error
source/NGio.hx:102: characters 65-78 :  have: (io.newgrounds.objects.Error) -> ...
source/NGio.hx:102: characters 65-78 :  want: (io.newgrounds.LoginOutcome) -> ...
source/NGio.hx:102: characters 65-78 : For optional function argument 'callback'
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field

**Comment by MemeHovy** [comment]
don't make duplicate issues

**Comment by JohnDoe3453** [comment]
> don't make duplicate issues

making duplicate issues is weird
