### ISSUE TITLE
It bothered me for a long time

### ISSUE THREAD

**Issue by fg133266** [FunkinCrew/Funkin#2186]
D:/haxe4.1.5/haxe/lib/flixel-addons/2,11,0/flixel/addons/transition/FlxTransitionableState.hx:81: lines 81-90 : Warning : switchTo is deprecated, use startOutro
source/Main.hx:87: characters 61-65 : Float should be Int
source/Main.hx:87: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:87: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:69: characters 21-29 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:115: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
D:/haxe4.1.5/haxe/lib/flixel-addons/2,11,0/flixel/addons/text/FlxTypeText.hx:77: characters 26-34 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
D:/haxe4.1.5/haxe/lib/flixel-addons/2,11,0/flixel/addons/text/FlxTypeText.hx:164: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:274: characters 22-30 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1579: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1581: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:32: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:42: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/ChartingState.hx:79: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/ChartingState.hx:357: characters 16-24 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound

Windows x64

help me

**Comment by AbsurdCoolMan** [comment]
In Main.hx, where it specifies the FlxGame, remove the zoom variable. Flixel removed the zoom parameter a while ago and that's what's causing the error in that file.

And for the warnings, FlxSound was moved into a new directory, and you can also blame that on Flixel. You can either just ignore the warnings, or replace the deprecated FlxSound path from the hx files where the warnings came from with the new path.

It's as easy as that! Hopefully you understand.

**Comment by fg133266** [comment]
> 在指定 FlxGame 的 Main.hx 中，删除 zoom 变量。Flixel 不久前删除了缩放参数，这就是导致该文件出错的原因。
> 
> 对于警告，FlxSound 被移到了一个新目录中，您也可以将其归咎于 Flixel。您可以忽略警告，也可以将警告来自的 hx 文件中已弃用的 FlxSound 路径替换为新路径。
> 
> 就这么简单！希望你能理解。

think you! I've solved it

**Comment by fg133266** [comment]
> 在指定 FlxGame 的 Main.hx 中，删除 zoom 变量。Flixel 不久前删除了缩放参数，这就是导致该文件出错的原因。
> 
> 对于警告，FlxSound 被移到了一个新目录中，您也可以将其归咎于 Flixel。您可以忽略警告，也可以将警告来自的 hx 文件中已弃用的 FlxSound 路径替换为新路径。
> 
> 就这么简单！希望你能理解。

Thank you, I've solved it
