### ISSUE TITLE
Compiling help: Public variables not accepted | source/NGio.hx:34: characters 2-8 : Unexpected public

### ISSUE THREAD

**Issue by Zenith000T** [FunkinCrew/Funkin#2187]
I'm completely new to compiling source code, and so far I've managed to fix a bunch of problems, but this one is something I genuinely can't figure out. For some reason the public variables don't seem to work with the "class NGio", and I'm afraid deleting them will cause more problems. I've tried simply removing the public part, but even then it just tells me "unexpected static".
I really don't know what to do at this point considering I've absolutely made sure I have all the necessary things used like Haxe, SScript, etc.

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

![image_2023-12-05_000840321](https://github.com/FunkinCrew/Funkin/assets/130024413/0612d8a0-0524-4523-978f-814468b8fb33)

**Comment by Vortex2Oblivion** [comment]
Get rid of the line that has ```public static apiStuff(default, null):?```
