### ISSUE TITLE
Bug Report: Zoomed Out Camera

### ISSUE THREAD

**Issue by RonyxDumb** [FunkinCrew/Funkin#2192]
## Info
Version: v0.2.7.1 (compiled from the source code)
Platform: Windows 

## Bug
(Only when entering PlayState) When a song starts, the game camera becomes very small, making gameplay impossible. I think it's a bug caused by the wrong libraries I'm using. Since the libraries are mostly out of date, is there a list with all the libraries with the corresponding versions of them? 

## Proofs
Take a look at this video to understand what I'm talking about.

https://github.com/FunkinCrew/Funkin/assets/104029827/fff6a357-a4a9-4299-9d37-a06fc3f386fc

**Comment by moxie-coder** [comment]
it's an issue involving old flixel versions, try using 5.2.2

**Comment by RonyxDumb** [comment]
Thank you, it worked

**Comment by moxie-coder** [comment]
np
