### ISSUE TITLE
How do I add noteTypes to the forever engine?

### ISSUE THREAD

**Issue by phrGithubGamerBR** [FunkinCrew/Funkin#2193]

**Comment by moxie-coder** [comment]
not the correct place to ask this

**Comment by pablowolfgamerbr** [comment]
Okay, where am I going to ask this question if the creator has already deleted the engine?

**Comment by moxie-coder** [comment]
> Okay, where am I going to ask this question if the creator has already deleted the engine?

definitely not here, that’s for sure

**Comment by moxie-coder** [comment]
the creator was a predator, there’s a good damn reason her account is gone and it should stay that way

**Comment by moxie-coder** [comment]
but @pablowolfgamerbr [I would use this instead](https://github.com/CrowPlexus-FNF/Forever-Engine)
