### ISSUE TITLE
Question: why do I get this error code when I type in haxelib git polymod https://github.com/MasterEric/polymod.git

### ISSUE THREAD

**Issue by Syckotik** [FunkinCrew/Funkin#2197]
Why do I get the "could not clone git repository" error when I type in 
haxelib git polymod https://github.com/MasterEric/polymod.git
in windows powershell. Every other command I've typed in before that worked fine.

**Comment by Vortex2Oblivion** [comment]
```haxelib install polymod``` instead

**Comment by ELIP4444** [comment]
> Why do I get the "could not clone git repository" error when I type in haxelib git polymod https://github.com/MasterEric/polymod.git in windows powershell. Every other command I've typed in before that worked fine.

Its cuz you have a bad internet connection. You must retry

**Comment by Portakal-Studio** [comment]
> `haxelib install polymod` instead
is it the same
