### ISSUE TITLE
Help i cant compile game

### ISSUE THREAD

**Issue by UserNamer172** [FunkinCrew/Funkin#2200]
source/Main.hx:87: characters 61-65 : Float should be Int
source/Main.hx:87: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:87: characters 61-65 : ... For function argument 'child'
source/NGio.hx:15: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:16: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:169: characters 25-39 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:169: characters 25-39 : ... For optional function argument 'callback'
source/NGio.hx:172: characters 30-45 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:172: characters 30-45 : ... For optional function argument 'callback'
source/NGio.hx:155: characters 24-33 : () -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:155: characters 24-33 : ... For optional function argument 'callback'
source/ui/ModMenu.hx:113: characters 26-34 : String should be Null<polymod.ScanParams>
source/ui/ModMenu.hx:113: characters 26-34 : ... String has no field apiVersionRule
source/ui/ModMenu.hx:113: characters 26-34 : ... For optional function argument 'scanParams'
source/PlayState.hx:69: characters 21-29 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:115: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:274: characters 22-30 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1579: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1581: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:32: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:42: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/ChartingState.hx:79: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/ChartingState.hx:357: characters 16-24 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/NGio.hx:53: characters 5-19 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:102: characters 65-78 : error: io.newgrounds.LoginOutcome should be io.newgrounds.objects.Error
source/NGio.hx:102: characters 65-78 : ... have: (io.newgrounds.objects.Error) -> ...
source/NGio.hx:102: characters 65-78 : ... want: (io.newgrounds.LoginOutcome) -> ...
source/NGio.hx:102: characters 65-78 : ... For optional function argument 'callback'

**Comment by roschreiber** [comment]
`haxelib install newgrounds 1.1.5`
`haxelib set newgrounds 1.1.5`
