### ISSUE TITLE
Question: how do i fix this? my friend asked me how to fix this

### ISSUE THREAD

**Issue by jack-dutchie** [FunkinCrew/Funkin#2202]
### how do i fix this my friend asked me how to fix this

![image](https://github.com/FunkinCrew/Funkin/assets/141778999/52cd0c17-4852-4dc4-9882-7d6cb9d0fbd9)

**Comment by moxie-coder** [comment]
this ain’t the right repo for that

**Comment by jack-dutchie** [comment]
> this ain’t the right repo for that

then what do i use?

**Comment by jack-dutchie** [comment]
nvm his engine was broken

**Comment by moxie-coder** [comment]
> > this ain’t the right repo for that
> 
> 
> 
> then what do i use?
> 
> 

Psych engine repo
