### ISSUE TITLE
Bug Report: NULL OBJECT REFERENCE AFTER FIRST SONG IN WEEK-END !

### ISSUE THREAD

**Issue by Coldstone007** [FunkinCrew/Funkin#2209]
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
v0.3.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Restarted the game and retried the week up to that point and the same issue occured.

## Please describe your issue. Provide extensive detail and images if possible.
Everytime I attempt to play the Week-END 1 week, after the first song completes my game crashes, giving me a pop-up saying "Error - Null Object Reference"

**Comment by PipocaAventuras** [comment]
this happens with every week

**Comment by RetroRyIn** [comment]
> this happens with every week

this also only seems to apply to hard difficulty

**Comment by PipocaAventuras** [comment]
whaaaaaaaaaaaaa

**Comment by Maz-github** [comment]
replace chart imports that have "fnf legacy" to  "generatedBy": "MasterEric (by hand)" in song metadata

**Comment by 07thecreeper** [comment]
> this also only seems to apply to hard difficulty
for me it happens on normal difficulty too (didn't test easy)

**Comment by Maz-github** [comment]
https://youtu.be/ftHOm_VaZ14 BUG FIX VIDEO ON HOW TO DO IT

**Comment by 07thecreeper** [comment]
> https://youtu.be/ftHOm_VaZ14 BUG FIX VIDEO ON HOW TO DO IT

didn't work for me

**Comment by GoldenAZ** [comment]
until a fix is made, pressing F5 after a song starts ( reloads the level ) prevents the crash at the end of a song ( or at least for me and my friends it does )

**Comment by mlo12345** [comment]
Neither F5 or the metadata trick is working for me

**Comment by Maz-github** [comment]
depends on the song. you may need to fuck w the actual chart file a bit

**Comment by EliteMasterEric** [comment]
This was from v0.3.0 it should be fixed now.
