### ISSUE TITLE
Bug Report: [DESCRIBE YOUR BUG IN DETAIL HERE]

### ISSUE THREAD

**Issue by GBAawesomekid** [FunkinCrew/Funkin#2210]
im being given this when i try to launch it

![image_2024-04-30_203547814](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/52b94bb7-877f-4463-9436-3bb9d0ae27cd/390ad428-e961-422e-8a94-e399672172c3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi81MmI5NGJiNy04NzdmLTQ0NjMtOTQzNi0zYmI5ZDBhZTI3Y2QvMzkwYWQ0MjgtZTk2MS00MjJlLThhOTQtZTM5OTY3MjE3MmMzIiwiaWF0IjoxNzE3MTA3MjQxLCJleHAiOjMzMjg3NjY3MjQxfQ.NoAn0R9nX9tjIue1FlhMuAA9M7b8wbdhHBGl-PpIp7E)

![image_2024-04-30_203649160](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/2ccb45b3-e189-4e8a-8520-dd25ac35d8c2/e24331d4-fd7d-48cb-88b1-9ef2e7bb32d1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi8yY2NiNDViMy1lMTg5LTRlOGEtODUyMC1kZDI1YWMzNWQ4YzIvZTI0MzMxZDQtZmQ3ZC00OGNiLTg4YjEtOWVmMmU3YmIzMmQxIiwiaWF0IjoxNzE3MTA3MjQxLCJleHAiOjMzMjg3NjY3MjQxfQ.9DjvCvzCPAAivyE06LPz1puGOzpkgYiVmZDAS2LK3O4)

**Comment by IzzyIsDead666** [comment]
same

**Comment by kirbychannel12** [comment]
same I just wanna play the game bruh look
![image](https://github.com/FunkinCrew/Funkin/assets/168609642/4f42bc3c-39a7-4b9d-8cf4-e86bae709ecc)

**Comment by SilverT4** [comment]
Commenting "same" doesn't do much for an issue.

Regardless... [Devs are aware of the issue and working on a fix.](https://twitter.com/ninja_muffin99/status/1785489337527803931)

**Comment by ninjamuffin99** [comment]
I believe this was fixed, so going to close it :)
