### ISSUE TITLE
please fix this for us bruh

### ISSUE THREAD

**Issue by kirbychannel12** [FunkinCrew/Funkin#2211]
### If you are playing the game in a browser, what site are you playing it from?

- [X] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [X] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [X] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

**Comment by SilverT4** [comment]
What exactly is going wrong? All I see is that you've checked Newgrounds, Windows, and Google Chrome. That doesn't tell much about what's going on.

**Comment by kirbychannel12** [comment]
im playin on opera

**Comment by SilverT4** [comment]
That doesn't help. What problem are you experiencing?

**Comment by pizzatowerfan126** [comment]
newgrounds

**Comment by pizzatowerfan126** [comment]
on Google chrome

**Comment by SilverT4** [comment]
@pizzatowerfan126 Open your own issue.

**Comment by EliteMasterEric** [comment]
The Opera issues got fixed in v0.3.1 I think.
