### ISSUE TITLE
Bug Report: [Weekend 1 songs not appearing in freeplay]

### ISSUE THREAD

**Issue by 07thecreeper** [FunkinCrew/Funkin#2212]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.0 prototype

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

![image](https://github.com/FunkinCrew/Funkin/assets/25090874/c3adcedc-edda-432a-96eb-14a004380c8a)

## Please describe your issue. Provide extensive detail and images if possible.

There aren't the new weekend songs in the freeplay menu

**Comment by VocalFan** [comment]
@07thecreeper It's in the changelog, they unlock if you complete the week

**Comment by 07thecreeper** [comment]
> @07thecreeper It's in the changelog, they unlock if you complete the week

ah thanks
