### ISSUE TITLE
"Blazin'" incorrectly labeled as from FNF OST Vol.1 instead of Vol.3

### ISSUE THREAD

**Issue by Pretender8** [FunkinCrew/Funkin#2213]
- [X] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [X] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
v0.3.0 prototype

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

- Start the game
- Go to the Free Play menu.
- Navigate down to the song Blazin'. 
- The album art and album name does not match the other songs from the week. 

## Please describe your issue. Provide extensive detail and images if possible.
Blazin' is incorrectly labelled as a Vol. 1 track when it should be Vol. 3 along with the rest of the songs for this week. 
![image](https://github.com/FunkinCrew/Funkin/assets/34997550/e64717ff-c4bb-44ea-a6ed-6360e0a2db0e)

**Comment by AwesomeCoder412412** [comment]
Did I miss something?

**Comment by EliteMasterEric** [comment]
Will be fixed in a future update.

**Comment by Hundrec** [comment]
The new 0.4.0 (itch.io Version 14) update now correctly labels Blazin' as Volume 3.

All Erect remixes except Satin Panties, Eggnog, and Roses are also labeled Volume 3.

**Comment by EliteMasterEric** [comment]
Oh yeah this is uh fixed.
