### ISSUE TITLE
Bug Report: Game Over Crashes

### ISSUE THREAD

**Issue by hifishlol** [FunkinCrew/Funkin#2214]
### If you are playing the game in a browser, what site are you playing it from?

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [X] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

0.3.0 prototype

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

2 ways to crash in gameover:

1. die before countdown is done
2. trigger stickersubstate whilst transitioning to playstate, (enter, then esc before the playstate transition happens)

## Please describe your issue. Provide extensive detail and images if possible.

the game. crashes!!!! lol

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

**Comment by SilverT4** [comment]
Running the game from a command prompt (PowerShell or cmd) can be helpful for bug reports on Windows, at least imo. I attempted to recreate both of the methods you mentioned, and got these errors in the console window:

For resetting before song start:

```
Called from funkin.play.PlayState.update (funkin/play/PlayState.hx line 1013)
Called from flixel.FlxState.tryUpdate (flixel/FlxState.hx line 223)
Called from flixel.FlxGame.update (flixel/FlxGame.hx line 750)
Called from flixel.FlxGame.step (flixel/FlxGame.hx line 680)
Called from flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 559)
Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)
Called from openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1399)
Null Object Reference
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 559
Called from flixel.FlxGame::step flixel/FlxGame.hx line 680
Called from flixel.FlxGame::update flixel/FlxGame.hx line 750
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 223
Called from funkin.play.PlayState::update funkin/play/PlayState.hx line 1013
```

For the StickerSubState one, I got this:

```
Called from funkin.ui.transition.StickerSubState.regenStickers (funkin/ui/transition/StickerSubState.hx line 241)
Called from flixel.util.FlxTimer.onLoopFinished (flixel/util/FlxTimer.hx line 205)
Called from flixel.util.FlxTimerManager.update (flixel/util/FlxTimer.hx line 295)
Called from flixel.FlxGame.update (flixel/FlxGame.hx line 748)
Called from flixel.FlxGame.step (flixel/FlxGame.hx line 680)
Called from flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 559)
Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)
Called from openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1399)
Null Object Reference
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 559
Called from flixel.FlxGame::step flixel/FlxGame.hx line 680
Called from flixel.FlxGame::update flixel/FlxGame.hx line 748
Called from flixel.util.FlxTimerManager::update flixel/util/FlxTimer.hx line 295
Called from flixel.util.FlxTimer::onLoopFinished flixel/util/FlxTimer.hx line 205
Called from funkin.ui.transition.StickerSubState::regenStickers funkin/ui/transition/StickerSubState.hx line 241
```

The 0.3.0 version of the game *is* a prototype, so not everything will work as expected. I imagine these problems may end up fixed in the next version released.

**Comment by Hundrec** [comment]
I tried to replicate these crashes in 0.5.1, and fortunately couldn't.
We can probably close this one now!

**Comment by AbnormalPoof** [comment]
Shouldn't this be closed if it was resolved?
