### ISSUE TITLE
Bug Report: [when i press in "touch here to play the game", my game freezes and this message appears: "Uncaught TypeError: Cannot read properties of null (reading 'duration') at openfl_media_Sound.get_length (Funkin.js:40023:34) at funkin_audio_FunkinSound.init (Funkin.js:95415:56) at funkin_audio_FunkinSound.loadEmbedded (Funkin.js:95375:15) at funkin_audio_FunkinSound.load (Funkin.js:119213:8) at funkin_audio_FunkinSound.playMusic (Funkin.js:119186:40) at funkin_ui_title_TitleState

### ISSUE THREAD

**Issue by iiwwakura** [FunkinCrew/Funkin#2215]
[weed]: <> (frozen game)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari 
- [x] pera

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

I can't say my game doesn't even loads to that point.

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

nop

## Please describe your issue. Provide extensive detail and images if possible.

game is frozing and an error message appears:

Uncaught TypeError: Cannot read properties of null (reading 'duration')
    at openfl_media_Sound.get_length (Funkin.js:40023:34)
    at funkin_audio_FunkinSound.init (Funkin.js:95415:56)
    at funkin_audio_FunkinSound.loadEmbedded (Funkin.js:95375:15)
    at funkin_audio_FunkinSound.load (Funkin.js:119213:8)
    at funkin_audio_FunkinSound.playMusic (Funkin.js:119186:40)
    at funkin_ui_title_TitleState.playMenuMusic (Funkin.js:210449:28)
    at funkin_ui_title_TitleState.startIntro (Funkin.js:210347:8)
    at flixel_util_FlxTimer.onComplete (Funkin.js:210318:11)
    at flixel_util_FlxTimer.onLoopFinished (Funkin.js:114574:9)
    at flixel_util_FlxTimerManager.update (Funkin.js:114635:56)

![image](https://github.com/FunkinCrew/Funkin/assets/166193776/c2f629a8-8c66-47ff-9b0a-a2ba53c498e8)

**Comment by SilverT4** [comment]
Are you using Opera GX? I'm simply speculating here, but it seems that Opera GX may handle audio in embedded things (which FNF technically is) differently than most Chromium-based browsers.

**Comment by iiwwakura** [comment]
my bad for late reply.

Yes I'm using Opera, I tried downloading the game and it opened just fine.
If the problem was on the browser then it's not a problem for me anymore.

Em ter., 30 de abr. de 2024 23:25, Devin ***@***.***>
escreveu:

**Comment by SilverT4** [comment]
Yeah, the devs fixed the issue according to a statement by ninjamuffin on Twitter

**Comment by EliteMasterEric** [comment]
This got resolved.
