### ISSUE TITLE
Bug Report: Null Object Reference errors everywhere

### ISSUE THREAD

**Issue by Johferson** [FunkinCrew/Funkin#2219]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [X] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.0 PROTOTYPE

## Please describe your issue. Provide extensive detail and images if possible.
There are only a couple of songs that work fine. The rest goes "Null Object Reference"
![image](https://github.com/FunkinCrew/Funkin/assets/85341402/862f49f8-12e3-4fe3-b83b-8640c53e0ec6)

AFFECTED SONGS:
-FRESH
-DAD BATTLE
-PHILLY NICE
-BLAMMED
-EGGNOG
-WINTER HORRORLAND
-ROSES
-THORNS
-GUNS
-STRESS
-LIT UP
-2HOT

This ain't really 100% accurate as I based this on playing every main week since I couldn't access Freeplay (which is another bug that I have to open aa a separate issue)

**Comment by SilverT4** [comment]
[Devs are aware of this issue.](https://twitter.com/ninja_muffin99/status/1785489337527803931)

#2209 #2214
