### ISSUE TITLE
[CRASH] Shader error makes Freeplay inaccessible

### ISSUE THREAD

**Issue by Johferson** [FunkinCrew/Funkin#2220]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [X] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.0 PROTOTYPE

## Please describe your issue. Provide extensive detail and images if possible.
Everytime I open Freeplay, it displays a long error that goes outside the screen (vertically) and crashes
![image](https://github.com/FunkinCrew/Funkin/assets/85341402/78690e50-ef7b-49fb-86da-bd566af6c404)

**Comment by SilverT4** [comment]
This may be an issue related to your computer's graphics drivers. Can you try checking for driver updates in Windows Update?

Also, if you press CTRL+C, you can copy that error message and paste it into Notepad. This works for many common error message boxes in Windows.

**Comment by Johferson** [comment]
> error

It seems that it's more of an AMD issue than an installed driver issue. Idk really.
![Screenshot_2024-05-01-13-54-38-936_com twitter android-edit](https://github.com/FunkinCrew/Funkin/assets/85341402/23ac68b7-6d9e-4299-af10-8b15441834ae)

**Comment by Johferson** [comment]
btw I forgot to put the full error message:

---------------------------
Error
---------------------------
[openfl.display.Shader] ERROR: Error compiling fragment shader
Fragment shader failed to compile with the following errors:
ERROR: 0:65: error(#132) Syntax error: "sample" parse error
ERROR: error(#273) 1 compilation errors.  No code generated


#version 100
      
				#ifdef GL_ES
				#ifdef GL_FRAGMENT_PRECISION_HIGH
					precision highp float;
				#else
					precision mediump float;
				#endif
				#endif
				
        varying float openfl_Alphav;
		varying vec4 openfl_ColorMultiplierv;
		varying vec4 openfl_ColorOffsetv;
		varying vec2 openfl_TextureCoordv;

		uniform bool openfl_HasColorTransform;
		uniform vec2 openfl_TextureSize;
		uniform sampler2D bitmap;

		uniform bool hasTransform;
		uniform bool hasColorTransform;

		vec4 flixel_texture2D(sampler2D bitmap, vec2 coord)
		{
			vec4 color = texture2D(bitmap, coord);
			if (!hasTransform)
			{
				return color;
			}

			if (color.a == 0.0)
			{
				return vec4(0.0, 0.0, 0.0, 0.0);
			}

			if (!hasColorTransform)
			{
				return color * openfl_Alphav;
			}

			color = vec4(color.rgb / color.a, color.a);

			mat4 colorMultiplier = mat4(0);
			colorMultiplier[0][0] = openfl_ColorMultiplierv.x;
			colorMultiplier[1][1] = openfl_ColorMultiplierv.y;
			colorMultiplier[2][2] = openfl_ColorMultiplierv.z;
			colorMultiplier[3][3] = openfl_ColorMultiplierv.w;

			color = clamp(openfl_ColorOffsetv + (color * colorMultiplier), 0.0, 1.0);

			if (color.a > 0.0)
			{
				return vec4(color.rgb * color.a * openfl_Alphav, color.a * openfl_Alphav);
			}
			return vec4(0.0, 0.0, 0.0, 0.0);
		}
	


        uniform vec2 size;
        uniform vec4 color;

        void main()
        {
            vec4 sample = flixel_texture2D(bitmap, openfl_TextureCoordv);
            if (sample.a == 0.) {
                float w = size.x / openfl_TextureSize.x;
                float h = size.y / openfl_TextureSize.y;

                if (flixel_texture2D(bitmap, vec2(openfl_TextureCoordv.x + w, openfl_TextureCoordv.y)).a != 0.
                || flixel_texture2D(bitmap, vec2(openfl_TextureCoordv.x - w, openfl_TextureCoordv.y)).a != 0.
                || flixel_texture2D(bitmap, vec2(openfl_TextureCoordv.x, openfl_TextureCoordv.y + h)).a != 0.
                || flixel_texture2D(bitmap, vec2(openfl_TextureCoordv.x, openfl_TextureCoordv.y - h)).a != 0.)
                    sample = color;
            }
            gl_FragColor = sample;
        }
    
---------------------------
OK   
---------------------------

**Comment by EliteMasterEric** [comment]
I believe I have a fix for this issue incoming.

**Comment by mariosbignuts** [comment]
hell yeah tysm eric we love you

**Comment by PixeltheProto** [comment]
so how do i fix this issue since im having it

**Comment by amyspark-ng** [comment]
> so how do i fix this issue since im having it

You'll have to wait for the update to come out

**Comment by EliteMasterEric** [comment]
This should be fixed in v0.3.3.

**Comment by Jh0sueB** [comment]
Pls help the version is v 1.0 and im playing a mod called late night city tales or smthing but when I play Lonely Saphire it says ---------------------------
Error
---------------------------
[openfl.display.Shader] ERROR: Error compiling fragment shader
Fragment shader failed to compile with the following errors:
ERROR: 0:59: error(#430) uniforms initialization is not allowed in GLSL 1.10.
ERROR: 0:60: error(#430) uniforms initialization is not allowed in GLSL 1.10.
ERROR: error(#273) 2 compilation errors.  No code generated


#ifdef GL_ES
				#ifdef GL_FRAGMENT_PRECISION_HIGH
				precision highp float;
				#else
				precision mediump float;
				#endif
				#endif
				

	

	varying float openfl_Alphav;
		varying vec4 openfl_ColorMultiplierv;
		varying vec4 openfl_ColorOffsetv;
		varying vec2 openfl_TextureCoordv;

		uniform bool openfl_HasColorTransform;
		uniform vec2 openfl_TextureSize;
		uniform sampler2D bitmap;

		uniform bool hasTransform;
		uniform bool hasColorTransform;

		vec4 flixel_texture2D(sampler2D bitmap, vec2 coord)
		{
			vec4 color = texture2D(bitmap, coord);
			if (!hasTransform)
			{
				return color;
			}

			if (color.a == 0.0)
			{
				return vec4(0.0, 0.0, 0.0, 0.0);
			}

			if (!hasColorTransform)
			{
				return color * openfl_Alphav;
			}

			color = vec4(color.rgb / color.a, color.a);

			mat4 colorMultiplier = mat4(0);
			colorMultiplier[0][0] = openfl_ColorMultiplierv.x;
			colorMultiplier[1][1] = openfl_ColorMultiplierv.y;
			colorMultiplier[2][2] = openfl_ColorMultiplierv.z;
			colorMultiplier[3][3] = openfl_ColorMultiplierv.w;

			color = clamp(openfl_ColorOffsetv + (color * colorMultiplier), 0.0, 1.0);

			if (color.a > 0.0)
			{
				return vec4(color.rgb * color.a * openfl_Alphav, color.a * openfl_Alphav);
			}
			return vec4(0.0, 0.0, 0.0, 0.0);
		}
	


	

	uniform float intensity = 0.35;

	uniform float blurSize = 1.0/512.0;

void main()

{

   vec4 sum = vec4(0);

   vec2 texcoord = openfl_TextureCoordv;

   int j;

   int i;



   //thank you! http://www.gamerendering.com/2008/10/11/gaussian-blur-filter-shader/ for the 

   //blur tutorial

   // blur in y (vertical)

   // take nine samples, with the distance blurSize between them

   sum += flixel_texture2D(bitmap, vec2(texcoord.x - 4.0*blurSize, texcoord.y)) * 0.05;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x - 3.0*blurSize, texcoord.y)) * 0.09;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x - 2.0*blurSize, texcoord.y)) * 0.12;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x - blurSize, texcoord.y)) * 0.15;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x, texcoord.y)) * 0.16;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x + blurSize, texcoord.y)) * 0.15;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x + 2.0*blurSize, texcoord.y)) * 0.12;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x + 3.0*blurSize, texcoord.y)) * 0.09;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x + 4.0*blurSize, texcoord.y)) * 0.05;

	

	// blur in y (vertical)

   // take nine samples, with the distance blurSize between them

   sum += flixel_texture2D(bitmap, vec2(texcoord.x, texcoord.y - 4.0*blurSize)) * 0.05;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x, texcoord.y - 3.0*blurSize)) * 0.09;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x, texcoord.y - 2.0*blurSize)) * 0.12;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x, texcoord.y - blurSize)) * 0.15;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x, texcoord.y)) * 0.16;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x, texcoord.y + blurSize)) * 0.15;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x, texcoord.y + 2.0*blurSize)) * 0.12;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x, texcoord.y + 3.0*blurSize)) * 0.09;

   sum += flixel_texture2D(bitmap, vec2(texcoord.x, texcoord.y + 4.0*blurSize)) * 0.05;



   //increase blur with intensity!

  gl_FragColor = sum*intensity + flixel_texture2D(bitmap, texcoord); 

  // if(sin(iTime) > 0.0)

   //    fragColor = sum * sin(iTime)+ texture(iChannel0, texcoord);

  // else

	//   fragColor = sum * -sin(iTime)+ texture(iChannel0, texcoord);

}

	

	

	
---------------------------
Aceptar   
---------------------------

**Comment by moxie-coder** [comment]
that's not our problem, also stop necro posting

**Comment by EliteMasterEric** [comment]
We don't provide technical support for mods.
