### ISSUE TITLE
Arrow key inconveniences 

### ISSUE THREAD

**Issue by Squirrel-God** [FunkinCrew/Funkin#2223]
When using the arrow keys, the screen does not lock and will scroll when pressing the up and down keys. This would normally not be a problem, and can be fixed by clicking the game, but that does not apply for FNF for some reason. I would like the option to not always have to play in fullscreen so is there a way to fix this and prevent scrolling during gameplay?

**Comment by ItzASecret** [comment]
Not sure if this is the games fault or not, but I did notice that.

**Comment by WaifuPop** [comment]
I'm having the same problem as well. I think it's the game for sure.

**Comment by NickMineBoom** [comment]
if you have a Fn key on your keyboard you can press Fn+W to make the arrow keys become WASD..It stops moving the window.I solved it that way cuz i play arrows aswell

**Comment by SilverT4** [comment]
> if you have a Fn key on your keyboard you can press Fn+W to make the arrow keys become WASD..It stops moving the window.I solved it that way cuz i play arrows aswell

@NickMineBoom I think that's your specific keyboard. Most keyboards don't have that functionality.

**Comment by Squirrel-God** [comment]
Update: this issue is now fixed
