### ISSUE TITLE
Bug Report: Week 8 Var missing when I restarted too many times?

### ISSUE THREAD

**Issue by SomeoneUnknownForReal** [FunkinCrew/Funkin#2224]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?
Newgrounds

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [X] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari
- [X] Opera GX (idk if it's chromium based but it probably is idk)

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
newest on newgrounds (0.3.0 prototype or some shit)

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
1. After I played the week 8 I challanged myself to get no misses in 2hot.
2. I was restarting many times and even instantly because yes
3. I started actually trying and on like an actual 5th attempt game crashed on the
bottle shot saying that a variable is missing which I guess is the the dark flash
effect so it's cool.

## Please describe your issue. Provide extensive detail and images if possible.

I don't have the image but there was a browser pop up like you know that one which is used to scam little kids by little kids.
In it said that an error occured or sth. Game was fine even after refreshing. Still reporting this as bug because it might be html, css, js or haxe problems.

**Comment by Aikoyori** [comment]
Opera GX is based on Chromium

**Comment by SilverT4** [comment]
Opera GX is indeed chromium based. It's a modified version of Opera, which is based on Chromium.

Additionally, [Opera GX players should be able to use the Newgrounds version just fine now.](https://twitter.com/ninja_muffin99/status/1785517657078259723)

**Comment by EliteMasterEric** [comment]
Very little info, user said they got an error popup but they didn't take a picture of it, since this is old I assume it got fixed.
