### ISSUE TITLE
Bug Report: seemingly death animation not loading.

### ISSUE THREAD

**Issue by AlfaFranek** [FunkinCrew/Funkin#2225]
I was playing Week End 1 on easy diffuculty and when I got to part of the song I haven't seen, it started lagging a shit ton, making me miss, resulting in my death from explosion, after which Newgrounds gave this message 
https://cdn.discordapp.com/attachments/699307541548498974/1235153209048301608/image.png?ex=66335591&is=66320411&hm=cc63735f9a2f72a6acc0d18d7d09daab8bb6ca58cd05410e50bb43dc1b031837&

It didn't crash but bug is a bug.

**Comment by SilverT4** [comment]
Please reupload your image directly. I'm assuming you use the desktop or web version of Discord. You can right click an image and select "Copy Image" to copy it, then paste it in a reply.

**Comment by EliteMasterEric** [comment]
Stale issue is presumably resolved, make a new issue if you can reproduce it in the latest version.
