### ISSUE TITLE
Bug Report: Able to select normal and hard dificulty whilste playing Erect Song using pause menu dificulty select 

### ISSUE THREAD

**Issue by Pucas01** [FunkinCrew/Funkin#2226]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [X] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [X] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
v0.3.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
To reproduce this bug you need to start Dadbattle Erect on Erect or nightmare difficulty, pause the game and click on change difficulty   
## Please describe your issue. Provide extensive detail and images if possible.
The bug is that your able to choose normal and hard when changing the difficulty in the pause menu, ive tested that this only happens on Dadbattle erect, when choosing either normal or hard the song will play but no notes will appear, as there is no chart for normal or hard on the erect version of dadbattle, i have attached a video of the bug!   

https://github.com/FunkinCrew/Funkin/assets/129163556/4d9c08ce-1e93-47ec-a80f-51b92a31de1b

**Comment by EliteMasterEric** [comment]
This should be fixed now.
