### ISSUE TITLE
Bug Report:  itch.io does not have the new update!

### ISSUE THREAD

**Issue by Mariogamer1000** [FunkinCrew/Funkin#2228]
When i try to download the game on itch.io does not have the new update

**Comment by Mariogamer1000** [comment]
> One word: W A I T.

why?

**Comment by adnt562378** [comment]
because when they first uploaded it (idk when but according to a lot of sources it did) it was broken as shit. So they have to fix all of the shit that went wrong with the native packages.

**Comment by SilverT4** [comment]
Not a bug. Developers intentionally removed the x64 Windows build due to how many crashes were occurring.

**Comment by adnt562378** [comment]
@SilverT4  ok

**Comment by adnt562378** [comment]
but at least I know more about this, and now I know why they aint releasing the source code yet

**Comment by NickMineBoom** [comment]
up  now
