### ISSUE TITLE
Crashing for the DOWNLOADED VERSION

### ISSUE THREAD

**Issue by Sonicfastblue** [FunkinCrew/Funkin#2235]
Everytime I get to the second song for the WeekEnd 1 or open the freeplay theres and error that appears, The second song for weekend 1 said null object while freeplay show a VERY long list.
I use WIndows 10 and the version is the latest version, which is prototype V.0.3.0 and I got my DOWNLOADED copy from the official Itch.io site.

**Comment by MarioSuper1234** [comment]
got this one too on week 7 story mode same version
i have windows 11
![obraz_2024-05-01_230651483](https://github.com/FunkinCrew/Funkin/assets/103045311/6c2462a9-77c1-4cbc-a2e4-b6f797f95b64)

**Comment by EliteMasterEric** [comment]
This is fixed in v0.3.2.
