### ISSUE TITLE
Bug Report: [Null Object Reference after certain songs end (E.g. Fresh, Pico, Satin Panties)]

### ISSUE THREAD

**Issue by ChaosChris124** [FunkinCrew/Funkin#2237]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [X] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
I am on version 0.3.0 (Prototype), also on windows 11.

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Simply just finish one of the listed songs, and you'll get the error, 100% of the time in my case.

## Please describe your issue. Provide extensive detail and images if possible.
After the end of certain songs, (see title). Game crashes with: Null Object Reference.
![image](https://github.com/FunkinCrew/Funkin/assets/94638196/d7bdde20-f0a0-4ed8-bd5f-1684e087a5bb)
There is little else to add to this, as this is all that happens.

**Comment by SilverT4** [comment]
Try running the game through a console. In File Explorer, press CTRL+L while in the folder where your FNF game files are stored. Type `cmd` and press Enter, then type `funkin` in the window that appears and press enter. When the game crashes, send the error message output here.

**Comment by ChaosChris124** [comment]
So, when i run it through command prompt and play, it doesn't seem to crash, so i closed it, and played it normally. Which is when it crashes. So I can't really send an error output.

**Comment by ChaosChris124** [comment]
Fixed with version 0.3.1.
