### ISSUE TITLE
Bug Report: Game crashes whenever Freeplay is opened - Windows Download

### ISSUE THREAD

**Issue by APenguin8582** [FunkinCrew/Funkin#2238]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

**Comment by Dark-Mario-Bros** [comment]
I've run into the same problem, I'm using the downloaded version from itch.io for Windows labelled Version 8 (in game v0.3.1)
basically I just open the game and go freeplay, and then the error from the first screenshot appears.

My system:
Windows 10 Pro 22H2
Intel i5-3570 CPU 3.40GHz
16GB ram
AMD R7 370 Video Card

![image](https://github.com/FunkinCrew/Funkin/assets/132832559/ca470094-1276-4313-b726-ec349fd548bb)
![image](https://github.com/FunkinCrew/Funkin/assets/132832559/b1c3c8d5-abb8-4421-9f8a-ab383b84e72a)
