### ISSUE TITLE
Linux build not available on itch.io

### ISSUE THREAD

**Issue by ThatOneCalculator** [FunkinCrew/Funkin#2240]
The macOS and Windows builds have been updated, but Linux seems to be stuck on the pre-0.3.0 version.

![image](https://github.com/FunkinCrew/Funkin/assets/44733677/b442d4c6-a5bc-4c41-ba59-550e55e63ca5)

**Comment by CharlesCatYT** [comment]
the devs probably dont have linux to compile it there, well they could do it on a vm but why would they?

**Comment by ThatOneCalculator** [comment]
1. Github actions exists
2. Cross-compilation exists
3. Linux was a platform already supported by FNF pre-0.3.0

**Comment by CharlesCatYT** [comment]
> 1. Github actions exists
> 2. Cross-compilation exists
> 3. Linux was a platform already supported by FNF pre-0.3.0

the 0.3.x source isnt out yet tho

**Comment by ThatOneCalculator** [comment]
That shouldn't make a difference for Linux builds being available. I'm not sure if you realize this, but even if a development machine is running Windows, FNF can compile to Windows, macOS, and Linux without needing to install those operating systems.

**Comment by AwesomeCoder412412** [comment]
> That shouldn't make a difference for Linux builds being available. I'm not sure if you realize this, but even if a development machine is running Windows, FNF can compile to Windows, macOS, and Linux without needing to install those operating systems. 

Admittedly, they can't test on Linux if they don't have a Linux computer, and chances are they don't. I agree that we need a Linux build, but I also understand why they don't provide one off the bat. I've built FNF from source code many times for many different platforms, and let me tell you, things can go wrong on one platform that don't happen on the other. The source code is supposed to be dropping very, very soon, and I'm sure a Linux build will follow very shortly afterwards using the GitHub CI or their own build system, or maybe some Linux users will build it from scratch. Regardless, Linux-specific bugs will be reported and fixed, and they'll hopefully provide an official build on itch after that.

**Comment by ThatOneCalculator** [comment]
I'm unsure why you're speaking authoritatively, but regardless, there were Linux builds for the previous versions. It's not as if I'm requesting builds for a platform that was never previously supported.

**Comment by SilverT4** [comment]
> FNF can compile to Windows, macOS, and Linux without needing to install those operating systems

Windows and Linux cannot compile macOS apps. They require Xcode, which is a **macOS only** development kit.

**Comment by ThatOneCalculator** [comment]
There's many cross-target toolchains that exist now – including building Haxe for macOS from non-macOS devices with `hxcpp` and the appropriate system toolchains.

**Comment by ThatOneCalculator** [comment]
But again, I have no clue why this is being argued (other than bikeshedding for the sake of bikeshedding), as official FNF Linux builds ***already existed*** for the previous major version.

**Comment by ThatOneCalculator** [comment]
Now that the source is public, I see even less of a reason for this to be blocked.

**Comment by EliteMasterEric** [comment]
Oh yeah I uploaded a linux build of v0.4

**Comment by ThatOneCalculator** [comment]
Seems that builds are still out of date with the latest release, are uploads being done by hand or automated with CI/CD?

![Screenshot_20240616-211512.png](https://github.com/FunkinCrew/Funkin/assets/44733677/80148058-0e5a-4e32-ad6e-644be664fefc)

**Comment by ThatOneCalculator** [comment]
Gotcha. It might be worth using something like https://github.com/marketplace/actions/itch-io-publish or the approach taken in https://ayowel.github.io/2023/01/22/github-itch-action.html , it doesn't seem to be incredibly complicated, and the Butler approach should work if you use another CI/CD platform like Jenkins instead of GitHub Actions :)
