### ISSUE TITLE
Bug Report: [error when running fnf]

### ISSUE THREAD

**Issue by Ciberxp** [FunkinCrew/Funkin#2241]
I installed fnf for windows 64 and when I run it, this comes out, please help me:
![error](https://github.com/FunkinCrew/Funkin/assets/123122796/0bb86d5d-86d3-49ec-978d-c16ccf632a03)

**Comment by SilverT4** [comment]
[Common issue for shaders on AMD GPUs with Haxe.](https://twitter.com/DiomaFX/status/1785508662469136856) Not much that can be done about this by the devs, I don't think. They'd have to make their own shader.

**Comment by EliteMasterEric** [comment]
Fixed in v0.3.3.

**Comment by Ciberxp** [comment]
> Corregido en v0.3.3.

that a new version came out?

**Comment by NotHyper-474** [comment]
> > Corregido en v0.3.3.
> 
> that a new version came out?

Yes

**Comment by Ciberxp** [comment]
> > > Corregido en v0.3.3.
> > 
> > 
> > que salio una nueva version?
> 
> Sí

do you have a link?

**Comment by NotHyper-474** [comment]
> > > > Corregido en v0.3.3.
> > > 
> > > 
> > > que salio una nueva version?
> > 
> > Sí
> 
> do you have a link?

Just redownload the game at Itch
io https://ninja-muffin24.itch.io/funkin

**Comment by Ciberxp** [comment]
> > > > > Corregido en v0.3.3.
> > > > 
> > > > 
> > > > que salio una nueva version?
> > > 
> > > 
> > > Si
> > 
> > 
> > ¿Tienes un enlace?
> 
> Simplemente vuelve a descargar el juego en Itch io https://ninja-muffin24.itch.io/funkin

ok thanks
