### ISSUE TITLE
Crash for DOWNLOADED Version

### ISSUE THREAD

**Issue by Sonicfastblue** [FunkinCrew/Funkin#2243]
THANK YOU FOR FIXING THE NULL OBJECT THING! but there is the freeplay thing where it will show this,
![image](https://github.com/FunkinCrew/Funkin/assets/100319067/53e76dbc-2a6b-4353-8f69-cd882e1176e1)
Still on WINDOWS with the version being, V0.3.1

**Comment by SilverT4** [comment]
[Common issue for shaders on AMD GPUs.](https://twitter.com/DiomaFX/status/1785508662469136856) Not much that can be done, I don't think.

**Comment by EliteMasterEric** [comment]
Duplicate of #2220.
