### ISSUE TITLE
Bug Report: On the New week death animation, you can see the outline of the sprite box and the background color is a shade brighter than the background so it looks like a box is around the death animation

### ISSUE THREAD

**Issue by SirWeenieLordofBaltimore** [FunkinCrew/Funkin#2250]
[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [x ] MS Edge
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
3.1

## Please describe your issue. Provide extensive detail and images if possible.

The death animation after losing as Pico in the new week shows the borders (box) around the animation when he dies, the box is a shade different than the pitch-black background so the purplish box is shown behind the full death animation.

**Comment by EliteMasterEric** [comment]
Reproduced, someone fixed this i think
