### ISSUE TITLE
Bug Report: Null Object Reference

### ISSUE THREAD

**Issue by MrStuip** [FunkinCrew/Funkin#2253]
=====================
 Funkin Crash Report
=====================

Generated by: Friday Night Funkin' - v0.3.1
  Git hash: 2c48b12 (CLEAN)
System timestamp: 2024-05-02-12-23-58
Driver info: OpenGL Vendor=ATI Technologies Inc. Version=4.6.0 Compatibility Profile Context 22.20.44.221025 Renderer=AMD Radeon(TM) Graphics GLSL=4.60
Platform: Windows
Render method: DRAW_TILES

=====================

HXCPP-Immix:
- Memory Used: 1694895356 bytes
- Memory Reserved: 1743517308 bytes
- Memory Current Pool: 1694898428 bytes
- Memory Large Pool: 1664903292 bytes
- HXCPP Debugger: Disabled
- HXCPP Exp Generational Mode: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Debug Link: Disabled
- HXCPP Stack Trace: Enabled
- HXCPP Stack Trace Line Numbers: Enabled
- HXCPP Pointer Validation: Enabled
- HXCPP Profiler: Disabled
- HXCPP Local Telemetry: Disabled
- HXCPP C++11: Disabled
- Source Annotation: Disabled

=====================

Flixel Current State: funkin.play.PlayState

=====================

Haxelibs: 
- discord_rpc git(https://github.com/Aidan63/linc_discord-rpc/:2d83fa863ef0c1eace5f1cf67c3ac315d1a3a8a5
- flixel git(https://github.com/FunkinCrew/flixel/:a7d8e3bad89a0a3506a4714121f73d8e34522c49
- flixel-addons git(https://github.com/FunkinCrew/flixel-addons/:a523c3b56622f0640933944171efed46929e360e
- flixel-text-input haxelib(1.1.0)
- flixel-ui git(https://github.com/HaxeFlixel/flixel-ui/:719b4f10d94186ed55f6fef1b6618d32abec8c15
- flxanimate git(https://github.com/FunkinCrew/flxanimate/:17e0d59fdbc2b6283a5c0e4df41f1c7f27b71c49
- format haxelib(3.5.0)
- funkin.vis git(https://github.com/FunkinCrew/funkVis/:98c9db09f0bbfedfe67a84538a5814aaef80bdea
- hamcrest haxelib(3.0.0)
- haxeui-core git(https://github.com/haxeui/haxeui-core/:0212d8fdfcafeb5f0d5a41e1ddba8ff21d0e183b
- haxeui-flixel git(https://github.com/haxeui/haxeui-flixel/:63a906a6148958dbfde8c7b48d90b0693767fd95
- hscript haxelib(2.5.0)
- hxCodec git(https://github.com/FunkinCrew/hxCodec/:c0c7f2680cc190c932a549c2e2fdd9b0ba2bd10e
- hxcpp haxelib(4.3.2)
- hxcpp-debug-server git(https://github.com/FunkinCrew/hxcpp-debugger/hxcpp-debug-server:147294123f983e35f50a966741474438069a7a8f
- hxp haxelib(1.2.2)
- json2object git(https://github.com/FunkinCrew/json2object/:a8c26f18463c98da32f744c214fe02273e1823fa
- lime git(https://github.com/FunkinCrew/lime/:391f15440638e209cabf6d820e63e161c41b2f4d
- mconsole git(https://github.com/massive-oss/mconsole/:06c0499ed8f80628a0e6e55ffa32c3cbd688a838
- mcover git(https://github.com/massive-oss/mcover/src:c3c47cd682b0b202a41caee95321989391b617ef
- mockatoo git(https://github.com/FunkinCrew/mockatoo/src:13d77a0a8eaf5e789ef5dae6cd33eee812deda36
- munit git(https://github.com/FunkinCrew/MassiveUnit/src:f61be7f7ba796595f45023ca65164a485aba0e7e
- openfl git(https://github.com/FunkinCrew/openfl/:228c1b5063911e2ad75cef6e3168ef0a4b9f9134
- polymod git(https://github.com/larsiusprime/polymod/:8553b800965f225bb14c7ab8f04bfa9cdec362ac
- thx.core git(https://github.com/FunkinCrew/thx.core/:22605ff44f01971d599641790d6bae4869f7d9f4
- thx.semver git(https://github.com/FunkinCrew/thx.semver/:cf8d213589a2c7ce4a59b0fdba9e8ff36bc029fa

=====================

Null Object Reference
  in flixel/graphics/tile/FlxDrawTrianglesItem.hx#63
  in flixel/FlxCamera.hx#774
  in flixel/FlxGame.hx#873
  in flixel/FlxGame.hx#566
  in openfl/events/EventDispatcher.hx#402
  in openfl/display/DisplayObject.hx#1399

**Comment by EliteMasterEric** [comment]
Not sure what would cause this one...

**Comment by Hundrec** [comment]
It might be safe to assume that the crash has been fixed since 0.3.1

**Comment by Entiego** [comment]
go to C:/Users/[your user name]/AppData/Roaming/FunkinCrew and delete file Funkin1.sol
