### ISSUE TITLE
Sprite work in week 4

### ISSUE THREAD

**Issue by Extractor1907** [FunkinCrew/Funkin#226]
While playing in week 4, while in a long note, the sprite resets entirely instead of going back a few frames, this may be because there might be less animated sprites for each action, or maybe it's a code oversight for that week, I noticed it while playing High, if that's any help

**Comment by regulad** [comment]
I think that might've been intentional, look at the `CHANGELOG.md` change on this commit https://github.com/ninjamuffin99/Funkin/commit/671dced3927c1eaf09067ad94f55915c57bc9108

Still weird tho
