### ISSUE TITLE
Bug Report: [Tried to access "zIndex", but it is not a valid field or method]

### ISSUE THREAD

**Issue by RngValue** [FunkinCrew/Funkin#2261]
![image](https://github.com/FunkinCrew/Funkin/assets/104089072/d5b438e2-4fd6-48fe-8ee6-215db2b7b7c0)

[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

## Please describe your issue. Provide extensive detail and images if possible.
Happened suddenly right after losing in 2hot (story mode).
Not sure if it was because I alt+tabbed, but the game wouldn't let me interact with the error message and would minimize itself after clicking anywhere on the screen. (needed task manager to close the game)

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
I was not able to reproduce it, but considering the function name "darkenStageProps" and it trying to access "zIndex" from a nonexistent object, it could be that a background element unloaded inappropriately.

**Comment by Hundrec** [comment]
Oh no, it's spelled "TwoHOT" here...
Anyway, can anyone replicate this in 0.5.0?

**Comment by RngValue** [comment]
> Oh no, it's spelled "TwoHOT" here... Anyway, can anyone replicate this in 0.5.0?

bruh, it's an old bug report. Those null references should be fixed by now

**Comment by Hundrec** [comment]
Right, I'm commenting on old issues to resolve them. Thanks for closing this!
