### ISSUE TITLE
Bug Report: ChartEditorToolboxHandler null error with events

### ISSUE THREAD

**Issue by BlueColorsin** [FunkinCrew/Funkin#2269]
FNF 0.3.2 || Version 11 Issue

In the chart editor while dealing with events there is a issue when the content of a box is "" or 0
the haxeui interposer or haxe itself reads this as null which is why I think it reads x as not in this "event data form"
could be other reasons but still causing a annoying crash

This was done with the FocusCamera event by the way
and the way it is usually done for me is, place down a event with a 0 or a empty string box and then open and close the playtest then open the event details
boom crash 

[crash-2024-05-03-21-23-48.log](https://github.com/FunkinCrew/Funkin/files/15206401/crash-2024-05-03-21-23-48.log)

**Comment by Hundrec** [comment]
I think chart editor event crashes are now fixed (thankfully), so we can close this issue.
