### ISSUE TITLE
Up anamation plays when song is being started

### ISSUE THREAD

**Issue by regulad** [FunkinCrew/Funkin#227]
See the image:
![image](https://user-images.githubusercontent.com/52430642/105208384-a45e8c80-5b16-11eb-9bf3-5ffb52a04cb8.png)

**Comment by ninjamuffin99** [comment]
semi intentional, i ran into an issue with the game where if no animation has played yet it would glitch. This was a quick and dumb workaround LOL!

**Comment by regulad** [comment]
yikes lol
