### ISSUE TITLE
Bug Report: Holding on a song in the freeplay menu brings up your High-Score or Clear Percentage by one.

### ISSUE THREAD

**Issue by WuffGaming** [FunkinCrew/Funkin#2272]
Holding on a song in the freeplay menu may bring up on of the stats. It should be noted that these extra stat changes go away if you hover on another song and back into the song. The clear percentage increasing by one seems to be also only when you haven't completed the song.

**Comment by EliteMasterEric** [comment]
This is purely a display issue, it should be fixed in the next update.

**Comment by Hundrec** [comment]
This should be fixed now, so you can close this issue.
