### ISSUE TITLE
Bug Report:fragment shader error?

### ISSUE THREAD

**Issue by rinf-ds** [FunkinCrew/Funkin#2274]
![Captura fnf error](https://github.com/FunkinCrew/Funkin/assets/98434034/6cb9b9f5-f2d6-4556-8201-fa6ca850e3c1)
this error ALWAYS appears when i try to enter freeplay

**Comment by afoxfan** [comment]
same, heres the log of mine btw:
ustom preloader...
source/funkin/ui/transition/preload/FunkinPreloader.hx:931: Preloader state: DownloadingAssets (100%, 0.189s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:934: Preloader state: PreloadingPlayAssets (100%, 0.326s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:934: Preloader state: PreloadingPlayAssets (0%, 0.383s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:934: Preloader state: PreloadingPlayAssets (40%, 0.424s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:934: Preloader state: PreloadingPlayAssets (55%, 0.439s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:934: Preloader state: PreloadingPlayAssets (73%, 0.456s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:937: Preloader state: InitializingScripts (0%, 0.706s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:940: Preloader state: CachingGraphics (0%, 0.772s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:940: Preloader state: CachingGraphics (0%, 0.811s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:940: Preloader state: CachingGraphics (65%, 0.877s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:940: Preloader state: CachingGraphics (76%, 0.888s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:940: Preloader state: CachingGraphics (91%, 0.903s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:943: Preloader state: CachingAudio (0%, 0.921s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:943: Preloader state: CachingAudio (0%, 0.936s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:943: Preloader state: CachingAudio (14%, 0.951s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:943: Preloader state: CachingAudio (30%, 0.967s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:943: Preloader state: CachingAudio (47%, 0.984s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:943: Preloader state: CachingAudio (63%, 1s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:943: Preloader state: CachingAudio (78%, 1.015s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:943: Preloader state: CachingAudio (95%, 1.032s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:946: Preloader state: CachingData (0%, 1.048s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:946: Preloader state: CachingData (0%, 1.065s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:946: Preloader state: CachingData (16%, 1.081s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:946: Preloader state: CachingData (30%, 1.095s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:946: Preloader state: CachingData (47%, 1.112s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:946: Preloader state: CachingData (62%, 1.127s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:946: Preloader state: CachingData (78%, 1.143s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:946: Preloader state: CachingData (94%, 1.15900024414063s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:949: Preloader state: ParsingSpritesheets (0%, 1.175s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:949: Preloader state: ParsingSpritesheets (0%, 1.191s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:949: Preloader state: ParsingSpritesheets (18%, 1.209s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:949: Preloader state: ParsingSpritesheets (36%, 1.227s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:949: Preloader state: ParsingSpritesheets (52%, 1.243s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:949: Preloader state: ParsingSpritesheets (65%, 1.257s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:949: Preloader state: ParsingSpritesheets (80%, 1.27100024414062s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:949: Preloader state: ParsingSpritesheets (95%, 1.287s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:952: Preloader state: ParsingStages (0%, 1.304s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:952: Preloader state: ParsingStages (0%, 1.319s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:952: Preloader state: ParsingStages (17%, 1.336s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:952: Preloader state: ParsingStages (33%, 1.352s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:952: Preloader state: ParsingStages (49%, 1.368s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:952: Preloader state: ParsingStages (64%, 1.383s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:952: Preloader state: ParsingStages (82%, 1.401s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:952: Preloader state: ParsingStages (96%, 1.415s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:955: Preloader state: ParsingCharacters (0%, 1.43s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:955: Preloader state: ParsingCharacters (0%, 1.448s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:955: Preloader state: ParsingCharacters (15%, 1.463s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:955: Preloader state: ParsingCharacters (31%, 1.479s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:955: Preloader state: ParsingCharacters (47%, 1.495s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:955: Preloader state: ParsingCharacters (64%, 1.512s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:955: Preloader state: ParsingCharacters (80%, 1.528s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:955: Preloader state: ParsingCharacters (96%, 1.54400024414063s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:958: Preloader state: ParsingSongs (0%, 1.56s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:958: Preloader state: ParsingSongs (0%, 1.576s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:958: Preloader state: ParsingSongs (14%, 1.591s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:958: Preloader state: ParsingSongs (34%, 1.61s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:958: Preloader state: ParsingSongs (48%, 1.625s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:958: Preloader state: ParsingSongs (63%, 1.64s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:958: Preloader state: ParsingSongs (79%, 1.656s)
source/funkin/ui/transition/preload/FunkinPreloader.hx:958: Preloader state: ParsingSongs (96%, 1.673s)
source/funkin/util/logging/CrashHandler.hx:34: [LOG] Enabling standard uncaught error handler...
source/funkin/util/logging/CrashHandler.hx:38: [LOG] Enabling C++ critical error handler...
source/funkin/util/logging/CrashHandler.hx:226: ERROR HANDLER STATUS: true
source/funkin/util/logging/CrashHandler.hx:229: Define: openfl_enable_handle_error is enabled
source/funkin/util/logging/CrashHandler.hx:237: Define: openfl_disable_handle_error is disabled
source/funkin/modding/PolymodHandler.hx:76: Initializing Polymod (using all mods)...
source/funkin/modding/PolymodHandler.hx:304: Scanning the mods folder...
source/funkin/modding/PolymodErrorHandler.hx:79: [INFO-] LOADING MOD - Searching for ZIP files in mods
source/funkin/modding/PolymodErrorHandler.hx:79: [INFO-] LOADING MOD - Found 0 files in modRoot.
source/funkin/modding/PolymodHandler.hx:315: Found 0 mods when scanning.
source/funkin/modding/PolymodHandler.hx:113: You attempted to load zero mods.
source/funkin/modding/PolymodErrorHandler.hx:89: [WARN-] Scripted class FunkinSound has already been imported.
source/funkin/modding/PolymodErrorHandler.hx:89: [WARN-] Scripted class FunkinSound has already been imported.
source/funkin/modding/PolymodErrorHandler.hx:79: [INFO-] Parsed and registered 46 scripted classes.
source/funkin/modding/PolymodHandler.hx:164: Mod loading complete. We loaded no mods / 0 mods.
source/funkin/save/Save.hx:44: [SAVE] Loading save...
source/funkin/save/Save.hx:662: [SAVE] Loading save from slot 1...
source/funkin/save/Save.hx:689: [SAVE] Loaded save data.
source/funkin/ui/options/FunkinSoundTray.hx:75: Custom tray added!
source/funkin/InitState.hx:161: Parsing game data...
source/funkin/data/event/SongEventRegistry.hx:39: Instantiating 6 built-in song events...
source/funkin/data/event/SongEventRegistry.hx:49:   Loaded built-in song event: (ZoomCamera)
source/funkin/data/event/SongEventRegistry.hx:49:   Loaded built-in song event: (SetCameraBop)
source/funkin/data/event/SongEventRegistry.hx:49:   Loaded built-in song event: (PlayAnimation)
source/funkin/data/event/SongEventRegistry.hx:49:   Loaded built-in song event: (FocusCamera)
source/funkin/data/BaseRegistry.hx:211: [SONG] Parsing 10 scripted entries...
source/funkin/play/song/Song.hx:524: Fetching song metadata for darnell
source/funkin/data/BaseRegistry.hx:211: [SONG] Successfully created scripted entry (DarnellSong = darnell)
source/funkin/play/song/Song.hx:524: Fetching song metadata for lit-up
source/funkin/data/BaseRegistry.hx:211: [SONG] Successfully created scripted entry (LitUpSong = lit-up)
source/funkin/play/song/Song.hx:524: Fetching song metadata for guns
source/funkin/data/BaseRegistry.hx:211: [SONG] Successfully created scripted entry (GunsSong = guns)
source/funkin/play/song/Song.hx:524: Fetching song metadata for stress
source/funkin/data/BaseRegistry.hx:211: [SONG] Successfully created scripted entry (StressSong = stress)
source/funkin/play/song/Song.hx:524: Fetching song metadata for ugh
source/funkin/data/BaseRegistry.hx:211: [SONG] Successfully created scripted entry (UghSong = ugh)
source/funkin/play/song/Song.hx:524: Fetching song metadata for thorns
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/BaseRegistry.hx:211: [SONG] Successfully created scripted entry (ThornsSong = thorns)
source/funkin/play/song/Song.hx:524: Fetching song metadata for senpai
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/BaseRegistry.hx:211: [SONG] Successfully created scripted entry (SenpaiSong = senpai)
source/funkin/play/song/Song.hx:524: Fetching song metadata for 2hot
source/funkin/data/BaseRegistry.hx:211: [SONG] Successfully created scripted entry (TwoHOTSong = 2hot)
source/funkin/play/song/Song.hx:524: Fetching song metadata for roses
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/BaseRegistry.hx:211: [SONG] Successfully created scripted entry (RosesSong = roses)
source/funkin/play/song/Song.hx:524: Fetching song metadata for blazin
source/funkin/data/BaseRegistry.hx:211: [SONG] Successfully created scripted entry (BlazinSong = blazin)
source/funkin/data/BaseRegistry.hx:211: [SONG] Parsing 16 unscripted entries...
source/funkin/play/song/Song.hx:524: Fetching song metadata for philly-nice
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(philly-nice)
source/funkin/play/song/Song.hx:524: Fetching song metadata for eggnog
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(eggnog)
source/funkin/play/song/Song.hx:524: Fetching song metadata for cocoa
source/funkin/data/song/SongRegistry.hx:436:   [WARN] Could not locate file assets/data/songs/cocoa/cocoa-metadata-erect.json
source/funkin/play/song/Song.hx:150:   FAILED to load variation: erect
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(cocoa)
source/funkin/play/song/Song.hx:524: Fetching song metadata for fresh
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(fresh)
source/funkin/play/song/Song.hx:524: Fetching song metadata for monster
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(monster)
source/funkin/play/song/Song.hx:524: Fetching song metadata for satin-panties
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(satin-panties)
source/funkin/play/song/Song.hx:524: Fetching song metadata for bopeebo
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(bopeebo)
source/funkin/play/song/Song.hx:524: Fetching song metadata for tutorial
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(tutorial)
source/funkin/play/song/Song.hx:524: Fetching song metadata for pico
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(pico)
source/funkin/play/song/Song.hx:524: Fetching song metadata for dadbattle
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(dadbattle)
source/funkin/play/song/Song.hx:524: Fetching song metadata for spookeez
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(spookeez)
source/funkin/play/song/Song.hx:524: Fetching song metadata for south
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(south)
source/funkin/play/song/Song.hx:524: Fetching song metadata for blammed
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(blammed)
source/funkin/play/song/Song.hx:524: Fetching song metadata for winter-horrorland
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(winter-horrorland)
source/funkin/play/song/Song.hx:524: Fetching song metadata for milf
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(milf)
source/funkin/play/song/Song.hx:524: Fetching song metadata for high
source/funkin/play/song/Song.hx:145:   Loaded variation: erect
source/funkin/data/song/SongRegistry.hx:103:   Loaded entry data: Song(high)
source/funkin/data/BaseRegistry.hx:211: [LEVEL] Parsing 1 scripted entries...
source/funkin/data/BaseRegistry.hx:211: [LEVEL] Successfully created scripted entry (Weekend1Level = weekend1)
source/funkin/data/BaseRegistry.hx:211: [LEVEL] Parsing 8 unscripted entries...
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Level(week6)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Level(week1)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Level(week7)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Level(week2)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Level(week3)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Level(week4)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Level(tutorial)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Level(week5)
source/funkin/data/BaseRegistry.hx:211: [NOTESTYLE] Parsing 0 scripted entries...
source/funkin/data/BaseRegistry.hx:211: [NOTESTYLE] Parsing 2 unscripted entries...
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: NoteStyle(funkin)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: NoteStyle(pixel)
source/funkin/data/BaseRegistry.hx:211: [CONVERSATION] Parsing 0 scripted entries...
source/funkin/data/BaseRegistry.hx:211: [CONVERSATION] Parsing 4 unscripted entries...
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Conversation(roses)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Conversation(thorns)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Conversation(senpai)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Conversation(roses-censored)
source/funkin/data/BaseRegistry.hx:211: [DIALOGUEBOX] Parsing 2 scripted entries...
source/funkin/data/BaseRegistry.hx:211: [DIALOGUEBOX] Successfully created scripted entry (RosesDialogueBox = roses)
source/funkin/data/BaseRegistry.hx:211: [DIALOGUEBOX] Successfully created scripted entry (ThornsDialogueBox = thorns)
source/funkin/data/BaseRegistry.hx:211: [DIALOGUEBOX] Parsing 1 unscripted entries...
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: DialogueBox(default)
source/funkin/data/BaseRegistry.hx:211: [SPEAKER] Parsing 0 scripted entries...
source/funkin/data/BaseRegistry.hx:211: [SPEAKER] Parsing 4 unscripted entries...
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Speaker(spirit)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Speaker(senpai)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Speaker(bf-pixel)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Speaker(senpai-angry)
source/funkin/data/BaseRegistry.hx:211: [ALBUM] Parsing 0 scripted entries...
source/funkin/data/BaseRegistry.hx:211: [ALBUM] Parsing 3 unscripted entries...
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Album(volume3)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Album(volume1)
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: Album(volume2)
source/funkin/data/BaseRegistry.hx:211: [STAGE] Parsing 8 scripted entries...
source/funkin/data/BaseRegistry.hx:211: [STAGE] Successfully created scripted entry (LimoRideStage = limoRide)
source/funkin/data/BaseRegistry.hx:211: [STAGE] Successfully created scripted entry (SchoolStage = school)
source/funkin/data/BaseRegistry.hx:211: [STAGE] Successfully created scripted entry (TankmanBattlefieldStage = tankmanBattlefield)
source/funkin/data/BaseRegistry.hx:211: [STAGE] Successfully created scripted entry (PhillyBlazinStageNew = phillyBlazin)
source/funkin/data/BaseRegistry.hx:211: [STAGE] Successfully created scripted entry (PhillyStreetsStage = phillyStreets)
source/funkin/data/BaseRegistry.hx:211: [STAGE] Successfully created scripted entry (SchoolEvilStage = schoolEvil)
source/funkin/data/BaseRegistry.hx:211: [STAGE] Successfully created scripted entry (SpookyMansionStage = spookyMansion)
source/funkin/data/BaseRegistry.hx:211: [STAGE] Successfully created scripted entry (PhillyTrainStage = phillyTrain)
source/funkin/data/BaseRegistry.hx:211: [STAGE] Parsing 3 unscripted entries...
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: (x: 0 | y: 0 | w: 0 | h: 0 | visible: true | velocity: (x: 0 | y: 0))
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: (x: 0 | y: 0 | w: 0 | h: 0 | visible: true | velocity: (x: 0 | y: 0))
source/funkin/data/BaseRegistry.hx:120:   Loaded entry data: (x: 0 | y: 0 | w: 0 | h: 0 | visible: true | velocity: (x: 0 | y: 0))
source/funkin/play/character/CharacterData.hx:46: [CHARACTER] Parsing all entries...
source/funkin/play/character/CharacterData.hx:55:   Fetching data for 28 characters...
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: spirit
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: gf-tankmen
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: senpai
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: pico-speaker
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: darnell-blazin
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: gf-pixel
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: gf
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: darnell
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: parents-christmas
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: bf
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: bf-pixel
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: bf-christmas
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: gf-christmas
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: pico
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: monster
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: nene
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: spooky
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: bf-car
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: pico-playable
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: tankman
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: bf-holding-gf
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: gf-car
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: monster-christmas
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: tankman-atlas
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: dad
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: mom-car
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: pico-blazin
source/funkin/play/character/CharacterData.hx:63:     Loaded character data: senpai-angry
source/funkin/play/character/CharacterData.hx:83:   Instantiating 6 (Sparrow) scripted characters...
source/funkin/play/character/CharacterData.hx:89:   Initialized character Pico (Speaker Shooter)
source/funkin/play/character/CharacterData.hx:89:   Initialized character Girlfriend
source/funkin/play/character/CharacterData.hx:89:   Initialized character Mommy and Daddy (Festive)
source/funkin/play/character/CharacterData.hx:89:   Initialized character Tankman
source/funkin/play/character/CharacterData.hx:89:   Initialized character Nene
source/funkin/play/character/CharacterData.hx:89:   Initialized character Darnell
source/funkin/play/character/CharacterData.hx:103:   Instantiating 1 (Packer) scripted characters...
source/funkin/play/character/CharacterData.hx:122:   Instantiating 3 (Multi-Sparrow) scripted characters...
source/funkin/play/character/CharacterData.hx:141:   Instantiating 3 (Animate Atlas) scripted characters...
source/funkin/play/character/CharacterData.hx:186:   Successfully loaded 28 stages.
source/funkin/modding/module/ModuleHandler.hx:27: [MODULEHANDLER] Loading module cache...
source/funkin/modding/module/ModuleHandler.hx:30:   Instantiating 0 modules...
source/funkin/modding/module/ModuleHandler.hx:48: [MODULEHANDLER] Module cache loaded.
source/funkin/InitState.hx:181: Parsing game data took: 2923 ms
source/funkin/PlayerSettings.hx:97: loading player settings for id: 1
source/funkin/PlayerSettings.hx:111: Loading keyboard control scheme from user save
source/funkin/InitState.hx:234: Command line args: { args => [], chart => { shouldLoadChart => false, chartPath => null } }
source/Main.hx:125: hxcpp_debug_server is disabled! This build does not support debugging.
source/funkin/Conductor.hx:538: Done mapping time changes: [SongTimeChange(0ms,102bpm)]
source/funkin/graphics/FunkinCamera.hx:247: disposing textures
source/funkin/ui/freeplay/FreeplayState.hx:214: 1280
source/funkin/ui/freeplay/FreeplayState.hx:215: 1
source/funkin/ui/freeplay/FreeplayState.hx:216: 1
source/funkin/ui/freeplay/FreeplayState.hx:217: 1
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 26
Called from ApplicationMain::create ApplicationMain.hx line 135
Called from lime.app.Application::exec lime/app/Application.hx line 151
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 147
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 381
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 2111
Called from openfl.display.OpenGLRenderer::__render openfl/display/OpenGLRenderer.hx line 764
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 17
Called from openfl.display._internal.Context3DDisplayObject::renderDrawable openfl/display/_internal/Context3DDisplayObject.hx line 68
Called from openfl.display._internal.Context3DShape::render openfl/display/_internal/Context3DShape.hx line 38
Called from openfl.display._internal.Context3DGraphics::render openfl/display/_internal/Context3DGraphics.hx line 611
Called from openfl.display.OpenGLRenderer::__initShaderBuffer openfl/display/OpenGLRenderer.hx line 590
Called from openfl.display.OpenGLRenderer::__initGraphicsShader openfl/display/OpenGLRenderer.hx line 576
Called from openfl.display.Shader::__init openfl/display/Shader.hx line 549
Called from openfl.display.Shader::__initGL openfl/display/Shader.hx line 621
Called from openfl.display.Shader::__createGLProgram openfl/display/Shader.hx line 436
Called from openfl.display.Shader::__createGLShader openfl/display/Shader.hx line 424
Called from lime.utils.Log::error lime/utils/Log.hx line 34
