### ISSUE TITLE
Bug Report: When I try to start any option in the main menu I am redirected to the chart editor

### ISSUE THREAD

**Issue by Arklyay** [FunkinCrew/Funkin#2275]
I can't access the weeks or freepay or any other option.
![ç](https://github.com/FunkinCrew/Funkin/assets/168933633/1cf2bdb8-f16f-4fa2-beb8-6dbfce91a939)
![ñ](https://github.com/FunkinCrew/Funkin/assets/168933633/c9740c7e-7968-4e2c-b238-b2fd30ba537e)
![Sin título](https://github.com/FunkinCrew/Funkin/assets/168933633/2db24125-7149-4891-886a-2c360da82718)

**Comment by SilverT4** [comment]
I honestly wonder how many people just clear out the bug report template.

Regardless, can you try getting a screen recording? From the screenshots, it looks like you are on at least Windows 10. You can press the Windows, Alt, and R keys at the same time to record a video.

Once you've recorded the issue, you can find it in `%UserProfile%\Videos\Captures`.

**Comment by Hundrec** [comment]
My only guess is that the debug options button was bound to the Enter key? It honestly doesn't seem like the game's issue

**Comment by Hundrec** [comment]
I stand by my above theory.
This issue is stale and should be closed.
