### ISSUE TITLE
Bug Report: The last song of weekend 1 crashes upon entering it in the itch.io build, but ONLY if you are in fullscreen when entering the song

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/Funkin#2277]
### If you are playing the game in a browser, what site are you playing it from?

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [X] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Enter Weekend 1 in story mode, then complete 2Hot in fullscreen and wait until the next song

## Please describe your issue. Provide extensive detail and images if possible.

![image](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/98499e9f-9ded-4f21-bbb3-7ad012fd3f4a/a2c1b352-6691-440e-8b05-9fd8529fd427?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi85ODQ5OWU5Zi05ZGVkLTRmMjEtYmJiMy03YWQwMTJmZDNmNGEvYTJjMWIzNTItNjY5MS00NDBlLThiMDUtOWZkODUyOWZkNDI3IiwiaWF0IjoxNzE3MTEwMjg0LCJleHAiOjMzMjg3NjcwMjg0fQ.CUA2PA-3YFRCfpttV0Q7Mn1r5Au5i1qcT7hsuIvypj8)

This is the error that appears for doing that. It's not just me that got this error.

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

**Comment by SilverT4** [comment]
Null object reference my beloved...

Try to run the game through a command prompt. To do this in Windows 11, click the address bar in File Explorer while you're in the folder containing your game files. This will allow you to input text. From there, type "cmd" and press enter. Then, type "funkin" and press enter.

Once the game crashes again, paste the TRACE (any lines with "Called from" in them) in a code block (\`\`\` before and after)

**Comment by biomseed** [comment]
> Null object reference my beloved...
> 
> Try to run the game through a command prompt. To do this in Windows 11, click the address bar in File Explorer while you're in the folder containing your game files. This will allow you to input text. From there, type "cmd" and press enter. Then, type "funkin" and press enter.
> 
> Once the game crashes again, paste the TRACE (any lines with "Called from" in them) in a code block (``` before and after)

This issue happens for EVERYBODY. Anybody can do that now, even the devs. I don't need to show a crash log either because the crash log works now. The normal "null object reference" is gone from the game now, the one that had no text with it was a bug with the crash handler and it's fixed.

**Comment by biomseed** [comment]
It's not just in fullscreen sometimes, it must have something to do with changing in and out of fullscreen

**Comment by Hundrec** [comment]
This bug has probably been resolved as of 0.5.1 (hopefully!)

**Comment by biomseed** [comment]
> This bug has probably been resolved as of 0.5.1 (hopefully!)

I'm glad this bug has hopefully PROBABLY been resolved. I'm glad that's a possibility.

**Comment by Hundrec** [comment]
> > This bug has probably been resolved as of 0.5.1 (hopefully!)
> 
> 
> 
> I'm glad this bug has hopefully PROBABLY been resolved. I'm glad that's a possibility.

Gotta hope for the best and account for the undesirable

**Comment by biomseed** [comment]
Resolved
