### ISSUE TITLE
Bug Report: [The cinematic bit at the end of 2hot doesn't load, it instead just cuts to black after the song and goes straight into Blazin'. ]

### ISSUE THREAD

**Issue by BigBuffBurrito** [FunkinCrew/Funkin#2278]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Please describe your issue. Provide extensive detail and images if possible.

The cinematic bit at the end of 2hot doesn't load ~~specifically on Opera GX I've found~~. it instead just cuts to black after the song and goes straight into Blazin'. Opened the game in chrome and it worked fine.(NOTE: this was done on a new tab with no accounts signed in.)
(edit)
Upon reopening chrome and signing in to my google account, while going through weekend 1 again once again after beating 2hot, the game immediately goes to the loading screen and starts Blazin'.

**Comment by EliteMasterEric** [comment]
Figured out the cause for this earlier. It happens if you lose during the song.

**Comment by Hundrec** [comment]
This issue has probably been resolved as of 0.5.1

**Comment by EliteMasterEric** [comment]
Yep
