### ISSUE TITLE
In Week 5, the score is white text on a while background, making it almost impossible to see.

### ISSUE THREAD

**Issue by regulad** [FunkinCrew/Funkin#228]
See the image below
![image](https://user-images.githubusercontent.com/52430642/105209653-12578380-5b18-11eb-98b1-144cc8659655.png)

**Comment by M1K3Altz** [comment]
I made a file fix to make the snow more like the evil snow texture. I just hope that they apply it to the game.
Just don't close this iss
![fgSnow](https://user-images.githubusercontent.com/16447578/105661805-4de9a900-5e9c-11eb-8e1d-6e49f1a61c72.png)
ue

**Comment by regulad** [comment]
@M1K3Altz this would also be fixed by #249 which imo is a much nicer solution
