### ISSUE TITLE
Bug Report: Newgrounds version sometimes erases progress upon refresh

### ISSUE THREAD

**Issue by Caylie-C** [FunkinCrew/Funkin#2287]
### If you are playing the game in a browser, what site are you playing it from?

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Ensure you are signed into your Newgrounds account. Either change your controls or log a score in any song or week (or both). Reload the page. It may result in all progress including controls/settings configuration being erased. More often than not, it should.

## Please describe your issue. Provide extensive detail and images if possible.
The scores I've earned are erased over 50% of the time I load the page. I have ensured I'm signed into my Newgrounds account, and sometimes it will save my progress upon refreshing, but even if it does, the next time it fails, it erases ALL progress including progress that was preserved from the previous refresh, as well as input settings and general configuration settings.

**Comment by EliteMasterEric** [comment]
I've heard this report from several people, we will look into it for sure.

**Comment by EliteMasterEric** [comment]
I believe I have a fix for this that should come in the next update.

**Comment by EnterTheVoid-x86** [comment]
This isn't just a Newgrounds issue. I've noticed this happening several times when running `lime test html5` from the source code repo and refreshing.

**Comment by EliteMasterEric** [comment]
Definitely resolved in v0.4.0.
