### ISSUE TITLE
I cant enter freeplay :( (v0.3.2 from itch.io)

### ISSUE THREAD

**Issue by thebopee** [FunkinCrew/Funkin#2293]
I play on PC, when i entered freeplay i get a very long error message, i used ran the game with the command prompt and got this message when the error appeared

Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 26
Called from ApplicationMain::create ApplicationMain.hx line 135
Called from lime.app.Application::exec lime/app/Application.hx line 151
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 147
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 381
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 2111
Called from openfl.display.OpenGLRenderer::__render openfl/display/OpenGLRenderer.hx line 764
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 30
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 850
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 17
Called from openfl.display._internal.Context3DDisplayObject::renderDrawable openfl/display/_internal/Context3DDisplayObject.hx line 68
Called from openfl.display._internal.Context3DShape::render openfl/display/_internal/Context3DShape.hx line 38
Called from openfl.display._internal.Context3DGraphics::render openfl/display/_internal/Context3DGraphics.hx line 611
Called from openfl.display.OpenGLRenderer::__initShaderBuffer openfl/display/OpenGLRenderer.hx line 590
Called from openfl.display.OpenGLRenderer::__initGraphicsShader openfl/display/OpenGLRenderer.hx line 576
Called from openfl.display.Shader::__init openfl/display/Shader.hx line 549
Called from openfl.display.Shader::__initGL openfl/display/Shader.hx line 621
Called from openfl.display.Shader::__createGLProgram openfl/display/Shader.hx line 436
Called from openfl.display.Shader::__createGLShader openfl/display/Shader.hx line 424
Called from lime.utils.Log::error lime/utils/Log.hx line 34

Any solutions?

**Comment by moxie-coder** [comment]
“ran the game with command prompt” I didn’t think this was possible, but part of me feels like this isn’t related to this at all, because I feel like you compiled a mod and put this error here

**Comment by thebopee** [comment]
> “ran the game with command prompt” I didn’t think this was possible, but part of me feels like this isn’t related to this at all, because I feel like you compiled a mod and put this error here

I didnt, i downloaded FNF from https://ninja-muffin24.itch.io/funkin, and running the game with command prompt is possible, i checked how to do so at a comment from https://ninja-muffin24.itch.io/funkin

**Comment by moxie-coder** [comment]
> > “ran the game with command prompt” I didn’t think this was possible, but part of me feels like this isn’t related to this at all, because I feel like you compiled a mod and put this error here
> 
> I didnt, i downloaded FNF from https://ninja-muffin24.itch.io/funkin, and running the game with command prompt is possible, i checked how to do so at a comment at https://ninja-muffin24.itch.io/funkin , which talks about (somewhat) the same problem.

okay well you sure you got an error message not just from the command prompt? because all of those aren’t errors, it’s just what the C++ hxcpp compiler is logging, but if you got an shader error, there’s an issue with AMD gpus right now

**Comment by thebopee** [comment]
> > > “ran the game with command prompt” I didn’t think this was possible, but part of me feels like this isn’t related to this at all, because I feel like you compiled a mod and put this error here
> > 
> > 
> > I didnt, i downloaded FNF from https://ninja-muffin24.itch.io/funkin, and running the game with command prompt is possible, i checked how to do so at a comment at https://ninja-muffin24.itch.io/funkin , which talks about (somewhat) the same problem.
> 
> okay well you sure you got an error message not just from the command prompt? because all of those aren’t errors, it’s just what the C++ hxcpp compiler is logging, but if you got an shader error, there’s an issue with AMD gpus right now

Yeah, an error pops up and the game crashes

**Comment by moxie-coder** [comment]
okay, well the source code is out so people might find a way to fix it

**Comment by ninjamuffin99** [comment]
checking in to see if this was fixed in one of our updates since 0.3.2? i believe there was something on freeplay related to amd gpu's that we fixed, so checking to see if i can close this one!

**Comment by thebopee** [comment]
Thank you very much, it works now!
