### ISSUE TITLE
This isn't a bug but this is urgent. LEAKS kind of urgent.

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/Funkin#2296]
There is content for new stuff that we aren't supposed to see in old commits of the assets repo before you removed them, such as cocoa erect. You gotta find a way to remove this stuff before it gets out, cuz once the modders see this they are gonna lose their marbles

**Comment by AbnormalPoof** [comment]
Welcome to version control.

**Comment by Lasercar** [comment]
lol.
