### ISSUE TITLE
Tutorial: Normal refuses to load --> crashes in the Linux build. ISSUE FOUND AND HAS PROPOSED RESOLUTION -- PLEASE READ

### ISSUE THREAD

**Issue by ThatOneCalculator** [FunkinCrew/Funkin#23]
Yep. Just that one difficulty on that one map. Only on the Linux version.

Log:

```
[lime.utils.Assets] ERROR: There is no TEXT asset with an ID of "assets/data/tutorial/tutorial.json"
Error : [lime.utils.Assets] ERROR: There is no TEXT asset with an ID of "assets/data/tutorial/tutorial.json"```

**Comment by ThatOneCalculator** [comment]
I found the issue: in the Linux build, y'all made it `./assets/data/tutorial/Tutorial.json` instead of `./assets/data/tutorial/tutorial.json`. PLEASE fix this, it's just a filename.

![image](https://user-images.githubusercontent.com/44733677/100973016-a8930400-34ee-11eb-96d4-d8bf178be994.png)

**Comment by ninjamuffin99** [comment]
ahhh yeah, i can't remember exactly why or how it happens, but i think it just like, automatically makes it capitalized or somethin? def gon be fixed, i fixed it once before but i guess some weird shit with repo reverted it?

**Comment by ThatOneCalculator** [comment]
lol why did this get stale'd 5 years later 😭
