### ISSUE TITLE
Compiling help: [Could not find haxelib "funkin.vis"]

### ISSUE THREAD

**Issue by Themoddingfungus** [FunkinCrew/Funkin#2304]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
When compiling, or attempting to, it tells me I'm missing haxelib "funkin.vis" and when I try to install it it doesnt. I tried to follow the new compiling instructions the best I could but nothing seems to work

**Comment by JackXson-Real** [comment]
Did you use this command: haxelib git funkin.vis https://github.com/FunkinCrew/funkVis

**Comment by METGameDev** [comment]
I personally solved this by just grabbing the funkinVis, downloading it, and then shoving them into source/Funkin so that the game has something to reference

All this did for me was give me a new error but it might work for you.

**Comment by EliteMasterEric** [comment]
This should be fixed in v0.3.3.
