### ISSUE TITLE
Compiling help: JsonParser_0 has no field ignoreUnknownVariables

### ISSUE THREAD

**Issue by METGameDev** [FunkinCrew/Funkin#2305]
source/funkin/data/song/SongRegistry.hx:138: characters 12-34

  138 |     parser.ignoreUnknownVariables = true;
      |            ^^^^^^^^^^^^^^^^^^^^^^
      | JsonParser_0 has no field ignoreUnknownVariables

tried building the game and got this.
the only thing i changed was adding the FunkinVis to the game cuz that wasnt working either

![image](https://github.com/FunkinCrew/Funkin/assets/76184245/ee476744-c897-4d4c-b7d3-7ce884a287dd)

PS: Commenting out all the lines that say "parser.ignoreUnknownVariables = true;" in SongRegistry.hx results in this new error:

source/funkin/graphics/shaders/RuntimeCustomBlendShader.hx:14: characters 10-23

   14 |     this.setBitmapData("sourceSwag", value);
      |          ^^^^^^^^^^^^^
      | funkin.graphics.shaders.RuntimeCustomBlendShader has no field setBitmapData

**Comment by Sword352** [comment]
Use funkin's json2object fork.

**Comment by EliteMasterEric** [comment]
Did you follow the compilation guide? It seems you have the wrong version of `json2object`

**Comment by METGameDev** [comment]
Ok, thanks that fixed that, getting a new error now.

**Comment by MulakkJ** [comment]
> Did you follow the compilation guide? It seems you have the wrong version of `json2object`

what is the right version?

**Comment by moxie-coder** [comment]
> > Did you follow the compilation guide? It seems you have the wrong version of `json2object`
> 
> what is the right version?

use hmm to do that

**Comment by MulakkJ** [comment]
> use hmm to do that, make sure it is run on your local repo

i love you bro

**Comment by MrKoyun** [comment]
> > > Did you follow the compilation guide? It seems you have the wrong version of `json2object`
> > 
> > 
> > what is the right version?
> 
> use hmm to do that, make sure it is run on your local repo

Wdym use hmm? can you explain further?

**Comment by EliteMasterEric** [comment]
> > > > Did you follow the compilation guide? It seems you have the wrong version of `json2object`
> > > 
> > > 
> > > what is the right version?
> > 
> > 
> > use hmm to do that, make sure it is run on your local repo
> 
> Wdym use hmm? can you explain further?

Follow the [compliation guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/COMPILING.md)
