### ISSUE TITLE
Bug Report: `PicoPlayerCharacter.onCreate()` causes an exception in the script, due to a null object reference from the super call.

### ISSUE THREAD

**Issue by saturn-volv** [FunkinCrew/Funkin#2317]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)
- [x] Compiled from source (without any changes), to platform:
- - [x] Windows

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
v0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Every time I open any of the weekend 1 songs, from Darnell through 2Hot.

## Please describe your issue. Provide extensive detail and images if possible.
When the character script for `pico-playable` is created, it crashes due to a Null Object Reference. The cause is said to be from line 26, which is the super call.
![image](https://github.com/FunkinCrew/Funkin/assets/115556838/bb500b3f-cff6-4aef-b60a-3342cd92dfe4)

**Comment by EliteMasterEric** [comment]
Fixed by #2388 .
