### ISSUE TITLE
Compiling help: source/funkin/Paths.hx:116: characters 75-76 : Unexpected ?

### ISSUE THREAD

**Issue by NovaTheFurryDev** [FunkinCrew/Funkin#2321]
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

I am having issues compiling `source/funkin/Paths.hx:116: characters 75-76 : Unexpected ?`
![image](https://github.com/FunkinCrew/Funkin/assets/61569905/59d13934-1fff-4bd2-9fec-db38a6e97049)
![image](https://github.com/FunkinCrew/Funkin/assets/61569905/7a891b04-b665-4189-9350-79fe8282f894)

**Comment by moxie-coder** [comment]
you need haxe 4.3

**Comment by NovaTheFurryDev** [comment]
thanks LMAO
