### ISSUE TITLE
Compiling help:  Type not found : T

### ISSUE THREAD

**Issue by METGameDev** [FunkinCrew/Funkin#2333]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

Honestly the funniest error I have ever gotten outta anything.
So I managed to get past a bunch of previous errors, but I dont even know what to say about this one:

 ERROR  (unknown position)

      | Type not found : T
      
(yes thats LITERALLY IT i have no clue what this is)

Theres also this warning thats bolded above it, dont know if it has anything to do with anything though.

 WARNING  D:/FNF CODING/PoopyfaceMod/.haxelib/flixel/5,8,0/flixel/FlxState.hx:196: lines 196-199

  196 |  public function switchTo(nextState:FlxState):Bool
  197 |  {
  198 |   return true;
  199 |  }
      |
      | switchTo is deprecated, use startOutro

Im pretty sure I installed everything correctly, but if this indicates a bad installation of a library lmk.

**Comment by METGameDev** [comment]
Ok, reinstalled flixel, this error disappeared but a new one appeared:

 ERROR  source/funkin/modding/PolymodHandler.hx:294: characters 7-24

  294 |       coreAssetRedirect: CORE_FOLDER,
      |       ^^^^^^^^^^^^^^^^^
      | { coreAssetRedirect : Null<String>, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect

**Comment by NotHyper-474** [comment]
This issue is probably stale by now but this also seems to be caused by Polymod?
Since for some reason `haxelib update polymod` causes this error to pop up and force-reinstalling it fixes it.
