### ISSUE TITLE
Enhancement: A generalized Script class

### ISSUE THREAD

**Issue by nebulazorua** [FunkinCrew/Funkin#2334]
## What is your suggestion, and why should it be implemented?

As it stands, you can only load 1 script per stage, song, character, etc. I think it'd be beneficial to have a generic Script class that you can extend, which won't load by default but can be loaded by other scripts for organizational purposes. Pretty much a Module that you can load and unload at will. The main use-case would be for loading multiple scripts on songs, calling the callbacks through the main song script or through adding it to some sort of system that automatically dispatches events during dispatchEvent

A less generalized approach would be a GameplayModule or something to that effect, which'd load on every PlayState and unload when PlayState is destroyed, to allow players the same goal of running multiple scripts, though this time only in PlayState. 
GameplayModule might have its own merits existing alongside Script, though, for stuff like HUD scripts, as right now doing stuff like that in Modules is a pain in the ass and is prone to many, many errors.

**Comment by EliteMasterEric** [comment]
Documentation on Modules isn't thorough, but they can be enabled or disabled at will.

```haxe
import funkin.modding.module.ModuleHandler;

// Retrieve a module by name. The ID is the string passed in the constructor of the Module.
var module = ModuleHandler.getModule('myModuleId');

// Make a module active. If a module is active, it will receive script events.
module.active = true;

// Oh yeah, and once you have the module in a variable, you can call script functions on it.
module.scriptCall('functionName', [arg1, arg2, arg3]);
```

```haxe
// You can disable a module on startup by making it inactive in the constructor.
// You can then enable it when you want it active.
public function new() {
  super('myModuleId')
  active = false;
}
```
