### ISSUE TITLE
Compiling help: PolymodHandler Error: { coreAssetRedirect : Null, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect

### ISSUE THREAD

**Issue by METGameDev** [FunkinCrew/Funkin#2336]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

Sorry for posting so many issues, but I genuinely dont have a solution to this one.

ERROR source/funkin/modding/PolymodHandler.hx:294: characters 7-24

294 | coreAssetRedirect: CORE_FOLDER,
| ^^^^^^^^^^^^^^^^^
| { coreAssetRedirect : Null, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect

Ive reinstalled polymod several times and it didnt fix this.

**Comment by METGameDev** [comment]
https://github.com/FunkinCrew/Funkin/issues/2299

this issue seems to be having the exact same problem. might be an outdated polymod.
I did however, manually install the libraries with terminal commands, so i dunno. 
![image](https://github.com/FunkinCrew/Funkin/assets/76184245/2980f59e-c645-44ea-acaa-f8a3ffb50302)

**Comment by Eviethecoder** [comment]
I've tried both the hmm install and manually installing it from the git and no luck.

**Comment by METGameDev** [comment]
https://github.com/FunkinCrew/Funkin/issues/2299
Answer in here.
