### ISSUE TITLE
Merch tab opening while in freeplay bug(?)

### ISSUE THREAD

**Issue by JabbingQuirker** [FunkinCrew/Funkin#2337]
I was playing through the new update, and starting some of the erect remixes (mainly pico and blammed) lagged out the game and opened the merch tab in my browser. unsure if that's on purpose, didn't see it in the PN.

(context, playing itch version using xbox one controller)

**Comment by METGameDev** [comment]
its not. the bug is probably caused by the fact that the main menu is still active underneath the freeplay substate, so its selecting the merch tab and opening it before the freeplay song can open.

**Comment by BernardoGP4504** [comment]
> pretty sure that’s intentional

It isn't 
He meant when he was starting a song on freeplay (pressed enter), it acted as he had pressed enter on the Merch button

**Comment by JackXson-Real** [comment]
What version are you on? Im pretty sure this was fixed in 0.3.2. Ive tried doing the bug on Itch and NG ver but I havent been able to get it to happen.

**Comment by JabbingQuirker** [comment]
> What version are you on? Im pretty sure this was fixed in 0.3.2. Ive tried doing the bug on Itch and NG ver but I havent been able to get it to happen.

ah, just realized i'm on 0.3.1. downloaded the 0.3.2 version now and didnt see the same issue. guess that's closed!
