### ISSUE TITLE
pixelated note sparks missing from week 6

### ISSUE THREAD

**Issue by JabbingQuirker** [FunkinCrew/Funkin#2338]
As title says, when hitting sick notes in week 6, the pixelated little note sparks are missing :(

(itch version)

**Comment by moxie-coder** [comment]
pretty sure that was intentional, not a bug unless they’re working on pixel splashes which is why there’s none rn

**Comment by JackXson-Real** [comment]
I believe its because they are working on new ones that also support the new hold arrow splashes.

**Comment by EliteMasterEric** [comment]
Duplicate of #2823, that one has more info.

**Comment by Michu0204** [comment]
Added in 0.6.0

**Comment by AbnormalPoof** [comment]
> Added in 0.6.0

This is a duplicate.
