### ISSUE TITLE
Compiling help: [BRIEF DESCRIPTION / ERROR MESSAGE OUTPUT]

### ISSUE THREAD

**Issue by ChickenSwimmer2020** [FunkinCrew/Funkin#2342]
for personal reasons, i have censored the name of my user.
----------------------------------------------------------------------------------------------------------------------------------------------------
source/Prebuild.hx:15: Building...
 WARNING  C:/Users/[MYPCNAME]/Downloads/Funkin-main/Funkin-main/.haxelib/hxcpp-debug-server/1,2,4/hxcpp/debug/jsonrpc/Server.hx:20: characters 1-7

   20 | @:enum abstract ScopeId(String) to String {
      | ^^^^^^
      | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  C:/Users/[MYPCNAME]/Downloads/Funkin-main/Funkin-main/.haxelib/hxcpp-debug-server/1,2,4/hxcpp/debug/jsonrpc/Protocol.hx:21: characters 1-7

   21 | @:enum
      | ^^^^^^
      | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  C:/Users/[MYPCNAME]/Downloads/Funkin-main/Funkin-main/.haxelib/polymod/1,7,0/polymod/Polymod.hx:1005: characters 1-7

 1005 | @:enum abstract PolymodErrorOrigin(String) from String to String
      | ^^^^^^
      | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  C:/Users/[MYPCNAME]/Downloads/Funkin-main/Funkin-main/.haxelib/polymod/1,7,0/polymod/Polymod.hx:1051: characters 1-7

 1051 | @:enum abstract PolymodErrorCode(String) from String to String
      | ^^^^^^
      | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  C:/Users/[MYPCNAME]/Downloads/Funkin-main/Funkin-main/.haxelib/polymod/1,7,0/polymod/backends/PolymodAssets.hx:226: characters 1-7

  226 | @:enum abstract PolymodAssetType(String) from String to String
      | ^^^^^^
      | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 ERROR  (unknown position)

      | Invalid commandline class : funkin.art.Postbuild should be art.Postbuild
----------------------------------------------------------------------------------------------------------------------------------------------------
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5
----------------------------------------------------------------------------------------------------------------------------------------------------
i have installed all dependencies, and attempted to compile the game. from what i know, i have zero clue what causes this

**Comment by ChickenSwimmer2020** [comment]
i just looked at the files, theres a little lock icon next to literally every single file of the 'funkin' folder, only folders excluded are: "rfc, source, tests, example_mods, docs, build, assets, art". i have no clue what caused this. i also dont know if it was their previously

**Comment by EliteMasterEric** [comment]
Try following the compilation guide again.

**Comment by Hundrec** [comment]
Have you been able to compile the game?
If so, you may close this issue.

**Comment by EliteMasterEric** [comment]
This person didn't follow the compilation guide. IF they still have issues they can create a new issue.
