### ISSUE TITLE
Compiling help: can't find "funkin.vis.dsp.SpectralAnalyzer"

### ISSUE THREAD

**Issue by SamicomOfficial** [FunkinCrew/Funkin#2349]
an issue in ABotVis.hx is causing my compile to fail, it says it can't find "funkin.vis.dsp.SpectralAnalyzer"
is there something i need to install or tweak in the code? i've already installed everything needed to compile the game

![Screenshot 2024-05-08 100541](https://github.com/FunkinCrew/Funkin/assets/116606678/e82c2c40-62e0-41f9-9238-769a0c689324)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

**Comment by 3zoosE** [comment]
this happens because the CMD didn't install the libraries correctly, i had this error too, what i did was go to [this repository](https://github.com/FunkinCrew/funkVis) download the zip file and extract the "funkVis-main/" in ".haxelib/funkin,vis/git/" if you don't have any folders there, make them.

**Comment by SlightlyCreative** [comment]
> this happens because the CMD didn't install the libraries correctly, i had this error too, what i did was go to [this repository](https://github.com/FunkinCrew/funkVis) download the zip file and extract the "funkVis-main/" in ".haxelib/funkin,vis/git/" if you don't have any folders there, make them.

thank you, that fixed it

**Comment by yigezhihuimazidexie** [comment]
> this happens because the CMD didn't install the libraries correctly, i had this error too, what i did was go to [this repository](https://github.com/FunkinCrew/funkVis) download the zip file and extract the "funkVis-main/" in ".haxelib/funkin,vis/git/" if you don't have any folders there, make them.

I followed your method and extracted the files into the specified folder, but I'm still encountering the same error. I can confirm that SpectralAnalyzer exists in my funkinvis.
