### ISSUE TITLE
Decompiling help: [HELP WITH STUCK ON PRELOAD SCREEN 0% 0/11]

### ISSUE THREAD

**Issue by Kiwwix** [FunkinCrew/Funkin#2354]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [x] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
**im lazy to type just see discord message**
![image](https://github.com/FunkinCrew/Funkin/assets/169297454/0493f8e8-37dc-40bf-ae4f-61e66d9673fb)
![image](https://github.com/FunkinCrew/Funkin/assets/169297454/4d7aebc7-dc44-48e4-86ba-a40e925ea171)
![image](https://github.com/FunkinCrew/Funkin/assets/169297454/8e101783-9403-40c6-b0fb-02c23104fba6)
![image](https://github.com/FunkinCrew/Funkin/assets/169297454/3426da42-cacb-4561-b4d3-9f2e254cbf22)

**Comment by Kiwwix** [comment]
guys help

**Comment by Futuredorito** [comment]
uploading to itch.io should make it work

**Comment by ninjamuffin99** [comment]
I believe you need to run the code off a small localhost webserver of some kind! Opening the .html file won't load it properly, since it needs to load the assets in a specific way!

**Comment by Kiwwix** [comment]
> I believe you need to run the code off a small localhost webserver of some kind! Opening the .html file won't load it properly, since it needs to load the assets in a specific way!

it worked but im now stucking in song load
![image](https://github.com/FunkinCrew/Funkin/assets/169297454/130a302e-5377-4a2b-85b0-2093c07d0783)

**Comment by Kiwwix** [comment]
> I believe you need to run the code off a small localhost webserver of some kind! Opening the .html file won't load it properly, since it needs to load the assets in a specific way!

pls see. How to fix, assets don't downloading

https://github.com/FunkinCrew/Funkin/assets/169297454/4b402e5c-1a72-4823-a03b-55c41cf24488
