### ISSUE TITLE
Ghost Tapping in Botplay results in missing and can cause the player to die

### ISSUE THREAD

**Issue by ZeitHeld** [FunkinCrew/Funkin#2358]
### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [X] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Please describe your issue. Provide extensive detail and images if possible.
- Open Chart Editor
- Go to any song
- Enable "Bot Play mode" in "Window > Playtest Properties"
- Smash the Arrow Keys
- Die to Ghost Tapping (with seemingly full health)

**Comment by EliteMasterEric** [comment]
Reproduced.

**Comment by TehEpikNoobKing** [comment]
I actually fixed this bug pretty easily in the source.

PlayState.hx - function processInputQueue()
![image_2024-08-02_224921341](https://github.com/user-attachments/assets/8fc45994-4453-432a-a69b-928004e6597b)

(The highlighted green is the added lines)

**Comment by Hundrec** [comment]
Cool! How are inputs handled with this change? Do they do nothing at all?

**Comment by Hundrec** [comment]
Bot play mode now skips handling misses in 0.5.0, so this is fixed!

**Comment by EliteMasterEric** [comment]
Closed as resolved
