### ISSUE TITLE
Bug Report: Week/song names in the results screen are misaligned

### ISSUE THREAD

**Issue by JackXson-Real** [FunkinCrew/Funkin#2365]
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Just play any week in story mode and look at the name in the top right of results screen.

## Please describe your issue. Provide extensive detail and images if possible.
Week names in the results screen are not aligned properly, they appear to be aligned slightly above the difficulty text. Here are some screenshots:

![screenshot-2024-05-08-16-13-24](https://github.com/FunkinCrew/Funkin/assets/32755192/8a29fc2c-287f-4bed-aee2-c2278c44d05a)
![screenshot-2024-05-08-16-32-02](https://github.com/FunkinCrew/Funkin/assets/32755192/48e56dc1-dff8-4c44-9580-ddc7a9c06a6e)
![screenshot-2024-05-08-16-37-59](https://github.com/FunkinCrew/Funkin/assets/32755192/253296a7-470d-47c8-82f3-eae6c7ba1254)

**Comment by EliteMasterEric** [comment]
Still present in v0.4.0, my fix for this is dependent on the resolution of HaxeFlixel/flixel#3144.
