### ISSUE TITLE
Compiling help: [hmm install ]

### ISSUE THREAD

**Issue by leaningmonkevr** [FunkinCrew/Funkin#2372]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

 so when i try to do haxelib --global run hmm setup it gives me this

 copy C:/HaxeToolkit/haxe/lib/hmm/3,1,0/hmm.cmd C:/HaxeToolkit/haxe/hmm.cmd
 
 what does it mean by copy?

because this, the hmm install step gives me this error 

 Validation error: hmm.json not found in current working directory
Use "hmm help" to see usage

**Comment by leaningmonkevr** [comment]
i am dum

**Comment by NotHyper-474** [comment]
From what I see `hmm setup` is working fine
Where are you running `hmm install` from? For it to work it should be executed in Funkin folder

**Comment by leaningmonkevr** [comment]
> From what I see `hmm setup` is working fine Where are you running `hmm install` from? For it to work it should be executed in Funkin folder


 wait i need to run hmm install in the funkin folder
