### ISSUE TITLE
Compiling help: PolymodHandler.hx Error in lines 289-295

### ISSUE THREAD

**Issue by SamicomOfficial** [FunkinCrew/Funkin#2376]
the Polymodhandler.hx file gives me an error in lines 289-295 that prevents my compile, this is the error i get.
![Screenshot 2024-05-08 185612](https://github.com/FunkinCrew/Funkin/assets/116606678/6da080a1-3ca9-4d0e-a3eb-00f345e25a79)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

**Comment by HertzLUK** [comment]
#2299  Here is the solution :)
