### ISSUE TITLE
Compiling help: flixel.addons.display.FlxRuntimeShader has no field glVersion

### ISSUE THREAD

**Issue by ItVid** [FunkinCrew/Funkin#2377]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
![image](https://github.com/FunkinCrew/Funkin/assets/82421426/a857a947-f05c-4e4d-9579-bf214a3784e7)

Everytime I build, I keep getting error, probably something to do with the libraries but no idea which one it is

**Comment by Kiwwix** [comment]
i have too

**Comment by NotHyper-474** [comment]
Are you sure you followed the [Compiling guide](./docs/COMPILING.md) correctly? Seems like Flixel didn't install properly

**Comment by ItVid** [comment]
Did it correctly, but i'll see if its flixel casuing issues

**Comment by ItVid** [comment]
Found the fix, openfl download the wrong version, thanks though!!

**Comment by coolaydang** [comment]
what version of openfl did you download?
