### ISSUE TITLE
Compiling help: hxcodec.flixel.FlxVideoSprite has no field autoPause

### ISSUE THREAD

**Issue by HertzLUK** [FunkinCrew/Funkin#2378]
Help when compiling I get this: source/funkin/play/cutscene/VideoCutscene.hx:148: characters 11-20

 148 |       vid.autoPause = false;
     |           ^^^^^^^^^
     | hxcodec.flixel.FlxVideoSprite has no field autoPause

**Comment by Tabpi** [comment]
I'm having the same issue, not very experienced with this though. Also, I'm targeting Linux, not sure if that's relevant.

**Comment by HertzLUK** [comment]
thank you thank you and thank you very much :)

**Comment by Ethan-makes-music** [comment]
Ive reinstalled the libs and assets, art etc and it still gives me the error does anyone have another idea on how to fix it?

**Comment by Mario-119** [comment]
Same issue here, the solutions provided unfortunately don't work
