### ISSUE TITLE
Bug Report: Y 'WOAH' Debug hotkey tweening accumulates

### ISSUE THREAD

**Issue by NotHyper-474** [FunkinCrew/Funkin#2379]
Basically it doesn't really check if you already pressed the key so it keeps adding a Tween to the game window to the point where it starts aggressively shaking
It's a non essential feature and stops after the State is changed so it's not really important to fix, in fact, I find it quite amusing
Here's a video of it occurring:
https://github.com/FunkinCrew/Funkin/assets/40342021/0d6de20c-462b-430a-9597-21e0f14209a7

**Comment by EliteMasterEric** [comment]
Fixed by #2300 expect to see it in v0.3.3.
