### ISSUE TITLE
Idle animation bug

### ISSUE THREAD

**Issue by IceboundCat6** [FunkinCrew/Funkin#238]
Like Lemon Demon in the "secret" Monster level, the idle animation of the BF's new skins (car and christmas) are bugged. When holding long notes, the idle animation will flash in and out for a split second.

YT link, because seein' is better than believin' : https://youtu.be/EdPpQNsR8sU

**Comment by Injourn** [comment]
Addressed here: https://github.com/ninjamuffin99/Funkin/pull/237

**Comment by ninjamuffin99** [comment]
fixed in #237
