### ISSUE TITLE
Am I missing something here?

### ISSUE THREAD

**Issue by ADuckInBlack** [FunkinCrew/Funkin#2392]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
![image](https://github.com/FunkinCrew/Funkin/assets/33814766/7aaa41a4-d3b8-40f2-9815-1957ff93b7e1)

**Comment by Stilic** [comment]
do you have git installed?

**Comment by ADuckInBlack** [comment]
> do you have git installed?

i believe i do, but do you think i need to do a quick reinstall?

**Comment by Stilic** [comment]
> > do you have git installed?
> 
> i believe i do, but do you think i need to do a quick reinstall?

probably

**Comment by ADuckInBlack** [comment]
> > > do you have git installed?
> > 
> > 
> > i believe i do, but do you think i need to do a quick reinstall?
> 
> probably

i completely reinstalled git, but i still got the exact same error, so unless i have the wrong version of git, idk what's going on. i have git 2.45.0 btw

**Comment by Stilic** [comment]
do you have the latest version of haxe too?

**Comment by ADuckInBlack** [comment]
i uninstalled haxe and neko (using the uninstaller), reinstalled both, reinstalled every library i needed to make this work using hmm, and now i'm getting this error. 
![image](https://github.com/FunkinCrew/Funkin/assets/33814766/8c3ec0e3-1120-4d8f-b922-19e27cd4966b)

**Comment by Stilic** [comment]
> i uninstalled haxe and neko (using the uninstaller), reinstalled both, reinstalled every library i needed to make this work using hmm, and now i'm getting this error. ![image](https://private-user-images.githubusercontent.com/33814766/329720009-8c3ec0e3-1120-4d8f-b922-19e27cd4966b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTc0NzYsIm5iZiI6MTcxNTQxNzE3NiwicGF0aCI6Ii8zMzgxNDc2Ni8zMjk3MjAwMDktOGMzZWMwZTMtMTEyMC00ZDhmLWI5MjItMTllMjdjZDQ5NjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA4NDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MzIwZDhiN2I2YmFjNGExOTU1YWNhZTJiMmE1ZGNlMTI1ZGY4MTgyYTc5MmNjNWRiNzQ3NTFhNDg3MWFjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4JznRPAUPfE2-WhqDn1Nk8asuHlpddHzae5bN5ynmRI)

then idk

**Comment by ADuckInBlack** [comment]
hope someone notices this soon

**Comment by chicken-nugget1104** [comment]
hey uh open source it. thats what i did and it fixed it

**Comment by kevkev3030** [comment]
how?

**Comment by Stilic** [comment]
> hey uh open source it. thats what i did and it fixed it

wdym

**Comment by ZonerPlayz** [comment]
Well, your not alone because I'm having the same issue. I hope @ninjamuffin99 or @EliteMasterEric notices this issue.

**Comment by chicken-nugget1104** [comment]
> > hey uh open source it. thats what i did and it fixed it
> 
> wdym

fork the project get into github desktop put your entire source in then compile from the folder.

**Comment by moxie-coder** [comment]
> > > hey uh open source it. thats what i did and it fixed it
> > 
> > 
> > wdym
> 
> fork the project get into github desktop put your entire source in then compile from the folder. this is there way of forcing every mod to be open source.

that’s not what open source means

**Comment by ZonerPlayz** [comment]
> > > > hey uh open source it. thats what i did and it fixed it
> 
> > > 
> 
> > > 
> 
> > > wdym
> 
> > 
> 
> > fork the project get into github desktop put your entire source in then compile from the folder. this is there way of forcing every mod to be open source.
> 
> 
> 
> that’s not what open source means, and it doesn’t work that way either 

Well yes, your right. That's not what open source means but, technically if you are going to make a mod for FNF, it says in one of the text files that if you are going to make a mod for FNF, you have to open source it.

**Comment by ZonerPlayz** [comment]
I hope the devs notice this topic because it's kind of a big issue because how in the world are people going to make mods for FNF when you can't compile the gams

**Comment by Galactic00** [comment]
ok so nobody knows what to do?

**Comment by EliteMasterEric** [comment]
- The first error (the EOF when getting the git hash) is because the user did not properly follow the compilation guide, and is missing the Git program.
- The second error (the coreAssetRedirect) is because the user did not properly follow the compilation guide, and is using the wrong version of Polymod (the compilation guide walks through proper installation of the correct library versions).

Conclusion: Error code PEBKAC
