### ISSUE TITLE
close it pls im stupid

### ISSUE THREAD

**Issue by Kiwwix** [FunkinCrew/Funkin#2394]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [x] HTML5

### **how to fix that? i have ported for fun all web version files (using devtools and localhost) into folder. BUT when i openned localhost page it's stucks on assets downloading. Help me pls** (im downloading using Resources Saver extension)

![image](https://github.com/FunkinCrew/Funkin/assets/169297454/cc573e9d-d1dc-4222-aa33-d8766d727e64)
video:
https://github.com/FunkinCrew/Funkin/assets/169297454/2847386b-b8af-476a-b962-73ff0de67000

**Comment by moxie-coder** [comment]
there’s literally a close button dude
