### ISSUE TITLE
Github Page Bug: CONTRIBUTORS.MD does not exist

### ISSUE THREAD

**Issue by ColdlordXRepositories** [FunkinCrew/Funkin#2415]
![image](https://github.com/FunkinCrew/Funkin/assets/49921877/f7b37ffe-ca8d-46d7-a84c-c09db7bec72f)
![image](https://github.com/FunkinCrew/Funkin/assets/49921877/8f5bfd4a-a45e-4f1d-a512-a66909966b02)
Self-explanatory.

**Comment by NotHyper-474** [comment]
Already reported twice https://github.com/FunkinCrew/Funkin/issues/2404 https://github.com/FunkinCrew/Funkin/issues/2362
