### ISSUE TITLE
Compiling help: Error installing funkin.vis

### ISSUE THREAD

**Issue by ColdlordXRepositories** [FunkinCrew/Funkin#2416]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
![image](https://github.com/FunkinCrew/Funkin/assets/49921877/257e1ee5-776c-4269-b027-68c2c2974133)
`haxelib --never git funkin.vis https://github.com/FunkinCrew/funkVis 98c9db09f0bbfedfe67a84538a5814aaef80bdea
Installing funkin.vis from https://github.com/FunkinCrew/funkVis branch: 98c9db09f0bbfedfe67a84538a5814aaef80bdea
Error: std@sys_remove_dir
Execution error: command "haxelib --never git funkin.vis https://github.com/FunkinCrew/funkVis 98c9db09f0bbfedfe67a84538a5814aaef80bdea" failed with status: 1 in cwd: C:\Users\corie\Documents\Funkin-main/`

Happens after running "hmm install"

From what I'm getting from this, does this already mean it's already installed? I did absolutely no research before doing this, so I'm sorry.
I was able to follow all previous steps.

**Comment by NotHyper-474** [comment]
Change to develop branch and rerun the command

**Comment by ColdlordXRepositories** [comment]
> Change to develop branch and run the command again Also a duplicate of #2298

oh wait theres a branch for contributing to the game
cool
also mb
