### ISSUE TITLE
Null Object Reference When You Don't Skip the Title Intro.

### ISSUE THREAD

**Issue by VirtuGuy** [FunkinCrew/Funkin#2417]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [X] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari
- [X] Neither because HTML is for losers

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Open the game.
Wait and don't skip the intro.

## Please describe your issue. Provide extensive detail and images if possible.
When you start the game, it shows the title screen intro. When you don't skip it, it crashes for some stupid reason. Also, it happens right before the intro message shows up. Here's an image of the error that crashes the game.
![image](https://github.com/FunkinCrew/Funkin/assets/103977942/b7240cab-1132-4dd8-8301-c31110af8b94)

I know it's not a huge deal because you can literally just bypass the crash by skipping it, but it should still get fixed because you never know if someone wants to see the intro and it crashes on them and they're all like: "What the hell?!" I apologize, this is supposed to be serious.

**Comment by JackXson-Real** [comment]
Doesnt happen for me, are you using a version you compiled yourself or the itch.io build?

**Comment by ColdlordXRepositories** [comment]
> Doesnt happen for me, are you using a version you compiled yourself or the itch.io build?

second this, i think your install is broken

**Comment by VirtuGuy** [comment]
Never mind, it's the mods and I guess I'm stupid. I didn't take that good enough of a look at them.
