### ISSUE TITLE
The controls 

### ISSUE THREAD

**Issue by wafflemaster13** [FunkinCrew/Funkin#242]
The game would be better if you can switch ur key binds the game seems not fun when you can’t choose ur keybinds when I first started playing the game wasn’t fun because I didn’t know how to play properly and we need a key bind so we can get a better way to play

**Comment by regulad** [comment]
sounds like a duplicate of #47

**Comment by wafflemaster13** [comment]
> sounds like a duplicate of #47

Oh didn’t know someone already posted the same thing :/

**Comment by regulad** [comment]
since it is a duplicate you should close this issue
