### ISSUE TITLE
Compiling help: [Game compiles but crashes after loading. Never gets to title screen. / source/funkin/modding/PolymodErrorHandler.hx:84: [ERROR] Your Lime/OpenFL configuration is using custom asset libraries, and you provided frameworkParams in Polymod.init(), but we couldn't find a match for this asset library: (vlc)]

### ISSUE THREAD

**Issue by Tabpi** [FunkinCrew/Funkin#2428]
- [ ] Windows
- [ ] Mac
- [X] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

I saw some people on MacOS with a similar issue solve it by running from terminal, this did not work for me. The game does compile but does not get any further than the loading screen, where it fades to black and exits. It's output is as follows.

https://pastebin.com/p864bFU9

**Comment by NotHyper-474** [comment]
Same here. I thought it was an error only in my end 'cause I had to compile their lime myself, but now I see it's not that. I'm in WSL2

**Comment by YahBoiiJose** [comment]
Yep, me too fellas. I'm on Debian Sid

**Comment by HerrSnorre** [comment]
Same here. On Arch.

I thought the problem was that VLC was not installed, but it is! I searched for VLC on haxelib and installed hxvlc, but nothing happened.

Maybe it's something with Pipewire, as my last brain cell suggested.


![image](https://github.com/FunkinCrew/Funkin/assets/79027813/c37e27f4-fe80-419f-ba3c-af4b45940301)
"no", said qpwgraph

At this point, i have no idea what does this error mean.

**Comment by NotHyper-474** [comment]
> I don't think there's much I can do other than wait for the devs to fix it, which I'm worried could take a while, also abt that they might just not care enough about the platform to fix it.

I guess they got this error as well and didn't bother trying to solve it at the time, which would explain why there's updated downloads for Windows and MacOS but not for Linux

**Comment by HerrSnorre** [comment]
I noticed something.
Compiling with `haxelib run lime test html5` (or `lime test html5`) makes the game run "natively" in the web browser.
So **maybe** the problem isn't with compiling the game, but with the executable itself. (i am not sure, i don't have **any** experience with Hexa)

**Comment by Noobz4Life** [comment]
Obviously expected, but commenting out line 126 allows the game to open (although without video support)

**Comment by Noobz4Life** [comment]
Actually, you can type haxelib git hxCodec https://github.com/FunkinCrew/hxCodec into the terminal and it also fixes it (presumably the commit they install with in hmm.json is broken on Linux for whatever reason)

**Comment by Tabpi** [comment]
> I noticed something. Compiling with `haxelib run lime test html5` (or `lime test html5`) makes the game run "natively" in the web browser. So **maybe** the problem isn't with compiling the game, but with the executable itself. (i am not sure, i don't have **any** experience with Haxe)

unrelated but..
itch version ate all my ram and made my computer lock up, idek how 😭
also I wanted to run it natively because the web version is capped at 60fps and looks stuttery to me

**Comment by Tabpi** [comment]
Fixed it for me as well!! tysmmm ^^

**Comment by YahBoiiJose** [comment]
> > You can type haxelib git hxCodec https://github.com/FunkinCrew/hxCodec into the terminal and it fixes it (presumably the commit they install with in hmm.json is broken on Linux for whatever reason)
> 
> Fixed it for me as well!! tysmmm ^^

Real

**Comment by znemux** [comment]
> You can type `haxelib git hxCodec https://github.com/FunkinCrew/hxCodec` into the terminal and it fixes it (presumably the commit they install with in hmm.json is broken on Linux for whatever reason)

I did that command, lime rebuild linux, then lime build linux -release, same issue. Is there something I'm missing?

**Comment by znemux** [comment]
I tried copying hxCodec in haxelib folder (where it downloaded) to .haxelib but I get this error:

```
 ERROR  source/funkin/modding/PolymodHandler.hx:294: characters 7-24

  294 |       coreAssetRedirect: CORE_FOLDER,
      |       ^^^^^^^^^^^^^^^^^
      | { coreAssetRedirect : Null<String>, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect
```
