### ISSUE TITLE
Bug Report: [You can press F1 several times to open the help guide several times]

### ISSUE THREAD

**Issue by amyspark-ng** [FunkinCrew/Funkin#2429]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
1. Open chart editor
2. Press F1
3. You can press F1 several times, which will open the help guide several times

https://github.com/FunkinCrew/Funkin/assets/92493175/46c919df-5cef-4c25-93e8-25da118035b6

## Please describe your issue. Provide extensive detail and images if possible.
You can open the help guide several times, if open should close and visceversa

**Comment by Hundrec** [comment]
No one's around to help.
(Reproduced in 0.5.1)

![image](https://github.com/user-attachments/assets/a3cdb4ed-3a5a-482f-9626-db71a947eb21)

**Comment by ninjamuffin99** [comment]
fixed with #3552 that was just merged

**Comment by amyspark-ng** [comment]
shouldn't this be added to changelog?

**Comment by Hundrec** [comment]
I think they're adding to the changelog internally

**Comment by ninjamuffin99** [comment]
it will be, i was gonna use a lil tool to generate the changelog instead of
writing every change manually

**Comment by amyspark-ng** [comment]
oh no worries then

**Comment by Lasercar** [comment]
lol, lmao even, imagine not checking to see if the stage editor has the same issue:
![Image](https://github.com/user-attachments/assets/2a4ca341-2edb-48da-b696-c4feff1c1e31)

**Comment by amyspark-ng** [comment]
ah nvm you already did it

**Comment by Lasercar** [comment]
> > lol, lmao even, imagine not checking to see if the stage editor has the same issue:
> 
> LOL when i made this fix there was no stage editor
> 
> I'll do it today

> ah nvm you already did it


Ah, if I knew that you wanted to fix this, I wouldn't have fixed it.

**Comment by amyspark-ng** [comment]
> > > lol, lmao even, imagine not checking to see if the stage editor has the same issue:
> > 
> > LOL when i made this fix there was no stage editor
> > 
> > I'll do it today
> 
> > ah nvm you already did it
> 
> 
> Ah, if I knew that you wanted to fix this, I wouldn't have fixed it.
> 
> 
> 

It's okay you already did the pr lol
