### ISSUE TITLE
'library lime not installed'

### ISSUE THREAD

**Issue by NewEater12k** [FunkinCrew/Funkin#2440]
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

when i type 'lime rebuild windows' or 'lime test windows' it gives me the error 'library lime not found'

**Comment by amyspark-ng** [comment]
Had this issue before, what i did was re-install haxe, and re-run the things said in the https://github.com/FunkinCrew/Funkin/blob/a6948c3a38c98af5d4e7dc04bd486e0aec4c87d1/docs/COMPILING.md#L4 guide, hope it helps

**Comment by NewEater12k** [comment]
yea i fixed it dw, it was a git error
thanks for the help tho

**Comment by amyspark-ng** [comment]
oh cool! glad you fixed it
