### ISSUE TITLE
Enhancement: Quick restart / "NOT R"

### ISSUE THREAD

**Issue by amyspark-ng** [FunkinCrew/Funkin#2442]
## What is your suggestion, and why should it be implemented?
There should be a key to make a quick restart, i know pressing R instantly kills you, but this is pretty slow since you have to go through the death animation, i think this should instead do the same as Restart song and instead pressing Ctrl + R or any other key for debugging should kill you instead

**Comment by amyspark-ng** [comment]
aw

**Comment by AbnormalPoof** [comment]
I'm one month late, but you can recreate this very easily within HScript.

```haxe
import funkin.modding.module.Module;
import funkin.play.PlayState;
import flixel.FlxG;

class QuickReset extends Module {
  function new() {
    super('QuickReset');
  }

  function onUpdate(event) {
    if (PlayState.instance != null) {
      if (FlxG.keys.pressed.CONTROL) {
        if (FlxG.keys.justPressed.F) {
          PlayState.instance.needsReset = true;
        }
      }
    }
  }
}
```

**Comment by amyspark-ng** [comment]
oh that's awesome, would there be a way to cancel the blue balls event with R?

**Comment by AbnormalPoof** [comment]
Not really, since calling `event.cancel();` in `onGameOver` will still trigger the Game Over screen. You can simply unbind the reset key though.
