### ISSUE TITLE
Bug Report: Hold Note Splashes not alligned properly on Downscroll

### ISSUE THREAD

**Issue by JamJarIsDumb** [FunkinCrew/Funkin#2443]
### If you are playing the game in a browser, what site are you playing it from?

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- \[ x \] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  * \[ x \] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

v 0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

This occurs all of the time.

## Please describe your issue. Provide extensive detail and images if possible.

Fairly small issue that can be overlooked, but I noticed that the hold note splashes are not lined up properly on downscroll. Below is an image of how they look on upscroll vs downscroll.

***UPSCROLL** (How they should look)*

![screenshot-2024-05-11-01-01-51](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/dadbe730-6408-4f57-8ed1-144149e93a3a/d794563c-2f26-4ea3-9685-bfc25d569e5d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi9kYWRiZTczMC02NDA4LTRmNTctOGVkMS0xNDQxNDllOTNhM2EvZDc5NDU2M2MtMmYyNi00ZWEzLTk2ODUtYmZjMjVkNTY5ZTVkIiwiaWF0IjoxNzE3MTA5NDI4LCJleHAiOjMzMjg3NjY5NDI4fQ.rCX5Z2tXtux-Mwq_LJCNhJePdKIXnbsONB8zUAeFhs4)

***DOWNSCROLL** (Not covering the hold note part)*

![screenshot-2024-05-11-01-02-16](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/3f0ebbd6-a89a-4ed6-8fde-14bd006e5d19/d426f9f4-5be7-4f63-8f6a-396e24576e57?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi8zZjBlYmJkNi1hODlhLTRlZDYtOGZkZS0xNGJkMDA2ZTVkMTkvZDQyNmY5ZjQtNWJlNy00ZjYzLThmNmEtMzk2ZTI0NTc2ZTU3IiwiaWF0IjoxNzE3MTA5NDI4LCJleHAiOjMzMjg3NjY5NDI4fQ.jErdM5j_aygQZjmtMfIOOW0cJODceOnWb2LexOUN7Tg)

As you can see, you can see the part where the hold note gets cut off, which I **assume** from how it looks on upscroll is supposed to be covered by the new hold splash assets.

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

**Comment by EliteMasterEric** [comment]
Got fixed in #2488
