### ISSUE TITLE
Bug Report:Game fails to load upon opening

### ISSUE THREAD

**Issue by gdandsm64fan123** [FunkinCrew/Funkin#2444]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?
![Captura de pantalla (42)](https://github.com/FunkinCrew/Funkin/assets/110691219/b3f2ae75-3014-4060-86dd-54c17475aa4a)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Just opening the game a day later completely breaks it.
## Please describe your issue. Provide extensive detail and images if possible.

When i open the game it starts to "download assets" and then this error comes up:
[lime.utils.Preloader] ERROR: There is no library assets with an ID of "songs".

**Comment by gdandsm64fan123** [comment]
can someone help me? i tried extracting the zip file again and again but it doesnt work

**Comment by gdandsm64fan123** [comment]
trying to delete the ninjamuffin99 appdata folder
lets see if this works

**Comment by gdandsm64fan123** [comment]
nope still errors

**Comment by gdandsm64fan123** [comment]
heres a view from the command line
![Captura de pantalla (43)](https://github.com/FunkinCrew/Funkin/assets/110691219/d8f7ed58-0482-4cef-8311-657c776916f7)

**Comment by gdandsm64fan123** [comment]
it seems to have to do with the scores.json file.. opening from the zip launches the game normally

**Comment by gdandsm64fan123** [comment]
ill check it tommorrow

**Comment by NotHyper-474** [comment]
I only get this issue when trying to run the .exe through the Terminal, but also only when the current working directory is not the game folder. So being at "C:\" and trying to run "C:\>path-to-funkin-folder\Funkin.exe" triggers that error, but being at "C:\path-to-funkin-folder\" and running "Funkin.exe" does not.

So, seems like the executable is not able to find the files it needs to run if executed from a different folder

**Comment by gdandsm64fan123** [comment]
interesting...
When i open the game using the bar where u type the directory (aka typing "funkin.exe" there) it open up normally and as well when i open it using the taskbar.

**Comment by gdandsm64fan123** [comment]
Idk if they should fix it but its just an inconvinience.

**Comment by gdandsm64fan123** [comment]
if anyone wants to close it please do.

**Comment by moxie-coder** [comment]
> if anyone wants to close it please do.

there is a close button dude

**Comment by NotHyper-474** [comment]
https://github.com/FunkinCrew/Funkin/pull/2629 might fix this.
