### ISSUE TITLE
Compiling help: [Missing SpectralAnalyzer?  / funkin.vis.dsp.SpectralAnalyzer]

### ISSUE THREAD

**Issue by Ethan-makes-music** [FunkinCrew/Funkin#2463]
#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
When compiling, I get this error: 
![image_2024-05-11_152258403](https://github.com/FunkinCrew/Funkin/assets/94811149/8a0ec779-cfa7-48f4-8af1-e103c7f17607)
I check the source to see if its a missing script and when I check: "funkin/audio/visualize/dsp". I dont see a script called SpectralAnalyzer. So I am thinking that's my problem, (that the file isn't there). Are there any other links to the file so I can add it in the source or a solution to the problem in general?

**Comment by Ethan-makes-music** [comment]
Also forgot to say this... I did not edit ANYTHING! This is fresh out of the instructions in the COMPILING.md. Absolutely no changes were made!

**Comment by Ethan-makes-music** [comment]
Also forgot to say this... I did not edit ANYTHING! This is fresh out of the instructions in the COMPILING.md. Absolutely no changes were made!

**Comment by NotHyper-474** [comment]
Did you run `hmm install` like the compiling guide says? If so did it give any error?

**Comment by Ethan-makes-music** [comment]
> Did `hmm install` give any error? If it did then try switching to develop branch and running it again.
> 
> Also likely a duplicate of #2298

It did not give an error when running 'hmm install' but I switched to develop branch anyways and I dont get that error anymore but now I get 
![image](https://github.com/FunkinCrew/Funkin/assets/94811149/fb02b270-1c71-4638-b274-aef16758871d)
sooo ¯\_(ツ)_/¯

**Comment by NotHyper-474** [comment]
Now that's a different issue. [According to Eric](https://github.com/FunkinCrew/Funkin/issues/2299#issuecomment-2099611719) that error happens when using an older version of Polymod.

Perhaps you could try make hmm reinstall Polymod again (through `hmm reinstall --force polymod`) but if other libraries were not installed properly as well then it'll just start throwing other errors, so it's probably better to run just `hmm reinstall`

**Comment by Ethan-makes-music** [comment]
> Now that's a different issue. [According to Eric](https://github.com/FunkinCrew/Funkin/issues/2299#issuecomment-2099611719) that error happens when using an older version of Polymod.
> 
> 
> 
> Perhaps you could try make hmm reinstall Polymod again (through `hmm reinstall --force polymod`), but if other libraries were also not installed properly then it'll just start throwing other errors, so it's probably better to run just `hmm reinstall --force`
> 
> 
> 
> 

Ya all of it works now like i can compile it to html5 but when i try to do windows it gives me this error seen in [#2378](https://github.com/FunkinCrew/Funkin/issues/2378) so ima be tryna fix thag for a while thanks for your help though! Feel free to comment again if u wanna
