### ISSUE TITLE
Week 5 Update General Bugginess

### ISSUE THREAD

**Issue by Murfykiddo** [FunkinCrew/Funkin#247]
Since week 5 update game crashes a lot more, certain aspects will fail to load resulting a black void as the background around the tree, or a comical censor bar over the parents and other such glitches. It will also just kinda poop out when transition into songs.

**Comment by regulad** [comment]
What site/build are you accessing the game from? If you could provide steps to reproduce that helps too.

**Comment by Murfykiddo** [comment]
All that its available on. On newgrounds it might load sometimes but
usually it crashes while loading and if not it crashes on song selection.
On itch.io it just freezes on the load bar. And in the downloaded version
the 32 bit one always crashes on song selection and the 64 bit one is a bit
mroe reliable but it will randomly lose assets. It has failed the load the
full background besides the tree and parents of week 5 and it has also
failed to load the parents, resulting in an almost comical censor bar that
takes up the space where they would be. Restarting songs when any assets
are missing crashes the game instantly
