### ISSUE TITLE
Compiling help:  ERROR  source/funkin/modding/PolymodHandler.hx:294: characters 7-24    294 |       coreAssetRedirect: CORE_FOLDER,       |       ^^^^^^^^^^^^^^^^^       | { coreAssetRedirect : Null<String>, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect

### ISSUE THREAD

**Issue by chicken-nugget1104** [FunkinCrew/Funkin#2471]
ERROR  source/funkin/modding/PolymodHandler.hx:294: characters 7-24

  294 |       coreAssetRedirect: CORE_FOLDER,
      |       ^^^^^^^^^^^^^^^^^
      | { coreAssetRedirect : Null<String>, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect
      
      WHAT DO I DO TO FIX THIS
      
      im using everything from the develop branch, and i used hmm to install everything
      so what the fluff is happening this wasnt happening earlier!!

**Comment by moxie-coder** [comment]
duplicate of #2299
