### ISSUE TITLE
Compiling help: Can't compile game, even without changing code.

### ISSUE THREAD

**Issue by Declan-Reid** [FunkinCrew/Funkin#2480]
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
I'm trying to compile the game before I made any mods, but I can't do that due to some errors in OpenFL. I don't understand what is going on.

Console dump:

```2794@Declan-Reid funkin % lime test mac -debug
Warning: Lime version 8.1.2 may not be compatible with OpenFL 9.2.2 (expected version 7.7.0+)
Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
source/Prebuild.hx:15: Building...
source/funkin/util/macro/GitCommit.hx:55: Git Branch Name: main
source/funkin/util/macro/GitCommit.hx:26: Git Commit ID: a6948c3
source/funkin/util/macro/GitCommit.hx:101: Git Status Output: 
 WARNING  /Users/2794/Documents/GitHub/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 WARNING  /Users/2794/Documents/GitHub/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 WARNING  /Users/2794/Documents/GitHub/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 WARNING  /Users/2794/Documents/GitHub/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 WARNING  /Users/2794/Documents/GitHub/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 WARNING  /Users/2794/Documents/GitHub/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 ERROR  /Users/2794/Documents/GitHub/funkin/.haxelib/openfl/git/src/openfl/utils/Assets.hx:602: characters 49-55

 602 |      LimeAssets.registerLibrary(name, _library, unload);
     |                                                 ^^^^^^
     | Too many arguments

 ERROR  /Users/2794/Documents/GitHub/funkin/.haxelib/openfl/git/src/openfl/utils/Assets.hx:602: characters 49-55

 602 |      LimeAssets.registerLibrary(name, _library, unload);
     |                                                 ^^^^^^
     | Too many arguments

 ERROR  /Users/2794/Documents/GitHub/funkin/.haxelib/lime/8,1,2/src/lime/system/Sensor.hx:15: characters 24-62

  15 |  public var onUpdate = new Event<Float->Float->Float->Void>();
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Unknown<0> cannot be constructed```

Any and all help is appreciated. I know this is not an awfully descriptive issue, but I'm not sure what to even write.

**Comment by biomseed** [comment]
You're using the wrong version of lime, I know that much. The one from the funkin crew's fork uses 8.0.2, not 8.1.2. Make sure you switch to the funkin crew versions of your libraries and not the vanilla ones. You either installed the wrong ones, installed the wrong ones after you installed the right ones, or it didn't switch the libraries. I hope you used the compiling guide because it goes through how to get the libraries

**Comment by Declan-Reid** [comment]
I've now installed 8.0.2, but it hasn't made an effect. I also uninstalled 8.1.2 so that shouldn't be affecting it. I tried to follow the compiling guide as close as I could.

**Comment by Declan-Reid** [comment]
And how would I "switch to the funkin crew versions of your libraries". No clue how.

**Comment by NotHyper-474** [comment]
>And how would I "switch to the funkin crew versions of your libraries". No clue how.  

`hmm install` should already do that for you. What's your current Haxe version btw? You can see it with `haxe --version`

**Comment by Declan-Reid** [comment]
My haxe is on version 4.3.4. I ran ``hmm install`` during installation so I'm not sure.

**Comment by NotHyper-474** [comment]
Hmm it's possible it could be using non-Funkin Lime. Try doing `haxelib git lime https://github.com/FunkinCrew/lime`

**Comment by Declan-Reid** [comment]
Well I uninstalled lime and recompiled the game and now I only have on error, but its not the same, so I'm working on that. I'll see if this compile fixes it.

**Comment by biomseed** [comment]
> Hmm it's possible it could be using non-Funkin Lime. Try doing `haxelib git lime https://github.com/FunkinCrew/lime`

You can switch versions of libraries. You don't need to install it again.

**Comment by NotHyper-474** [comment]
> > Hmm it's possible it could be using non-Funkin Lime. Try doing `haxelib git lime https://github.com/FunkinCrew/lime`
> 
> You can switch versions of libraries. You don't need to install it again.

How, then?

**Comment by biomseed** [comment]
> > > Hmm it's possible it could be using non-Funkin Lime. Try doing `haxelib git lime https://github.com/FunkinCrew/lime`
> > 
> > 
> > You can switch versions of libraries. You don't need to install it again.
> 
> How, then?

`haxelib set [project-name] [version]`

**Comment by Declan-Reid** [comment]
I HAVE NEWS. I deleted .haxelib and ran ``hmm install`` and it built! Thank you all!

**Comment by NotHyper-474** [comment]
Good to hear that you managed to solve it!
