### ISSUE TITLE
Compiling help: Error: Video.cpp ./src/hxcodec/openfl/Video.cpp(6): fatal error C1083: Cannot open include file: 'vlc/vlc.h': No such file or directory

### ISSUE THREAD

**Issue by chicken-nugget1104** [FunkinCrew/Funkin#2484]
Error: Video.cpp
./src/hxcodec/openfl/Video.cpp(6): fatal error C1083: Cannot open include file: 'vlc/vlc.h': No such file or directory

what. im on the dev branch i dont think this is a duplicate i just want help :(

**Comment by NotHyper-474** [comment]
Are you trying to compile to Linux by any chance?

**Comment by chicken-nugget1104** [comment]
> Are you trying to compile to Linux by any chance?

windows.

**Comment by chicken-nugget1104** [comment]
> Are you trying to compile to Linux by any chance?

arent you the person who made the bump hxCodec pr? im actually trying that RN to see if it fixes the issue!

**Comment by NotHyper-474** [comment]
> > Are you trying to compile to Linux by any chance?
> 
> arent you the person who made the bump hxCodec pr? im actually trying that RN to see if it fixes the issue!

Nah that's other guy. I was asking 'cause I was having the same problem on Linux.
I don't remember how I fixed it but I think it was either a missing Linux vlc library or me reinstalling some Haxelib library, which was probably hxCodec

**Comment by chicken-nugget1104** [comment]
> > > Are you trying to compile to Linux by any chance?
> > 
> > 
> > arent you the person who made the bump hxCodec pr? im actually trying that RN to see if it fixes the issue!
> 
> Nah that's other guy. I was asking 'cause I was having the same problem on Linux. I don't remember how I fixed it but I think it was either by installing a missing Linux vlc library or by reinstalling some Haxelib library, which was probably hxCodec. It guess it was the latter that fixed it

Ok ok i am trying to re-install hxCodec rn and then compiling (doing that RN) if it doesn't work then ima be sad :(

**Comment by chicken-nugget1104** [comment]
Doesn't even install now using the branch 2aa654b974507ab51ab1724d2d97e75726fd7d78 so uh :(

**Comment by NotHyper-474** [comment]
What do you mean? That branch is for funkin.Vis

**Comment by chicken-nugget1104** [comment]
> What do you mean? That branch is for funkin.Vis
> 
> Edit: Oh I see what's happening. Seems like that PR is trying to use funkin.Vis branch in hxCodec, maybe an oversight on his part. Reinstall but without using that PR.

eh ok uh i aint using that pr i just tried doing it thru powershell uh i cant fix it :( i can try reinstalling hxCodec over and over but it will never work so i dont know if i can ever fix my bug :((

**Comment by NotHyper-474** [comment]
Well sorry but idk how to solve it then. I guess the last thing you could try is deleting the .haxelib folder (or using `hmm clean` for that) and running hmm install again, could be other library other than hxCodec that's causing it so reinstalling everything could perhaps fix that.

**Comment by chicken-nugget1104** [comment]
> Well sorry but idk how to solve it then. I guess the last thing you could try is deleting the .haxelib folder (or using `hmm clean` for that) and running hmm install again, could be other library other than hxCodec that's causing it so reinstalling everything could perhaps fix that.

i finally got it to install!! :) will try compiling! btw do u have discord i would like more help from u

**Comment by chicken-nugget1104** [comment]
didnt fix

**Comment by chicken-nugget1104** [comment]
> didnt fix

did hmm clean and reinstalled it didnt work.

**Comment by NotHyper-474** [comment]
Sorry but I ran out of options. I hope someone else is able solve your issue.

**Comment by chicken-nugget1104** [comment]
> Sorry but I ran out of options. I hope someone else is able solve your issue.

its ok no one really likes to help with issues alot

**Comment by NotHyper-474** [comment]
Could you try `lime test windows -clean`?

**Comment by EliteMasterEric** [comment]
Try deleting your repo, and following the compilation guide again from scratch.

**Comment by chicken-nugget1104** [comment]
> Try deleting your repo, and following the compilation guide again from scratch.

That wouldn't work, i already tried same error.

I just gave up that's why i haven't responded to this in a while

**Comment by chicken-nugget1104** [comment]
But im'a close this now... no longer intrested in modding FNF anymore, and if i am then i will just use the legacy branch cuz that work's.
