### ISSUE TITLE
Compiling help: It appears a lot of warnings (not very much) for the HX files (obviously) / MathUtil.coolLerp: (WDeprecated) Use smoothLerp instead

### ISSUE THREAD

**Issue by Osmaci123** [FunkinCrew/Funkin#2485]
`lime test windows
source/Prebuild.hx:15: Building...
source/funkin/util/macro/GitCommit.hx:26: Git Commit ID: a6948c3
source/funkin/util/macro/GitCommit.hx:101: Git Status Output:  M source/funkin/play/notes/NoteSplash.hx
source/funkin/util/macro/GitCommit.hx:55: Git Branch Name: main
source/funkin/ui/credits/CreditsDataMacro.hx:13: Hardcoding credits data...
source/funkin/ui/credits/CreditsDataHandler.hx:39: CreditsData(33 entries containing 113 lines)
 WARNING  C:/Users/omate/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 WARNING  C:/Users/omate/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 WARNING  C:/Users/omate/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 WARNING  C:/Users/omate/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 WARNING  C:/Users/omate/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 WARNING  C:/Users/omate/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

 196 |  public function switchTo(nextState:FlxState):Bool
 197 |  {
 198 |   return true;
 199 |  }
     |
     | switchTo is deprecated, use startOutro

 WARNING  source/funkin/ui/freeplay/FreeplayState.hx:736: characters 17-34

 736 |     lerpScore = MathUtil.coolLerp(lerpScore, intendedScore, 0.2);
     |                 ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/freeplay/FreeplayState.hx:737: characters 22-39

 737 |     lerpCompletion = MathUtil.coolLerp(lerpCompletion, intendedCompletion, 0.9);
     |                      ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/play/components/HealthIcon.hx:207: characters 38-55

 207 |         var targetSize:Int = Std.int(MathUtil.coolLerp(this.width, HEALTH_ICON_SIZE * this.size.x, 0.15));
     |                                      ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/play/components/HealthIcon.hx:213: characters 38-55

 213 |         var targetSize:Int = Std.int(MathUtil.coolLerp(this.height, HEALTH_ICON_SIZE * this.size.y, 0.15));
     |                                      ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/play/components/HealthIcon.hx:219: characters 20-37

 219 |       this.angle = MathUtil.coolLerp(this.angle, 0, 0.15);
     |                    ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/Alphabet.hx:224: characters 11-28

 224 |       y = MathUtil.coolLerp(y, (scaledY * 120) + (FlxG.height * 0.48), 0.16);
     |           ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/Alphabet.hx:225: characters 11-28

 225 |       x = MathUtil.coolLerp(x, (targetY * 20) + 90, 0.16);
     |           ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/MenuItem.hx:48: characters 9-26

  48 |     y = MathUtil.coolLerp(y, (targetY * 120) + 480, 0.17);
     |         ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/freeplay/SongMenuItem.hx:332: characters 11-28

 332 |       x = MathUtil.coolLerp(x, targetPos.x, 0.3);
     |           ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/freeplay/SongMenuItem.hx:333: characters 11-28

 333 |       y = MathUtil.coolLerp(y, targetPos.y, 0.4);
     |           ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/options/FunkinSoundTray.hx:80: characters 9-26

  80 |     y = MathUtil.coolLerp(y, lerpYPos, 0.1);
     |         ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/options/FunkinSoundTray.hx:81: characters 13-30

  81 |     alpha = MathUtil.coolLerp(alpha, alphaTarget, 0.25);
     |             ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead

 WARNING  source/funkin/ui/story/LevelTitle.hx:57: characters 14-31

  57 |     this.y = MathUtil.coolLerp(y, targetY, 0.17);
     |              ^^^^^^^^^^^^^^^^^
     | (WDeprecated) Use smoothLerp instead`

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

IDK if I did something for not installing correctly from the hmm or something else. I want to think that I compile it very good. It opens the .exe, but in the week 7 I can't play the "stress" level/song, and it appears an error of the HX files that doesn't compile very well (ignore the "NoteSplash.hx" thing). 

Also, if I said something that you cannot read, it is because I only speak/write Spanish. I have skill issue to write in English (I think).

**Comment by chicken-nugget1104** [comment]
its not an error. this normally happens. the warnings arent errors. i encounter them too but they dont stop compiling.

**Comment by NotHyper-474** [comment]
They have replaced the obsolete functions in the latest commits so these warning won't appear anymore.

**Comment by Osmaci123** [comment]
Ok, thanks

**Comment by NotHyper-474** [comment]
Turns out I was wrong, I swear they had replaced those. Anyways, these won't affect the compilation and can be safely ignored.
