### ISSUE TITLE
"Cleared" percentage appears to always be 90%+ even though I clearly fucked the chart up alot

### ISSUE THREAD

**Issue by mallownimbus** [FunkinCrew/Funkin#2486]
Pretty self explanatory, at first I didn't notice anything because I thought I was just good at the game, but then I played a v-slice whitty port and saw that I somehow had a "90%" clear on ballistic old, even though I VERY clearly got a shitton of misses
![image](https://github.com/FunkinCrew/Funkin/assets/161256480/d3b511b2-539d-44ae-853c-e65a8173a7b8)

I did Spookeez Nightmare and again noticed that I had a "95%" cleared percentage even though the results screen says that I got 83 bad, 32 shit, and 39 missed
![image](https://github.com/FunkinCrew/Funkin/assets/161256480/653cf2a5-f184-4a63-944f-09efaf2258d6)
![image](https://github.com/FunkinCrew/Funkin/assets/161256480/faaea61e-4ae5-4fcb-ad7a-dc9ebacbd515)

Looked through all of the charts that i've played and they ALL have a 90%+ clear on them
There's definitely something wrong with how the game calculates clear percentages

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

v0.3.2

**Comment by METGameDev** [comment]
(notes hit)/(notes in song) = clear
(874-39)/874 = ~95%

the game rates your clear based on how many notes you hit outta how many notes there are, NOT how well you hit the notes.

**Comment by mallownimbus** [comment]
ohh i see, still doesnt make sense to only calculate the notes and not how well you hit them since getting a bad or shit breaks your combo

**Comment by mallownimbus** [comment]
whoops FUCK lol

**Comment by Hundrec** [comment]
Pretty sure some mod changed the way clear percentages were calculated (if that's even possible for mods to do).
The percentage for Spookeez Erect should definitely be 759/874 ≈ 87%.
