### ISSUE TITLE
Compiling help: source/funkin/Conductor.hx:256: characters 17-18 : Unexpected .

### ISSUE THREAD

**Issue by NickIdk1235** [FunkinCrew/Funkin#2489]
I tried to change the code where it's telling me where the error is occurring, but I don't want to cause more errors to happen.
`source/funkin/Conductor.hx:256: characters 17-18 : Unexpected .`
![image](https://github.com/FunkinCrew/Funkin/assets/97841607/ec16460e-19bc-4697-a2cb-c40279764dc5)
-----------------------------------
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5
------------------------------------

**Comment by moxie-coder** [comment]
you need haxe 4.3

**Comment by NickIdk1235** [comment]
Thanks
