### ISSUE TITLE
Compiling help: [Error: type not found : hxjsonast.json]

### ISSUE THREAD

**Issue by dougy2shoez** [FunkinCrew/Funkin#2491]
When compiling, i get this issue:
![image](https://github.com/FunkinCrew/Funkin/assets/79595919/ebb5b121-1529-43e2-a2f9-42e1a764a80b)
i dont know where to find hxjsonast.json 

- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

**Comment by NotHyper-474** [comment]
You're supposed to specify the platform, `lime test windows`, for instance

**Comment by justamole** [comment]
![image](https://github.com/FunkinCrew/Funkin/assets/79595919/36059435-1196-45f5-b204-91db6a41f122)
i resorted to that after trying ‘lime test windows’ and it gave me this error.

**Comment by NotHyper-474** [comment]
Are you sure you followed the [Compiling guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/COMPILING.md) correctly?

**Comment by justamole** [comment]
Yes

**Comment by justamole** [comment]
So what's the issue

**Comment by justamole** [comment]
Theres no hxjsonast.json

**Comment by EliteMasterEric** [comment]
You definitely didn't complete the compilation guide.

**Comment by dougy2shoez** [comment]
how could i be so foolish..
