### ISSUE TITLE
In Dadbattle, on Hard, you can miss notes without losing health.

### ISSUE THREAD

**Issue by SonicBlam** [FunkinCrew/Funkin#25]
If you play Dadbattle on Hard mode, missing notes will not cause loss of health. Pressing a key at the wrong time still will, however.
This allows you to win Dadbattle in Hard mode without pressing any buttons at all.
As far as I know, this doesn't happen with other tracks, and it doesn't happen in other difficulties either.

**Comment by SonicBlam** [comment]
#10 #13 
Found 2 similar threads, one of which is on the exact same issue. This is still not fixed, at least on the web versions.
And unlike what issue 10 says, this applies to Dadbattle in Story mode as well.

**Comment by ninjamuffin99** [comment]
pushed out the update earlier today with the 0.2.3 update, tell me if its still busted and I'll reopen the issues!
