### ISSUE TITLE
Random frame loss in the middle of songs

### ISSUE THREAD

**Issue by Flightless-Plane** [FunkinCrew/Funkin#250]
Basically i'll be playing any song, but after about 10 seconds or so, the game will go down to about 2-3 fps, yet the song still plays in the background, so we miss notes. There might be something running in the back of the code that takes up too much processing(i wouldn't know i haven't coded in 7 years). Maybe adding an auto pause when the frames get too low could help somewhat?

**Comment by gedehari** [comment]
Same, mine happens on the HTML5 build. Is it the same for you?
