### ISSUE TITLE
Compiling help: [Paths.hx / unexpected ?]

### ISSUE THREAD

**Issue by bf244** [FunkinCrew/Funkin#2505]
help?

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

i try to compile the game and this happens, i have everything needed to compile
![image](https://github.com/FunkinCrew/Funkin/assets/84717235/9dde0628-7fea-4825-b45e-70e39a875d83)

source/Prebuild.hx:15: Building...
source/funkin/Paths.hx:116: characters 75-76 : Unexpected ?

**Comment by NotHyper-474** [comment]
Could be related to https://github.com/FunkinCrew/Funkin/issues/2489
Make sure you're using Haxe 4.3

**Comment by bf244** [comment]
i updated haxe but now it says this what should i do?
![image](https://github.com/FunkinCrew/Funkin/assets/84717235/80a248de-f723-4d14-bd2b-8722edccf6ac)

**Comment by bf244** [comment]
> Could be related to #2489 Make sure you're using at least Haxe 4.3

i updated haxe to 4.3.4 and now it says this what should i do?
![image](https://github.com/FunkinCrew/Funkin/assets/84717235/50d53cc0-a22f-4083-af7d-c1c474f00c8d)

**Comment by NotHyper-474** [comment]
Have you setup `hmm` like the Compiling guide says?

**Comment by bf244** [comment]
> Have you setup `hmm` like the Compiling guide says?

Yes

**Comment by bf244** [comment]
i tried to remove haxe and install everything else and now says this
![image](https://github.com/FunkinCrew/Funkin/assets/84717235/63573938-d10b-4826-9434-6d66d52da1e5)
any ideas?
