### ISSUE TITLE
Issue adding mods now that Week 5 has been added.

### ISSUE THREAD

**Issue by yxkimxrax** [FunkinCrew/Funkin#251]
I'm working on a new mod/skins for this game and I have 2 versions: one w/o Week 5 and one with Week 5. I'm changing out the Mom_Assets png for the one containing the skins I'm using and it will not implement into the Week 5 version. It worked fine with the old version but not with this one. The Mom_Assets is the only one that does it, as I have assets for the spooky kids, dad, and gf all done and they work fine. When loading up the levels with just the mom, it gives me the Mom's Assets even though she's no longer in the folders of the game. If someone could help, that would be great.

**Comment by regulad** [comment]
In v0.2.6, `mom` is unused. `mom-car` is used for week 4 in version 0.2.6. Hope that helps.

**Comment by regulad** [comment]
![image](https://user-images.githubusercontent.com/52430642/105429022-a1e75a00-5c1e-11eb-931b-1de463567541.png)
Use these files

**Comment by yxkimxrax** [comment]
Got it, thank you so much!
