### ISSUE TITLE
Compiling help: [Copy haxeToolkit ]

### ISSUE THREAD

**Issue by bf244** [FunkinCrew/Funkin#2513]
when i type in haxelib --global run hmm setup after typing haxelib --global install hmm
it says this copy C:/HaxeToolkit/haxe/lib/hmm/3,1,0/hmm.cmd C:/HaxeToolkit/haxe/hmm.cmd
ideas?

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

**Comment by AltronMaxX** [comment]
It's normal behavior for this command.

**Comment by bf244** [comment]
> It's normal behavior for this command.

Oh ok

**Comment by Hackx2** [comment]
wha?!?!?
