### ISSUE TITLE
Compiling help: [Postbuild / funkin.art]

### ISSUE THREAD

**Issue by ITzGabGB** [FunkinCrew/Funkin#2514]
i try to compile but this happens
![image](https://github.com/FunkinCrew/Funkin/assets/84717235/3bc408e1-e167-4c47-9132-d10d71ef8817)
any ideas?

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

**Comment by EliteMasterEric** [comment]
You didn't follow the compilation guide properly.
