### ISSUE TITLE
Bug Report: A compile Issue relating polymodhandler.hx

### ISSUE THREAD

**Issue by LeonGamerPS1** [FunkinCrew/Funkin#2516]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.3

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
nah
## Please describe your issue. Provide extensive detail and images if possible.

so i tried to compile on latest haxe version and this popped up
![image](https://github.com/FunkinCrew/Funkin/assets/108237023/68b7b0c8-91d0-44bf-bd4f-f750490c0eeb)

heres my haxe version 
![image](https://github.com/FunkinCrew/Funkin/assets/108237023/354551aa-bbe9-477e-89d5-7e1f51595e1a)

and the version of the libs

![image](https://github.com/FunkinCrew/Funkin/assets/108237023/e90465be-22e3-4246-9ff0-b12853089bb1)

**Comment by ShartDev1** [comment]
send me the polymod version

**Comment by ShartDev1** [comment]
now ok

**Comment by Hundrec** [comment]
This issue has been resolved, so you should close it.

**Comment by LeonGamerPS1** [comment]
closed
