### ISSUE TITLE
Bug Report: [the Funkin application still not loading on Mac]

### ISSUE THREAD

**Issue by ProjectDreadman** [FunkinCrew/Funkin#2520]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [x] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.3

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Open the application up on Mac

## Please describe your issue. Provide extensive detail and images if possible.
So pretty much whenever I try to open up the Funkin application on Mac it loads but then it closes/crashes instantly.

https://github.com/FunkinCrew/Funkin/assets/168795340/a2b2bfb3-2f5e-46c2-80c8-7634f3965e33

 I thought it was a one time thing but it kept happening whenever I try to open up the application

**Comment by biomseed** [comment]
It can't have been created yesterday if it's 0.3.3

**Comment by NotHyper-474** [comment]
The game has only been updated for x64 Windows at the moment
