### ISSUE TITLE
Bug Report: [Chart Menu Wont Open (See Description)]

### ISSUE THREAD

**Issue by Fletchpike** [FunkinCrew/Funkin#2530]
Anytime I Try To Open The Chart Menu I Does Not Work! I Go To Options Add Bindings To "Chart" And Press That Key Nothing Happens, I Even Go To Freeplay. Still Nothing Happens Not Sure Why?

### If you are playing the game in a browser, what site are you playing it from?

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [x] box!)

- [ x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

[game version]
v0.3.3

**Comment by AbnormalPoof** [comment]
The chart editor is currently not supported on web.
https://twitter.com/ninja_muffin99/status/1785492222898577527

**Comment by Fletchpike** [comment]
Thanks at least i know now

**Comment by EliteMasterEric** [comment]
Chart editor is disabled on web.

As of v0.5.1, the chart editor keybind is now hidden from the controls list on builds where the chart editor is hidden, so I'd mark this resolved.

We'll get chart editor working on Newgrounds eventually.
