### ISSUE TITLE
Enhancement: Improved Practice Mode

### ISSUE THREAD

**Issue by NandoBroquiGames** [FunkinCrew/Funkin#2535]
### My Problem

I already beat the entire game in fucking hard mode, now I'm trying the fucking erect mode, but I can't pass the fucking first week 2 song due to unpracticable and fast patterns. There's the fast "right down left down" pattern, which's super fast; and some crazy one involving pressing the arrows in chronological order forward and backwards, but with a catch, a random fucking up or down note will appear to ruin the arrow spam. I'm playing the game in the "DFJK" control set, and this helped me a lot beat the first week erect difficulty, but I can't catch up to week 2.

I already tried practicing with practice mode, but it's kinda the same experience (note: I practiced it once, should I try it more times?), and it sucks trying to use the chart menu as it's super unpolished as some arrows doesn't even appear.

### Ideas

After a game over, it would be cool if you could spectate the song's chart to check what notes you're missing. This can also be fixed by making the chart editor much more practical, as it's not only extremely bugged, it sucks having to select the difficulty manually even though it says "Spookez (Erect) loaded".

Another thing I would suggest is to make an option that slows the song's BPM to make the song slower and easy to practice, because starting slower and easier is the solution for most stuff (kinda contradicting since I already got through the entire game, lol, jk).

### Other

Maybe it's easier to ask "what can I do for now?", I suck at this game, is there anything I'm missing that I'm not having fun with it?

Hope I can get any help from this, lol. Have a nice day!

**Comment by amyspark-ng** [comment]
For now you could just keep practicing or change the playback speed in the audio tab in the chart editor

**Comment by JackXson-Real** [comment]
Just use the chart editor and keep using minimal playtest (shift + enter) to keep playing from a specific spot to practice. Thats what Ive been doing for the erect songs, and I also did that using psych engine before the update.

**Comment by NandoBroquiGames** [comment]
> Just use the chart editor and keep using minimal playtest (shift + enter) to keep playing from a specific spot to practice. Thats what Ive been doing for the erect songs, and I also did that using psych engine before the update.

Didn't know this was possible, lol. I'll try that, thank you!

**Comment by EliteMasterEric** [comment]
The "Play Song at Specific Speed" and "Play Song Starting at Specific Point" features are all available from the Chart Editor, but I'd personally agree this stuff should be accessible with a comfortable UI from the Freeplay menu. Compare with Beat Saber's practice mode.

**Comment by JackXson-Real** [comment]
> The "Play Song at Specific Speed" and "Play Song Starting at Specific Point" features are all available from the Chart Editor, but I'd personally agree this stuff should be accessible with a comfortable UI from the Freeplay menu. Compare with Beat Saber's practice mode.

I agree, I hope you guys add that soon since it would be extremely useful and would be much more intuitive

**Comment by Lasercar** [comment]
https://github.com/FunkinCrew/Funkin/pull/4107

This issue has a pending PR.

**Comment by pedro3997** [comment]
SUGGESTION: How about the concept of being able to fast-forward, rewind, or go to a certain part of a song in Practice Mode? This way, if you want to practice a difficult part at the end of a song, you don’t have to go through it entirely first. It could be a feature OUTSIDE of the chart editor so that It’s compatible for both PC and mobile. Thanks to this, Practice Mode would be a more useful tool for pro players that want to P rank songs, and to casual players as well!
