### ISSUE TITLE
Bug Report: Sometimes misses show as 0, but note combo resets

### ISSUE THREAD

**Issue by JackXson-Real** [FunkinCrew/Funkin#2541]
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.3

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
You have to do very specific timings or something to recreate it. The best way Ive found to recreate it is by playing South nightmare mode since my skill with the chart is just enough to be able to do this precise timing. You will know if you have successfully recreated this if you see your combo counter reset to 0 in-game, but you don't hear the note missed sound effect.

## Please describe your issue. Provide extensive detail and images if possible.
Sometimes misses don't register, but note combo resets. In the results screen, it will show my max combo is less than my total notes, but my misses still show as 0, and it shows me having a 100% score on the freeplay menu even though I supposedly missed a note. Here are some screenshots showing what it looks like: 
![screenshot-2024-05-17-19-12-30](https://github.com/FunkinCrew/Funkin/assets/32755192/31e67249-3936-40aa-a5fa-bc0d6103ff61)
![screenshot-2024-05-17-19-21-02](https://github.com/FunkinCrew/Funkin/assets/32755192/fb92fd54-b169-4ab9-ae94-8a48ef1e3e09)

**Comment by EliteMasterEric** [comment]
Getting a BAD or a SHIT breaks your combo now. You have to get all GOOD and SICK to get a perfect combo.

**Comment by JackXson-Real** [comment]
> Getting a BAD or a SHIT breaks your combo now. You have to get all GOOD and SICK to get a perfect combo.

Ah ok, makes sense
