### ISSUE TITLE
Compiling help: [Stuck on compiling / GitCommit]

### ISSUE THREAD

**Issue by Daikicalla** [FunkinCrew/Funkin#2546]
Compiling for:
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

So, I've been struggling to compile for the past 8 hours now. I have forked and ran into some issues, so i ended up following the official compilation guide. However, at the start of compiling it immediately gets stuck.

![image](https://github.com/FunkinCrew/Funkin/assets/107242652/81f83bf7-68b3-4a4c-828e-1c6f86ed4976)
**It will not continue after this.**
Doesn't matter if i do it for Linux, Mac or HTML5, or if I do any of them in debug, it refuses to continue. I have yet to find an issue that's similar to this that has been resolved, or been called out at all. Is there any way I can fix this?

**Comment by NotHyper-474** [comment]
Have you seen #2374? Seems to be caused by deleting a bunch of files

**Comment by Daikicalla** [comment]
> Have you seen #2374? Seems to be caused by deleting/editing a bunch of files without committing

Thank you for pointing this out. I have committed and retried and I've successfully gotten past the problem. However, a new issue has arrived:
![image](https://github.com/FunkinCrew/Funkin/assets/107242652/885224bf-15c5-4970-97e5-16467f05309a)
I've reinstalled hxCodex and it hasn't fixed the problem. Not sure what the root cause for this is either at this point.

I'll be closing this issue soon, as this is a different one. If you find a fix for this, please tell me. 👍

**Comment by Daikicalla** [comment]
It turns out I was using the wrong version of hxCodec. I am compiling now with no issues 👏
