### ISSUE TITLE
Bug Report: when starting the game up that says click here to play it shows an image with bunch of errors saying typer error cannot read properties of null and about couple paragraphs of zips etc

### ISSUE THREAD

**Issue by ThePickleViking** [FunkinCrew/Funkin#2547]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

**Comment by gamerbross** [comment]
post a video or image plz

**Comment by amyspark-ng** [comment]
Could you properly fill the form? The click here to play screen doesn't even show on desktop

**Comment by ThePickleViking** [comment]
Sorry I saw someone else had the same problem it's been resolved sorry

**Comment by amyspark-ng** [comment]
oh good, if it's been resolved close the issue plssss

**Comment by ThePickleViking** [comment]
No worries just not home atm I can do that
