### ISSUE TITLE
Bug Report: Unable to import CharacterData classes via HScript

### ISSUE THREAD

**Issue by Lethrial** [FunkinCrew/Funkin#2548]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.3

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Write a script importing any class or enum from `CharacterData` (e.g. `import funkin.play.character.CharacterData.CharacterDataParser;`)

## Please describe your issue. Provide extensive detail and images if possible.
When attempting to import a class from `CharacterData` using HScript, an error message pops up saying that the class doesn't exist.

![image](https://github.com/FunkinCrew/Funkin/assets/38376404/41cae345-d3ad-46f0-beaf-7d42303b6550)

Here's the script I've been working on for reference:
```hx
import funkin.play.PlayState;
import funkin.play.song.Song;
import funkin.play.character.BaseCharacter;
import funkin.play.stage.Stage;
import funkin.play.character.CharacterData.CharacterDataParser;

class BeachsideSong extends Song 
{
    // Characters
    var boyf:BaseCharacter;
    var girlf:BaseCharacter;

    public function new() {
        super('beachside');
    }

    override function onCreate() 
    {
        super.onCreate();

        // Loads Boyfriend, positions him and adds him to the current stage.
        boyf = CharacterDataParser.fetchCharacter('bf');
        boyf.characterType = CharacterType.DAD;
        boyf.zIndex = 150;
        boyf.flipX = false;
        boyf.x = PlayState.instance.currentStage.getBoyfriend().x - 150;
        boyf.y = PlayState.instance.currentStage.getBoyfriend().y - 50;
        PlayState.instance.currentStage.addCharacter(boyf);

        // Loads Girlfriend, positions her and adds her to the current stage.
        girlf = CharacterDataParser.fetchCharacter('chibi-gf');
        girlf.characterType = CharacterType.DAD;
        girlf.zIndex = 149;
        girlf.x = PlayState.instance.currentStage.getDad().x + 150;
        girlf.y = PlayState.instance.currentStage.getDad().y - 50;
        PlayState.instance.currentStage.addCharacter(girlf);
    }
}
```

If there's any workaround for loading a character without importing CharacterData then please let me know! I'd appreciate any and all help.

**Comment by gamerbross** [comment]
Importing works different in HScript, with "class path", not by module.
you need to import like
`import funkin.play.character.CharacterDataParser;`
not
`import funkin.play.character.CharacterData.CharacterDataParser;`

`CharacterData` is the module, but it has to be skipped when importing in hscript.
I hope Eric finds some kind of fix for that, would be awesome

**Comment by Lethrial** [comment]
Ah I see, thank you so much for the help!
