### ISSUE TITLE
Song Editor Tedious; Proposed Solution (Play audio when panning through note editor)

### ISSUE THREAD

**Issue by mesalikefortnite** [FunkinCrew/Funkin#255]
I am trying to make a note sheet of Tunak Tunak Tun, but I keep having to go back and replay the level in order to sync the notes to the song which is incredibly tedious.

It would be easiest if the song could be played in clips during the editor, perhaps when panning.

**Comment by mesalikefortnite** [comment]
The key for doing so is space. i went through the code and these are the keys if anyone is wondering:

SPACE is the key

**Comment by gedehari** [comment]
@ninjamuffin99  should probably add key hints for modders so they are not confused, how about that?

**Comment by mesalikefortnite** [comment]
ill try forking it and add a description when I have time.

**Comment by regulad** [comment]
@mesalikefortnite https://github.com/ninjamuffin99/Funkin/blob/master/Modding.md is being developed for this exact reason
