### ISSUE TITLE
monster-christmas' Left and Right Directions Swapped

### ISSUE THREAD

**Issue by SkylarDragon** [FunkinCrew/Funkin#257]
I have no idea whether or not this is intentional or not, but I wanted to submit it as an issue anyway. Basically, monster-christmas will face right when a left note is played and vice versa. (Note, I was playing around with the source code and some pull requests, but this happens in the release version too)

https://user-images.githubusercontent.com/10256423/105565317-3c659d00-5cf4-11eb-8e6b-9196e4f2165f.mp4

I made a workaround fix to it by swapping some code, but I didn't make it a pull request because I thought it was too simple of a fix lmao

![image](https://user-images.githubusercontent.com/10256423/105565063-f825cd00-5cf2-11eb-9d76-d4d53d075997.png)

**Comment by regulad** [comment]
I mean, I would make a pull request, I didn't even notice that lol

**Comment by NukerDragon** [comment]
> I mean, I would make a pull request, I didn't even notice that lol

fair enough, i just thought it wasn't worth it with it being mismatched but like who'd know abt it as long as it works lmao. i have other minor things i fixed too but idk what im doing lol

**Comment by EliteMasterEric** [comment]
Oh yeah I fixed this.
