### ISSUE TITLE
Bug Report: Story mode menu - Tutorial bop speed is less than other weeks

### ISSUE THREAD

**Issue by JackXson-Real** [FunkinCrew/Funkin#2571]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.3

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Go to story mode menu and look at tutorial, then scroll to other weeks.

## Please describe your issue. Provide extensive detail and images if possible.
In the story mode menu, the bop speed is less than all the other weeks. This causes boyfriend to bop slower when looking at other weeks as well. Here is a video:

https://github.com/FunkinCrew/Funkin/assets/32755192/12662b67-fce9-4484-9e4f-f20b07b670a8

**Comment by NATIONALNANAYT** [comment]
I think it's because the funkin crew wanted 
to have bf bob at the same time as gf
I wo
Wouldn't call it bug unless it's not what I mentioned above

**Comment by JackXson-Real** [comment]
> I think it's because the funkin crew wanted to have bf bob at the same time as gf
> 
> I wouldn't call it bug unless it's not what I mentioned above

Ye but I think she’s supposed to be bopping faster 😭
