### ISSUE TITLE
Compiling help: Everytime i compile an older version i get this error

### ISSUE THREAD

**Issue by Szymonek1974** [FunkinCrew/Funkin#2574]
/home/deck/haxelib/flixel-ui/2,4,0/flixel/addons/ui/FlxUICursor.hx:561: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
assets/images/menuDesat.png~:1: character 1 : Warning : Invalid name: menuDesat__png~ for file: assets/images/menuDesat.png~
assets/images/menuBG.png~:1: character 1 : Warning : Invalid name: menuBG__png~ for file: assets/images/menuBG.png~
source/PlayState.hx:46: characters 21-29 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/NGio.hx:61: characters 25-39 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:61: characters 25-39 : ... For optional function argument 'callback'
source/NGio.hx:64: characters 30-45 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:64: characters 30-45 : ... For optional function argument 'callback'
source/NGio.hx:50: characters 25-34 : () -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:50: characters 25-34 : ... For optional function argument 'callback'
source/PlayState.hx:389: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:391: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/ChartingState.hx:77: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/ChartingState.hx:292: characters 16-24 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
/home/deck/haxelib/flixel/5,8,0/flixel/ui/FlxButton.hx:191: characters 13-19 : Field status has different type than in flixel.addons.ui.interfaces.IFlxUIButton
/home/deck/haxelib/flixel-ui/2,4,0/flixel/addons/ui/interfaces/IFlxUIButton.hx:60: characters 2-38 : ... Interface field is defined here

**Comment by EliteMasterEric** [comment]
We're currently not providing official support for compilation issues on older versions.
