### ISSUE TITLE
Funny feature idea: full gituar hero controller support

### ISSUE THREAD

**Issue by ChickenSwimmer2020** [FunkinCrew/Funkin#2575]
Full gituar hero controller support. 5 keys, whammy bar, strum. And possibly even star power system. It would be hilarious to have in the base game without mods

**Comment by amyspark-ng** [comment]
Probably not 5 keys, whammy bar, strum, etc but i guess the game will have support for different controllers, such as a guitar hero controller

**Comment by EliteMasterEric** [comment]
We have basic controller support right now, does connecting a Guitar controller to your computer and configuring the binds work?

**Comment by amyspark-ng** [comment]
I don't actually have a controller, but a friend does, i could ask them to try

**Comment by ChickenSwimmer2020** [comment]
tested with my gituar hero controller, can confirm that the support does work, its only missing the downscroll, and the fact that you dont have to strum to register the input

**Comment by biomseed** [comment]
> tested with my gituar hero controller, can confirm that the support does work, its only missing the downscroll, and the fact that you dont have to strum to register the input

Doesn't the game already have downscroll?

**Comment by ninjamuffin99** [comment]
closing since it does have controller support and downscroll :)
