### ISSUE TITLE
Crash when exiting Chart Editor: Notification was already destroyed

### ISSUE THREAD

**Issue by amyspark-ng** [FunkinCrew/Funkin#2579]
### If you are playing the game in a browser, what site are you playing it from?

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [X] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

0.3.3

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

I haven't really identified specific steps but i think it's related to the notification that pops up when copying notes

## Please describe your issue. Provide extensive detail and images if possible.

Here's the logs
[crash-2024-05-20-22-16-00.log](https://github.com/FunkinCrew/Funkin/files/15384028/crash-2024-05-20-22-16-00.log)
I say is related to the notification since the "steps" i've done to reproduce it is copying the notes which will pop up the notifications and when i press Ctrl + Q it makes the game crash, the crash message says:
`There was a problem validating this component as it has already been destroyed (haxe.ui.notifications.Notification#null)`

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

**Comment by Hundrec** [comment]
Replicated in 0.5.0 by pasting notes and pressing Ctrl + Q immediately afterwards.

![image](https://github.com/user-attachments/assets/76308565-71b3-4a76-adda-9056377f941a)

**Comment by amyspark-ng** [comment]
how did you do it? i can't even select notes or do whatever in the chart editor

**Comment by Hundrec** [comment]
The chart editor doesn't take most mouse inputs, but Ctrl + A, Ctrl + C, and Ctrl + V did the trick!

**Comment by amyspark-ng** [comment]
oh makes sense! chart editor hopefully gets fixed in 0.5.1 for now it's kinda busted
