### ISSUE TITLE
Week 5 Crashes the game

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#258]
This game is really good but since Week 5 has been put in there has been a lot of issues. The game will be stuck on the loading screen, and if you're lucky enough to get past it, you can play! Most of the gameplay is normal, but Week 5 runs to about 10 FPS. This is also affect other weeks, especially the long notes. If the game crashes completely It will look somewhat like the picture provided.  (had to draw couldn't get the game to give me the crash screen)
![Screenshot 2021-01-22 at 9 57 16 PM](https://user-images.githubusercontent.com/77870069/105568184-0aa50400-5cfd-11eb-8b18-052db3892b0b.png)

**Comment by NukerDragon** [comment]
What site/build are you running the game on?

**Comment by GoldenEditor1** [comment]
> What site/build are you running the game on?

I tried NewGrounds and itch.io

**Comment by NukerDragon** [comment]
it might be your internet. try downloading it from itch.io. if you use linux/macOS, wine can run the windows download just fine since the linux download hasnt been updated yet.

**Comment by GoldenEditor1** [comment]
> it might be your internet. try downloading it from itch.io. if you use linux, wine can run the windows download just fine since the linux download hasnt been updated yet.

That worked! Thanks

**Comment by GoldenEditor1** [comment]
That worked! Thanks

**Comment by NukerDragon** [comment]
no problem! plus it performs _far_ better than the web version
