### ISSUE TITLE
[BUG] Freeplay Menu: Favorites aren't saved when leaving the menu

### ISSUE THREAD

**Issue by EliteMasterEric** [FunkinCrew/Funkin#2580]
Any favorites are forgotten as soon as the menu closes, making the feature basically useless.

This should be fixed in the next update.

**Comment by JackXson-Real** [comment]
Thanks Eric very cool 👍

**Comment by biomseed** [comment]
> Any favorites are forgotten as soon as the menu closes, making the feature basically useless.
> 
> This should be fixed in the next update.

Do the other "sorting" options do anything or are they for the next update too?

**Comment by amyspark-ng** [comment]
> > Any favorites are forgotten as soon as the menu closes, making the feature basically useless.
> > This should be fixed in the next update.
> 
> Do the other "sorting" options do anything or are they for the next update too?

What would other sorting options be?

**Comment by biomseed** [comment]
> What would other sorting options be?

![image](https://github.com/FunkinCrew/Funkin/assets/73907153/fc20468f-0cf4-4a49-8b1f-3ceecc1b580a)

**Comment by EliteMasterEric** [comment]
The other sorting options already work

**Comment by JackXson-Real** [comment]
> > What would other sorting options be?
> 
> ![image](https://private-user-images.githubusercontent.com/73907153/332935647-fc20468f-0cf4-4a49-8b1f-3ceecc1b580a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTIxOTksIm5iZiI6MTcxNjQxMTg5OSwicGF0aCI6Ii83MzkwNzE1My8zMzI5MzU2NDctZmMyMDQ2OGYtMGNmNC00YTQ5LThiMWYtM2NlZWNjMWI1ODBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDIxMDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMjgwZDhjNDQ2NGEwNzY3MTYwYjZmYmE5NzY5NmFjOGFhNzIwNjY5YzBiMzQwMGQxMTU5MTc4YTc1OTAyNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nQaWE0zAIpCHpcq6T9mzciAQ15Ibih5SAS-U_zni9Ds)

You can switch between those by pressing Q and E. I think there should be an indication for the keybinds for that since it took me a bit to figure it out.

**Comment by amyspark-ng** [comment]
> > > What would other sorting options be?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/73907153/332935647-fc20468f-0cf4-4a49-8b1f-3ceecc1b580a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTIxOTksIm5iZiI6MTcxNjQxMTg5OSwicGF0aCI6Ii83MzkwNzE1My8zMzI5MzU2NDctZmMyMDQ2OGYtMGNmNC00YTQ5LThiMWYtM2NlZWNjMWI1ODBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDIxMDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMjgwZDhjNDQ2NGEwNzY3MTYwYjZmYmE5NzY5NmFjOGFhNzIwNjY5YzBiMzQwMGQxMTU5MTc4YTc1OTAyNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nQaWE0zAIpCHpcq6T9mzciAQ15Ibih5SAS-U_zni9Ds)
> 
> You can switch between those by pressing Q and E. I think there should be an indication for the keybinds for that since it took me a bit to figure it out.
Oh yeah i agree, i did figure them out but they're not really intuitive

**Comment by EliteMasterEric** [comment]
Definitely resolved in v0.4.0.
