### ISSUE TITLE
Question: Open HaxeFlixel Debugger

### ISSUE THREAD

**Issue by gamerbross** [FunkinCrew/Funkin#2583]
I already have my debug build, but i have no idea how to open the HaxeFlixel's Debugger, it just doesnt work as always did

**Comment by EnterTheVoid-x86** [comment]
If you're 100% sure you compiled the game for debug and not release, the key will either be F2, `, or \.

**Comment by gamerbross** [comment]
oh thanks, idk why they overwrote the open debugger keys, now you just can with f2
