### ISSUE TITLE
Enhancement: chart

### ISSUE THREAD

**Issue by moha0100110** [FunkinCrew/Funkin#2586]
## What is your suggestion, and why should it be implemented?

the ability of loading psych engine chart or convert it to the new chart style

**Comment by biomseed** [comment]
> #### Please check for duplicates or similar issues before creating this issue.
> ## What is your suggestion, and why should it be implemented?
> the ability of loading psych engine chart or convert it to the new chart style

you can already do that with the legacy chart option, it just adds all the events as right notes

**Comment by EliteMasterEric** [comment]
You can already load charts from old versions of the game.

As for Psych charts, we will not be supporting content from mods or engines.

**Comment by moha0100110** [comment]
> You can already load charts from old versions of the game.
> 
> As for Psych charts, we will not be supporting content from mods or engines.

about psych there is already converter so we can

**Comment by moha0100110** [comment]
> You can already load charts from old versions of the game.
> 
> As for Psych charts, we will not be supporting content from mods or engines.

i used a converter it didnt work but when i used a normal fnf psych engine chart it worked

**Comment by SyncGit12** [comment]
export as legacy chart then import into v-slice, easy

maybe

**Comment by Marcosayfi** [comment]
just use psych to v-slice in psych engine 1.0
