### ISSUE TITLE
bugs with some weeks

### ISSUE THREAD

**Issue by bigboi12321** [FunkinCrew/Funkin#259]
week 1: sometimes during "bopeebo" the first note from the dad is played on loop indefinitely. restarting or exiting the song does not help

week 5: the mom and dad sprite sometimes becomes corrupted with only certain parts visible during certain frames of animation

-during the 2 mom and dad songs, sometimes the lines are shuffled and the game has you playing the lines in the incorrect order
(more songs had this issue, but these were the only ones i could remember vividly)

**Comment by NukerDragon** [comment]
Are you playing the browser version or the downloadable?

**Comment by bigboi12321** [comment]
> Are you playing the browser version or the downloadable?

The browser version

**Comment by NukerDragon** [comment]
try downloading it from itch.io. it's much better for performance. if you use linux, wine runs the windows build just fine since linux hasnt been updated yet
