### ISSUE TITLE
Enhancement: a scriptable NoteKind class

### ISSUE THREAD

**Issue by nebulazorua** [FunkinCrew/Funkin#2601]
## What is your suggestion, and why should it be implemented?
I think a scriptable NoteKind class would be useful to have for note kinds that you'll be using in lots of songs or that could be just generally useful (i.e some sort of "Alt Anim" note like a lot of engines have, and also mines.)

My suggestion for how it'd be implemented is effectively a class that attaches to Notes that has the callbacks you'd expect on a class like this. onHit, onMiss, onCreate, onDestroy, etc. I'd also expect some function like getTitle to add it to the chart editor state.

This'd allow us to just make stuff a little bit easier to create more generic note kinds that don't apply to specific songs or characters, but apply to many contexts and situations, without having to script each song and character seperately.
It'd also mean we wouldn't have to use a custom NoteStyle to give it functionality in multiple songs more easily, allowing us to leave NoteStyles as a way to customize the visual aspects of notes and nothing more (unless we're intended to use NoteStyles in this way, then disregard this whole thing).

**Comment by nebulazorua** [comment]
Prob gonna do a PR to try to tackle this issue, but I'm gonna leave the issue here just incase I don't finish it

**Comment by Johferson** [comment]
didn't parents-christmas.hxc already do alt anims?

**Comment by EliteMasterEric** [comment]
This would be really useful to have! There is currently a pull request for this in progress.

**Comment by AbnormalPoof** [comment]
this is now in v0.5.0
