### ISSUE TITLE
Compiling help: assets/preload is missing

### ISSUE THREAD

**Issue by noskincz** [FunkinCrew/Funkin#2608]
#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

This is my first time compiling fnf and i have run into an issue when trying to test run and build the game where it told me that it was missing said assets/preload

![image](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/2a250a34-ed88-416b-8054-948dfd0979fa/2e2a9c5d-6e7e-479f-90d0-51242c93d364?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi8yYTI1MGEzNC1lZDg4LTQxNmItODA1NC05NDhkZmQwOTc5ZmEvMmUyYTljNWQtNmU3ZS00NzlmLTkwZDAtNTEyNDJjOTNkMzY0IiwiaWF0IjoxNzE3NTY3ODY5LCJleHAiOjMzMjg4MTI3ODY5fQ.lyT35C5N-jQ0rCdvnENMVZIb94nKKOQMunaZoWNd1WA)

**Comment by NotHyper-474** [comment]
Seems like the assets and art submodules were not initialized (to put it simple, they weren't downloaded)

You can download them with `git submodule update --init --recurse`

**Comment by CreamslyCream** [comment]
> Seems like the assets and art submodules were not initialized (to put it simple, they weren't downloaded)
> 
> You can download them with `git submodule update --init --recursive`

it says, "fatal: not a git repository (or any of the parent directories): .git"

**Comment by NotHyper-474** [comment]
> > Seems like the assets and art submodules were not initialized (to put it simple, they weren't downloaded)
> > You can download them with `git submodule update --init --recursive`
> 
> it says, "fatal: not a git repository (or any of the parent directories): .git"

Did you download the repository as a zip instead of cloning it?

**Comment by CreamslyCream** [comment]
> > > Seems like the assets and art submodules were not initialized (to put it simple, they weren't downloaded)
> > > You can download them with `git submodule update --init --recursive`
> > 
> > 
> > it says, "fatal: not a git repository (or any of the parent directories): .git"
> 
> Did you download the repository as a zip instead of cloning it?
 I've cloned it and downloaded the zip

**Comment by NotHyper-474** [comment]
> > > > Seems like the assets and art submodules were not initialized (to put it simple, they weren't downloaded)
> > > > You can download them with `git submodule update --init --recursive`
> > > 
> > > 
> > > it says, "fatal: not a git repository (or any of the parent directories): .git"
> > 
> > Did you download the repository as a zip instead of cloning it?
>  I've cloned it and downloaded the zip
> 

You mean you did both `git clone https://github.com/FunkinCrew/Funkin.git` and click on this button?
![Screenshot_20240531-104953_Chrome.jpg](https://github.com/FunkinCrew/Funkin/assets/40342021/1cc7898d-34b6-4c29-962b-a4d682fb3b4b)

**Comment by CreamslyCream** [comment]
> > > > > Seems like the assets and art submodules were not initialized (to put it simple, they weren't downloaded)
> > > > > You can download them with `git submodule update --init --recursive`
> > > > 
> > > > 
> > > > it says, "fatal: not a git repository (or any of the parent directories): .git"
> > > 
> > > 
> > > Did you download the repository as a zip instead of cloning it?
> > > I've cloned it and downloaded the zip
> 
> You mean you did both `git clone https://github.com/FunkinCrew/Funkin.git` and click on this button? ![Screenshot_20240531-104953_Chrome.jpg](https://private-user-images.githubusercontent.com/40342021/335607321-1cc7898d-34b6-4c29-962b-a4d682fb3b4b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjYwNjgsIm5iZiI6MTcxNzE2NTc2OCwicGF0aCI6Ii80MDM0MjAyMS8zMzU2MDczMjEtMWNjNzg5OGQtMzRiNi00YzI5LTk2MmItYTRkNjgyZmIzYjRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE0MjkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NzExZWZmMmQ4ZTVkMTM4OTk2M2RmZmI0Nzk0OTZiODI5OWUyYmJlNGJjYjU2YzdmZGNmYjYyYjllNzVmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6iIbBBSSSs970XMXLA2wKDMwYyBtu1tazNhhCl7fwuE)

yup

**Comment by NotHyper-474** [comment]
> yup

Ok, do you know in which directory you had run the clone command? If so is there a folder named exactly "Funkin" in it?

**Comment by CreamslyCream** [comment]
> > yup
> 
> Ok, do you know in which directory you had run the clone command? If so is there a folder named exactly "Funkin" in it?

directory: \Downloads\Funkin-main\Funkin-main> so no

**Comment by CreamslyCream** [comment]
now the main folder name is funkin, and I recloned it, git submodule update --init --recursive still gives the same error and still no assets>preload

**Comment by NotHyper-474** [comment]
> now the main folder name is funkin, and I recloned it, git submodule update --init --recursive still gives the same error and still no assets>preload

Cloning is just a better way of downloading the repository, the problem with downloading the ZIP is that it doesn't have support for Git pull/submodule/etc commands. 

Try following the [Compiling Guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/COMPILING.md) but do it in another folder, not the one extracted from the zip cuz that's just not gonna work
