### ISSUE TITLE
Week 5 missing/misplaced notes

### ISSUE THREAD

**Issue by AltGaming** [FunkinCrew/Funkin#261]
Bf is missing notes in a few sections of Week 5 songs, one being Winter Horrorland
![bug](https://user-images.githubusercontent.com/16447578/105571182-06d4aa00-5d1c-11eb-8d77-41ae65efb0da.PNG)

**Comment by NukerDragon** [comment]
it might be intentional based on the difficulty. what difficulty is it?

**Comment by M1K3Altz** [comment]
> it might be intentional based on the difficulty. what difficulty is it?

In hardmode

**Comment by NukerDragon** [comment]
ah you're right, it'd prolly be best to let the dev handle it :p
