### ISSUE TITLE
Enhancement: when making a chart for difficulty it start with the one you already created

### ISSUE THREAD

**Issue by ytggobs** [FunkinCrew/Funkin#2611]
## What is your suggestion, and why should it be implemented?
when making a new difficulty it start with the chart that you already made (and i dont want to remake the whole chart for a difficulty)

**Comment by EliteMasterEric** [comment]
The easiest way to do this is to simply copy all the notes (`Ctrl-A` then `Ctrl-C` or `Edit->Select All` and `Edit->Copy`) and paste them (`Ctrl-V` or `Edit->Paste`) in the correct difficulty.
