### ISSUE TITLE
Bug Report:SongConverter.hx:49: characters 34-35 : Reification $ is not allowed outside of `macro` expression

### ISSUE THREAD

**Issue by LeonGamerPS1** [FunkinCrew/Funkin#2612]
### If you are playing the game in a browser, what site are you playing it from?

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [ ] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux
- [X] SongConverter.hx

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## Please describe your issue. Provide extensive detail and images if possible.

SongConverter.hx:49: characters 34-35 : Reification $ is not allowed outside of `macro` expression

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

**Comment by AbnormalPoof** [comment]
`SongConverter.hx` is an old script from 3 years ago, if you're trying to import old songs then please use the `FNF Legacy` option in the Chart Editor.

**Comment by LeonGamerPS1** [comment]
thanks!
