### ISSUE TITLE
Enhancement: Way to tell where your notes will end up when copy pasting.

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#2617]
## What is your suggestion, and why should it be implemented?
Currently when you copy and paste a selection of notes it can be pretty tough to tell where those notes are going to be placed as they just kind of vaguely go in the middle of the screen. If they spawned starting from wherever you have the red play head at the moment I think that would be more intuitive, and just make the flow of copy pasting more efficient.

**Comment by Hundrec** [comment]
When pasting a selection, the earliest note you copied will be placed at the closest snapped position to the red playhead. If your snap is set to something like 1/4, the placement can look a little random.

I like to click on the ruler on the side to move the playhead exactly where I want my selection before pasting. It’s a handy feature!

However, I do agree that copying and pasting could be a bit more intuitive, so I’d love to see what the Funkin’ Crew adds!

**Comment by EliteMasterEric** [comment]
What Hundrec said is correct. Pasting is done such that the first note is placed near your playhead, and respects note snapping, and all other notes are placed relative to that one (notes after the first one won't get snapped, so as not to mess up your clipboard!).
