### ISSUE TITLE
Polymod

### ISSUE THREAD

**Issue by GemFin** [FunkinCrew/Funkin#2619]
im using funkin 0.3.3 (compiled myself) and whenever i try to use the mods folder, the mod simply doesn't load in-game. I assue it's an issue with polymod but nothing so far has worked

**Comment by GemFin** [comment]
oh yeah, im using windows if that's useful

**Comment by tposejank** [comment]
If the mod does not have polymod icon or polymod meta files, then it will not load. If that isn't the case, then there is another issue
