### ISSUE TITLE
Game missing sprites and closing while loading levels

### ISSUE THREAD

**Issue by finntheguy** [FunkinCrew/Funkin#262]
As soon as week 5 came out, I deleted and redownloaded the game, only to find that only the monster level, the dad's levels, and pico and the mom's level would open without suddenly closing, but they would close around 80% of the time if I got unlucky, the mom's and pico's being the worst. Cocoa and Eggnog won't load at all. If one level DID manage to open and play, and I would try and play another, it would close on me. Sometimes when the levels do load in, either girlfriend, boyfriend, or the opponent will show up as black boxes that mimic the character's motions. It doesn't alter the gameplay in any way, it's just a but annoying. Cant enjoy the game without these issues!!! I've deleted and reinstalled the game a few times, but the issues persist, the constant closing being the biggest issue. I'm not sure if it's an issue with my computer or not, or if it's the game itself.

**Comment by regulad** [comment]
Is your `assets` folder corrupted or unable to be read?
