### ISSUE TITLE
Secret Lemon Demon fight closing mid song and Boyfriend sprite not appearing on Freeplay

### ISSUE THREAD

**Issue by Agent22Gengar** [FunkinCrew/Funkin#263]
Title should say it all tbh,i've tried doing the secret fight a lot of times and the song always abruptly closes in the middle
Also when i'm on freeplay the boyfriend's sprite doesn't appear at all unless he's either hitting or missing a note

**Comment by AkkiTheGamerFox** [comment]
Monster crashing is a known issue with this update, as for the BF sprites, try redownloading the game.

**Comment by Agent22Gengar** [comment]
i didn't download the game in the first place,i played it through newgrounds
