### ISSUE TITLE
Enhancement: Load song directly as a command line argument

### ISSUE THREAD

**Issue by Fancy2209** [FunkinCrew/Funkin#2630]
## What is your suggestion, and why should it be implemented?
It'd be neat if I could just tell the game a song/week and difficulty as cmd args and it'd just load directly, this would just allow for booting stuff quickly, mainly handy in the hypotehtical of having a bunch of mods and having shorcuts to them on steam that all just point to funkin and the week.

**Comment by tposejank** [comment]
you can kinda do this, but only when compiling. the only command line argument supported rn is the --chart command

**Comment by EliteMasterEric** [comment]
Having the option to do it when compiling is enough. If we allowed directly playing songs via argument it could lead to bugs like not having assets loaded or playing songs you don't have access to.
