### ISSUE TITLE
Bug Report: 2Hot does not show up on sorted Freeplay menu

### ISSUE THREAD

**Issue by GoombarioFan** [FunkinCrew/Funkin#2636]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.3

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
1. Go to Freeplay menu
2. Sort by #
3. 2Hot will not be present

## Please describe your issue. Provide extensive detail and images if possible.
![screenshot-2024-06-01-02-25-44](https://github.com/FunkinCrew/Funkin/assets/80182971/ea2244a9-3ad8-4ea4-91a0-046bbdaa7e4e)
Any song that begins with a number does not show up under the "#" option on the Freeplay menu. This includes 2Hot, as well as any songs that are modded into the game that begin with a number.

If songs that begin with numbers are supposed to use the first letter in their title to sort as instead, then 2Hot still doesn't show up under H either.

**Comment by Keoiki** [comment]
If it's meant to be a number filter, which would make the most sense, they screwed up the implementation. It actually filters for songs starting with a # instead of 0-9.

So if you were to add a modded song starting with a # then it'd show up there.

**Comment by tposejank** [comment]
What Keoiki said, just '#' sorting, for now it only seems to represent filtering songs that start by that symbol rather than the interpreted sorting of numbers

**Comment by ninjamuffin99** [comment]
doh good catch! will add this to our task listy

**Comment by ninjamuffin99** [comment]
this should be fixed in the upcoming 0.4.1 patch! thanks for the bug report!
