### ISSUE TITLE
Update the issue and pull request templates

### ISSUE THREAD

**Issue by tposejank** [FunkinCrew/Funkin#2640]
## What is your suggestion, and why should it be implemented?

These currently look horrible 😭 and the latest versions are not present on the bug template. Very unprofessional and not gamer move

There's also a whole 29 word paragraph in h1 size

As a suggestion for the bug template, instead of using checkboxes use a dropdown to select the platform

There are also so many words (those marked with weed) instructing unrelated stuff when doing a bug report

**Comment by ninjamuffin99** [comment]
Been meaning on doing this ! These templates we used r very very old and gunky… def on the todo :)

**Comment by ninjamuffin99** [comment]
cleaned up the bug report template and hopefully simplified it and made it cleaner to read! I did leave in some of the old info, but wrapped those in markdown comment instead of the weird invisible links? lol…
