### ISSUE TITLE
Question: Will base game get Lua support?

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#2643]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

### Will base game ever get Lua support as well as Hscript?
I know like Hscript already works fine, but if like the kickstarter said you want even the most casual of players to be able to dip their toes into the modding scene, then Lua would definitely be way more accessible. I've been modding in Psych engine for a bit and I know the second I opened up an Hscript file I had absolutely no clue what the fuck was happening, in a far worse way than when I started using Lua.

I was originally going to make this an enhancement request but for some reason I thought that might be kinda rude so I'm just curious.

**Comment by ninjamuffin99** [comment]
I will say, unlikely!

**Comment by Average-FNF-Modder** [comment]
Damn ok.
