### ISSUE TITLE
Bug Report: Game crashes after selecting an event in the chart editor that isn't your currently selected event type

### ISSUE THREAD

**Issue by AndrewIdot** [FunkinCrew/Funkin#2647]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.3

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

1. Open the chart editor
2. Place down an event (here I just used 2hot as an example and didn't bother doing so)
3. Change the event you're currently using to differ from the one placed down
4. Game assumes you're selecting the event with the same event type, fails to find the needed parameters for it, crash.

https://github.com/FunkinCrew/Funkin/assets/78974994/6a79ecfd-fd19-4bf6-9989-7fa5a89a3760

## Please describe your issue. Provide extensive detail and images if possible.

I feel as if this is a bit redundant...

**Comment by tposejank** [comment]
seems like this could be because the event window is not updated as the person clicks on a different event type than the one selected
