### ISSUE TITLE
Bug Report: Charting errors in several songs

### ISSUE THREAD

**Issue by afreetoplaynoob** [FunkinCrew/Funkin#2648]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.3

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Play or check the chart data/metadata of any of the songs mentioned.

## Please describe your issue. Provide extensive detail and images if possible.
Some songs have errors in their charts, some more noticable than others:
![Screenshot 2024-06-03 12 08 06](https://github.com/FunkinCrew/Funkin/assets/149265233/cff1b1c2-c195-4203-8ebb-3fef420c4ab2)
![Screenshot 2024-06-03 12 18 25](https://github.com/FunkinCrew/Funkin/assets/149265233/9545497e-2636-4530-84ab-3561b9d4f165)
![Screenshot 2024-06-03 15 06 51](https://github.com/FunkinCrew/Funkin/assets/149265233/b3c8f478-4a00-4813-8c95-abe7c947fbb5)
![Screenshot 2024-06-03 14 59 44](https://github.com/FunkinCrew/Funkin/assets/149265233/c8042331-f527-40f5-b77f-e74c2a57cd73)
M.I.L.F. (Easy) and Lit Up (Hard) both have notes stacked on each other, making them impossible to hit with one key press.
(Also it would be nice if the note in the fourth picture, present in all difficulties, was properly synced with the singing.)

![Screenshot 2024-06-03 12 09 03](https://github.com/FunkinCrew/Funkin/assets/149265233/59d772cf-ea87-4b95-8f6c-6977c2233427)
Monster has its BPM changes all messed up; the camera zooming and health icon bopping are completely off-beat.

![Screenshot 2024-06-03 12 09 26](https://github.com/FunkinCrew/Funkin/assets/149265233/8d659cad-0abf-4d0c-ab68-cfbd6454bbaa)
Winter Horrorland has the scroll speed for all of its difficulties set to 0.

**Comment by NotHyper-474** [comment]
Some of these were already reported in https://github.com/FunkinCrew/Funkin/issues/2525 and #2350 but this does add some more info.

**Comment by afreetoplaynoob** [comment]
Yep, was planning to add that detail in the issue, guess I forgot...
Regardless, there might be even more charting errors, beyond the ones others have mentioned already, that no one has noticed or brought up yet, and I'm pointing out the ones I've seen, even if I end up repeating some of the known ones.

**Comment by Hundrec** [comment]
As of 0.5.2, all of these issues (except the UI bop desync in Monster) are resolved!
We might want to create an updated issue focusing only on Monster's BPM changes for the sake of clarity
