### ISSUE TITLE
Bug Report: Player's left arrows are always selected along with Opponent's left arrows

### ISSUE THREAD

**Issue by Hundrec** [FunkinCrew/Funkin#2657]
## Operating System

- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the game are you using?
0.3.3 (still present in 0.4.1 - itch.io Version 16)

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

1. Start any song
2. Open the chart editor
3. Scroll to any point where the player has a left arrow
4. Drag and select where the left arrow would be on the opponent's side
5. The player's left arrow will be selected

## Please describe your issue. Provide extensive detail and images if possible.

Dragging to select left arrows on the **opponent's** side will also select left arrows on the **player's** side.
However, selecting the **player's** left arrows does not select the **opponent's** left arrows.

Selecting an area within the opponent's side excluding the left arrow will not select the player's left arrow.

The opponent does not have to have arrows for this bug to occur.

Through testing, it seems that only the player's left arrows are affected by this bug. All other arrows are selected normally.

https://github.com/FunkinCrew/Funkin/assets/170126004/64d5ae1a-8363-43f3-895f-904e1bb925b7

**Comment by NotHyper-474** [comment]
After some testing I discovered it only happens if you select the leftmost part of the chart

https://github.com/user-attachments/assets/0a436698-d6db-415f-b3a3-97063502f61f

**Comment by Hundrec** [comment]
I've also noticed that highlighting any region left of the measure marker selects left arrows too.
