### ISSUE TITLE
Possible 1080P (or higher) native resolution in the future?

### ISSUE THREAD

**Issue by cryptofyre** [FunkinCrew/Funkin#267]
Playing the game on a 1080P display in full screen appears really pixelated due to the scaling down to 720P perhaps this could be changed in a later update to the desktop builds for a better playing experience? 

I took a look at some of the assets and with a little upscaling some of the [menu backgrounds](https://imgur.com/a/1fv3N1t) look fine on 1080P but the [scenes and positions](https://imgur.com/a/u7m5RtW) of the sprites appear out of place likely due to how its set its in the XML. _perhaps a settings menu could change these for those who want a bigger playfield?_

This isn't a huge deal overall but it would help the overall quality of life of the game and the usability of the on screen counters especially on a 4K display with a capable graphics card.

Anyways keep up the great work!

**Comment by ActualMandM** [comment]
Full-screening the game (pressing `F` at the title screen or `Alt+Enter` anytime) makes the game render at the resolution you  are currently running at.

**Comment by iiFir3z** [comment]
> Full-screening the game (pressing `F` at the title screen or `Alt+Enter` anytime) makes the game render at the resolution you  are currently running at.

This just stretches the window to span across your display. This does not actually modify the game canvas size or the sprite size making everything appear pixelated.

**Comment by ActualMandM** [comment]
I am pretty sure it renders at the desktop resolution when full-screened. This is with a modified camera zoom.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/15317421/105669750-b3399c00-5e94-11eb-899b-0adba0911c03.png">
<img width="960" alt="2021-01-24_22-36-07_Discord" src="https://user-images.githubusercontent.com/15317421/105669740-b03eab80-5e94-11eb-941b-d4052ca78a04.png">

**Comment by regulad** [comment]
When full screened using `ALT-ENTER` or `F` it does not change the internal render resolution. As for when the size of the window is changed, IDFK maybe.

**Comment by iiFir3z** [comment]
Yes that does appear to be the case. Nothing is actually "changed" asset wise making everything appear blurry as it would if you clicked ALT+ENTER on any other game with a 720P internal resolution.
