### ISSUE TITLE
Bug Report: wrong vol. pack for 3 songs

### ISSUE THREAD

**Issue by BStasik** [FunkinCrew/Funkin#2672]
### If you are playing the game in a browser, what site are you playing it from?

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [X] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

0.4.0(0.4.1 too)

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

No special steps/actions needed.

## Please describe your issue. Provide extensive detail and images if possible.

For some reason, songs: Roses Erect, Satin Panties Erect and Eggnog Erect are in vol 1 album in game.

Roses Erect should be in vol.3
Other two - in the completly new one.("vol.1 exp." for example)

**Comment by crazyj3re** [comment]
when starting week end 8 and immediately dying pico will be in his idle animation and no music ONLY HAPPENS WHEN STARTING WEEK 8.
![Screenshot 2024-06-07 150836](https://github.com/FunkinCrew/Funkin/assets/172078225/6c0667e3-d2d7-4bb4-a511-82bfbe12a02b)

**Comment by BStasik** [comment]
> when starting week end 8 and immediately dying pico will be in his idle animation and no music ONLY HAPPENS WHEN STARTING WEEK 8. ![Screenshot 2024-06-07 150836](https://private-user-images.githubusercontent.com/172078225/337780079-6c0667e3-d2d7-4bb4-a511-82bfbe12a02b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3OTEyNzYsIm5iZiI6MTcxNzc5MDk3NiwicGF0aCI6Ii8xNzIwNzgyMjUvMzM3NzgwMDc5LTZjMDY2N2UzLWQyZDctNGJiNC1hNTExLTgyYmZiZTEyYTAyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QyMDA5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzMzZWE0MzA4ODI2NTNhZWEwYTdjMTAxYmE5YTViNmFjOTA4NmE2MjhiOTMyMzFiOTk2MDUwYThhMWQ4ZGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n9uQQsWeMZ_RcTQRfioCSjNYQlrPFY9h0w4VLFwIr1Y)

what😭

**Comment by crazyj3re** [comment]
?

**Comment by BStasik** [comment]
> when starting week end 8 and immediately dying pico will be in his idle animation and no music ONLY HAPPENS WHEN STARTING WEEK 8. ![Screenshot 2024-06-07 150836](https://private-user-images.githubusercontent.com/172078225/337780079-6c0667e3-d2d7-4bb4-a511-82bfbe12a02b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NjQ1OTcsIm5iZiI6MTcxNzk2NDI5NywicGF0aCI6Ii8xNzIwNzgyMjUvMzM3NzgwMDc5LTZjMDY2N2UzLWQyZDctNGJiNC1hNTExLTgyYmZiZTEyYTAyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMDE4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWNiMDgwNjcxMjU5MGE1ZDhhZTdiOWEwNTNmYTVlMDE3ZjdkM2FjMTY2MjkxNjY4Y2YyNTIwODNlOTAxYzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a4VJP_dg8dX3LjkBpZcX_ihg2m6mJCFhFuJPS5daFJI)

delete this pls

**Comment by crazyj3re** [comment]
how DO I DELETE ITT

**Comment by moxie-coder** [comment]
just close the issue then
