### ISSUE TITLE
Bug Report: [DESCRIBE YOUR BUG IN DETAIL HERE]

### ISSUE THREAD

**Issue by FazR11** [FunkinCrew/Funkin#2673]
### If you are playing the game in a browser, what site are you playing it from?

- [X] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [X] Windows
- 
  - [X] Mac
- 
  - [X] Linux

### If you are playing the game in a browser, what browser are you using?

- [X] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [X] Firefox
- [X] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

V0.4.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Tested on V0.4.0 [itch.io](http://itch.io) build newgrounds and [itch.io](http://itch.io) web

## Please describe your issue. Provide extensive detail and images if possible.

Favouriting a easy/normal/hard song in freeplay favourites the erect/nightmare version of the song and vice versa
This should be considered to be fixed as i may not like the normal version of the song but love the erect version e.g Bopeebo
no hard feelings x

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

**Comment by JackXson-Real** [comment]
Bro did not [DESCRIBE YOUR BUG IN DETAIL HERE]

**Comment by tposejank** [comment]
Very unlikely to be added. Just would add more complexity to the code
