### ISSUE TITLE
Bug Report: A-bot sprite moves for some reason.

### ISSUE THREAD

**Issue by BStasik** [FunkinCrew/Funkin#2674]
### If you are playing the game in a browser, what site are you playing it from?

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [X] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

0.4.0(still in 0.4.1)

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

No special steps/actions needed.

## Please describe your issue. Provide extensive detail and images if possible.

When you loosing in weekend 1 Nene is going to throw a knife at you.
But if you heal enough she will put away her knife and after this animation A-Bot moves to the left for a moment and comes back. Its easy to notice.
This bug has existed since version 0.3.0.

**Comment by Hundrec** [comment]
A-Bot's sprite actually doubles during the transition!

https://github.com/FunkinCrew/Funkin/assets/170126004/eef3705d-6e8a-449f-adac-be5913fe9fc4

**Comment by BStasik** [comment]
> A-Bot's sprite actually doubles during the transition!
> 
>  A-Bot.Sprite.bug.mp4

you are such a nice person

**Comment by biomseed** [comment]
> A-Bot's sprite actually doubles during the transition!
> 
>  A-Bot.Sprite.bug.mp4

Usually when there's 2 of a character, that's a mod's fault. I know cuz of that broken change character event that people always use.

**Comment by Hundrec** [comment]
> > A-Bot's sprite actually doubles during the transition!
> > A-Bot.Sprite.bug.mp4
> 
> Usually when there's 2 of a character, that's a mod's fault. I know cuz of that broken change character event that people always use.

I used an unmodified version of 0.4.0 for this recording, so mods aren't at play here

I suspect this is just an error with Nene's **lowerKnife** animation in the .json or .xml file

**Comment by TabTray** [comment]
this bug happens because nene's spritesheet still has 3 leftover frames that include abot, being used for the last 3 frames of nene's knife lowering animation. however, abot and nene are supposed to use separate sprites. this visual glitch wouldnt normally be noticable, however nene has since been moved slightly to the left/abot has been moved slightly to the right since the creation of the sprites, causing the visual.

the solution would be to just remove the last 3 frames from the `KnifeLower` animation, fixing the visual glitch.

**Comment by Hundrec** [comment]
This bug has been fixed as of 0.5.0, though Nene still slightly freezes when resyncing with A-Bot.

https://github.com/user-attachments/assets/a0ae1d4c-875a-4b1a-b24d-6546acd93e2a
