### ISSUE TITLE
Bug Report: Roses Erect Doesn't Do The Correct Zoom Events

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#2677]
### If you are playing the game in a browser, what site are you playing it from?

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

(It doesn't work on both Newgrounds AND the download)

### If you are playing the game in a browser, what browser are you using?

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
Version 0.4.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
It's very simple, just play the song Roses Erect and you'll see it.

## Please describe your issue. Provide extensive detail and images if possible.
When booting up the song Roses Erect on the new pitstop update it seems that for some reason the zoom events have been removed. They make the song look cool and I'm sure this is just a simple mistake in charting, but they should be added back! Images wouldn't really help here but I'm sure you get the idea lol.

**Comment by GoombarioFan** [comment]
Seems to be fixed in 0.4.1.

**Comment by Average-FNF-Modder** [comment]
Cool.

> Seems to be fixed in 0.4.1.
