### ISSUE TITLE
Bug Report: Freeplay song title displays Erect variation title

### ISSUE THREAD

**Issue by Hundrec** [FunkinCrew/Funkin#2678]
## Operating System

- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the game are you using?

0.4.0 ([itch.io](http://itch.io) Version 14)

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

1. Start a song with an Erect counterpart on Easy/Normal/Hard difficulty through the Freeplay menu 
2. Exit to the Freeplay menu
3. The title of the song may be its Erect version instead

## Please describe your issue. Provide extensive detail and images if possible.

Sometimes, the title of a song in the Freeplay menu will display its Erect counterpart instead.
Exiting and re-entering the Freeplay menu OR cycling through variations (Hard <> Erect) does **not** revert the song title.

The incorrect title only applies to the difficulty you started and exited previously.

https://github.com/FunkinCrew/Funkin/assets/170126004/707033cb-408c-45f4-9cb3-b887bb9d7391

**Comment by JordanSantiagoYT** [comment]
i was confused why in HARD mode it calls Dadbattle "DadBattle Erect"

**Comment by Hundrec** [comment]
> i was confused why in HARD mode it calls Dadbattle "DadBattle Erect"

I started Dadbattle on Hard after cycling through the variations in the Freeplay menu
Then, I exited and Hard displays Erect (weird!)
