### ISSUE TITLE
Enhancement: Add Lua compatibility

### ISSUE THREAD

**Issue by AcedGit** [FunkinCrew/Funkin#2679]
## What is your suggestion, and why should it be implemented?

Add the ability for people to script things in Lua. It would be just like in psych engine, but brought into base game. Plus, Lua is easier to understand than hxc and Lua scripting in FNF mods has been a thing for almost 3 years.
Here are functions that are already in FNF Lua and hopefully you guys could add this feature in the game https://raw.githubusercontent.com/ShadowMario/FNF-PsychEngine/main/docs/TemplateScript.lua

**Comment by NotHyper-474** [comment]
Considering https://github.com/FunkinCrew/Funkin/issues/2643#issuecomment-2143718093 seems like they don't plan on adding it.

**Comment by AcedGit** [comment]
> Considering [#2643 (comment)](https://github.com/FunkinCrew/Funkin/issues/2643#issuecomment-2143718093) seems like they don't plan on adding it.

damn

**Comment by tposejank** [comment]
You can do this in your fork, I don't think Lua should be added. The current Module system is very sophisticated
