### ISSUE TITLE
Bug Report: [pico death bug]

### ISSUE THREAD

**Issue by crazyj3re** [FunkinCrew/Funkin#2680]
[weed]: <> (when STARTING weekend 8 and trying to die immediately pico will sit in his idle animation and no music )

![Screenshot 2024-06-07 150836](https://github.com/FunkinCrew/Funkin/assets/172078225/df23ff07-7b59-4183-92bb-fc721e6b2dd9)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

v0.4.0

start weekend 8 and die immediately 
don't restart the song if you do the bug will not occur!

**Comment by Hundrec** [comment]
The forced animation on death bug has been reported in #2319 
This does add Pico’s frowning animation to the list, though
