### ISSUE TITLE
Bug Report: Song name Incorrectly displays as "Erect" when on hard

### ISSUE THREAD

**Issue by EaTStu** [FunkinCrew/Funkin#2685]
### If you are playing the game in a browser, what site are you playing it from?

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [X] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

0.4.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

After going through weeks 1-3 on hard in story mode, I beat weekend 1 and went back to free play. It was then, that I discovered this. I did not even play the erect version of Dadbattle yet.

## Please describe your issue. Provide extensive detail and images if possible.

![image](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/4f5b90ac-76ec-4d5d-a946-5293e37d7e30/a4b7ec3e-d40d-40f7-875d-1aa8fbcbd049?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi80ZjViOTBhYy03NmVjLTRkNWQtYTk0Ni01MjkzZTM3ZDdlMzAvYTRiN2VjM2UtZDQwZC00MGY3LTg3NWQtMWFhOGZiY2JkMDQ5IiwiaWF0IjoxNzE3ODEyODYzLCJleHAiOjMzMjg4MzcyODYzfQ.9kbbqoA7rWL9yKCu1nrn1Kgg_mh0ImPSiZoPfNKcbm0)

It only happens when I put it on hard. It plays the original music, and displays the rank of the original song. It stays when changing difficulties, and the difficulty is set to nothing.

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

**Comment by EaTStu** [comment]
I still have the game running, and I'll keep it running for a few more hours without doing anything.

**Comment by ninjamuffin99** [comment]
this will be fixed in the upcoming 0.4.1 update 🙂
