### ISSUE TITLE
Bug Report: Incorrect Rank being displayed after P Rank

### ISSUE THREAD

**Issue by bakedroyal** [FunkinCrew/Funkin#2686]
### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.4.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

https://github.com/FunkinCrew/Funkin/assets/160797203/e443cfc3-4108-41df-831e-5c2b9caa0070

## Please describe your issue. Provide extensive detail and images if possible.

When I cleared Eggnog Erect and got a P Rank, the game played all intended animations, but displayed as 99% when going back to the Freeplay menu. When flipping back through, the P Rank also changed to an E Rank.

**Comment by Average-FNF-Modder** [comment]
THIS, MAN I WANT MY P-RANK BACK &nbsp;&nbsp;X[

**Comment by Hundrec** [comment]
Also reported in #2664, but this video is useful

**Comment by M7theguy** [comment]
I think the reason why it does that is because it only saves the score (with its rank) with the highest points. For example, this video shows a score of 206307 in the result screen but a score of 209541 in the menu.  (In my opinion, this should be changes to save both the highest score and the highest rank that was achieved in a song)

**Comment by bakedroyal** [comment]
> I think the reason why it does that is because it only saves the score (with its rank) with the highest points. For example, this video shows a score of 206307 in the result screen but a score of 209541 in the menu. (In my opinion, this should be changes to save both the highest score and the highest rank that was achieved in a song)

99% sure this is whats happening
I got a high score on darnell with 97% (my previously saved high score had a 99%) and now that 97% is whats saved even though it was higher before

**Comment by Average-FNF-Modder** [comment]
> > I think the reason why it does that is because it only saves the score (with its rank) with the highest points. For example, this video shows a score of 206307 in the result screen but a score of 209541 in the menu. (In my opinion, this should be changes to save both the highest score and the highest rank that was achieved in a song)
> 
> 99% sure this is whats happening I got a high score on darnell with 97% (my previously saved high score had a 99%) and now that 97% is whats saved even though the percent was higher before

Yeah they should just have the 2 saved as separate things.

**Comment by ninjamuffin99** [comment]
this might be fixed in 0.4.1 that came out earlier this week, can OP confirm if this occurs still?

**Comment by M7theguy** [comment]
> this might be fixed in 0.4.1 that came out earlier this week, can OP confirm if this occurs still?

Tested on Newgrounds v0.4.1:
1. Eggnog NIGHTMARE: 213094 + 1 Miss = E Rank
2. Eggnog NIGHTMARE: 198091 + no Miss/Bad = P Rank

And after changing difficulties, menus and reloading fnf it kept the P Rank but also the Highscore of 213094, so it should be fixed!!

**Comment by ninjamuffin99** [comment]
nice thank you for testing :)
