### ISSUE TITLE
Bug Report: Modded songs do not have song previews in Freeplay

### ISSUE THREAD

**Issue by echolotl** [FunkinCrew/Funkin#2687]
### What platform are you using?
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

## What version of the game are you using? 
0.4.0, 0.4.1

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Have any modded song with filled out "previewStart" and "previewEnd" variables in the -metadata.json file of the song, hover over said song in Freeplay.
## Please describe your issue. Provide extensive detail and images if possible.
Editing these variables either through the Chart Editor or manually editing the song's metadata JSON file does not play the song's Inst, like other base game songs. Does not matter which variation of the song. Consistent with all mods, no matter what song.

**Comment by EliteMasterEric** [comment]
Believe this is fixed by #2724.
