### ISSUE TITLE
Enhancement: Please add a frame limit option

### ISSUE THREAD

**Issue by hihun8072** [FunkinCrew/Funkin#2692]
## What is your suggestion, and why should it be implemented?
When playing on a laptop, frames at 165 cause more noise and battery drain than necessary.

I think it should be implemented for better play experience and power consumption efficiency.

**Comment by Hundrec** [comment]
This is a great setting to have!
For me, changing line 29 of source\Main.hx and compiling the game myself resolves the high power consumption issue on my laptop.

**Comment by hihun8072** [comment]
> This is a great setting to have! For me, changing line 29 of source\Main.hx and compiling the game myself resolves the high power consumption issue on my laptop.
> 
> ![image](https://private-user-images.githubusercontent.com/170126004/337860106-9a0c6538-ba77-4af5-93e9-5dd07bd68370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDAxMDksIm5iZiI6MTcxNzgzOTgwOSwicGF0aCI6Ii8xNzAxMjYwMDQvMzM3ODYwMTA2LTlhMGM2NTM4LWJhNzctNGFmNS05M2U5LTVkZDA3YmQ2ODM3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwOTQzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDFlYjVmZTQwMWMwNTM4OTI2ZjU4NDk1YmUzODhhNTU4MjEzMDY1YmY4YjFkYjk3NzRkZmU5YmVjMDBmODM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7enBLUxvAKNyyP_My7szh1Of3Larmp3hAkF9rdacjZI)

I modified and compiled it myself, and it works fine.
Thanks a lot!

**Comment by Benefonde** [comment]
it looks like they're planning to do this so that's cool

**Comment by ninjamuffin99** [comment]
good suggestion! This will be in our task queue now :)

**Comment by EliteMasterEric** [comment]
This is in v0.5.1 by the way

**Comment by EliteMasterEric** [comment]
Resolved
