### ISSUE TITLE
Bug Report: Opening freeplay with songs that do not have a "normal" difficulty in the metadata crash the game

### ISSUE THREAD

**Issue by MadBear422** [FunkinCrew/Funkin#2693]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
As of now I am using version 0.4.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Either create a modded week with a custom song with a chart and metadata or modify an existing song's metadata. Have only the hard difficulty present in the medata, do not include the normal difficulty. Start the game and select freeplay, there the game will crash with no additional logs or traces back to what could be the culprit. I could probably check the source code for a potential suspect.

## Please describe your issue. Provide extensive detail and images if possible.
Having a song that does not have the normal difficulty will close the game when trying to open the freeplay menu.

**Comment by Loganthegamer12678** [comment]
What the hell's the point with making a hard mode mod exclusive mod when this shit keeps happening?! This is rediculous!

**Comment by MadBear422** [comment]
#2712 Is a fix for this.

**Comment by EliteMasterEric** [comment]
Fix got merged.
