### ISSUE TITLE
Enhancement: Ghost tapping

### ISSUE THREAD

**Issue by snewwslay** [FunkinCrew/Funkin#2696]
I just wanna ask, in FNF newer version, there's no ghost tapping. It make me very uncomfortable

**Comment by hihun8072** [comment]
I think the absence of ghost tapping is part of FNF's personality and identity.

**Comment by Average-FNF-Modder** [comment]
It's not getting added. It was only needed initially because the input system was ass. Now it would just make the game to easy.

**Comment by Ronin546** [comment]
it will be added maybe in 0.7.5

**Comment by charlesisfeline** [comment]
> it will be added maybe in 0.7.5

...no...

**Comment by moxie-coder** [comment]
> it will be added maybe in 0.7.5

it's not being added dumbass

**Comment by Average-FNF-Modder** [comment]
> > it will be added maybe in 0.7.5
> 
> it's not being added dumbass

chill out bro it's not that serious

**Comment by moxie-coder** [comment]
> > > it will be added maybe in 0.7.5
> > 
> > 
> > it's not being added dumbass
> 
> chill out bro it's not that serious

try telling them that, they don’t ever stop being annoying

**Comment by Ronin546** [comment]
Ghost tapping is in the mobile version.

**Comment by NotHyper-474** [comment]
Bro, at least comment in the [original issue](https://github.com/FunkinCrew/Funkin/issues/2651) and not a duplicate.
