### ISSUE TITLE
Vocal desync with Instrument

### ISSUE THREAD

**Issue by sqirradotdev** [FunkinCrew/Funkin#27]
Tried running the game in a slow hard drive, pressing a note will cause a lag spike and then the vocal desyncs with the instrument.
I'm too stupid to understand HaxeFlixel to fix this problem, however I have suggestions:

- Maybe preload all the assets before starting the game, or
- Find a way to detect when a lag spike happens and perform a syncing of vocal and instrument

ty!

**Comment by gedehari** [comment]
Some more things:  I ran the game with SSD this time, everything is fine except Fresh, for some reason, it has a slight vocal desync with the instrument. I will edit this to add a video example.

**Comment by gedehari** [comment]
It has been fixed in 60f53dccca5b7ec5b256a506ac5ad8c8051bc20a , closing now
