### ISSUE TITLE
Bug Report: Darnell's icon going out of the bar

### ISSUE THREAD

**Issue by MrSteveOff** [FunkinCrew/Funkin#2702]
### If you are playing the game in a browser, what site are you playing it from?

- [X] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)?
- 
  - [X] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chromium based like Brave, Vivaldi, MS Edge)
- [X] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

0.4.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

you need to get NO misses on any Darnell song, then the bug appears

## Please describe your issue. Provide extensive detail and images if possible.

When i get no misses on the Darnells songs, the darnell is flying out off the bar.

![Скриншот 08-06-2024 154826](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/0c8d95db-2d64-4157-a3ef-d15a6e8b7c95/1be6d4d9-3c53-407f-b082-afa48893f4aa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi8wYzhkOTVkYi0yZDY0LTQxNTctYTNlZi1kMTVhNmU4YjdjOTUvMWJlNmQ0ZDktM2M1My00MDdmLWIwODItYWZhNDg4OTNmNGFhIiwiaWF0IjoxNzE4MDU1NTgzLCJleHAiOjMzMjg4NjE1NTgzfQ.znIoOsqSCJjpqR1cxXxpT7PuCfL3EKiWzNDYiQCb2HQ)

**Comment by MrSteveOff** [comment]
this also happens on everyone

**Comment by CrusherNotDrip** [comment]
I'm pretty sure that's normal

**Comment by Hundrec** [comment]
Just checked, and Darnell's icon does significantly offset between his normal and losing icons. I've moved the losing icon to be aligned with the normal one.

**Offset**

![icon-darnell](https://github.com/FunkinCrew/Funkin/assets/170126004/fede5f95-bacd-4c97-8803-04b0cbd427af)

**Aligned**

![icon-darnell](https://github.com/FunkinCrew/Funkin/assets/170126004/b6f974be-a843-4cf1-a61d-d4c892854293)

**Comment by MrSteveOff** [comment]
> Just checked, and Darnell's icon does significantly offset between his normal and losing icons. I've moved the losing icon to be aligned with the normal one. (and started a pull request)
> 
> **Offset**
> 
> ![icon-darnell](https://private-user-images.githubusercontent.com/170126004/337905002-fede5f95-bacd-4c97-8803-04b0cbd427af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MjIwOTgsIm5iZiI6MTcxNzkyMTc5OCwicGF0aCI6Ii8xNzAxMjYwMDQvMzM3OTA1MDAyLWZlZGU1Zjk1LWJhY2QtNGM5Ny04ODAzLTA0YjBjYmQ0MjdhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwODI5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODY4ZmQ5YjlhMTBmYWRlZjM0NzY5NDVmYTJiMTdlOTcxYmM2NjkwMjg0YzkyZTllODgyY2Q3ODhjYTlhZjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.izBCI5JkLR85CT1Q6-vh3eY9IfrAwnL2xqfYjQ4MeC4)
> 
> **Aligned**
> 
> ![icon-darnell](https://private-user-images.githubusercontent.com/170126004/337905243-b6f974be-a843-4cf1-a61d-d4c892854293.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MjIwOTgsIm5iZiI6MTcxNzkyMTc5OCwicGF0aCI6Ii8xNzAxMjYwMDQvMzM3OTA1MjQzLWI2Zjk3NGJlLWE4NDMtNGNmMS1hNjFkLWQ0Yzg5Mjg1NDI5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwODI5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzZlMzVhZjQyMzkzZTgwZmNjYThjYjlmNDE1ZDA2NzZjNGYyYjllMmRlOWRhZTZhNjAzNGNkNDA3MTk3NzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IbWbu3yG5Qw95SNVVty9Wu3b6CSAYxeXlvr5ffmWP6w)

thx

**Comment by Hundrec** [comment]
funkin.assets PR merged!

**Comment by MrSteveOff** [comment]
no way after 7 months of inactivity the issue is fixed

**Comment by MrSteveOff** [comment]
im gonna close it cuz this is fixed
