### ISSUE TITLE
it dosnt let me open play on chrome

### ISSUE THREAD

**Issue by coolgamer1650** [FunkinCrew/Funkin#271]
it dosnt let me open play on chrome

**Comment by regulad** [comment]
Where are you playing? Could you provide a little bit more information?

**Comment by JaidenTfs** [comment]
> Where are you playing (ie. Newgrounds or Itch.io)? Could you provide a little bit more information?

For me it also doesn't work, I have tried itch and newgrounds. The game will load till maybe 70% and just stop loading, I suggested making a different itch game that haas less details, but yes the website never loads all the way.

I am not sure why it is not loading- I have even tried letting the website stay for an hour, and the number didn't change
