### ISSUE TITLE
Enhancement: 

### ISSUE THREAD

**Issue by crazyj3re** [FunkinCrew/Funkin#2711]
# What is your suggestion, and why should it be implemented?

I would like a counter for restarting the song because i always restart the songs when im trying to 100% all the songs! 😱 and a counter would be amazing 😱 the counter should be in the top right when pausing in the middle of the song 😱

**Comment by tposejank** [comment]
isnt that what the countdown is for

**Comment by Hundrec** [comment]
> isnt that what the countdown is for

I think the poster wants an additional “# Restarts” counter like the “# Blue Balls” counter in the Pause menu
