### ISSUE TITLE
Pico results screen

### ISSUE THREAD

**Issue by ObjectShowAnimations** [FunkinCrew/Funkin#2719]
#### Add Pico in the results screen after completed Weekend 1

**Comment by Hundrec** [comment]
I’m sure they’re working on this!

**Comment by ninjamuffin99** [comment]
closing as it's suggestion, and I think we are aiming for the github issues to be more bug reports than suggestions!

**Comment by ninjamuffin99** [comment]
actually i immediately change my mind, I'll re open dis

**Comment by AbnormalPoof** [comment]
your wish was granted
