### ISSUE TITLE
Enhancement: Add a 3-second countdown when resuming after pausing the game

### ISSUE THREAD

**Issue by hihun8072** [FunkinCrew/Funkin#2721]
## What is your suggestion, and why should it be implemented?

Sometimes, due to unavoidable circumstances, it is necessary to pause during play.

However, it's easy to lose your grip on the game right after resuming, so we think a 3-second countdown is necessary

**Comment by Hundrec** [comment]
I’ve thought of this too!
Maybe they should add a “resume with countdown” option to still allow rapid pausing

**Comment by ninjamuffin99** [comment]
not planned for anytime near future! will keep it in brain tho, maybe preference :)
