### ISSUE TITLE
Bug Report: Difficulty text gets cut off too soon

### ISSUE THREAD

**Issue by M7theguy** [FunkinCrew/Funkin#2728]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
v0.4.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
just finish any song
## Please describe your issue. Provide extensive detail and images if possible.
The difficulty text in every result screen gets cut off too soon. (I only checked the HARD and NIGHTMARE difficulties but im 90% sure this happens to every difficulty)

https://github.com/FunkinCrew/Funkin/assets/170743168/bf812384-2073-435a-a3b1-c13d4ab9f1f5

**Comment by M7theguy** [comment]
This might be a duplicate but I´m to lazy to check

**Comment by Hundrec** [comment]
This is a duplicate of #2283, please don't read that thread for your own sake

**Comment by M7theguy** [comment]
aight
