### ISSUE TITLE
Bug report: Debug mode lag

### ISSUE THREAD

**Issue by fistiG** [FunkinCrew/Funkin#273]
hi! I found a very unpleasant bug in the debug menu. When I get to section 18, I can't go back(when I press the button to go back, I'm thrown to the next section). Please fix this bug, it greatly interferes with the creation of mods.

Sincerely, FistiG.

**Comment by regulad** [comment]
https://user-images.githubusercontent.com/52430642/105635484-fd893180-5e30-11eb-9d77-878ab6410f33.mp4

I don't seem to have any issue. I was able to move around section 18 in Cocoa with no issues at all.

**Comment by fistiG** [comment]
>  2021-01-24.10-42-00_Trim.mp4 
> I wasn't able to reproduce the issue. I was able to move around section 18 in Cocoa with no issues at all.

Oh, I'm sorry, I made a little mistake. When I get to section 21.

**Comment by regulad** [comment]
https://user-images.githubusercontent.com/52430642/105638562-30d3bc80-5e41-11eb-8213-d828751f5450.mp4

Still can't seem to reproduce it.

**Comment by regulad** [comment]
@fistiG Could you provide a video of the problem occurring?

**Comment by fistiG** [comment]
> @fistiG Could you provide a video of the problem occurring?

ok

**Comment by fistiG** [comment]
https://user-images.githubusercontent.com/71457837/105750894-569eb580-5f56-11eb-8df4-13cf4c0a039a.mp4

**Comment by ninjamuffin99** [comment]
debug mode is debug mode
