### ISSUE TITLE
Bug Report: Week 6 Roses Erect, No zoom ins during the drops

### ISSUE THREAD

**Issue by RevivedAstor** [FunkinCrew/Funkin#2737]
1. Play on Erect version of Roses
2. There should be several consecutive zoom ins during the drops
3. No zoom ins

## Describe the bug
In Erect version of Roses (both Erect and Nightmare difficulties) zoom ins during the drops are gone. They used to be there an update prior to the newest one (Before Erect version of Satin Panties was added).  Character focusing is still there. The issue seems to be only in Roses, other songs don't have that issue.
I am playing in the browser

## Desktop
 - OS:
 Windows 10
 - Browser
 OperaGX
 - Version:
 0.4.0

**Comment by Hundrec** [comment]
This issue was also reported in https://github.com/FunkinCrew/Funkin/issues/2677

**Comment by GoombarioFan** [comment]
Seems to be fixed in 0.4.1.
