### ISSUE TITLE
Please, PLEASE FIX THIS. ITS DIRE.

### ISSUE THREAD

**Issue by GettinFreakyOnASundayNight** [FunkinCrew/Funkin#274]
When entering the game browser wise via Newgrounds or itch.io, the games loading screen tends to freeze at 80s and 70s. This has stopped me for playing for a week, in total, I have been able to open the game twice. I have also tried downloading the game, alas it will tell me that something is wrong and just erase itself off. Please try and fix the browser version.

**Comment by regulad** [comment]
Have you tried clearing your browser's cache, or trying another browser?

**Comment by gedehari** [comment]
Is refreshing the browser works for you? Mine stuck on 80% too but refreshing works

**Comment by regulad** [comment]
`CTRL+F5` on Firefox or `SHIFT+F5` on Chrome
