### ISSUE TITLE
Bug Report: Speaker doesn´t react to Volume (Desktop)

### ISSUE THREAD

**Issue by M7theguy** [FunkinCrew/Funkin#2744]
## Describe the bug

The Speaker in the Weekend 1 Songs does not react to volume (like it does in the Web builds)

## To Reproduce

This happens in every Weekend 1 Song

## Expected behavior

The bars in the speaker should go down/up by some

## Screenshots/Video

[https://github.com/FunkinCrew/Funkin/assets/170743168/234000d3-cb42-4158-846a-895fe43534b6](https://github.com/FunkinCrew/Funkin/assets/170743168/234000d3-cb42-4158-846a-895fe43534b6)

sorry for the laggy recording

## Desktop

* OS:
  Windows 11
* Version:
  v0.4.0

## Additional context

**Comment by Hundrec** [comment]
I personally think the web build reacting to game volume was an unintentional consequence of the way the HTML build visualizes audio
I prefer that the visualizer is unaffected by game volume

**Comment by M7theguy** [comment]
> I personally think the web build reacting to game volume was an unintentional consequence of the way the HTML build visualizes audio I prefer that the visualizer is unaffected by game volume

Oh I thought it was just a fun easter egg. 
I´m gonna leave this open tho in case that a dev wants it in

**Comment by VictorV323** [comment]
i'll like to add that the last line to the right of the visualizer NEVER goes up, i think that's a bug too
![imagen](https://github.com/FunkinCrew/Funkin/assets/84610589/1045b7dc-9783-4681-a7b7-1b71d83440fa)

**Comment by Hundrec** [comment]
> i'll like to add that the last line to the right of the visualizer NEVER goes up, i think that's a bug too

Just checked and this is true!

**HIGH PITCHED SOUND WARNING**

https://github.com/FunkinCrew/Funkin/assets/170126004/66a0690b-997f-42ed-be42-5f9063f63d14

**Comment by ninjamuffin99** [comment]
woops idk why
