### ISSUE TITLE
Bug Report: [Score BUG]

### ISSUE THREAD

**Issue by Dxgamer7405** [FunkinCrew/Funkin#2748]
I had a pfc in this song, and for some reason when i got a Excellent my pfc got replaced
This shouldn't happen
![image](https://github.com/FunkinCrew/Funkin/assets/95672691/556fd825-6757-4391-949a-3e67ca3c6710)

**Comment by NotHyper-474** [comment]
Already reported in https://github.com/FunkinCrew/Funkin/issues/2664

**Comment by EliteMasterEric** [comment]
Marked duplicate.
