### ISSUE TITLE
Black screen on 64 bit version Crashing 32 bit version

### ISSUE THREAD

**Issue by Geekume** [FunkinCrew/Funkin#275]
I honestly wish i got to enjoy the game I even put in a 5 dollar donation just cause i like seeing the game and how fun it is. However it has caused nothing but frustration. I had downloaded the 64 bit version first i was excited. only to find that i cant see a single thing, but i can hear the audio just fine and the controls still work. Then i thought no problem I will just play the 32 bit version. Deleted my files reinstalled the game but this time 32 bit version. I actually saw the game and could hear it too i played the 1st week 1st song and kinda getting into it when sudddenly boom. it crashes. I try skipping to week 2. Crashes. Week 4, crashed mid song. I tried looking over the internet for things to solve this issue but all i saw was "idk" and "me too" which helped out in no way. What is happening? I want to enjoy the game but i cant :( . If anyone out there could help that would be amazing.

**Comment by regulad** [comment]
Try clearing your AppData. (you will lose high scores!)

I'm assuming you are using windows, so the steps below or for Windows.

1. Navigate to `%appdata%/ninjamuffin99`
1. Delete the folder `Funkin`
1. Go back to where you unzipped the archive to
1. Delete the folder you unzipped the archive to
1. Re-download the `x86_64` version from itch.io
1. Use a tool like [7-Zip](https://www.7-zip.org/) to extract it to a safe place (ie, documents or deskstop)
1. Try again, see if it works.

**Comment by GabrielPivot** [comment]
hmmm yes
the game appears at task manager then dies.
the appdata in the 32 bit version doesn't appears.
i think i should only do step 3 to step 7 then.

**Comment by regulad** [comment]
> 
> 
> hmmm yes
> the game appears at task manager then dies.
> the appdata in the 32 bit version doesn't appears.
> i think i should only do step 3 to step 7 then.

All builds for windows read and write to AppData. It is likely that something else is wrong if it is never written to.

**Comment by Geekume** [comment]
Annnd it didnt work

**Comment by Geekume** [comment]
![Capture](https://user-images.githubusercontent.com/24945388/105639664-93c85200-5e47-11eb-80cf-c21a9fa9274b.PNG)

**Comment by GabrielPivot** [comment]
I can confirm that my pc is a windows 8 with 32 bit os
and drivers got forced.
And probably the game doesn't even opens neither if you extract it with 7-zip.

**Comment by regulad** [comment]
Are you using the `x86_64` (64 bit) version? There is no reason to use the `x86` (32 bit) version if your machine is `x86_64` (64 bit).

**Comment by Geekume** [comment]
I am indeed using the 64 bit version

**Comment by GabrielPivot** [comment]
> Are you using the `x86_64` (64 bit) version? There is no reason to use the `x86` (32 bit) version if your machine is `x86_64` (64 bit).

Oh wait sorry for the misunderstanding.
I got a 32 bit machine with 64 processor.
I tried the 64 bit version and windows says that it's not for my pc...
you know the blue rectangle with white text-

**Comment by regulad** [comment]
> 
> 
> > Are you using the `x86_64` (64 bit) version? There is no reason to use the `x86` (32 bit) version if your machine is `x86_64` (64 bit).
> 
> Oh wait sorry for the misunderstanding.
> I got a 32 bit machine with 64 processor.
> I tried the 64 bit version and windows says that it's not for my pc...
> you know the blue rectangle with white text-

Why are you running an `x86` OS on an `x86_64` Processor? Also, the `x86` version works perfectly fine for me. Both the dev build and the release build work perfectly, so architecture is not the issue.

**Comment by Geekume** [comment]
so what about my issue with the black screen what do I do about that? it seems like after investigating that when upon opening it still has the white flash effect and there is a black box which in my understanding is the "game screen". it seems as though the actual game itself is not calibrating to the size of the screen as it is supposed to. I know that that option depending on which compiler/language you used sometimes a fixed screen is default just as languages like Java do. and even after further investigation I noticed that the only thing that prevents each version to run either the 64 bit data on the 32 bit version or vise versa is the file named lime.ndll bringing in the specifics version of the file allowed me to run the manifest data for the other version meaning the json is identical that being said it could be a bug with a certain versions file. (keep in mind im not an expert on the language you use I mostly use languages such as C++ and took a course on Java)

**Comment by GabrielPivot** [comment]
> 
> Why are you running an `x86` OS on an `x86_64` Processor? Also, the `x86` version works perfectly fine for me. Both the dev build and the release build work perfectly, so architecture is not the issue.

First of all. Where's the dev build? and second of all. I can't fucking play it since week 3 update.

**Comment by regulad** [comment]
Just clone the repo and build the code using lime

**Comment by GabrielPivot** [comment]
i don't know how to build shit sorry

**Comment by Geekume** [comment]
im pretty sure he was referring to me man

**Comment by Geekume** [comment]
hey is there a way to contact you I feel like i am so close I just need a tiny bit of help

**Comment by Geekume** [comment]
Ok look this is just very annoying i at this point did so much work just to play this rhythm game i compiled the code downloaded lime installed all the visual studio components. did everything on that document. I spent days trying to get this working. and for some reason no matter what I do it is just broken. I even will show a screenshot showing in one picture that I have compiled the code and have gotten an error.

**Comment by Geekume** [comment]
![impissed](https://user-images.githubusercontent.com/24945388/105687512-89996880-5ec6-11eb-9ba1-54b43085016f.PNG)

**Comment by regulad** [comment]
Pretty sure that's because of #146, go and comment out shit making calls to newgrounds

**Comment by Geekume** [comment]
so it ran it didn't give that error and i wish I was joking but sadly im not the same dang issue that happened on the normal build of the game happened to the git version I really don't want to give up on it I want to play that game sooo bad.

**Comment by Geekume** [comment]
![not giving up](https://user-images.githubusercontent.com/24945388/105787139-65806a80-5f4c-11eb-8962-8bd96113b71e.PNG)

**Comment by lolBoi9696** [comment]
Why did you or someone mark this as a bug it's not really a bug since it works for us maybe you have outdated drivers or maybe your drivers are fucked or your windows is corrupted it's probs just windows being a little shit tbh and if you can update try that if your getting null object reference it's probs just ngio messing around it's legit fucked as it trys to login but it doesn't work cuz it isn't a Ng project they really need to fix that also if your getting it on free play just remove the ngio stuff in there it's pointless and Ur not using the ngio anyway

**Comment by Geekume** [comment]
> Have u even tried anything people said tho it sounds like u didnt

Yes and yes. I have done what people have asked. I have used both. If you read the comment chain heck even if your read the title that would give it away in plain site

**Comment by lolBoi9696** [comment]
just try updating or reinstalling windows or idk maybe just buy another computer cuz ur computer might just be the problem it works totally fine for me what specs do u have?

**Comment by Geekume** [comment]
> just try updating or reinstalling windows or idk maybe just buy another computer cuz ur computer might just be the problem it works totally fine for me what specs do u have?

You know what I advice you to just leave your helpful at all to me it seems like you have little to no computer knowledge. It is not my pc it can handle mid to high graphics just fine. My windows is up to date not that it would matter cause just look at how much it would take to play that game (very little it's a fricken rhythm game) you're just a troll who knows a) nothing about the situation and b) nothing about technology. It's not as simple as a windows update or this and that. I'm sick of hearing words come out of a mouth who knows absolutely nothing. Now if you excuse me I'm gonna go make a smart glasses with a raspberry pico and a custom ai

**Comment by lolBoi9696** [comment]
> > just try updating or reinstalling windows or idk maybe just buy another computer cuz ur computer might just be the problem it works totally fine for me what specs do u have?
> 
> You know what I advice you to just leave your helpful at all to me it seems like you have little to no computer knowledge. It is not my pc it can handle mid to high graphics just fine. My windows is up to date not that it would matter cause just look at how much it would take to play that game (very little it's a fricken rhythm game) you're just a troll who knows a) nothing about the situation and b) nothing about technology. It's not as simple as a windows update or this and that. I'm sick of hearing words come out of a mouth who knows absolutely nothing. Now if you excuse me I'm gonna go make a smart glasses with a raspberry pico and a custom ai

f u i do know about technology i just idk why you cant play this game i think its ur computer cuz it runs perfectly fine for me i even try the 32bit version if you want and i see if it works

**Comment by Geekume** [comment]
> > > just try updating or reinstalling windows or idk maybe just buy another computer cuz ur computer might just be the problem it works totally fine for me what specs do u have?
> > 
> > You know what I advice you to just leave your helpful at all to me it seems like you have little to no computer knowledge. It is not my pc it can handle mid to high graphics just fine. My windows is up to date not that it would matter cause just look at how much it would take to play that game (very little it's a fricken rhythm game) you're just a troll who knows a) nothing about the situation and b) nothing about technology. It's not as simple as a windows update or this and that. I'm sick of hearing words come out of a mouth who knows absolutely nothing. Now if you excuse me I'm gonna go make a smart glasses with a raspberry pico and a custom ai
> 
> f u i do know about technology i just idk why you cant play this game i think its ur computer cuz it runs perfectly fine for me i even try the 32bit version if you want and i see if it works

That is amazing but my point goes over your faster than a shooting star. That is awesome that it works for you. It's amazing stunning what other works can I use to describe that. However it may not be the same for everyone henceforth why this whole bug report is here honestly I probably have a better computer than you ngl. So if you have absolutely jack sh*t to contribute then I would stop replying NOW

**Comment by lolBoi9696** [comment]
> > > > just try updating or reinstalling windows or idk maybe just buy another computer cuz ur computer might just be the problem it works totally fine for me what specs do u have?
> > > 
> > > 
> > > You know what I advice you to just leave your helpful at all to me it seems like you have little to no computer knowledge. It is not my pc it can handle mid to high graphics just fine. My windows is up to date not that it would matter cause just look at how much it would take to play that game (very little it's a fricken rhythm game) you're just a troll who knows a) nothing about the situation and b) nothing about technology. It's not as simple as a windows update or this and that. I'm sick of hearing words come out of a mouth who knows absolutely nothing. Now if you excuse me I'm gonna go make a smart glasses with a raspberry pico and a custom ai
> > 
> > 
> > f u i do know about technology i just idk why you cant play this game i think its ur computer cuz it runs perfectly fine for me i even try the 32bit version if you want and i see if it works
> 
> That is amazing but my point goes over your faster than a shooting star. That is awesome that it works for you. It's amazing stunning what other works can I use to describe that. However it may not be the same for everyone henceforth why this whole bug report is here honestly I probably have a better computer than you ngl. So if you have absolutely jack sh*t to contribute then I would stop replying NOW

look im trying to help here idk why its not working for you it must be something with ur computer or operating system or cpu or gpu or whatever crap if it wasnt then it wouldnt work for anyone lol like it works for me totally fine really dont know why it doesnt work for you
