### ISSUE TITLE
Beating stress on normal also credits level completion for Darnell when in free play, when difficulty is switched, breaks free play menu

### ISSUE THREAD

**Issue by Oatm3a1** [FunkinCrew/Funkin#2750]
When you beat the song stress on normal in free play , after level completion, it credits Darnell with a new letter of it is unbeaten instead of stress, if you try to change difficulty after the bug, it breaks and the only song option is “random” which is nonfunctional if you try to play it, after you exit free play, the menu returns to normal 

Not sure what exact conditions trigger the bug I played the song stress in free play and got an exact score of 122018, after you exit the song completion menu with your note hit stats you see the new letter icon for when you beat a song in free play come up. after you do that, try to switch the difficulty and see if the only song listed is “random”

I expected for the compeletion letter grade next to the song in free play to come up because I hadn’t completed the song yet

![IMG_2458](https://github.com/FunkinCrew/Funkin/assets/172343990/c67c22a5-04e4-4424-bbbf-63479beb07c3)
![IMG_2457](https://github.com/FunkinCrew/Funkin/assets/172343990/a088879a-eff7-44c6-a2ee-d11f6f48d9f7)

## Desktop
 - OS: Windows 11
 - Browser: Ccleaner browser
 - Version: 0.4.0

**Comment by Hundrec** [comment]
It sounds like a few things happened here:

Right after you completed Stress, you hit a down button, which caused this bug to occur: https://github.com/FunkinCrew/Funkin/issues/2676

Then, when changing the difficulty, you hit Q, which switched the song list from "ALL" to "favorites".

Exiting the menu and re-entering reset the category to "ALL", displaying the songs again.

I think this is what happened, correct me if you these steps don't replicate your experience!
