### ISSUE TITLE
Enhancement: Animations and missing fla files

### ISSUE THREAD

**Issue by ImNot4ntony** [FunkinCrew/Funkin#2752]
While reviewing the fla files of the 0.4.0 update I noticed that several animations are missing such as the 4 new ones on the results screen + the new UI, freeplay redesigned assets (such as the easter eggs), the credits button in the main menu, the animation when santa speaks in eggnog etc, etc, even missing animations from before the update like tankman's ugh animation, etc etc

and this for modding is a problem since by not facilitating access to these new things it could make it difficult for someone to make their mod in a simpler and more comfortable way, I know that you have more animations and stuff pending so you won't release anything you should still Consider reviewing the fla files again and updating
 some to solve this type of thing, we modders would greatly appreciate it :)

![Captura de pantalla (2003)](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/981bf475-0e74-4314-b80c-aef5a43f5caf/7e130477-56fe-42c2-ab0f-03cd1c854054?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi85ODFiZjQ3NS0wZTc0LTQzMTQtYjgwYy1hZWY1YTQzZjVjYWYvN2UxMzA0NzctNTZmZS00MmMyLWFiMGYtMDNjZDFjODU0MDU0IiwiaWF0IjoxNzE4MTE5NzQ2LCJleHAiOjMzMjg4Njc5NzQ2fQ.iDPSyaVUxwNWL31vQVabTYlLmFMjQ4rUN_gApuiLmJg)

**Comment by AbnormalPoof** [comment]
List of missing FLAs I could think of:

- Blazin' Assets
- WeekEnd 1 cutscene assets
- DJ Boyfriend V2 (Pitstop)
- Eggnog Erect (Mall Santa talking and Parents animations)
- Alternate Results Screen animations (SHIT, GREAT, PERFECT)
- Tankman ("ugh" animation)
- Alternate Pico game over animations (2hot can explosion, Blazin')
- WeekEnd 1 background
- Boyfriend fakeout death

**Comment by EliteMasterEric** [comment]
Going to look into nagging Dave about this

**Comment by MlopsFunny** [comment]
> List of missing FLAs I could think of:
> 
> * Blazin' Assets
> * WeekEnd 1 cutscene assets (Darnell, 2hot, Blazin')
> * DJ Boyfriend V2 (Pitstop)
> * Eggnog Erect (Mall Santa talking and Parents animations)
> * Alternate Results Screen animations (SHIT, GREAT, PERFECT)
> * Tankman ("ugh" animation)
> * Alternate Pico game over animations (2hot can explosion, Blazin')
> * WeekEnd 1 background
> * Boyfriend fakeout death

Dont forget! The current shooting animation in Pico's FLA is a older draft, and not the same one as seen ingame. I also am relatively sure the "YEAH!" Spookeez animations are yet to be added. Also, Excellent Rank exists too, so dont forget that!

**Comment by PipocaAventuras** [comment]
i really need these flas to finish my reskin

**Comment by EliteMasterEric** [comment]
https://github.com/FunkinCrew/funkin.art/pull/2

The following were approved and uploaded a few minutes ago:

- Story Menu Weekend 1 Animations
- Weekend 1 Can Arc/Explosion Animations
- Weekend 1 Blazin' Darnell Animations
- Weekend 1 Blazin' Pico Animations
- Boyfriend Results Screen Excellent Animations
- Boyfriend Results Screen Great Animations
- Boyfriend Results Screen Loss Animations
- Boyfriend Results Screen Perfect Animations
- Weekend 1 Background Assets
- Boyfriend "Shiny" Fakeout Death Animation
- Weekend 1 Lighting Animations
- Christmas Santa Lipsync Animation
- Weekend 1 Traffic/Cars Animations

**Comment by AbnormalPoof** [comment]
Seems like v0.4 DJ Boyfriend isn't in here, will that one also be uploaded eventually?

**Comment by EliteMasterEric** [comment]
> Seems like v0.4 DJ Boyfriend isn't in here, will that one also be uploaded eventually?

DJ Boyfriend got uploaded about 6 seconds after you asked that!

I think almost everything is done so I'll mark this resolved. There might be one or two FLAs missing but we will get to them.

**Comment by AbnormalPoof** [comment]
> DJ Boyfriend got uploaded about 6 seconds after you asked that!
Ahaha, I see! Looks like that's all of the WeekEnd 1 stuff.

**Comment by PipocaAventuras** [comment]
YEES

**Comment by ImNot4ntony** [comment]
LET'S GO, TY FUNKIN GUYS!!!!!

**Comment by Lasercar** [comment]
We seem to still be missing a few of these? for example: Freeplay_redesign_assets_VER3 (the difficulty stars)

**Comment by AbnormalPoof** [comment]
- `Freeplay_redesign_assets_VER3.fla` is missing (The one with the difficulty stars)
- `Pico_FNF_assetss.fla` is outdated (The animation that plays during the intro of Weekend 1 is not there, the shooting animation is an early version, no "HEY!" or cheer animations)
- `FNF_main_menu_assets.fla` is outdated (No "Merch" and "Credits" sprites)
- All the FLAs for Week 2 Erect are missing (BG, Characters)
- `spooky_kids_assets.fla` is outdated (No cheer animation)
- `BoyFriend_Assets.fla` is outdated (No cheer animation, unless that's a different FLA??)
- All the Weekend 1 cutscene FLAs are missing (I believe Dave said these would be released at some point? I think it's somewhere in this VOD if I remember correctly: https://www.youtube.com/watch?v=wRwUMqRuHfw)
- `Tankman_Assets_pack.fla` is outdated (No "Ugh!" animation, unless that's a different FLA??)
