### ISSUE TITLE
Bug Report: Full Sick FCs overwritten by less accurate gameplay with higher score(s)

### ISSUE THREAD

**Issue by squidgegame** [FunkinCrew/Funkin#2753]
When getting an all Sick FC on a song, i expected to see a golden P next to my song score,
and when exiting the song, i see my Gold P as expected, however when i then leave and re-enter the Freeplay menu, its overwritten by a Pink P instead.

So what happened here?
Well, the reason the bug is happening is because of an underlying "issue" with the PBOT1 scoring system -

Let's say you have a song with 700 notes,
the max possible score would be 350000, because the tightest sicks reward 500 points per note and the max note count is 700
700 x 500 = 350 000
however, when scoring with the lowest possible sicks, your SFC High Score would be 245 000
700 x 350 = 245 000

Sorry for all the yapping, now onto the issue itself
On that same song, i could score an FC of 342 000, with 699 Sicks and 1 good
but then i could retry the same song and score a Sick FC of 341 150

and the bug then happens when you press ENTER to return to the Freeplay menu, you see your Gold P as expected
but when you back out and return, the game notices your high score was lower and replaces your Gold P with your Pink P

---

That was a hypothetical, but this actually has happened to me (as well as my friend Veta) on multiple occassions with multiple songs and its VERY frustrating, here's a video example:

https://youtu.be/7KNX-qi57AU

My SFC score here was 236 747
but my FC (1 Good) High score was 237 418
(The max score for Philly Nice Erect-N is 241 500) (483 x 500 = 241 500)

This means my Sicks were around 490/500 quality on average, aroooouund here ish on this graph
https://imgur.com/a/ThsbtuA

(because 483 x 490 = 236 670, which is the closest i could get to my score of 236 747 without decimals)

---
So, in summary
What im expecting to see: A Gold P next to the matching freeplay song because i got a Full Sick FC
What im actually seeing: My Gold P disappears when exiting the freeplay menu and is overwritten by my Pink P instead
Whats happening: my High Score on my Gold attempt is very very slightly lower than my Pink attempt, causing it to be overwritten

To recreate this issue, you need to play as well as you possibly can but intentionally score (at least) 1 good
and then retry the song and aim for the SFC and there's a high chance you might experience it

Or, you can write a bot to play as accurately as it can but intentionally scores 1 good on any song it plays
and then retry the same song with a bot thats written to play all Sicks but scores less accurate Sicks than the first bot
---
Effects of the issue:
It punishes expereinced players because of an extremely negligible accuracy difference of roughly 1000 to 2000 score spread over hundereds of notes and can actually make getting a new non-SFC high score feel worse than not getting one at all, because you know it just made getting an SFC high score much much harder than it would ever be if you never played the song at all
---
What can be done to fix the issue?
Well, the problem is that there isnt really an issue to begin with, the accuracy system is working fine and the high score system is working as intended (even though it does cause a temporary visual glitch in the freeplay menu)
I understand the logic behind both and i understand its technically still a skill issue on my part because a 490/500 avg still isnt a 500/500 avg per sick note
however i do disagree with it from a game design standpoint because of the effects of the issue so i do have a few fixes i think would work
---
Potential Fixes:
Add an option to erase specific song scores manually on the freeplay menu using the DEL key
-Allows players to compromise for a slightly worse high score in exchange for a Gold P

Add an option to overwrite your High score with a lower one on song completion
-Allows players to compromise for a Gold P, without having to manually erase their score on each failed attempt

Add a flat rating based small bonus per note based on your Sick to Good ratio:
Min: Note 0 of (song)
Sick +0
Good + 0

Max: Note (final) of (song)
Sick +50
Good + 20

Pro: -Prevents this small issue from happening in the first place
Con: -Outdates all previous scores by raising the High score ceiling by 50 per note
(For example, the new highest score on Philly Erect-N would be 265 650, instead of 241 500)
---
In my opinion i think one of the first two options would work best, just because it adds a bit of player agency to the scoring system
(and theres probably an issue in the third suggestion regardless LOL)
------

I think that should be everything LOL
(sorry for the book report its a really really specific thing to explain but im sure u guys get it cause ur smart and u made it)
in hindsight i probably should have listed this under feature suggestion but its also a visual glitch so idk which one fits more :(
sorry LOL

-thanks for making this game regardless of any issues big or small, it's awesome and it brings me back to watching stupid ass newgrounds cartoons on the youtube xbox app and playing GH3 with my friends when i was younger, it's already a phenomenal game and i cant wait to see what u guys have in store

**Comment by squidgegame** [comment]
(sorry for weird bold text, idk why it did that lol)

**Comment by Hundrec** [comment]
This bug was reported in #2664

Your text became headers because they were preceded by hashtags

## like this

**Comment by squidgegame** [comment]
aaah, ty
(sorry its my first time on github)

**Comment by Templarfreak** [comment]
if overall your all-sicks is, say, 95% accurate, because you dont hit the sick windows *perfectly,* than its only 95% accurate.

but i could see it being possible that you do all-sicks-but-1-good and all the sicks being exactly perfect being objectively a higher % accuracy overall even though you did 1 good instead of all sicks.

but to be fair i have no idea if this is actually how the new accuracy system for 0.3.x works.

**Comment by Hundrec** [comment]
> if overall your all-sicks is, say, 95% accurate, because you dont hit the sick windows *perfectly,* than its only 95% accurate.
> 
> 
> 
> but i could see it being possible that you do all-sicks-but-1-good and all the sicks being exactly perfect being objectively a higher % accuracy overall even though you did 1 good instead of all sicks.
> 
> 
> 
> but to be fair i have no idea if this is actually how the new accuracy system for 0.3.x works.

Please see #2664 for existing explanations of this issue!

**Comment by EliteMasterEric** [comment]
Fixed in v0.4.1 also a duplicate
