### ISSUE TITLE
Listen. I got a suggestion.

### ISSUE THREAD

**Issue by GabrielSomething** [FunkinCrew/Funkin#276]
Can you try fixing 32 bit build?
please?
i'm a windows 8.1 user with an x86_64 toaster machine.
The game don't even open and it only appears in the task manager.
## I had enough
just please fix it

**Comment by regulad** [comment]
The 32bit build seems to work perfectly fine for me on my `x86_64` machine. You shouldn't use the `x86` version if you are using a `x86_64` machine.

Also, this issue appears to be mislabeled as an enhancement.

**Comment by regulad** [comment]
This also seems to be a duplicate of #275.

**Comment by GabrielPivot** [comment]
ok. thanks anyways.
