### ISSUE TITLE
Bug Report: Re: #2758 ("Could not locate manifest" after editing and rezipping fnfc file)

### ISSUE THREAD

**Issue by prokube** [FunkinCrew/Funkin#2763]
## Describe the bug

I was looking to modify my chart's scroll speed, and after readin up on other peoples reports, I realized you could unzip a `fnfc` file. So, I did that, modified my scroll speed, rezipped and renamed the stuff. etc etc. Then, when I tried to load that `fnfc` again, it threw the error seen in attachment 1.

UPDATE: After seemingly finding a solution and charting without any issues, I save my `fnfc`, re-enter the charter, reopen the `fnfc`, and it hands me the same error.

## To Reproduce
1. Find an `fnfc` file (by making and saving a new chart or otherwise)
5. Try to load the `fnfc` ingame
6. Could not locate manifest :(

## Expected behavior

I expected the `fnfc` to load fine, seeing as I did not touch the manifest.

## Screenshots/Video

1. ![Screenshot 2024-06-12 at 11 08 50 AM](https://github.com/FunkinCrew/Funkin/assets/68293280/66c0df51-147d-4329-9d29-008ab4b8135f)

## Desktop
 - OS:
 
Mac
 - Browser
 
N/A
 - Version:
 
0.4.0

## Additional context

Maybe it's just a Mac thing :)))))

**Comment by prokube** [comment]
Reads bytes from `fnfc`, looks for manifest.json in the `fnfc`, throws once it doesnt find manifest, despite manifest being present. cool

**Comment by NotHyper-474** [comment]
You don't need to modify the chart file just to modify the scroll speed, the metadata window already has an option to do that: 
![image](https://github.com/FunkinCrew/Funkin/assets/40342021/07f4eedd-a4b6-43ce-8a53-fa7e64e6a38f)


Also in the case of #2758 it was only required because the files were "broken".

**Comment by prokube** [comment]
how did i never see this

**Comment by prokube** [comment]
nevermind. you actually dont even have to unzip it, it seems. it just breaks when i try to open it again after saving. on top of that, backups only seem to load the events and not the notes. ???

**Comment by tposejank** [comment]
Unzip whatever is the latest backup or save of your fnfc and check if it has the manifest.json

**Comment by prokube** [comment]
> Unzip whatever is the latest backup or save of your fnfc and check if it has the manifest.json

I'll do y'all one better: here's an unzipped backup.
![Screenshot 2024-06-12 at 1 18 35 PM](https://github.com/FunkinCrew/Funkin/assets/68293280/5c4c7e4a-9bc2-4b3b-8b53-3d5fe575bbb3)

**Comment by tposejank** [comment]
does the manifest .JSON say the songid is "isatest"?

**Comment by prokube** [comment]
It's because I created it from Erect/Nightmare only. oh my fuckin god lol

**Comment by prokube** [comment]
> nevermind. you actually dont even have to unzip it, it seems. it just breaks when i try to open it again after saving. on top of that, backups only seem to load the events and not the notes. ???

this was because I was charting the Easy difficulty (default diff after creating the map), and the default difficulty when loading is Normal
