### ISSUE TITLE
Whenever i get a perfect rank on high nightmare mode, it puts the rating back down to excellent instead

### ISSUE THREAD

**Issue by Goofer529** [FunkinCrew/Funkin#2764]
-->

## Describe the bug

So whenever i beat high erect with a perfect rank, if i change the difficulty or exit out of freeplay then it puts the rating of the song down to excellent.

## To Reproduce
Just whenever i get perfect rank on high erect.
## Expected behavior
Expected it to keep the rank.

## Screenshots/Video
Video showing the issue
https://github.com/FunkinCrew/Funkin/assets/172536161/03a75142-03a8-4aac-96f7-e38b81086232

## Desktop
 - OS: Windows 10
 - Browser: on application version
 - Version: 0.4.0

I hope you can get this sorted.

**Comment by NotHyper-474** [comment]
This issue was already reported here https://github.com/FunkinCrew/Funkin/issues/2664

**Comment by EliteMasterEric** [comment]
Fixed in v0.4.1 also a duplicate
