### ISSUE TITLE
Cutscenes are WAYYY too quiet if on lower volumes

### ISSUE THREAD

**Issue by LightninghawkYT** [FunkinCrew/Funkin#2765]
Nothing much to explain here, cutscenes seem to be way more sensitive to volume changes than the actual game itself

https://github.com/FunkinCrew/Funkin/assets/57375551/d84711a7-c76d-4837-981b-dd49fe7fc14a

**Comment by NotHyper-474** [comment]
Duplicate of https://github.com/FunkinCrew/Funkin/issues/2410
