### ISSUE TITLE
bug: Characters Fly When Resized with Json

### ISSUE THREAD

**Issue by MemTheBun** [FunkinCrew/Funkin#2766]
## What is your suggestion, and why should it be implemented?

Characters fly (again) when changing sizes in the json

**add skibidi toilet to the game pls mr muffin**

**Comment by MemTheBun** [comment]
**i was forced to say this**

**Comment by Hundrec** [comment]
Can you provide more information or a video?

**Comment by MemTheBun** [comment]
wait lemme

**Comment by MemTheBun** [comment]
also this happenes in character offset editor and gameplay

**Comment by AbnormalPoof** [comment]
fixed in v0.5.0

**Comment by EliteMasterEric** [comment]
Fixed
