### ISSUE TITLE
Bug Report: Freeplay song title STILL displays Erect variation title

### ISSUE THREAD

**Issue by Hundrec** [FunkinCrew/Funkin#2768]
## Describe the bug
Sometimes, the title of a song in the Freeplay menu will display its Erect variation's title instead.

## To Reproduce
1. Start Dadbattle on Hard difficulty through the Freeplay menu 
2. Exit to the Freeplay menu
3. The title of Dadbattle will be Dadbattle Erect

## Desktop
 - OS:
Windows 11
 - Version:
0.4.1 (itch.io Version 16)

## Additional context
Previously reported in #2678 and #2685 (and several duplicates)

Marked as fixed in the v0.4.1 patch, but the bug still persists in the downloadable build.
Doesn't happen in the browser itch.io/Newgrounds version

**Comment by NotHyper-474** [comment]
Interestingly this is also the case when building the game: web version doesn't have issue but native does. So it's not like some code they forgot to port to native

**Comment by BStasik** [comment]
did 0.4.1 even fixed anything for real...

**Comment by NotHyper-474** [comment]
> Interestingly this is also the case when building the game: web version doesn't have issue but native does. So it's not like some code they forgot to port to native

My dumbass only tested the web version when compiling, and tested native on the downloadable build instead. Turns out it WAS fixed in native too, but for whatever reason this fix is not in the downloadable build

**Comment by Hundrec** [comment]
@NotHyper-474 This makes a lot more sense. Thanks for testing!

**Comment by ninjamuffin99** [comment]
may have just had lil snafu with update, may or may not be fixed now / uploaded properly!

**Comment by BStasik** [comment]
in the version 17(0.4.1) this bug still exicts

**Comment by NotHyper-474** [comment]
> in the version 17(0.4.1) this bug still exicts

It's fixed for me, did you re-download it?
