### ISSUE TITLE
Bug Report: Crash when clicking inside game's window

### ISSUE THREAD

**Issue by Netskia** [FunkinCrew/Funkin#2769]
Newest update makes the game crash when clicking inside the window even just to fullscreen the game.

![Screenshot 2024-06-12 233124](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/a475857a-32bb-45a0-9d7a-8e5fcff1a0c3/412380aa-edcd-4df2-9f35-2c24a7dd70bc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi9hNDc1ODU3YS0zMmJiLTQ1YTAtOWQ3YS04ZTVmY2ZmMWEwYzMvNDEyMzgwYWEtZWRjZC00ZGYyLTlmMzUtMmMyNGE3ZGQ3MGJjIiwiaWF0IjoxNzE4MjM3NDE4LCJleHAiOjMzMjg4Nzk3NDE4fQ.\_hLQF7XjYoY2XNiJyXlcAU2RhmNvFU8kbwtp6qMmD8U)

**Comment by ninjamuffin99** [comment]
I believe this is fixed now, just had piece of wonky code! If you redownload, gimme shout if you're still running into this!

**Comment by Netskia** [comment]
Thanks for the Quick fix! I am on Win11 and it was version 15 but I re-downloaded it right after, replaced the files and it worked fine again. So I can't replicate the bug just yet but will let you know! Thanks for the good work guys ❤️

**Comment by Netskia** [comment]
Fixed for now
