### ISSUE TITLE
Enhancement: Add those camera events from 0.3.0 update to Roses Erect.

### ISSUE THREAD

**Issue by BStasik** [FunkinCrew/Funkin#2771]
## What is your suggestion, and why should it be implemented?
Events like "zoom in" at the player or opponent.
They had exicted until version 0.4.0 came out. But they were deleted and in 0.4.1 they are still missing.

**Comment by Hundrec** [comment]
Apparently, the camera events are present in itch.io and Newgrounds HTML build but not itch.io Version 16.

I'm starting to think some changes were left out in the downloadable build!

**Comment by BStasik** [comment]
> ild!

yes! in the downloadable build almost nothing got fixed

**Comment by Hundrec** [comment]
This bug is now fixed in the latest build!
https://github.com/FunkinCrew/Funkin/issues/2768#issuecomment-2164142508

**Comment by BStasik** [comment]
> This bug is now fixed in the latest build! [#2768 (comment)](https://github.com/FunkinCrew/Funkin/issues/2768#issuecomment-2164142508)

some bug are still not fixed((
