### ISSUE TITLE
Bug Report: A-Bot's visualizer has a stuck column on Desktop

### ISSUE THREAD

**Issue by Hundrec** [FunkinCrew/Funkin#2772]
## Describe the bug
The last column of A-Bot's visualizer will always stay at the lowest level while all other columns react to the instrumental

## To Reproduce
1. Play any Weekend 1 song

## Desktop
 - OS:
Windows 11
 - Version:
0.4.1 (itch.io Version 16)

## Video

https://github.com/FunkinCrew/Funkin/assets/170126004/3599906b-10d4-40cd-8b0f-425506f79fa6

## Additional context
First mentioned in this comment: https://github.com/FunkinCrew/Funkin/issues/2744#issuecomment-2159188133

Tested with a high pitched sound here: https://github.com/FunkinCrew/Funkin/issues/2744#issuecomment-2159220337

**Comment by BStasik** [comment]
what was that rain😭

**Comment by Hundrec** [comment]
> what was that rain😭

The game hit me with the double-bug 🌧️

**Comment by AbnormalPoof** [comment]
[funkVis#7](https://github.com/FunkinCrew/funkVis/pull/7) addresses this.

**Comment by Hundrec** [comment]
Such an easy fix, hope this gets added in the next update!

**Comment by MidyGamy** [comment]
Yeah, the bug actually addresses all visializer

**Comment by ninjamuffin99** [comment]
> [funkVis#7](https://github.com/FunkinCrew/funkVis/pull/7) addresses this.
This PR was merged into funkVis, so next update shoudl fix this bug !
