### ISSUE TITLE
Report: (Some) fixes for v0.4.1 do not apply to downloadable builds

### ISSUE THREAD

**Issue by NotHyper-474** [FunkinCrew/Funkin#2774]
For whatever reason issues like https://github.com/FunkinCrew/Funkin/issues/2676, https://github.com/FunkinCrew/Funkin/issues/2678 and various others that should've been fixed in this update were not. 

This only applies to the downloadable builds (I only tested with Windows but it could be the same with MacOS too), the Itch.io and Newgrounds versions do not share this problem, and neither do builds that are compiled by yourself

**Comment by Hundrec** [comment]
I'd like to add that at least _some_ bugs were fixed on the downloadable build, such as https://github.com/FunkinCrew/Funkin/pull/2683

**Comment by NotHyper-474** [comment]
Will be closing this due to https://github.com/FunkinCrew/Funkin/issues/2768#issuecomment-2164142508
