### ISSUE TITLE
Enhancement: Add a toggle that causes the current song to immediately restart when you get a game over

### ISSUE THREAD

**Issue by ChillyBeanBAM** [FunkinCrew/Funkin#2779]
## What is your suggestion, and why should it be implemented?
I think there should be a toggle where enabling it causes the current song to restart immediately after getting a game over, skipping the usual sequence (the blue ball counter will still go up, however); think of it being something like the "`doImmediateRespawn`" game rule in Minecraft. It could help players jump back into the song much quicker after dying without being forced to watch the rather lengthy sequence first. Thanks in advance!

**Comment by AbnormalPoof** [comment]
This describes a similar thing to #2442, which was rejected. (Except this one asks for a toggle and #2442 asks for a hotkey.)

**Comment by ChillyBeanBAM** [comment]
Should I close this issue then?

**Comment by Hundrec** [comment]
Yes, please close this issue
