### ISSUE TITLE
Linux build outdated on itch.io

### ISSUE THREAD

**Issue by nununoisy** [FunkinCrew/Funkin#278]
Title says it all.

**Comment by ninjamuffin99** [comment]
pixel day update coming in the next day or so, I'll update linux build around then!!! sorry bout dat just got busy wit dis new update heheh

**Comment by itstoast27** [comment]
is it coming soon? i want crisms fams

**Comment by foxsouns** [comment]
....

**Comment by ninjamuffin99** [comment]
woops
