### ISSUE TITLE
Enhancement: Better Difficulty Ratings

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#2781]
## What is your suggestion, and why should it be implemented?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There are a lot of songs I think everyone agrees are harder than other songs that are rated lower, and I feel like I see this happening due to trying to map the difficulty ratings to a smooth curve when no such curve really exists for base game. Main songs go up in star rating too smoothly and there are base game songs harder than erect songs, like come on, if we're being real, Guns and 2hot are much harder than freaking _Eggnog Erect_, yet have a lower ranking. Many songs I find to be like this where their star rating closer match what you might feel they **should** be at for their placement in the game rather than their actual difficulty.

**Comment by Hundrec** [comment]
Maybe they could run some moderated polls to determine how hard the community thinks each song is on a scale from 1-20 (or more)

**Comment by amyspark-ng** [comment]
i still think that ratings should not be set manually but rather with notes per second or something like that

**Comment by EliteMasterEric** [comment]
If we decide to change the difficulty ratings, we will, but we currently have no plans to do that.
