### ISSUE TITLE
Bug Report: A-Bot doesn't "bump" to the beat in-game

### ISSUE THREAD

**Issue by rrev07** [FunkinCrew/Funkin#2783]
The A-Bot hull is static, there's supposed to be an animation playing but it is not currently present.
![Leak_8_Nene](https://github.com/FunkinCrew/Funkin/assets/168675317/4ffffdae-e0b3-470b-8026-5fac6200d87a)
 (not talking about the viz)

**Comment by Hundrec** [comment]
I don't see any static parts other than the tube on the right.
Can you point to the animation error?

**Comment by rrev07** [comment]
the issue is present in the game itself! The gif I attached was for reference. The animation itself exists in the sprite

Uploading 2024-06-13 11-29-21.mp4…

map, however it appears to be unused.

**Comment by rrev07** [comment]
the issue is present in the game itself! The gif I attached was for reference. The animation itself exists in the spritemap, however it appears to be unused.

https://github.com/FunkinCrew/Funkin/assets/168675317/68b7ad8a-7f45-4f98-9959-c04078a92a60

**Comment by Hundrec** [comment]
Thanks for clarifying!

This is honestly a pretty important detail, good that you noticed it!

**Comment by ninjamuffin99** [comment]
woah thanks! I will look into this!

**Comment by ninjamuffin99** [comment]
Fix has been found internally, we should have this in an upcoming update, thanks!
