### ISSUE TITLE
Bug Report: character offseting issue with sizing and isPixel

### ISSUE THREAD

**Issue by 7oltan** [FunkinCrew/Funkin#2788]
## Describe the bug
when the characters size is other then 1 or the character isPixel is enabled, the offseting becomes off and the character leans off screen

## To Reproduce
i genuinly dk what reproudce is lmao
## Expected behavior
the character not to lean??

## Screenshots/Video
pretty self explantory doesnt really need a video

i cant believe yall didnt inculde this in 0.4.1

here are the lines:

https://github.com/FunkinCrew/Funkin/blob/49155b06b3cfb5b8bae9322b463efef026c6c1e3/source/funkin/play/character/BaseCharacter.hx#L127
https://github.com/FunkinCrew/Funkin/blob/49155b06b3cfb5b8bae9322b463efef026c6c1e3/source/funkin/play/character/BaseCharacter.hx#L128

-----

heres the fix :

replace` (this.isPixel ? 6 : 1))` with `getBaseScale()`

for both line 127 and 128

sorry if this issue thingy is messy this is my first time

**Comment by AbnormalPoof** [comment]
This was fixed in v0.5.0
