### ISSUE TITLE
Bug Report: Polymod doesn't use binary assets in mods

### ISSUE THREAD

**Issue by regulad** [FunkinCrew/Funkin#279]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [x] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.6

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Copy a mod into the `assets/mods` folder that changes binary assets, like `.ogg` or `.png`
1. Declare the mod in `modList.txt`
1. Launch the game

## Please describe your issue. Provide extensive detail and images if possible.
Only text files, like `.txt`, `.json`, and `.xml` can currently be changed by Polymod, not binary files like `.ogg` or `.png`.

**Comment by AyeTSG** [comment]
Is anyone aware why this happens? If we can fix this, this would make the polymod modding system fully complete, no?

**Comment by AyeTSG** [comment]
I think I've found out the problem. Polymod hooks into the lime ``Assets`` class, but most of the images don't use that, rather they use ``FlxSprite`` and ``FlxAtlasFrames``. This may instead be a polymod issue.

**Comment by regulad** [comment]
> 
> 
> I think I've found out the problem. Polymod hooks into the lime `Assets` class, but most of the images don't use that, rather they use `FlxSprite` and `FlxAtlasFrames`. Sounds also aren't replaced as they're being loaded with `FlxG.sound.playMusic`. This may instead be a polymod issue.

If it's not too much of a pain, could you consider making a pull request?

**Comment by AyeTSG** [comment]
I would, but I don't know enough about Haxe to fix this on FNF or Polymod's end...
