### ISSUE TITLE
Bug Report: Heart Icons look weird when changing Categories

### ISSUE THREAD

**Issue by M7theguy** [FunkinCrew/Funkin#2795]
## Describe the bug
When giving a song a "Favourite" and then changing the category/difficulty, the heart icon on the song will look weird

## To Reproduce
(not 100% sure)
1. Press F on any song
2. Change the difficulty to the Encore/non-Encore variant of the song
3. Change the category to one that has your song
## Expected behavior
The Heart icon is supposed to look different (see video) 

## Screenshots/Video

https://github.com/FunkinCrew/Funkin/assets/170743168/990e9c2e-d50e-4a8e-9701-0df963074eed

## Desktop
 - OS:
 Windows 11 
 - Version:
 v0.4.1

**Comment by EliteMasterEric** [comment]
Was able to reproduce this myself, although not consistently.

**Comment by ninjamuffin99** [comment]
I have a fix for this @elitemastereric in our development repo peep peep
