### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by GracuszeQ** [FunkinCrew/Funkin#28]
The game won't load sometimes, it's stuck on a black screen and you need to refresh the page for it to work. (Sorry if my english is bad)
![Zrzut ekranu (4)](https://user-images.githubusercontent.com/75179771/101156773-63272180-3629-11eb-86e0-c9416bf53022.png)

**Comment by gedehari** [comment]
Hi, have you tried clicking on the game screen after it loaded? That solves it for me. I think it is related to the Chrome multimedia policy

**Comment by ninjamuffin99** [comment]
ay this one a lil vague, imma close it for now!
