### ISSUE TITLE
Results percentage counter plays ticking audio inconsistently

### ISSUE THREAD

**Issue by rrev07** [FunkinCrew/Funkin#2802]
The score percentage counter in the results screen has a weird audio bug that's present in the HTML5 version of the game only

https://github.com/FunkinCrew/Funkin/assets/168675317/c6e2679e-4bdd-4b61-8ebc-e53a2a613a82

**Comment by Average-FNF-Modder** [comment]
Pretty sure this happens in all versions last I checked.

**Comment by rrev07** [comment]
correct, I just put the version I tested it on.

**Comment by EliteMasterEric** [comment]
I do not have any reproduction for this issue yet. I have seen other users experience it but I have never experienced it myself.

**Comment by Hundrec** [comment]
Replicated on Newgrounds and Itch.io 0.5.0

# Newgrounds
## Perfect
https://github.com/user-attachments/assets/1a89ea67-a4d8-47f7-b6be-874e16542fae

## Loss
https://github.com/user-attachments/assets/46433acd-8c8f-4532-8e90-489778ad53a0

# Itch
## Perfect
https://github.com/user-attachments/assets/15883d94-64a6-4ca4-a65b-f130bcee53f9

## Loss
https://github.com/user-attachments/assets/3534a2cb-da5b-4e5c-9697-c36f8c3af661

**Comment by AbnormalPoof** [comment]
I noticed at times that this bug can cause the results music to not play, which may be linked to #2732!

**Comment by EliteMasterEric** [comment]
Fixed
