### ISSUE TITLE
Bug Report: FlxAtlasSprite.hx:66: characters 5-38

### ISSUE THREAD

**Issue by fianalins** [FunkinCrew/Funkin#2806]
## Describe the bug
I am getting an error while compiling because of FlxAtlasSprite.hx:66: characters 5-38
## To Reproduce
- Follow steps on COMPILING.md
- Try and compile
- Get error
- Try and troubleshoot
- Nothing appears 👍
## Expected behavior
To compile properly

## Screenshots/Video
![image](https://github.com/FunkinCrew/Funkin/assets/87100196/2f3ec712-ca2a-4537-8389-40a1a61cf196)

## Desktop
 - OS:
 Windows 11
 - Browser
 Chrome
 - Version:
 TRYING to compile 0.4.1

## Additional context
I dislike trying to compile base game

**Comment by Hundrec** [comment]
I totally relate to your frustration

Let's start simple: 
Did you make sure you had the art and assets submodules downloaded?

If not, try running "git submodule update --init --recursive"

**Comment by fianalins** [comment]
I have both the art and assets folder already.

**Comment by Hundrec** [comment]
Next up, did anything fail to install when you ran "hmm install"?

Even if things looked fine, you can try deleting the .haxelib folder and rerunning "hmm install"

This always fixed mysterious issues for me

**Comment by fianalins** [comment]
I didn't see anything wrong when I had ran hmm. I removed it though and now it is telling me that it could not find haxelib "haxeui-core", when it didn't tell me this before. I went through the same steps in the COMPILING.md after deleting the folder.

**Comment by Hundrec** [comment]
Try deleting your hmm file and reinstalling it.

If this doesn't work, try cloning the entire repository from scratch.

**Comment by fianalins** [comment]
I reinstalled it and now its telling me "Validation error: hmm.json not found in current working directory"
Everything is going wrong now lol 😭

**Comment by Hundrec** [comment]
It seems like you aren't properly reinstalling the files you're deleting. Are you in the right directory? 

Make sure to follow the steps in the building guide after each deletion.

**Comment by fianalins** [comment]
I figured out that I had to do `hmm init` and it creates the hmm.json file which it doesn't say in the compile guide. However it's giving me an error about grig.audio now.

![image](https://github.com/FunkinCrew/Funkin/assets/87100196/4eba8777-dcca-4fdf-a02a-444682aea908)

**Comment by fianalins** [comment]
I found that you have to do `haxelib git grig.audio https://github.com/osakared/grig.audio` instead of `haxelib install grig.audio` and now it is giving me this

![image](https://github.com/FunkinCrew/Funkin/assets/87100196/15a6a7a7-822c-4af9-9e47-87bb64623afb)

**Comment by fianalins** [comment]
Download GitHub
