### ISSUE TITLE
Bug Report: Yo Dev So I Playing My Own Game And I Noticed That My Game Crashes On Week 2 And My Gf Dissapering In The BG 

### ISSUE THREAD

**Issue by KeithFromFridayNightFunkin** [FunkinCrew/Funkin#282]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [ ] macOS

**Comment by regulad** [comment]
Have you tried the basic troubleshooting steps?
