### ISSUE TITLE
Bug Report: % Cleared will save a lower number as long as you don't score below your current rank.

### ISSUE THREAD

**Issue by NewCs386148** [FunkinCrew/Funkin#2821]
## Describe the bug
 As long as your rank is the same, playing a song with a worse completion will always replace the saved % cleared to your most recent one.

## To Reproduce

Play any song that you already have a rank on (that isn't 100% completed). If you get the same rank, your % complete will always get overridden by the new % completed, even if your score is lower than your highscore or your % complete is lower than before.
## Expected behavior
 % complete should save your best completion instead of your most recent one.

## Screenshots/Video

Before (99% saved):
![PicoBefore](https://github.com/FunkinCrew/Funkin/assets/172553474/324805cf-900a-408e-927e-69f7bf173859)

After (93% saved):
![PicoAfter](https://github.com/FunkinCrew/Funkin/assets/172553474/05d8c04e-6bcf-4194-ae3e-08a87b536412)

## Desktop
 - OS: Windows 10.
 
 - Browser: Edge.
 
 - Version: 0.4.1

**Comment by WhatIsThisPl** [comment]
It happens as well to all Desktop Version

**Comment by EliteMasterEric** [comment]
Investigating

**Comment by SnowyyWHY** [comment]
this happened to me too

**Comment by bernardo3333** [comment]
eu tenho uma conta na newgrounds e minhas medalhas nao cairam na minha conta

**Comment by NotHyper-474** [comment]
> eu tenho uma conta na newgrounds e minhas medalhas nao cairam na minha conta

Isso não tem nada a ver com este issue

**Comment by AbnormalPoof** [comment]
This still happens on v0.5.0
