### ISSUE TITLE
There is no assets in the source code

### ISSUE THREAD

**Issue by CorpsyPartRe** [FunkinCrew/Funkin#2825]
I tried to download the source code there was no assets and nothing.

**Comment by NotHyper-474** [comment]
You mean you downloaded it as a ZIP? You should be doing `git clone https://github.com/FunkinCrew/Funkin.git --recurse-submodules` instead.

If you just want the assets you can download https://github.com/FunkinCrew/funkin.assets

**Comment by EliteMasterEric** [comment]
User did not properly follow the compilation guide.
