### ISSUE TITLE
Tiny Things

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#2826]
## You do `NOT` have to add all of these! These ideas will just make the game better and more interesting, and probably fix my triggers.

- Difficulty Based Voices (Example: The chart of some songs for the easier difficulties lose arrows, but when they are singing there are still extra vocals, so what if the vocals match the chart of a song, like the easy/normal difficulty chart.)  (This is a big thing to implement so its fine if it doesn't get added in-game.)

- More Stickers for characters (Senpai, Angry Senpai, Spirit, Spooky Kids, Nene, Darnell, Tankman)

- Bonus Stickers (Arrows, Boombox/Speaker, Pico's Uzi, Boyfriends Mic, Newgrounds Tank, Darnell Spraycan, Nene Knife, etc.)

- Custom Freeplay Image when hovering over a song. (Example: When you hover over any of the Week 1 Songs, it will show that picture of Daddy Dearest, but then when you hover over Week 6 for example, it will show Senpai or something related to Week 6 instead of the Daddy Dearest Freeplay PNG)

- Album MetaData Fixing (Some of the songs are in the incorrect albums, like Eggnog Erect remix says Volume 1, when its from Volume 3 or OST Expansion.

- Custom Stage Background for Animation Editor, like you could either have the option for the transparent PNG or to use one of the games stages, or you could import your own background or picture.

- Week 6 Note Fixes, like note splashes, and note hold covers.

- Nightmare and Erect difficulties on Story Mode Menu

- Achivements, like if you full combo a week, get a certain results screen, if you perfect combo a week or a song, or something straight up stupid like scrolling in the freeplay menu for a bit. (This is a big one so it's fine if I don't see this in game)

Once again, you do `NOT` have to add all of these! These ideas will just make the game better and more interesting, and probably fix my triggers. I want the update ASAP so if any of these are too hard then you could skip it.

Thank you Funkin' Crew for all of these years of work and love, you guys have worked so hard! You guys have geniunely cured my boredom and gave me memories and new things to explore, this game will be forever in my heart. Even when I'm dying in the hospital bed.

- `Pixel.`

**Comment by JVNpixels** [comment]
![bfSticker1](https://github.com/FunkinCrew/Funkin/assets/146671762/3a474eea-08e2-4ff8-b53a-465bc7b7fb79)
![bfSticker2](https://github.com/FunkinCrew/Funkin/assets/146671762/e23be26a-9beb-4427-a7c3-91a83d39c2c0)
![bfSticker3](https://github.com/FunkinCrew/Funkin/assets/146671762/a335e280-cc62-432a-809f-ddad639e197a)

**Comment by JVNpixels** [comment]
asdf

**Comment by EliteMasterEric** [comment]
> Difficulty Based Voices (Example: The chart of some songs for the easier difficulties lose arrows, but when they are singing there are still extra vocals, so what if the vocals match the chart of a song, like the easy/normal difficulty chart.) (This is a big thing to implement so its fine if it doesn't get added in-game.)

There are no plans to implement this, as it would mess with how the song sounds, drastically complicate easy/normal charting (because now the new charts need to SOUND good too), and drastically increase the game's already expanding file size.

> More Stickers for characters (Senpai, Angry Senpai, Spirit, Spooky Kids, Nene, Darnell, Tankman)
> Bonus Stickers (Arrows, Boombox/Speaker, Pico's Uzi, Boyfriends Mic, Newgrounds Tank, Darnell Spraycan, Nene Knife, etc.)

Maybe.

> Custom Freeplay Image when hovering over a song. (Example: When you hover over any of the Week 1 Songs, it will show that picture of Daddy Dearest, but then when you hover over Week 6 for example, it will show Senpai or something related to Week 6 instead of the Daddy Dearest Freeplay PNG)

This was originally planned, but there are technical issues involved with making it work without stuttering.

> Album MetaData Fixing (Some of the songs are in the incorrect albums, like Eggnog Erect remix says Volume 1, when its from Volume 3 or OST Expansion.

This is already in progress.

> Custom Stage Background for Animation Editor, like you could either have the option for the transparent PNG or to use one of the games stages, or you could import your own background or picture.

I don't see the point of this, the existing grid is there to help with positioning.

> Week 6 Note Fixes, like note splashes, and note hold covers.

I think this was planned at one point but I'm not sure of the status.

> Nightmare and Erect difficulties on Story Mode Menu

This was originally planned but then removed.

> Achivements, like if you full combo a week, get a certain results screen, if you perfect combo a week or a song, or something straight up stupid like scrolling in the freeplay menu for a bit. (This is a big one so it's fine if I don't see this in game)

Already mentioned in #2827.

Overall, all these things are either not planned, already planned, or duplicates. Closing.

**Comment by JVNpixels** [comment]
aww man :(

**Comment by JVNpixels** [comment]
aww shucks :(

**Comment by Banjoei** [comment]
Why exactly are Erect mixes in the Story Mode removed? Does this mean they'll never happen?
