### ISSUE TITLE
Bug Report: Chart Editor Crash when attempting to leave.

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#2829]
## Describe the bug
Sometimes when I leave the Chart Editor, it crashes with a bug related to Haxe UI.

## To Reproduce
Leave the chart editor using F4 or leaving it in genera (It is a slight chance)
## Expected behavior
It is suppose to take me back to the MainMenuState

## Screenshots/Video
I do not have a screenshot or video, but here is the error message:
There was a problem validating this component as it has already been destroyed (haxe.ui.notifications.Notification#null)

## Desktop
 - OS:
Windows 11
 - Browser
Chrome
 - Version:
v0.4.1

**Comment by amyspark-ng** [comment]
rename the issue, i think this is related to the notification that appears when you copy notes

**Comment by amyspark-ng** [comment]
rename the issue, i think this is related to the notification that appears when you copy notes

**Comment by ChillyBeanBAM** [comment]
Still happens in v0.5.1. Here's my crash log:
[crash-2024-10-01-11-07-00.log](https://github.com/user-attachments/files/17211848/crash-2024-10-01-11-07-00.log)

**Comment by Hundrec** [comment]
To clarify, this is the same issue as #2579
