### ISSUE TITLE
Bug Report: The "h" in "2hot" is capitalized on the freeplay menu, but lowercase in story mode and the OST. Literally unplayable.

### ISSUE THREAD

**Issue by NewCs386148** [FunkinCrew/Funkin#2830]
## Screenshots/Video

2Hot:

![2HotFreeplay](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/049dab99-ad69-476f-82cf-f8102f5f5088/5f32ebcd-460e-4501-877b-bae7912d9585?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi8wNDlkYWI5OS1hZDY5LTQ3NmYtODJjZi1mODEwMmY1ZjUwODgvNWYzMmViY2QtNDYwZS00NTAxLTg3N2ItYmFlNzkxMmQ5NTg1IiwiaWF0IjoxNzE4NTk0NDkxLCJleHAiOjMzMjg5MTU0NDkxfQ.sqr0wuo8k4qDl-6FYVwf6B-vk2Q7je0lWdCL_MyVkxI)

2hot:

![2hotStory](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/5f8405bf-71dd-4936-9ec1-f5d3e82b08c0/551974fb-e3ef-4466-be8f-7f2ddd96c80e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi81Zjg0MDViZi03MWRkLTQ5MzYtOWVjMS1mNWQzZTgyYjA4YzAvNTUxOTc0ZmItZTNlZi00NDY2LWJlOGYtN2YyZGRkOTZjODBlIiwiaWF0IjoxNzE4NTk0NDkxLCJleHAiOjMzMjg5MTU0NDkxfQ.1CB7WwYcXg5OnYn1p95W7OESIqzuzAKkDrxALDzv8PM)

![2hotOST](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/323d764f-e78c-416c-ac98-2c2ff3dd5624/28ae1fbf-4e45-4c42-9f30-ad345eb44c12?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi8zMjNkNzY0Zi1lNzhjLTQxNmMtYWM5OC0yYzJmZjNkZDU2MjQvMjhhZTFmYmYtNGU0NS00YzQyLTlmMzAtYWQzNDVlYjQ0YzEyIiwiaWF0IjoxNzE4NTk0NDkxLCJleHAiOjMzMjg5MTU0NDkxfQ.-anzw0LTXrHTg-CDTqtWdhnBR4uOJtj2kyBE2JvwsDU)

**Comment by Hundrec** [comment]
This is an urgent one.

**Comment by EliteMasterEric** [comment]
Literally unplayable, flagging this as a high priority issue.

**Comment by JackXson-Real** [comment]
lmao the high priority tag tho. Based Eric

**Comment by JVNpixels** [comment]
It runs fine for me, maybe the os is different

**Comment by Hundrec** [comment]
> It runs fine for me, maybe the os is different

Are you sure about that?

This issue has rendered all versions of the game unplayable on every OS.

**Comment by JVNpixels** [comment]
Yes, I have a screenshot proof.
![screenshot-2024-06-17-16-27-27](https://github.com/FunkinCrew/Funkin/assets/146671762/e330ad23-140d-4e09-b7a0-00ba837a9d82)
![screenshot-2024-06-17-16-28-21](https://github.com/FunkinCrew/Funkin/assets/146671762/a4903625-37c7-41bc-ba10-b5ce11fa8056)
![screenshot-2024-06-17-16-28-28](https://github.com/FunkinCrew/Funkin/assets/146671762/6afbd9fc-967e-4e20-be7f-27580f3e18f8)

**Comment by JVNpixels** [comment]
I don't understand what is happening?

**Comment by Hundrec** [comment]
Oh dear, now it's in the pause menu as well 😔

**Comment by JVNpixels** [comment]
Oh damn really? I never noticed until you said that, welp I guess more investigating, good to know tho.

**Comment by JVNpixels** [comment]
Wait, is it when you play in Story Mode? Or is it for Freeplay?

**Comment by Hundrec** [comment]
The screenshots are in the original post.

**Comment by JVNpixels** [comment]
Yeah, but we don't know if they are playing from Story Mode or Freeplay.

**Comment by Hundrec** [comment]
There are no gameplay screenshots in the post. Did you read the title of the post?

**Comment by JVNpixels** [comment]
Let me try on Story Mode and see if the Pause Menu is different, or if I can even run it.

**Comment by JVNpixels** [comment]
Well I mean, they could have recorded it, or used snip tool, or record from their phone, but yea I can see why there is no pictures.

**Comment by JVNpixels** [comment]
## It runs perfectly fine on my side, I am on the latest version (17)
![screenshot-2024-06-17-16-46-23](https://github.com/FunkinCrew/Funkin/assets/146671762/5a41be94-498d-4179-9716-61d8f69f0af9)

**Comment by Hundrec** [comment]
@JVNpixels The urgency of this bug report is a joke that everyone else is in on. 

Eric only labeled it as "high priority" because the capitalization of a single letter is so insignificant that it would be funny to call it the most pressing issue.

There aren't any performance issues related to the capital H, so you don't need to spend any more time testing it.

**Comment by JVNpixels** [comment]
oh, whoops.

**Comment by gamerbross** [comment]
![image](https://github.com/FunkinCrew/Funkin/assets/55158797/f33ffe66-f215-412a-b99e-f14e5813a144)
omg eric 😡

**Comment by JVNpixels** [comment]
ehh its fine idgf

**Comment by JVNpixels** [comment]
although srsly blazin does crash

**Comment by JackXson-Real** [comment]
Stfu guys my email is getting blown up

**Comment by Hundrec** [comment]
> although srsly blazin does crash

This is a known bug that has a workaround here: https://github.com/FunkinCrew/Funkin/issues/2559#issuecomment-2119238934

**Comment by JVNpixels** [comment]
oh alr, well now what, im just trying to think of ways to make the game better

**Comment by NotHyper-474** [comment]
> Stfu guys my email is getting blown up

Just unsubscribe from Notifications bro

**Comment by AbnormalPoof** [comment]
Glad to see that pressing issues like this are being taken care of

**Comment by Sword352** [comment]
> I don't understand what is happening?

Windows is not case sensitive when looking for files lmao

**Comment by CreamslyCream** [comment]
Guys this breaks my game!!1!!!111!1!1!!11111!1!!!!11!!!!!

**Comment by CoolDudeT** [comment]
WTF, literally unplayable.

**Comment by moxie-coder** [comment]
> > I don't understand what is happening?
> 
> Windows is not case sensitive when looking for files lmao

true lol

**Comment by moxie-coder** [comment]
![image](https://github.com/FunkinCrew/Funkin/assets/124418090/c0db076e-0b3b-47dd-9bff-8a2f6817ee0b)

**Comment by GettingTheHubNStuff** [comment]
i randomly viewed the funkin' blog and the 2025/09/19 one brought me to this page through a link and idk what i walked into
