### ISSUE TITLE
SLIGHT BUG REPORT: Tutorial bug in Freeplay

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#2840]
## Note
I have a feeling this was not added because the week is called tutorial, if that is the case then I understand.

## Describe the bug
The Tutorial in freeplay does not show the week (Tutorial / Teaching Time)

## To Reproduce
Just enter the freeplay menu and take a look at Tutorial
## Expected behavior
The expected behavior is that it is suppose to show the tutorial week.

## Screenshots/Video
![screenshot-2024-06-17-11-57-40](https://github.com/FunkinCrew/Funkin/assets/146671762/212d5c44-597a-4e14-9a0d-6dc17b7c387e)

## Desktop
 - OS:
Windows 11
 - Browser
I am playing on the Windows 11 Build but I use chrome
 - Version:
v0.4.1

**Comment by gamerbross** [comment]
i think it would be redundant to display "Tutorial" twice, and the current way these week texts work, its not possible. I hope they add this text as a font and not an image
