### ISSUE TITLE
ENHANCEMENT: New Album

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#2843]
## This is a small suggestion.

- Add the OST Expansion Album as seen in the Funkin Sound Team YouTube channel.
![Draft Idea for new Album In-Game (Enhancement Issue)](https://github.com/FunkinCrew/Funkin/assets/146671762/99c99f65-78c1-4a42-9fa6-1f0d5de92add)

**Comment by AbnormalPoof** [comment]
This was added in v0.5.0
