### ISSUE TITLE
MINOR BUG REPORT: Freeplay Capsule Title Squish

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#2845]
## Describe the bug
Sometimes out of nowhere, the Freeplay Capsule song names get squished. It usually happens when a bunch of activity happens on this state, like changing the difficulty of a song, and scrolling through the songs at the same time, and just spamming random buttons.

## To Reproduce
Just go haywire on the freeplay menu, change the difficulty, scroll through the songs, push random buttons. It should squish after a while
## Expected behavior
The expected behavior is that it is suppose to stay normal and not get squished. For some reason it does this and I have no clue why.

## Screenshots/Video
![screenshot-2024-06-17-12-55-23](https://github.com/FunkinCrew/Funkin/assets/146671762/d8d3474e-306b-49ed-b244-cb6b8d112355)
![screenshot-2024-06-17-12-48-29](https://github.com/FunkinCrew/Funkin/assets/146671762/01797db7-6f41-49c7-9e9a-bf5157bd8987)

## Desktop
 - OS:
Windows 11
 - Browser
I am on the Windows build, but I use chrome
 - Version:
v0.4.1

## Additional context

It use to happen more often in 0.3.0, but this bug seemed to occur less in newer builds like v0.4.0, and v0.4.1

**Comment by TabTray** [comment]
already reported in #2659

**Comment by BStasik** [comment]
a lot of things supposed to be changed in v0.4.1 but they wasn't.(

**Comment by Hundrec** [comment]
@BStasik 
Most of the bugs that went unfixed were just an uploading error to itch.io that has since been fixed.
This one wasn't in the changelog, so it has yet to be resolved.

**Comment by SnowyyWHY** [comment]
Same issue.
