### ISSUE TITLE
BUG REPORT: Health for BotPlay is incorrectly displayed and you can die.

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#2846]
## Describe the bug
When you are playtesting a chart with BotPlay on, it sets your health to 100%, but you can still die, miss notes, and lose health.

## A possible fix
Force enable Practice Mode and it should work.

## To Reproduce
1. Go to the Chart Editor
2. Load any song
3. Go to the Window tab
4. Open the PlayTest Properties window
5. Enable Bot play mode
6. Playtest the chart, and you should see the bug.
## Expected behavior
The health is suppose to match the actual health, you can lose health, be near death, or die while the bar stays at 100%

## Screenshots/Video
![screenshot-2024-06-17-14-54-42](https://github.com/FunkinCrew/Funkin/assets/146671762/6985acf4-7df7-4167-8cb5-bdcaef860a2a)
![screenshot-2024-06-17-14-54-38](https://github.com/FunkinCrew/Funkin/assets/146671762/23f39833-c70a-4ef8-bede-a616e3713eaf)
![screenshot-2024-06-17-14-54-33](https://github.com/FunkinCrew/Funkin/assets/146671762/b272029f-85b8-4583-911c-c971f420e308)

## Desktop
 - OS:
Windows 11
 - Browser
Chrome (I play on Windows)
 - Version:
v0.4.1

## Additional context

This may seem like a duplicate, but no one has written about this yet.

**Comment by Hundrec** [comment]
The issue OP is referencing: https://github.com/FunkinCrew/Funkin/issues/2358

Botplay mode is coded to always display max health, so I feel like this is intentional.
_Dying_ on Botplay mode might be unintentional though.

**Comment by Hundrec** [comment]
You can no longer miss in Botplay mode, so this is resolved!
