### ISSUE TITLE
Bug Report: Freeplay sorting after switching from Erect/Nightmare can trigger unusual behavior

### ISSUE THREAD

**Issue by GoombarioFan** [FunkinCrew/Funkin#2847]
## Describe the bug
Behavior while going through the sorted Freeplay options is unusual when switching from Nightmare/Erect back to Easy/Normal/Hard under specific circumstances.

## To Reproduce
**Method 1:** Only can be produced while no songs with an Erect/Nightmare difficulty are favorited
1. Enter Freeplay menu
2. Switch to Erect/Nightmare difficulty
3. Select, but DO NOT play Random
4. While on Random, sort to "#" or U-Z
5. Switch to Easy/Normal/Hard difficulty
6. Result: Favorites is shown on "#" or U-Z sorting instead (or nothing, if Favorites aren't being used)

**Method 2:** Only can be produced if no songs that begin with U-Z have an Erect/Nightmare difficulty
1. Enter Freeplay menu
2. Switch to Erect/Nightmare difficulty
3. Sort to T
4. Select, but DO NOT play Random
5. While on Random, sort to "#" or Favorites
8. Switch to Easy/Normal/Hard difficulty
9. Result: U-Z sorting is shown on either "#" or Favorites instead

**Method 3:** Only can be produced if no songs that begin with I-N have an Erect/Nightmare difficulty
1. Enter Freeplay menu
2. Switch to Erect/Nightmare difficulty
3. Select, but DO NOT play Random
4. While on Random, sort to M-N
5. Switch to Easy/Normal/Hard difficulty
6. Result: M-N sorting shows I-L sorting instead
7. Alt: Repeat these steps but starting from O-R sorting instead, resulting in I-L showing M-N sorting

**Method 4:** Only can be produced if no songs that begin with U-Z or favorited songs have an Erect/Nightmare difficulty.
1. Enter Freeplay menu
2. Sort by "#"
3. Select, but DO NOT play Random
4. Switch to Erect/Nightmare difficulty
5. Sort by either U-Z or Favorites
6. Result: "#" sorting is shown on either U-Z or Favorites

## Screenshots/Video
**Method 1:**
![d](https://github.com/FunkinCrew/Funkin/assets/80182971/c8a34ca1-e0e2-4c9b-b0d3-421fa8dcd137)

**Method 2:**
![d](https://github.com/FunkinCrew/Funkin/assets/80182971/7d70e4ff-9733-4528-a7f8-f47799ba3291)

**Method 3:**
![d](https://github.com/FunkinCrew/Funkin/assets/80182971/784d7dc1-b2dc-49d8-b124-4e6a83cf27ac)

**Method 3 Alt:**
![d](https://github.com/FunkinCrew/Funkin/assets/80182971/2e97421b-a781-414c-a82a-3f0bcf645c42)

## Desktop
 - OS: Windows 10
 - Version: 0.4.1

**Comment by Hundrec** [comment]
This one is crazy elaborate. Props to you for describing it in such great detail!

**Comment by EliteMasterEric** [comment]
Reproduced successfully. This one is kinda elaborate but the steps helped.

**Comment by GoombarioFan** [comment]
Closing since this seems to be fixed as of 0.5.0. Thanks for fixing!
