### ISSUE TITLE
Bug Report: Source Code unable to find current revision in submodule path 'assets'

### ISSUE THREAD

**Issue by NickIdk1235** [FunkinCrew/Funkin#2868]
When trying to do add the assets and art stuff in the folder with the command, it just give me this error.
And yes I did use the build from the command and I didn't download the github version.

The error says "fatal: Unable to find current revision in submodule path 'assets'"
![image](https://github.com/FunkinCrew/Funkin/assets/97841607/2ae50b61-2c73-417e-afc4-0bf2b44e2574)

- Desktop: Windows
- Version: v0.4.1

**Comment by Hundrec** [comment]
I'm not sure if this will work, but you can try this:

```
git pull --recurse-submodules
```

**Comment by NickIdk1235** [comment]
> git pull --recurse-submodules

It still gives me the error
![image](https://github.com/FunkinCrew/Funkin/assets/97841607/bcff38bf-9916-49cf-9eb7-5d00a3e540c4)

**Comment by Hundrec** [comment]
Hold on, do you have the art and assets folders in your funkin folder right now?
If they're there with all their content, try moving to the next step on the compiling guide.

**Comment by NickIdk1235** [comment]
> Hold on, do you have the art and assets folders in your funkin folder right now? If they're there with all their content, try moving to the next step on the compiling guide.

Both of the folders is empty

**Comment by Hundrec** [comment]
Have you tried deleting the empty folders and rerunning the command from the guide?

**Comment by NickIdk1235** [comment]
> Have you tried deleting the empty folders and rerunning the command from the guide?

Yes
Deleting the folder made it work. Thanks
