### ISSUE TITLE
Bug Report: The build doesn't want to build even though I downloaded lime

### ISSUE THREAD

**Issue by NickIdk1235** [FunkinCrew/Funkin#2870]
After finishing what the building guide says. I was at a error where it told me to put in 'haxelib install lime.' However, for some reason after I keep puting this command. It never let me build.

I also checked my library and it was there.
![image](https://github.com/FunkinCrew/Funkin/assets/97841607/cf4deb22-0b39-4f52-bef5-782bc3284a35)

- Desktop: Windows
- Version: v0.4.1

**Comment by Hundrec** [comment]
Strange errors like these can sometimes be solved by deleting the .haxelib folder and rerunning `hmm install`

**Comment by NickIdk1235** [comment]
That worked! Thanks
