### ISSUE TITLE
Bug Report: Cant find T

### ISSUE THREAD

**Issue by NickIdk1235** [FunkinCrew/Funkin#2872]
I know I been making a long of issues but this time it can't find T which was meant to be a postion.
![image](https://github.com/FunkinCrew/Funkin/assets/97841607/6ad7ba62-af4a-4619-b859-632683b411e5)

- Desktop: Windows
- Version: v0.4.1

**Comment by Hundrec** [comment]
Can you provide more details or console logs?

For example, did you modify any code before compiling?

**Comment by NickIdk1235** [comment]
> Can you provide more details or console logs?
> 
> For example, did you modify any code before compiling?

![image](https://github.com/FunkinCrew/Funkin/assets/97841607/0e1f6023-ff7d-4e8b-b66d-5592324425b4)

**Comment by Hundrec** [comment]
I have no idea what it could mean by "T"

Assuming you didn't edit any code, you can try deleting and reinstalling all your haxelibs (even if you have before)

**Comment by CrusherNotDrip** [comment]
> ![image](https://private-user-images.githubusercontent.com/97841607/341686313-0e1f6023-ff7d-4e8b-b66d-5592324425b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjgwOTYsIm5iZiI6MTcxODk2Nzc5NiwicGF0aCI6Ii85Nzg0MTYwNy8zNDE2ODYzMTMtMGUxZjYwMjMtZmY3ZC00ZThiLWI2NmQtNTU5MjMyNDQyNWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDExMDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhOWRmODg1ZWE2NzZhZWFiNzJlMTgzYTU4NWZjMGUxYTRkZjIxZGY4MWM1YzgyOGE5ZWM4YmQ4NzlhMjQ4MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UlwPuH5-U2RLW0EY2TETKCa_52g4drEHU_V52i8jqFU)

it looks like u have the main flixel and not the funkincrew forked one.

you might wanna install the haxelibs with `hmm install` instead

(`haxelib --global install hmm` `haxelib --global run hmm setup` to setup hmm if you haven't already.)

**Comment by NotHyper-474** [comment]
Same issue as #2333, generally gets solved by reinstalling Flixel via `hmm reinstall -f flixel`

**Comment by NotHyper-474** [comment]
Any updates on this?

**Comment by EliteMasterEric** [comment]
Read and follow the compilation instructions again, and only then create a new issue.
