### ISSUE TITLE
Bug Report: Stage Editor Layers Stay Visible When Disabled

### ISSUE THREAD

**Issue by Darkness8374939** [FunkinCrew/Funkin#2882]
## Describe the bug
(Not sure if this counts as a bug, since it is still a WIP.) The stage editor layers stay visible, even after they have been selected as not visible. 

## To Reproduce
1. Go to stage editor
2. Disable a layer
3. It will stay visible.

## Expected behavior
Whenever a layer is selected to not be shown, it should become invisible.

## Screenshots/Video
![Screenshot 2024-06-22 024019](https://github.com/FunkinCrew/Funkin/assets/97869964/809839ee-ebca-4108-b5bd-0ee9313bf9df)

## Desktop
 - OS:
  Windows
 - Version:
 0.4.1

## Additional context
The stage editor is probably still a WIP, so unsure if this is considered a bug,

**Comment by Hundrec** [comment]
I remember seeing somewhere that they're aware of the stage editor's lack of functionality. Good to report it anyway though!

**Comment by Hundrec** [comment]
Stale due to the new stage editor in 0.5.2
We can close this now!
