### ISSUE TITLE
Compiling help:  ERROR  (unknown position)        | Type not found : T

### ISSUE THREAD

**Issue by raymah-noodles** [FunkinCrew/Funkin#2884]
```
 ERROR  (unknown position)

      | Type not found : T
```
after following all the instructions i get this :( how do i fix this?, note i have wiped haxe and the repo 10 times and still have not been able to compile due to this error and 294

**Comment by Hundrec** [comment]
The same issue has been reported in #2872
The comments have some suggestions you can try there. 
Good luck!

**Comment by EliteMasterEric** [comment]
I'm going to mark this as a duplicate since I'm assuming that's what's happening here.
