### ISSUE TITLE
[BUG] Instrumentals and vocals desync when the song starts

### ISSUE THREAD

**Issue by CryptoLockedFry** [FunkinCrew/Funkin#2888]
## Describe the bug

When starting a song on the desktop version (not the website) occasionally the instrumental and vocals can de-sync. This can be fixed by pausing and unpausing the game.

## To Reproduce

Start a song on desktop until it happens

## Screenshots/Video

https://github.com/FunkinCrew/Funkin/assets/173584212/46388c3d-01e8-4654-965a-a69bd72dad42

## Desktop
 - OS:
Windows 11
 - Version:
0.4.1

**Comment by JackXson-Real** [comment]
this is fire

**Comment by CryptoLockedFry** [comment]
> this is fire

fr

**Comment by Hundrec** [comment]
This seems to be caused by poor performance.

Every time I start a song for the first time after launching the game on my laptop, there's a lag spike after "Go!" and the vocals desync.

I've developed muscle memory to restart the first song every time at this point!

**Comment by AbnormalPoof** [comment]
This issue is addressed in PR #2706

**Comment by Benefonde** [comment]
> This seems to be caused by poor performance.
> 
> Every time I start a song for the first time after launching the game on my laptop, there's a lag spike after "Go!" and the vocals desync.
> 
> I've developed muscle memory to restart the first song every time at this point!

I literally also just pause unpause right as a song starts

**Comment by CryptoLockedFry** [comment]
> This seems to be caused by poor performance.
> 
> Every time I start a song for the first time after launching the game on my laptop, there's a lag spike after "Go!" and the vocals desync.
> 
> I've developed muscle memory to restart the first song every time at this point!

I don't think it's poor performance, it happens on my laptop with an i7 and a 4070 even if I'm running nothing else in the background

**Comment by EliteMasterEric** [comment]
Should have been resolved in v0.5.
