### ISSUE TITLE
Bug Report: pico's icon loaded like this randomly

### ISSUE THREAD

**Issue by CryptoLockedFry** [FunkinCrew/Funkin#2889]
## Describe the bug
picos icon was not the right icon
## To Reproduce
no idea it just happened
## Screenshots/Video
![Screenshot 2024-06-22 191618](https://github.com/FunkinCrew/Funkin/assets/173584212/21fc2380-b307-4200-8ad9-e05467f76320)

## Desktop
 - OS:
Windows 11
 -Browser
Chrome
 - Version:
0.4.1

**Comment by NotHyper-474** [comment]
You probably pressed the Debug key that changes the player icon (iirc it's 9)

**Comment by JackXson-Real** [comment]
You pressed 9 dummy

**Comment by CryptoLockedFry** [comment]
> You probably pressed the Debug key that changes the player icon (iirc it's 9)

idk how i didn't know this before lmao
