### ISSUE TITLE
Bug Report: [my game crash]

### ISSUE THREAD

**Issue by Niox124** [FunkinCrew/Funkin#2896]
i have no idear how to reproduce it but here is the file 
the game wase supose to keep going but it dont 
-->

## Desktop
 - OS:
 
 - Version:
 

## Additional context

https://github.com/FunkinCrew/Funkin/assets/173632089/20910ee8-5baa-4114-8b2c-9cf7d04740a2

**Comment by Niox124** [comment]
sorry idk much

**Comment by Niox124** [comment]
the file is https://drive.google.com/file/d/1Kvqo5I750qBwym8H9ONGDOF1v1qQls3g/view?usp=drive_link

**Comment by Hundrec** [comment]
Is this a modified build? 
If so, how?

(The Google Drive file is inaccessible)

**Comment by Niox124** [comment]
no it not and wait i am going to make it accessible

**Comment by Niox124** [comment]
https://drive.google.com/file/d/1Kvqo5I750qBwym8H9ONGDOF1v1qQls3g/view?usp=drive_link

**Comment by Niox124** [comment]
@Hundrec welp now i think it up and if it still not working we coud just share it by  e-mails

**Comment by ninjamuffin99** [comment]
this might be a duplicate of the other mac opening bug!

**Comment by Niox124** [comment]
alr
