### ISSUE TITLE
how do i change the Characters scale/ how do i fix the Characters scale

### ISSUE THREAD

**Issue by thegamenig** [FunkinCrew/Funkin#2899]
![image](https://github.com/FunkinCrew/Funkin/assets/142361218/fd5af5ff-25cf-4101-9f41-d911331c5879)

**Comment by Beelijah** [comment]
are u 100% sure thats not a modded client?

**Comment by Hundrec** [comment]
> are u 100% sure thats not a modded client?

Aside from a new character and a missing icon, this looks unmodified to me.
