### ISSUE TITLE
Sprite doesn't render properly

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#29]
![image](https://user-images.githubusercontent.com/45773590/101224583-17638f00-36a0-11eb-9013-e7f43c8ae650.png)
I don't have any steps to reproduce it. Sometimes it returns to normal, sometimes it bugs like in the picture.

**Comment by ninjamuffin99** [comment]
Imma use this one as the main thing for duplicate issues!

**Comment by kem4li** [comment]
I almost forgot about this issue. Problem happened when using the NG version. I think the stage was either stage 1 or tutorial.
