### ISSUE TITLE
FIX The Glitched textures

### ISSUE THREAD

**Issue by valentin657900** [FunkinCrew/Funkin#291]
EVERYTIME i Play FNF Some character textures are glithed Please fix it                                                                                                                            I will send you a photo of how they look   
![image](https://user-images.githubusercontent.com/78165519/106170741-8674d580-616f-11eb-94e7-9e9f6fce0c24.png)

**Comment by valentin657900** [comment]
that shit looks like it was classificated by the CIA

**Comment by regulad** [comment]
I was not able to reproduce. Try clearing your cache or trying a different browser.

**Comment by ninjamuffin99** [comment]
known issue
