### ISSUE TITLE
Bug Report: [The game gives me an error]

### ISSUE THREAD

**Issue by JHAM25** [FunkinCrew/Funkin#2910]
## Describe the bug

the game gives an error when starting

## To Reproduce

When you press Enter at the beginning it stays there and does not go to the menu and when you press Enter again it throws the error

## Screenshots/Video

https://github.com/FunkinCrew/Funkin/assets/108441263/cc9dca99-564e-4fa1-96ae-df2a02fa2854

## Desktop
 - OS: Windows 10
 
 - Version: 0.4.1

**Comment by Hundrec** [comment]
Wow.

This seems like a performance issue.

What are your computer's specifications?

**Comment by JHAM25** [comment]
> Wow.
> 
> This seems like a performance issue.
> 
> What are your computer's specifications?

![image](https://github.com/FunkinCrew/Funkin/assets/108441263/716d5f0a-dddc-4507-b6b4-1bfc7cf72987)

**Comment by Hundrec** [comment]
Thanks for the info. 

This is definitely a performance issue due to an old CPU and low RAM. 

You should try to play the game using a newer device, if possible.
