### ISSUE TITLE
Bug report: Raiting change on highscore based

### ISSUE THREAD

**Issue by woksio1** [FunkinCrew/Funkin#2918]
Okay so picture this. I had a Perfect rating on Fresh Nightmare when i got from 100% to 99%. 
This is actually caused by highscore. 
So when you got 100% and then you play the same song and then you look and you have 99%, because rating changes when you have some more score than previoulsly. 

Please fix this to be % based, not to be score based.

OS: Windows 11

Version: 0.4.0

Game type: .exe

**Comment by NotHyper-474** [comment]
Isn't this already fixed in v0.4.1?

**Comment by woksio1** [comment]
Uhhhh... Oh so I'm gonna download ver 0.4.1

**Comment by woksio1** [comment]
I'm not closing this to check if it actually is fixed

**Comment by woksio1** [comment]
Okay uhh it's fixed in 0.4.1 so closed
