### ISSUE TITLE
Bug Report: background text in results screen goes off background if you changed screen size

### ISSUE THREAD

**Issue by 7oltan** [FunkinCrew/Funkin#2922]
## Describe the bug
as stated in title

## Screenshots/Video
![image](https://github.com/FunkinCrew/Funkin/assets/87986834/2d2def50-01d4-4d6b-81c7-591ccd38f474)
![image](https://github.com/FunkinCrew/Funkin/assets/87986834/fd179547-0d21-45c8-a6d4-10d8adc61b02)

## Additional context
make the bg bigger??

**Comment by Hundrec** [comment]
This issue was reported in #2694

**Comment by 7oltan** [comment]
> This issue was reported in #2694

Oh shit lemme close this
