### ISSUE TITLE
play animation event didn't play 

### ISSUE THREAD

**Issue by ega445** [FunkinCrew/Funkin#2923]
my character didn't play the animation  
https://github.com/FunkinCrew/Funkin/assets/173577618/9c49f97f-9e7b-49b0-ac30-a3b1e791db28

os:
window 10
website:
chrome
version:0.4.1

**Comment by Hundrec** [comment]
Animations usually don't work for me if I put in the wrong name.

You can try putting "ChibiGF-V2" as the target, but that might not work.

What most likely _will_ work is putting "bf" and "dad" as the targets. Lemme know if it does!

**Comment by ega445** [comment]
huh it work but why can't use the custom target?

**Comment by Hundrec** [comment]
I think it's coded that way for now. I don't think I've seen anything other than "bf" and "dad" work, but they might (like pico)

**Comment by ega445** [comment]
but what about gf?

**Comment by Hundrec** [comment]
Whoops, I forgot about her
"gf" also works

**Comment by ega445** [comment]
ohh ok thanks
