### ISSUE TITLE
Bug Report: [Im having this problem after installing Hmm

### ISSUE THREAD

**Issue by Reyreychan** [FunkinCrew/Funkin#2928]
so im tryin to install the source like the Compiling one
and the problem is like this

-->
../src/lime/system/ThreadPool.hx:25: characters 26-46 : Expected TypeDefinition but got {name: _Event_Dynamic_Void, params: [{name: T}], pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46), fields: [{name: canceled, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Whether the event was canceled during the previous dispatch
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:31: characters 2-42), access: [APublic], kind: FProp(default,null,TPath({name: <...>, params: <...>, pos: <...>, pack: <...>}),null), meta: [], name_pos: #pos(../src/lime/app/Event.hx:31: characters 13-21)},{name: __repeat, doc: null, pos: #pos(../src/lime/app/Event.hx:34: characters 29-61), access: [APublic], kind: FVar(TPath({name: <...>, params: <...>, pos: <...>, pack: <...>}),null), meta: [{name: :noCompletion, params: [], pos: #pos(../src/lime/app/Event.hx:34: characters 2-16)},{name: :dox, params: [<...>], pos: #pos(../src/lime/app/Event.hx:34: characters 17-22)}], name_pos: #pos(../src/lime/app/Event.hx:34: characters 40-48)},{name: __priorities, doc: null, pos: #pos(../src/lime/app/Event.hx:36: characters 17-53), access: [APrivate], kind: FVar(TPath({name: <...>, params: <...>, pos: <...>, pack: <...>}),null), meta: [{name: :noCompletion, params: [], pos: #pos(../src/lime/app/Event.hx:36: characters 2-16)}], name_pos: #pos(../src/lime/app/Event.hx:36: characters 29-41)},{name: new, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Creates a new Event instance
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:41: lines 41-49), access: [APublic], kind: FFun({ret: null, params: [], expr: {pos: <...>, expr: <...>}, args: []}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:41: characters 18-21)},{name: add, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Adds a new event listener
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @param  listener        A callback that matches the signature of the event
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @param  once    Whether to receive an event dispatch only once, or each time it is fired
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @param  priority        The priority for this listener, a higher priority will be dispatched sooner
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:57: lines 57-75), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [<...>,<...>,<...>]}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:57: characters 18-21)},{name: cancel, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Marks the event as canceled, and stops the current event dispatch
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:80: lines 80-83), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: []}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:80: characters 18-24)},{name: has, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Checks whether a callback is a listener to this event
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @param  listener        A callback that matches the signature of the event
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @return Whether the callback is a listener
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:126: lines 126-136), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [<...>]}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:126: characters 18-21)},{name: remove, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Removes an event listener
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @param  listener        A callback that matches the signature of the event
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:142: lines 142-157), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [<...>]}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:142: characters 18-24)},{name: removeAll, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Removes all event listeners
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:162: lines 162-171), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: []}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:162: characters 18-27)},{name: __listeners, pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46), access: [APublic], kind: FVar(TPath({name: <...>, params: <...>, pack: <...>}),null)},{name: dispatch, pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [<...>]})}], pack: [lime,app], kind: TDClass(null,null,null,null,null), meta: [{name: :dox, params: [{pos: #pos(../src/lime/_internal/macros/EventMacro.hx:148: characters 35-39), expr: EConst(<...>)}], pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46)},{name: :noCompletion, pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46)},{name: :fileXml, params: [{pos: #pos(../src/lime/_internal/macros/EventMacro.hx:153: characters 48-69), expr: EConst(<...>)}], pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46)},{name: :noDebug, pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46)}]} (see dump/decoding_error.txt for details)

what should i do?

[message.txt](https://github.com/user-attachments/files/16026274/message.txt)

## Desktop
 - Windows: -

 
 - Browser
 
 - Version:
 

## Additional context

[message.txt](https://github.com/user-attachments/files/16026256/message.txt)

**Comment by Hundrec** [comment]
Which command did you run for this error to occur?

Your best bet would be to delete `hmm.json` and the `.haxelib` folder, if you have either.

Then, make sure you follow the steps on the compiling guide very closely.
If you still run into this (or any other) error, reply here and I'll try my best to help.

**Comment by Reyreychan** [comment]
Beforely, I'm installing the haxelib by using lime test windows. After that this problem comin
![Screenshot_2](https://github.com/FunkinCrew/Funkin/assets/174096806/0eba1ebe-92fb-43d2-a81a-6a12c870dfd7)
So, I'm trying to do hmm cuz I think it can fix all haxelib and tgis prob come

**Comment by Hundrec** [comment]
`lime test windows` is the final step on the compiling guide. It tells your computer to attempt to compile and open the game. 

If you haven't, please follow each step and run every command listed in the [compiling guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/COMPILING.md) after deleting all of your repository's files. 

Ensure that you are in the directory you want the game's source code to be in when you run these commands.

Let me know if you have any questions at any step.

**Comment by Reyreychan** [comment]
Should I delete all of the haxelib file first to start from beginning, how to delete all haxelib?

**Comment by Hundrec** [comment]
To delete all haxelibs, delete the  folder named `.haxelib`.

However, I strongly recommend that you delete all other files and folders located in the same directory as the `.haxelib` folder. This will provide you with a clean slate to follow the compiling guide from.

**Comment by Reyreychan** [comment]
done, but how to fix this
![Screenshot_3](https://github.com/FunkinCrew/Funkin/assets/174096806/f6aaeada-da5b-4b90-8e8b-bdb1f870b65f)

**Comment by Hundrec** [comment]
It looks like you didn't input exactly what the compiling guide instructed you to.

Try deleting all the files in Funkin-main and restarting from Step 1.

**Comment by Reyreychan** [comment]
im already delete the first funikin main, and this was the new folder

**Comment by Hundrec** [comment]
When a command fails to run, the console provides feedback to let you know. 

Try picking up from the step where you install hmm

**Comment by Reyreychan** [comment]
../src/lime/system/ThreadPool.hx:25: characters 26-46 : Expected TypeDefinition but got {name: _Event_Dynamic_Void, params: [{name: T}], pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46), fields: [{name: canceled, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Whether the event was canceled during the previous dispatch
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:31: characters 2-42), access: [APublic], kind: FProp(default,null,TPath({name: <...>, params: <...>, pos: <...>, pack: <...>}),null), meta: [], name_pos: #pos(../src/lime/app/Event.hx:31: characters 13-21)},{name: __repeat, doc: null, pos: #pos(../src/lime/app/Event.hx:34: characters 29-61), access: [APublic], kind: FVar(TPath({name: <...>, params: <...>, pos: <...>, pack: <...>}),null), meta: [{name: :noCompletion, params: [], pos: #pos(../src/lime/app/Event.hx:34: characters 2-16)},{name: :dox, params: [<...>], pos: #pos(../src/lime/app/Event.hx:34: characters 17-22)}], name_pos: #pos(../src/lime/app/Event.hx:34: characters 40-48)},{name: __priorities, doc: null, pos: #pos(../src/lime/app/Event.hx:36: characters 17-53), access: [APrivate], kind: FVar(TPath({name: <...>, params: <...>, pos: <...>, pack: <...>}),null), meta: [{name: :noCompletion, params: [], pos: #pos(../src/lime/app/Event.hx:36: characters 2-16)}], name_pos: #pos(../src/lime/app/Event.hx:36: characters 29-41)},{name: new, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Creates a new Event instance
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:41: lines 41-49), access: [APublic], kind: FFun({ret: null, params: [], expr: {pos: <...>, expr: <...>}, args: []}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:41: characters 18-21)},{name: add, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Adds a new event listener
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @param  listener        A callback that matches the signature of the event
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @param  once    Whether to receive an event dispatch only once, or each time it is fired
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @param  priority        The priority for this listener, a higher priority will be dispatched sooner
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:57: lines 57-75), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [<...>,<...>,<...>]}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:57: characters 18-21)},{name: cancel, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Marks the event as canceled, and stops the current event dispatch
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:80: lines 80-83), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: []}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:80: characters 18-24)},{name: has, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Checks whether a callback is a listener to this event
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @param  listener        A callback that matches the signature of the event
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @return Whether the callback is a listener
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:126: lines 126-136), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [<...>]}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:126: characters 18-21)},{name: remove, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Removes an event listener
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             @param  listener        A callback that matches the signature of the event
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:142: lines 142-157), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [<...>]}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:142: characters 18-24)},{name: removeAll, doc:
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...             Removes all event listeners
../src/lime/system/ThreadPool.hx:25: characters 26-46 : ...     , pos: #pos(../src/lime/app/Event.hx:162: lines 162-171), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: []}), meta: [], name_pos: #pos(../src/lime/app/Event.hx:162: characters 18-27)},{name: __listeners, pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46), access: [APublic], kind: FVar(TPath({name: <...>, params: <...>, pack: <...>}),null)},{name: dispatch, pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [<...>]})}], pack: [lime,app], kind: TDClass(null,null,null,null,null), meta: [{name: :dox, params: [{pos: #pos(../src/lime/_internal/macros/EventMacro.hx:148: characters 35-39), expr: EConst(<...>)}], pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46)},{name: :noCompletion, pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46)},{name: :fileXml, params: [{pos: #pos(../src/lime/_internal/macros/EventMacro.hx:153: characters 48-69), expr: EConst(<...>)}], pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46)},{name: :noDebug, pos: #pos(../src/lime/system/ThreadPool.hx:25: characters 26-46)}]} (see dump/decoding_error.txt for details)

when im setting the haxelib run lime setup this text was pop up

**Comment by Hundrec** [comment]
Can you show a screenshot of the console including the command you ran to get this error?

**Comment by Reyreychan** [comment]
![Screenshot_4](https://github.com/FunkinCrew/Funkin/assets/174096806/a1cb3a51-c9de-4bb4-a60c-277576b903b0)
heres the screenshoot, im already follow the steps

**Comment by Hundrec** [comment]
Can you screenshot what the inside of your .haxelib folder looks like?

**Comment by Reyreychan** [comment]
![Screenshot_5](https://github.com/FunkinCrew/Funkin/assets/174096806/0a5fa86f-d87a-456f-ad65-549fc003ac74)
here

**Comment by Hundrec** [comment]
Now can you screenshot the contents of the parent folder? (the one named funkin)

**Comment by Reyreychan** [comment]
![Uploading Screenshot_6.png…]()

**Comment by Reyreychan** [comment]
![Screenshot_6](https://github.com/FunkinCrew/Funkin/assets/174096806/bb6f62ee-7077-4267-9aa4-7dd542d8d656)
here

**Comment by Hundrec** [comment]
Thanks for the screenshots, the directories look fine.

I'm not sure what could be causing the issue, but reinstalling [Haxe 4.3.4](https://haxe.org/download/) might lead to a different result on your next attempt.
Make sure [git](https://git-scm.com/downloads) is installed as well.

Let me know how it goes!

**Comment by Reyreychan** [comment]
![Screenshot_7](https://github.com/FunkinCrew/Funkin/assets/174096806/7a5f5f80-8381-4693-8a28-7d59ac22c269)
im tryin to lime test, how to fix it?

**Comment by Hundrec** [comment]
Did you edit any of the source code? 

Regardless, try running `lime rebuild windows` before running `lime test windows`

**Comment by Reyreychan** [comment]
no, imnt change anything

**Comment by Reyreychan** [comment]
its still same after im lime rebuild windows

**Comment by Hundrec** [comment]
Try running `hmm reinstall -f hxcodec`
Then run `lime test windows -clean`

**Comment by Reyreychan** [comment]
sheesh bro tysm 
![Uploading Screenshot_8.png…]()

**Comment by Reyreychan** [comment]
sheeesh bro tysm
![Screenshot_8](https://github.com/FunkinCrew/Funkin/assets/174096806/214ffbc1-7765-4e6a-b01b-66798a01b1a2)

**Comment by Hundrec** [comment]
Hooray! Glad it worked out :D

**Comment by Reyreychan** [comment]
And no problem with all, no Broken at weekend and etc ty
