### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by lauyc-c** [FunkinCrew/Funkin#293]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
V.0.2.6
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Whenever I begin any song, either from story mode or freeplay.
## Please describe your issue. Provide extensive detail and images if possibe.
Every time I play any song (except for those in Weeks 4 and 5), the Boyfriend's body was always clipped out unless I press a note.
![screenshot_fnfbug_v 0 2 6](https://user-images.githubusercontent.com/77763953/106336092-1147f400-6286-11eb-911c-fd86d5e7a358.png)

**Comment by StreamyGuy** [comment]
Update: Nevermind, I just troubleshot it by clearing cookies in my browser, and the animations loaded fine.

**Comment by regulad** [comment]
Could you close this issue?
