### ISSUE TITLE
Mods adding options no longer work

### ISSUE THREAD

**Issue by AnniIsHere** [FunkinCrew/Funkin#2930]
Whenever I launch the game with a mod that add something in the options menu (such as the Forever engine Hud mod gamebanana.com/mods/511242) I get this error :
![optionull](https://github.com/FunkinCrew/Funkin/assets/147985030/9c95fab9-6c28-4a6e-9c64-c7c569bb21a0)
After launching the game like this and going into the options menu, I get this error:
![optionull2](https://github.com/FunkinCrew/Funkin/assets/147985030/f5597b45-7737-4045-8b87-4622c8cf217a)
There are then none of the extra options added by the mod in the preferences menu.
I'm playing on the 4.1 windows build. I don't think this was an issue in 4.0 and it certainly wasn't before then.

**Comment by Hundrec** [comment]
Just tested the ForeverEngine HUD mod on 0.4.1 and ran into the same error.

Also tested it on 0.4.0 and it worked fine.

This means that 0.4.1 changed something the mod script relied on to implement options.

And I think this is the one that did it: https://github.com/FunkinCrew/Funkin/pull/2451

**Comment by NotHyper-474** [comment]
> Just tested the ForeverEngine HUD mod on 0.4.1 and ran into the same error.
> 
> Also tested it on 0.4.0 and it worked fine.
> 
> This means that 0.4.1 changed something the mod script relied on to implement options.
> 
> And I think this is the one that did it: #2451

Yup, they even mentioned that change would break existing mods.

**Comment by AbnormalPoof** [comment]
Remove the `PageName` import
`import funkin.ui.options.PageName;`

Change this
`var prefs = event.targetState.pages.get(PageName.Preferences);`
To
`var prefs = event.targetState.pages.get("preferences");`

**Comment by AnniIsHere** [comment]
> Remove the `PageName` import `import funkin.ui.options.PageName;`
> 
> Change this `var prefs = event.targetState.pages.get(PageName.Preferences);` To `var prefs = event.targetState.pages.get("preferences");`

I found the PageName import, but I did not find any line similar to the second one shown here in the mod script

**Comment by AnniIsHere** [comment]
I guess now it's up to the modders to update their mods then
