### ISSUE TITLE
Fnf

### ISSUE THREAD

**Issue by Kingkhalil990** [FunkinCrew/Funkin#2931]

**Comment by Beelijah** [comment]
This isn't an issue.

**Comment by Hundrec** [comment]
> This isn't an issue.

I think he's trying to say _the game_ is the issue 😥

**Comment by NotHyper-474** [comment]
> > This isn't an issue.
> 
> I think he's trying to say _the game_ is the issue 😥

It is tho, this game killed my family! 😡

**Comment by Reyreychan** [comment]
What the sigma

**Comment by CrusherNotDrip** [comment]
> > > This isn't an issue.
> > 
> > 
> > I think he's trying to say _the game_ is the issue 😥
> 
> It is tho, this game killed my family! 😡

oh yea u think thats bad

fnf killed ME!

**Comment by JVNpixels** [comment]
oh no guys fnf week 8 is gonna get us!!!

**Comment by NewCs386148** [comment]
> oh no guys fnf week 8 is gonna get us!!!

Don't worry, they'll never have the time to finish week 8 when they're busy fixing high priority major bugs like tankman's icon missing a pixel and 2hot having capital "h" in freeplay. Looks like we're in the clear for now.

**Comment by Hundrec** [comment]
> > oh no guys fnf week 8 is gonna get us!!!
> 
> 
> 
> Don't worry, they'll never have the time to finish week 8 when they're busy fixing high priority major bugs like tankman's icon missing a pixel and 2hot having capital "h" in freeplay. Looks like we're in the clear for now.

Fnf

**Comment by CrusherNotDrip** [comment]
> > > oh no guys fnf week 8 is gonna get us!!!
> > 
> > 
> > 
> > Don't worry, they'll never have the time to finish week 8 when they're busy fixing high priority major bugs like tankman's icon missing a pixel and 2hot having capital "h" in freeplay. Looks like we're in the clear for now.
> 
> Fnf

stop saying the magic word they gonna eat us

**Comment by TabTray** [comment]
> oh no guys fnf week 8 is gonna get us!!!

I Called Boyfriend FNF at 3 AM!! (NOT CLICKBAIT) (GONE WRONG) (DO NOT ATTEMPT)

**Comment by Beelijah** [comment]
goo goo gaa gaa
