### ISSUE TITLE
[OPTIMIZATION]: Console Flooding

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#2936]
## Describe the issue

**When the user is on a compiled build of the game, there are many functions that the game traces, for example, the bopper function traces the DanceLeft and DanceRight animations, and when you miss, the console traces penalty score, this usually makes my game lag and if not, other people as well, if these traces were removed then it could even possibly improve optimization. If these functions are needed to be treced I understand, but I feel like the dance animations are unnecessary to trace, same with a few other traces.**
## To Reproduce

Just play a song, or open the game and you can see the console flooding with major amounts of tracing. It starts lagging on low end devices (like mine) and this is most likely the problem. I also did some testing and removed **some** of the traces, my game ran smoother and faster.
## Expected behavior

Nothing is really wrong, but just a bug/optimization report and enhancement feature.

## Screenshots/Video

![Console Flood (1)](https://github.com/FunkinCrew/Funkin/assets/146671762/1ec2cd3e-7ca6-4aa5-8046-704ddd73a8c8)
![Console Flood (2)](https://github.com/FunkinCrew/Funkin/assets/146671762/759928e0-28f6-4a68-a321-2aec08f4b29a)
![Freeplay 29 FPS](https://github.com/FunkinCrew/Funkin/assets/146671762/99a55622-4836-4b5c-b976-194a0dbd8aa5)

## Desktop
 - OS:
 Windows 11 Home
 - Browser
 Chrome
 - Version:
v0.4.1 (Windows)

## Additional context

This really frustrates me when I try to play Friday Night Funkin' and I can't even run the game smoothly, and I can't really upgrade my device at the moment until for like a couple of months, and it will also make the game more optimized in general.

**Comment by NotHyper-474** [comment]
Seems like they plan on doing that considering the branch [bugfix/no-traces-on-release](https://github.com/FunkinCrew/Funkin/tree/bugfix/no-traces-on-release) exists

**Comment by JVNpixels** [comment]
Alright then, this will be closed.
