### ISSUE TITLE
Change Script File Extension

### ISSUE THREAD

**Issue by lemz1** [FunkinCrew/Funkin#2940]
I would suggest changing the script file extension from .hxc to .hx, because it would ensure that code formatting is done. The haxe formatter doesn't recognize .hxc as Haxe, which is annoying.
Maybe I could go in the settings and do something about, but I think it is way better to just change the extensions.
That way the setup for vscode is less complicated.

**Comment by tposejank** [comment]
You can change the language vs code interprets the code on the bottom right of the VSCode window. Instead of "Plaintext" you can choose any language (haxe in this case)

**Comment by moxie-coder** [comment]
> You can change the language vs code interprets the code on the bottom right of the VSCode window. Instead of "Plaintext" you can choose any language (haxe in this case)

yeah I do it all the time, it’s not too hard

**Comment by lemz1** [comment]
i did that, but it doesnt format the code.

**Comment by tposejank** [comment]
Press F1, then Format Document. There may be extensions which could do it for you too

**Comment by lemz1** [comment]
I compmetely forgot about manually formatting. Still kinda annoying, but I guess its better than nothing
