### ISSUE TITLE
Bug Report: Two Daddy Dearest Vocal Tracks for Dadbattle Erect

### ISSUE THREAD

**Issue by Darkness8374939** [FunkinCrew/Funkin#2947]
## Describe the bug
(Not an in game bug and not on the github.) In the song files of Dadbattle. There are two duplicates for the Erect vocals of Daddy Dearest. The first one is titled “Voices-dad-erect.ogg”. The second one is titled “Voices-erect-dad.ogg”.

## To Reproduce
Go to the game files, go to assets, songs, and then the Dadbattle folder.

## Expected behavior
There should only be one Daddy Dearest vocal track the Erect remix of Dadbattle.

## Desktop
 - OS:
 Windows
 - Version:
 0.4.1

## Additional context
Doesn’t effect gameplay.

**Comment by Hundrec** [comment]
I've started a pull request that deletes these five duplicate files:

![image](https://github.com/FunkinCrew/Funkin/assets/170126004/bb3d67e7-f3b7-4a3e-9548-38c04a0619cc)

**Comment by Darkness8374939** [comment]
Oh, W

**Comment by bakedroyal** [comment]
![Breakfast1](https://github.com/FunkinCrew/Funkin/assets/160797203/80b57ab1-db04-4ff7-adfb-40908556190c)
![Breakfast2](https://github.com/FunkinCrew/Funkin/assets/160797203/4234ff53-277e-4b63-96f2-89953a9e44cb)
Theres also a useless copy of Breakfast in assets/shared/music
