### ISSUE TITLE
Enhancement: Update the Linux Binaries on itch.io

### ISSUE THREAD

**Issue by Twig6943** [FunkinCrew/Funkin#2950]
## What is your suggestion, and why should it be implemented?
Please compile the latest build of fnf for linux and upload it to itch.io

**Comment by Twig6943** [comment]
Last time I checked the linux build was from 2021 turns out its been updated. Mb yall

**Comment by NotHyper-474** [comment]
Tbf they still haven't updated it from 0.4.0 to 0.4.1

**Comment by Twig6943** [comment]
I didn't know about that. Reopening the issue

**Comment by Twig6943** [comment]
still waiting

**Comment by NotHyper-474** [comment]
Yep

**Comment by Twig6943** [comment]
@NotHyper-474 ur a real one <3

**Comment by NotHyper-474** [comment]
Also they just recently updated it on [Itch.io](https://ninja-muffin24.itch.io/funkin) so I think this can be closed.

**Comment by Twig6943** [comment]
![image](https://github.com/user-attachments/assets/3ca4b5ad-84a0-4c32-b479-e9abbdea826b)

**Comment by Twig6943** [comment]
@NotHyper-474 's binaries
![image](https://github.com/user-attachments/assets/7707b336-96ef-4a73-891c-280822e47de8)
