### ISSUE TITLE
Bug Report: Incorrect % Bug is Back

### ISSUE THREAD

**Issue by bakedroyal** [FunkinCrew/Funkin#2951]
## Describe the bug

When I got a high score on a song while getting a lower percent, that lower perfect will still be saved even if I had a higher one to start. Bug will not happen if I get a lower rank than I have.
Also: if you get a higher percent at this point, that higher percent will save even if you dont get a high score.
## To Reproduce

Get a lower perfect but high score, that lower percent will save.
## Expected behavior

This issue was supposed to be fixed in 0.4.1 but is only partially fixed.
## Screenshots/Video

![Capture](https://github.com/FunkinCrew/Funkin/assets/160797203/5af2ac40-effc-43b6-ae22-12db4ffc4e98)
Here, this 98% was overwritten with a 96% after getting a high score.

## Desktop
 - OS: Windows 10
 
 - Browser: Desktop version
 
 - Version: 0.4.1
 

## Additional context

Originally reported: https://github.com/FunkinCrew/Funkin/issues/2686

**Comment by NotHyper-474** [comment]
Isn't this now #2821?

**Comment by bakedroyal** [comment]
> Isn't this now #2821?

ah thank you
