### ISSUE TITLE
Bug Report: Death animation override (Weekend 1)

### ISSUE THREAD

**Issue by Beelijah** [FunkinCrew/Funkin#2952]
## Is this a dupe?
Kinda, like [this issue.](https://github.com/FunkinCrew/Funkin/issues/26804)
However, its not fixed.

## Describe the bug
When dying during an animation, the animation overrides the death animation, and the death music does not play.

## To Reproduce
Go into 2Hot, and right before the can explodes, press R. Pressing R will kill you during Pico's load animation, where the glitch occurs.

## Expected behavior
You should die regularly, without the animation override, and with the music still playing.

## Screenshots/Video
[a youtube video](https://youtu.be/2kEBT6qV46k)

## Desktop
 - OS: Windows 11
 
- Browser: Microsoft Edge
 
- Version: 0.4.1
 
## Additional context
im in a sub race against my sister pls sub

**Comment by Hundrec** [comment]
This should be fixed by #2891

**Comment by SnowyyWHY** [comment]
still broken for me

**Comment by Beelijah** [comment]
same snowy

**Comment by anysad** [comment]
> still broken for me

It is because the pull request I have submitted to fix this issue has not been merged yet, and hasn't been fully implemented into the game. If if gets merged until the update, expect it to be fixed soon

**Comment by Hundrec** [comment]
This is fixed and can be closed!

**Comment by Beelijah** [comment]
ok dope
