### ISSUE TITLE
Enhancement: This is quite the ask, but for charting it would be pretty skibidi if we got a speakers variant of Bf and Pico as well as a playable Gf.

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#2953]
## What is your suggestion, and why should it be implemented?
You read the title. I'm just asking for a straight up added couple characters, even if they wouldn't be used in  the actual game. I 100%, fully expect a no, but I had to try. Please bro, Bf holding Gf just isn't cutting it.

**Comment by JackXson-Real** [comment]
"skibidi" in title, automatically rejected.

**Comment by moxie-coder** [comment]
> "skibidi" in title, automatically rejected.

agreed

**Comment by Average-FNF-Modder** [comment]
> "skibidi" in title, automatically rejected.

God forbid I felt like being goofy to match the craziness of the request.

**Comment by JackXson-Real** [comment]
> > "skibidi" in title, automatically rejected.
> 
> God forbid I felt like being goofy to match the craziness of the request.

If the request is crazy enough to require the use of the word “skibidi” then you probably should not even make the request lol

**Comment by Average-FNF-Modder** [comment]
> > > "skibidi" in title, automatically rejected.
> > 
> > 
> > God forbid I felt like being goofy to match the craziness of the request.
> 
> If the request is crazy enough to require the use of the word “skibidi” then you probably should not even make the request lol

I might as well try. If I'm going to go down then it's gonna be with me swingin'

**Comment by EliteMasterEric** [comment]
Just make them yourself, you have a pen.

**Comment by Average-FNF-Modder** [comment]
> Just make them yourself, you have a pen.

I promise you the feeling of making charts with base game assets is a euphoric experience, PLUS I want to make charts people can pop in and play with only the fnfc file, and you can't add characters to an fnfc file.

**Comment by Hundrec** [comment]
I'm pretty sure Eric is telling you to draw and animate the characters yourself

**Comment by Average-FNF-Modder** [comment]
> I'm pretty sure Eric is telling you to draw and animate the characters yourself

Yea but I'm saying that 
A: having things in base game style (Not modded) feels really cool when you can still make it good and
B: If I make it myself it can't all fit within' an fnfc. file like I want it too because I'll have to get people to download that and use the buggy base game mod system (I can't even get a character to load up myself) to play my chart

Also C: I can't draw lmao

**Comment by biomseed** [comment]
> Just make them yourself, you have a pen.

This can be said for ANY feature that involves art
