### ISSUE TITLE
Bug Report: The Bug Report Template Is Literally Unusable, You Forgot One Colon Next To "Browser"

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#2958]
## Describe the bug

When you go to create a new bug, you will be shocked and appalled upon noticing that you have to place the colon next to browser used YOURSELF, because the devs simply **FORGOT TO PUT IT THERE!** This is an outrage.
## To Reproduce

Open a new bug template and pray you don't cry upon seeing it.
## Expected behavior

I expected there to be a _goddamn **COLON**_
## Screenshots/Video

![Omg bro](https://github.com/FunkinCrew/Funkin/assets/157259571/264c7d04-ab5e-4758-ba04-0008d86d12db)
![Literally unusable](https://github.com/FunkinCrew/Funkin/assets/157259571/8b2d3448-b911-4ce3-bfe1-044189f2371d)

## Desktop
 - OS: Doesn't matter
 
 - Browser <-- You really expect us to type this colon out ourselves??
 
 - Version: N SLASH A dawg

**Comment by Hundrec** [comment]
Resolved by awesome new templates!

**Comment by Average-FNF-Modder** [comment]
Lovely.
