### ISSUE TITLE
Bug Report: gfSticker3.png doesn't have a light purple outline

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#2960]
Hello! I wanted to report a texture bug (not sure if this is a bug but it looks like it)

 What is wrong with the texture?
![gfSticker3](https://github.com/FunkinCrew/Funkin/assets/134156720/ba90f733-d42f-44a8-adcd-cad84e99e85f)
as you can see, this texture doesnt have outlines like other ones, for example this one has them:
![gfSticker2](https://github.com/FunkinCrew/Funkin/assets/134156720/85f5c463-3183-4d57-9c59-ed2a2d4f2eb6)

Yeah and thats it, im not 100% sure if this is a texture error or is this done like that on purpose.

**Comment by NotHyper-474** [comment]
Already reported in https://github.com/FunkinCrew/Funkin/issues/2852

**Comment by TabTray** [comment]
literally unplayable
its so bad i had to fix it myself
![image](https://github.com/FunkinCrew/Funkin/assets/81453312/45c175ad-f415-4f37-8322-8bd77f0d527b)
