### ISSUE TITLE
Bug Report: Pause Screen Is Affect By Camera Bop Which Can Make It Look Wonky (Minor Bug)

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#2963]
## Describe the bug

Everything on the pause screen from the dimming background layer to all the text and buttons is on the same camera as the HUD, which means that when the camera bumps, so does the text. In extreme cases it can become very noticeable during gameplay.
## To Reproduce

You can see it any song but to get the best view chart a song with either a decently sized negative camera bump or a very intense positive bump. Start the song, and pause right on the bump. If it's large camera zoom positively, you'll see everything be way to large. The reason you don't need very much if it's negative camera bump is because the layer that dims the background shrinks smaller than the screen size so it looks kinda goofy 😭
## Expected behavior

I expected everything to stay at the same scale when pausing no matter what.
## Screenshots/Video
Here's a screenshot of the easily obvious negative pulse variant:
![image](https://github.com/FunkinCrew/Funkin/assets/157259571/dbec5cdf-9090-4cd4-9b80-fc48fd40a238)

And now one of a large inwards pulse (You can't even see everything :<):
![image](https://github.com/FunkinCrew/Funkin/assets/157259571/0295cf80-e156-4d44-9635-4b0e99dbf65a)

## Desktop
 - OS: Windows 10
 
 - Browser: N/A
 
 - Version: 0.4.1

**Comment by NotHyper-474** [comment]
PR #2567 should fix this.

**Comment by NotHyper-474** [comment]
The PR has since been merged so I think this should be fixed now.
