### ISSUE TITLE
Enhancement: Make M.I.L.F Naming Consistent

### ISSUE THREAD

**Issue by bakedroyal** [FunkinCrew/Funkin#2964]
## What is your suggestion, and why should it be implemented?
![MilfGame](https://github.com/FunkinCrew/Funkin/assets/160797203/393b1c44-3a16-42ee-a2de-547b3b80f380)
![MilfOther](https://github.com/FunkinCrew/Funkin/assets/160797203/7180bcba-1b07-4ca4-9ad5-0b5c5a9a1315)
In the game, Milf is named M.I.L.F. while in other sources, its named M.I.L.F
Maybe make it consistent

**Comment by TabTray** [comment]
oh no it’s 2Hot 2hot 2

**Comment by Average-FNF-Modder** [comment]
Make this high priority Eric, just like the 2Hot bug, this literally makes the game unplayable (And then never fix it)

**Comment by gamerbross** [comment]
Also Dad Battle, in the game is "DadBattle" but in Spotify and YouTube is "Dad Battle"

**Comment by EliteMasterEric** [comment]
Got clarification on this, the official correct namings are `2hot`, `M.I.L.F`, and `DadBattle`.

**Comment by Hundrec** [comment]
This vital issue is resolved in 0.5.0 now, right?

**Comment by AbnormalPoof** [comment]
yes
![Screenshot 2024-09-19 at 2 32 02 PM](https://github.com/user-attachments/assets/3ac9a556-bf55-451a-bef2-f36b2b37cc1b)
