### ISSUE TITLE
Bug Report: 2 problems 1. when I first got into the game on week one the bf wasnt appearing just dad and gf 2. when you play on a chromeback and want to play again the game gets stuck on the loading screen also im on version 4.8.1  

### ISSUE THREAD

**Issue by Jetblack1234** [FunkinCrew/Funkin#297]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [x] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ ] Windows x86_64
- [x] Linux
- [ ] macOS

**Comment by regulad** [comment]
What?
