### ISSUE TITLE
I'm getting an error when building a game with lime test windows -debug

### ISSUE THREAD

**Issue by Darkness-apl** [FunkinCrew/Funkin#2970]
### How to fix it???

`source/Prebuild.hx:15: Building...
E:/My-document/funkin/.haxelib/flxanimate/3,0,4/flxanimate/animate/FlxAnim.hx:26: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
E:/My-document/funkin/.haxelib/funkin,vis/git/src/funkin/vis/dsp/SpectralAnalyzer.hx:7: characters 8-22 : Type not found : grig.audio.FFT`

! [WeChat screenshot_20240706171927] (https://github.com/ShadowMario/FNF-PsychEngine/assets/132057301/3d7638d5-eef8-4f16-98b8-72a3a002306d)

**Comment by moxie-coder** [comment]
run hmm

**Comment by Darkness-apl** [comment]
> 运行嗯

source/Prebuild.hx:15: Building...
source/funkin/util/macro/GitCommit.hx:55: Git Branch Name: main
source/funkin/util/macro/GitCommit.hx:26: Git Commit ID: 27bf88c
source/funkin/util/macro/GitCommit.hx:101: Git Status Output:
E:/My-document/funkin/.haxelib/flixel-addons/git/flixel/addons/display/FlxRuntimeShader.hx:47: characters 9-18 : flixel.addons.display.FlxRuntimeShader has no field glVersion
