### ISSUE TITLE
I'm getting an error when building a game with lime test windows -debug

### ISSUE THREAD

**Issue by Darkness-apl** [FunkinCrew/Funkin#2971]
#How to fix it???

`source/Prebuild.hx:15: Building...
source/funkin/util/macro/GitCommit.hx:55: Git Branch Name: main
source/funkin/util/macro/GitCommit.hx:26: Git Commit ID: 27bf88c
source/funkin/util/macro/GitCommit.hx:101: Git Status Output:
E:/My-document/funkin/.haxelib/flixel-addons/git/flixel/addons/display/FlxRuntimeShader.hx:47: characters 9-18 : flixel.addons.display.FlxRuntimeShader has no field glVersion`

![微信截图_20240706181008](https://github.com/FunkinCrew/Funkin/assets/132057301/be85a770-322b-45e6-a45e-59a2ab16289b)

**Comment by Hundrec** [comment]
I'm not sure exactly what the issue is here, but you should be able to fix it by following the troubleshooting steps I've provided in #2928

**Comment by moxie-coder** [comment]
also don’t make duplicate issues
