### ISSUE TITLE
can't compile game

### ISSUE THREAD

**Issue by UltraFatBoi** [FunkinCrew/Funkin#2973]
I am on Windows 11 and I'm TRYING to download the game assets for a web port, but I keep getting this error on the 4th step:
![Screenshot 2024-07-06 131704](https://github.com/FunkinCrew/Funkin/assets/138963208/138b6f74-5d47-41f2-8a71-511eb6f72f93)
I am trying to compile the latest version of the game.

**Comment by moxie-coder** [comment]
you’re not in the right directory dude

**Comment by UltraFatBoi** [comment]
which directory is the right one?

**Comment by NotHyper-474** [comment]
> which directory is the right one?

Do `cd Funkin` (or funkin if it doesn't work)
