### ISSUE TITLE
Bug Report: Stage Editor Controls

### ISSUE THREAD

**Issue by randomguyorsomething** [FunkinCrew/Funkin#2974]
## Describe the bug
It's simple, or not, depending on what you think. if you go to the stage editor, exit by pressing ESC and restart the song, you will lose control of boyfriend.

## To Reproduce
Go to the stage editor on ANY SONG (i got the bug on bopeebo erect.) exit using ESC and restart the song.
## Expected behavior
I expected to still have control of my character.

## Screenshots/Video
(i don't really have any screenshots or videos of it. and i don't wanna spend 5 minutes waiting for my recording software to open)

## Desktop
 - OS:
Windows 11
 - Browser
 (not running the browser version)
 - Version:
 0.4.1

## Additional context
I don't really think you need any other context.

**Comment by randomguyorsomething** [comment]
another thing that i just got, you literally cannot die. whether you have practice mode or not.

**Comment by Hundrec** [comment]
Weird bug! The pause menu should definitely not be accessible from the animation editor.

https://github.com/FunkinCrew/Funkin/assets/170126004/3bc434f8-9147-4b5d-a85b-1053d7d204f8

**Comment by EliteMasterEric** [comment]
The stage builder is an early prototype and not officially supported right now.
