### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Darkness-apl** [FunkinCrew/Funkin#2975]
source/funkin/graphics/shaders/RuntimeCustomBlendShader.hx:14: characters 10-23 : funkin.graphics.shaders.RuntimeCustomBlendShader has no field setBitmapData

I found the same issue #2751 but no one replied to him or her

What exactly went wrong?

**Comment by Hundrec** [comment]
When in doubt, delete the `.haxelib` folder and rerun the `hmm` command. That usually resolves any mysterious compiling errors!

**Comment by EliteMasterEric** [comment]
This looks like yet another compilation error caused by a bad library version. Make sure to properly follow the compilation guide.
