### ISSUE TITLE
Bug Report: [DESCRIBE YOUR BUG IN DETAIL HERE]

### ISSUE THREAD

**Issue by Tymonek123** [FunkinCrew/Funkin#2978]
i tried building the windows clean version and this appears:

C:/HaxeToolkit/haxe/lib/polymod/1,7,0/polymod/Polymod.hx:1005: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/polymod/1,7,0/polymod/Polymod.hx:1051: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/polymod/1,7,0/polymod/backends/PolymodAssets.hx:226: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/NGio.hx:12: characters 1-68 : Abstract<io.newgrounds.objects.events.Result> has no field GetCurrentVersionResult
source/NGio.hx:13: characters 1-61 : Abstract<io.newgrounds.objects.events.Result> has no field GetVersionResult
source/NGio.hx:47: characters 62-76 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:47: characters 104-127 : Type not found : GetCurrentVersionResult
source/TitleState.hx:61: characters 16-24 : Module APIStuff does not define type APIStuff
source/TitleState.hx:61: characters 16-24 : ... For function argument 'api'
source/PlayState.hx:55: characters 21-29 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:99: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:224: characters 21-29 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:988: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:990: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:20: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:26: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/ChartingState.hx:81: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/ChartingState.hx:357: characters 16-24 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/NGio.hx:96: characters 25-39 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:96: characters 25-39 : ... For optional function argument 'callback'
source/NGio.hx:99: characters 30-45 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:99: characters 30-45 : ... For optional function argument 'callback'
source/NGio.hx:85: characters 25-34 : () -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:85: characters 25-34 : ... For optional function argument 'callback'

**Comment by moxie-coder** [comment]
run hmm

**Comment by EliteMasterEric** [comment]
Read the compilation guide properly.
