### ISSUE TITLE
Compiling Help: Class<funkin.Paths> has no field txt

### ISSUE THREAD

**Issue by PumpkinSheee** [FunkinCrew/Funkin#2979]
im on windows, been trying to compile for atleast 3 hours now 😭 every time i fix something i get a new error
ive checked and no-ones got this which is weird but

source/Prebuild.hx:15: Building...
source/funkin/util/macro/GitCommit.hx:26: Git Commit ID: d1a1f2a
source/funkin/util/macro/GitCommit.hx:101: Git Status Output:  M art
source/funkin/util/macro/GitCommit.hx:55: Git Branch Name: main
source/funkin/ui/credits/CreditsDataMacro.hx:13: Hardcoding credits data...
source/funkin/ui/credits/CreditsDataHandler.hx:39: CreditsData(33 entries containing 113 lines)
source/funkin/ui/title/TitleState.hx:242: characters 48-51 : Class<funkin.Paths> has no field txt

i have no idea what that means, ive tried everything from reinstalling hmm, deleting the .haxelib folder and even completely cloning the source code again, nothing - what makes it worse is i have no idea how to recreate this, it just happened
btw i was using lime test windows for this

**Comment by NotHyper-474** [comment]
What's the Haxe version? And have you done any modifications to the source code?

**Comment by EliteMasterEric** [comment]
Based on this log, it appears you have either modified the repository or cloned it incorrectly.

Please follow the compilation guide again.

**Comment by Hundrec** [comment]
Have you been able to compile the game?
We might want to close this issue if you can compile with no issues.

**Comment by EliteMasterEric** [comment]
Going to close since the person hasn't elaborated on their issue
