### ISSUE TITLE
Enhancement: Let us add characters to an fnfc. file. (There's no way they pass this)

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#2989]
## What is your suggestion, and why should it be implemented?
If we're not gonna get a playable Gf in base game (That issue I made was closed), this is the next best thing. For sharing charts, it's really nice to just get an fnfc. file and open it with out folder placement hassle on the players end. Adding characters to the file would let me keep it in one file and still have a playable Gf.

**Comment by Hundrec** [comment]
I think this would bloat the already significant file size of the .fnfc file.
If you want people to play your chart with modded characters, it's better to just place the chart, audio, character data, and spritesheets in an `assets` folder people can drag and drop into their game directory.

**Comment by EliteMasterEric** [comment]
If you want people to play your chart with modded characters, it's better to just place the chart, audio, character data, and spritesheets in a folder with a `_polymod_metadata.json` file for people can drag and drop into their `mods` directory. That lets people manage the mod easily.
