### ISSUE TITLE
Can't compile the game Error: Int should be funkin.play.notes.NoteSprite       | For function argument 'note'

### ISSUE THREAD

**Issue by CreamslyCream** [FunkinCrew/Funkin#2993]
im trying to make a miss counter on your health bar, i've used the onNoteMiss to track it, the code is VERY simple its just var misses = 0; then i did, onNoteMiss(misses ++); (btw this is in playstate.hx in lines 2266 and 2267)

use the onNoteMiss thing (i think)
just wanted to test if the variable would work properly 
![Screenshot 2024-07-09 234846](https://github.com/FunkinCrew/Funkin/assets/104226184/b12ecf10-e10d-4d14-b706-c72dcda8f6a3)
![Screenshot 2024-07-09 235006](https://github.com/FunkinCrew/Funkin/assets/104226184/37c6bc1c-b72c-4a6d-a22e-e8b46f03c9f3)

## Desktop
 - OS:
 windows 11
 - Browser
chrome 
 - Version:
0.4.1

## Additional context
The only other thing i have changed in playstate, is comment the lines have ghost tapping work, but that hasnt caused any errors

**Comment by moxie-coder** [comment]
> im trying to make a miss counter on your health bar, i've used the onNoteMiss to track it, the code is VERY simple its just var misses = 0; then i did, onNoteMiss(misses ++); (btw this is in playstate.hx in lines 2266 and 2267)
> 
> use the onNoteMiss thing (i think) just wanted to test if the variable would work properly ![Screenshot 2024-07-09 234846](https://private-user-images.githubusercontent.com/104226184/347250967-b12ecf10-e10d-4d14-b706-c72dcda8f6a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODQwNTEsIm5iZiI6MTcyMDU4Mzc1MSwicGF0aCI6Ii8xMDQyMjYxODQvMzQ3MjUwOTY3LWIxMmVjZjEwLWUxMGQtNGQxNC1iNzA2LWM3MmRjZGE4ZjZhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwMzU1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2RjNmM0MWU3OGNiNTYyYmEwODY2ZDExMjMwODM4MjY2NGFmYTk5NGU0YTM1ZDdmMTJjMDdhNDg1OGNiNTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P_byiprhqZdBfrnbgyq0rXmpa_VSv-YfCH_NX94Mv4w) ![Screenshot 2024-07-09 235006](https://private-user-images.githubusercontent.com/104226184/347250979-37c6bc1c-b72c-4a6d-a22e-e8b46f03c9f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODQwNTEsIm5iZiI6MTcyMDU4Mzc1MSwicGF0aCI6Ii8xMDQyMjYxODQvMzQ3MjUwOTc5LTM3YzZiYzFjLWI3MmMtNGE2ZC1hMjJlLWU4YjQ2ZjAzYzlmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwMzU1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDA1ZTBkZjQ0NTQyMzllNjBkNzc3MWNkMmU1NDg5M2YyNzM0NmYwNDdlY2I2ZTE5OGYxMmNmMTQ2ODZhNzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Pt-VCPBxT3WCW222ZvmoefXDdSpVqP6suk9Gup0_0A)
> 
> ## Desktop
> * OS:
>   windows 11
> * Browser
>   chrome
> * Version:
>   0.4.1
> 
> ## Additional context
> The only other thing i have changed in playstate, is comment the lines have ghost tapping work, but that hasnt caused any errors

you can’t use ints like that, and it takes a noteSprite for the first argument, not an int
![IMG_0119](https://github.com/FunkinCrew/Funkin/assets/124418090/0f169459-0341-4a8a-bb7b-77e1e5a5d2cc)

**Comment by CreamslyCream** [comment]
good to know! im kind of new to coding
