### ISSUE TITLE
On Hard difficulty, sustain notes have a graphical gap

### ISSUE THREAD

**Issue by Herschel** [FunkinCrew/Funkin#3]
When playing on Hard difficulty, the increased speed of the arrows seems to cause a graphical gap at the end cap of sustain notes:

![image](https://user-images.githubusercontent.com/36278/98436916-c3ab5900-2093-11eb-89ef-a30309674acd.png)

**Comment by Gaturrito100** [comment]
Yhea, I've see that too, might be because it's too fast to properly draw them.

**Comment by bradorak** [comment]
I implemented a new fnf character

**Comment by MemeHovy** [comment]
> I implemented a new fnf character

no one cares

**Comment by bradorak** [comment]
😥

**Comment by SpareEnderboy** [comment]
quick links:
first pull request: #1
first closed pull request: #2
first issue (that's still open): #1038
