### ISSUE TITLE
Bug Report: Test

### ISSUE THREAD

**Issue by tposejank** [FunkinCrew/Funkin#3000]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if it has been previously reported

### What platform are you using?

Itch.io - Windows

### If you were playing on a browser, which one were you using?

None

### Version

0.4.infinite

### Context (Provide images, videos, etc.)

is this issue 3000?

**Comment by Hundrec** [comment]
True

**Comment by tposejank** [comment]
wow, #3000! this is so crazy!
