### ISSUE TITLE
Poses

### ISSUE THREAD

**Issue by asd3fg** [FunkinCrew/Funkin#3001]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I looked in issues/discussions, if it has been previously reported

### What platform are you using?

Itch.io - Windows

### If you were playing on a browser, which one were you using?

None

### Version

pitshop update

### Context (Provide images, videos, etc.)

A problem that is not very serious but somewhat annoying is that the characters sink to the floor every time they make a pose. This happened when I tried to lower the scaling of a character or if a character made an alternate pose.

I don't know if this is my problem or the engine's problem in general, but it would be nice if this bug disappeared in the next update.

here is a preview of what I mean
https://files.catbox.moe/dqlcfg.mp4

**Comment by tposejank** [comment]
this is an ongoing bug. you should check for duplicates:
#2938 #2271 #2865 
and prs that fix them: 
#2610 

and by "pitshop update", which one

**Comment by NotHyper-474** [comment]
And while the issue isn't solved you can apply this fix this guy made https://github.com/FunkinCrew/Funkin/issues/2865#issuecomment-2184242954

> and prs that fix them
> * #2610

considering it was merged I don't think it fixes it lol

**Comment by asd3fg** [comment]
> and by "pitshop update", which one

the most recent update i mean

**Comment by Hundrec** [comment]
Please edit your report to indicate "0.4.1" under "Version"

**Comment by asd3fg** [comment]
> And while the issue isn't solved you can apply this fix this guy made [#2865 (comment)](https://github.com/FunkinCrew/Funkin/issues/2865#issuecomment-2184242954)
> 
> > and prs that fix them
> > 
> > * [[BUGFIX] Correct characters scaling on stage #2610](https://github.com/FunkinCrew/Funkin/pull/2610)
> 
> considering it was merged I don't think it fixes it lol

HOLY SHIT IT ACTUALLY WORKS

**Comment by tposejank** [comment]
Close please... gentlemen!

**Comment by asd3fg** [comment]
> Close please... gentlemen!

I don't know how to close this, it only lets me change the title of the post
