### ISSUE TITLE
Crash: crash report test (IGNORE, FAKE, NOT REAL)

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#3002]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if it has been previously reported

### What platform are you using?

Itch.io - Windows

### If you were playing on a browser, which one were you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc. of the crash happening)

so uhh i was playing the game and then i became so cool

### Steps to reproduce

1. open the game
2. type fnf
3. the game explodes with fun

### Crash Logs (can be found in the crash folder)

crash overload: one of the best games in the world

**Comment by JVNpixels** [comment]
ok it works! yay @tposejank new template works!

**Comment by tposejank** [comment]
wow! this crash report is so helpful!

**Comment by ExcodeFNF** [comment]
close this

**Comment by JVNpixels** [comment]
yk what else you can close? 🫃

**Comment by tposejank** [comment]
it is already closed sir

**Comment by moxie-coder** [comment]
> close this

it's already closed

**Comment by JVNpixels** [comment]
> close this

close this
