### ISSUE TITLE
Bug Report (GITHUB ISSUE): Github Actions not working

### ISSUE THREAD

**Issue by CrusherNotDrip** [FunkinCrew/Funkin#3006]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if it has been previously reported

### What platform are you using?

Itch.io - Windows

### If you were playing on a browser, which one were you using?

Firefox

### Version

0.4.1 (NOT github actions)

## (Sorry if this isn't where this issue is meant to go)

I have noticed that this repository doesn't really allow Github Actions to work as intended

![image](https://github.com/FunkinCrew/Funkin/assets/90648119/47a04ba4-1e70-47ee-8383-729da2093bb4)

I would make a PR but this is something that you tamper with inside the repository settings
anyways to fix this heres something that **might** work:

`Settings` -> `Actions (General)` -> `Actions permissions` -> `Allow all actions and reusable workflows` (or maybe also `Allow FunkinCrew, and select non-FunkinCrew, actions and reusable workflows`)

### Steps to reproduce (or crash logs, errors, etc.)

Push something to FunkinCrew / Funkin or Pull Request

**Comment by tposejank** [comment]
yes because my email blows up

**Comment by NotHyper-474** [comment]
I've disabled those workflows in my fork just so I don't get spammed lol

**Comment by Hundrec** [comment]
Do actions finally work now?

**Comment by Hundrec** [comment]
I didn't receive an error when I opened https://github.com/FunkinCrew/Funkin/issues/3584, so I think we're good!

**Comment by CrusherNotDrip** [comment]
> I didn't receive an Issue labeler error email when I opened #3584, so I think we're good!

thats awesome sauce

**Comment by Raltyro** [comment]
Workflow doesn't work

**Comment by AbnormalPoof** [comment]
> Workflow Builds doesn't work

#4175
