### ISSUE TITLE
Cant install hmm.json

### ISSUE THREAD

**Issue by CreamslyCream** [FunkinCrew/Funkin#3008]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

When i run haxelib --global run hmm setup it gives the error: copy C:/HaxeToolkit/haxe/lib/hmm/3,1,0/hmm.cmd C:/HaxeToolkit/haxe/hmm.cmd, when I did that, it does absolutely nothing and gives the same error. i tried to use the command hmm install and that also did not work. 
![Screenshot 2024-07-11 172721](https://github.com/user-attachments/assets/264bb556-9b27-4c06-bafd-79688c6a22e9)
![Screenshot 2024-07-11 172730](https://github.com/user-attachments/assets/2e1c7055-1457-4c53-a079-be9de09ea4ae)
and yes i installed hmm, and re-installed it.

### Steps to reproduce (or crash logs, errors, etc.)

idk what i did but whatever  i did, dont do it

**Comment by Hundrec** [comment]
Are you in the right directory? The error indicates that hmm.json isn't present in your directory.

Check your `funkin` directory for a hmm.json file. If it's not there, then `cd` to the directory and try Step 5 again.

**Comment by CreamslyCream** [comment]
> Are you in the right directory? The error indicates that hmm.json isn't present in your directory.
> 
> Check your `funkin` directory for a hmm.json file. If it's not there, then `cd` to the directory and try Step 5 again.

theres no hmm.json, and im in the correct directory

**Comment by CreamslyCream** [comment]
i think i could have found a fix

**Comment by CreamslyCream** [comment]
found the fix, just went to the github page and copied down hmm.json and made a hmm,json file
