### ISSUE TITLE
YO ERIC WHAT DID YOU DO WITH DEVELOP BRANCH LMFAOO

### ISSUE THREAD

**Issue by gamerbross** [FunkinCrew/Funkin#3010]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Other (Specify below)

### Version

develop

### Context (Provide images, videos, etc.)

where is develop

**Comment by NotHyper-474** [comment]
WHAT HAPPENED 😭

**Comment by Hundrec** [comment]
So that's what snapped the PRs out of existence...

**Comment by NotHyper-474** [comment]
> So that's what snapped the PRs out of existence...

eric really just pulled a Thanos with most PRs

**Comment by cyn0x8** [comment]
ITS ALL GONE

https://github.com/user-attachments/assets/c88b64f2-c6b2-4d82-a0b6-7eb7c20f85f1

**Comment by NotHyper-474** [comment]
we're so back

**Comment by gamerbross** [comment]
tysm eric

**Comment by EliteMasterEric** [comment]
![xeroxed-smily](https://github.com/user-attachments/assets/b9121be7-942c-4f1d-891e-7c236061d5c7)

Live reaction to me realizing I accidentally auto-closed 70 pull requests and had to manually re-open them

**Comment by tposejank** [comment]
😭😭 I feel you bruh 🙏
