### ISSUE TITLE
Bug Report:  Pico's Death Sprites have a Miscolored Background

### ISSUE THREAD

**Issue by stixsti** [FunkinCrew/Funkin#3015]
### Issue Checklist

- [X] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

Title says it all
Pico's Death sprites have a miscolored background.
![image](https://github.com/user-attachments/assets/dd7cd5f5-a586-407b-82b0-15a8a4c1e134)

### Steps to reproduce (or crash logs, errors, etc.)

die as pico

**Comment by Hundrec** [comment]
Reported in #2250

**Comment by EliteMasterEric** [comment]
Duplicate
