### ISSUE TITLE
Crash Report: crashes when I open Freeplay/story mode

### ISSUE THREAD

**Issue by Poshua-I-guess** [FunkinCrew/Funkin#3024]
### Issue Checklist

- [x] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Google Chrome

### Version

0.4.1

### Context (Provide screenshots or videos of the crash happening)

![Screenshot 2024-07-13 19 48 20](https://github.com/user-attachments/assets/c2586647-ed36-4d9b-bad4-de438b9442fa)
 
I tried to open the game and play, but it crashes when it opens the Freeplay/story mode!

### Steps to reproduce

Open the game
story mode/Freeplay
Tutorial (any mode)

### Crash logs (can be found in the logs folder where Funkin.exe is)

N/A

**Comment by Hundrec** [comment]
Does this happen with other browsers as well?

**Comment by Poshua-I-guess** [comment]
> Does this happen with other browsers as well?

No idea

**Comment by Hundrec** [comment]
Please test if this happens on itch.io (Web) and any other browsers you can access

**Comment by Poshua-I-guess** [comment]
> Please test if this happens on itch.io (Web) and any other browsers you can access

ok

**Comment by Poshua-I-guess** [comment]
> Please test if this happens on itch.io (Web) and any other browsers you can access

I tested it on Itch.io (web) and it did not work

**Comment by Hundrec** [comment]
Do you have any Chrome extensions installed?

**Comment by Poshua-I-guess** [comment]
> Do you have any Chrome extensions installed?

yes, many
I disabled my ad blocker but that didn't help

**Comment by Hundrec** [comment]
Please try accessing the game from Microsoft Edge or another browser

**Comment by Poshua-I-guess** [comment]
> Please try accessing the game from Microsoft Edge or another browser

ok, I will try

**Comment by Poshua-I-guess** [comment]
> Please try accessing the game from Microsoft Edge or another browser

I used opera (Browser) and it worked on newgrounds (web)!
