### ISSUE TITLE
Bug Report: Can't Compile

### ISSUE THREAD

**Issue by 2JENO** [FunkinCrew/Funkin#3025]
### Issue Checklist

- [X] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

source/Prebuild.hx:15: Building...
source/funkin/util/macro/GitCommit.hx:55: Git Branch Name: main
source/funkin/util/macro/GitCommit.hx:26: Git Commit ID: 3438705
source/funkin/util/macro/GitCommit.hx:101: Git Status Output: 
 WARNING  D:/Files/Source Code/fnf/funkin/.haxelib/polymod/git/polymod/Polymod.hx:1005: characters 1-7

 1005 | @:enum abstract PolymodErrorOrigin(String) from String to String
      | ^^^^^^
      | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  D:/Files/Source Code/fnf/funkin/.haxelib/polymod/git/polymod/Polymod.hx:1051: characters 1-7

 1051 | @:enum abstract PolymodErrorCode(String) from String to String
      | ^^^^^^
      | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  D:/Files/Source Code/fnf/funkin/.haxelib/polymod/git/polymod/backends/PolymodAssets.hx:226: characters 1-7

  226 | @:enum abstract PolymodAssetType(String) from String to String
      | ^^^^^^
      | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  D:/Files/Source Code/fnf/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199      

  196 |  public function switchTo(nextState:FlxState):Bool
  197 |  {
  198 |   return true;
  199 |  }
      |
      | switchTo is deprecated, use startOutro

 WARNING  D:/Files/Source Code/fnf/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199      

  196 |  public function switchTo(nextState:FlxState):Bool
  197 |  {
  198 |   return true;
  199 |  }
      |
      | switchTo is deprecated, use startOutro

 WARNING  D:/Files/Source Code/fnf/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

  196 |  public function switchTo(nextState:FlxState):Bool
  197 |  {
  198 |   return true;
  199 |  }
      |
      | switchTo is deprecated, use startOutro

 WARNING  D:/Files/Source Code/fnf/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199      

  196 |  public function switchTo(nextState:FlxState):Bool
  197 |  {
  198 |   return true;
  199 |  }
      |
      | switchTo is deprecated, use startOutro

 ERROR  source/funkin/modding/PolymodHandler.hx:294: characters 7-24

  294 |       coreAssetRedirect: CORE_FOLDER,
      |       ^^^^^^^^^^^^^^^^^
      | { coreAssetRedirect : Null<String>, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect

 *  터미널 프로세스 "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command lime build windows -debug -DFORCE_DEBUG_VERSION --haxelib=hxcpp-debug-server"이(가) 종료되었습니다(종료 코드: 1). 
 *  터미널이 작업에서 다시 사용됩니다. 닫으려면 아무 키나 누르세요.

**Comment by Hundrec** [comment]
Looks like you might be using the wrong version of Polymod.

Try deleting the `polymod` folder in `.haxelib` and follow the [compiling guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/COMPILING.md) from Step 5 again.

**Comment by tposejank** [comment]
you must download the latest polymod
