### ISSUE TITLE
Bug Report: Senpai Transformation Cutscene doesn't work properly when blueballing

### ISSUE THREAD

**Issue by yeetree** [FunkinCrew/Funkin#3030]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

If you blue ball during the scene in Hating Simulator where Senpai turns into Spirit by smashing  random buttons, whenever you try to "retry," the song will play immediately without waiting for the dialog to finish 

https://github.com/user-attachments/assets/d59119fe-d43c-4a86-b14b-94292c3f1e9a

### Steps to reproduce (or crash logs, errors, etc.)

* play Hating Simulator in story mode
* beat roses and thorns
* when senpai's transformation screen begins, blueball yourself by hitting random buttons
* retry

**Comment by yeetree** [comment]
^^ whoops, butterfingers over here

**Comment by Hundrec** [comment]
Wow, this is a pretty funny bug

I think this should be easy to fix just by disabling inputs once Roses ends.

**Comment by ninjamuffin99** [comment]
hopefully should be fixed in the next update, thanks!
