### ISSUE TITLE
When long arrow pressed once long arrow disappers

### ISSUE THREAD

**Issue by NotLazyWoods** [FunkinCrew/Funkin#3040]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

As I was playing fnf I found a bug/glitch in week 7. I haven't checked for other weeks but when you see a long press in the game and you press it once it disappears without saying you missed it. This bug is not a big bug but kind of cheating. 

### Steps to reproduce (or crash logs, errors, etc.)

1. Get into week 7(I haven't tried it for other weeks)
2. When a long press is coming quickly press the arrow once
3. The arrow will disappear registering as a click.

**Comment by moxie-coder** [comment]
that doesn't even seem like a bug, just sounds like you're an idiot who doesn't know how sustains work

**Comment by lemz1** [comment]
this is the intented behaviour of sustains

**Comment by moxie-coder** [comment]
> this is the intented behaviour of sustains

exactly

**Comment by NotLazyWoods** [comment]
> that doesn't even seem like a bug, just sounds like you're an idiot who doesn't know how sustains work

Chill I just started I thought it was a bug

**Comment by moxie-coder** [comment]
> > that doesn't even seem like a bug, just sounds like you're an idiot who doesn't know how sustains work
> 
> Chill I just started I thought it was a bug

![IMG_0998](https://github.com/user-attachments/assets/b1eb7dd4-408f-439c-a7d4-6ec2e93fd3e5)

**Comment by moxie-coder** [comment]
bro doesn’t know how rhythm games work

**Comment by lemz1** [comment]
Come on, give it a rest.
They thought it was a bug and decided to report it, which is a good thing.
Even if it turned out not to be an actual bug.

**Comment by NotLazyWoods** [comment]
> Come on, give it a rest. They thought it was a bug and decided to report it, which is a good thing. Even if it turned out not to be an actual bug.
> 
> I get that it can be sometimes annoying, if people report things that aren't bugs, but there is no reason to be rude to them.

Okay :|

**Comment by moxie-coder** [comment]
> Come on, give it a rest. They thought it was a bug and decided to report it, which is a good thing. Even if it turned out not to be an actual bug.
> 
> I get that it can be sometimes annoying, if people report things that aren't bugs, but there is no reason to be rude to them.

I do whatever I like, you’re not my mom

**Comment by moxie-coder** [comment]
> bro doesn’t know how rhythm games work 

and plus, this was mainly a joke

**Comment by lemz1** [comment]
@NotLazyWoods can you close this issue, since its been resolved?

**Comment by moxie-coder** [comment]
I’m just gonna hide my comment since I’ll admit, I was aggressive but like, I can’t help myself but be aggressive when I’ve lost my patience with people like this, but I’ll try to be less of that going forward
