### ISSUE TITLE
Enhancement: Let Us Set More Specific Event Values And Remove Caps

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#3044]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

There is no real reason we shouldn't be able to have one camera zoom every 16 beats persay, or set the camera's zoom value to a decimal more specific than tenths. It being stepped that way is nice for convince when using it normally, but when typing in a value, just let us set it to whatever we want and remove the caps. I don't see why not.

**Comment by Hundrec** [comment]
Yep, the caps are especially limiting for consecutive zoom events, and some erect charts use invalid zoom values too!

**Comment by Average-FNF-Modder** [comment]
> Yep, the caps are especially limiting for consecutive zoom events, and some erect charts use invalid zoom values too!

Yea, I know base game cheats with source code still a lot, like how monster changes BPM but there's no event for it. It's annoying.

**Comment by EliteMasterEric** [comment]
> There is no real reason we shouldn't be able to have one camera zoom every 16 beats persay

~~Literally no idea what you're talking about.~~ I just found the issue with this.

> set the camera's zoom value to a decimal more specific than tenths.

Valid! Being able to set the zoom level to increments of 0.05 would be good and that's a quick change.

> how monster changes BPM but there's no event for it. It's annoying.

This one is a known issue, it's not easy to solve though because changing BPM without breaking the chart editor is frustrating!
