### ISSUE TITLE
Enhancement: Have A Way To More Specifically Set Your Volume / At Least Let Us Set It To Something Less Than 10%

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#3061]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sometimes I wanna like, listen to a Phantom Arcade stream or a Ted Talk or any video really in the background while I'm playing FNF, and I still wanna hear the game, but I want it to be super quite so I can hear what I'm watching. Because FNF is such a loud game in general, even at minimum in game volume with whatever I'm watching cranked to max I can't hear people, so the only way to play and listen at the same time is to turn the FNF game audio all the way off, which really sucks.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;So I suggest an options setting to maybe specifically set your volume amount down to the percent and having an even lower than 10% option with the plus and minus keys, maybe like a 3% amount before hitting straight up mute.

**Comment by Hundrec** [comment]
I think this would be nice, but for now, Windows users can go to the volume mixer and turn FNF down to a lower volume.

**Comment by Cartridge-Man** [comment]
> I think this would be nice, but for now, Windows users can go to the volume mixer and turn FNF down to a lower volume.

Yeah, and plus when the full game comes out we’ll probably get a fully finished options menu by then that has about everything we need

**Comment by Average-FNF-Modder** [comment]
> I think this would be nice, but for now, Windows users can go to the volume mixer and turn FNF down to a lower volume.

How the hell do you do that respectfully please tell me. Evens still it would be good for Mac users.

**Comment by Cartridge-Man** [comment]
> How the hell do you do that respectfully please tell me. Evens still it would be good for Mac users.

Hey, amazing idea but why don’t you try a neat thing called looking up the answer. It works every time.

**Comment by Average-FNF-Modder** [comment]
> > How the hell do you do that respectfully please tell me. Evens still it would be good for Mac users.
> 
> Hey, amazing idea but why don’t you try a neat thing called looking up the answer. It works every time.

That is in fact an amazing idea that my special ass did not think of. You didn't have to be rude about it tho :(

**Comment by ninjamuffin99** [comment]
just did this today! I submitted a PR to upstream flixel as well, and it should be in our next update, thanks!
