### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by dogsuscool** [FunkinCrew/Funkin#3071]
### Issue Checklist

- [x] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

None

### Version

experimental

### Context (Provide images, videos, etc.)

I don't know how to get this work I try to see is someone else had this to but no one did
![Screenshot 2024-07-28 042644](https://github.com/user-attachments/assets/6bd8b905-c1d5-4f4b-80b4-756b7e5d9b46)

**Comment by AbnormalPoof** [comment]
Someone didn't read the Bug Report template.
![Screenshot 2024-07-28 at 4 32 39 AM](https://github.com/user-attachments/assets/54aec946-2b91-4479-af45-c95908fd8847)

**Comment by NotHyper-474** [comment]
As AbnormalPoof noted you should report this on https://github.com/ShadowMario/FNF-PsychEngine instead.

**Comment by dogsuscool** [comment]
> Someone didn't read the Bug Report template. ![Screenshot 2024-07-28 at 4 32 39 AM](https://private-user-images.githubusercontent.com/86753001/352802614-54aec946-2b91-4479-af45-c95908fd8847.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTk0OTYsIm5iZiI6MTcyMjE1OTE5NiwicGF0aCI6Ii84Njc1MzAwMS8zNTI4MDI2MTQtNTRhZWM5NDYtMmI5MS00NDc5LWFmNDUtYzk1OTA4ZmQ4ODQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA5MzMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNjc0YzRjNDdmYTVlMGNkZDcxZDYzOTg1MWU2MThlOTFjMzQ1ODAwNmVlNmIyMTQyYmE2OTY4YTVlNmNjYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HHifc17PEbrJ8nd35eeq1WlB3VJniY1tKhi6Ynh4Ros)

my dumbass sorry

**Comment by Cartridge-Man** [comment]
Close this.

**Comment by Keoiki** [comment]
Closing an issue seems to be the most difficult thing in the world for some people to do

**Comment by Cartridge-Man** [comment]
> Closing an issue seems to be the most difficult thing in the world for some people to do

Exactly

**Comment by dogsuscool** [comment]
> > Closing an issue seems to be the most difficult thing in the world for some people to do
> 
> Exactly

i was not looking

**Comment by Hundrec** [comment]
There should be a button labeled "Close issue" somewhere on this page. It might have a purple icon or be labeled "Close issue with comment"
