### ISSUE TITLE
Enhancement: Future-proof difficulty star visuals

### ISSUE THREAD

**Issue by LukerUpgradez** [FunkinCrew/Funkin#3075]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

The freeplay menu visuals currently handle difficulties up to level 15, and it's been stated that the maximum difficulty will likely be 20. But what if those plans change, and the maximum level is raised to 30? Or, more likely, a player/modder wants to use a difficulty level higher than 20 for their song chart? It might be useful to have some functionality for this prepared, if only to give the engine more versatility.

A simple solution would be to re-shade the flames as a different color for each range of ten. For example, let's say 11-20 has blue flames, 21-30 has purple flames, 31-40 has red flames, and so on, with each loop being a darker shade from the last. This could be handled by some kind of formula so the colors aren't hard coded.

I don't work in Haxe so I can't give exact code ideas, but I imagine you could take advantage of the difficulty visual being handled in multiples of 10 to simplify the process. `curDifficulty / 10` gives you the shade for all of the stars (2 for blue, 3 for purple, 4 for red, etc.), while `curDifficulty % 10` gives you the number of stars that need the shade `curDifficulty / 10 + 1`.

**Comment by Cartridge-Man** [comment]
After reading this my brain turned to ooze on why in the first place that the game has both a difficulty level next to songs and then difficulty stars below the album art lol

**Comment by EliteMasterEric** [comment]
I think for base Funkin', we currently don't want to go beyond 20, and we'll definitely only add new difficulty sprites if we actually decide to do that.

Keep in mind that 20 is currently intended to be the level of difficulty for the hardest song in the game EVER, and we might rework the difficulty levels for the songs that exist to fit with that if needed.

**Comment by LukerUpgradez** [comment]
That’s reasonable. Definitely more of a mod project than something the official game needs, then.
