### ISSUE TITLE
Bug Report: it says: Error: "platform" is an unknown target. What does this mean?

### ISSUE THREAD

**Issue by ziopero11** [FunkinCrew/Funkin#3079]
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

![image](https://github.com/user-attachments/assets/121d30ca-2962-4b56-8074-a7f251bf5b27)

**Comment by NotHyper-474** [comment]
You're not supposed to literally write "PLATFORM".

**Comment by ziopero11** [comment]
i wrote: "lime test platform" and it didn't work. I also wrote "lime rebuild platform -debug" "lime test platform -debug" and "lime rebuild platform -debug" but it didn't work

**Comment by taufei** [comment]
> i wrote: "lime test platform" and it didn't work. I also wrote "lime rebuild platform -debug" "lime test platform -debug" and "lime rebuild platform" but it didn't work

platform is supposed to be like windows mac linux html5 whatever
just replace the word platform with windows and it should work

**Comment by Cartridge-Man** [comment]
Somebody sucks at understanding how to compile something..

btw, close this issue. purple button that says “close issue”
