### ISSUE TITLE
Enhancement: Include a link to the modding documentation in a README.txt in the mods folder

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/Funkin#3080]
### Issue Checklist

- [ ] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

You should add a link to the modding documentation a README in the mods folder so newer people can understand that that is where to go to figure out how to mod the game.

**Comment by NotHyper-474** [comment]
> w h a t .

https://github.com/FunkinCrew/funkin-modding-docs

**Comment by Cartridge-Man** [comment]
oh thanks lol I had no idea documentation for modding existed! Gonna make a pr for this in order to link the repository for the mods folder README.md

**Comment by biomseed** [comment]
> oh thanks lol I had no idea documentation for modding existed! Gonna make a pr for this in order to link the repository for the mods folder README.md

I was referring to the mods folder readme. Do not do this.

**Comment by NotHyper-474** [comment]
> > oh thanks lol I had no idea documentation for modding existed! Gonna make a pr for this in order to link the repository for the mods folder README.md
> 
> I was referring to the mods folder readme. You changed the one for the repository. Do not add my issue to your PR or else it will be closed if merged.

Actually he didn't use keywords "fix" or "close" as mentioned [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). Unless you mean Eric/Cameron manually closing the issue.

**Comment by biomseed** [comment]
I was wrong, there was no README in the mods folder. I made the changes to this issue as needed (imo)

**Comment by biomseed** [comment]
Partially done
