### ISSUE TITLE
Bug Report: Old Boyfriend icon easter egg breaks on pixel stages

### ISSUE THREAD

**Issue by CoolDudeT** [FunkinCrew/Funkin#3085]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

So you know when you press 9, the old Boyfriend icon from the ludum dare demo replaces BF's "new" icon? Yeah? Well, it breaks on Week 6 or pixel stages in general. Unsure why it breaks, but it doesn't break the game in anyway.
![Friday Night Funkin' 8_2_2024 6_40_47 PM](https://github.com/user-attachments/assets/60190b28-08dc-4b0d-a152-55e47c1a0c2b)

### Steps to reproduce (or crash logs, errors, etc.)

press 9 on senpai, senpai erect, roses, roses erect, thorns, or thorns erect.

**Comment by ninjamuffin99** [comment]
should be fixed in upcoming update, thanks
