### ISSUE TITLE
Build troubles when trying to compile haslink

### ISSUE THREAD

**Issue by galleniz** [FunkinCrew/Funkin#3088]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Linux

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

When I tried to compile to haslink because I can't compile to normal linux, I had a problem that I really don't know why, because I tried to compile from another lime project and it left me correctly.

> The problem in cuestion
![image](https://github.com/user-attachments/assets/209e8804-149b-45f7-9dad-f9fc9fd2983f)

> proof of the compilation on other project
![image](https://github.com/user-attachments/assets/f7629ee5-e727-4ca2-82b1-f8768f7ddca7)

### Steps to reproduce (or crash logs, errors, etc.)

I just installed the GitHub version and tried to compile to hashlink, and I read all the documentation for building and there is no specification for hashlink.

And the logs was:
<pre><font color="#FF0000">❯</font> lime test hl
source/Prebuild.hx:15: Building...
source/funkin/util/macro/GitCommit.hx:26: Git Commit ID: 9b483de
source/funkin/util/macro/GitCommit.hx:101: Git Status Output: 
source/funkin/util/macro/GitCommit.hx:55: Git Branch Name: main
source/funkin/ui/credits/CreditsDataMacro.hx:13: Hardcoding credits data...
source/funkin/ui/credits/CreditsDataHandler.hx:39: CreditsData(33 entries containing 113 lines)
<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> /home/galleniz/Documents/GitHub/funkin/.haxelib/thx,core/git/src/thx/Weekday.hx:7: characters 1-7

   7 | <b>@:enum</b>
     | <font color="#A2734C">^^^^^^</font>
     | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> /home/galleniz/Documents/GitHub/funkin/.haxelib/thx,core/git/src/thx/Weekday.hx:7: characters 1-7

   7 | <b>@:enum</b>
     | <font color="#A2734C">^^^^^^</font>
     | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/play/ResultState.hx:875: lines 875-887

 875 |                 FlxG.switchState(<b>FreeplayState.build(</b>
   - |                   [...]
 887 | <b>                  })</b><font color="#AAAAAA">);</font>
     |
     | (WDeprecated) use `MyState.new` or `()-&gt;new MyState()` instead of `new MyState()`)

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/play/components/HealthIcon.hx:208: characters 38-55

 208 |         var targetSize:Int = Std.int(<b>MathUtil.coolLerp</b><font color="#AAAAAA">(this.width, HEALTH_ICON_SIZE * this.size.x, 0.15));</font>
     |                                      <font color="#A2734C">^^^^^^^^^^^^^^^^^</font>
     | (WDeprecated) Use smoothLerp instead

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/play/components/HealthIcon.hx:214: characters 38-55

 214 |         var targetSize:Int = Std.int(<b>MathUtil.coolLerp</b><font color="#AAAAAA">(this.height, HEALTH_ICON_SIZE * this.size.y, 0.15));</font>
     |                                      <font color="#A2734C">^^^^^^^^^^^^^^^^^</font>
     | (WDeprecated) Use smoothLerp instead

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/play/components/HealthIcon.hx:220: characters 20-37

 220 |       this.angle = <b>MathUtil.coolLerp</b><font color="#AAAAAA">(this.angle, 0, 0.15);</font>
     |                    <font color="#A2734C">^^^^^^^^^^^^^^^^^</font>
     | (WDeprecated) Use smoothLerp instead

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/ui/Alphabet.hx:224: characters 11-28

 224 |       y = <b>MathUtil.coolLerp</b><font color="#AAAAAA">(y, (scaledY * 120) + (FlxG.height * 0.48), 0.16);</font>
     |           <font color="#A2734C">^^^^^^^^^^^^^^^^^</font>
     | (WDeprecated) Use smoothLerp instead

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/ui/Alphabet.hx:225: characters 11-28

 225 |       x = <b>MathUtil.coolLerp</b><font color="#AAAAAA">(x, (targetY * 20) + 90, 0.16);</font>
     |           <font color="#A2734C">^^^^^^^^^^^^^^^^^</font>
     | (WDeprecated) Use smoothLerp instead

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/ui/MenuItem.hx:48: characters 9-26

  48 |     y = <b>MathUtil.coolLerp</b><font color="#AAAAAA">(y, (targetY * 120) + 480, 0.17);</font>
     |         <font color="#A2734C">^^^^^^^^^^^^^^^^^</font>
     | (WDeprecated) Use smoothLerp instead

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/ui/freeplay/SongMenuItem.hx:703: characters 11-28

 703 |       x = <b>MathUtil.coolLerp</b><font color="#AAAAAA">(x, targetPos.x, 0.3);</font>
     |           <font color="#A2734C">^^^^^^^^^^^^^^^^^</font>
     | (WDeprecated) Use smoothLerp instead

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/ui/freeplay/SongMenuItem.hx:704: characters 11-28

 704 |       y = <b>MathUtil.coolLerp</b><font color="#AAAAAA">(y, targetPos.y, 0.4);</font>
     |           <font color="#A2734C">^^^^^^^^^^^^^^^^^</font>
     | (WDeprecated) Use smoothLerp instead

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/ui/options/FunkinSoundTray.hx:80: characters 9-26

  80 |     y = <b>MathUtil.coolLerp</b><font color="#AAAAAA">(y, lerpYPos, 0.1);</font>
     |         <font color="#A2734C">^^^^^^^^^^^^^^^^^</font>
     | (WDeprecated) Use smoothLerp instead

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/ui/options/FunkinSoundTray.hx:81: characters 13-30

  81 |     alpha = <b>MathUtil.coolLerp</b><font color="#AAAAAA">(alpha, alphaTarget, 0.25);</font>
     |             <font color="#A2734C">^^^^^^^^^^^^^^^^^</font>
     | (WDeprecated) Use smoothLerp instead

<span style="background-color:#A2734C"><font color="#171421"> WARNING </font></span> source/funkin/ui/story/LevelTitle.hx:57: characters 14-31

  57 |     this.y = <b>MathUtil.coolLerp</b><font color="#AAAAAA">(y, targetY, 0.17);</font>
     |              <font color="#A2734C">^^^^^^^^^^^^^^^^^</font>
     | (WDeprecated) Use smoothLerp instead

<font color="#A2734C"><b>Warning:</b></font> <b>Could not find template file: bin/hl/Linux64</b>
chmod: cannot access &apos;export/release/hl/bin/Funkin&apos;: No such file or directory

</pre>

**Comment by NotHyper-474** [comment]
I also tried this before, eventually I found [this](https://community.haxe.org/t/failed-to-compile-haxe-feathersui-project-in-hashlink/4221/2) comment which, albeit solves that issue, leaves me with another.

So I don't think building with HashLink on Linux is possible at the moment, and even on Windows it's quite buggy.

**Comment by NotHyper-474** [comment]
It could be that I was trying latest HashLink when apparently current Lime doesn't seem to support it: * https://github.com/openfl/lime/pull/1801

**Comment by galleniz** [comment]
So?

**Comment by NotHyper-474** [comment]
So what? I already linked to a fix. It might not work though.

**Comment by NotHyper-474** [comment]
[Update] I found a way to fix the other issue, I think.

If, when testing the game, you get a segfault after rebuilding HashLink or the error mentioned here: https://github.com/HaxeFoundation/hashlink/issues/590 when using the prebuilt binaries provided [here](https://github.com/HaxeFoundation/hashlink/releases) then you can fix those by building with the `-Dno_ssl` flag (i.e `lime test hl -Dno_ssl`)

**Comment by galleniz** [comment]
Thanks ^^

**Comment by NotHyper-474** [comment]
You're welcome. Also if you just want to play the game then you can download my build provided [here](https://github.com/NotHyper-474/Funkin-Legacy-Linux/releases/tag/v0.4.1)

**Comment by galleniz** [comment]
tyy:3
