### ISSUE TITLE
Bug Report: Lower accuracies can sometimes save over better ones!

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#3110]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

I finally got a good score on Spookeez Erect (97%), and wanted to try for even higher, so I played the song again. It was bad run, and I only got a 92. when I went back out to freeplay, the 92 has _saved over_ my 97, even though my high-score didn't even change! I have NO IDEA what caused this sorry, but I thought I'd report it anyways.

### Steps to reproduce (or crash logs, errors, etc.)

1. Play a song and get an accuracy score
2. Get an accuracy lower than that
3. Repeat till it works I guess, I really don't know why this happend

**Comment by NotHyper-474** [comment]
Wasn't this already reported in #2821?

**Comment by Average-FNF-Modder** [comment]
> Wasn't this already reported in #2821?

Hm, I suppose it is. Though in my experience it doesn't happen every time like it does for them.

**Comment by Cartridge-Man** [comment]
Bud forgot to read the second thing on the checklist

**Comment by Average-FNF-Modder** [comment]
> Bud forgot to read the second thing on the checklist

Well there's a reason I didn't check it off.

**Comment by Cartridge-Man** [comment]
Then just actually DO THAT, like you just have the read the titles at a fast pace or just use the very awesome search bar.

**Comment by Hundrec** [comment]
Resolved in 0.5.1!
