### ISSUE TITLE
Bug Report: Incorrect layering on Week 4

### ISSUE THREAD

**Issue by Kimmmmq** [FunkinCrew/Funkin#312]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [*] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [*] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [*] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Play week 4 lol,
## Please describe your issue. Provide extensive detail and images if possibe.
GF sprite overlaps the foreground car

**Comment by ninjamuffin99** [comment]
OOPS LOL HOW TF I MISS THIS LMAO
will be fixed in next small update later in the day!

**Comment by ninjamuffin99** [comment]
should be solved with 0.2.7.1 patch!
