### ISSUE TITLE
Bug Report: bunch of bullshit when compiling 

### ISSUE THREAD

**Issue by SyncGit12** [FunkinCrew/Funkin#3120]
### Issue Checklist

- [x] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.2.x legacy versions

### Context (Provide images, videos, etc.)

lime test windows -debug

source/NGio.hx:15: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
                                                                                                                        source/NGio.hx:16: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
                                                                 source/NGio.hx:169: characters 25-39 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
                                source/NGio.hx:169: characters 25-39 : ... For optional function argument 'callback'
                                                                                                                    source/NGio.hx:172: characters 30-45 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
                                                                                   source/NGio.hx:172: characters 30-45 : ... For optional function argument 'callback'
                                                                                                                                                                       source/NGio.hx:155: characters 24-33 : () -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
                                                                                                   source/NGio.hx:155: characters 24-33 : ... For optional function argument 'callback'
               source/ui/ModMenu.hx:113: characters 26-34 : String should be Null<polymod.ScanParams>
                                                                                                     source/ui/ModMenu.hx:113: characters 26-34 : ... String has no field apiVersionRule
                source/ui/ModMenu.hx:113: characters 26-34 : ... For optional function argument 'scanParams'
                                                                                                            source/PlayState.hx:69: characters 21-29 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                  source/PlayState.hx:115: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                                                                                                                 source/PlayState.hx:274: characters 22-30 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                                                        source/PlayState.hx:1579: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                source/PlayState.hx:1581: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                                                                                                                source/PauseSubState.hx:32: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                                                          source/PauseSubState.hx:42: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                    source/ChartingState.hx:79: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                                                                                                                      source/ChartingState.hx:357: characters 16-24 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
                                                                                                                 C:/HaxeToolkit/haxe/lib/jsonpath/1,0,0/json/util/ArrayUtil.hx:15: characters 35-48 : Class<thx.Arrays> has no field containsExact
                                                                          C:/HaxeToolkit/haxe/lib/jsonpath/1,0,0/json/util/ArrayUtil.hx:31: characters 25-38 : Class<thx.Arrays> has no field containsExact
                                   C:/HaxeToolkit/haxe/lib/jsonpath/1,0,0/json/util/ArrayUtil.hx:35: characters 25-38 : Class<thx.Arrays> has no field containsExact
                                                                                                                                                                    C:/HaxeToolkit/haxe/lib/jsonpath/1,0,0/json/util/ArrayUtil.hx:48: characters 35-48 : Class<thx.Arrays> has no field containsExact
                                                                                                                             C:/HaxeToolkit/haxe/lib/jsonpatch/1,0,0/json/patch/JSONPatch.hx:78: characters 22-34 : json.JSONData has no field insertByPath
                                                                                   C:/HaxeToolkit/haxe/lib/jsonpatch/1,0,0/json/patch/JSONPatch.hx:106: characters 23-35 : json.JSONData has no field existsByPath
                                          C:/HaxeToolkit/haxe/lib/jsonpatch/1,0,0/json/patch/JSONPatch.hx:109: characters 18-30 : json.JSONData has no field removeByPath
 C:/HaxeToolkit/haxe/lib/jsonpatch/1,0,0/json/patch/JSONPatch.hx:126: characters 18-27 : json.JSONData has no field setByPath (Suggestion: getByPath)
                                                                                                                                                     C:/HaxeToolkit/haxe/lib/jsonpatch/1,0,0/json/patch/JSONPatch.hx:144: characters 23-35 : json.JSONData has no field existsByPath
                                                                                                            C:/HaxeToolkit/haxe/lib/jsonpatch/1,0,0/json/patch/JSONPatch.hx:149: characters 18-30 : json.JSONData has no field removeByPath
                                                                   C:/HaxeToolkit/haxe/lib/jsonpatch/1,0,0/json/patch/JSONPatch.hx:151: characters 22-31 : json.JSONData has no field setByPath (Suggestion: getByPath)
                                               C:/HaxeToolkit/haxe/lib/jsonpatch/1,0,0/json/patch/JSONPatch.hx:169: characters 23-35 : json.JSONData has no field existsByPath
      C:/HaxeToolkit/haxe/lib/jsonpatch/1,0,0/json/patch/JSONPatch.hx:175: characters 22-31 : json.JSONData has no field setByPath (Suggestion: getByPath)
                                                                                                                                                          C:/HaxeToolkit/haxe/lib/jsonpatch/1,0,0/json/patch/JSONPatch.hx:195: characters 27-39 : json.JSONData has no field existsByPath
                                                                                                                 C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/LimeBackend.hx:146: characters 54-55 : Unexpected ?

### Steps to reproduce (or crash logs, errors, etc.)

Install Haxe and dependencies

boom

**Comment by SyncGit12** [comment]
i can't compile any engine too!

**Comment by SyncGit12** [comment]
update

C:/haxelib/polymod/git/polymod/backends/LimeBackend.hx:146: characters 54-55 : Unexpected ?

**Comment by SyncGit12** [comment]
{
	// STATIC:
54	private static var defaultAssetLibraries:Map<String, LimeAssetLibrary>;
55



hmm....

**Comment by AbnormalPoof** [comment]
0.2.x is an outdated and unsupported version, so you won't really receive support here. The only thing I can really advise is downgrading your dependencies, since the code-base is over 3 years old at this point and hasn't been updated to support newer versions of Flixel.

**Comment by SyncGit12** [comment]
dude im tryna make a mod that is based off early builds of fnf

AKA https://github.com/FunkinCrew/Funkin/commits/1.0.0

need absolute fnf veteran help

**Comment by Cartridge-Man** [comment]
Buddy just learn to use HScript and use the latest version of Funkin. Like dude it ain’t that hard, read the modding docs

**Comment by SyncGit12** [comment]
i get it bruh

my pc likes more compiling sm64 than fnf

especially 0.2.x and kade and latest versions of funkin

**Comment by okaysnsil** [comment]
LimeBackend.hx:146: characters 54-55 : Unexpected ?


how tf am i supposed to solve this

**Comment by moxie-coder** [comment]
> LimeBackend.hx:146: characters 54-55 : Unexpected ?
> 
> how tf am i supposed to solve this

use haxe 4.3

**Comment by SyncGit12** [comment]
lit using haxe 4.3

**Comment by xalya-what** [comment]
:/HaxeToolkit/haxe/lib/jsonpatch/1,0,0/json/patch/JSONPatch.hx:195: characters 27-39 : json.JSONData has no field existsByPath

**Comment by EliteMasterEric** [comment]
We do not provide technical support for old versions of the game.
