### ISSUE TITLE
Bug Report: stupid fucking error

### ISSUE THREAD

**Issue by okaysnsil** [FunkinCrew/Funkin#3123]
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

a version idfk

### Context (Provide images, videos, etc.)

C:/HaxeToolkit/haxe/lib/polymod/1,8,0/polymod/backends/LimeBackend.hx:146: characters 54-55 : Unexpected ?

**Comment by moxie-coder** [comment]
use haxe 4.3

**Comment by SyncGit12** [comment]
same error ae
