### ISSUE TITLE
Bug Report: Adding a custom event, playtesting then exiting to charter makes said custom event APPEAR to disappear

### ISSUE THREAD

**Issue by CharGoldenYT** [FunkinCrew/Funkin#3128]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

https://github.com/user-attachments/assets/f42c64e5-12d6-43f0-a76f-8074fedd3569

### Steps to reproduce (or crash logs, errors, etc.)

Go into chart editor

Place any custom Event not from base game

Go back into chart editor (Can crash on github builds)

**Comment by Hundrec** [comment]
Did this behave differently if you returned through the pause menu rather than pressing the chart editor keybind?
Does this still happen on 0.5.2?

**Comment by CharGoldenYT** [comment]
idk about 0.5.2, but in 0.5.3 the bug is indeed fixed.
