### ISSUE TITLE
Enhancement: Daddy Dearest Losing Icons for Weeks 1/5.

### ISSUE THREAD

**Issue by Darkness8374939** [FunkinCrew/Funkin#3133]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

There is no losing Icon for Daddy Dearest currently, maybe he could have one.

Current Icon:
![IMG_1782](https://github.com/user-attachments/assets/81b2303d-d87c-4d28-9439-ad83e1e8dd2b)

**Comment by AbnormalPoof** [comment]
Quote from Eric in #3048:

> Not currently planned, and even if it was we wouldn't use other people's art for it.

**Comment by Darkness8374939** [comment]
Oh, thanks for letting me know!
