### ISSUE TITLE
Week 5 sprite issue?

### ISSUE THREAD

**Issue by SpiroThe96th** [FunkinCrew/Funkin#3135]
### Issue Checklist

- [x] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Firefox

### Version

0.4.1

### Context (Provide images, videos, etc.)

I was replying Week 5 on Newgrounds and I saw that the up sprite for when Daddy Dearest sings is erroneously cut?
![Screenshot 2024-09-06 at 11-46-57 FRIDAY NIGHT FUNKIN'](https://github.com/user-attachments/assets/d226cf01-3b0b-442b-8e11-93cd95dcaa53)

Oh, and Mommy Mearest's up sprite just straight up disappears
![Screenshot 2024-09-06 at 12-03-06 FRIDAY NIGHT FUNKIN'](https://github.com/user-attachments/assets/70770099-0c65-4760-9c7b-cec6f9db3518)

Here's some footage:

https://github.com/user-attachments/assets/b146fd93-c2cc-49bb-9e3f-daf4eb906cb2

Am I the only one who has this issue?

**Comment by AbnormalPoof** [comment]
This is a memory issue on your end, not an issue with the game.

**Comment by Hundrec** [comment]
You should close this issue for the reason above.
