### ISSUE TITLE
Bug Report: onSubStateOpenEnd not called when entering ResultState

### ISSUE THREAD

**Issue by lemz1** [FunkinCrew/Funkin#3136]
### Issue Checklist

- [x] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

I made a script that overrides `onSubStateOpenEnd`, for some reason it doesn't work with the ResultState. I know that it is not the script that is the problem, because when entering playmode from chart editor the `onSubStateOpenEnd` event gets  called.

**Comment by AbnormalPoof** [comment]
Fixed in v0.5.1.
