### ISSUE TITLE
Bug Report: boyfriend's V pose with the gameover screen

### ISSUE THREAD

**Issue by Bambi-the-guy** [FunkinCrew/Funkin#3137]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Microsoft Edge

### Version

ex. 0. 4. 1

### Context (Provide images, videos, etc.)

so one time when i was playing FNF and i was playing the song "bopeebo", i wanted to get a perfect score and i messed up a bit and i clicked the reset button when boyfriend was doing his V pose. y'know, the one where he says "hey!" to the rhythm of the song. and i think that it kinda glitched cuz the gameover screen was just the sprite of boyfriend doing the v pose while the background was normally black and no music started playing, i was a bit confused so i wanted to report this issue cuz i love the game 👍  :) this is how it looks btw
![help](https://github.com/user-attachments/assets/3c516c87-fd01-43ea-9fd0-63a0c4861038)

**Comment by AbnormalPoof** [comment]
already reported in #2319

**Comment by Bambi-the-guy** [comment]
Oh shit my bad bro

sob., 7 wrz 2024, 17:43 użytkownik Abnormal ***@***.***>
napisał:

**Comment by ninjamuffin99** [comment]
yes should be fixed and in our upcoming update, thank you for report though :)
