### ISSUE TITLE
Bug Report: Spirit's trail is placed incorrectly

### ISSUE THREAD

**Issue by CrusherNotDrip** [FunkinCrew/Funkin#3144]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Spirit's FlxTrail is off from the original spirit position.
![image](https://github.com/user-attachments/assets/20e2e03f-ffe8-439d-89c2-cc9e981d9901)

### Steps to reproduce (or crash logs, errors, etc.)

Go to thorns.

**Comment by EliteMasterEric** [comment]
Confirmed

**Comment by EliteMasterEric** [comment]
IDK why this was closed it's still a thing

**Comment by Hundrec** [comment]
Fixed in 0.5.1

**Comment by CrusherNotDrip** [comment]
This was fixed in 0.5.1 so I'm closing this

**Comment by CrusherNotDrip** [comment]
> Fixed in 0.5.1

bro its like we were in the same place at the same time
