### ISSUE TITLE
Bug Report: Player can die during Week 3 (Pico Mix) cutscenes, causing weird bugs

### ISSUE THREAD

**Issue by CrusherNotDrip** [FunkinCrew/Funkin#3146]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

I was messing around and I died during a cutscene (via RESET bind) and discovered this bug.
the picos are taking over planet earth as we know it.

oh and the game crashes too but I think its because the song plays with the chart during the cutscene after death as well

![image](https://github.com/user-attachments/assets/6f894ba5-a256-465b-944e-0f829bbac6f7)

### Steps to reproduce (or crash logs, errors, etc.)

- Freeplay
- Select Pico as character
- Go to one of the songs with pico in it
- Press RESET during cutscene
- Respawn

**Comment by EliteMasterEric** [comment]
Confirmed. This is the oldest issue so others will be marked as duplicates
