### ISSUE TITLE
Bug Report: Chart Editor is completely broken (does not allow placing notes)

### ISSUE THREAD

**Issue by AbnormalPoof** [FunkinCrew/Funkin#3147]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - MacOS

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Title explains itself.

https://github.com/user-attachments/assets/2fd64951-ffeb-403c-b263-321dba26a7ed

**Comment by EliteMasterEric** [comment]
Confirmed.

**Comment by AbnormalPoof** [comment]
Live input mode still appears to work.

**Comment by XenonHedgehog** [comment]
this also applies on animation editor and stage editor

**Comment by AbnormalPoof** [comment]
Stage Editor is a mess right now, so there's pretty much no need to focus on that. For the Animation Editor, I opened a separate issue (#3151).

**Comment by AbnormalPoof** [comment]
This is fixed in v0.5.1!! Thank god I can chart more vocaloid songs now lol
