### ISSUE TITLE
Bug Report: DadBattle (Pico Mix) is missing Normal and Easy charts

### ISSUE THREAD

**Issue by arhaansday** [FunkinCrew/Funkin#3149]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Opera

### Version

0.4.1

### Context (Provide images, videos, etc.)

In all the difficulties in Dadbattle (Pico Remix), the notes aren't showing up.
![Screen Shot 2024-09-13 at 7 52 53 AM](https://github.com/user-attachments/assets/5bd1f6f8-4332-49a5-95ef-5c32811e9baf)

### Steps to reproduce (or crash logs, errors, etc.)

Play Dadbattle (Pico remix) on any difficulty.

**Comment by EliteMasterEric** [comment]
Just checked and this is definitely not happening on hard, just normal and easy. Still verified though.

Since this is the oldest issue reporting it I'll mark anything else as duplicate.

**Comment by Hundrec** [comment]
Maybe the real duplicate was the songs we charted along the way
