### ISSUE TITLE
Bug Report: The game will not load

### ISSUE THREAD

**Issue by BritterBanner** [FunkinCrew/Funkin#315]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [x] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [x] macOS

**Comment by imfunkinrn** [comment]
im using a chromebook on newgrounds chrome browser and it just freezes halfway through no warning or anything it just stops.

**Comment by imfunkinrn** [comment]
version 4.8.1
