### ISSUE TITLE
Bug Report: Pico Intro Cutscene does not stop player input.

### ISSUE THREAD

**Issue by saturn-volv** [FunkinCrew/Funkin#3152]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

One of my note keybinds is "Z", same as the skip cutscene keybind, so the player can lose score for skipping the cutscene.

### Steps to reproduce (or crash logs, errors, etc.)

- Set a note keybind to Z
- Skip Pico Mix Intro on Pico songs

**Comment by EliteMasterEric** [comment]
Duplicate of #3146
