### ISSUE TITLE
Bug Report: the camera for hating simulator is very unsmooth 

### ISSUE THREAD

**Issue by MTB207** [FunkinCrew/Funkin#3153]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Opera

### Version

0.5.0

### Context (Provide images, videos, etc.)

when you load into any senpai levels the camera will move very roughly (noticed this when checking out the erect remix for any stage changes)

**Comment by AbnormalPoof** [comment]
This is due to Week 6 now being rendered pixel-perfect. (See #2534)

**Comment by MTB207** [comment]
> This is due to Week 6 now being rendered pixel-perfect. (See #2534)

damn it sure messes with your eyes when you play it, especially for erect mode which has a lot of camera work

**Comment by JackXson-Real** [comment]
> > This is due to Week 6 now being rendered pixel-perfect. (See #2534)
> 
> damn it sure messes with your eyes when you play it, especially for erect mode which has a lot of camera work

I agree, it looks too weird imo

**Comment by EliteMasterEric** [comment]
Rejected: not a bug
