### ISSUE TITLE
Crash Report: 

### ISSUE THREAD

**Issue by Fasade03** [FunkinCrew/Funkin#3154]
### Issue Checklist

- [x] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide screenshots or videos of the crash happening)

![Screenshot 2024-09-12 235705](https://github.com/user-attachments/assets/fe839063-2374-434b-a6f2-c02b87dab1bd)
I'm unsure if it's a universal bug or just an issue with my computer, but I get this error message when trying to run the Windows build of FNF. The game window will appear but will crash before any of the intro text appears.

### Steps to reproduce

Just downloaded the build and tried to run it.

### Crash logs (can be found in the logs folder where Funkin.exe is)

[CHANGELOG.md](https://github.com/user-attachments/files/16988366/CHANGELOG.md)
Closest thing I could find, unless I'm looking in the completely wrong place.

**Comment by NotHyper-474** [comment]
Have you tried redownloading?

**Comment by EliteMasterEric** [comment]
It sounds like you need to redownload the game, or re-extract the game from its zip file

**Comment by Fasade03** [comment]
> It sounds like you need to redownload the game, or re-extract the game from its zip file

Did it multiple times last night didn't work then. It's working now, so idk what that was about.
