### ISSUE TITLE
Bug Report: pico doesnt have any shooting animations in stress

### ISSUE THREAD

**Issue by MTB207** [FunkinCrew/Funkin#3155]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Opera

### Version

0.5.0

### Context (Provide images, videos, etc.)

checked to see if the naughtyness mode affects week 7 (spoiler alert: it doesn't), turns out pico refuses to shoot anyone now
![image_2024-09-13_070935702](https://github.com/user-attachments/assets/554b2bfd-8076-466f-b2a2-6e89284b8e26)

### Steps to reproduce (or crash logs, errors, etc.)

just play stress

**Comment by PlazmaZX** [comment]
Yes, I also saw this while playing story mode stress (hard) and I'm on OSX, restarting the song doesn't do anything either, nor does freeplay. So I'm assuming it has something to do with the chart. afterwards I checked easy and normal difficulties and they also have pico doing no animations.

**Comment by Nomi07R** [comment]
Same here, playing on Win x64, Pico just sits on the speaker and spins his gun lol.
