### ISSUE TITLE
Bug Report: Spirit's after-images are placed incorrectly

### ISSUE THREAD

**Issue by GenesisGreen** [FunkinCrew/Funkin#3158]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

The after-images that Spirit has while singing are misplaced, appearing above, below, to the left, or to the right of the character. I tested this in both Thorns and Thorns Erect and both had the same problem.
![image](https://github.com/user-attachments/assets/64d847c5-5df5-46b7-bc3a-4675bbba8b31)

https://github.com/user-attachments/assets/f95446bb-2736-4202-a2ff-c4965c7882c3

### Steps to reproduce (or crash logs, errors, etc.)

Play Thorns or Thorns Erect, I've only tested it through freeplay but I assume it'd also happen through Story Mode

**Comment by AbnormalPoof** [comment]
already reported in #3144

**Comment by EliteMasterEric** [comment]
Closed as duplicate
