### ISSUE TITLE
Game crashes at startup

### ISSUE THREAD

**Issue by davidlikesgames** [FunkinCrew/Funkin#316]
Everytime i start the game on the 64 bit version it crashes and says valueException
On the 32 bit version it says that the game stopped respoding
Please help i really wanna play the friday night funkin.

**Comment by devin503** [comment]
are you starting the game via a command prompt/powershell window? if so, make sure the prompt is showing the **root** directory of your game folder, i.e. `C:\Users\devin503\funkin-windows-64bit`, and not a folder outside or inside it.
![image](https://user-images.githubusercontent.com/41199354/106661892-c113af00-656f-11eb-8055-713e1af735c4.png)

**Comment by em69420hahafunnyplslaugh** [comment]
I’m getting the same issue but it’s from double clicking the application, how do I fix that?

**Comment by devin503** [comment]
> I’m getting the same issue but it’s from double clicking the application, how do I fix that?

Please create a new issue.
