### ISSUE TITLE
Bug Report: Ugh is named Ugh Erect on Normal and Hard Mode after playing Pico then changing to BF

### ISSUE THREAD

**Issue by ytggobs** [FunkinCrew/Funkin#3160]
### Issue Checklist

- [X] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

![image](https://github.com/user-attachments/assets/02c56179-a069-4613-a5e4-02c05a19db48)
![image](https://github.com/user-attachments/assets/20b33a16-1faa-4fa8-a151-04c71abe0c49)
![image](https://github.com/user-attachments/assets/42b1eef6-0ad9-4cdd-82b1-86cecea764f2)

### Steps to reproduce (or crash logs, errors, etc.)

Change to Pico, play a song, change back to Boyfriend (can also be reproduce like #3210 )

**Comment by JackXson-Real** [comment]
Can confirm this happens

**Comment by ADA-Funni** [comment]
I've got the same issue. 😭

**Comment by ADA-Funni** [comment]
![image](https://github.com/user-attachments/assets/f946efff-1c08-48d2-8bcf-27b7040ad402)
![image](https://github.com/user-attachments/assets/a1667205-dc65-443d-8b39-a42e33cf8ac4)

**Comment by GoombarioFan** [comment]
Seems to be fixed as of 0.5.2!
