### ISSUE TITLE
Bug Report: Unlocked character doesnt save upon restart

### ISSUE THREAD

**Issue by JackXson-Real** [FunkinCrew/Funkin#3165]
### Issue Checklist

- [x] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Every time you restart the game, you have to see the same animations for pico being unlocked (both the freeplay menu one and the character select one.) The ranks on the songs do save though.

### Steps to reproduce (or crash logs, errors, etc.)

Restart game and enter freeplay menu.

**Comment by EliteMasterEric** [comment]
Confirmed

**Comment by losferra** [comment]
r

**Comment by EliteMasterEric** [comment]
Resolved internally
