### ISSUE TITLE
Bug Report: Duplicate boyfriend in character select menu

### ISSUE THREAD

**Issue by JackXson-Real** [FunkinCrew/Funkin#3169]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Read title, here is a video:

https://github.com/user-attachments/assets/d95388f0-d2d6-4bdf-84b3-6985280aeb33

### Steps to reproduce (or crash logs, errors, etc.)

Enter character select menu and look at boyfriend, it seems more likely to happen if you enter it when boyfriend is already selected, but I havent tested much.

**Comment by Hundrec** [comment]
The character select screen looks great in 0.5.2!
We can close this one.
