### ISSUE TITLE
Character select Bug Report: After playing a song with BF, if you switch to Pico, there are no songs in Freeplay.

### ISSUE THREAD

**Issue by Prod-42** [FunkinCrew/Funkin#3171]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

5.0.0

### Context (Provide images, videos, etc.)

When you finish a song with BF and then switch to Pico the songs don't show up in free play, changing the difficulty seems to make the songs appear again but the bug can reoccur.

There's also a small chance that the game will crash after exiting the freeplay menu when the bug occurs. I tried to replicate the crash a third time, but the recording doesn't capture the moment when it crashes.

### Steps to reproduce (or crash logs, errors, etc.)

1. Open freeplay
2. Play a song with BF
3. Go back to freeplay
4. Select Pico
5. There's no songs in freeplay!!

https://github.com/user-attachments/assets/37cb585f-d825-4ebb-9771-ff9d60276185

**Comment by Hundrec** [comment]
This bugged behavior has been consistent for me whenever I switch to Pico. Pressing right arrow to switch to Hard brings all the songs back for now!

**Comment by JackXson-Real** [comment]
> This bugged behavior has been consistent for me whenever I switch to Pico. Pressing right arrow to switch to Hard brings all the songs back for now!

same

**Comment by Verwex** [comment]
Looked into it and it's very much consistent in only erect difficulties (erect and nightmare). You don't even have to play any erect song, you just... need to have the difficulty set into one of the two.

I guess the game does not know that the Pico mixes doesn't have erect difficulties and doesn't have a fallback???

**Comment by Hundrec** [comment]
We have an entirely new issue in 0.5.1 now... 
Hopefully 0.5.2 fixes it for good!

**Comment by Prod-42** [comment]
It seems like this got fixed in the new update!

I'm closing this now.
