### ISSUE TITLE
Enhancement: Add "Unlock FPS" option from browser to desktop version

### ISSUE THREAD

**Issue by JackXson-Real** [FunkinCrew/Funkin#3173]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

Im surprised it hasnt been added yet, desktop is stuck at 168fps and feels much more choppy compared to browser now. Also it would be cool to just have a slider to allow you to choose your max FPS.

**Comment by EliteMasterEric** [comment]
See #2602
