### ISSUE TITLE
Bug Report: picoChristmasDeath renders Retry and Nene in wrong position

### ISSUE THREAD

**Issue by Hundrec** [FunkinCrew/Funkin#3179]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0 - 0.5.3

### Context (Provide images, videos, etc.)

Pico's Christmas death animation renders an offset "Retry"
![image](https://github.com/user-attachments/assets/989790f4-380d-4f02-a168-510078925569)

...and Nene renders too low
![image](https://github.com/user-attachments/assets/2b45d8d9-8435-4f9b-90c8-533d6ca384e3)

### Steps to reproduce (or crash logs, errors, etc.)

Die in Eggnog (Pico Mix).

**Comment by FourLion4L** [comment]
Same issue in the Newgrounds' version
![Screenshot from 2024-09-13 09-56-45](https://github.com/user-attachments/assets/e5a38973-d0ce-41f9-974e-58df011cee78)

**Comment by ninjamuffin99** [comment]
thank you very much, when this issue is closed it means this should be fixed internally!
