### ISSUE TITLE
Bug Report: I play Friday Night Funkin on a Mac computer so i cant play week 6 

### ISSUE THREAD

**Issue by ThatOneGuyNamedKahron** [FunkinCrew/Funkin#318]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [x] macOS

**Comment by devin503** [comment]
you can compile the game yourself as well

**Comment by hdboye** [comment]
Why do you need to download it? The web version works just fine with Week 6. Play that until NinjaMuffin publishes the mac version or as devin said compile the game yourself.
