### ISSUE TITLE
Bug Report: Week 6 Snappy Backgrounds

### ISSUE THREAD

**Issue by anysad** [FunkinCrew/Funkin#3183]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

* When playing Week 6, the backgrounds feel really snappy and glitchy, which was NOT an issue pre 0.5.0 update. Also, there is a bug with the fucked up FlxTrail for spirit, which was also reported in https://github.com/FunkinCrew/Funkin/issues/3144 (just showing video evidence as well)

https://github.com/user-attachments/assets/890a2baf-9b3d-4a76-8835-bdbe42bc556b

* This is how the background was pre-update. Feeling much smoother and better than now.

https://github.com/user-attachments/assets/71249554-a526-4e28-9301-998774d41638

### Steps to reproduce (or crash logs, errors, etc.)

Just... play week 6, each and every song, that's it.

**Comment by usb-port-2** [comment]
...this is intentional

**Comment by anysad** [comment]
you sure?

**Comment by anysad** [comment]
nvm, just saw it.
