### ISSUE TITLE
Enhancement: You should make Friday Night Funkin for Nintendo Switch and Playstation 4 and 5 and plus every 2 or 3 fridays there should be a new Week update

### ISSUE THREAD

**Issue by ThatOneGuyNamedKahron** [FunkinCrew/Funkin#319]
# Please check for duplicates or similar issues before creating this issue.

**Comment by regulad** [comment]
IIRC there was a switch pitch a while ago but I doubt it's going to go through since the game is open source. Also there has been a new level every couple of weeks.

**Comment by Salladk-but-no-mo-flaged** [comment]
its expensive upload a game in worldwide consoles

PSN: $5000
NINTENDO: possibly free
XBOX: same to nintendo

**Comment by polybiusproxy** [comment]
I will explain this:
It is possible building FNF for X?

- PlayStation: **no**.
- Nintendo Switch: **yes!**
- Nintendo Wii U: **it was possible, but for legal reasons, it isn't now**.
- Xbox One: **same with wii u**.

About PS5 and Xbox Series X & S, there isn't any way to build lol.

**Comment by nickpythonluajava** [comment]
> I will explain this:
> 
> It is possible building FNF for X?
> 
> 
> 
> - PlayStation: **no**.
> 
> - Nintendo Switch: **yes!**
> 
> - Nintendo Wii U: **it was possible, but for legal reasons, it isn't now**.
> 
> - Xbox One: **same with wii u**.
> 
> 
> 
> About PS5 and Xbox Series X & S, there isn't any way to build lol.

im confused, if the nintendo switch is allowed for you to build for, then why not the wii u?

**Comment by polybiusproxy** [comment]
Because, Wii U backend was using third party licenses and those are
outdated now. Same with PS4 and Xbox.

**Comment by Windows1Door2Daniel** [comment]
i saw mufin tried to put fnf to switch

but got rejected by NinJa
