### ISSUE TITLE
Bug Report: Sprilt

### ISSUE THREAD

**Issue by ender69funk** [FunkinCrew/Funkin#3192]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5

### Context (Provide images, videos, etc.)

![image](https://github.com/user-attachments/assets/7daf7db8-7c51-42f3-bfa3-b3e5e760583a)

### Steps to reproduce (or crash logs, errors, etc.)

just play thorns and u get this

**Comment by AbnormalPoof** [comment]
already reported in #3144. please actually do the second checkmark next time

**Comment by ender69funk** [comment]
> already reported in #3144. please actually do the second checkmark next time

Thanks for saying that. I will close this issue
