### ISSUE TITLE
Bug Report: Makeing Web Ports Ruins The Engine 

### ISSUE THREAD

**Issue by chickeniscoolest** [FunkinCrew/Funkin#3194]
### Issue Checklist

- [x] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

im a coder fellow fnf fan i like to play this game at school but i cant play anything because its blocked 
so me and my friend copied the assets for the newgrounds website and we started to play the game
when you play a song thats been modified the songs notes dissapear at 10% and we get the results shit animation 
so we also press tab to get the menu but the screen was all black    
-Bubba osu

**Comment by AbnormalPoof** [comment]
Not a bug.

**Comment by chickeniscoolest** [comment]
yes it is i ant even play the game

**Comment by chickeniscoolest** [comment]
*cant

**Comment by AbnormalPoof** [comment]
It isn't a bug in the sense that you are using an unofficial build to run the HTML5 version. Do stuff like that at your own risk!
