### ISSUE TITLE
Bug Report: Title Screen Sys.exit(0) Halting Issue

### ISSUE THREAD

**Issue by Blue2359** [FunkinCrew/Funkin#3196]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

The Title Screen itself can halt after pressing the `ESCAPE` Key to exit the game by calling the `Sys.exit(0)` method, but it instead just proceeds to halt the entire game itself; without exiting/closing the window instance.

![image](https://github.com/user-attachments/assets/0a98c53a-e541-4657-af1e-735fdd3f7ee9)

### Steps to reproduce (or crash logs, errors, etc.)

TitleState.hx => Press ESCAPE: The re-production method.

**Comment by NotHyper-474** [comment]
Confirmed.

**Comment by Hundrec** [comment]
Truly a tragedy for the exit game shortcut
![image](https://github.com/user-attachments/assets/4bbe1cd7-a9fe-4df9-9bf5-d36cba090596)

**Comment by Blue2359** [comment]
Now that I think about it, this might be happening because of the crash handler system or whateva' they got goin' on, since thrown exceptions in the 0.5.0 update; ***(for example, a null obj ref exception inheriting from a scripted/module file)*** no longer causes the game to close, instead they also cause the game to halt.

**Comment by amyspark-ng** [comment]
still happens in 0.5.1, very sad

**Comment by NotHyper-474** [comment]
I knew it, it's an issue with Lime: https://github.com/openfl/lime/issues/1803

**Comment by AbnormalPoof** [comment]
Is this a Windows-only issue? I can't reproduce this one on macOS.

**Comment by NotHyper-474** [comment]
I can't reproduce it on Linux either so I believe so.

**Comment by NotHyper-474** [comment]
Does this still happen in 0.5.2?

**Comment by amyspark-ng** [comment]
nope on my part!

**Comment by Hundrec** [comment]
Yay, pressing escape on the title screen now exits instantly!

**Comment by NotHyper-474** [comment]
While this bug has been solved in Funkin' using a workaround (0d60929f187864122b691fb2106f58d211adec18) the underlying issue on Lime has been resolved too: https://github.com/openfl/lime/commit/6a4099861e1ed4d2b4703248db0a2df321f277b1 which means Funkin's Lime repo can just be fast-forwarded.

Also I think this should be closed since, well, it's been resolved.

**Comment by Blue2359** [comment]
Alrighty then, I'll be closing the issue if it's been resolved, thanks!
