### ISSUE TITLE
Crash Report: Crashes after load

### ISSUE THREAD

**Issue by vivi-dly** [FunkinCrew/Funkin#3197]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - MacOS

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide screenshots or videos of the crash happening)

After it finishes loading up and completes the "Finishing up" and 11/11 section, it crashes immediately with no pop up saying it crashed. Also takes a while to load up. Can't find crash logs either. On latest version of macOS Sonoma.

### Steps to reproduce

Itch.io download for MacOS from Safari and launch from downloads.

### Crash logs (can be found in the logs folder where Funkin.exe is)

Cannot find crash logs.

**Comment by AbnormalPoof** [comment]
Already reported in #2236. Run the game through the terminal once to fix the issue for now.
