### ISSUE TITLE
Music problems while playing on the itch.io and Newgrounds versions

### ISSUE THREAD

**Issue by Nathanstillexists** [FunkinCrew/Funkin#32]
Hello there! First off, great game. Will play it for hours if I could. There is a small problem.

Bopdeepo has an awkward (but rather funny) bug when it ends. The dad just seems to play a random note a couple times as the songs change to Fresh. It sounds like he's singing multiple right key notes.

Also, during Bopdeepo, The dad has a random purple note after a long red note, but the player doesnt have that. 

Im sure you guys/gals/whatever you decide to be identified as (not judging) can fix it up no problem.

Again, love the game and the music.

Take care!

**Comment by gedehari** [comment]
Yep can confirm it happened to me too
