### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Maks7594** [FunkinCrew/Funkin#320]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.
I'm not playing on the browser.
## Where are you playing the game?
Downloaded onto SSD.
### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [✓] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
On the main menu, go to Story Mode and Week 6. When the textbox appears, press R. The game crashes
## Please describe your issue. Provide extensive detail and images if possible.
When you die on the textbox, the game crashes/stops responding.

**Comment by regulad** [comment]
I was able to reproduce by pressing `R` on the first dialogue box. (Windows `x86_64`)
