### ISSUE TITLE
Bug Report: The character in the character select menu doesn't update properly

### ISSUE THREAD

**Issue by amyspark-ng** [FunkinCrew/Funkin#3201]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

When entering the character select menu and moving to the left to select pico. the character doesn't update leaving you like this
![image](https://github.com/user-attachments/assets/718eda77-9963-4b9b-90b2-66da2fe5a638)

you have to move to boyfriend again, and then pico so it updates properly and shows pico

ALSO NOT SURE IF IT'S A BUG but when you're playing as pico and go to character select screen the cursor will be on boyfriend and not pico (the character you're currently playing as) it kinda bothers me

**Comment by GoombarioFan** [comment]
I've replicated this by immediately switching to Pico as soon as the choose menu loads in. This also creates an overlapping effect on Boyfriend's animation that can be seen in #3220. This bug is purely visual since Pico is still selected if you select him while Boyfriend/Girlfriend are present.

**Comment by AbnormalPoof** [comment]
Fixed in v0.5.2.

**Comment by amyspark-ng** [comment]
yup
