### ISSUE TITLE
Bug Report: The NEW UNLOCK! anim appears every time

### ISSUE THREAD

**Issue by amyspark-ng** [FunkinCrew/Funkin#3202]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Everytime i open the game i get the NEW UNLOCK! animation on freeplay even though i already beat the pico songs

**Comment by AbnormalPoof** [comment]
Already reported in #3165

**Comment by amyspark-ng** [comment]
oh sorry
