### ISSUE TITLE
Crash Report: Game crashes on closing

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3209]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide screenshots or videos of the crash happening)

the game crashes when you try to exit the game with ESC in the start menu with GF

### Steps to reproduce

When opening the game, just click ESC (it closes the game)

### Crash logs (can be found in the logs folder where Funkin.exe is)

There is no crashlog
[NoCrashLog.txt](https://github.com/user-attachments/files/16997576/NoCrashLog.txt)

**Comment by Hundrec** [comment]
Well that's one way to fulfill #2807!

**Comment by Hundrec** [comment]
Actually, I think you're reporting the same issue as https://github.com/FunkinCrew/Funkin/issues/3196

**Comment by SnowyyWHY** [comment]
> Actually, I think you're reporting the same issue as #3196

oh yea, let me close this then
