### ISSUE TITLE
Bug Report: Sometimes when you finish Thorns Flash/HTML5(whichever it is) crashes.

### ISSUE THREAD

**Issue by Polydank** [FunkinCrew/Funkin#321]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [x] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [x] Windows x86_64
- [ ] Linux
- [ ] macOS

**Comment by Templarfreak** [comment]
Can you be more specific? "Sometimes crashes" is not very easy to pinpoint down. :D
