### ISSUE TITLE
Ugh ERECT appears on normal and hard after been played

### ISSUE THREAD

**Issue by JustJasonLol** [FunkinCrew/Funkin#3210]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

image and video should explain

https://github.com/user-attachments/assets/52a76bfa-c7d2-4960-a9bf-b14ddb0342ff

### Steps to reproduce (or crash logs, errors, etc.)

- choose ugh erect (nightmare in my case)
- beat it
- after going to the freeplay menu change the difficulty and erect will still show alongside it's instrumental playing

this is more of a visual bug (as pressing enter plays the normal ugh) but still wanted to report it

**Comment by Hundrec** [comment]
Also reported in #3160

**Comment by Hundrec** [comment]
This issue has been resolved, so you should close it now!
