### ISSUE TITLE
[5.0.0] Character unlock intro sequence plays upon restarting the game.

### ISSUE THREAD

**Issue by rrev07** [FunkinCrew/Funkin#3211]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

5.0.0

### Context (Provide images, videos, etc.)

https://github.com/user-attachments/assets/d9a99f46-405e-4e25-a720-58016ab344c9

### Steps to reproduce (or crash logs, errors, etc.)

Open the game>Go to freeplay>Press tab>Select pico>restart game

**Comment by AbnormalPoof** [comment]
already reported in #3165
