### ISSUE TITLE
Bug Report: Boyfriends songs percentage and score saves onto pico mixes

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3214]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

So if you have for example 67% on dadbattle, it saves for pico the 67% (as you can see on those screenshots)
Also the score too
![Zrzut ekranu 2024-09-13 204629](https://github.com/user-attachments/assets/2d8f5600-c3ef-4937-86eb-192515468ea8)
![Zrzut ekranu 2024-09-13 204709](https://github.com/user-attachments/assets/3276f2af-2fe9-4936-9245-672fb1a665df)

**Comment by NotHyper-474** [comment]
Already reported in https://github.com/FunkinCrew/Funkin/issues/3145

**Comment by Hundrec** [comment]
Original issue resolved in 0.5.1
