### ISSUE TITLE
Bug Report: Swapping the playable character causes a song percentage visual bug

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3215]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

so as you can see, the percentage of song is normal on the first screenshot, but its broken when you swap a character (as you can see on the second screenshot)
![Zrzut ekranu 2024-09-13 205143](https://github.com/user-attachments/assets/d7d906de-7e05-4036-810b-c40793ad8b7c)
Broken one, works in to ways (from pico to boyfriend, from boyfriend to pico)
![Zrzut ekranu 2024-09-13 205249](https://github.com/user-attachments/assets/c959bf7e-2a90-4c81-9b8f-5eed06a9e32c)

### Steps to reproduce (or crash logs, errors, etc.)

switch a character to an other one

**Comment by ttheng3810** [comment]
I also encountered the same issue in the Newgrounds version.

**Comment by Hundrec** [comment]
Percentage display (and scores) fixed in 0.5.1!
