### ISSUE TITLE
Bug Report: Week 3 Pico Cutscene has noticable black outlines along the sprites

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3216]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Some black outlines appear for some parts of pico, example screenshots:
![Zrzut ekranu 2024-09-13 205849](https://github.com/user-attachments/assets/43d9995d-7a6c-4f86-93a7-7d72b2ec8550)
![Zrzut ekranu 2024-09-13 205901](https://github.com/user-attachments/assets/e5b8d6d5-f557-4c1c-b634-026327dabcba)
![Zrzut ekranu 2024-09-13 210119](https://github.com/user-attachments/assets/f6cf2acb-2c38-4a73-a2df-6ec4622671eb)

### Steps to reproduce (or crash logs, errors, etc.)

go to any week 3 pico mix song and watch the cutscene

**Comment by EliteMasterEric** [comment]
NOTE: This was also seen in #3390 to occur on the lock sprite in Character Select.

**Comment by SnowyyWHY** [comment]
![image](https://github.com/user-attachments/assets/6c34e6ac-8499-4be7-b8f3-e739aa15d805)
this too

**Comment by Hundrec** [comment]
I actually can't make out what that is. Can you provide a full image?

**Comment by NotHyper-474** [comment]
Seems like it's the sprite of Pico with his blown out head bleeding

**Comment by Hundrec** [comment]
Ohh that makes sense, thanks!

**Comment by ninjamuffin99** [comment]
I believe we fixed this internally and it will be in the next update, thanks!
