### ISSUE TITLE
Bug Report: Boyfriend Dupping in Character Select and +

### ISSUE THREAD

**Issue by daniyusk** [FunkinCrew/Funkin#3220]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

So, I don't know **why**, but when I switched characters, BF got duplicated into two. Another thing I noticed is that, for some reason, Pico is selected there even though I'm seeing BF and not Pico. 

Here is the screenshot:

![image](https://github.com/user-attachments/assets/76584526-df4f-487b-9f5f-e373636a7bb1)

**Comment by Hundrec** [comment]
This is fixed in 0.5.2
Please close this issue.
