### ISSUE TITLE
Bug Report: mods folder doesn't work anymore

### ISSUE THREAD

**Issue by MidyGamy** [FunkinCrew/Funkin#3221]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

So I dropped mods I'm working on from the 0.4.1 to the newest one, but it's not getting loaded anymore
(btw I tried using a mod replacing already existing assets, doesn't work either)

**Comment by NotHyper-474** [comment]
The API version has changed from 0.1.0 to 0.5.0. You need to change the version in your mods accordingly or they won't load.

**Comment by MidyGamy** [comment]
thx
