### ISSUE TITLE
Bug Report: Character Icons In Chart Editor Turned Into Spritesheets

### ISSUE THREAD

**Issue by daniyusk** [FunkinCrew/Funkin#3222]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

5.0.0

### Context (Provide images, videos, etc.)

![image](https://github.com/user-attachments/assets/e150b0ec-3628-4dac-a809-feacb599a0f6)

self explanatory

**Comment by IdealistCat** [comment]
there are now a bunch of mini bfs!!!

**Comment by EliteMasterEric** [comment]
Duplicate of #3148
