### ISSUE TITLE
Bug Report: "Shit" Rating (others unaffected) is Antialiased in Week 6

### ISSUE THREAD

**Issue by CyndaquilDAC** [FunkinCrew/Funkin#3224]
### Issue Checklist

- [x] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Exactly what it says on the tin. No clue how this happened.
![wtf](https://github.com/user-attachments/assets/bac3546d-551a-4a5f-a066-918789bbe33f)

### Steps to reproduce (or crash logs, errors, etc.)

Get a "Shit" rating in week 6. That's it.

**Comment by EliteMasterEric** [comment]
Confirmed

**Comment by EliteMasterEric** [comment]
Resolved internally
