### ISSUE TITLE
Bug Report: Dadbattle Pico Remix Normal and Easy Mode both have no chart

### ISSUE THREAD

**Issue by Goofer529** [FunkinCrew/Funkin#3225]
### Issue Checklist

- [X] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

5.0

### Context (Provide images, videos, etc.)

Easy and Normal both don't have a chart
video attached of normal mode but its the same with easy

https://github.com/user-attachments/assets/19996756-4079-4254-9a23-4bb07d722928

### Steps to reproduce (or crash logs, errors, etc.)

go into easy or normal dadbattle pico mode lmao

**Comment by Goofer529** [comment]
its low quality cause had to put it in a compressor btw lmao

**Comment by picoburpsalot** [comment]
LMAO I LEGIT JUST POSTED A BUG REPORT FOR THIS AS WELL.. MY FRIEND WOULDNT STOP LAUGHING WHEN THEY DIDINT SING

**Comment by Goofer529** [comment]
LMAOOOO

> LMAO I LEGIT JUST POSTED A BUG REPORT FOR THIS AS WELL.. MY FRIEND WOULDNT STOP LAUGHING WHEN THEY DIDINT SING

**Comment by EliteMasterEric** [comment]
Confirmed

**Comment by EliteMasterEric** [comment]
Closing since this is a duplicate of #3149
