### ISSUE TITLE
Bug Report: Week 5 Erect remixes ONLY have lag spikes

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/Funkin#3227]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

There are lag spikes that happen at random in this stage, but only if you play as BF. Mention Settle Into da Metal and Cheems will know what to do.

### Steps to reproduce (or crash logs, errors, etc.)

Play Cocoa or Eggnog Erect. Pico Mix will not suffice.

**Comment by JackXson-Real** [comment]
Already reported in #3161

**Comment by EliteMasterEric** [comment]
Duplicate
