### ISSUE TITLE
Bug Report: Eggnog Pico Mix Gameover - the sprite positions are incorrect

### ISSUE THREAD

**Issue by daniyusk** [FunkinCrew/Funkin#3229]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

5.0.0

### Context (Provide images, videos, etc.)

![image](https://github.com/user-attachments/assets/036127cc-f73e-4247-8cd6-dc0246dd40fe)
I think this 'retry' was supposed to be inside that sprite.

### Steps to reproduce (or crash logs, errors, etc.)

Just die in eggnog.

**Comment by EliteMasterEric** [comment]
Duplicate #3179
