### ISSUE TITLE
Bug Report: freeplay cleared percent box is broken

### ISSUE THREAD

**Issue by 7oltan** [FunkinCrew/Funkin#3230]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

this is after switching the character
![image](https://github.com/user-attachments/assets/74b62e38-c0a1-42c4-91ac-d9a809d2eb66)

also sometimes it shows the wrong percent, i fc'd dadbattle NOT dadbattle pico mix
![image](https://github.com/user-attachments/assets/50f6f29e-c499-4b0a-bd59-39a8fd591182)

**Comment by Hundrec** [comment]
The percent cleared box should now display properly in 0.5.1!

**Comment by 7oltan** [comment]
> The percent cleared box should now display properly in 0.5.1!

closingggggg

**Comment by AbnormalPoof** [comment]
lol how did this get through
