### ISSUE TITLE
Bug Report: Pressing Tab doesn't save

### ISSUE THREAD

**Issue by ADA-Funni** [FunkinCrew/Funkin#3231]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Basically, I have to unlock Pico every time I relaunch the game.

**Comment by AbnormalPoof** [comment]
duplicate of #3165

**Comment by EliteMasterEric** [comment]
Duplicate
