### ISSUE TITLE
Bug Report: if u switch to pico as soon as u click tab in free play his character doesnt load and u see bfs character instead

### ISSUE THREAD

**Issue by ninjarecroomyt** [FunkinCrew/Funkin#3236]
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Google Chrome

### Version

0.5

### Context (Provide images, videos, etc.)

i have video proof but i cant show it because the file type isnt supported

### Steps to reproduce (or crash logs, errors, etc.)

click tab in the freeplay menu and instantly switch to pico

**Comment by moxie-coder** [comment]
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3165

**Comment by GoombarioFan** [comment]
Actually, this issue seems to be a duplicate of #3201.
#3165 describes the game's current inability to save Pico being unlocked, which is a separate issue.

**Comment by moxie-coder** [comment]
> Actually, this issue seems to be a duplicate of #3201. #3165 describes the game's current inability to save Pico being unlocked, which is a separate issue.

oops

**Comment by EliteMasterEric** [comment]
Duplicate
