### ISSUE TITLE
Bug Report: going to the title screen locks pico

### ISSUE THREAD

**Issue by ninjarecroomyt** [FunkinCrew/Funkin#3237]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Google Chrome

### Version

0.5

### Context (Provide images, videos, etc.)

when u go to the title screen pico gets locked again you can still play as him you just have to watch the unlock cutscene again

### Steps to reproduce (or crash logs, errors, etc.)

unlock pico go to title screen than go back to freeplay menu and u should see thats hes locked again and u have to watch the cutscene again

**Comment by AbnormalPoof** [comment]
Duplicate of #3165

**Comment by EliteMasterEric** [comment]
Confirmed duplicate of #3165
