### ISSUE TITLE
Bug Report: linux build on itch.io is still 0.4.0

### ISSUE THREAD

**Issue by circuitsystem** [FunkinCrew/Funkin#3238]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Linux

### If you are playing on a browser, which one are you using?

None

### Version

0.4.0

### Context (Provide images, videos, etc.)

linux build on itch.io is the only one still at 0.4.0

**Comment by mll-enh** [comment]
this isn't a bug
linux is hell to compile and devs don't update it often

**Comment by JackXson-Real** [comment]
Switch to Windows, easy fix

**Comment by SIG7Pro** [comment]
> this isn't a bug linux is hell to compile and devs don't update it often

Honestly I feel like Linux based systems are some of the easiest to compile to for games. However, if there was system specific code that would cause errors on Linux, I suppose that makes sense.



> Switch to Windows, easy fix

That doesn't fix the issue.

**Comment by circuitsystem** [comment]
> Switch to Windows, easy fix

if you were having trouble with security on windows, it would be a horrible bullshit thing for me to say "switch to linux". you're not solving the issue, go away

**Comment by circuitsystem** [comment]
> > this isn't a bug linux is hell to compile and devs don't update it often
> 
> Honestly I feel like Linux based systems are some of the easiest to compile to for games. However, if there was system specific code that would cause errors on Linux, I suppose that makes sense.
> 
> > Switch to Windows, easy fix
> 
> That doesn't fix the issue.

its been a few days, crossing my fingers and hoping they didnt forget about us linux users but i cant even get any devs to acknowledge my question

**Comment by NotHyper-474** [comment]
> its been a few days, crossing my fingers and hoping they didnt forget about us linux users but i cant even get any devs to acknowledge my question


Closest thing I found is [this](https://x.com/ninja_muffin99/status/1833168684606521652?t=Th6HDGvzZxK1_AAkdV7DEA&s=19)

**Comment by NotHyper-474** [comment]
This has been resolved as of 0.5.1
