### ISSUE TITLE
Bug Report: Erect + Pico remixes refuse to run on HTML5 instances outside of Itch + NG.

### ISSUE THREAD

**Issue by mll-enh** [FunkinCrew/Funkin#3240]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Web)

### If you are playing on a browser, which one are you using?

Google Chrome

### Version

0.5.0

### Context (Provide images, videos, etc.)

I know someone uploaded this as an issue before but there wasn't enough context before he closed it so, I'll just drop my two cents. I had pulled assets from the itch.io build to run on my own localhost server, and every time I try to play any Pico or Erect/Nightmare song [other than Senpai], it crashes at 10% playthrough or hang indefinitely. I have troubleshooted by using the Windows and Mac assets, Newgrounds, hell I've tried the Gamaverse reupload [ugh]. Nothing seems to work and I'm not sure if it's a javascript related issue or a haxe stage issue. If anyone has any input, please help me.

### Steps to reproduce (or crash logs, errors, etc.)

test here: https://reading.diesmos.com/0.5.0/ 

also this specific build has pico menu crashing but that's since been resolved internally

note: i would compile via source if it was out

**Comment by Hundrec** [comment]
I tested your link and was able to complete Bopeebo (Pico Mix) and Bopeebo Erect just fine.
Have you changed the content in the link since you posted this issue?

**Comment by mll-enh** [comment]
I have, it was an issue with the audio files. I apologize for not closing this issue.
Thank you much, and have a wonderful night/day.
