### ISSUE TITLE
Bug Report: Modded songs don't load in.

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#3244]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Simple enough. Modded songs just aren;t loading into either freeplay menu for me.

### Steps to reproduce (or crash logs, errors, etc.)

Put a week in the same way it worked in 4.1
The song won't show up in freeplay.

**Comment by AbnormalPoof** [comment]
Not a bug. Breaking changes were made to the modding system. As a result, mods will have to be migrated. (See [Migrating from v0.1.0 to v0.5.0](https://funkincrew.github.io/funkin-modding-docs/09-migration/09-01-0.1.0-to-0.5.0.html#migrating-from-v010-to-v050))

**Comment by Average-FNF-Modder** [comment]
> Not a bug. Breaking changes were made to the modding system. As a result, mods will have to be migrated. (See [Migrating from v0.1.0 to v0.5.0](https://funkincrew.github.io/funkin-modding-docs/09-migration/09-01-0.1.0-to-0.5.0.html#migrating-from-v010-to-v050))

My fault
