### ISSUE TITLE
Bug Report: DadBattle Erect Stage

### ISSUE THREAD

**Issue by Tabiba172** [FunkinCrew/Funkin#3256]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

I noticed that in DadBattle Erect, when the camera zooms back in, you can see that the background below is cropped.
![screenshot-2024-09-14-15-22-04](https://github.com/user-attachments/assets/93f806be-30f6-48a1-abe3-9c4bf40faf03)

**Comment by PipocaAventuras** [comment]
this happens in bopeebo and fresh too
