### ISSUE TITLE
Bug Report: Chart Editor is useless (Cloned, check #3147)

### ISSUE THREAD

**Issue by XenonHedgehog** [FunkinCrew/Funkin#3258]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

![Screenshot 2024-09-14 183705](https://github.com/user-attachments/assets/a70ddff0-6b27-4e20-84ea-fd991bf64962)
i can't drag nor place notes/events and scroll except seeking the bar to skip time

### Steps to reproduce (or crash logs, errors, etc.)

1. find chart editor code
2. re-add note placement and dragging

**Comment by AbnormalPoof** [comment]
duplicate of #3147

**Comment by XenonHedgehog** [comment]
oops
