### ISSUE TITLE
Question: custom_chars folder no longer present in images?

### ISSUE THREAD

**Issue by SilverT4** [FunkinCrew/Funkin#326]
# Please check for duplicates or similar issues before asking your question.

## What is your question?
I noticed the custom_chars folder in assets/images was removed. Is it being removed in favour of the mods folder?
![image](https://user-images.githubusercontent.com/41199354/106663282-7dba4000-6571-11eb-9750-9f19f625678c.png)

**Comment by regulad** [comment]
I think a lot of modding shiz was stripped out, I'm not very sure why, I'd assume it's because he is working on re-implementing polymod.

**Comment by devin503** [comment]
> I think a lot of modding shiz was stripped out, I'm not very sure why, I'd assume it's because he is working on re-implementing polymod.

I'd assume so as well. I usually use the custom_chars folder in clones locally for extra characters, so having it suddenly disappear was kinda unsettling at first.
