### ISSUE TITLE
Bug Report: Song ends at wrong time when you choose diffrent instrumental

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3261]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

if you go for example to Pico erect with Pico mix instrumental, the song ends at the time pico mix instrumental ends, which may cause the song to end before the vocals end

### Steps to reproduce (or crash logs, errors, etc.)

Choose for example Pico Erect with Pico mix instrumental and play it

**Comment by BombasticTom** [comment]
i don't think the erect remixes were supposed to have the ability for pico instrumentals, cuz they use different bpms and are basically completely different songs. the reason it ends is because the game looks for if the instrumental has finished playing, not the vocals

**Comment by SnowyyWHY** [comment]
> i don't think the erect remixes were supposed to have the ability for pico instrumentals, cuz they use different bpms and are basically completely different songs. the reason it ends is because the game looks for if the instrumental has finished playing, not the vocals

Oh yea the bug should be that you can choose pico instrumental on pico erect, but i already saw someone report it so i will close this issue
