### ISSUE TITLE
Enhancement: Background Darnell's redesign of the Week 5

### ISSUE THREAD

**Issue by 256smash** [FunkinCrew/Funkin#3262]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

In the spring was made the last official design of Darnell as an opponent on Weekend 1, then the old design should be redone on Week 5 (Except Erect) to match the new Darnell on Weekend 1. It would be great to improve that! ;)

Old:
![oldDarnell](https://github.com/user-attachments/assets/124aaefa-e6ed-4ab4-9638-11a5aae449c8)

New:
![Darnell_New](https://github.com/user-attachments/assets/cc6255dc-f316-418d-b581-891945312255)

**Comment by JackXson-Real** [comment]
That would be a nice improvement especially since his sprite in the Week 5 erect BG is more up to date.
