### ISSUE TITLE
Bug Report: Start of song looped indefinitely (due to a low visual & input offset)

### ISSUE THREAD

**Issue by MothyMoss** [FunkinCrew/Funkin#3265]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

If you have a low visual / input offset the start of the song is looped. Video uploaded on YouTube as the file is too big. 

[Watch here: https://www.youtube.com/watch?v=tJZQslmKqT8](https://www.youtube.com/watch?v=tJZQslmKqT8)

Time stamps are included in the video

### Steps to reproduce (or crash logs, errors, etc.)

Put a low offset (I'm guessing -100 and below, just to be sure try -125 and below, and try putting the same for visual and input)
Start a song

(I don't know how to put crash logs / errors)

**Comment by NotHyper-474** [comment]
Seems to be already reported in #3264

**Comment by MothyMoss** [comment]
> Seems to have already been reported in #3264

Sorry, but it didn't have much explanation, so I still made mine. Have anyone tried replicating this bug though?

**Comment by NotHyper-474** [comment]
> > Seems to have already been reported in #3264
> 
> Sorry, but it didn't have much explanation, so I still made mine. Has anyone tried replicating this bug though?

I see. I did and managed to.

**Comment by MothyMoss** [comment]
> > > Seems to have already been reported in #3264
> > 
> > 
> > Sorry, but it didn't have much explanation, so I still made mine. Has anyone tried replicating this bug though?
> 
> I see. I did and could replicate it successfully.

Hip hip hooray... 🎉🎉

**Comment by Hundrec** [comment]
This should be fixed as of 0.5.2!
https://github.com/FunkinCrew/Funkin/issues/3264#issuecomment-2418519618

**Comment by MothyMoss** [comment]
woohoo :D
