### ISSUE TITLE
Enhancement: Make the reset key restart the song and not just kill you

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3268]
### Issue Checklist

- [X] I have properly named the enhancement
- [ ] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

Make the reset key [R] restart the song and not kill the player, would be cool

**Comment by NotHyper-474** [comment]
Already requested before in https://github.com/FunkinCrew/Funkin/issues/2442 but got rejected.

**Comment by EliteMasterEric** [comment]
Duplicate of #2442
