### ISSUE TITLE
Bug Report: Pico Mix instrumental can be selected for Pico Erect

### ISSUE THREAD

**Issue by ActualMandM** [FunkinCrew/Funkin#3269]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

![2024-09-14_10-45-40_Funkin](https://github.com/user-attachments/assets/dd718b69-9101-45f0-8408-afa58dcc9771)

https://github.com/user-attachments/assets/6548bb5e-cb84-4b4f-94bd-0deda8794ffd

### Steps to reproduce (or crash logs, errors, etc.)

1. Go to Freeplay
2. Hover over Pico
3. Change to Erect or Nightmare difficulty
4. Select the song, the instrumental type selection will appear

**Comment by EliteMasterEric** [comment]
Replicated and resolved internally.

**Comment by IdealistCat** [comment]
that sounds so weird lol
