### ISSUE TITLE
Crash Report: Using "Pico (Pico Mix)" 's instrumental crashes the game.

### ISSUE THREAD

**Issue by MlopsFunny** [FunkinCrew/Funkin#3278]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Google Chrome

### Version

0.5.0

### Context (Provide screenshots or videos of the crash happening)

Should you try using the Pico Mix instrumental on BF's "Pico", the game throws an error.
(Btw, in case of curiosity, I was running the game using the ungrounded.net mirror, to obtain fullscreen visuals.)

### Steps to reproduce

1. Play "Pico" as BoyFriend, but select the Pico instrumental for it.
2. The game crashes, due to instrumentals not being found.

### Crash logs (can be found in the logs folder where Funkin.exe is)

![image](https://github.com/user-attachments/assets/58ca7260-cdcd-4d71-8a11-0a557554ef0b)
![image](https://github.com/user-attachments/assets/293bd58c-4366-4bd5-af62-010c73ec4df5)
![image](https://github.com/user-attachments/assets/758841c2-4324-4a03-a1e0-fd3d9e4a7999)

**Comment by Hundrec** [comment]
This issue was reported in https://github.com/FunkinCrew/Funkin/issues/3251.
Also, I think this is resolved in 0.5.1!
