### ISSUE TITLE
Bug Report: Wonky Freeplay Scrolling

### ISSUE THREAD

**Issue by MlopsFunny** [FunkinCrew/Funkin#3279]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Google Chrome

### Version

0.5.0

### Context (Provide images, videos, etc.)

I found this whilst checking the Pico (Pico Mix) bug, where if you select a song using its pico inst but havent "unlocked" pico yet (Ive already finished all his songs!), the menu scrolls a bit TOO much down. it also has some goofy physics effects depending on how you mess with it lol

### Steps to reproduce (or crash logs, errors, etc.)

1. Select a song while Freeplay BF is in the "UNLOCK!" animation
2. Select the Pico instrumental for the song
3. Either exit out or win the song
4. Scroll down on the menu, it should go a bit *too* much down, in my case.

**Comment by Hundrec** [comment]
I think this is the same issue as https://github.com/FunkinCrew/Funkin/issues/3239
If Boyfriend's new character animation is present on the Freeplay menu, earning a new rank on a song will completely break the capsule.

Please close this one as a duplicate!
