### ISSUE TITLE
Bug Report: if you spam spacebar (or any key) to skip through the dialogue fast in week 6 the game will crash 

### ISSUE THREAD

**Issue by CorruptedOcto** [FunkinCrew/Funkin#328]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [x] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [ ] macOS

**Comment by regulad** [comment]
I was not able to reproduce. However, as specified in #320, hitting the reset key does cause the game to crash.

**Comment by CorruptedOcto** [comment]
https://user-images.githubusercontent.com/77571344/106695659-0accbb80-65a9-11eb-85bd-f6751c8ade60.mp4

here is a video of it

**Comment by CorruptedOcto** [comment]
doesnt seem to have the bug on the downloaded version

**Comment by Maks7594** [comment]
> I was not able to reproduce. However, as specified in #320, hitting the reset key does cause the game to crash.

That's the DIE kill. You die.

**Comment by Maks7594** [comment]
>  2021-02-02.22-47-28_Trim.mp4 
> here is a video of it

B

**Comment by diecasti** [comment]
here ill leave you a console crash from the itch.io
![image](https://user-images.githubusercontent.com/62880649/106791948-e0850780-6655-11eb-9a04-1db693599e33.png)
