### ISSUE TITLE
Bug Report: Playing as Pico in freeplay shows Boyfriend's scores instead

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/Funkin#3287]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Pico's freeplay does not show Pico scores and instead shows scores for the default variation.
![image](https://github.com/user-attachments/assets/b4642db5-b323-4b83-9cf2-61ad95488c69)
It should not be possible to have a score like this with this rank.

### Steps to reproduce (or crash logs, errors, etc.)

Get a score on a song as boyfriend. Play as pico and get a different score on that song. The menu will show boyfriend's score instead.

**Comment by NotHyper-474** [comment]
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3145

**Comment by biomseed** [comment]
Resolved
