### ISSUE TITLE
Bug Report: Pico is unlocked on game start rather than when Weekend 1 is beaten.

### ISSUE THREAD

**Issue by EliteMasterEric** [FunkinCrew/Funkin#3294]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Expected behavior: Players should have to beat Weekend 1 in order to unlock Pico.
Actual behavior: Pico is available immediately when starting the game even with no levels completed.

**Comment by 7oltan** [comment]
this was already reported eric you HAVENT done the issue checklist correctly >:(

**Comment by 7oltan** [comment]
https://github.com/FunkinCrew/Funkin/issues/3165

**Comment by AbnormalPoof** [comment]
They are different issues. This issue describes how Pico is unlocked immediately instead of having to go through WeekEnd 1 (which is the intended way to unlock him). #3165 describes how Pico doesn't STAY unlocked after a reset.

**Comment by 7oltan** [comment]
> They are different issues. This issue describes how Pico is unlocked immediately instead of having to go through WeekEnd 1 (which is the intended way to unlock him). #3165 describes how Pico doesn't STAY unlocked after a reset.

oh- then shit he is doing it right lol
