### ISSUE TITLE
Bug Report: The music keeps looping after i finish it

### ISSUE THREAD

**Issue by meianove99** [FunkinCrew/Funkin#3295]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Opera

### Version

0.5.0

### Context (Provide images, videos, etc.)

When i finished Dadbattle (pico ver.) the music kept looping without the notes and the level wouldn't end and proceed to the results screen

**Comment by AbnormalPoof** [comment]
duplicate of #3142

**Comment by EliteMasterEric** [comment]
Duplicate
