### ISSUE TITLE
Enhancement: ER*CT mode for Story Mode, Locked Weeks and new Cutscenes

### ISSUE THREAD

**Issue by LokiTheDevCat** [FunkinCrew/Funkin#3306]
### Issue Checklist

- [X] I have properly named the enhancement
- [ ] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

It would be cool if the creators add ER*CT mode for the Story Mode cuz it would be harder than before, and the weeks would be Locked for example "Complete Week 1 to Unlock Week 2" and continues, they should add new cutscenes for Week 1, 2, 3, 4, these weeks doesn't have any cutscenes and it would be nice if they add

**Comment by ChillyBeanBAM** [comment]
ERECT mode _was_ planned to be in Story Mode, but it was [scrapped](https://github.com/FunkinCrew/Funkin/issues/2826#issuecomment-2171911263).

**Comment by AbnormalPoof** [comment]
[Cutscenes for previous weeks will be a full game thing.](https://www.youtube.com/watch?v=sS0s5n4z4p0)
