### ISSUE TITLE
Bug Report: Game Freezes when you die on cutscene (Week 6)

### ISSUE THREAD

**Issue by AnotherSeawhite** [FunkinCrew/Funkin#331]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ X ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ X ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ X ] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.

v0.2.7 (Latest)

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

I pressed R key (Instant game over) (and F9 icon change) on cutscene and the game freezes.

## Please describe your issue. Provide extensive detail and images if possible.

uh. the game freezes.

https://user-images.githubusercontent.com/52661206/106685997-eacee380-660c-11eb-9ee4-ace4c24503dc.mp4

**Comment by ActualMandM** [comment]
Duplicate of #313
