### ISSUE TITLE
Bug Report: The Fresh Erect vocals are messy and keep playing on freeplay menu

### ISSUE THREAD

**Issue by meianove99** [FunkinCrew/Funkin#3311]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Opera

### Version

0.5.0

### Context (Provide images, videos, etc.)

i recorded a video of the bug https://drive.google.com/file/d/1AREFhP57JkR1mSE7JB7vxg6DfiejRrKu/view?usp=sharing (github keep bitching about the video size so heres the google drive link)

### Steps to reproduce (or crash logs, errors, etc.)

enter on fresh erect, when the music starts, just pause the game

**Comment by Hundrec** [comment]
Are you able to reliably reproduce this? Is the bug accompanied by a freeze or stutter?

**Comment by meianove99** [comment]
i tried to reproduce it again and it didn't work, looks like the bug got fixed
