### ISSUE TITLE
Enhancement: Ability to update scores to Newgrounds/Custom database from application distributions + other things

### ISSUE THREAD

**Issue by devmckenzie** [FunkinCrew/Funkin#332]
## Score Database Integration
- It would be neat to see a feature to log into Newgrounds through the executable via SSO or something. I don't know how the servers are run or how they could be linked up, but something to think about down the road.
### 
## Config Menu
- This also may have been mentioned before, but reconfigurable controls! I don't have any issue with it as-is but it would definitely be an accessibility/QOL improvement for some. (see Enhancement request #304 -- I think that's what this person is trying to convey). A general settings menu with graphics options and such have been discussed in other opened cases.
###

**Comment by Templarfreak** [comment]
This may give players another avenue to cheat. I think currently cheating is still happening anyway, but this would definitely just give another way to cheat. Since the game is open source, players could modify the code of their game and then log into Newgrounds through their compiled local copy, and through that they could have changed the game in any way they see fit. They could just not distribute the source code with Newgrounds login and instead have their official version that you can download off of Itch.io be able to log in, but that kinda partly defeats the purpose of this game being open source in my opinion.

Also, just a note, I'm not totally sure about the etiquette of this repo in particular, but usually it's bad etiquette to request and/or report more than one thing in the same issue. It makes things harder to manage and keep track of. Just keep that in mind for the future. :D

**Comment by regulad** [comment]
This seems like a pretty tall order, you can always make a pull request yourself if it won't break anything else.

> Also, just a note, I'm not totally sure about the etiquette of this repo in particular, but usually it's bad etiquette to request and/or report more than one thing in the same issue. It makes things harder to manage and keep track of. Just keep that in mind for the future. :D
~~this repo is a nuclear wasteland anyway don't worry about it~~

**Comment by devmckenzie** [comment]
> This seems like a pretty tall order, you can always make a pull request yourself if it won't break anything else.

Good idea! Maybe I'll fool around with some things in my free time. The last thing I want is to put any strain on contributors. I just wanted to share a bit of what I was thinking. It would be neat to see, but putting stuff like this into action is another story. I really appreciate the response. Loving the game regardless of any suggestions mentioned above. General game function/playability is just fine as is.

> I think this poses potential security risks for the Newgrounds copy in general, players Newgrounds accounts, etc, etc. So overall I think it's not a good idea.

Touching on this, I feel that it _is_ a complicated feature to add, and I am by no means qualified to say if this would cause security risks, but online leaderboard implementation is certainly possible in some shape or form. I still think it is a good idea. 
>>
> This may give players another avenue to cheat. I think currently cheating is still happening anyway, but this would definitely just give another way to cheat. Since the game is open source, players could modify the code of their game and then log into Newgrounds through their compiled local copy, and through that they could have changed the game in any way they see fit. They could just not distribute the source code with Newgrounds login and instead have their official version that you can download off of Itch.io be able to log in, but that kinda partly defeats the purpose of this game being open source in my opinion.

Again, just some thoughts. I will say, I agree cheating is an issue if you have access to the source code, but I feel it could worked out if done correctly. Either way, cheating is inevitable in my opinion, but there are ways to handle the validity of scores, submissions, etc. As someone who isn't working on the project, I can only offer my thoughts. I do want to fool around with it and try to get the desktop version working with a database. Would be neat as a little side project!

> Also, just a note, I'm not totally sure about the etiquette of this repo in particular, but usually it's bad etiquette to request and/or report more than one thing in the same issue. It makes things harder to manage and keep track of. Just keep that in mind for the future. :D

Thanks for the heads up haha. I will be sure to consider this in future issue reports.

### Thank you both for discussing with me! I'll go ahead and close this. I hope to see the game grow even more than it already has. It's crazy to see how far it's come already since the Ludum Dare build.
# 
_**Funk on y'all🚀🚀🚀- Mike**_
