### ISSUE TITLE
Enhancement: bro eated Project.xml

### ISSUE THREAD

**Issue by Dxgamer7405** [FunkinCrew/Funkin#3330]
### Issue Checklist

- [ ] I have properly named the enhancement
- [ ] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

bottom text

**Comment by NotHyper-474** [comment]
It has been replaced by [project.hxp](https://github.com/FunkinCrew/Funkin/blob/main/project.hxp)

**Comment by Dxgamer7405** [comment]
ah i didnt know, thanks for telling me
