### ISSUE TITLE
Bug Report: not keeping the correct score!! and for some reason keeps showing i unlocked a new character

### ISSUE THREAD

**Issue by AxoUniverse** [FunkinCrew/Funkin#3344]
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

So basically, it keeps showing that i keep unlocking a new character?? even though its still pico everytime i go to freeplay, i dont know if its just me but it also shows ive beaten some songs but have 0 score???
![screenshot-2024-09-17-04-31-49](https://github.com/user-attachments/assets/26f7b99b-2ac1-4372-81fb-24844b0fd88f)
![screenshot-2024-09-17-04-31-47](https://github.com/user-attachments/assets/0f8dded8-bfec-4359-b0df-2badd0f09f56)
![screenshot-2024-09-17-04-31-44](https://github.com/user-attachments/assets/55a1fd15-51b3-4b05-b8c1-9392575f4a05)
![screenshot-2024-09-17-04-31-42](https://github.com/user-attachments/assets/576b2791-a747-4e6b-9a46-9d3a30ebe333)
![screenshot-2024-09-17-04-31-38](https://github.com/user-attachments/assets/0c5b80ec-a683-4749-9f20-d02b883aee4a)
![screenshot-2024-09-17-04-31-31](https://github.com/user-attachments/assets/5eb32cc1-a770-4e31-b147-bfc072f0ae44)
![screenshot-2024-09-17-04-31-29](https://github.com/user-attachments/assets/06f7717f-8859-49a9-8cea-30abaa05da69)
and the video proof, https://streamable.com/p0ig90

**Comment by AxoUniverse** [comment]
all the screenshots are the songs BEATEN, but with 0 score somehow

**Comment by NotHyper-474** [comment]
* Character Unlock bug has already been reported in https://github.com/FunkinCrew/Funkin/issues/3165
* Scores bug has already been reported in https://github.com/FunkinCrew/Funkin/issues/3145

**Comment by AxoUniverse** [comment]
oh awesome
