### ISSUE TITLE
Bug Report: Chart editor completely broken on 0.4.1

### ISSUE THREAD

**Issue by koueu** [FunkinCrew/Funkin#3349]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

Chart editor cannot place notes or events, theyre may be other issues but i have not checked. songs, charts, difficulties and removing notes is still possible but notes cannot be placed at all. only temp fix i have is to port charts into 0.4+ or make charts in 0.4+ and then add them to the 0.4.1 directory, eg mods folder
![image](https://github.com/user-attachments/assets/a1ff68aa-25b0-42c1-9609-22157f759132)

**Comment by koueu** [comment]
I am wrong, you cant access the menus either once in here, the only way to exit is either through closing the game or pressing f4 (that i know of)

**Comment by koueu** [comment]
> I am wrong, you cant access the menus either once in here, the only way to exit is either through closing the game or pressing f4 (that i know of)

It depends. menus worked when i loaded 2hot, additionally you cannot scroll through the chart, only go down by pressing space and playing the song

**Comment by koueu** [comment]
> > I am wrong, you cant access the menus either once in here, the only way to exit is either through closing the game or pressing f4 (that i know of)
> 
> It depends. menus worked when i loaded 2hot, additionally you cannot scroll through the chart, only go down by pressing space and playing the song

you can drag the player icon at the bottom though. 
![image](https://github.com/user-attachments/assets/540cae00-4199-4cb6-8cd9-064501cca93e)

**Comment by koueu** [comment]
also pressing exit crashes ur game

**Comment by NotHyper-474** [comment]
I think you mean 0.5.0 because 0.4.1's charts are working fine (at least for me). If so then this is a duplicate of https://github.com/FunkinCrew/Funkin/issues/3147

**Comment by Kade-github** [comment]
most of these issues are fixed in https://github.com/FunkinCrew/Funkin/pull/3337, only one currently not fixed is the exit problem (crashing)

**Comment by tposejank** [comment]
0.4.1's chart editor is 90% functional. 0.5.0 i've seen does not work at all

**Comment by EliteMasterEric** [comment]
If this report is for Funkin' v0.5.0 (the Playable Pico update), this is a duplicate of #3147 and resolved by #3337 .

If this report is for Funkin' v0.4.1 (the patch to the Pit Stop update), this is a legacy issue which is not permitted on this repository.

**Comment by koueu** [comment]
I got the wrong version. yea its 5.0

**Comment by tposejank** [comment]
Extremely late.
