### ISSUE TITLE
[Enhancement] Expression as values in json files for modding

### ISSUE THREAD

**Issue by MidyGamy** [FunkinCrew/Funkin#3360]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

I suggest being able to use an expression as a value for json files, similar of how molang works in Minecraft Bedrock...

For example, we could have something like this:
`{
   offset:
   [
       "this.flipX ? 100 : 0;",
        10
   ]
}`
Here it alows the json to set a different offset depending on the flipX

This would also allow characters to be in one file for opponent and playable.

You could make also use `this.setSciptValue()` like in HXC to set custom values

**Comment by EliteMasterEric** [comment]
The JSON parsing for Minecraft Bedrock is very complicated and hard to maintain, and the relevant behavior can easily be replicated via creating a scripted class for the relevant object.

If the only thing you would need this for is `flipX`, I'd rather just resolve that (see #3335 )
