### ISSUE TITLE
Bug Report: Visual bug of boyfriend persisting while hovering over a different character in character select (Plus a weird thing where boyfriend does the entry animation during the character select cutscene twice)

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#3365]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Web)

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

If you go into character select, you'll notice that boyfriend actually does his intro animation twice, once at the start and again after a second or so. This is already a visual bug, but if you change characters before this second intro, your cursor will switch slots but it will stay on boyfriend visually, and another copy of his sprite will get layered behind him for some reason. Here's a video:

https://github.com/user-attachments/assets/f0fddf59-fdc4-4e5d-8ba4-5795279fcd90

It fixes itself as soon as you scroll again after waiting a sec, presumably waiting however long it would've been till that 2nd intro animation from bf. Small bug for sure.

### Steps to reproduce (or crash logs, errors, etc.)

1. Enter character select
2. Before bf's intro anim loops, swap characters
3. If you swapped to an unlocked one, bf will get a copy of himself under him and visually replace that character, otherwise, this will happen for one anim cycle and then it will switch to the unknown character animation on it's own

**Comment by GoombarioFan** [comment]
Seems to be another duplicate of #3201, but the video is a welcome addition!

**Comment by Hundrec** [comment]
This is fixed in 0.5.2
Please close this issue.

**Comment by Average-FNF-Modder** [comment]
> This is fixed in 0.5.2 Please close this issue.

Oh yeah mb.
