### ISSUE TITLE
Enhancement: Lyrics on the 3 songs pico vs pico

### ISSUE THREAD

**Issue by LokiTheDevCat** [FunkinCrew/Funkin#3366]
### Issue Checklist

- [X] I have properly named the enhancement
- [ ] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

Well, In Pico vs Pico first song, playable pico has lyrics but in other 2 pico vs pico songs doesn't have, it should be in the game to match the first song that has lyrics

**Comment by EliteMasterEric** [comment]
No idea what you're talking about.

**Comment by LokiTheDevCat** [comment]
> No idea what you're talking about.

It was lines in the Pico vs Pico songs
