### ISSUE TITLE
Compiling help: Type not found : flxanimate.effects.FlxTint

### ISSUE THREAD

**Issue by xenkap** [FunkinCrew/Funkin#3370]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Attempting to compile in my case throws an error about a missing Type in the Lock.hx class.
It refers to FlxTint in an effects folder in flxanimate, but I checked and it's not there, nor is it in the GitHub releases that I check in.
Am I missing something, or...?

![image](https://github.com/user-attachments/assets/f422e675-dcfd-480a-8700-0fa21e87ee16)

**Comment by NotHyper-474** [comment]
Try reinstalling flxanimate via `hmm reinstall -f flxanimate`

**Comment by xenkap** [comment]
> Try reinstalling flxanimate via `hmm reinstall -f flxanimate`
I thought I did this already... odd. Thanks!

Now I'm back to an error I last had about ERROR (unknown position) Type not found : T
Which I'm aware already has issue reports on, but none of the suggestions helped...? The suggestions actually led me back to this error.
I'll probably look further into it on my own, but advice would be appreciated!

**Comment by NotHyper-474** [comment]
Since you said you've already seen the issues does that mean reinstalling Flixel didn't fix it?

**Comment by xenkap** [comment]
> Since you said you've already seen the issues does that mean reinstalling Flixel didn't fix it?

It didn't, no. I still have no idea what's causing it-- even reinstalled Haxe...

**Comment by NotHyper-474** [comment]
> > Since you said you've already seen the issues does that mean reinstalling Flixel didn't fix it?
> 
> It didn't, no. I still have no idea what's causing it-- even reinstalled Haxe...

Did you also try reinstalling all haxelibs? (Through either `hmm clean` + `hmm install` or `hmm reinstall -f`)

**Comment by xenkap** [comment]
> > > Since you said you've already seen the issues does that mean reinstalling Flixel didn't fix it?
> > 
> > 
> > It didn't, no. I still have no idea what's causing it-- even reinstalled Haxe...
> 
> Did you also try reinstalling all haxelibs? (Through either `hmm clean` + `hmm install` or `hmm reinstall -f`)

Already have. Although the issue seems to have fixed itself today...?
...while presenting me with more different issues, however...
![image](https://github.com/user-attachments/assets/adba1974-7b24-41cd-a5aa-dcd78547b9c4)

**Comment by xenkap** [comment]
Commenting out all related lines (and replacing animDropDownMenu with offsetAnimationDropdown) seems to result in a successful compile...! No clue what's going on here.

**Comment by NotHyper-474** [comment]
If you're on develop branch I've seen a guy having issues with compiling in it, maybe it's that?
