### ISSUE TITLE
Enhancement: Add "getInstance" and "setInstance" fields to scripted classes

### ISSUE THREAD

**Issue by Ralsin** [FunkinCrew/Funkin#3377]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

Add `getInstance("moduleName")` and `setInstance("moduleName", obj)` to scripted classes (`ScriptedModule`, `ScriptedFlxState`, etc) so its easier to send info around between modules.

I'm rewriting one of my mods that has lotta stuff going on so I want to split it into separate modules for easier code management. I want to get and change properties from within another module that doesn't have direct access to the instance, but looks like there's no way to do that yet.

**Comment by lemz1** [comment]
can't you just use `ModuleHandler.getModule('moduleName')`?

**Comment by Ralsin** [comment]
oh i didnt know that, getInstance seemed like a more intuitive thing while module handler had like internal stuff but alright
thanks

**Comment by Ralsin** [comment]
though its a module class, not the clear instance itself so ill have to still copypaste some code to add an instance field and do `getModule('module').scriptGet('instance')` everytime instead of `getInstance('module')`

**Comment by AbnormalPoof** [comment]
You can just have a helper function to do what you want for you:
```haxe
function getInstance(variable:String):Dynamic {
   return ModuleHandler.getModule(MODULE_ID).scriptGet(variable);
}

function setInstance(obj:Dynamic, variable:String):Dynamic {
   return ModuleHandler.getModule(MODULE_ID).scriptSet(obj, variable);
}
```
