### ISSUE TITLE
Enhancement: pico pissed sprites not being in picos FLA

### ISSUE THREAD

**Issue by CasualMythoids** [FunkinCrew/Funkin#3378]
### Issue Checklist

- [x] I have properly named the enhancement
- [x] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

I've been questioning when this was going to be added in the Pico_FNF_assetss.fla and it NEVER has so I'm hoping Eric could see this and finally add this missing sprite to his FLA

![GXyhvJHXMAAA_sV](https://github.com/user-attachments/assets/3993cd8c-68c8-428f-a9c0-7f735ae8edc9)

**Comment by JVNpixels** [comment]
eric usually isnt the one who takes care of the .fla stuff, that is phantom arcades job, but eric could contact phantom arcade and get stuff resovled.

**Comment by ExcodeFNF** [comment]
> eric usually isnt the one who takes care of the .fla stuff, that is phantom arcades job, but eric could contact phantom arcade and get stuff resovled.

solved*

**Comment by EliteMasterEric** [comment]
Resolved, check the art repo
