### ISSUE TITLE
Setting Visual Offsets to causes the song to repeatedly skip ("Swing Mode")

### ISSUE THREAD

**Issue by gordonite** [FunkinCrew/Funkin#3380]
### Issue Checklist

- [ ] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

While playing the v0.5.0, it appears as if the songs are sped up in both pico and bf mode. the notes are also very broken, and it gets annoying to complete a song. it happens in all of the songs, based on my testing. doesnt matter if its either story mode or freeplay

### Steps to reproduce (or crash logs, errors, etc.)

1. Open Game
2. Pick a song from either freeplay or story mode.
3. bug happens when the song loads.

https://github.com/user-attachments/assets/a15ec601-99a5-4b8a-a958-9a1b588114b8

**Comment by gordonite** [comment]
Other versions I have on my PC, like v0.4.0, work perfectly fine and lack this bug btw.

**Comment by MrMooey** [comment]
Sounds like a swing rhythm remix of 2hot

**Comment by ChillyBeanBAM** [comment]
This is probably due to lag spikes, but yeah, I had this problem too.

**Comment by gordonite** [comment]
> This is probably due to lag spikes, but yeah, I have this problem too.

Do you think it could be happening because of old hardware? My pc is old, but I'm curious as it doesn't seem like people that record on Youtube have the issue.

Makes sense either way, game does lag.

**Comment by ChillyBeanBAM** [comment]
> > This is probably due to lag spikes, but yeah, I have this problem too.
> 
> Do you think it could be happening because of old hardware? My pc is old, but I'm curious as it doesn't seem like people that record on Youtube have the issue.
> 
> Makes sense either way, game does lag.

I dunno, but it is possible. Then again, I don't have this problem in previous versions, so...

**Comment by gordonite** [comment]
> > > This is probably due to lag spikes, but yeah, I have this problem too.
> > 
> > 
> > Do you think it could be happening because of old hardware? My pc is old, but I'm curious as it doesn't seem like people that record on Youtube have the issue.
> > Makes sense either way, game does lag.
> 
> I dunno, but it is possible. Then again, I don't have this problem in previous versions, so...

i got a frametime thingy to work
![image](https://github.com/user-attachments/assets/fee6b730-8775-4fea-838e-cdb82d431f19)

it doesn't look like it could be a lag issue, but there does seem to be some micro-stutters when I'm playing.

**Comment by MrMooey** [comment]
> > > > This is probably due to lag spikes, but yeah, I have this problem too.
> > > 
> > > 
> > > Do you think it could be happening because of old hardware? My pc is old, but I'm curious as it doesn't seem like people that record on Youtube have the issue.
> > > Makes sense either way, game does lag.
> > 
> > 
> > I dunno, but it is possible. Then again, I don't have this problem in previous versions, so...
> 
> i got a frametime thingy to work ![image](https://private-user-images.githubusercontent.com/79427718/368816058-fee6b730-8775-4fea-838e-cdb82d431f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTM5MDQsIm5iZiI6MTcyNjcxMzYwNCwicGF0aCI6Ii83OTQyNzcxOC8zNjg4MTYwNTgtZmVlNmI3MzAtODc3NS00ZmVhLTgzOGUtY2RiODJkNDMxZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAyNDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTA5ODE4Y2ZkNmIwYjg0Y2Q3MmVmYzY4ZGRiMmM0MTAyYTNjMzYwMGQ1MTUyZWIyYmM1N2M1M2FkYzNmOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.he77kS7V6ZJzuJAlx41PCyZH_lCgTxovvoxgXapasBo)
> 
> it doesn't look like it could be a lag issue, but there does seem to be some micro-stutters when I'm playing.

Could you try getting this graph for the previous (working) version too? To see if it's any different than this

**Comment by Hundrec** [comment]
> Sounds like a swing rhythm remix of 2hot which is funny

A really good one at that!
Makes me want an actual implementation of "swing mode"

**Comment by MrMooey** [comment]
> > Sounds like a swing rhythm remix of 2hot which is funny
> 
> A really good one at that!
> Makes me want an actual implementation of "swing mode"

Yeah if it was still playable this would be a really fun feature, maybe could be added as a fun modifier

**Comment by Blue2359** [comment]
This actually happens because of the offset settings, this has no correlation to your performance/lag spikes!

**Comment by gordonite** [comment]
> This actually happens because of the offset settings, this has no correlation to your performance/lag spikes!
> 
> _(Visual Offset set to 150, for instance causes this, AND a visual offset of -150 completely causes the song to keep looping the first few milliseconds, lol!)_
> 
> This only applies to Visual Offsets, not Input Offsets.
> 
> Edit: Someone on Twitter has also encountered this issue: https://twitter.com/D1ngo3K/status/1836873973935624479

I know I might sound dumb, but how could I fix this?

**Comment by Blue2359** [comment]
> > This actually happens because of the offset settings, this has no correlation to your performance/lag spikes!
> 
> > 
> 
> > _(Visual Offset set to 150, for instance causes this, AND a visual offset of -150 completely causes the song to keep looping the first few milliseconds, lol!)_
> 
> > 
> 
> > This only applies to Visual Offsets, not Input Offsets.
> 
> > 
> 
> > Edit: Someone on Twitter has also encountered this issue: https://twitter.com/D1ngo3K/status/1836873973935624479
> 
> 
> 
> I know I might sound dumb, but how could I fix this? 

By setting your Visual Offsets to 0.

**Comment by gordonite** [comment]
> > > This actually happens because of the offset settings, this has no correlation to your performance/lag spikes!
> > 
> > 
> > > 
> > 
> > 
> > > _(Visual Offset set to 150, for instance causes this, AND a visual offset of -150 completely causes the song to keep looping the first few milliseconds, lol!)_
> > 
> > 
> > > 
> > 
> > 
> > > This only applies to Visual Offsets, not Input Offsets.
> > 
> > 
> > > 
> > 
> > 
> > > Edit: Someone on Twitter has also encountered this issue: https://twitter.com/D1ngo3K/status/1836873973935624479
> > 
> > 
> > I know I might sound dumb, but how could I fix this?
> 
> By setting your Visual Offsets to 0.

Thanks. All fixed now, Sorry for any troubles caused or time taken up over a small issue.

**Comment by AbnormalPoof** [comment]
Oh... that explains a lot.
![Screenshot 2024-09-21 at 5 18 50 PM](https://github.com/user-attachments/assets/7871a91f-1679-413f-b7e3-69264b0f2b34)

**Comment by EliteMasterEric** [comment]
Fixed internally

**Comment by NotHyper-474** [comment]
While the visual offset doesn't seem to cause this anymore, setting both visual+input offsets to negative values still messes with the resync.
##### (Bot Play because it's almost impossible to not die with this)

https://github.com/user-attachments/assets/f55c3edb-ab3b-4287-852b-b66128396fa3

**Comment by Hundrec** [comment]
This is hilarious

**Comment by NotHyper-474** [comment]
Oh my god it's even worse if you set only input offsets

https://github.com/user-attachments/assets/79468dd8-5e68-44ea-9555-333de758c4f4

**Comment by Average-FNF-Modder** [comment]
I real hope they make this a feature man, swing mode is so cool.

**Comment by AbnormalPoof** [comment]
HScript and Polymod:

**Comment by Hundrec** [comment]
> I real hope they make this a feature man, swing mode is so cool.

Context for readers: This feature was rejected in this issue: https://github.com/FunkinCrew/Funkin/issues/3403

**Comment by AbnormalPoof** [comment]
Fixed in v0.5.2.
