### ISSUE TITLE
Bug Report: Boyfriend freeze frame spawns behind pico in Character select screen.

### ISSUE THREAD

**Issue by InsanityGrasp** [FunkinCrew/Funkin#3381]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

![Screenshot 2024-09-19 094502](https://github.com/user-attachments/assets/7732cea2-6ca4-489e-9db4-c6f64ac5351f)

### Steps to reproduce (or crash logs, errors, etc.)

Enter character select screen
Rapidly switch between boyfriend and lock icon during unlock animation
duplicate boyfriend freeze frame will spawn behind pico.

**Comment by MrMooey** [comment]
This bug seems related to bugs #3220 and #3201, but I haven't actually seen boyfriend and pico appear at the same time since from what I know only gf and nene are hardcoded to be visibile.

**Comment by Hundrec** [comment]
This should be fixed in 0.5.2
Does this still happen for anyone?
If not, please close this issue.
