### ISSUE TITLE
Bug Report: Week 7 Pico Stress not animating with music (Present in all platforms)

### ISSUE THREAD

**Issue by Sh0e-Man** [FunkinCrew/Funkin#3382]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

This is an Issue that I have observed in all platforms of the game, but in wee 7 on the song stress when Pico is supposed to be killing all of the tank men in sync with the song he is instead just standing their idle spinning his gun.

**Comment by Hundrec** [comment]
Also reported in https://github.com/FunkinCrew/Funkin/issues/3155
