### ISSUE TITLE
Bug Report: Pico only burps once at the end of South (Pico Mix)

### ISSUE THREAD

**Issue by Hundrec** [FunkinCrew/Funkin#3385]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

I found it odd that Pico plays the burping animation once at the end of South, but not the second time.

As it turns out, burpShit plays
![image](https://github.com/user-attachments/assets/0f681d74-f2fd-4976-8e2f-8b360daa6fe6)

...but burpSmile doesn't play right afterwards
![image](https://github.com/user-attachments/assets/2212b02d-fa77-46d4-bb8b-3e8dcdf5ebb6)

However, burpSmile plays just fine at the beginning of Guns
![image](https://github.com/user-attachments/assets/249fe8a4-e0ab-43e2-b84e-133b3c04f594)

Here's a video of the animations:
https://github.com/user-attachments/assets/77203677-1025-482e-9121-45b01fb3278d

### Steps to reproduce (or crash logs, errors, etc.)

Play South (Pico Mix)

**Comment by Kami-prog** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by lemz1** [comment]
Is that a virus again?
This is like the second time in this repo

**Comment by Hundrec** [comment]
Uh huh, reporting right now

**Comment by Hundrec** [comment]
Scammers be like:
> Install this virus to make Pico burp twice

**Comment by IdealistCat** [comment]
I think this issue is just a cause of the animation not existing for the character

**Comment by Hundrec** [comment]
> I think this issue is just a cause of the animation not existing for the character of pico-dark

I investigated pico-dark.json, pico_dark.png, and pico_dark.xml and found the animation in all of them. Something's just not working somewhere along the way!

**Comment by IdealistCat** [comment]
wrong anim name

**Comment by IdealistCat** [comment]
??

**Comment by OrbyyOrbinaut** [comment]
Running into this same issue but with a mod I'm working on rn, my guess is maybe its an issue with forcing the animation perhaps?

**Comment by OrbyyOrbinaut** [comment]
It seems like the issue has to do when you force an animation to play when a forced one is already playing (for the event at least, not sure if this is an issue otherwise)

**Comment by Hundrec** [comment]
You're right! I disabled forcing for the burpShit animation and it allowed burpSmile to play. Turns out the burpShit animation just lasts longer than it needs to and overrides following animations for nearly bars.

https://github.com/user-attachments/assets/00bc4698-a747-466b-b085-4b2c03f265a0

**Comment by OrbyyOrbinaut** [comment]
This only half the issue, I think the intended behavior is trying to play two forced animations in a row causes the second forced one to not play for whatever reason. (This didn't happen on 0.4.1 so I assume the current behavior is a bug)

**Comment by Hundrec** [comment]
This has always been the case, refer to #2670

**Comment by OrbyyOrbinaut** [comment]
Oh huh, never knew.

**Comment by IdealistCat** [comment]
that's weird

**Comment by Hundrec** [comment]
Resolved in 0.5.1, perhaps by shortening the length of burpShit

**Comment by IdealistCat** [comment]
probably

**Comment by AbnormalPoof** [comment]
I feel like to solve another issue like this in the future, would it be more feasible if the “Force” toggle also cancels any forced animations? I’m not really sure.

**Comment by Hundrec** [comment]
> I feel like to solve another issue like this in the future, would it be more feasible if the “Force” toggle also cancels any forced animations? I’m not really sure.

I've thought about how the "Force" feature should really work. 
I think we could benefit from having two separate levels of forcing:
- One that overrides animations like the "Force" we have now
- One that overrides all other animations including the above Forced animations (an "Absolute Force" of sorts)
