### ISSUE TITLE
Enhancement: Release the new .fla of Boyfriend and Pico's freeplay sprites!!!

### ISSUE THREAD

**Issue by PipocaAventuras** [FunkinCrew/Funkin#3391]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

There are new bf sprites in freeplay, but neither this one nor pico are in the flash art folder

**Comment by AbnormalPoof** [comment]
Check funkin.art

**Comment by PipocaAventuras** [comment]
oh
