### ISSUE TITLE
Bug Report: Game audio is still audible even when volume tray is set to 0%

### ISSUE THREAD

**Issue by Blue2359** [FunkinCrew/Funkin#3394]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Okay, I have no clue how I even managed to notice this, *lol*.

I guess there's an issue with how the volume management system works in the game; when your volume slider percentage is at 0% ***(WITHOUT BEING MUTED)***, you can still *slightly* hear the game, this is also the same case across all other builds; **(Web, Desktop... & etc)**.
![image](https://github.com/user-attachments/assets/afe37cc4-a9fd-41b3-816a-e64921e3cbc7)

**Comment by Hundrec** [comment]
Whoa, you're right!

https://github.com/user-attachments/assets/535f4f96-c695-465e-90b2-731cb8115a89

**Comment by Blue2359** [comment]
It's probably this change here that causes the problem.
![image](https://github.com/user-attachments/assets/24befe47-10cf-46e7-9c7a-266570acf543)

**Comment by Keoiki** [comment]
Make the volume scale logarithmically, that'll be good, they thought. Look who can't reach 0 volume without the mute key!
![image](https://github.com/user-attachments/assets/e3defbf3-564f-407c-bf11-40f7cb335c6a)

**Comment by lemz1** [comment]
it has something to do with these functions:

```haxe
    public function linearToLog(x:Float, minValue:Float = 0.001):Float {
        // Ensure x is between 0 and 1
        x = Math.max(0, Math.min(1, x));

        // Convert linear scale to logarithmic
        return Math.exp(Math.log(minValue) * (1 - x));
    }

    public function logToLinear(x:Float, minValue:Float = 0.001):Float {
        // Ensure x is between minValue and 1
        x = Math.max(minValue, Math.min(1, x));

        // Convert logarithmic scale to linear
        return 1 - (Math.log(x) / Math.log(minValue));
    }
```

since you cant take the log of `0` you are required to have some small value above `0`.
so i guess you are just forced into using the mute key.

**Comment by Hundrec** [comment]
I'm no coder, but I'd think to just insert a conditional somewhere in there making sure that a linear volume of 0.0 sets the actual volume to 0%

**Comment by EliteMasterEric** [comment]
Added a fix for this in a branch that's pending merge

**Comment by Blue2359** [comment]
Didn't mean to close this issue, whoops

**Comment by Keoiki** [comment]
Still not fixed in 0.5.1.

**Comment by EliteMasterEric** [comment]
> Still not fixed in 0.5.1.

I'm confused why you say it's not fixed because I literally fixed it.

**Comment by NotHyper-474** [comment]
https://github.com/user-attachments/assets/4ceeb618-4e79-43f9-a84a-6a7d7bd6467b

Can confirm it's still not fixed. Just like before, muting with `0` works, but decreasing to 0 % with `-` does not.

**Comment by Keoiki** [comment]
> > Still not fixed in 0.5.1.
> 
> I'm confused why you say it's not fixed because I literally fixed it.

I'm still able to hear audio at 0% myself, remember this isn't about the Mute key. Probably the easiest way to listen for audio at 0% is in the character select screen.

or just, y'know, set your PC's volume to 100% when the game is at 0% and you'll be able to hear it more clearly.

**Comment by Blue2359** [comment]
This issue is still apparent in v0.5.3 btw

**Comment by ninjamuffin99** [comment]
should have a fix for this internally now!<br>seems like my log/linear math didn't account for taking in a 0 value, so it would always do the math with a value of 0.001 or something (since log() doesn't accept a non-zero input) 

for those curious on the fix, should be in our FunkinCrew/flixel `dev-6.0.0-latest` branch, one of the recent commits as of writing<br>when this issue is marked as closed, it means it should be merged internally 🙂

**Comment by Blue2359** [comment]
yay, volume is finally fixed!
