### ISSUE TITLE
Enhancement: add animation for gf when selecting bf on the char select menu

### ISSUE THREAD

**Issue by TJHOnGithub** [FunkinCrew/Funkin#3395]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

just a little something that slightly bugs me lol, think it'd be nicer looking and more in line with what we currently have with nene having an animation when you select pico

**Comment by Keoiki** [comment]
She already does, but it's so similar to her idle animation I don't blame you for not noticing. (It's a slightly faster and bouncier idle basically)

**Comment by TJHOnGithub** [comment]
ohhhhhhhhhh i thought it was the animation messing up lol

**Comment by amyspark-ng** [comment]
close if fixed please
