### ISSUE TITLE
Bug Report: Guns Pico Speakers Broken Animation

### ISSUE THREAD

**Issue by ShatteredOverlord** [FunkinCrew/Funkin#3401]
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

None

### Version

0.5

### Context (Provide images, videos, etc.)

For some reason pico doesnt shoot his gun at all in the last song of week 7. Instead hes just doing his idle animation.

### Steps to reproduce (or crash logs, errors, etc.)

it always happens

**Comment by Hundrec** [comment]
The Stress Pico Speaker bug was reported here: https://github.com/FunkinCrew/Funkin/issues/3155

**Comment by EliteMasterEric** [comment]
Duplicate
