### ISSUE TITLE
Enhancement: Allow us to change songs to swing tempo

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#3403]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

There's currently a bug going around with visual offset where is you set it to 150 it makes songs play in swing (But crashes when the songs ends and the notes appear buggy). So instead of reporting the bug (I'm sure someone else will), I'm here to report that's it's super fucking cool and whatever it's doing should be cleaned up and turned into a game mechanic in settings or freeplay for fun. /dedadass

Edit: Currently you still have to press notes that are glossed over by the song with the way the game makes it swing, so maybe the swing mode could remove any part of the chart the is glossed over by the audio, basically removing every 3rd step, doing this shorten the chart as well to the new song length so the scroll speed would be preserved and would no longer need to do that skipping thing to keep up. Just having this as a thing the game can do for funsies would be so FNF I think.

**Comment by ChillyBeanBAM** [comment]
This would actually be a funny mechanic.

**Comment by Average-FNF-Modder** [comment]
Is this not gas be real (Ignore video quality)

https://github.com/user-attachments/assets/504ddf13-74ed-4c99-a37f-335124fb3bed

**Comment by Hundrec** [comment]
This suggestion was inspired by the issue reported here: https://github.com/FunkinCrew/Funkin/issues/3380
A swing mode is a must-have after discovering this hilarious bug

**Comment by EliteMasterEric** [comment]
This would be really funny but I don't think we're going to implement anything like this on purpose.
Feel free to make a mod for it though.

**Comment by JordanSantiagoYT** [comment]
you know what that means

TIME FOR ME TO MAKE IT A MO

**Comment by Average-FNF-Modder** [comment]
Please do.

**Comment by AbnormalPoof** [comment]
> Is this not gas be real (Ignore video quality)
> Swing.tempo.Pico.BITCRUSH.mp4

Judging from this, the game appears to "snap" to a note when it gets close enough. I wonder how hard this would be to implement...
