### ISSUE TITLE
Enhancement: Blazin BF mix

### ISSUE THREAD

**Issue by Phantomamn** [FunkinCrew/Funkin#3408]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

Please add Blazin bf mix in the song pack update because it will be awsome to see Boyfriend fighting with Darnell

**Comment by DanTheMan-1234** [comment]
This is not the place for asking for new content. This is for bugfixes and minor features. Besides, Blazin' remixes are already planned.

**Comment by EliteMasterEric** [comment]
Don't ask for new content here.
