### ISSUE TITLE
Enhancement: Make 0.5.0 Release Tag

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#3422]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

Just add a release tag for update 0.5.0 since the latest release tag is 0.4.1

**Comment by EliteMasterEric** [comment]
Done
