### ISSUE TITLE
Enhancement: Scroll Speed Override

### ISSUE THREAD

**Issue by Johnsen290** [FunkinCrew/Funkin#3428]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

There should be an option to override the scroll speed to what you prefer instead of relying on the charts to have the speed you prefer, coming from other rhythm games, certain songs have slower scroll speed than expected even on hard difficulties, only Kade Engine and Holofunk's custom engine are the most prominent engines to have this feature.

**Comment by Hundrec** [comment]
This appears to be the same suggestion as https://github.com/FunkinCrew/Funkin/issues/2943

**Comment by Johnsen290** [comment]
> This appears to be the same suggestion as #2943

ah oops, didn't catch that one, weird, I searched "scroll" first and that did not show up, hm, thanks

**Comment by Hundrec** [comment]
No problem!
