### ISSUE TITLE
Bug Report: Chart Editor does not work

### ISSUE THREAD

**Issue by fianalins** [FunkinCrew/Funkin#3430]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Bars work fine, deleting notes and selecting with the top buttons and Ctrl+A work, and different windows, but nothing else, not even scrolling.

Don't know why this has happened, but it is

https://github.com/user-attachments/assets/0d487000-e08a-4b58-ab14-8c13590eebd4

### Steps to reproduce (or crash logs, errors, etc.)

Open chart editor, from a song or from main menu

**Comment by JackXson-Real** [comment]
This is a duplicate of literally every issue 😭 bro did not check at all

**Comment by NotHyper-474** [comment]
Duplicate of #3147

**Comment by fianalins** [comment]
My fault, GitHub does not show Closed issues by default
