### ISSUE TITLE
Bug Report: In debug menu, the character icons show the full spritesheet because of the new animated icons

### ISSUE THREAD

**Issue by epokgamr** [FunkinCrew/Funkin#3434]
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

![image](https://github.com/user-attachments/assets/916d5b26-7342-4b6a-905e-6d2f64e706f7)
![image](https://github.com/user-attachments/assets/8bc8f14f-3e34-4337-8525-d507e22a2d1c)

**Comment by JVNpixels** [comment]
This issue has been reported already! You can close this now, and it also has a bug-fix here: #3339
