### ISSUE TITLE
Bug Report: Pico doesn't shoot during Stress

### ISSUE THREAD

**Issue by glintfishGH** [FunkinCrew/Funkin#3441]
### Issue Checklist

- [x] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Pico doesn't play any of his "shooting" animations, but the tankmen in the background still die as expected

https://github.com/user-attachments/assets/0d3f4e92-23fd-40d9-bab6-5d3d189009ed

### Steps to reproduce (or crash logs, errors, etc.)

Play Stress.

**Comment by NotHyper-474** [comment]
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3155

**Comment by glintfishGH** [comment]
> Duplicate of #3155

My bad, didn't see it!
