### ISSUE TITLE
Bug Report: onCountdownStep function uses an enum, which HScript classes can't use

### ISSUE THREAD

**Issue by dombomb64** [FunkinCrew/Funkin#3442]
### Issue Checklist

- [X] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

I can't use the `onCountdownStep` function to find out what step of the countdown it is because I can't compare the `step` variable to the enum values. HScript doesn't support enums.

### Steps to reproduce (or crash logs, errors, etc.)

![image](https://github.com/user-attachments/assets/52e6d8b0-a3c7-4953-bada-f95cf6bff1cc)
![image](https://github.com/user-attachments/assets/6f0eec0b-26ae-4201-83c2-9a312234b0d9)

**Comment by Keoiki** [comment]
HScript can use enums defined by the game, however your usage is not correct.
The import is `funkin.play.CountdownStep` and usage is `CountdownStep.VALUE` and not `Countdown.CountdownStep.VALUE`
![image](https://github.com/user-attachments/assets/f9dc3d8e-614c-40b3-a110-2af050659cde)

**Comment by dombomb64** [comment]
Got it, thanks.
