### ISSUE TITLE
Crash Report: Game will crash if you select boyfriend when entering the character unlock screen

### ISSUE THREAD

**Issue by amyspark-ng** [FunkinCrew/Funkin#3455]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Web)

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide screenshots or videos of the crash happening)

In the character select screen, while coming from the new unlocked animation in freeplay, i pressed enter a moment after the lights cutscene ended which caused a crash saying something about pitch not found, this causes the game to freeze tho, not to crash but i'd argue that since the game is unplayable after this happens it's a crash

![image](https://github.com/user-attachments/assets/c356c510-193d-4cd7-83cd-dee5e085b942)

### Steps to reproduce

1. Enter character select screen in the "New character unlock screen" in freeplay
2. Before the cursor moves to the lock the newly unlocked character and is still in boyfriend, press enter
3. Will cause the no pitch found textbox to appear, and after pressing ok it will freeze the game

### Crash logs (can be found in the logs folder where Funkin.exe is)

None

**Comment by AbnormalPoof** [comment]
Duplicate of #3156

**Comment by amyspark-ng** [comment]
aw sorry
