### ISSUE TITLE
Enhancement: add flipX and flipY to stage prop data

### ISSUE THREAD

**Issue by cyn0x8** [FunkinCrew/Funkin#3466]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

self explanatory

![image](https://github.com/user-attachments/assets/a8bc2001-646d-47d7-8a25-8f7fbc82d2d2)

**Comment by AbnormalPoof** [comment]
See #3474

**Comment by AbnormalPoof** [comment]
Added in v0.5.1.
