### ISSUE TITLE
Bug Report: A bot dosen't react to the volume

### ISSUE THREAD

**Issue by Szymonkruk12** [FunkinCrew/Funkin#3468]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

5.0

**Comment by AbnormalPoof** [comment]
Duplicate of #3400

**Comment by NotHyper-474** [comment]
https://github.com/FunkinCrew/Funkin/issues/3400

**Comment by EliteMasterEric** [comment]
Duplicate
