### ISSUE TITLE
Bug Report: Weird song button offsetting after getting a new rank in Freeplay

### ISSUE THREAD

**Issue by AndrewIdot** [FunkinCrew/Funkin#3472]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

After P-Ranking a song in Freeplay, the song's button randomly had its offsets messed up.
![image](https://github.com/user-attachments/assets/1177a4a7-9af1-4e95-97e8-a43c64b8c7af)
![image](https://github.com/user-attachments/assets/e68881c6-fad4-4bd8-a661-f80b4afc5985)
![image](https://github.com/user-attachments/assets/53a2d9a3-dc09-4769-8d4e-6383b949a17d)
I unfortunately didn't think to record this, so the least I have of this bug is these screenshots.

### Steps to reproduce (or crash logs, errors, etc.)

I'm unable to replicate this and completely dumbfounded as to what happened here. 
Maybe it's the shaking effect fucking up? Maybe not entering the character select menu caused it? I dunno, but I think me scrolling away from it as the new rank animation was playing might've been a factor.

**Comment by AndrewIdot** [comment]
Duplicate, I'm an idiot.

**Comment by Hundrec** [comment]
No worries, you can close this issue now!

**Comment by ExcodeFNF** [comment]
you have full permission close this issue, it's been up for 8 hours now.

**Comment by AndrewIdot** [comment]
I thought I closed it but I guess I didnt, oops.
