### ISSUE TITLE
Compilation guide: "Great for fast iteration, but the game-"

### ISSUE THREAD

**Issue by Hundrec** [FunkinCrew/Funkin#3478]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

https://github.com/FunkinCrew/Funkin/blob/main/docs/COMPILING.md

### Context (Provide images, videos, etc.)

The new **Build Flags** section in the compilation guide looks great!
I just noticed that this line about `-DREDIRECT_ASSETS_FOLDER` seems to be unfinished:

![image](https://github.com/user-attachments/assets/1be78004-31c6-46c3-b905-ff07ca189645)

I just gotta know what happens to the game!

**Comment by NotHyper-474** [comment]
But the game

I lost the game

**Comment by NotHyper-474** [comment]
![Screenshot_20241005-080313_Chrome.jpg](https://github.com/user-attachments/assets/3f8f8f69-cd04-4065-bd61-873cdff36817)
