### ISSUE TITLE
Bug Report: Ugh song not having the correct name in Freeplay menu

### ISSUE THREAD

**Issue by Sblorgotech** [FunkinCrew/Funkin#3479]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Ugh is displayed as Ugh erect in the freeplay menu while selecting normal and hard difficulties, but not while selecting the easy difficulty
![image](https://github.com/user-attachments/assets/cc74354c-9498-4a7c-98ec-1b795d6f1db6)

**Comment by Hundrec** [comment]
This has been reported here: https://github.com/FunkinCrew/Funkin/issues/3160

**Comment by Hundrec** [comment]
This bug has been resolved! Please close this issue.
