### ISSUE TITLE
Pico Freeplay menu displays Pico Mix and Weekend 1 songs under separate difficulties

### ISSUE THREAD

**Issue by MrBossGuy36** [FunkinCrew/Funkin#3487]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.1

### Context (Provide images, videos, etc.)

Once youve choosed pico there will only be the weekend 1 songs showing up. The way to fix it is by scrolling to the side when youre on the random button.
![bild_2024-09-30_194127627](https://github.com/user-attachments/assets/e42b7e8f-c1c1-47c6-9c67-8a4740b5b842)

### Steps to reproduce (or crash logs, errors, etc.)

Chosse pico.

**Comment by MrBossGuy36** [comment]
![bild_2024-09-30_194212131](https://github.com/user-attachments/assets/0fb89930-1c65-48e1-877c-eb82cdbacd74)

**Comment by DragonXLink** [comment]
I can confirm this bug as well, it also happens on the web version too. In addition, when you do this the placements of the difficulties get swapped for some reason. So it goes from "Easy, Norm, Hard" to "Easy, Hard, Norm".

**Comment by MrBossGuy36** [comment]
> I can confirm this bug as well, it also happens on the web version too. In addition, when you do this the placements of the difficulties get swapped for some reason. So it goes from "Easy, Norm, Hard" to "Easy, Hard, Norm".

I just noticed that aswell, i thought i was just tired until you mentioned it

**Comment by LukerUpgradez** [comment]
This also happens for Boyfriend's remix of Darnell. It seems character remixes in general have been separated from the songs for which they are the default character.
![screenshot-2024-09-30-14-04-08](https://github.com/user-attachments/assets/60cf3115-6e54-4750-aed6-6b7b54d74ee0)

**Comment by camsPatience** [comment]
A minor addition, also: the difficulties on BF/Pico mixes are out of order (going in the order of Easy, Hard, Normal)

**Comment by Hundrec** [comment]
Looks like Weekend 1 and Pico Mixes are now displayed as different variations?

https://github.com/user-attachments/assets/aee96b9a-b68d-43b1-9594-c89994f528e8

**Comment by biomseed** [comment]
> Looks like Weekend 1 and Pico Mixes are now displayed as different variations?
> 
>  0.5.1.difficulty.bug.mp4

That's because they are. The playable character's `ownedChars` field decides the character the songs belong to, not the variation name.

**Comment by biomseed** [comment]
They should add this in as a feature, like maybe for debug builds or as an extra sorting category. It could help modders

**Comment by EliteMasterEric** [comment]
Confirmed reproduced, working on seeing if "flattening" variations when possible will solve the problem.
