### ISSUE TITLE
Bug Report: Options menu has no music after entering freeplay or credits

### ISSUE THREAD

**Issue by NioMastr74** [FunkinCrew/Funkin#3488]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.1

### Context (Provide images, videos, etc.)

https://youtu.be/EWvr3PvbARk

### Steps to reproduce (or crash logs, errors, etc.)

Go to freeplay/credits then go to options

**Comment by trayfellow** [comment]
The story mode menu also replays 'freakyMenu' from the very beginning everytime you load in or exit out of the menu everytime aswell

**Comment by Johnsen290** [comment]
and when this happens. if you go to input offsets menu and return back, it crashes the game

**Comment by AbnormalPoof** [comment]
Fixed in v0.5.2.
