### ISSUE TITLE
Crash Report: Null Object Reference when exiting the Input Offset menu

### ISSUE THREAD

**Issue by MTB207** [FunkinCrew/Funkin#3489]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.1

### Context (Provide screenshots or videos of the crash happening)

im not entirely sure how this happened but after downloading the new version and trying to finally fc cocoa erect i noticed that my game wasnt running smoothly as it should so i went to settings where my fps was reseted to 60. music cut off once i got on the options menu and after kicking my frames up and entering the input offset screen for no real reason i got a null object as soon as i tried to exit

### Steps to reproduce

not sure how to replicate this, maybe its a one time thing but still
PS it is not a one time thing

### Crash logs (can be found in the logs folder where Funkin.exe is)

[crash-2024-09-30-21-01-05.log](https://github.com/user-attachments/files/17194466/crash-2024-09-30-21-01-05.log)
[crash-2024-09-30-21-01-03.log](https://github.com/user-attachments/files/17194467/crash-2024-09-30-21-01-03.log)

**Comment by lemz1** [comment]
i looked at the code, and noticed that the crash happens because no music was playing
i'll just quickly make a pr for that

**Comment by lemz1** [comment]
btw i was able to replicate the issue, it seems as if going to freeplay and then back to mainmenu and then to options makes the music cut off, idk why though, definitely gotta look into that

**Comment by AbnormalPoof** [comment]
Fixed in v0.5.2.
