### ISSUE TITLE
Crash Report: You can die during the week 3 cutscene while playing as pico, game crashes.

### ISSUE THREAD

**Issue by Frostee5941** [FunkinCrew/Funkin#3496]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide screenshots or videos of the crash happening)

![image](https://github.com/user-attachments/assets/d97c9787-6394-48bd-b406-5fd0a4065861)
Game crashes when you die. Some bugs can happen from it but in the end it crashes.

### Steps to reproduce

play week 3 as pico
die during cutscene

### Crash logs (can be found in the logs folder where Funkin.exe is)

[crash-2024-09-30-16-50-27.log](https://github.com/user-attachments/files/17196362/crash-2024-09-30-16-50-27.log)
[crash-2024-09-30-16-50-18.log](https://github.com/user-attachments/files/17196363/crash-2024-09-30-16-50-18.log)
pretty sure these are both the same but im not 100% so im uploading both

**Comment by Hundrec** [comment]
To clarify, are you playing on the newest patch 0.5.1, or the Sept 12 update 0.5.0?

**Comment by Frostee5941** [comment]
i didnt even know there was an update, but the crash doesnt occur, there is still bugs tho

**Comment by CrusherNotDrip** [comment]
Duplicate of #3146

**Comment by CrusherNotDrip** [comment]
> i didnt even know there was an update

yea man it dropped today

**Comment by EliteMasterEric** [comment]
Duplicate

**Comment by Frostee5941** [comment]
alr

**Comment by Hundrec** [comment]
Work with me here Linear
