### ISSUE TITLE
Bug Report: Traces from script files don't work.

### ISSUE THREAD

**Issue by Keoiki** [FunkinCrew/Funkin#3497]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.1

### Context (Provide images, videos, etc.)

Traces only work in debug builds, which makes sense, people don't want PlayState and others spamming traces when working on mods. However, hscript has no exception to this rule, making traces not work from .hxc files.

### Steps to reproduce (or crash logs, errors, etc.)

Try calling `trace()` in a script file.

**Comment by CrusherNotDrip** [comment]
me when no trace in hscript:
![steamsad](https://github.com/user-attachments/assets/50fe2faa-878d-4cb7-b51f-0c79c3ce271d)

**Comment by AbnormalPoof** [comment]
Had trouble debugging Funker Selector bc of this lol

**Comment by MAZ12211** [comment]
I genuinely thought it was me only lol
Devs please look into this 🙏

**Comment by AbnormalPoof** [comment]
PR #3728 re-adds traces to non-debug builds.

**Comment by Keoiki** [comment]
> PR #3728 re-adds traces to non-debug builds.

![keoiki](https://github.com/user-attachments/assets/62059037-2114-4d1f-98ae-f026842a2579)
