### ISSUE TITLE
Enhancement: v0.5.1 changelog and release tag

### ISSUE THREAD

**Issue by AbnormalPoof** [FunkinCrew/Funkin#3498]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

I noticed that the changelog hasn't been updated to reflect the new changes in v0.5.1. It would be helpful to know what's changed without having to sift through lots of commits.
![Screenshot 2024-09-30 at 5 04 42 PM](https://github.com/user-attachments/assets/267903df-f08d-4781-818a-f024167d7554)

I'd also recommend making a release tag for v0.5.1 for consistency sake.

**Comment by PSI3x** [comment]
Seconding. I'm interested in what the fixes (aside from the obvious chart editor) were, but there's no information as to what it did.

**Comment by NotHyper-474** [comment]
https://github.com/FunkinCrew/Funkin/releases/tag/v0.5.1

**Comment by EliteMasterEric** [comment]
There's a PR that adds the changelog
