### ISSUE TITLE
Bug Report: Faster song progression problem

### ISSUE THREAD

**Issue by Blue2359** [FunkinCrew/Funkin#3500]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Newgrounds (Web/HTML5)

### Browser

Other (Specify in Description field)

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

Unless I'm tripping, the songs in the 0.5.1 patch update seem to progress a little tiny bit faster than original, but still fast enough to notice something unusual going on, there's also slightly audible clipping noises *(which arise from I assume the vocals)*, while the song is progressing, which can get a bit annoying overtime, I guess.

I did some tests playing some songs on Desktop; *(running on version 0.5.0)*, and on Web; *(running on version 0.5.1)*,
and there does seem to be some lil' differences between each other:

![image](https://github.com/user-attachments/assets/e4d416d5-9c3b-4312-9b46-980b2dbc1567)

I didn't really calculate the math between these song times, so the *3.5%ish* thing I just winged from my head.
This issue might be coming from this PR here #3384, which was merged with the 0.5.1 patch update.

Which might mean that the re-sync check causes the song to progress a *realllyyyy* tiny bit further while
also trying to sync the vocals with the song time, or whatever if I'm getting this correctly...

I haven't tried a Desktop build of the 0.5.1 patch update, but I would assume it behaves the same as the Web build.
*(Edit 1: I've been told that it actually doesn't behave like this on Desktop, but I've yet to try it out.)*
*(Edit 2: It does seem to be behaving the same.)*

`(Also note that my Offsets; (Visual & Input) were both set to 0ms on both platforms during these tests!)`
`Web Browser being used: Brave`

### Steps to Reproduce

There's not really a reproduction method, you just have to play a song in the 0.5.1 patch update.
Everything for it are basically documented in the description already.

**Comment by NotHyper-474** [comment]
Yeah I'm on Firefox and also noticed this. Even the audio clipping.

**Comment by Kade-github** [comment]
I'll have to test later but this could be because of how the game now resyncs more often, from my pr. But otherwise if it has no instrumental offset, nothing should have changed.

Again i'll have to check, as I did test my pr on browser really quickly but not in depth.

**Comment by Hundrec** [comment]
After playing the game on both a PC and a laptop at the same time (both set to 300 fps), I've found that devices with weaker performance lag behind over the course of the song. I think this has to do with the actual framerate the device is reaching as well as its load times for assets and events.

Maybe running this timing test with different framerate caps and different levels of processing power would yield different results?

**Comment by ThatGreenBlur** [comment]
On my lower end device, the frame pacing is atrocious and has so much stutters and rewinds or random offsetting unlike v0.5.0

**Comment by macmacfire** [comment]
I've noticed this is particularly noticeable on Bopeepo Erect, and Thorns both Erect and not. I don't know if each song is sped up differently but it seems like it to me.

**Comment by Shaunyman** [comment]
This issue has been fixed for me in v0.5.2

**Comment by NotHyper-474** [comment]
> This issue has been fixed for me in v0.5.2

Maybe the changes done in https://github.com/FunkinCrew/Funkin/pull/3546 accidentally fixed this

**Comment by Shaunyman** [comment]
> > This issue has been fixed for me in v0.5.2
> 
> Maybe the changes done in #3546 accidentally fixed this

Not sure... I know for a fact that I never changed any offsets though. I don't particularly care _how_ it was fixed, so much that it _was_ fixed

**Comment by Hundrec** [comment]
> After playing the game on both a PC and a laptop at the same time (both set to 300 fps), I've found that devices with weaker performance lag behind over the course of the song. I think this has to do with the actual framerate the device is reaching as well as its load times for assets and events.
> 
> Maybe running this timing test with different framerate caps and different levels of processing power would yield different results?

Just ran this test again on 0.5.2 and they progressed at the same rate throughout the song. 
Hooray!

**Comment by Blue2359** [comment]
Thats weird, I still get the same issue on v0.5.2

**Comment by Blue2359** [comment]
Fixed in 0.5.3, closing this now..!
