### ISSUE TITLE
Bug Report: Character select square completely breaks at framerates below 60FPS

### ISSUE THREAD

**Issue by Squiddu** [FunkinCrew/Funkin#3505]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

When playing at framerates below 60, the "aftereffect" of the character select UI gets extremely volatile.

https://github.com/user-attachments/assets/2d9f3b4b-83f1-4a21-8852-3613df85974e

### Steps to Reproduce

See above.

**Comment by Hundrec** [comment]
Tested every framerate 60 and below: the squares jiggled slightly more with each -5 until I hit 30 fps
Then it looked exactly like this and gave me a good laugh

**Comment by Squiddu** [comment]
I've never seen a cursor so excited to select your ~~dipshit~~ character
