### ISSUE TITLE
Bug Report: Headphone Switching

### ISSUE THREAD

**Issue by EchoDidAThing1048** [FunkinCrew/Funkin#3515]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

when I switched from my wireless earbuds to a speaker, the game audio wouldn't play until I restarted the game.

### Steps to Reproduce

1. Have the game open
2. Connect to a Bluetooth audio device
3. Disconnect the old device and connect a new one

**Comment by EliteMasterEric** [comment]
Duplicate
