### ISSUE TITLE
Bug Report: Soundtray sprite doesn't go away when muting the game with 0

### ISSUE THREAD

**Issue by MAZ12211** [FunkinCrew/Funkin#3518]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

Trying to mute the game with `0` causes the soundtray to stay static in its place and not go away (this wasn't present in v0.5)
This only happens when you press the mute keybind and not increasing/decreasing with `-` or `+`

https://github.com/user-attachments/assets/0945999c-c04f-41ec-80bb-e46931d48a03

### Steps to Reproduce

1. Open the game
2. Once you do that, mute the game with `0` or whatever you set the mute keybind to

**Comment by JVNpixels** [comment]
This may be intentional to let players know the game is muted, but if not then this will need to be fixed!

**Comment by ninjamuffin99** [comment]
This is intentional, we had people who either pressed the mute button, or maybe the game accidentally saved the volume preference on mute, and when they booted up the game it would boot muted. So when the game is muted, we always display the sound tray. It's a rhythm game after all 🙂
