### ISSUE TITLE
Bug Report: Songs lists break after character selection, backing up to main menu and completing a song

### ISSUE THREAD

**Issue by DelovoyB** [FunkinCrew/Funkin#3520]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

There is a way to get non-erect songs and erect songs in one list. This happens after you choose erect or nightmare difficulty and go to character selection menu, complete any song or back up to main menu and hit freeplay again. After that you'll get all songs in one category.

### Steps to Reproduce

1. Open the game
2. Go to any erect or nightmare song in freeplay
3. Press tab to go to character selection | Press esc to go to main menu | Complete any song
4. If you go for character selection then choose boyfriend
![image](https://github.com/user-attachments/assets/11530062-ff08-4046-92c4-bfdc5fdcb552)
![image](https://github.com/user-attachments/assets/c42fdb2b-df5e-4587-a51d-88b652a1e333)

**Comment by Hundrec** [comment]
I think this is the same issue: https://github.com/FunkinCrew/Funkin/issues/3514

**Comment by oddMLan** [comment]
Can confirm the issue, also visible on this [Twitter](https://x.com/MajidyMajidy_/status/1840811401683636307) video
