### ISSUE TITLE
Bug Report: after playing a song on Erect/Nightmare, the songs that dont have erect remixes appear

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3523]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

![image](https://github.com/user-attachments/assets/13e088e0-90d9-4f56-ab23-d9b92904ad32)
this happens after playing any erect mix

### Steps to Reproduce

play any erect/nightmare song

**Comment by Hundrec** [comment]
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3514

**Comment by SnowyyWHY** [comment]
> Duplicate of #3514

okay
