### ISSUE TITLE
Bug Report: Song score data and settings reset after relaunch

### ISSUE THREAD

**Issue by rockybalboba** [FunkinCrew/Funkin#3524]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.0

### Description (include any images, videos, errors, or crash logs)

After downloading the update from itch.io and launching it, my score rankings were there as they should be. I played the new pico remixes and then closed the game, and then some time later I launched the game again and all of my base game/erect/nightmare/mod scores/rankings were completely gone. The only scores/ranks that persisted were the pico remixes. My settings such as volume, note position, and keybinds were also reset after relaunch.

0.5.1 did not fix as I'm sure it just reads the scores as blank now, and I had to complete weekend 1 again to unlock pico but the data for his remixes are still there.

**Comment by Hundrec** [comment]
Are you reporting an instance of save data erasure?
If so, did you do anything in between launches such as powering off your computer?

**Comment by rockybalboba** [comment]
> Are you reporting an instance of save data erasure? If so, did you do anything in between launches such as powering off your computer?

I believe that is the case, and no after closing the game I did other unrelated stuff on the computer for a few hours and then launched the game again to check on something. I haven't installed mods on that build yet or changed anything other than playing the new mixes

**Comment by Hundrec** [comment]
That's really strange, sorry that happened to you
Let us know if this ever happens again and in what context it occurred.

**Comment by rockybalboba** [comment]
sure thing, will probably just wait for 0.5.2 to go through everything again
the erasure is really annoying but a couple fluke gold P ranks on songs I'll never be able to do again are the only things I'm really bummed about

**Comment by NotHyper-474** [comment]
Could be the same issue as https://github.com/FunkinCrew/Funkin/issues/3369

**Comment by speedlorenzo12** [comment]
it happened to me too, I wanted to import a mod in the latest build, but I already had it so I cancelled and then I opened the game and the save disappeared

**Comment by speedlorenzo12** [comment]
going from version 0.5.2 and then going to a previous version will result in the loss of game data

**Comment by rockybalboba** [comment]
Replayed everything on 0.5.2 and subsequent launches appeared fine, moved to 0.5.3 which was an emergency patch regarding save data and everything carried over. Played some mods too and nothing out of the ordinary after relaunches so I'll just close this off
