### ISSUE TITLE
Bug Report: the zoom out at the end of south erect makes the background cut

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3525]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

![image](https://github.com/user-attachments/assets/d43d5aa1-e318-48ef-bdf2-c2e51c3e8b7a)
self explanatory

### Steps to Reproduce

Play south erect

**Comment by Hundrec** [comment]
This was reported here: https://github.com/FunkinCrew/Funkin/issues/3257
