### ISSUE TITLE
Bug Report: Volume bar can be seen all the time if its set to 0%

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3531]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

![image](https://github.com/user-attachments/assets/3090b25d-a490-4815-84bc-f201ca59a293)

### Steps to Reproduce

Open the game and set the volume to 0

**Comment by trayfellow** [comment]
Oh my god your right, you just need to press 0 on your keyboard to reproduce it

**Comment by NotHyper-474** [comment]
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3518

**Comment by SnowyyWHY** [comment]
> Duplicate of #3518

kk
