### ISSUE TITLE
Bug Report: freeplay difficulty selection

### ISSUE THREAD

**Issue by DemiSans** [FunkinCrew/Funkin#3547]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description

So right now seems like weekend 1 has separate ez/hard/norm difficulties (with normal and hard being switched...), so the only way to access weekend 1 in freeplay is switching difficulties at "random".

https://github.com/user-attachments/assets/3e5be3f9-3c1f-44e9-ac57-955a8daf9dde

**Comment by Hundrec** [comment]
Each of these issues has been reported by others. Please search for them to see how they're being addressed!

**Comment by DemiSans** [comment]
Oh, sry. But I cant find the first issue

**Comment by Hundrec** [comment]
Refer to #3487

**Comment by DemiSans** [comment]
oh wow Im blind. Sry

**Comment by Hundrec** [comment]
No worries. Thanks for closing!
