### ISSUE TITLE
Bug Report: whenever a level starts, the game will repeatedly play the same beat after 2 seconds

### ISSUE THREAD

**Issue by scribblesquid** [FunkinCrew/Funkin#3559]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

whenever I play a song, whether its freeplay or storymode, even after a cutscene, after 2 or 3 seconds, the game plays the same beat over and over again, and the notes stop moving. everything still works, but the song just glitches out.

https://github.com/user-attachments/assets/7c4874f9-9835-4a45-8fb5-f6b56ad08660

**Comment by Hundrec** [comment]
This is the same issue as this: https://github.com/FunkinCrew/Funkin/issues/3495
Make sure that your input offsets are set to 0, then see if the issue persists.

**Comment by scribblesquid** [comment]
> This is the same issue as this: #3495 Make sure that your input offsets are set to 0, then see if the issue persists.

thank you, i did not see that post my bad

**Comment by Hundrec** [comment]
No worries! You can close this issue now
