### ISSUE TITLE
Bug Report: Zoom outs on Week 1 Erect makes the background cut

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3568]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

![image](https://github.com/user-attachments/assets/337ea80f-7983-4d5e-907b-62b6d045f02c)
![image](https://github.com/user-attachments/assets/02ee1295-9287-4fa2-bb05-91dab263a917)
![image](https://github.com/user-attachments/assets/c8767cb9-b5b6-4abc-beea-c2d7afac1496)

### Steps to Reproduce

1. Open the game
2. Go to any Week 1 erect song

**Comment by MrBossGuy36** [comment]
Duplicate

**Comment by SnowyyWHY** [comment]
> Duplicate

duplicate of what?

**Comment by AbnormalPoof** [comment]
> Duplicate

Please link the issue next time.

This is a duplicate of #3242.

**Comment by SnowyyWHY** [comment]
> > Duplicate
> 
> I recommend linking the issue next time.
> 
> This is a duplicate of #3242.

thanks, i will close this then
