### ISSUE TITLE
Enhancement: Make 50 combo animation for pixel girlfriend

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3576]
### Issue Checklist

- [X] I have properly named my enhancement
- [ ] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

Make 50 combo animation for pixel girlfriend

**Comment by Hundrec** [comment]
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3284

**Comment by SnowyyWHY** [comment]
> Duplicate of #3284

woah, you are really fast! thanks!
