### ISSUE TITLE
Bug Report: Sometimes the song plays again after the song ends and you need to wait for them to end so the results screen shows up

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3578]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

I was playing Ugh on normal with pico instrumental and after i finished the song, it started playing again but without any chart, after the song ends the second time, result screen pops out

https://github.com/user-attachments/assets/487d54c9-c743-45b9-8488-f9b82bec0662

(sorry for the bad audio quality, when i record with headphones it happens)

### Steps to Reproduce

1. Open the game
2. go to freeplay menu
3. Choose any song with pico instrumental (i think?)
4 finish the song, replay if it doesnt work

**Comment by Hundrec** [comment]
This is the same issue as https://github.com/FunkinCrew/Funkin/issues/3142, but it confirms that the bug is still present in 0.5.1
