### ISSUE TITLE
Bug Report: WHat the Actual FUCK (No words)

### ISSUE THREAD

**Issue by AnniIsHere** [FunkinCrew/Funkin#3579]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

This is the weirdest glitch I have EVER seen in a game... pls just watch the video [https://youtu.be/813QNXE6xKY]
this issue gets """better""" the lesser the framerate is

### Steps to Reproduce

1.Open the game and play any song... That's about it

**Comment by Hundrec** [comment]
The video you linked is private and your description doesn't provide any information.
Might your issue be related to https://github.com/FunkinCrew/Funkin/issues/3495?
