### ISSUE TITLE
Bug Report: Crashing whenever I choose a level

### ISSUE THREAD

**Issue by KirbZ80** [FunkinCrew/Funkin#358]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

## Where are you playing the game?
On my PC
### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [X] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Whenever I try to start any level or in story mode or freeplay it just crashes

## Please describe your issue. Provide extensive detail and images if possible.
![20210204_214758](https://user-images.githubusercontent.com/78567988/106959739-003e2d80-6733-11eb-8cbf-e3caf02b8419.jpg)
This message appears shortly before crashing

**Comment by devin503** [comment]
![image](https://user-images.githubusercontent.com/41199354/107135153-424ba880-68c6-11eb-969a-9520370d75cf.png)
check your data folder (funkin-windows-32bit/assets/data). it's possible the song data is missing. if everything appears to be there, check music, sounds, and images as well.
![image](https://user-images.githubusercontent.com/41199354/107135177-5d1e1d00-68c6-11eb-8a66-c70b161c36ae.png)
![image](https://user-images.githubusercontent.com/41199354/107135180-61e2d100-68c6-11eb-8b20-9de0436e53f5.png)
![image](https://user-images.githubusercontent.com/41199354/107135181-64ddc180-68c6-11eb-96e3-5324a90d2a55.png)
if there are any missing files, try re-extracting the game and playing again.

**Comment by KirbZ80** [comment]
> ![image](https://user-images.githubusercontent.com/41199354/107135153-424ba880-68c6-11eb-969a-9520370d75cf.png)
> check your data folder (funkin-windows-32bit/assets/data). it's possible the song data is missing. if everything appears to be there, check music, sounds, and images as well.
> ![image](https://user-images.githubusercontent.com/41199354/107135177-5d1e1d00-68c6-11eb-8a66-c70b161c36ae.png)
> ![image](https://user-images.githubusercontent.com/41199354/107135180-61e2d100-68c6-11eb-8b20-9de0436e53f5.png)
> ![image](https://user-images.githubusercontent.com/41199354/107135181-64ddc180-68c6-11eb-96e3-5324a90d2a55.png)
> if there are any missing files, try re-extracting the game and playing again.

**Comment by KirbZ80** [comment]
I have checked the files and none are missing but it still doesn't work.

**Comment by devin503** [comment]
> I have checked the files and none are missing but it still doesn't work.

two things: what are your system specs, and have you tried playing an earlier version? I'll use the first question here to make a Windows 10 virtual machine with the same amount of RAM and test the 32-bit version myself

**Comment by KirbZ80** [comment]
First Answer
This is my current setup for the current version
System Specs
Processor: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
RAM: 4GB (2.91 GB usable)
System type: 32-bit OS, x64-based processor

Second Answer (Might not be as useful) 
I have played a previous version which was when week 4 was the latest addition and it worked but poorly as it kept crashing whenever I failed a song and I'd have to boot it up again if I wanted to play and would sometimes just crash anyway if I selected a song. I'd like to note I had a different setup at this point but I do not remember it well enough to give accurate specs.

**Comment by devin503** [comment]
> System type: 32-bit OS, x64-based processor
an x86 OS on an x86_64 processor?
i actually have a windows 7 virtual machine with **3gb** of ram but I'll upgrade it to 4gb and test it, then send results.

**Comment by KirbZ80** [comment]
To add on to my first answer I'm using Windows 10 pro

**Comment by devin503** [comment]
![image](https://user-images.githubusercontent.com/41199354/107291895-e9e7e880-6a36-11eb-9c8b-21b8071d1542.png)
while I couldn't get the game to crash, I did receive an alert from Windows itself about the game taking up too much memory.
(sprites also didn't work in the menu)

**Comment by devin503** [comment]
now of course i was also using a virtual machine for that, but try re-extracting the game and playing to see if that helps

**Comment by KirbZ80** [comment]
I have tried re-extracting and selected the tutorial stage and this happened

![image](https://user-images.githubusercontent.com/78567988/107378246-aeefbe80-6ae3-11eb-8335-b6bfd22642c7.png)

After I competed the song the game crashed and displayed the crash message I sent earlier

**Comment by KirbZ80** [comment]
Alright I've upgraded to a 64 bit system and everything is fine now, I guess its only an issue for 32 bit systems or something idk.
