### ISSUE TITLE
Bug Report: Pico's death screen put the retry button in the wrong place, resulting in a freeze right afterwards

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#3582]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

I just died in Cocoa Erect, and for some reason Pico's bloody retry appeared in the wrong place, seen here. 

![image](https://github.com/user-attachments/assets/4940f2a6-04da-491e-95ec-c95acb8fd13d)

Immediately after I retryed, the game gave me something called a, range error? Here it is:

![image](https://github.com/user-attachments/assets/60cd41ea-e8e3-4e0f-8725-ab1aaa6a217a)

And then this:

![image](https://github.com/user-attachments/assets/ec2ec8a4-024b-4691-9d49-90e8dd43946d)

Right after that, the game freezes, doesn't crash, but you eventually get that windows thing saying: This program isn't responding!- and then you can close it. I was able to repeat the bug on further attempts.

### Steps to Reproduce

1. Open the game
2. Play Cocoa (Pico Mix) - I haven't tested other songs but who knows.
3. Die
4. Restart
5. You're fucked

**Comment by Hundrec** [comment]
These issues were reported in https://github.com/FunkinCrew/Funkin/issues/3146 and https://github.com/FunkinCrew/Funkin/issues/3179
