### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by roboblast6** [FunkinCrew/Funkin#3586]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

1- When you enter the character selection screen normally there will be a boyfriend that will automatically disappear after a second, this is annoying because pico doesn't appear until this boyfriend leaves

2- The songs/pico mix don't seem to appear lol

3- When you exit the character selection screen the random song will have the placeholder image, this is not intentional

Uploading 2024-10-05 03-04-04 (1).mp4…

### Steps to Reproduce

just play normally

**Comment by Hundrec** [comment]
Please title your bug report.

1. I'm not sure what you mean by this, can you elaborate?
2. The separate difficulty issue was reported here: #3487
3. The album placeholder issue was reported here: #3206

Your video didn't finish uploading before you submitted the report, so can you try reuploading it?
