### ISSUE TITLE
Bug Report: Crash makes the game freeze

### ISSUE THREAD

**Issue by Szymonkruk12** [FunkinCrew/Funkin#3588]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

https://github.com/user-attachments/assets/d4e2119d-b1ba-4d53-9b45-1fc1457f1149

### Steps to Reproduce

When the game crash i must use task manager to fix that so please this this bug now!

**Comment by Hundrec** [comment]
This was reported in https://github.com/FunkinCrew/Funkin/issues/3196, but the video you provided is useful!
