### ISSUE TITLE
Bug Report: What...

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3593]
### Issue Checklist

- [ ] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

![image](https://github.com/user-attachments/assets/9aaa480f-10a1-4aff-b3b4-f26c6d98d9ae)
I played South (Pico Mix) on normal and this happened when i ranked up and finished the song
(but its only a visual glitch because when you exit and enter the freeplay menu, it dissapears and the rank is placed on good song)

**Comment by NotHyper-474** [comment]
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3526

**Comment by SnowyyWHY** [comment]
> Duplicate of #3526
