### ISSUE TITLE
[IGNORE] False Issue [IGNORE]

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#3598]
ignore this, my sibling made this for "revenge"

**Comment by JVNpixels** [comment]
W

**Comment by JVNpixels** [comment]
Please ignore everyone, I am so sorry!

**Comment by ExcodeFNF** [comment]
ooh

**Comment by ExcodeFNF** [comment]
what type of problem is this?

**Comment by Hundrec** [comment]
You guys are funny
This actually reveals how GitHub Actions handles author comments after closing, so that's good to know!

**Comment by JVNpixels** [comment]
Wow, I guess this issue was good I guess! He thought he got revenge but he discovered something new for the repo lol.

**Comment by Lasercar** [comment]
I think you need to set a password for your computer

**Comment by JVNpixels** [comment]
> I think you need to set a password for your computer

He knew my password, but now I changed it.
