### ISSUE TITLE
Bug Report: Friday Night Funkin Loading Is Stuck

### ISSUE THREAD

**Issue by megalives717** [FunkinCrew/Funkin#3601]
### Issue Checklist

- [ ] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Web/HTML5)

### Browser

Other (Specify in Description field)

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

![fnfloading](https://github.com/user-attachments/assets/45f8d2d9-20db-4345-ac71-447cecd05152)
The Game Is Not Loading for Low End/Bad PC

**Comment by Hundrec** [comment]
Are you able to download Funkin' from itch.io and launch it there?
I've also noticed low-end computers don't handle the Web version very well.

**Comment by biomseed** [comment]
You just need to wait a while
