### ISSUE TITLE
Bug Report: Character Select Screen Lacks Adobe Animate 24 Compatibility

### ISSUE THREAD

**Issue by toastyfriez** [FunkinCrew/Funkin#3616]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

When attempting to import a sprite atlas using Adobe Animate 2024 rather than 22 to the character select screen, the sprite will have the following issues:
- Offset from its intended position
- When playing the "slidein" animation, all other animations will play as well
- When playing the "deselect" animation, both the "slidein" and "slideout" animations will play afterwards

This is all using the exact same frame timings as the ones found in the Pico Character Select fla.
![Screenshot 2024-10-07 164418](https://github.com/user-attachments/assets/e5841d09-00ad-43ab-a0ea-c0ed4271664f)
Pico fla for reference:
![Screenshot 2024-10-07 164426](https://github.com/user-attachments/assets/5dcaf108-2c58-415d-a953-760c66491273)

Videos showcasing these issues:
https://streamable.com/r4rrnd
https://streamable.com/s8d1tj

The same issues replicated using a re-exported Pico fla:
https://streamable.com/tvddin

### Steps to Reproduce

1. Download a mod containing a new playable character whose character select sprite atlas was made in Adobe Animate 2024 (or possibly a different version other than 22) and place it in the "mods" folder
2. Open game
3. Open character select menu and hover over new playable character

**Comment by charlesisfeline** [comment]
> * [[Bug Report: Girlfriend's Character Select sprite has a stray black line #3565](https://github.com/FunkinCrew/Funkin/issues/3565)] Bug Report: Girlfriend's Character Select sprite has a stray black line (62.02%)

THESE TWO ARENT EVEN RELATED WDYM

**Comment by AbnormalPoof** [comment]
At least you tried, Github Actions.

**Comment by Keoiki** [comment]
The bot is 3 for 3 on potiential duplicates NOT being duplicates, which it had a 60% or greater confidence mind you.

Meanwhile actual duplicates fly over the bots head, I think the bot is just useless at marking duplicate issues.

**Comment by biomseed** [comment]
This is my \# 1 reason why AI is not going to kill us all and y'all are just dum dums.

**Comment by toastyfriez** [comment]
I-SCREAM's Character Select screen stuff uses 24 with no issues, I guess it was just a problem on my end lol 😓
