### ISSUE TITLE
Bug Report: Character Select Is Broken In 30 FPS

### ISSUE THREAD

**Issue by megalives717** [FunkinCrew/Funkin#3621]
### Issue Checklist

- [ ] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

https://github.com/user-attachments/assets/aab67cc7-064c-4f6f-94b6-0db570a34ad2
Character Select Glitch

**Comment by Hundrec** [comment]
This issue was reported here: https://github.com/FunkinCrew/Funkin/issues/3505

**Comment by tposejank** [comment]
Somebody hire @Hundrec for Funkin Team QA bro this is crazy

**Comment by biomseed** [comment]
> Somebody hire @Hundrec for Funkin Team QA bro this is crazy

This but actually
