### ISSUE TITLE
Bug Report: FPS Option is able to be flickered/selected.

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#3624]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

v0.5.1

### Description (include any images, videos, errors, or crash logs)

# Issue

Basically, when you select a bool preference (true or false option), it flickers, but you are able to select the fps option as if it was a bool option when its a numerical option.

# Media

https://github.com/user-attachments/assets/5dfa0aad-49df-4eef-8806-870e654d04d0

### Steps to Reproduce

1. Open the game
2. Go to options
3. Select preferences
4. Go to FPS and press accept (enter, z, space, etc.)

**Comment by JVNpixels** [comment]
Nice try GitHub actions bot! But nah...

**Comment by Hundrec** [comment]
We really need to increase the threshold on this thing...

**Comment by JVNpixels** [comment]
Closing, as the pull request by lemz1 was merged by the myth, the legend, mr muffin.
