### ISSUE TITLE
Crash Report: Deleting introText.txt Will Crashes Friday Night Funkin'

### ISSUE THREAD

**Issue by megalives717** [FunkinCrew/Funkin#3625]
### Issue Checklist

- [ ] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description

![crash](https://github.com/user-attachments/assets/326495ba-57b1-4904-a342-fd450c8f390f)
crash message

### Steps to Reproduce

https://github.com/user-attachments/assets/65e6b4c3-6b3c-4644-a310-33e6b14eedc8
if you delete file crashes the game

### Crash logs

[crash-2024-10-09-15-44-14.log](https://github.com/user-attachments/files/17308385/crash-2024-10-09-15-44-14.log)
crashlog

**Comment by AbnormalPoof** [comment]
Breaking News: Deleting an important asset in a video game crashes said video game.

**Comment by Cartridge-Man** [comment]
> Breaking News: Deleting an important asset in a video game crashes said video game.

News these days be crazy tho, never thought deleting a very important asset can crash ANY game, just thought that only happens to Crash Bandicoot games, now I’ve seen everything..

**Comment by JVNpixels** [comment]
Please close this issue by hitting the purple checkmark button, and yea the intro text is not hardcoded, it relys off the file you deleted and therefore giving you the crash report.
