### ISSUE TITLE
Bug Report: Week 6 Crash

### ISSUE THREAD

**Issue by WaluigiBestGirl** [FunkinCrew/Funkin#365]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [O] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [O] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
While Senpai is doing his whole thing for Thorns, just spam Arrows until your HP is 0.
## Please describe your issue. Provide extensive detail and images if possibe.
It crashes.

**Comment by devin503** [comment]
https://user-images.githubusercontent.com/41199354/107135424-a0798b00-68c8-11eb-84fe-9b828ea8ef56.mp4

![image](https://user-images.githubusercontent.com/41199354/107135426-a1122180-68c8-11eb-9a8c-cfd46f96bfc1.png)
also recreateable by pressing R to reset.
