### ISSUE TITLE
Enhancement: Ability to skip multiple cutscenes except pico meeting pico.

### ISSUE THREAD

**Issue by Stompyyyy** [FunkinCrew/Funkin#3673]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

# Ability to skip:
- Santa Cutscene at the end of Eggnog Erect
- Weekend 1 intro and end (i know you can already do this, but Z as skip should also be allowed)
- Tankman Cutscenes in Week 7
- Senpai transformation scene in Week 6

**Comment by AbnormalPoof** [comment]
Duplicate of #2833.
