### ISSUE TITLE
Enhancement: Ability to continue to the other freeplay song  or restart the current when you get the result screen.

### ISSUE THREAD

**Issue by Stompyyyy** [FunkinCrew/Funkin#3674]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

When you finish a song in freeplay mode and you get the results screen, there should be an option to continue to the next one or replay the one you just beat! Something like:
Try Again? Continue?

**Comment by NotHyper-474** [comment]
Sounds similar to https://github.com/FunkinCrew/Funkin/issues/3658

**Comment by Stompyyyy** [comment]
ah alrighty

**Comment by Lenancha** [comment]
Great minds think alike lol
