### ISSUE TITLE
Enhancement: Changelog Fixing

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#3676]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

Basically just add the new contributors section to 0.5.0 and 0.5.1 since it feels weird and I wanna see who contributed, and the format doesn’t really fit with the other changelog sections.

**Comment by JVNpixels** [comment]
This will probably not be added due to it being older updates, but I just thought that it would be a good idea.

**Comment by Cartridge-Man** [comment]
Have you stopped to think it might not exist in those because nobody new contributed to those updates?

**Comment by JVNpixels** [comment]
> Have you stopped to think it might not exist in those because nobody new contributed to those updates?

I contributed in 0.5.0, so I am wondering, and I am pretty sure in 0.5.1 there was new contributors.

**Comment by Hundrec** [comment]
I did some of this in #3655 right after 0.5.2 released, and then Eric did his own rewrite that conflicted with mine (lol)

**Comment by Hundrec** [comment]
Alright, I've done a bunch more linking all the way back to 0.3.3
That includes highlighting your first contribution in 0.5.0, @JVNpixels!
