### ISSUE TITLE
When playing on new grounds the doesnt load and gets stuck at 58 percent .Bug Report: 

### ISSUE THREAD

**Issue by fnfplssee** [FunkinCrew/Funkin#368]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [ ] macOS

**Comment by devin503** [comment]
try clearing your browser cookies. (in chrome, you can type "clear cache" into the address bar and it'll suggest clearing browser data. uncheck the first and third options, change the option to all time, and click clear.)
![image](https://user-images.githubusercontent.com/41199354/107135517-6ceb3080-68c9-11eb-8fbf-df77faeb0656.png)

**Comment by KeithFromFNF2nd** [comment]
same thing happens to me but it goes to 2fps
