### ISSUE TITLE
Enhancement: Unused character select icons

### ISSUE THREAD

**Issue by Szymonkruk12** [FunkinCrew/Funkin#3686]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

Please add these icon because these are so cool like these
![bfIcon](https://github.com/user-attachments/assets/d66a1052-7362-433a-b1e2-c785613eeb95)
![picoIcon](https://github.com/user-attachments/assets/c85f9803-b1cc-4722-a14b-1f2a215072f3)

**Comment by AbnormalPoof** [comment]
These were sketches used as reference for when turning them into pixel art, I’m pretty sure they’re unused for a reason.
