### ISSUE TITLE
Repeatedly pausing and unpausing during a song desyncs the music.

### ISSUE THREAD

**Issue by SonicBlam** [FunkinCrew/Funkin#37]
Rapidly pausing and unpausing the game causes the music and vocals to desync. The notes desync as well, staying with the vocals.
If you pause and unpause enough, you can move the notes ahead until they're on-beat again, but still late. While that can sound cool sometimes, I don't think that's how the songs are supposed to sound.

**Comment by ninjamuffin99** [comment]
ahh yeah, i've seen this one floatin around. I'll dig into it

**Comment by ninjamuffin99** [comment]
fixed in a recent commit, update coming on Friday with the fix!
