### ISSUE TITLE
Enhancement: Remove 0.5sec of input ignoring when entering pause menu

### ISSUE THREAD

**Issue by DemiSans** [FunkinCrew/Funkin#3709]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

That wasnt a thing before weekend 1 update :(

**Comment by Hundrec** [comment]
I think disabling pause spamming prevents some bugs from occurring, but I'm open to hearing out why you want it back.
What would you want to do with it?

**Comment by DemiSans** [comment]
@Hundrec I want to fast restart the song by pressing enter, ↓, enter, but I cant bc ↓ didnt register and instead im pressing "resume".

And overall, just qol improvement. For navigating in pause menu instantly, without waiting.

**Comment by Hundrec** [comment]
I see, that's a pretty good purpose! Maybe they can find a compromise between disabling inputs and allowing quick restarts.
One idea I have is making the RESET keybind work in the pause menu, instantly restarting the song (as many people have requested)

**Comment by amyspark-ng** [comment]
> I see, that's a pretty good purpose! Maybe they can find a compromise between disabling inputs and allowing quick restarts. One idea I have is making the RESET keybind work in the pause menu, instantly restarting the song (as many people have requested)
i remember asking for it but i think they denied it and instead send me a script that i use to today

**Comment by Average-FNF-Modder** [comment]
> > I see, that's a pretty good purpose! Maybe they can find a compromise between disabling inputs and allowing quick restarts. One idea I have is making the RESET keybind work in the pause menu, instantly restarting the song (as many people have requested)
> 
> i remember asking for it but i think they denied it and instead send me a script that i use to today

Be a G and pass the script around to the class.

**Comment by NotHyper-474** [comment]
> > > I see, that's a pretty good purpose! Maybe they can find a compromise between disabling inputs and allowing quick restarts. One idea I have is making the RESET keybind work in the pause menu, instantly restarting the song (as many people have requested)
> > 
> > 
> > i remember asking for it but i think they denied it and instead send me a script that i use to today
> 
> Be a G and pass the script around to the class.

https://github.com/FunkinCrew/Funkin/issues/2442#issuecomment-2297539376

**Comment by Average-FNF-Modder** [comment]
> > > > I see, that's a pretty good purpose! Maybe they can find a compromise between disabling inputs and allowing quick restarts. One idea I have is making the RESET keybind work in the pause menu, instantly restarting the song (as many people have requested)
> > > 
> > > 
> > > i remember asking for it but i think they denied it and instead send me a script that i use to today
> > 
> > 
> > Be a G and pass the script around to the class.
> 
> [#2442 (comment)](https://github.com/FunkinCrew/Funkin/issues/2442#issuecomment-2297539376)

Thank you fr.

**Comment by amyspark-ng** [comment]
```ts
import funkin.modding.module.Module;
import funkin.play.PlayState;

import funkin.play.PauseSubState;
import funkin.play.PauseMode;

import funkin.ui.freeplay.FreeplayState;
import flixel.FlxG;
import funkin.audio.FunkinSound;

class QuickReset extends Module {
	function new() {
		super('QuickReset');
	}

	function onUpdate(event) {
		if (PlayState.instance != null) {
			if (FlxG.keys.pressed.CONTROL) {
				if (FlxG.keys.justPressed.R) {
					PlayState.instance.needsReset = true;

					// is paused
					if (PlayState.instance.subState != null) {
						PlayState.instance.closeSubState();
					}
				}
			}
		}
	}
}
```

i modified it so it also works if the game is paused

**Comment by amyspark-ng** [comment]
if you want to change the key just replace the FlxG.keys.justPressed.R with the key you want

**Comment by M7theguy** [comment]
where do I add the code to make it work?

**Comment by amyspark-ng** [comment]
> where do I add the code to make it work?
> 
> 

you have to make a .hxc file and place it in a folder in mods so like

funkin/mods/quickreset/reset.hxc

**Comment by ninjamuffin99** [comment]
very nice suggestion, when this is issue gets closed, it means it's merged internally, thanks!

**Comment by Hundrec** [comment]
Sorry @ninjamuffin99, I messed something up!
Can you create a new label called `status: resolved internally`?

**Comment by ninjamuffin99** [comment]
hundrec you devil

**Comment by Hundrec** [comment]
Bahaha, looks like my actions system needs some more work!

I'll make a couple labels suggestions in a new issue for you and Eric to look over.
Hopefully that will make things easier to use :)
