### ISSUE TITLE
Bug Report: Friday Night Funkin’ Slowly Loading

### ISSUE THREAD

**Issue by megalives717** [FunkinCrew/Funkin#3742]
### Issue Checklist

- [ ] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Newgrounds (Web/HTML5)

### Browser

Other (Specify in Description field)

### Version

0.5.2

### Description (include any images, videos, errors, or crash logs)

Why?

### Steps to Reproduce

![srgsrfg](https://github.com/user-attachments/assets/94b94d61-aa59-4bcf-a76e-e4bab1d825f0)
aaaaaaaaaa

**Comment by moxie-coder** [comment]
pretty sure that’s an issue with your WiFi or you don’t have hardware acceleration enabled

**Comment by Hundrec** [comment]
Please properly complete the bug report template before submitting issues.

Even on better devices, Funkin' can load very slowly on Newgrounds. Please try [itch.io](https://ninja-muffin24.itch.io/funkin) or the downloadable build.
