### ISSUE TITLE
Enhancement: third gf sticker fixed

### ISSUE THREAD

**Issue by Szymonkruk12** [FunkinCrew/Funkin#3745]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

Please fix this third gf sticker because gfSticker3 is the only sticker in FNF to not have a lighter, secondary outline
![image](https://github.com/user-attachments/assets/15548367-ceaf-4b56-a4a4-d7e9181401d0)

**Comment by NotHyper-474** [comment]
Duplicate of https://github.com/FunkinCrew/Funkin/issues/2852

**Comment by Hundrec** [comment]
Also, already resolved by https://github.com/FunkinCrew/funkin.assets/pull/33
Please close this issue.
