### ISSUE TITLE
Enhancement: Add a Miss and Accuracy counter to the healthbar

### ISSUE THREAD

**Issue by epokgamr** [FunkinCrew/Funkin#3749]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

it would be nice, most engines have it.

**Comment by AbnormalPoof** [comment]
This was rejected in #2681.

**Comment by charlesisfeline** [comment]
bro we already have HUD scripts that add the two counters, whats the point 😭

**Comment by LukerUpgradez** [comment]
Funkin’s a rhythm game designed for casuals and rhythm game noobs at the end of the day. They already have to deal with dying if they suck too much - having counters reminding them of their imperfection at every moment is likely to reinforce a new player’s negative perception of their abilities. The common fan placement under the HUD also means players’ eyes will move down to the bottom of the screen during breaks, away from the chart.

The team seems to prefer using art and visual feedback to convey information. The game only judges you one time after you’re done, and you get to see a cool animation even if you do terribly. Responding to high-accuracy players through the combo counter and the speaker character’s reactions keeps the action on the center of the screen, right next to the chart. Newer players are less likely to see or pay attention to that feedback, so it won’t affect their mindset until they start getting good enough for it to matter.

I don’t know for 100% sure, but I would guess those are some of the reasons why they rejected this.

**Comment by Hundrec** [comment]
Good points ^

**Comment by JackXson-Real** [comment]
Dave called you a beta cuck for suggesting this

**Comment by Hundrec** [comment]
![image](https://github.com/user-attachments/assets/f908eca5-780c-46fd-a541-f8c52115ef46)

**Comment by trayfellow** [comment]
Since this is probably going to be rejected and closed soon, I suggest checking the mods I linked below that'll solve your issue nicely

[Kade Engine HUD Port](https://gamebanana.com/mods/510941)
[Psych Engine HUD Port](https://gamebanana.com/mods/511527)
[Fancy HUD](https://gamebanana.com/mods/511830)
