### ISSUE TITLE
Bug Report: Game Crash Week 6

### ISSUE THREAD

**Issue by IvanSnow0** [FunkinCrew/Funkin#376]
I was playing the newgrounds version and i was skipping through the text in week 6 roses (spamming the enter button) and then the game crashed. I think it might be because it tried to load two character portraits at the same time, or it tried to load multiple strings of text at the same time.
![Screenshot (66)](https://user-images.githubusercontent.com/78705815/107160545-eb48e080-6964-11eb-85a0-98cae1739ac3.png)

**Comment by BojayB** [comment]
Happens all the time for me too. It's a hinder to gameplay when you just want to play the songs in story mode as quick as you can.

**Comment by IvanSnow0** [comment]
yeah its annoying.
