### ISSUE TITLE
Bug Report: Erect and Nightmare mode are not accessible in Freeplay Mode

### ISSUE THREAD

**Issue by Shana2221** [FunkinCrew/Funkin#3762]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Newgrounds (Web/HTML5)

### Browser

Microsoft Edge

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

I cannot access erect or nightmare mode through pressing left on easy mode or right on hard mode; it just takes me back through easy, medium, and hard mode. I have access to the BF remix for Darnell and all the available Pico remixes when I select Pico in the main menu. 

Edit: added video that shows off the issue: https://youtu.be/Ml-oahnfLUo

### Steps to Reproduce

Simply opening the game on Newgrounds on microsoft edge and google chrome and going to freeplay mode allows the issue to be encountered.

**Comment by GoombarioFan** [comment]
Seems to be #3661. Does switching difficulty not work while having something other than Random selected?

**Comment by Hundrec** [comment]
Not being to switch on random is definitely a bug, but you should be able to switch to Erect/Nightmare on any song that has those difficulties (try this on Bopeebo, for example)

**Comment by Shana2221** [comment]
I just checked and it was possible to switch to erect and nightmare mode on the songs that had an erect and nightmare mode.

**Comment by Hundrec** [comment]
Good, so this is the same issue as mentioned by GoombarioFan. 

You may close this issue and direct your discussion to #3661.
