### ISSUE TITLE
Bug Report: I just opened 5.2 and all my save data's gone. Like actually all of it. (FREAKING OUT)

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#3773]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.2

### Description (include any images, videos, errors, or crash logs)

I was going to play FNF, I opened 5.2, ALL OF MY SAVE DATA WAS GONE, WIPED, HISTORY. Not even just my highscores. Pico is no longer unlocked, and even in chart editor I could tell it was wrong because I don't have any "Recent" charts to open. Even my keybinds and preferences were reset! I LITTERALLY DON'T KNOW WHAT HAPPENED. So I opened 4.2, and IT WAS STILL LIKE THAT. It happens on all versions. I tried to read my save file, but I don't know enough about it to know if my save-file is actually corrupted or if FNF is just reading it wrong. I'm lowkey freaking out right now.

The only thing I can think of as a cause  is that I hadn't opened the game since 5.3 dropped but like... I don't even HAVE 5.3??? So how would that be able to affect my game? I don't even know I am just so in disarray right now and this is definitely a HIGH priority bug to be figured out, like on an even higher level then the last big that put on this pedestal with the "Scores being overwritten by lower ones" bug (And the 2hot naming inconsistency lol). 

Please if anyone knows what caused this or how to fix it let me know.

### Steps to Reproduce

1. Open the game.
2. I don't know what caused it???

**Comment by NotHyper-474** [comment]
https://github.com/FunkinCrew/Funkin/issues/3679

Unfortunately there's no way to recover it

**Comment by Hundrec** [comment]
I'm sorry this happened to you, but this has been the first pinned issue for over a week.
Time to get back on that grind!

**Comment by Average-FNF-Modder** [comment]
> I'm sorry this happened to you, but this has been the first pinned issue for over a week. Time to get back on that grind!

Fuck. You know, I have One Drive, and have managed to get earlier versions of my save file. Attempts to replace it back into the game are failing. Is there any known way to implement the save file if I actually still HAVE the version with all the correct scores?

**Comment by Hundrec** [comment]
If you still have a copy of your Funkin1.sol file, simply replace the existing sol file in your %appdata%\FunkinCrew folder.
Then, never open 0.5.2 again.

**Comment by Average-FNF-Modder** [comment]
> Unfortunately there's no way to recover it.

I'm sorry, but I am unfamiliar with what that file is or even what a .sol file is in general. I mean to say that I have an earlier copy of "scores.json" that is different and seems to still have all the right data.

**Comment by Hundrec** [comment]
I don't think you can recover your save data with a scores.json file.
Please correct me if I'm wrong (I hope I am)

**Comment by Average-FNF-Modder** [comment]
> I don't think you can recover your save data with a scores.json file. Please correct me if I'm wrong (I hope I am)

Is that not what saves them anyways? If the game wouldn't so stubbornly rewipe it every time I enter, then everything would be fine. 

In lieu of that, what is a .sol file, and where would I find the one I'm apparently looking for?

**Comment by Hundrec** [comment]
To obtain your .sol file:
1. Press **Win + R**
2. Enter %appdata%
3. Click OK
4. Locate and open the `FunkinCrew` folder

**Comment by Average-FNF-Modder** [comment]
How do I know if I have the right one (One that has the old data) and where would I put it? (Thank you so fucking much for this man.)

**Comment by Hundrec** [comment]
If you don't care about your current post-wipe save, you can just replace it with any .sol file you might have and then load up 0.5.3 to check its progress.
Otherwise, make a backup copy of the existing save and then go through with the replacement.

**Comment by Average-FNF-Modder** [comment]
> If you don't care about your current post-wipe save, you can just replace it with any .sol file you might have and then load up 0.5.3 to check its progress. Otherwise, make a backup copy of the existing save and then go through with the replacement.

Sorry I died for a moment. Ok, so I have the file. Where do I go and what specifically do I replace with this new file?

**Comment by Hundrec** [comment]
To clarify, you need to have backed up a .sol file before the wipe to restore it.
You'll need to take the backup of `Funkin1.sol` and replace the post-wipe `Funkin1.sol`

![image](https://github.com/user-attachments/assets/9cc0467c-ef5b-40ac-a708-c6f8e1489ca3)

**Comment by Average-FNF-Modder** [comment]
> To clarify, you need to have backed up a .sol file before the wipe to restore it. You'll need to take the backup of `Funkin1.sol` and replace the post-wipe `Funkin1.sol`
> 
> ![image](https://private-user-images.githubusercontent.com/170126004/380360841-9cc0467c-ef5b-40ac-a708-c6f8e1489ca3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTQ0NzAsIm5iZiI6MTcyOTkxNDE3MCwicGF0aCI6Ii8xNzAxMjYwMDQvMzgwMzYwODQxLTljYzA0NjdjLWVmNWItNDBhYy1hNzA4LWM2ZjhlMTQ4OWNhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwMzQyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDdkODNkZDMxZTFjMjg0ZDA1ODg5ZTNkODg2Mzc4N2ZmOWE5ZTkyODcyNWMzNDk4NmQ3ZmQzMjhkYmQ4Zjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6DYJ3mc8AW9wVqgqYEv-KbUFtY2xWZMKRjyS8KJfoZI)

Oh ok, I'll try that with one drive

**Comment by Average-FNF-Modder** [comment]
> > To clarify, you need to have backed up a .sol file before the wipe to restore it. You'll need to take the backup of `Funkin1.sol` and replace the post-wipe `Funkin1.sol`
> > ![image](https://private-user-images.githubusercontent.com/170126004/380360841-9cc0467c-ef5b-40ac-a708-c6f8e1489ca3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTQ0NzAsIm5iZiI6MTcyOTkxNDE3MCwicGF0aCI6Ii8xNzAxMjYwMDQvMzgwMzYwODQxLTljYzA0NjdjLWVmNWItNDBhYy1hNzA4LWM2ZjhlMTQ4OWNhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwMzQyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDdkODNkZDMxZTFjMjg0ZDA1ODg5ZTNkODg2Mzc4N2ZmOWE5ZTkyODcyNWMzNDk4NmQ3ZmQzMjhkYmQ4Zjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6DYJ3mc8AW9wVqgqYEv-KbUFtY2xWZMKRjyS8KJfoZI)
> 
> Oh ok, I'll try that with one drive

The version I was able to recover is missing one of my best Golden-P's, but other than that it seems intact. Thank you dearly, this genuinely means so much to me.

**Comment by Hundrec** [comment]
No problem! Be sure to back up your save files regularly from now on :)

**Comment by Average-FNF-Modder** [comment]
> No problem! Be sure to back up your save files regularly from now on :)

You get bet I won't be forgetting now. Scared the life outta me.
