### ISSUE TITLE
Bug Report: Warning: Lime version  may not be compatible with OpenFL openfl (expected version 7.7.0+)

### ISSUE THREAD

**Issue by embedded-p** [FunkinCrew/Funkin#3803]
### Issue Checklist

- [x] I have properly named my issue
- [x] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Compiled from GitHub Source Code

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

![Capture d'écran 2024-10-29 210031](https://github.com/user-attachments/assets/ae0e3be3-5f69-4dfc-a6cf-98cdab0f428d)
Hi, each time i tried to compile the game after following the instructions on COMPILING.md, it says that either might something should be in the specific order or if the lime version didn't correspond to the game requirements (as i installed 7.0.0 after actually installing it first), i couldn't find any project.xml (or any other .xml file, there's ton of project.xml files) that respond for that exact code. Could you point out where the file is, or, you can just adjust the code so i can compile the game properly, just don't forget to tell me where the issue were from. I appreciate your work and dedication, even in the hard times.

> Love from the valid xister. 
> FNFWABA -ACK! -ACK! -ACK!
> P.S.: Don't mind the manner of that text, i'm still mental, just playing all along as the part of the bald men with glasses site, despite of that, i'm highly tolerant, but the only thing i need is therapy.

### Steps to Reproduce

If you're new to FNF modding or contribution like myself, then you'd might to clone the repo and follow the compilation instructions on COMPILING.md file on the docs folder, you may encounter the same problem.
![Capture d'écran 2024-10-29 212202](https://github.com/user-attachments/assets/fc2a714f-95e3-4a87-8d72-bc5393250034)

**Comment by AbnormalPoof** [comment]
Not a bug. It says Warning for a reason, just ignore it.

**Comment by NotHyper-474** [comment]
Like AbnormalPoof said, those are just warnings and can be safely ignored.
The line that actually matters here is the `Error: Source path "art/readme.txt" doesn't exist`. Did you run `git submodule update --init --recursive` like Step 4 says?

**Comment by embedded-p** [comment]
> Like AbnormalPoof said, those are just warnings and can be safely ignored. The line that actually matters here is the `Error: Source path "art/readme.txt" doesn't exist`. Did you run `git submodule update --init --recursive` like Step 4 says?

I did it before, but i recently encountered the another problem, there's nothing in the art folder, i tried to type the command one more time - nothing happened.

**Comment by embedded-p** [comment]
> Not a bug. It says Warning for a reason, just ignore it.

I thought that it was the program-related problem.

**Comment by Hundrec** [comment]
Did you follow Hyper's instructions?

If so, did they work?

If this still doesn't work, you can try deleting your files and starting over. Sometimes we forget to follow a crucial step!

**Comment by embedded-p** [comment]
> Did you follow Hyper's instructions?
> 
> If so, did they work?
> 
> If this still doesn't work, you can try deleting your files and starting over. Sometimes we forget to follow a crucial step!

I did it all, i strictly followed every instructions, i want to know how i can install the art resources properly. I found the TROUBLESHOOTING doc, and it said: 

>Other compilation issues may be caused by installing bad library versions. Try deleting the `.haxelib` folder and following the guide starting from **Step 5**.

Which i hoped that it's the way i can resolve the art folder resources problem, but i ended up just deleting the dependencies. I tried to install the missing ones by manually each time i launch the "haxelib run lime test windows" command. I want to hear your opinions if i should reinstall Haxe.

**Comment by Hundrec** [comment]
If you properly followed up to Step 4 of the compiling guide, your art folder should not be empty. Make sure you run `cd` into the right folder and restart from Step 4.

**Comment by embedded-p** [comment]
> If you properly followed up to Step 4 of the compiling guide, your art folder should not be empty. Make sure you run `cd` into the right folder and restart from Step 4.

My source directory is C:\Users\[user]\Documents\funker\Funkin

**Comment by Hundrec** [comment]
Please run the command from Step 4 and send a screenshot of the output.

**Comment by embedded-p** [comment]
> Please run the command from Step 4 and send a screenshot of the output.

![Capture d'écran 2024-10-30 001338](https://github.com/user-attachments/assets/b98bf29a-c10d-4a0f-a9ab-8f7083e57dcb)
![Capture d'écran 2024-10-30 001402](https://github.com/user-attachments/assets/df142d07-0e7b-433d-9ecf-ee546f35b04a)

**Comment by Hundrec** [comment]
Okay, that's strange. Hopefully nothing's wrong with the repository right now!

Try deleting everything and starting from scratch. Let us know how it goes.

**Comment by embedded-p** [comment]
> Okay, that's strange. Hopefully nothing's wrong with the repository right now!
> 
> Try deleting everything and starting from scratch. Let us know how it goes.

Golly, i didn't believe that FNF source folder was that large.
![Capture d'écran 2024-10-30 003220](https://github.com/user-attachments/assets/d30b10a6-aa46-475a-8649-2bc8430303cd)

**Comment by embedded-p** [comment]
Why is the git submodule update --init --recursive is so damn lengthy? I no have patience to waste the time.

**Comment by moxie-coder** [comment]
> Why is the git submodule update --init --recursive is so damn lengthy? I no have patience to waste the time, i even did canceled the operation multiple times.

there's a lot of assets it has to go through, it may depend on the speed of your internet but you gotta wait for it to finish, don't cancel it while it works, it'll get done eventually, you have to wait

**Comment by embedded-p** [comment]
> > Why is the git submodule update --init --recursive is so damn lengthy? I no have patience to waste the time, i even did canceled the operation multiple times.
> 
> there's a lot of assets it has to go through, it may depend on the speed of your internet but you gotta wait for it to finish, don't cancel it while it works, it'll get done eventually, you have to wait

Oh, so the patience is actually rewarding? Alright, i'd wait for it despite my monthly unlimited internet getting slower each day.

**Comment by Hundrec** [comment]
Funkin' has an increasingly large list of assets that can take a long time to download. 
Compiling can require a great deal of patience as well, as compiling version 0.3.3 on my laptop would initially take over 15 minutes to complete.
