### ISSUE TITLE
Bug Report: Error while executing function PicoPlayerCharacter.doExplosionDeath0Z201: ElnvalidAccess InvalidAcce55 error: Tried 'add', but it is not a valid field or method. Is the target object null?

### ISSUE THREAD

**Issue by embedded-p** [FunkinCrew/Funkin#3814]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Compiled from GitHub Source Code

### Browser

None

### Version

0.5.2

### Description (include any images, videos, errors, or crash logs)

Guys, i'd like to find out what the fix is for that, that's in the exact moment i've lost in 2Hot.
![Capture d'écran 2024-10-31 162444](https://github.com/user-attachments/assets/ae01ca22-732a-47d5-a262-50641e51f87c)

**Comment by Hundrec** [comment]
This issue was already reported in https://github.com/FunkinCrew/Funkin/issues/3308.
You may close this issue and contribute to the discussion there.

**Comment by embedded-p** [comment]
> This issue was already reported in #3308. You may close this issue and contribute to the discussion there.

Understandable, thanks.
