### ISSUE TITLE
Bug Report: Plethora of cosmetic bugs that should be fixed

### ISSUE THREAD

**Issue by JayWarudo** [FunkinCrew/Funkin#3817]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

Instead of reporting a singular big issue, I'm reporting tons of smaller slightly annoying cosmetic bugs that shouldn't be too hard to fix.

1 - The Blazin' offsets are completely messed up when dying or restarting, including the death screen.

2 - The retry text in the pico week 5 death screen is offset.

3 - The 2hot can explosion death screen is all kinds of messed up, this also includes some errors, although these errors can just be ignored.

4 - The freeplay rank reactions no longer smoothly go back to idle like in 0.4.X, they now play too long and flicker for a second instead of having in-between frames going into idle.

5 - Whenever you beat an erect song, songs that do not yet have erect remixes will show up without a character icon next to them, and going to those songs will change the difficulty to normal. This is pretty annoying if you want to play all the erect songs in a row.

6 - The week 1 and 2 erect backgrounds aren't big enough to fit the camera movement in the all of the week 1 erect songs and the zoom out at the end of South Erect. So sometimes the outside of these backgrounds are visible.

### Steps to Reproduce

Steps for bug 1 : Die or retry in Blazin'.
Steps for bug 2 : Die in Eggnog (Pico Mix).
Steps for bug 3 : Die in 2hot via Darnell's explosive cans.
Steps for bug 4 : Beat any song in freeplay.
Steps for bug 5 : Beat any erect song.
Steps for bug 6 : Beat any week 1 erect song or South Erect.

**Comment by JayWarudo** [comment]
If there need to images attached to any of these bugs, please let me know.

**Comment by MAZ12211** [comment]
All of these have been reported in their own issues, you can close this.

Also, bugs are easier to track when they're posted as their own separate issues instead of a big checklist of bugs posted as one issue.

Think of it like a todo list, instead of "I want to `taskA`, `taskB`, `taskC`" as one task, it's easier to have each task as their own separate task to check.

**Comment by JayWarudo** [comment]
> All of these have been reported in their own issues, you can close this. (Unless somebody else has never reported one of them)
> 
> Also, bugs are easier to track when they're posted as their own separate issues instead of a big checklist of bugs posted as one issue.
> 
> Think of it like a todo list, instead of "I want to `taskA`, `taskB`, `taskC`" as one task, it's easier to have each task as their own separate task to check.

Oh, i see. I'll keep that in mind for next time. Some of these issues have been reported over a month ago, but still about nothing has been done about them in the hotfixes, hopefully the pitstop does something about them.

**Comment by Hundrec** [comment]
Can confirm each of these issues has been reported:
1. https://github.com/FunkinCrew/Funkin/issues/3168
2. https://github.com/FunkinCrew/Funkin/issues/3179
3. https://github.com/FunkinCrew/Funkin/issues/3182
4. https://github.com/FunkinCrew/Funkin/issues/3432
5. https://github.com/FunkinCrew/Funkin/issues/3514
6. https://github.com/FunkinCrew/Funkin/issues/3785

If the issues are old, you may bump the issue by commenting on them. Please do not create duplicates!
