### ISSUE TITLE
Enhancement: Tankman Battlefield Erect Stage

### ISSUE THREAD

**Issue by TureenOfficial** [FunkinCrew/Funkin#3819]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

every other stage has an erect variant so it would only make sense

**Comment by Hundrec** [comment]
They're definitely working on this. I expect them to release a Week 7 erect stage in an upcoming destination/pitstop.

**Comment by AbnormalPoof** [comment]
sorry bout that lol this is in 0.6.0
