### ISSUE TITLE
Enhancement: Increase Scroll Speed on Slow Hard Difficulty Songs

### ISSUE THREAD

**Issue by Toadette8394** [FunkinCrew/Funkin#3825]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

The scroll speed on some of the Hard difficulty songs, especially the older ones like in Week 3, should be increased because they are legitimately so slow that it is very hard to hit the notes properly. The newer weeks are a lot better about this but the old ones seriously need to be faster and since it is already on Hard difficulty it's not that unreasonable of a change.

**Comment by Hundrec** [comment]
Note: Similar to #3101
