### ISSUE TITLE
Bug Report: not opening

### ISSUE THREAD

**Issue by fluttermsm** [FunkinCrew/Funkin#383]
so like i downloaded 64 bit since my pc is a 64 bit
extracted files to a folder
and i cannot open the game
no error code i just can't

**Comment by devin503** [comment]
are you starting the game in its root directory? shortcuts to the game don't always work properly.
![image](https://user-images.githubusercontent.com/41199354/107292472-e7d25980-6a37-11eb-8104-d5ec7403572f.png)

**Comment by Whatisbehindu** [comment]
I run into the same issue. Extracted from .zip and .exe closes as soon as it opens according to task manager

**Comment by c3ypt1c** [comment]
Maybe your antivirus?

**Comment by Whatisbehindu** [comment]
Doubt it. I have funkin.exe set to excluded for virus scans and passes through firewall
