### ISSUE TITLE
Bug Report: in blazin darnell is too low after dying and restarting

### ISSUE THREAD

**Issue by jacobtheminer11** [FunkinCrew/Funkin#3842]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Web/HTML5)

### Browser

Opera

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

![Screenshot (3)](https://github.com/user-attachments/assets/c323be13-574f-4552-91b1-27af7e1762ce)
as you can see darnell is too low

### Steps to Reproduce

idk

**Comment by charlesisfeline** [comment]
sorry but its a dupe of #3168

**Comment by Hundrec** [comment]
Please close this issue since it has been reported before.
