### ISSUE TITLE
Bug Report: Results Text is moveable

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#3845]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

v0.5.3

### Description (include any images, videos, errors, or crash logs)

I was spamming arrow keys in the results screen for fun, but then I saw that the text was moving?
(Hitsounds were included for proof of pressing arrow keys)

https://github.com/user-attachments/assets/55df9392-e25f-455c-a742-df63da41823d

Nothing really else to say, but I don't know if this was an intentional debug feature that was left in by mistake or something?

### Steps to Reproduce

1. Open the game...
2. Beat a week/song through Story Mode or Freeplay
3. Get to the results screen
4. Press arrow keys and (maybe) see error.

**Comment by JVNpixels** [comment]
I am still able to reproduce without mods.

**Comment by AbnormalPoof** [comment]
Looks like this is some leftover debug code!
https://github.com/FunkinCrew/Funkin/blob/9e13ea0b2c0799d9a7fae7db56eddb05898739d0/source/funkin/play/ResultState.hx#L724C1-L729C6

**Comment by amyspark-ng** [comment]
i've known about this for months but didn't want people to find out so they don't remove it :pensive:

**Comment by AbnormalPoof** [comment]
> i've known about this for months but didn't want people to find out so they don't remove it 😔

```haxe
import funkin.play.ResultState;
import funkin.modding.module.Module;
import flixel.FlxG;

class ResultsThing extends Module {
	public function new() {
		super('ResultsThing');
	}

	function onUpdate() {
	    if (FlxG.state.subState is ResultState) {
	      if (FlxG.keys.justPressed.RIGHT) FlxG.state.subState.speedOfTween.x += 0.1;
	      if (FlxG.keys.justPressed.LEFT) FlxG.state.subState.speedOfTween.x -= 0.1;
	    }
	}
}

**Comment by JVNpixels** [comment]
no problem ninjamuffin, i love you bro. (kisses cutely)
