### ISSUE TITLE
Bug Report: FlxTint not found

### ISSUE THREAD

**Issue by sphis-Sinco** [FunkinCrew/Funkin#3846]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Compiled from GitHub Source Code

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

 ERROR  source/funkin/ui/charSelect/Lock.hx:4: characters 8-34

 4 | import flxanimate.effects.FlxTint;
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^
   | Type not found : flxanimate.effects.FlxTint

### Steps to Reproduce

Compile Game

**Comment by Hundrec** [comment]
Have you tried deleting the `.haxelib` folder and then reinstalling starting from Step 5?

**Comment by Hundrec** [comment]
Please try following my suggestion if you still want to compile the game.
Otherwise, you should close this issue.

**Comment by sphis-Sinco** [comment]
> Have you tried deleting the `.haxelib` folder and then reinstalling starting from Step 5?

Trying right now

**Comment by sphis-Sinco** [comment]
> For some reason sometimes just deleting the folder isn't enough. Try `hmm reinstall -f flxanimate`

now I have this
![image](https://github.com/user-attachments/assets/282fdce8-3b2f-4e94-a55e-75de35497993)

**Comment by NotHyper-474** [comment]
Can't say for sure what's wrong here. But from my investigation in https://github.com/FunkinCrew/Funkin/issues/2333#issuecomment-2375494911 reinstalling polymod might fix that.

**Comment by sphis-Sinco** [comment]
> Can't say for sure what's wrong here. But from my investigation in [#2333 (comment)](https://github.com/FunkinCrew/Funkin/issues/2333#issuecomment-2375494911) reinstalling polymod might fix that.
> 
> If all fails you can try reinstalling everything through just `hmm reinstall -f`.

I think I will
![image](https://github.com/user-attachments/assets/1f94bcfc-5a7a-4c74-8eb4-b6a7e09408a1)

**Comment by NotHyper-474** [comment]
lol

**Comment by sphis-Sinco** [comment]
> lol

It's still reinstalling

**Comment by sphis-Sinco** [comment]
> Can't say for sure what's wrong here. But from my investigation in [#2333 (comment)](https://github.com/FunkinCrew/Funkin/issues/2333#issuecomment-2375494911) reinstalling polymod might fix that.
> 
> If all fails you can try reinstalling everything through just `hmm reinstall -f`.

IT WORKED!!!!
ITS WORKING
THANK YOU SO MUCH
![image](https://github.com/user-attachments/assets/90583361-ec87-4b20-a426-79d4023ac0ca)
