### ISSUE TITLE
Spritemap1 anime play

### ISSUE THREAD

**Issue by Stupidcoderfnf** [FunkinCrew/Funkin#3852]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

Opera

### Version

0.7.3

### Description (include any images, videos, errors, or crash logs)

What script do i use to play animation of
Spritemap1?

**Comment by AbnormalPoof** [comment]
https://github.com/FunkinCrew/Funkin/issues/2477#issuecomment-2110876798:

> You can instantiate an FlxAtlasSprite to play an Animate Atlas, or use AnimateAtlasCharacter to render a character in a song (see the Blazin' character data files for an example of how to do this). Future functionality will make it easier to mix and match sprite sheets and Atlases, and to use Atlases in stages.

**Comment by Hundrec** [comment]
0.7.3 is a version of Psych Engine.
In the future, please verify that you are reporting to the correct GitHub repository.
Also, please ask questions like these in the Discussions tab.

We can close this issue now.

**Comment by EliteMasterEric** [comment]
I got confused and thought bro was from the future

**Comment by JVNpixels** [comment]
So many people use Psych Engine that they probably think it is the real game lol!
