### ISSUE TITLE
Bug Report: black characters

### ISSUE THREAD

**Issue by Milkycream143** [FunkinCrew/Funkin#386]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

## Where are you playing the game?
On mobile
### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ x] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7 
## Please describe your issue. Provide extensive detail and images if possibe.

![Screenshot_20210210_020712_com ninjamuffin99 funkin](https://user-images.githubusercontent.com/78813936/107400228-f65a6700-6b44-11eb-967f-1a3e1c0ae6d9.jpg)

**Comment by devin503** [comment]
before i begin, **the android port is not an official port of the game.**
what are the specs of your phone? older phones or those with less memory will have issues running the game.
