### ISSUE TITLE
Bug Report: Songs with Alt Instrumentals can be selected more that one time on Freeplay

### ISSUE THREAD

**Issue by Honton129** [FunkinCrew/Funkin#3865]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

Duplicated of https://github.com/FunkinCrew/Funkin/pull/3615 and https://github.com/FunkinCrew/Funkin/issues/3562

So when i select a song with an unlocked alt instrumental (Ex. Bopeebo, Spookeez or every song with a Pico Mix)
I am able to spam the select button as seen here on the video:

https://github.com/user-attachments/assets/c8259bb2-5107-44a1-a11a-85b745f559ed

It also doesn't blocks the input for change the instrumental:

https://github.com/user-attachments/assets/7c2c1a35-b3a1-4e2f-a01c-7b5f62460b2b

Doing an extra issue because i haven't seen people tried to fix it (aside from https://github.com/FunkinCrew/Funkin/pull/3615)

### Steps to Reproduce

1. Go to freeplay.
2. Select any song with an unlocked alt instrumental.
3. Spam the accept button.
4. Bug reproduces.

**Comment by AbnormalPoof** [comment]
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3562, “extra” issues are not needed since it makes it harder for the maintainers to keep track of everything.

**Comment by Honton129** [comment]
yeah makes sense.
so do i close and move the discussion to the original issue?

**Comment by charlesisfeline** [comment]
> yeah makes sense. so do i close this issue and move the discussion to the original issue?

close

**Comment by Honton129** [comment]
oki doki
