### ISSUE TITLE
Bug Report: Won't compile because of a missing: lime.ndll

### ISSUE THREAD

**Issue by sphis-Sinco** [FunkinCrew/Funkin#3867]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Compiled from GitHub Source Code

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

im trying to compile the game and I got
```
Uncaught exception - Could not find lime.ndll. This file is provided with Lime's Haxelib releases, but not via Git. Please copy it from Lime's latest Haxelib release into either C:\HaxeToolkit\haxe\lib\lime/8,0,2/src//ndll/Windows or C:\HaxeToolkit\haxe\lib\lime/8,0,2/src//ndll/Windows64, as appropriate for your system. Advanced users may run `lime rebuild cpp` instead.
```

i did what it said but nothing changed
it gave me the same thing

**Comment by NotHyper-474** [comment]
On which platform are you?

**Comment by sphis-Sinco** [comment]
ok

**Comment by sphis-Sinco** [comment]
worked!
