### ISSUE TITLE
Bug Report: Error: Could not determine current git branch; is this a proper Git repository?

### ISSUE THREAD

**Issue by sphis-Sinco** [FunkinCrew/Funkin#3868]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Compiled from GitHub Source Code (Windows)

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

I was trying to compile
and I got a
```
Error: Could not determine current git branch; is this a proper Git repository?
```

**Comment by moxie-coder** [comment]
it’s self explanatory, you didn’t clone the FNF repo

**Comment by sphis-Sinco** [comment]
> it’s self explanatory, you didn’t clone the FNF repo

I HAVE to clone it?
I can't just download the zip?

**Comment by AbnormalPoof** [comment]
You have to clone the repo or else the submodules won't work.

**Comment by sphis-Sinco** [comment]
oh

**Comment by moxie-coder** [comment]
> You have to clone the repo or else the submodules (`art`, `assets`) won't work.

and those are required, downloading a zip won't download those too

**Comment by sphis-Sinco** [comment]
> > You have to clone the repo or else the submodules (`art`, `assets`) won't work.
> 
> and those are required, downloading a zip won't download those too

it did for me, that's why I was confused

**Comment by moxie-coder** [comment]
> what does repo mean bc im trying to make a fnf mod doing a build im new to making builds and more and i wanna know what fnf repo stands for or what mean

https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository read this first if you want to understand what it means and to know how to clone repos

**Comment by Viquitus** [comment]
how the heck i do this... (im new to coding stuff and i know NOTHING about this repo thing) i did clone the repo but the game still doesnt open

**Comment by Hundrec** [comment]
Please follow the [Compiling Guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/COMPILING.md) very carefully. Missing a single step can create errors!
