### ISSUE TITLE
Bug Report: lag in every song of fnf

### ISSUE THREAD

**Issue by speedlorenzo12** [FunkinCrew/Funkin#3870]
### Issue Checklist

- [x] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

Hi, I know there are many lag reports but mine is slightly different.
I randomly receive some lag, as you notice in the video, belonging the sound part you do not notice well in the video, the arrows are immobilized for a moment also making me make miss as well as being very annoying.

https://github.com/user-attachments/assets/d84f516d-626a-4c93-923d-112d8ef319d7

I have tried for months to solve it alone but I never succeeded so now I wanted to try to ask the community if someone had the same problem; and it also happens with the mods (obviously I made the video without mods activated)
I have a decent pc and in the past this lag did not happen

### Steps to Reproduce

1. open the game
2. play casual songs

**Comment by AbnormalPoof** [comment]
Looks like this is the same issue as #3495, #3380 and like 3 other duplicate issues that aren't worth mentioning. I could be wrong, though.

**Comment by speedlorenzo12** [comment]
the problem was returning to 60 fps, as soon as I returned to 150fps the game became fluid again, unfortunately I tried with lag and not swing however the problem is practically solved
