### ISSUE TITLE
Bug Report: Hmm erroring during installation process

### ISSUE THREAD

**Issue by Daikicalla** [FunkinCrew/Funkin#3871]
### Issue Checklist

- [x] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Compiled from GitHub Source Code

### Browser

None

### Version

0.5.2

### Description (include any images, videos, errors, or crash logs)

I have attempted to use hmm multiple times now to install all the dependencies that FNF needs to decompile. However, every single time I get to jsonpath, the whole thing decides to error and I cannot install anything from that point on. Here is the error that has been ruining the entire hmm workflow:
![image](https://github.com/user-attachments/assets/4c9d8919-6d65-4ec1-9bc6-414fa1a3fa63)

Because of this, it leads me to downloading everything individually on github, then having to use hmm git to apply them appropriately. Unfortunately, this method is actually not working for me. I consistently run into issues during compiling, which involve tickets such as #3750, #2872, #3370 and many others. I have however ran into another error today (which I have not ran into yet, nor is there any ticket about yet), which is `Type not found : json.JSONData` for polymod. (I have already reinstalled haxe and every single dependency i could).

Is there any other alternatives to reliably get the dependencies for FNF compiling? Hmm just isn't working for me at all flat out and I'm getting absolutely sick of it.

### Steps to Reproduce

1. Follow the [Compiling Guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/COMPILING.md) all the way to step 6.
2. Attempt to use `hmm install`.
3. Error upon reaching jsonpath.

**Comment by Hundrec** [comment]
When you run `hmm install`, do you encounter the same error as the one in your screenshot?
Did you make sure to run both commands in Step 5?

**Comment by Daikicalla** [comment]
> When you run `hmm install`, do you encounter the same error as the one in your screenshot? Did you make sure to run both commands in Step 5?

Yes, running hmm install or anything in that matter when it comes to installing dependencies will always error upon reaching jsonpath.

**Comment by NotHyper-474** [comment]
What I find odd here is that it's trying to get branch `master` from jsonpath when it only has a branch called `main` instead, and as a matter of fact, it's supposed to be something like `Installing jsonpath from https://github.com/EliteMasterEric/jsonpath branch: 7a24193717b36393458c15c0435bb7c4470ecdda` which suggests that you have modified hmm.json.

**Comment by Daikicalla** [comment]
> What I find odd here is that it's trying to get branch `master` from jsonpath when it only has a branch called `main`, and as a matter of fact, it's supposed to be something like `Installing jsonpath from https://github.com/EliteMasterEric/jsonpath branch: 7a24193717b36393458c15c0435bb7c4470ecdda` which suggests that you have modified hmm.json.

That's extremely odd. I haven't modified hmm.json in any shape or form; I have opened it to get the link for jsonpath, which has been copied and pasted into my web browser. I'll give removing and reinstalling hmm a try and see if that fixes anything.

**Comment by NotHyper-474** [comment]
> I'll give removing and reinstalling hmm a try and see if that fixes anything.

Reinstalling hmm might not solve it since it only parses what's in the hmm.json file.

> That's extremely odd. I haven't modified hmm.json in any shape or form; I have opened it to get the link for jsonpath, which has been copied and pasted into my web browser. 

> having to use hmm git to apply them appropriately

You may not have modified it through an editor but perhaps when you ran `hmm git` like you said above. Run `git restore hmm.json` (or download the file from the repo and replace the current one with it) and see if the installation works now.

**Comment by Daikicalla** [comment]
> You may not have modified it through an editor but perhaps when you ran `hmm git` like you said above. Run `git restore hmm.json` (or download the file from the repo and replace the current one with it) and see if the installation works now.

I have done this command and took a look. It went through just fine, no issues. I will close this issue as solved; Everybody who's having issues regarding downloading things with hmm, be sure to check hmm.json for any issues. Thank you for your help!
