### ISSUE TITLE
Enhancement: Make FNFC files automatically open the Chart Editor.

### ISSUE THREAD

**Issue by notkaif** [FunkinCrew/Funkin#3873]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

Similarly to how if you open a .fla file or a .psd file it automatically opens Animate or Photoshop and the file, I think FNFC or FNFS files should do the same with the Chart Editor and the Stage Editor. 
This makes it easier for when you are testing a custom song and you need to make adjustments to the character or stage without having to go through the entire menu. 

Or you guys can just add a refresh all files button which automatically changes or updates stuff without having to reboot the game.

**Comment by AbnormalPoof** [comment]
> Or you guys can just add a refresh all files button which automatically changes or updates stuff without having to reboot the game.

F5:

**Comment by notkaif** [comment]
WHAT

**Comment by KoloInDaCrib** [comment]
> > Or you guys can just add a refresh all files button which automatically changes or updates stuff without having to reboot the game.
> 
> F5:

I think at this point having a button in the debug menu that redirects you to the modding docs (similar to how the merch button in the main menu works) would be quite useful 

Back to the suggestion though I think it'd be quite neat!
