### ISSUE TITLE
Bug Report: Girlfriend... Isn't wearing pants...

### ISSUE THREAD

**Issue by Beelijah** [FunkinCrew/Funkin#3877]
### Issue Checklist

- [X] I have properly named my issue
- [x] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.0

### Description (include any images, videos, errors, or crash logs)

I was playing a song, and turned on practice mode to get all misses as a joke. Then the loss results screen comes on...
So apparently, Girlfriend forgot pants...

![gfforgotpants](https://github.com/user-attachments/assets/e43863b8-0579-49db-8772-873d8feec005)

Weirdest bug report I've made, but I had to put it out there.

### Steps to Reproduce

1. Get the 'L' rank in the results screen.
2. Use your eyeballs.

**Comment by Keoiki** [comment]
What?

**Comment by CobaltBar** [comment]
Bug Report: The Sky is Blue

**Comment by Beelijah** [comment]
aight nvm

**Comment by Beelijah** [comment]
CobaltBar that wasn't needed

**Comment by CrusherNotDrip** [comment]
You're **complaining** about girlfriend not having pants???

**Comment by Beelijah** [comment]
yo what???????????

**Comment by Beelijah** [comment]
WAIT THIS IS ACTUALLY CANNON HOW DID I NOT KNOW THIS AFTER 3 YEARS

**Comment by SantiagoCalebe** [comment]
> WAIT THIS IS ACTUALLY CANNON HOW DID I NOT KNOW THIS AFTER 3 YEARS

This is part of the sex update.

**Comment by anysad** [comment]
<img width="1280" height="665" alt="Image" src="https://github.com/user-attachments/assets/78471cc9-031d-40ac-ba54-5f3a84a6c681" />

**Comment by Lasercar** [comment]
GirlFreak

**Comment by SantiagoCalebe** [comment]
> you like girlfriend not having pants????????????????????????????????????????????????????????????

Yeah, a lot, it fits her

**Comment by requazar** [comment]
> GirlFreak
😭
