### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by ThePRIME557** [FunkinCrew/Funkin#388]
I started playing the game yesterday afternoon and it was running just fine, with just a couple of seconds of lag the entire time. I could play for around 30 minutes this morning until I had to get on some work I had to do. When I loaded back in, the loading screen would get stuck in between 70 or 60 percent, with other times being at different percentages. I have refreshed the page, restarted my computer, turned on and off my computer multiples times but it doesn't fix the issue.

**Comment by devin503** [comment]
try clearing your browser's cookies. in chrome, you can type "clear cache" into the address bar (see image below)
![image](https://user-images.githubusercontent.com/41199354/107442020-495ffa00-6b04-11eb-89e0-521d3d7b554b.png)
which will bring up the prompt below.
![image](https://user-images.githubusercontent.com/41199354/107442106-701e3080-6b04-11eb-8ab1-0bdd5691cb36.png)
by default, all three options here will be checked. uncheck the first and third, and optionally change the time period to all time.
NOTE: you will be signed out of all websites and have to sign in again. additionally, if you have a google account signed in, your cookies there will be cleared unless you sign out first.
