### ISSUE TITLE
Bug Report: fnf is loading slowly

### ISSUE THREAD

**Issue by megalives717** [FunkinCrew/Funkin#3883]
### Issue Checklist

- [ ] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Web/HTML5)

### Browser

Other (Specify in Description field)

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

![0 5 3](https://github.com/user-attachments/assets/bf472900-2da9-4b7a-9086-9b60e5294076)
very slow

**Comment by moxie-coder** [comment]
probably an issue with your WiFi

**Comment by moxie-coder** [comment]
it could be an issue with your browser if you didn’t enable hardware acceleration

**Comment by megalives717** [comment]
this problem never fixed
