### ISSUE TITLE
Enhancement: BPM change event

### ISSUE THREAD

**Issue by amyspark-ng** [FunkinCrew/Funkin#3889]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

Why is there not an event to signify bpm changes, i think they're only on metadata but i don't see anything for monster in the chart editor

**Comment by Average-FNF-Modder** [comment]
They are currently found manually inside a charts .json (check Monsters .json to see this, it's at the start), though some artwork in the files suggests plans to add an event.
I however have already suggested this in #2911

**Comment by Hundrec** [comment]
It's quite strange that there is BPM change functionality and an event icon, but still no basic BPM change event with at least one field.

**Comment by Average-FNF-Modder** [comment]
> It's quite strange that there is BPM change functionality and an event icon, but still no basic BPM change event with at least one field.

For real. I've heard Eric say it's because BPM changes mess up the chart editor often and are very buggy, plus maybe they are planning to implement gradual BPM shifts before they make it an event.

**Comment by amyspark-ng** [comment]
i'll close then

> > It's quite strange that there is BPM change functionality and an event icon, but still no basic BPM change event with at least one field.
> 
> For real. I've heard Eric say it's because BPM changes mess up the chart editor often and are very buggy, plus maybe they are planning to implement gradual BPM shifts before they make it an event.

It is VERY hard to do, however i don't think it's that buggy in the chart editor, at least on monster's, they do have a way to calculate steps properly and it seems to work out fine
