### ISSUE TITLE
Bug Report: Strumlines are not centered

### ISSUE THREAD

**Issue by Johferson** [FunkinCrew/Funkin#3892]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.1.0-0.5.3

### Description (include any images, videos, errors, or crash logs)

self explanatory. also applies to the Newgrounds and Itch-HTML5 builds

![Screenshot (3)](https://github.com/user-attachments/assets/e2ea3fde-fa42-4195-9b98-ee6db2819352)

**Comment by KoloInDaCrib** [comment]
If I recall correctly this is intentional

**Comment by charlesisfeline** [comment]
not a bug

**Comment by EliteMasterEric** [comment]
not a bug
