### ISSUE TITLE
Enhancement: Background Dim Option

### ISSUE THREAD

**Issue by JordanRadar** [FunkinCrew/Funkin#3898]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What:
A setting to dim the background.
### Why:
It can be hard to distinguish the notes from the background at times (notable example that comes to mind being "'blazin" (Song 4 of Weekend 1). I believe this would be a good feature for accessibility and clarity.

### Implementation:
The setting would use a percentage value (possibly in increments of 5 or 10 for simplicity?) that could be adjusted in the options screen. 
Given that the pause menu uses a transparent background, I imagine it could be implemented in a similar way, instead being layered in between the notes/hit window and the background graphics rather than on top of everything on screen.

### Challenges:
I'm not sure how the engine handles objects with transparency or fading on the fly (save for the notes), but black screen graphics (1x1 pixel tiled across the whole screen to support different resolutions?) could be prepared in advance with varying levels of transparency to be swapped in based on the setting. Just so the engine doesn't have to do *all* the work. Although, this may be an awful idea, I'm just throwing it out there. There's probably a few ways in which this type of feature could be implemented well without sacrificing performance.

**Comment by Hundrec** [comment]
Is https://github.com/FunkinCrew/Funkin/pull/2949 what you have in mind?

**Comment by JordanRadar** [comment]
> Is #2949 what you have in mind?

Ah. Oops. Guess I didn't check the pull requests. That's my bad.

That looks like it would work fairly well. My only concern would be that it doesn't dim the "note highway" for the opponent, which could be useful for seeing upcoming patterns, but it does seem like it would still be beneficial. It's not quite what I had in mind, but it is functionally similar enough to not make a significant distinction.

My apologies for not doing my due diligence and searching harder. I'll be sure to check the pull requests as well in the future.

Should I close this then? At least to not clutter up the tracker with requests for similar features?

**Comment by Hundrec** [comment]
Don't worry about it! 
It can be hard to locate some issues and PRs based on their names among hundreds of entries.
As long as you explain your issues and suggestions clearly, other users can help you find any similar issues!

**Comment by JordanRadar** [comment]
> Don't worry about it! It can be hard to locate some issues and PRs based on their names among hundreds of entries. As long as you explain your issues and suggestions clearly, other users can help you find any similar issues!

Yeah, I did sift through searching with "background" and "dim" but I didn't think to check to see if it was something already in development. Oops! Mental lapse on my part.

> You should close this issue, but don't be afraid to open up new ones in the future.

Okay, I'll close it. Thanks again!
