### ISSUE TITLE
week 2 crash

### ISSUE THREAD

**Issue by jmint33** [FunkinCrew/Funkin#39]
I was trying to beat dad and took a break but when I came back and it said I had unlocked week 2 and when I hit tried to play week 2 it came up with a crash screen
![Screenshot 2020-12-07 at 3 09 26 AM](https://user-images.githubusercontent.com/75610520/101332652-2f234a80-383b-11eb-9c2c-4f118eb27550.png)

**Comment by Gaturrito100** [comment]
Could you be a little more specific? Like what where you doing before leaving?

**Comment by Loretoes** [comment]
I had the same issue for this too, you probably have too little storage for it to load. Try deleting some junk from your computer, that should fix the problem.
