### ISSUE TITLE
Crash Report: Return to Chart Editor crash (not a duplicate as far as I'm aware)

### ISSUE THREAD

**Issue by KadePleaseHelpMe** [FunkinCrew/Funkin#3908]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

v0.5.1 (develop : e66290c) PROTOTYPE

### Description

I'm inconsistently crashing whenever returning to the chart editor after playtesting. It doesn't matter whether I press 7 or get there via the pause menu, it just crashes and spits this at me
![Screenshot 2024-12-01 210351](https://github.com/user-attachments/assets/226df2f5-f505-4073-b90b-b0b4de6cde49)

### Steps to Reproduce

1. Open game
2. Load any chart (I promise it'll work on any of them)
3. Playtest
4. Go back to chart editor
5. It might crash

### Crash logs

[crash-2024-12-01-21-03-20.log](https://github.com/user-attachments/files/17971622/crash-2024-12-01-21-03-20.log)

**Comment by Hundrec** [comment]
You're on an older version of the game before this bug was fixed.
Please make sure you verify that the issue is present on the newest version (0.5.3) before reporting issues.
Refer to https://github.com/FunkinCrew/Funkin/issues/2579 for the original bug report

**Comment by Hundrec** [comment]
Actually, scratch that! This isn't the same issue as the closed one, sorry.
This is a unique issue that I haven't seen before either.

Have you checked that this also occurs on an unmodified copy of 0.5.3? This might be happening due to changes to the game's code.

**Comment by KadePleaseHelpMe** [comment]
yes I'll try it on the latest version and let you know if it persists

**Comment by Hundrec** [comment]
The latest version is 0.5.3, which can be downloaded from itch.io.
You're using the GitHub download, which is usually behind the latest version.

**Comment by KadePleaseHelpMe** [comment]
oh ok thanks

**Comment by amyspark-ng** [comment]
close if fixed plase
