### ISSUE TITLE
Enhancement: 0.6.0 Release Date

### ISSUE THREAD

**Issue by megalives717** [FunkinCrew/Funkin#3909]
### Issue Checklist

- [ ] I have properly named my enhancement
- [ ] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

PLS UPDATE

**Comment by AbnormalPoof** [comment]
0.6.0 will release on “when it’s finished”.

**Comment by MAZ12211** [comment]
???

**Comment by Hundrec** [comment]
Please create GitHub discussions or post to other Funkin' related websites.
GitHub Issues is not the right place to discuss release dates (see https://github.com/FunkinCrew/Funkin/issues/3904)

**Comment by charlesisfeline** [comment]
> PLS UPDATE

the update will drop when it drops, just let em take their time

**Comment by EliteMasterEric** [comment]
The real v0.6.0 was the friends we made along the way.

**Comment by Hundrec** [comment]
So true Eric
