### ISSUE TITLE
Bug Report: Event values don't save when switching to another event

### ISSUE THREAD

**Issue by MAZ12211** [FunkinCrew/Funkin#3911]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

Let's say you placed two events in the chart editor called Focus Camera and Zoom Camera
You placed the former event with custom values you want like targeting the opponent with custom positions with custom duration.
You placed the zoom camera event. Now if you go back and click on Focus Camera event again, the custom values get reset to their default values.
This is annoying especially if you want to tweak the values a bit after playtesting.
This applies to all events too and not just Focus Camera.

https://github.com/user-attachments/assets/930da03f-0c34-47e4-a3fe-c96f18cb6c70

### Steps to Reproduce

1. Place two events with custom values in the chart editor.
2. Once done, click on the event you placed before the last one.

**Comment by Hundrec** [comment]
This was reported in https://github.com/FunkinCrew/Funkin/issues/2957

Long standing issue that should be addressed as high priority once Eric gets back to working on the chart editor.
