### ISSUE TITLE
Enhancement: Reset Score Option

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#3916]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

I suggest having an option to reset your accuracy and score for either a single difficulty on a song, or the entire track, maybe with the player's bound retry key, so by default, "r".

While this is just a nice option to have if you wanna have a clean slate, it's especially helpful if you say, messed with/changed a song's chart, played the song, got a higher score than normally possible, reverted it back to normal on a later version, and now have no way to really get legitimate scores anymore (I wouldn't know anything about this :3). If you are actively making you *own* chart and want to get scores from it once you finalize it, this will also be useful.

**Comment by EliteMasterEric** [comment]
I don't think this is necessary considering the chart editor already disables high scores.

**Comment by Average-FNF-Modder** [comment]
> I don't think this is necessary considering the chart editor already disables high scores.

GODDAMMIT MY HIGH ERECT SCORE IS GOING TO BE BUGGED FOREVER *FUCK*. 😭😭😭 Maann....

(To be clear, I meant if you had already implemented the song into freeplay and you were playing it outside of chart editor, and then made changes.)
