### ISSUE TITLE
Bug Report: shaders (adjustColor shader) on texture atlases causing weird outlines

### ISSUE THREAD

**Issue by 7oltan** [FunkinCrew/Funkin#3917]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

on the week 3 pico mix cutscene it uses a texture atlas for pico(s) and with that it uses the "adjustColor" shader, i noticed that the outline of an object that has the same color as the object below it, becomes a darker color? (focus on his balls)
![image](https://github.com/user-attachments/assets/e58d9742-5495-405c-b3fe-a2f5937a74e9)
i tried using an adjustColor shader on a texture atlas for a mod and noticed it again (focus on the top of her head)
![image](https://github.com/user-attachments/assets/7204b871-e50f-495e-80aa-267eb3abb665)

### Steps to Reproduce

play any week 3 pico mix song and watch the cutscene

**Comment by ninjamuffin99** [comment]
this will be fixed in the next update, so I will close this! We have it all marked done internally. Thanks anyways!

**Comment by 7oltan** [comment]
> this will be fixed in the next update, so I will close this! We have it all marked done internally. Thanks anyways!

np <33

**Comment by 7oltan** [comment]
oops shouldnt have closed it
or should i idk how this shit works

**Comment by Hundrec** [comment]
I'd keep this open until Cam closes it for sure!

**Comment by ninjamuffin99** [comment]
can have this closed, since its fixed internally and already merged and all dat!

**Comment by 7oltan** [comment]
> can have this closed, since its fixed internally and already merged and all dat!

but whaddabout the people that will report this again not seeing it in the reports? gulp

**Comment by Hundrec** [comment]
That's okay, the community's got that one handled!
