### ISSUE TITLE
Bug Report: mods not loading; polymod seems to be at fault

### ISSUE THREAD

**Issue by KadePleaseHelpMe** [FunkinCrew/Funkin#3922]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

v0.5.3

### Description (include any images, videos, errors, or crash logs)

For whatever reason, none of my mods are loading. I've cross-referenced my mod assets with the documentation several times and personally found no issue with my assets. Is there some extra step that I'm missing to load the mod?

Here's my directory just in case _that's_ the problem
![image](https://github.com/user-attachments/assets/49f430cd-467b-4c2e-b8c0-6b0c548dde54)

**Comment by Keoiki** [comment]
The file `_polymod_metadata.json` should be named `_polymod_meta.json`

**Comment by KadePleaseHelpMe** [comment]
perfect!
tysm
