### ISSUE TITLE
Bug Report: Chart Editor Crashing

### ISSUE THREAD

**Issue by KadePleaseHelpMe** [FunkinCrew/Funkin#3925]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

Whenever I open my mod song (with Darnell-Payable as the player), this message shows up before a crash
![image](https://github.com/user-attachments/assets/dc49b9ff-5c77-44ff-9f3a-a43457fd061d)
Note that this _doesn't_ happen when I load the song from .fnfc

### Steps to Reproduce

1. Open Chart Editor from the ~ menu
2. Open a mod-inserted chart from this dinky little menu
![image](https://github.com/user-attachments/assets/8ed7c9be-3b63-442a-bf4c-585c7e1f4907)
4. Die

**Comment by KadePleaseHelpMe** [comment]
> Potential duplicates:
> 
> * [[Bug Report: Animation Editor Crashing #3924](https://github.com/FunkinCrew/Funkin/issues/3924)] Bug Report: Animation Editor Crashing (86.67%)

Not even close, buddy. A) that's my bug report, B) that's not even the same editor

**Comment by Hundrec** [comment]
Does your song have a Voices-bf.ogg file?
If not, can you add one and try again?

**Comment by KadePleaseHelpMe** [comment]
> Does your song have a Voices-bf.ogg file? If not, can you add one and try again? Otherwise, can you rename Voices-darnell to Voices-bf?

I would be fine with doing that, but that wouldn't explain how the playable stuff gets added
Like it's only when I click it from Create From Song. Otherwise, if I load it from the fnfc, it's fine

**Comment by Hundrec** [comment]
The Chart Editor currently struggles with handling difficulties, variations, and playable characters. 
The Create From Song section often breaks under some circumstances, so you should opt in for a workaround for now.

**Comment by KadePleaseHelpMe** [comment]
aight will do
I'll always save to fnfc 👍
