### ISSUE TITLE
Bug Report: Discord RPC not showing correctly?

### ISSUE THREAD

**Issue by JamJarIsDumb** [FunkinCrew/Funkin#3929]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

I noticed others playing the game had their status show the album art and icons for the current song they were playing, however when I play the game it just shows this. I couldn't find anyone else with this issue. I'm using the official V slice build from github and I do not have any mods installed. I also saw that in the source code there is a folder called discord so I assume this is supposed to be fully implemented?

![image](https://github.com/user-attachments/assets/e5c6aea9-888c-4e18-a19c-5ed14fb652ce)

### Steps to Reproduce

1. Open the game
2. Check discord status

I tried removing the game from my registered games and then re-adding it but it did not seem to do anything, might be worth trying though to see if that somehow breaks it

**Comment by NotHyper-474** [comment]
Those builds from GitHub release are kinda outdated. Try 0.5.3 from the itch.io.

Also these builds have the `GITHUB_BUILD` define which in turn enable the `FEATURE_DEBUG_FUNCTIONS` which disables Discord RPC.
https://github.com/FunkinCrew/Funkin/blob/be08bbec58b96620748b60f9010b354c847a3ef1/project.hxp#L484

**Comment by JamJarIsDumb** [comment]
> Those builds from GitHub release are kinda outdated. Try 0.5.3 from itch.io.

This totally worked! I had no idea there was a newer version on itch, my bad! Closing issue, thanks for the help!
