### ISSUE TITLE
Enhancement: Dad Battle instead of DadBattle

### ISSUE THREAD

**Issue by TechnikTil** [FunkinCrew/Funkin#3930]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

its called Dad Battle on the music platforms, so why the inconsistency?

**Comment by TechnikTil** [comment]
![image](https://github.com/user-attachments/assets/8a35b1b7-ab93-4b29-887e-dd92f354b336)

**Comment by CrusherNotDrip** [comment]
![394965379-8a35b1b7-ab93-4b29-887e-dd92f354b336](https://github.com/user-attachments/assets/47122249-b55f-4b4a-b910-5178ccc512b5)

**Comment by trayfellow** [comment]
Recent spotify releases uncapitalize the B in Dadbattle now though....

**Comment by Hundrec** [comment]
> Recent spotify releases uncapitalize the B in Dadbattle now though....

literally unplayable.
