### ISSUE TITLE
Bug Report: Unable to add Sprites to appear under playerStrum underlay notes

### ISSUE THREAD

**Issue by Starexify** [FunkinCrew/Funkin#3933]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.x

### Description (include any images, videos, errors, or crash logs)

I try to make a custom Sprites to have the zIndex under the notes of the playerStrum underlay, for example if I try to make a sprite when a note is hit:
```haxe
override function onNoteHit(event:HitNoteScriptEvent) {
    var sprite = new FunkinSprite(0, 0, "img");
    sprite .zIndex = 900;
    sprite .cameras = [state.camHUD];
    state.add(sprite );
 }
```
`state = PlayState.instance;` in this simple case

The notes appear under the sprite for some reason, but normally the notes should be over the sprite (doesn't matter what zIndex I give, result still same even if i usethe zIndex of the strumline or one strumline note)
Edit: The only idea I could come up with is to render the sprite beforehand onSongLoaded, but the approach is not that *optimal* imo
Or call the method sort but idk how optimal is this
`state.sort(SortUtil.byZIndex, FlxSort.ASCENDING);`

### Steps to Reproduce

1. Create a polymod with the code snippet above (with an actual image name)
2. Notes are shown under the Sprite even tho zIndex should render them above the Sprite.

**Comment by Keoiki** [comment]
Below the line which adds the sprite, put `state.refresh();`, it does what your sort example does and it's exactly what you're supposed to do. The only time zIndex works is when you call the refresh function, otherwise it's pointless.

**Comment by Starexify** [comment]
> Below the line which adds the sprite, put `state.refresh();`, it does what your sort example does and it's exactly what you're supposed to do. The only time zIndex works is when you call the refresh function, otherwise it's pointless.

Oh so it's the same literally but without having to import stuff, nice thanks. but still why isn't it called refreshZIndex/reorderZIndex/rerenderZIndex or smth like that so it's more clear when trying to use the method ;-;
