### ISSUE TITLE
Bug Report: Werid Weekend 1 bug?

### ISSUE THREAD

**Issue by thomasT1P** [FunkinCrew/Funkin#3937]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

Opera

### Version

v0.5.2

### Description (include any images, videos, errors, or crash logs)

i just restarted the song because i missed and this showed up
![Screenshot 2024-12-15 125850](https://github.com/user-attachments/assets/027ee7c4-ad55-473d-ab04-84e3e8611886)
![Screenshot 2024-12-15 125855](https://github.com/user-attachments/assets/d9d9c42e-e2f4-4b5d-82b0-7c0e0081bb76)

### Steps to Reproduce

1. open the game
2. go to "Story Mode"
3. go down to "Weekend 1" (on Hard)
4. play week, skip the cutscene
5. pause and restart song

**Comment by Hundrec** [comment]
This was reported in https://github.com/FunkinCrew/Funkin/issues/3499

Please close this issue and refer to the discussion in that thread for more information!
