### ISSUE TITLE
What file keeps saves?

### ISSUE THREAD

**Issue by BojayB** [FunkinCrew/Funkin#395]
I'm just asking because deleting the entire Funkin folder obviously erases everything so I was wondering what file keeps the saves so I could put it somewhere, delete the folder, redownload the update, and replace the file to keep all of my saves.

**Comment by ninjamuffin99** [comment]
all the saves are OUTSIDE of the main folder, which should mean you can delete the folder and redownload the game and keep your scores and all that.

The file should be in your AppData/Roaming/ninjamuffin99/Funkin folder on your computer if you're on Windows

**Comment by BojayB** [comment]
oh wow, I thought all of my saves were removed but I suppose I just didn't realise. My bad.
I'm using Linux though. Do you know where the saves are located on Linux or is it somewhere you wouldn't be aware of.
