### ISSUE TITLE
Bug Report: skipCountdown doens't work at all

### ISSUE THREAD

**Issue by Starexify** [FunkinCrew/Funkin#3954]
### Issue Checklist

- [x] I have properly named my issue
- [x] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Newgrounds (Web/HTML5)

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

I try create a new song in FNF and I want to skip the countdown when the song is loaded and just start the song, I tried using both events `onSongLoaded` and `onCountdownStart` and called `Countdown.skipCountdown();` but no use, it still plays the Countdown for some reason (Yes other classes work, only the skipCountdown doesnt for some reason)

### Steps to Reproduce

1. Create a ScriptedSong
2. Try `Countdown.skipCountdown();` `onSongLoaded` and/or `onCountdownStart` 
3. Doesn't work

**Comment by AbnormalPoof** [comment]
It does work, but you have to put it in a FlxTimer for some reason:
```haxe
override function onCountdownStart(event) {
  super.onCountdownStart(event);
  new FlxTimer().start(0.0001, function(tmr:FlxTimer) {
     Countdown.skipCountdown();
  });
}
```

**Comment by lemz1** [comment]
it might not be the best solution, but you could do something like this:

```haxe
override function onCountdownStart(event) {
  super.onCountdownStart(event);
  event.eventCanceled = true;
  PlayState.instance.isInCountdown = true;
  Conductor.instance.update(0);
}
```

by doing it like this you dont have to use a timer, which is better in my opinion

**Comment by Starexify** [comment]
Thanks, it seems to work
