### ISSUE TITLE
Bug Report: Cannot open include file: 'pixman.h': No such file or directory

### ISSUE THREAD

**Issue by imguest24897-alt** [FunkinCrew/Funkin#3957]
### Issue Checklist

- [x] I have properly named my issue
- [x] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Compiled from GitHub Source Code

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

soooooooo........... i was lately at night trying to build fnf and and then i got this error saying "No such file or directory", i have cairo installed and it still does that ._.

something like:
Error: cairo-base85-stream.c
C:\Users\Guest4242\funkin lets gooooooo\.haxelib\lime\git\project\lib\cairo\src\cairoint.h(71): fatal error C1083: Cannot open include file: 'pixman.h': No such file or directory

### Steps to Reproduce

1. try to compile game

**Comment by sphis-Sinco** [comment]
run `hmm install` before you compile.

**Comment by imguest24897-alt** [comment]
i realised it was just a windows issue. i tried it on linux and it worked fine.

**Comment by sphis-Sinco** [comment]
> i realised it was just a windows issue. i tried it on linux and it worked fine.

uh, ok
