### ISSUE TITLE
Bug Report: Compile error.

### ISSUE THREAD

**Issue by Gotchfutchian** [FunkinCrew/Funkin#397]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
N/A
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
N/A
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Linux, Compilation error.
## What version of the game are you using? Look in the bottom left corner of the main menu.
Whatever was the master branch on 02/10/2021
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Compile using the guide on the readme, and run as root (using doas or sudo.)
## Please describe your issue. Provide extensive detail and images if possible.
1. compile attempt
```
gotchfutchian@pop-os:~/Downloads/Funkin-master$ doas lime test linux -debug
Password: 
/usr/share/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:201: characters 31-37 : Warning : This typedef is deprecated in favor of sys.thread.Thread
/usr/share/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:72: characters 14-20 : Warning : This typedef is deprecated in favor of sys.thread.Thread
/usr/share/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:77: characters 13-19 : Warning : Usage of this typedef is deprecated
/usr/share/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:183: characters 31-37 : Warning : Usage of this typedef is deprecated
/usr/share/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:174: characters 32-38 : Warning : Usage of this typedef is deprecated
/usr/share/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:96: characters 32-38 : Warning : Usage of this typedef is deprecated
/usr/share/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
/usr/share/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/NGio.hx:46: characters 17-53 : Warning : Use currentVersion
Creating /home/gotchfutchian/Downloads/Funkin-master/export/debug/linux/obj/obj/linux64-debug/__pch/haxe/hxcpp.h.gch...

Compiling group: haxe
g++ -Iinclude -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -m64 -DHXCPP_M64 -I/usr/share/haxe/lib/hxcpp/4,2,1/include ... tags=[haxe,static]
```
files and lines later...
```
XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  84
  Current serial number in output stream:  85

```
cooool

This seems to be a consistent issue, even after restarting and other small attempts.

I will gladly provide more info if need be.

**Comment by devin503** [comment]
using "doas" is not required to compile on linux. just run "lime test linux -debug" as yourself.

**Comment by Gotchfutchian** [comment]
> using "doas" is not required to compile on linux. just run "lime test linux -debug" as yourself.

Doas is just a sudo alternative, dosent matter because when I run it under doas, sudo, or none, i get the same result.

**Comment by devin503** [comment]
hm. are you using a Wayland display server or an X display server? if you're using Wayland, try switching to an X based one, such as XFCE.

**Comment by Gotchfutchian** [comment]
> hm. are you using a Wayland display server or an X display server? if you're using Wayland, try switching to an X based one, such as XFCE.

I use Budgie/MATE/Gnome 2. I'll see if I can grab XDE and try.

**Comment by devin503** [comment]
> > hm. are you using a Wayland display server or an X display server? if you're using Wayland, try switching to an X based one, such as XFCE.
> 
> I use Budgie/MATE/Gnome 2. I'll see if I can grab XDE and try.

let me know how that goes

**Comment by Gotchfutchian** [comment]
Error remains the same, is it because I'm using debian?

**Comment by devin503** [comment]
debian shouldn't have any issues with compiling a build for the game. i can
try to compile what you have if you want, just create a fork with your code.
