### ISSUE TITLE
No sound (Mostly) when opened, fresh download

### ISSUE THREAD

**Issue by JPysus** [FunkinCrew/Funkin#399]
https://www.youtube.com/watch?v=mAWLvV1ND7k

Version 4

Windows 10 64 bit

**Comment by Incinefield** [comment]
I had an issue pretty similar to this one, make sure the program's audio isn't being routed to something else (such as if you have anything like adobe sound capture, etc.), try tinkering with your sound settings and that should do it.

**Comment by JPysus** [comment]
I don't think this is the case, but I could be wrong. 
I restarted the pc, turned off all startup programs, made sure sound settings are at default, and not attached to a speaker and bluetooth is turned off. 

There is still no music on most part of the game except the last week songs. When missing a note, the whole sound on the game turns off and slowly fades in.

**Comment by JPysus** [comment]
I just found out thateven the Ludum Dare 47 version doesn't have audio for me. By any chance tht this game needs something to be installed first before playing? 

Or its because of windows 10 1909 version.

**Comment by Incinefield** [comment]
I have genuinely no clue what the issue is, try reinstalling the sound drivers on your PC maybe?? If not, I'd wait for another update and see if it gets fixed
