### ISSUE TITLE
Score displayed in menu is off by 2 points from Newgrounds score

### ISSUE THREAD

**Issue by Herschel** [FunkinCrew/Funkin#4]
The score displayed by menu seems to be 2 points less from the score displayed by Newgrounds. Possibly caused by the "counting up" effect stopping too soon:

![image](https://user-images.githubusercontent.com/36278/98437028-1553e380-2094-11eb-854e-1d009401513a.png)

![image](https://user-images.githubusercontent.com/36278/98437040-200e7880-2094-11eb-8ed3-044fd131a2c3.png)

**Comment by ninjamuffin99** [comment]
HMMMMMMMMM good catch!

**Comment by ninjamuffin99** [comment]
Update on Friday with the fix :)
