### ISSUE TITLE
Freeplay song doesn't stop

### ISSUE THREAD

**Issue by Gaturrito100** [FunkinCrew/Funkin#40]
v0.2.3 Added a song visualizer before choosing a song in freeplay, however the song doesn't stop after leaving. 
Here's a video regarding the issue:
https://youtu.be/GB8lK7pwsfA
(Using youtube link because Github doesn't support mp4 formats)

**Comment by ninjamuffin99** [comment]
this is semi-intentional, like a happy accident, so imma close dis issue but thanks anyways hehe
