### ISSUE TITLE
Bug Report: Unable to compile after multiple attempts

### ISSUE THREAD

**Issue by Nathan-R-Og** [FunkinCrew/Funkin#403]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Niether.
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
N/A
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x64.
## What version of the game are you using? Look in the bottom left corner of the main menu.
[0.2.7]. Formatting might be different on the main menu, don't know, haven't seen past the command prompt.
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Start the compilation to html5/windows.
## Please describe your issue. Provide extensive detail and images if possible.
When compiling, it is very quick, but I notice it is leaving out a lot of key files.
This is what I get after typing lime test windows -debug into the command prompt in the root directory:
```C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:143: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES2RenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:144: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGLRenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:150: characters 6-24 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES3RenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:151: characters 6-25 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGL2RenderContext
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/utils/src/openfl/utils/ByteArray.hx:750: characters 3-30 : openfl.utils.ByteArray should be lime.utils._Bytes.LimeBytes
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:473: characters 80-91 : Type not found : ObjectClass
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:201: characters 31-37 : Warning : This typedef is deprecated in favor of sys.thread.Thread
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:72: characters 14-20 : Warning : This typedef is deprecated in favor of sys.thread.Thread
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:77: characters 13-19 : Warning : Usage of this typedef is deprecated
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:183: characters 31-37 : Warning : Usage of this typedef is deprecated
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:174: characters 32-38 : Warning : Usage of this typedef is deprecated
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,3/lib/Source/io/newgrounds/utils/AsyncHttp.hx:96: characters 32-38 : Warning : Usage of this typedef is deprecated
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/ColorMatrix.hx:117: characters 12-17 : lime.math.ColorMatrix should be Null<lime.utils.ArrayBufferView>
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/ColorMatrix.hx:117: characters 12-17 : ... For optional function argument 'view'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2313: characters 36-42 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2313: characters 36-42 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2319: characters 36-42 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2319: characters 36-42 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4617: characters 63-64 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4617: characters 63-64 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4631: characters 64-65 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4631: characters 64-65 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4639: characters 66-67 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4639: characters 66-67 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4655: characters 70-71 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4655: characters 70-71 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4669: characters 71-72 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4669: characters 71-72 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4678: characters 73-74 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4678: characters 73-74 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4696: characters 80-81 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4696: characters 80-81 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4712: characters 81-82 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4712: characters 81-82 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4721: characters 83-84 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4721: characters 83-84 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4757: characters 75-76 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4757: characters 75-76 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4767: characters 77-78 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4767: characters 77-78 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/stage3d/src/openfl/display3D/VertexBuffer3D.hx:113: characters 41-45 : openfl.utils.ByteArray should be Null<Int>
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/stage3d/src/openfl/display3D/VertexBuffer3D.hx:113: characters 41-45 : ... For optional function argument 'elements'
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/stage3d/src/openfl/display3D/VertexBuffer3D.hx:113: characters 41-45 : ... For function argument 'data'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/Matrix4.hx:235: characters 12-17 : lime.math.Matrix4 should be Null<lime.utils.ArrayBufferView>
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/Matrix4.hx:235: characters 12-17 : ... For optional function argument 'view'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/media/OpenALAudioContext.hx:573: characters 3-40 : lime.media.openal.ALBuffer should be Int
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/sound/src/openfl/media/Sound.hx:591: characters 37-42 : openfl.utils.ByteArray should be Null<Int>
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/sound/src/openfl/media/Sound.hx:591: characters 37-42 : ... For optional function argument 'elements'
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:852: characters 19-30 : Type not found : ObjectClass
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/text/harfbuzz/HBBlob.hx:47: characters 3-48 : Float should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/text/harfbuzz/HBBlob.hx:56: characters 3-57 : Float should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/bitmapdata/src/openfl/display/BitmapData.hx:1885: characters 45-54 : openfl.utils.ByteArray should be lime.utils.BytePointer
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/bitmapdata/src/openfl/display/BitmapData.hx:1885: characters 45-54 : ... For function argument 'bytePointer'
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:47: characters 19-28 : Type not found : ClassType
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:94: characters 20-29 : Type not found : ClassType
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/assets/src/openfl/utils/AssetLibrary.hx:47: characters 52-57 : openfl.utils.ByteArray should be lime.utils.Bytes
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/assets/src/openfl/utils/AssetLibrary.hx:47: characters 52-57 : ... For function argument 'bytes'
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/assets/src/openfl/utils/AssetLibrary.hx:293: characters 38-43 : openfl.utils.ByteArray should be lime.utils.Bytes
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/assets/src/openfl/utils/AssetLibrary.hx:293: characters 38-43 : ... For function argument 'bytes'
```
This is what the export > debug > windows > bin folder looks like:
![image](https://user-images.githubusercontent.com/46973173/107712566-40e7fa80-6c8f-11eb-8fb7-7a92bc259795.png)
Practically the same result came when I exported as HTML.
I went back and reinstalled visual studio 2019 with everything required, and even found the git for polymod. Everything else I followed the steps exactly.
A video compiling this game would be helpful, as I came to the same result by using this tutorial and the only other tutorial I could find on gamebanana. And as of writing this, I can't find any videos going over it, so any feedback would be appreciated.

Other note, I found a video that said to compile (at least to linux) you had to remove any mention of APIStuff.hx in TitleState.hx. Don't know the validity of this, but I thought it was something worth mentioning. Also, the gamebanana tutorial for this suggests using a batch script that does the work, I also don't know the validity of this, but it did make a release folder, so take with that what you will.

**Comment by mesalikefortnite** [comment]
Im having an identical issue with identical error message

**Comment by Gotchfutchian** [comment]
> Im having an identical issue with identical error message

Same here, similar compilation errors but im in linux.

**Comment by hdboye** [comment]
It seems that this is happening to alot of people lately. I'm pretty sure this is either a bug on Ninjamuffin's part or on Lime and OpenFL's part.

**Comment by TentaRJ** [comment]
getting these same errors as well when using windows and mac.

also how did you get polymod to work? i couldnt get it working.

**Comment by TentaRJ** [comment]
### I have figured it out!

I'll try to push a readme.md out and fix the main readme.md.

**Comment by Gotchfutchian** [comment]
> ### I have figured it out!
> I'll try to push a readme.md out and fix the main readme.md.

Wonderful! Can't wait to see what I messed up.

**Comment by TentaRJ** [comment]
#450
Hope this helps!

**Comment by Nathan-R-Og** [comment]
> ### I have figured it out!
> I'll try to push a readme.md out and fix the main readme.md.

Seems like there is less errors with Haxe 1.5, however I am still unable to compile.
The error this time is:
```
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/NGio.hx:46: characters 17-53 : Warning : Use currentVersion
Creating C:/Users/Nathaniel Robinson/Downloads/Funkin-master/export/debug/windows/obj/obj/msvc1964-debug-nc/__pch/haxe/hxcpp.pch...
hxcpp.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
Error: Could not create PCH
```
Also, something else to note, for some reason, this current code's zip is corrupted for me. I tried extracting it with WinRAR but I got the same error. I might be getting this error because my folder is not completely up to date, so there is that.

**Comment by MarFeto** [comment]
> > ### I have figured it out!
> > I'll try to push a readme.md out and fix the main readme.md.
> 
> Seems like there is less errors with Haxe 1.5, however I am still unable to compile.
> The error this time is:
> 
> ```
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> source/NGio.hx:46: characters 17-53 : Warning : Use currentVersion
> Creating C:/Users/Nathaniel Robinson/Downloads/Funkin-master/export/debug/windows/obj/obj/msvc1964-debug-nc/__pch/haxe/hxcpp.pch...
> hxcpp.cpp
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
> Error: Could not create PCH
> ```
> 
> Also, something else to note, for some reason, this current code's zip is corrupted for me. I tried extracting it with WinRAR but I got the same error. I might be getting this error because my folder is not completely up to date, so there is that.

it doesn't work for me too and instead it gives me this error: C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/LuaClass.hx:10: characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)
source/PlayState.hx:4: characters 8-16 :     referenced here
source/Replay.hx:100: characters 16-25 :     referenced here
I tried it with HTML5 and Windows and it says the same

**Comment by ACrazyTown** [comment]
> > > ### I have figured it out!
> > > I'll try to push a readme.md out and fix the main readme.md.
> > 
> > 
> > Seems like there is less errors with Haxe 1.5, however I am still unable to compile.
> > The error this time is:
> > ```
> > C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> > C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> > source/NGio.hx:46: characters 17-53 : Warning : Use currentVersion
> > Creating C:/Users/Nathaniel Robinson/Downloads/Funkin-master/export/debug/windows/obj/obj/msvc1964-debug-nc/__pch/haxe/hxcpp.pch...
> > hxcpp.cpp
> > C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
> > Error: Could not create PCH
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, something else to note, for some reason, this current code's zip is corrupted for me. I tried extracting it with WinRAR but I got the same error. I might be getting this error because my folder is not completely up to date, so there is that.
> 
> it doesn't work for me too and instead it gives me this error: C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> source/LuaClass.hx:10: characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)
> source/PlayState.hx:4: characters 8-16 : referenced here
> source/Replay.hx💯 characters 16-25 : referenced here
> I tried it with HTML5 and Windows and it says the same

I smell Kade Engine, you should probably go to the Kade Engine repo, not here.
