### ISSUE TITLE
Bug Report: Hitting 1 of 2 double notes does not break your streak.

### ISSUE THREAD

**Issue by Injourn** [FunkinCrew/Funkin#404]
[Newgrounds][Chrome][0.2.7]

Very easy to repeat bug, just hit one of the notes when playing.

https://user-images.githubusercontent.com/24728334/107719729-c5397e00-6c8d-11eb-97be-0bb937e769e5.mp4

**Comment by AndrewIdot** [comment]
Pretty sure that isn't a bug.

**Comment by Injourn** [comment]
What makes you say that?

**Comment by Bloatatoe** [comment]
> What makes you say that?

pretty sure this is not a bug, go to any level get a combo streak on where you start getting numbers. intentionally don hit any keys/note.( As in just let the note miss on it own without you pressing any key ). Then proceed to keep hitting notes, you will keep the streak but your health will drop when you miss note without pressing any button. Could be an unimplemented feature or its intended im not sure but its not a BUG

**Comment by Injourn** [comment]
K, Didn't know that.
