### ISSUE TITLE
Not supporting a device

### ISSUE THREAD

**Issue by TheStaringFace** [FunkinCrew/Funkin#41]
Friday Night Funkin' does support a samsung chromebook for me, are there any ways yall could help?

**Comment by TheStaringFace** [comment]
Here is an image
![image](https://user-images.githubusercontent.com/75649471/101423140-fe382980-38bd-11eb-8e58-3b96532e6459.jpg)

**Comment by ninjamuffin99** [comment]
Hmmm, I don't have a chromebook or a super low end device like that. But if I were to guess I might think that it just doesn't have enough resources or memory or something like that to even show the page. Probably something I can look into more
