### ISSUE TITLE
Bug Report: Minus and Zero Keys still alter in-game volume in Debug Mode

### ISSUE THREAD

**Issue by Apollyon-Pal** [FunkinCrew/Funkin#414]
OS: Windows (`x86`)

Version: V0.2.7 (though I believe this bug is in every single version of the game)

Steps to reproduce: Start a song in Freeplay, enter Debug Mode, and press either button while in a text field such as for the song name

Issue: Pressing the Minus (-) or Zero (0) Key while in Debug mode will still alter the in-game volume when pressed. While you could argue this technically isn't a bug, it is a massive inconvenience as both of these keys are frequently used when working with custom song creation for the game. Whenever I add a hyphen to the song name I then need to click out of the text field and press Plus (+) to fix the game audio, for example. I suggest that these volume controls are disabled whilst in debug mode to prevent this issue from happening.

![image](https://user-images.githubusercontent.com/79024125/107861226-5416d980-6df9-11eb-8d07-41c78f5cb1f5.png)

**Comment by Salladk** [comment]
i dont think is a bug
