### ISSUE TITLE
Bug Report: ChangeBPM doesn't change the in-game section speed

### ISSUE THREAD

**Issue by mewtek** [FunkinCrew/Funkin#417]
### If you are playing a downloaded version of the game, what operating system are you using?
 Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1) Use the "ChangeBPM" feature in the chart editor/debug menu

## Please describe your issue. Provide extensive detail and images if possible.
When using the ChangeBPM feature in the debug menu while creating a chart, the chart menu's chart speed accurately portrays the set BPM from the change. 

However, when attempting to play with the BPM in-game, the section speed will remain at the BPM set in the "Song" tab instead of the requested BPM. In my case, I changed the BPM from 88 to 115. In the chart editor, it runs fine and has the correct timing, but it becomes unplayable in-game because the section speed cramps up all of the notes.

**Comment by Zeexel** [comment]
Bump

**Comment by Zeexel** [comment]
Closing this so I can give more detail + an example.
