### ISSUE TITLE
Bug Report: I'm playing the game on NewGrounds on my Chromebook and I have to constantly restart the page because the loading screen keeps freezing.

### ISSUE THREAD

**Issue by Leroy678** [FunkinCrew/Funkin#420]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by hdboye** [comment]
Chromebooks aren't very good anyways. If there are no errors in the console when you check devtools then it's probably your chromebook being very weak.
