### ISSUE TITLE
When you spam enter during boot up the game crashes

### ISSUE THREAD

**Issue by Speedrunner-doomguy** [FunkinCrew/Funkin#428]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Im using Windows x86_64
## What version of the game are you using? Look in the bottom left corner of the main menu.
The most recent (2.7.1)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
You first open up the game and spam enter and it insta crashes
## Please describe your issue. Provide extensive detail and images if possible.
Its more nitpicky than some of the other more obvious ones but still a bug so ill share, the issue being that if you spam enter while the game first boots up ( on the haxefixel logo) the game just crashes every time, ironically 2.7 doesnt do this

**Comment by Speedrunner-doomguy** [comment]
for the record I was trying to get the game to open faster to chase after the easter eggs, guess I found one lol

**Comment by actuallyasmartname** [comment]
#577
