### ISSUE TITLE
Bug Report: Random Note Misses in Winter Horrorland

### ISSUE THREAD

**Issue by GlitchCrack** [FunkinCrew/Funkin#432]
In Week 5, "Winter Horrorland" while playing, even if you hit perfectly, sometimes the note plays the miss sound and doesn't count it, and the boyfriend's fail animation doesn't show. I have no idea if that's just for me, but it's a very weird thing, i haven't experienced that in other songs, so i think it;s just for Winter Horrorland. (Version 0.2.7.1)

**Comment by AndrewIdot** [comment]
It seems that v0.2.7.1 has messed up long notes, for whatever reason. I have a slight suspicion that it might be from the long note fix that MTH made. Who knows.
Hopefully ninjamuffin finds this and fixes it...

**Comment by PrincessMtH** [comment]
May or may not be the same issue as #424?

**Comment by NickHam13** [comment]
> May or may not be the same issue as #424?

This is the song where I first noticed the issue. I think it was far more noticeable because it has a lot of sustain notes but it definitely persists throughout the whole game.

**Comment by PrincessMtH** [comment]
Duplicate of #424
