### ISSUE TITLE
Game crashes after HaxeFlixel splash screen

### ISSUE THREAD

**Issue by Bowzerz9001** [FunkinCrew/Funkin#436]
I've noticed that if you spam enter during or after the HaxeFlixel splash screen it will crash

**Comment by JonathanGamesProduction** [comment]
Make sure that you opened game in WINRAR, 7-zip or other archives because when you extract the game, game will not open.

**Comment by ABAABAAAAA** [comment]
The game was extracted using WINRAR, and placed on my secondary drive.

**Comment by ABAABAAAAA** [comment]
and I also checked on my C: drive that is an SSD and it does the same thing

**Comment by JonathanGamesProduction** [comment]
> and I also checked on my C: drive that is an SSD and it does the same thing

Play it just in WINRAR everything gonna be okay if not help redownload the game

**Comment by ABAABAAAAA** [comment]
Just downloaded the game and ran it from WINRAR and tried spamming enter and it did the same thing
