### ISSUE TITLE
Editor hold note offset Issue

### ISSUE THREAD

**Issue by StrPointless** [FunkinCrew/Funkin#437]
when in the freaking editor, when you make a hold note the "hold part" is offset relative to the note itself
![Screenshot (8)](https://user-images.githubusercontent.com/65548634/108001353-347adf00-6fba-11eb-8ece-cf5ff9b03c48.png)
![Screenshot (9)](https://user-images.githubusercontent.com/65548634/108001426-6b50f500-6fba-11eb-9fea-d993efbc1f38.png)
![Screenshot (11)](https://user-images.githubusercontent.com/65548634/108001433-6db34f00-6fba-11eb-98ae-c1f53006adb8.png)
![Screenshot (12)](https://user-images.githubusercontent.com/65548634/108001434-6f7d1280-6fba-11eb-82ec-0afe5b519bc6.png)

**Comment by PrincessMtH** [comment]
Seems about right, what's the issue?
