### ISSUE TITLE
Bug Report: I updated the game and it is just saying you're running an older version 0.2.7.1 please update to version 0.2.7.1

### ISSUE THREAD

**Issue by Imimikyu191** [FunkinCrew/Funkin#438]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by hdboye** [comment]
Press the ESC key to skip it. I can't help you any more or explain why it happens because you didn't provide any info.
