### ISSUE TITLE
Week 2, Spookez and South crash

### ISSUE THREAD

**Issue by Loretoes** [FunkinCrew/Funkin#44]
When trying to play Week 2, for me the game seems to crash. Occasionally, week 2 will load, but when I lose and retry, the game then crashes. With free play mode, if I want to play Spookez or South, they have to be the first song I play after loading up the game. Again, when I lose and retry, the game crashes.

**Comment by gedehari** [comment]
Hi, in what platform are you running that causes the crash? thanks

**Comment by Loretoes** [comment]
Newgrounds.

**Comment by gedehari** [comment]
Looks like similar issue with #39 . I'll try to confirm it myself.

**Comment by Loretoes** [comment]
Alright, thanks!
