### ISSUE TITLE
Outaded Current Version

### ISSUE THREAD

**Issue by BojayB** [FunkinCrew/Funkin#451]
(I've seen this bug around before so If its already been dealt with please close as quick as possible)

Playing version 0.2.7.1 of the game locally using Chromium on Manjaro Linux.

I noticed there was a new release so I decided to git clone the repo, add my own APIStuff.hx in /source and run lime test html5.
(I don't use -debug because the console appears randomly for me sometimes and it ruins gameplay, removing -debug gets rid of the console for me completely)

Game boots up normally but says I'm running outdated version 0.2.7.1 please update to 0.2.7.1.

Image of bug:
![image](https://user-images.githubusercontent.com/41974762/108278073-73d73600-7148-11eb-9337-e87d4b75ec81.png)

I'm just going to ignore this for now which is fine but if it appears every time it will slowly become more and more irritating.

Thank you guys for the amazing game! Just trying to help out in as best I can!

**Comment by Salladk-but-no-mo-flaged** [comment]
Game be like:

Download update V0. 2. 7. 1. or we are going to bother you until you download it
Because the update V0. 2. 7. 1. is trash now and the update V0. 2. 7. 1. is the best for now
