### ISSUE TITLE
Bug Report: ok so i was playing week 4 and the song was satin panties during one part in the middle of the song, the game will freeze and go onto the next song high i thought that this was my pc acting up so i passed it on but when i played week 4 for a second time the same thing happened   ( i would like to note that i am playing this on new grounds and on the chrome browser) is

### ISSUE THREAD

**Issue by kookiekatuwu** [FunkinCrew/Funkin#456]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by TentaRJ** [comment]
pleae put your problem in the text, not the title...
