### ISSUE TITLE
Week 4: Boyfriend's and mom's parts swapped (seen in all difficulties)

### ISSUE THREAD

**Issue by xolyne** [FunkinCrew/Funkin#460]
In High, and Milf, some parts are swapped, where the boyfriend is singing moms part, and vice versa.
This is seen in both levels, in all difficulties.
(in advance, i apologize for the low quality of videos, i wasn't too bothered to upload my own gameplay so i took videos off of youtube instead.)
Edit: Oh and yeah, forgot to note that the videos were taken on the version when week 4 was released, but this issue is still in the latest version (0.2.7.1)

https://user-images.githubusercontent.com/79317688/108510557-bb3bfe80-72cf-11eb-985a-c51e78a32c9d.mp4

https://user-images.githubusercontent.com/79317688/108510564-be36ef00-72cf-11eb-959b-432d89dc9271.mp4

**Comment by dinkstr** [comment]
Where's the bug? I'm fairly sure this is intentional. They're just swapping melodies.

**Comment by SilentDashin** [comment]
> Where's the bug? I'm fairly sure this is intentional. They're just swapping melodies.

Listen to the boyfriend's voice and look at the mom's patterns. It may take a couple of listens to see/hear it

**Comment by dinkstr** [comment]
> > Where's the bug? I'm fairly sure this is intentional. They're just swapping melodies.
> 
> Listen to the boyfriend's voice and look at the mom's patterns. It may take a couple of listens to see/hear it
> 
> Edit: I should also mention that the mom had the exact same pattern just before the recorded section, except it was in her voice/tone/ whatever you wanna call it. (I'm not the OP but noticed this as well while playing)

idk if I'm blind and/or deaf but I can't see where the bug is

**Comment by jvc2** [comment]
i hear it too. i think this is a charting error, in both those clips boyfriend's voice is higher pitched than mom's which is probably what led to the confusion.

**Comment by EEYM** [comment]
the reason for this is probably because they thought it's too difficult
