### ISSUE TITLE
I cant open story mode!

### ISSUE THREAD

**Issue by No-Blip** [FunkinCrew/Funkin#461]
When i downloaded the game and open story mode... the screen ecomes black and the game CLOSES, with no reason.

I've already downloaded it 3 times and still the same (already tried to delete the cache from %appdata%)

Pls help :(

**Comment by TentaRJ** [comment]
having this same problem with freeplay menu.
Where did you get the game from? (Open source, itch.io)
What build are you running? (Windows, mac, Linux, HTML5(browser))
