### ISSUE TITLE
Bug Report: even tho i like the game the problem is that everytime i load the game it just gives me black cubes and only on some levels and even the loading screen

### ISSUE THREAD

**Issue by CupheadkidYT** [FunkinCrew/Funkin#462]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by LoafyToast** [comment]
This is not a bug, this is the result of your pc not having enough free cpu to run the game properly thus certain textures become black squares.
