### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by samueldavibritosilva** [FunkinCrew/Funkin#466]
so uhh, the game wont load ?
i have to keep refreshing the page. and even then, it only gets to 60%-72% everytime
fix this please.
i would like to friday

**Comment by Bloatatoe** [comment]
Download the desktop version. It should work. if it doesn't, its your PC/Laptop

**Comment by samueldavibritosilva** [comment]
ok nice

Em sáb., 20 de fev. de 2021 às 06:17, Bloatatoe <notifications@github.com>
escreveu:
