### ISSUE TITLE
Bug Report: Every time i try to download the game. it either deletes it or says couldnt download. how can this be fixed?

### ISSUE THREAD

**Issue by TheCreation51** [FunkinCrew/Funkin#472]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below. i am downloading the game

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
im using edge
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below. 

## What version of the game are you using? Look in the bottom left corner of the main menu.
v5
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
no
## Please describe your issue. Provide extensive detail and images if possible.
Every time i try to download the game. it either deletes it or says couldnt download

**Comment by Bloatatoe** [comment]
could be your anti-virus or firewall blocking it, or even windows security. Im sure the game is safe. Disable those things, download the game make exception for the folder and turn the things back on if you want.
