### ISSUE TITLE
Bug Report: 32-Bit version is broken.

### ISSUE THREAD

**Issue by Terraquatic** [FunkinCrew/Funkin#473]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Terraquatic** [comment]
I downloaded the game from itch.io and i'm using a 32-bit operating system. And i'm using the latest version

**Comment by sadman2347** [comment]
iam 32 the game always do error

**Comment by dinkstr** [comment]
May have been fixed by v.0.2.7.1? The 32 bit exe used to crash for me, but after compiling with the latest commits it seems to work fine.
