### ISSUE TITLE
I downloaded the 32-bit version of the game from itch.io yesterday (Windows 7) and I'm quite surprised that other people running on 32-bits seem to have this issue as well. It boots up fine, but when you see the opening screen (the one where gf bobs her head), the asset for gf is missing, This goes for almost all of the assets being missing in-game. Another issue is the crashes. I can't play the game properly because of the crashes. Funky crashes. The only playable weeks I can play fully without crashing is tutorial, week 4, and week 6. Week 5 is completely unplayable. Week 2 and 3 gives up after 1 song. Week 1 can only play 2 songs before crashing. Freestyle can only play certain songs (by that I mean few) from unplayable weeks. Only song that I can play in freestyle from week 5 is Winter Horrorland (lol). I hope this gets fixed soon, I want to play this game so badly without the crashes qwq

### ISSUE THREAD

**Issue by KrazyMelon** [FunkinCrew/Funkin#480]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by PORTB** [comment]
You're supposed to describe your issue in detail in the description and keep the title as a brief description of the issue. You are also supposed to follow the template that you have left blank in the description

**Comment by CyberXVI** [comment]
Please don't list that shit as the title
