### ISSUE TITLE
Since v0.2.7.1, hold notes started behaving weirdly

### ISSUE THREAD

**Issue by NeypahTit** [FunkinCrew/Funkin#481]
https://user-images.githubusercontent.com/68984014/108789671-645e4f80-7583-11eb-8d28-12072d6792d5.mp4

(Footage from a friend of mine)
Unless I'm wrong, the game sometimes considers that you missed a note despite clearly hitting it when it comes to hold notes, and I don't remember this happening before v0.2.7.1

**Comment by Injourn** [comment]
This may have been addressed by #467

**Comment by NeypahTit** [comment]
Oh whoops my bad, I did try to find anything relating to this before making this issue but I suppose I didn't find that one

If it is indeed addressed already, then this issue can be closed no problem

**Comment by PrincessMtH** [comment]
Yeah, duplicate of #424, fixed by #467

**Comment by NeypahTit** [comment]
Alright, then I'll be closing this one. Glad to hear its been fixed though!
