### ISSUE TITLE
Bug Report: I'm on latest version, but the game tells me to update it even though there's no update yet

### ISSUE THREAD

**Issue by KrazyMelon** [FunkinCrew/Funkin#484]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by ninjamuffin99** [comment]
yeah is a weird dumb bug, def gonna be fixed in next update!
