### ISSUE TITLE
Bug Report: UI Portrait Overlay Bug on Thorns

### ISSUE THREAD

**Issue by AyeTSG** [FunkinCrew/Funkin#489]
### If you are playing a downloaded version of the game, what operating system are you using?
**_Windows (`x86_64`)_**

## What version of the game are you using? Look in the bottom left corner of the main menu.
**_I am using commit 88c26f9._**

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
**_Yes. Play the Thorns track._**

## Please describe your issue. Provide extensive detail and images if possible.
**_My issue is that the layering on the UI portraits does not properly layers as of this commit._**
![Funkin_Ly7j6Dj05b](https://user-images.githubusercontent.com/49595354/109034757-f6567d00-7695-11eb-8abf-1da0955aea11.png)

**Comment by AyeTSG** [comment]
Confirmed to still be an issue as of d92cd63

**Comment by prokube** [comment]
that and the shadow is wrong

**Comment by ActualMandM** [comment]
shadow is correct, it was always meant to be a silhouette of senpai
