### ISSUE TITLE
Spamming the Enter key while the game is starting up crashes the game.

### ISSUE THREAD

**Issue by Superrobin1099** [FunkinCrew/Funkin#491]
This happens on the Itch.io version, I only tested it on the 64-bit version but it might happen on the other versions too. If you spam the enter key for about 3 seconds when the HaxeFlixel logo is on screen, the game will crash. I've tried this multiple times and it always crashes. I used the latest version (v.0.2.7.1)

Update: This also happens on the newgrounds, since when I attempted the bug in the newgrounds version, it froze and I had to refresh the page. This means it occurs on all versions.

**Comment by usgyt** [comment]
lol same but i posted the issue a few days ago but didnt know how to tag it
