### ISSUE TITLE
Bug Report: Pixel ready sounds no longer used

### ISSUE THREAD

**Issue by AyeTSG** [FunkinCrew/Funkin#497]
### If you are playing a downloaded version of the game, what operating system are you using?
**_Windows (`x86_64`)_**

## What version of the game are you using? Look in the bottom left corner of the main menu.
**_I am using commit d92cd63._**

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
**_Yes. Play any week 6 track._**

## Please describe your issue. Provide extensive detail and images if possible.
**_My issue is that the pixel sounds for "3, 2, 1, date!" are no longer used as of the new asset system, and instead "3, 2, 1, go!" is now used._**

**Comment by ActualMandM** [comment]
Can verify this as well.

https://user-images.githubusercontent.com/15317421/109365667-8e936400-7846-11eb-805c-8728763775b7.mp4

**Comment by lolBoi9696** [comment]
Hmm weird must be a bug since it doesn't for me
