### ISSUE TITLE
"Jumps" and quick notes are difficult to hit

### ISSUE THREAD

**Issue by Herschel** [FunkinCrew/Funkin#5]
Notes in quick succession (16th notes and shorter) and jumps (two steps together) are difficult to hit.

For example, this jump in Dadbattle Hard is impossible to hit properly; you will always miss one of the notes. (You can fudge it by pressing the second note some time later for a 'Good').
![image](https://user-images.githubusercontent.com/36278/98437281-d2930b00-2095-11eb-8c60-d67d2de1fa99.png)

These 16th notes are also difficult to hit (you often miss the subsequent notes after pressing the first Left):
![image](https://user-images.githubusercontent.com/36278/98437317-0d953e80-2096-11eb-993e-ea6b7097fffc.png)

[This code](https://github.com/ninjamuffin99/Funkin/blob/a71abb577277ac0a6b950a14c708ad613aa6a8ba/source/PlayState.hx#L1014-L1052) may be the culprit, as it can test several nearby notes against each key, even if that key "hits" another note. For example, if Up, Left, Down are in the possibleNotes list, and the user presses Up, they will score 1 hit for the Up by 2 misses for the Left and Down, even though they successfully hit the up. The misses also freeze the character for a moment, which may cause them to miss further when they actually press Left and Down, even though they are correctly following the pattern.

Some ideas:
 * If a key can successfully hit a note, the input should be consumed by that arrow, and other notes should not consider it.
 * A key should consider the nearest note(s) in the stream first (i.e. the nearest before the current time and the nearest after the current time; sort by `Math.abs(currentTime - noteTime)`?).
 * If a note is hit, any earlier unhit notes could be auto-missed/ignored (because they should have been pressed earlier in time).

**Comment by ninjamuffin99** [comment]
I'll definitely have to do some testing and whatnot to see what feels right for this one, bless up Mike

**Comment by BrandyBuizel** [comment]
definitely looks like the switch case taking priority over note presses when they should all be possible simultaneously. Could make gameplay more fun to keep double hits as long as they work consistently.

bless up Mike
