### ISSUE TITLE
Music unsyncs and acts weird when PAUSING right at the start of the song

### ISSUE THREAD

**Issue by xChillax** [FunkinCrew/Funkin#50]
https://youtu.be/Ur7AYIaerh4

You can even hold the song (by pausing the game long enough) and die instantly.

Pausing the game too quickly also can cause past songs to play instead of the actual song you are supposed to be playing (for example Game over music over the vocals of your current song).

**Comment by gedehari** [comment]
Yep happens to me too. About to report too, actually

**Comment by gedehari** [comment]
Made a pull request! Although I am not sure how to fix the "pause right at start of song". I might be able to fix the latter issue. ty

**Comment by gedehari** [comment]
All done! Now we wait for the owner to merge this PR #48

**Comment by gedehari** [comment]
Just checked, the PR got merged! You should close this issue

**Comment by ninjamuffin99** [comment]
oops ye forgot to close issue
