### ISSUE TITLE
Bug Report: Outdated Up to Date Version and Freeplay Machine Broke

### ISSUE THREAD

**Issue by ItIsIWeeg** [FunkinCrew/Funkin#501]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 64-bit
## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7.1 (compiled from the github source release)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Yes, no matter what I do this always happens.
## Please describe your issue. Provide extensive detail and images if possible.
Whenever the game boots I'm greeted by the auto update screen. Which, wouldn't be an issue if it weren't for the fact this is the most current release of the game: 
![image](https://user-images.githubusercontent.com/79732045/109372146-0af16b80-7876-11eb-82a0-846adfebfd09.png)

This isn't even the only issue I'm facing with the github release, whenever I go to even try the freeplay mode I'm greeted by this:
![image](https://user-images.githubusercontent.com/79732045/109372182-370cec80-7876-11eb-98a5-ff580425b5f3.png)

I've made no modifications to the source either, and I'm not sure if it was an error with the compiling process or not but this hasn't happened with past releases.

**Comment by jbmagination** [comment]
Freeplay mode has been bugged for the past few days. Try replacing NGio.hx with [this file](https://gist.githubusercontent.com/jbmagination/caf9eb6a7ae8b415e8acd02962f851e1/raw/d76486854a7676a0ce16907dfa82bf804b155388/NGio.hx)

**Comment by jbmagination** [comment]
Just did a check and the other part of your bug report is a dupe of #451.

**Comment by ItIsIWeeg** [comment]
Yes thank you!! And I wasn't quite aware someone already reported both of those. Thank you and have a nice day!
