### ISSUE TITLE
Enhancement: Key rebinding

### ISSUE THREAD

**Issue by Shady-Heretic** [FunkinCrew/Funkin#503]
I would really like to rebind my keys as my style for playing rhythm games is pretty unique so it makes it hard for me to play the game with the current static binds.

**Comment by lolBoi9696** [comment]
He wouldn't add this anyway you should be able to edit controls.txt it has all the controls

**Comment by lolBoi9696** [comment]
i mean there might be a options menu not sure ik there is one but its unfinished
