### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Devailey101** [FunkinCrew/Funkin#505]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Itch.io
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Linux installed, playing on chromebook
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I just try and play the game on my chromebook and i get the following screen:
![Screenshot 2021-02-27 at 5 54 50 PM](https://user-images.githubusercontent.com/79771360/109402588-f8823b00-7924-11eb-8d08-554ad23467fa.png)

## Please describe your issue. Provide extensive detail and images if possible.
Every time i try to play the game, regardless what site i try to use, i am unable to actually get the game to load properly and it results in the screenshot i attached above. Could it just be a problem with my device or something else?

**Comment by lolBoi9696** [comment]
This is a duplicate lol
