### ISSUE TITLE
Bug Report: It doesn't load, it is about to finish loading but then a image with a error face appears.

### ISSUE THREAD

**Issue by rolopop** [FunkinCrew/Funkin#506]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by rolopop** [comment]
![Screenshot 2021-02-27 at 9 22 07 PM](https://user-images.githubusercontent.com/79776990/109406854-f1b5f100-7941-11eb-9948-5bfac7d16948.png)

**Comment by lolBoi9696** [comment]
It's a issue with chrome os

**Comment by lolBoi9696** [comment]
If your using that anyway

**Comment by Salladk-but-no-mo-flaged** [comment]
you can play the game in NewGrounds too
