### ISSUE TITLE
Bug Report: Changing song's names or character's in html5 causes a crash

### ISSUE THREAD

**Issue by Tuxsupa** [FunkinCrew/Funkin#508]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Compiled html5
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
Latest repo changes
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Just go to any song in the html5 version open the debug menu with '7' and change the name of the song or a character to something else. The game will crash.
## Please describe your issue. Provide extensive detail and images if possible.
Just go to any song in the html5 version open the debug menu with '7' and change the name of the song or a character to something else. The game will crash. In the windows version this does not happen however. The song's seconds doesn't change when reloading the audio with a different song name like the windows version too.

**Comment by lolBoi9696** [comment]
Yeah that's because it's trying to read files and images and data and things from files it doesn't exist if there where checks for it then it could be fine but it's pretty pointless fixing it
