### ISSUE TITLE
0 key on numpad mutes the game and it is annoying

### ISSUE THREAD

**Issue by randGit0** [FunkinCrew/Funkin#509]
Hello. I use a full keyboard including the numpad, and the way I play is using both WASD and the arrow keys, however during intense moments I accidentally hit the 0 key on the numpad, which completely breaks my flow. NUMLOCK on or off, same effect.

I use the downloaded version, win 10.

No, I am not gonna switch my handstance.

volvo pls fix

**Comment by MarioLuigi124** [comment]
try not to press 0

**Comment by TootNoot** [comment]
try not to press 0

**Comment by TentaRJ** [comment]
try not to press 0

**Comment by lolBoi9696** [comment]
Yeah try not to press 0 because that can't be fixed anyway because that's a default control for haxeflixel and idk if you can actually change i
