### ISSUE TITLE
32 bit version not working well

### ISSUE THREAD

**Issue by Fancy2209** [FunkinCrew/Funkin#51]
So starting by the start

On newgrounds and itch.io on the web version it shows an dead Mac
![image](https://user-images.githubusercontent.com/64917206/101793075-f31b0e80-3af4-11eb-86c7-0d98b4628b3a.png)
![image](https://user-images.githubusercontent.com/64917206/101794224-2d38e000-3af6-11eb-9dc1-c82eddf14faa.png)

And on the downloaded itch.io 32 bit windows version it has these graphical problems:

Characters not existing:
![image](https://user-images.githubusercontent.com/64917206/101793318-2d84ab80-3af5-11eb-9fb5-c401122170db.png)
![image](https://user-images.githubusercontent.com/64917206/101793425-4db46a80-3af5-11eb-8f73-fd180cbbbe97.png)

and the Death screen being just black but you can still use it
![image](https://user-images.githubusercontent.com/64917206/101793487-645ac180-3af5-11eb-9b6b-536f657e2f80.png)

**Comment by Fancy2209** [comment]
weirdly this one seems like the ludum dare version is working rigth
https://ninja-muffin24.itch.io/friday-night-funkin

**Comment by Fancy2209** [comment]
I think this is the same issue as https://github.com/ninjamuffin99/Funkin/issues/20

**Comment by Fancy2209** [comment]
What the hell
the characters show up if I copy the images folder from the prototye to the new version

**Comment by Fancy2209** [comment]
not on the menu 
but the still what the hell

**Comment by Loretoes** [comment]
you probably dont have enough memory or RAM.

**Comment by Fancy2209** [comment]
> you probably dont have enough memory or RAM.

uuhhh, So 2,5 GBs of ram aren't enough?
![image](https://user-images.githubusercontent.com/64917206/102231716-ce9ca900-3edd-11eb-803e-3f59ce829a78.png)
