### ISSUE TITLE
Bug Report: Bugged out Boyfriend

### ISSUE THREAD

**Issue by RealNoobForce** [FunkinCrew/Funkin#510]
![Odd Bug](https://user-images.githubusercontent.com/79800146/109424496-37160500-79ba-11eb-9552-3476bd58fb59.png)

As you see here, the boyfriend is nowhere to be found. However whenever I pressed one the commands only his top half would appear with the respected animation. I believe the idle animation was broken for some reason.

**Comment by lolBoi9696** [comment]
That was Ur computer not the game I think
