### ISSUE TITLE
Bug Report: I made a mod that fixes a lot of bugs.

### ISSUE THREAD

**Issue by dizhydron** [FunkinCrew/Funkin#512]
Why report bugs when you can fix em?

I was inspired to make a bug fix mod when I found the debug menu. That random note in Bopeebo was bugging me for the longest time. I decided to do what I could to fix timing issues and mistakes in the gameplay using the editor and as of today, my first draft is complete! I figured that doing things myself might save yall some time and let you get to new content/other things you want to work on. I also plan on updating the mod and taking care of other non-gameplay-related bugs in the near future. I've got my eye on some minor graphical bugs now that I think I can fix.

This mod includes the following fixes:

Off Beat Notes Corrected: 185

Missing notes added: 47

Extra notes removed: 102

Buggy/Short Hold notes changed: 30

Must hit sections corrected: 12

Missing notes added: 34

Notes added to improve telegraphing: 39

Sections reworked to fit the music better: 181

Sections changed to match other sections: 34

Notes that interfere with each other fixed: 71

Plus a LOT more stuff that I neglected to note because I wasn't taking notes as religiously as I could have.

I'd say feel free to check it out, but it's takng the mods on gamebanana FOREVER to approve it. It's been almost 3 days. If you'd like to give it a look, here's a link to a showcase of it I have on Youtube.

https://www.youtube.com/watch?v=_7WykctHPzM

I also attached the file here if you want to check it out yourself. It's not malware, if you want to be on the safe side, you can also check the gamebanana page for it to be approved.

[Funkin Fix.zip](https://github.com/ninjamuffin99/Funkin/files/6057804/Funkin.Fix.zip)

https://gamebanana.com/gamefiles/15919

I really hope that this is of some help.

Keep on Funkin on!

P.S. My 7 and 4-year-old nieces love the girlfriend. They think she's so pretty. Though that might make someone's day. =)

**Comment by 8bit-coder** [comment]
This seems awesome, tried it out and it does actually fit the songs better!
