### ISSUE TITLE
Performance Report: Frequent crashes

### ISSUE THREAD

**Issue by RichardCarter2021** [FunkinCrew/Funkin#515]
I am using the 32-bit Windows version of the game, v.0.2.7.1. The game starts and works fine, but the game always crashes after completing the first Week 1 song. I haven't played the Tutorial, but it's possible that's a problem too. I tried using free play mode instead, but when playing Dadbattle, Girlfriend and Boyfriend's sprites are just black squares. I tried playing Week 2 songs, but it crashed my game. If it matters, I am using an old computer (made for Windows Vista), but I think the game should be able to work find despite that. It runs smoothly, too. Can't do much of anything else now and hope that it's just a me-issue and not an issue with the game.

**Comment by Lacter0** [comment]
Same happens to me.

**Comment by RichardCarter2021** [comment]
UPDATE: Tried playing again. Tutorial worked fine. Tried starting Week 1 and the game crashed. Restarted and replayed Week 1. Bopeebo worked fine, and Fresh actually played, but GF's sprite was a black square. After the song was over, the game crashed. I tried playing Week 2 again, but it crashed. I tried playing Week 3, and it worked on Pico, but GF's sprite was a black square. After the song ended, the game crashed. I played Week 4, and I actually managed to reach M.I.L.F. (despite the extremely long freezes between songs), but I failed and the game crashed before it does that game over animation. The long freeze transitions happen to everything else as well.

Game is still effectively broken and unplayable, and I know now that it's not a me issue. Hope this gets fixed ASAP.

**Comment by MarioLuigi124** [comment]
have you tried playing on the web

**Comment by RichardCarter2021** [comment]
> have you tried playing on the web

Yes, many times, but the game crashed before it even finished loading (typically crashes at ~50%.)

**Comment by lolBoi9696** [comment]
> > have you tried playing on the web
> 
> Yes, many times, but the game crashed before it even finished loading (typically crashes at ~50%.)

Ur pc bad then

**Comment by 8bit-coder** [comment]
> > Yes, many times, but the game crashed before it even finished loading (typically crashes at ~50%.)
> 
> Ur pc bad then

Yeah, that seems like the issue
