### ISSUE TITLE
Building Problems on Linux

### ISSUE THREAD

**Issue by jumper-cable-morty** [FunkinCrew/Funkin#517]
## What is your question?
I've been trying to compile this for a while now, but I must be missing something in the guide or my haxe is just broken. Everything seems to compile fine, and without warnings as far as I can tell, but the executable is never there. I'm running Endeavor OS, based on Arch Linux, and this is what shows up in the command line when I run `lime test linux -debug`.
[untitled.txt](https://github.com/ninjamuffin99/Funkin/files/6063466/untitled.txt)
Could someone help me out with this please?
Oh and P.S: I would just download it from itch.io, but it seems that it hasn't been updated to 2.7.1 yet.

**Comment by Hendicted** [comment]
[have you followed these instructions before compiling?](https://haxeflixel.com/documentation/install-haxeflixel/) i compiled it on the same distro as yours and it works for me

**Comment by jumper-cable-morty** [comment]
Yeah, I did it a couple times just to be sure too.

**Comment by UwUnyaa** [comment]
The current release of haxe in arch repos is `4.2.1`, which is too new according to the readme. I'm considering trying to build this myself, and using a docker container might be the best idea to be able to use an older version of haxe without making things messy.

**Comment by Hendicted** [comment]
> 
> 
> Yeah. I did it a couple times just to be sure, too.

whats your haxe version? you need 4.1.5 to compile properly

**Comment by jumper-cable-morty** [comment]
I'm using the one in the Arch repos. I downloaded 4.1.5, but I'm not sure how to make it compile specifically with that version.

**Comment by jumper-cable-morty** [comment]
Scratch that, I got it to run correctly using the haxelib executable from the haxe 4.1.5 folder, but it still doesn't compile right.

**Comment by UwUnyaa** [comment]
If you want to do it on your current arch install, try installing an older version from an archive, although you'll likely need to resolve dependencies by hand.

**Comment by jumper-cable-morty** [comment]
I have the archive, but I didn't know you were supposed to install it, and I'm not sure how you're supposed to install it anyways. It just has the haxe and haxelib exectuables. I ran lime from the haxelib that was in the archive but it just did the same thing as the 4.2.1 version did.

**Comment by seangatesgit** [comment]
uninstall current version of haxe and downgrade using package archives.
\# pacman -U https://archive.archlinux.org/packages/h/haxe/haxe-4.1.5-1-x86_64.pkg.tar.zst
worked for me

**Comment by jumper-cable-morty** [comment]
Gave me an error saying it can't find libmbedtls.so eve though I checked that I have it installed. My computer just hates me I guess. `haxe: error while loading shared libraries: libmbedtls.so.12: cannot open shared object file: No such file or directory`

**Comment by seangatesgit** [comment]
then symlink any newer installed version of libmbedtls. also install mbedtls if you haven't.
\# pacman -S mbedtls
\# ln -s /usr/lib/libmbedtls.so.2.25.0 /usr/lib/libmbedtls.so.12
\#ln -s /usr/lib/libmbedx509.so.2.25.0  /usr/lib/libmbedx509.so.0
\#ln -s /usr/lib/libmbedcrypto.so.2.25.0 /usr/lib/libmbedcrypto.so.3
should be all you need. if any of these commands report 'No such file', hunt down the location of any installed 'libmbedtls' and etc. in your system and symlink it to the desired file in the same folder you found it.

**Comment by jumper-cable-morty** [comment]
That did it! Thanks, I really appreciate all the help.
