### ISSUE TITLE
Bug Report: i play on a chrome book and completely out of nowhere four things will happen at the same time or at different times #1 the game crashes #2 the audio cuts out even though i did not press 0 #3 the audio gets all glitchy and staticy #4 the game just freezes and just brings me to the next stage

### ISSUE THREAD

**Issue by t00manyglitch** [FunkinCrew/Funkin#524]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
https://newgrounds/portal/view/770371
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
4.0.1
## Please describe your issue. Provide extensive detail and images if possible.
the game freezes and brings to the next stage of the battle the game crashes the audio starts to cut out and in the main menu the audio will start to glitch and make static sounds and my speakers are not broken since my laptop is quite new and have not even damaged it in any way

**Comment by t00manyglitch** [comment]
if you are reading this ninja muffin and the other developers PLEASE fix this it drives me INSANE

**Comment by MarioLuigi124** [comment]
0.2.7.1?

**Comment by AdirBlaz** [comment]
I'm having a sort of similar issue here on Pop!_OS.
I cannot get the linux-native build of the game ot run, but I can manage to get the windows version to run with WINE.

Although at some points seemingly upon trying to load a stage before play, or at times when losing, the game will freeze up and I believe the entire PC will freeze along with it.
If not the PC, the game must be taking up control priority over everything else somehow? I become no longer able to access my dashboard and I cannot see my mouse. Clicking the X or any other windows does nothing.

I'm using an AMD Kabini and when the game _does_ play, it runs perfectly fine. It just has these freezes that make it absolutely unbearable to play, and often the only way around said freezing is a hard reboot.

I ran a "glxinfo | grep OpenGL" as well in case the info may be needed.
adirblaz@pop-os:~$ glxinfo | grep OpenGL
OpenGL vendor string: AMD
OpenGL renderer string: AMD KABINI (DRM 2.50.0, 5.8.0-7642-generic, LLVM 11.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 20.3.2
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 20.3.2
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.3.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
adirblaz@pop-os:~$

**Comment by mrchromebookman** [comment]
same here bro lol

**Comment by lolBoi9696** [comment]
Idk man this is sus in think these people are lieing it works fine with me but I havent tried Linux yet but it could just be u know because each Linux dist have different executable formats

**Comment by 8bit-coder** [comment]
Part of this is because of the fact that you're using a chromebook. Those laptops have very underpowered CPUs and low amounts of RAM which can cause all sorts of issues in things other than basic web browsing.
