### ISSUE TITLE
Bug Report: windows 32bit issue

### ISSUE THREAD

**Issue by zTenam** [FunkinCrew/Funkin#525]
Hello, I know this might be a recurring issue among the users. I wasn't able, however, to find any solution.

Basically, a friend of mine wants to play this game on his laptop running 32bit windows, though he isn't able to play the game at all. He tried to play it using Chrome as well as Microsoft Edge, though as soon as it gets on 50% of the loading screen it crashes (the computer slows down and the game windows gets that sad face thingy), ![image](https://user-images.githubusercontent.com/79943673/109723658-b0764900-7bae-11eb-9e66-9c3df18051ac.png) he tried it both on newgrounds and itch.io. 
![image](https://user-images.githubusercontent.com/79943673/109724485-f253bf00-7baf-11eb-85bc-3556b2b49a4a.png)

He tried to download the windows 32 bit version, though as soon as he tries to start a song, the screen gets all black, though the game appears to be still working, he managed to perform some notes on the tutorial stage.
https://youtu.be/n70K1JOT9Wc
The video I attached doesn't have the audio, he forgot to unplug the headphones, though he managed to play the "left, right" part.

He tried to re extract the zip file, and he even tried to use and replace some of the 64bit version files out of despair.
Nothing worked, is it an issue that can be fixed on a future version? Many people that had the same issues had been told simply to run the 64bit version of the game in a 64bit environment, though it's not possible for him.

As for the version of the game he was trying to play: it was the 0.2.7.1, he wasn't able to play any older version.
I just hope that it will get fixed soon.

**Comment by RichardCarter2021** [comment]
Yeah, he and I are experiencing the same issues basically. Clearly the game seems to not be properly optimized for 32-bit Windows computers.

**Comment by lolBoi9696** [comment]
I think it's cuz the newgrounds maybe doesn't have a 32 bit version on it but idk what could be causing that on the 32 bit game I'm not very sure I don't have a 32 bit computer laying around with me to test but I don't think it's the code itself as you see this game is built on something called haxeflixel it uses it and is coded in haxe the game isn't that big and doesn't have much code so it be mostly like all the libs and haxeflixel and haxe itself might be causing a issue and maybe if it's a old computer maybe it might not support that graphics card it it's a old one? Or I think it's just the computer is too slow to run the game
