### ISSUE TITLE
Error: forbidden, I use 32-bit windows and every time I want to install the game it tells me: error: forbiddenBug Report: 

### ISSUE THREAD

**Issue by 1XxbenjaminxX1** [FunkinCrew/Funkin#526]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by lolBoi9696** [comment]
Please fill out the templare next time not the title with you're error but I really don't know what that error is never got it before

**Comment by lolBoi9696** [comment]
Probs something to do with Ur windows install

**Comment by lolBoi9696** [comment]
It could also be that you have a modified windows maybe
