### ISSUE TITLE
Question: what the fuck is/source i just wanna play rhythm  game man

### ISSUE THREAD

**Issue by 60098722** [FunkinCrew/Funkin#529]
## What is your question?
i downloaded all the fucking code shit but wtf is /source, im a fucking toddler in coding/computer  shit so please simplify it please thank you

**Comment by DjBRINE** [comment]
Lol, you can actually play this on Newgrounds(https://www.newgrounds.com/portal/view/770371) or itch.io(https://ninja-muffin24.itch.io/funkin). Just read carefully. No need to get it here on github if you want to just play the game

**Comment by 60098722** [comment]
> Lol, you can actually play this on Newgrounds(https://www.newgrounds.com/portal/view/770371) or itch.io(https://ninja-muffin24.itch.io/funkin). Just read carefully. No need to get it here on github if you want to just play the game

i wanted to play the whitty mod and some b side

**Comment by DjBRINE** [comment]
> > Lol, you can actually play this on Newgrounds(https://www.newgrounds.com/portal/view/770371) or itch.io(https://ninja-muffin24.itch.io/funkin). Just read carefully. No need to get it here on github if you want to just play the game
> 
> i wanted to play the whitty mod and some b side

Then go to gamebanana and download these mods onto the released version in itch.io. Here is a source code for original game, not the mods

**Comment by TentaRJ** [comment]
> > Lol, you can actually play this on Newgrounds(https://www.newgrounds.com/portal/view/770371) or itch.io(https://ninja-muffin24.itch.io/funkin). Just read carefully. No need to get it here on github if you want to just play the game
> 
> i wanted to play the whitty mod and some b side

B sides are just reskins and recharts of the game. Download the Itch.io build and replace the files.

And the Whitty mod is literally an already compiled game. Just download it from the site.

**Comment by ninjamuffin99** [comment]
closin this cuz these nice peopole answered da question hehehehe

**Comment by B-Si** [comment]
Who
