### ISSUE TITLE
I cant play it

### ISSUE THREAD

**Issue by ZayaMane** [FunkinCrew/Funkin#53]
so you may be confused but i cant play it on chromebook, I get this gray screen and the box person that looks dead and it reminds me of the mac error screen but i cant play and i dont hear sound, please make it so you can play on chromebook!

**Comment by ElijahZAwesome** [comment]
Not to backseat moderate but it would help everyone a lot if you could give us a screenshot of whatever error you're getting and see if theres some kind of "see details" button. It could be you're running out of RAM, or the chromebook doesnt support a web technology that Haxe Flixel needs, etc but we can't know without some kind of error (or even just a model of chromebook for research and reproducing the issue)

**Comment by ZayaMane** [comment]
ok here is what it looks like
![Screenshot 2020-12-10 at 9 20 16 PM](https://user-images.githubusercontent.com/75820383/101857758-d51dd000-3b2d-11eb-8332-2fec8f32037c.png) and i cant find the box of my chromebook

**Comment by ZayaMane** [comment]
i also get the same thing logged in

**Comment by ElijahZAwesome** [comment]
try opening the console and show us what it says (Right click and press Inspect or press CTRL SHIFT i on your keyboard), then select the console tab and reload the page.

**Comment by ZayaMane** [comment]
ok here
![Screenshot 2020-12-10 at 9 40 33 PM](https://user-images.githubusercontent.com/75820383/101858996-62622400-3b30-11eb-8ba8-2190591db19c.png)

**Comment by ElijahZAwesome** [comment]
use the console tab at the top, not the little one. It should hopefully show more detail?

**Comment by ZayaMane** [comment]
oh sorry i accidently hiden it but i can show you where it is
here:
![Screenshot 2020-12-10 at 9 48 09 PM](https://user-images.githubusercontent.com/75820383/101859511-6cd0ed80-3b31-11eb-9cb6-a9f8e184214f.png) and btw i remmber the error being about allowfullscreen

**Comment by REEEEEEEEEEEEEEEEEEEEEEEEEEEEeEEeE3** [comment]
this is what i got when looking at the console 
![Screenshot 2020-12-15 at 2 34 28 PM](https://user-images.githubusercontent.com/76069698/102264355-854f5800-3ee3-11eb-9e7e-b30fe6b67ac1.png)

**Comment by sidetrackinstar** [comment]
i dont know much about chromeOS but could you theoretically build a native version? afaik its just a proprietary fork of gentoo. try using the haxe binaries from a terminal. if you need help accessing the terminal, inquire further.
[https://haxe.org/download/file/4.1.5/haxe-4.1.5-linux64.tar.gz/](url)
