### ISSUE TITLE
Bug Report: Textures do not align properly when launching the game in fullscreen mode. (WINDOWS)

### ISSUE THREAD

**Issue by brandonapt** [FunkinCrew/Funkin#544]
### If you are playing the game in a browser, what browser are you using?
I am using the desktop version. 

### If you are playing a downloaded version of the game, what operating system are you using?
Windows 64Bit

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
0. Create a Shortcut to funkin.exe by right clicking and hitting "create shortcut" (https://imgur.com/0G4F8sF)
1. Right Click the shortcut and hit properties. (https://imgur.com/wXWlzUu)
2. In that menu, find "Run". (https://imgur.com/oeQOZnw)
3. Changing that to maximized and launching will make the textures not position properly. 

## Please describe your issue. Provide extensive detail and images if possible.

Textures do not align properly when launching the game in fullscreen mode. (https://imgur.com/BD7U9oa) (https://imgur.com/a3WEPW6 dont mind the text in this one i was playing around

**Comment by TentaRJ** [comment]
This is an issue with launching the game in full screen.

So, whenever you compile the game, you set the native resolution and the full screen value. This can be changed in the project.xml file before you compile the game. Change the `Fullscreen`value from `false` to `true` for your build before you compile to put it into fullscreen.
