### ISSUE TITLE
Bug Report: The game crashes after usually failing, or just randomly crashing. It happens to Pico, and Mommy must. I don't know if its because of my computer but i have uninstalled alot of stuff yet it still does this, mainly I use the windows 32 bit.

### ISSUE THREAD

**Issue by Finitryplayz** [FunkinCrew/Funkin#545]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by MarioLuigi124** [comment]
are using the 32 bit version of Friday Night Funkin?

**Comment by Mou-Ikkai** [comment]
Maybe actually follow the description, Finitry.

**Comment by TentaRJ** [comment]
@Finitryplayz Please don't put your error in the title. Fill out the template next time you create an issue.
