### ISSUE TITLE
Winter Horrorland: Can't Hit Those Notes!

### ISSUE THREAD

**Issue by LotteryWoman** [FunkinCrew/Funkin#546]
I am playing the game from Newgrounds in Google Chrome. Whenever I try and play "Winter Horrorland", the game plays the "record scratch" noise that signifies failure every time I hold the notes at the beginning. This is _right_ at the beginning, with the "Your skin is freezing, here, let me help you take it off" part. I am not a bad player, this consistently happens every single time I attempt the song. I know I am holding the correct keys for the correct amount of time. It plays the record scratch part every time.

I asked a friend if she was experiencing this bug, and she said she was experiencing it too.

Has anyone else experienced this bug alongside me?

**Comment by MasterDirector99** [comment]
Yep, for me.

**Comment by NickHam13** [comment]
Fixed by #467

**Comment by LotteryWoman** [comment]
Ah, okay.
