### ISSUE TITLE
Enhancement: Skipping played animations

### ISSUE THREAD

**Issue by ghosthacker478** [FunkinCrew/Funkin#547]
When playing the game on week 6, and you die on thorns, you have to watch the animation for senpai dude over and over, and when you're bad at the game like me, it kinda gets annoying, so can you have it so when the animation has played, and you die, it goes immediately to the song, instead of playing the already played animation.

**Comment by lolBoi9696** [comment]
Look this doesn't really matter and I mean idc and o loose alot ik sometimes it can get annoying but its meant to play everytime also if you play in free play I don't think it plays it so try doing it in that and when you finally beat it then do it on the week 6 to actually try and beat it better on week 6

**Comment by ghosthacker478** [comment]
Huh, didn't realise it did that on free play, thanks for the help
