### ISSUE TITLE
Bug Report: Can skip a song

### ISSUE THREAD

**Issue by Treabien** [FunkinCrew/Funkin#548]
So I was playing week 6 and on thorns spamming enter as I bored from dying I bunch. Each time it paused it skipped just a tiny bit of the song, when it was my turn it was only vocals then I was back on the main menu after about 3 seconds. I know it thinks it beat as I hadn't done Week 6 on hard yet and there was a score and a score in freeplay. Fix this if you intend on having weeks locked like you originally did. Or keep it with you want speed runners or something idk.

**Comment by TentaRJ** [comment]
Please use the template next time you create an issue.
