### ISSUE TITLE
Question: Why does it always crash after 1 song on HP laptops specifically?

### ISSUE THREAD

**Issue by crystalknux** [FunkinCrew/Funkin#549]
## What is your question?
Why does it always crash after 1 song on HP laptops? I'm just curious because I've seen others report this and I know it has to do with HP laptops specifically, but is it known why? It just seems strange that it would load perfectly fine but then always crash after 1 song.

**Comment by MrGhost7969** [comment]
What is that "1 song" exactly?

**Comment by crystalknux** [comment]
> What is that "1 song" exactly?

after either completing the first song track on any week or failing the first song, it always crashes on hp laptops.just find it odd that it would load and function perfectly fine but only to play 1 song and then stop working.

**Comment by TentaRJ** [comment]
It's not dependent on the computer, it's dependent on the CPU and ram available. Some CPUs are just bad.

**Comment by MrGhost7969** [comment]
@crystalknux if you can, please list the specific hardware you're working with

**Comment by crystalknux** [comment]
> It's not dependent on the computer, it's dependent on the CPU and ram available. Some CPUs are just bad.

ah okay that makes sense, most hp laptops dont have great CPU. thanks!
