### ISSUE TITLE
Bug Report: Laptop issue

### ISSUE THREAD

**Issue by jjumpyu** [FunkinCrew/Funkin#555]
When i pause and close my laptop(macbook air) and come back after like a minute. When i resume the game, the notes go extremely fast and the song breaks, all songs become like that and i have to restart the whole tab.

**Comment by TentaRJ** [comment]
That happens because your computer's resources fluctuate when closing it. The game tries to use the same resources but because the resources changed, the game bugs out.

Also next time you make an issue, use the template. It will help us a lot more.

**Comment by jjumpyu** [comment]
ok
