### ISSUE TITLE
Bug Report: I need help

### ISSUE THREAD

**Issue by EchoJams1111** [FunkinCrew/Funkin#556]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 64 I think
## Please describe your issue. Provide extensive detail and images if possible.

Ok, look, I don't know much about technology or really anything but I really need help. I'm trying to download FNF for Windows 64. I had the game before but uninstalled it to try and reinstall it again. But now I can't reinstall it. Every time I try, the file deletes itself for some reason, and then when I try again, it tells me there was an error. I don't know what I did or what to do, please help.

**Comment by lolBoi9696** [comment]
Probs Ur antivirus picking it up
