### ISSUE TITLE
Pausing issue

### ISSUE THREAD

**Issue by Catsuki5856** [FunkinCrew/Funkin#56]
I tested this problem on other weeks i couldnt get it to happen again but on week 1 if i pause at a point im unsure if its a random point but i did it before it switches to bf to start rapping and when i unpaused it it already progressed to the song and said i failed

**Comment by ninjamuffin99** [comment]
yeah, i've personally experienced this myself. Definitely gonna dig into it because it annoyed me lol

**Comment by Catsuki5856** [comment]
> yeah, i've personally experienced this myself. Definitely gonna dig into it because it annoyed me lol

pogs ill try and update you on any other bugs i find
