### ISSUE TITLE
Bug Report: Hang when pressing backspace after the title screen

### ISSUE THREAD

**Issue by dinkley** [FunkinCrew/Funkin#562]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Currently only tested on Newgrounds
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Microsoft Edge Version 89.0.774.45 (Official build) (64-bit)
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 10 20H2 (Build 19042.804), 64 bit
## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Press Enter after the game tells you to do so, then press Backspace. 
## Please describe your issue. Provide extensive detail and images if possible.
After doing the step above, your screen will fade into black and the game will become completely unresponsive. [I recorded a clip of this happening.](https://streamable.com/xlutxq)

**Comment by dinkstr** [comment]
I did check for duplicates, but I could find nothing for "backspace" or "black screen", so apologies if I missed something :)

**Comment by dinkstr** [comment]
Update: Crash appears to be: "Uncaught TypeError: Cannot read property 'animation' of null" in TitleState.hx, line 342
![image](https://user-images.githubusercontent.com/24577847/110590390-9ec51080-816f-11eb-981f-0d76900afe3c.png)

**Comment by pesopeso9868** [comment]
I've actually stumbled upon this problem myself, and I've fixed it with a really simple if statement that checks if logoBl really exists.
Like so:
TitleState.hx, line 342
```haxe
if(logoBl != null){
	logoBl.animation.play('bump');
}
```
I only tested this in the Windows build, so I don't know if this works on the HTML5 build.
