### ISSUE TITLE
Bug Report: Character.hx and PlayState.hx cannot read the property name of null.

### ISSUE THREAD

**Issue by Animeliqite** [FunkinCrew/Funkin#563]
### If you are playing the game in a browser, what browser are you using?
Chrome. It is localhosted with Visual Studio Code.

## What version of the game are you using? Look in the bottom left corner of the main menu.
Version 2.7.1.

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I've done what the error said, but the errors just keep continuing until I delete the whole file, which is not a good thing.
![image](https://user-images.githubusercontent.com/39384772/110668081-fb5e1500-81db-11eb-9831-7a590d3af90b.png)

## Please describe your issue. Provide extensive detail and images if possible.
Sometimes, while modding, the Haxe Compiler gives an error about reading the property name of null. It mostly happens where dadVar is changed in Character.hx, and the file (PlayState.hx) where it sets the offsets of the arrows. It continues until the whole file is deleted. Some PC's don't have the same problem, though. Sure, the same thing happens, but fixing two errors make the game work. I don't know if this is an issue with Haxe, but this is really annoying.

![image](https://user-images.githubusercontent.com/39384772/110668666-99ea7600-81dc-11eb-8619-11eaef65e420.png)
(PlayState.hx)
![image](https://user-images.githubusercontent.com/39384772/110668750-b090cd00-81dc-11eb-9c67-8890435dd587.png)
(Character.hx)

**Comment by lolBoi9696** [comment]
Doesn't happen with me

**Comment by lolBoi9696** [comment]
Maybe it thinks dadvar or holdtimer is null before setting idk or maybe it something else maybe add just a bunch of checks to make sure nothing is null and if you modified the game you probs bricked it
