### ISSUE TITLE
Question: License

### ISSUE THREAD

**Issue by zoeleu** [FunkinCrew/Funkin#564]
## What is your question?
Why use Apache license, and not GPL license, to force more open source in the mods community? This would benefit Linux users to get source code and build mods such as Whitty or FPS Plus.

**Comment by JoanKX** [comment]
I would like the license to change to GPL. It would force all of those mods only available for Windows to release their source code if they want to be up to date and allow Mac and Linux users to create binaries for their platforms, I don't understand the apache license.

#### TL;DR, mods for other platforms than Windows.

**Comment by VMGuy23** [comment]
Wine on Linux surprisingly works for Windows fnf but must be in working directory, so I can do Windows mods

**Comment by JoanKX** [comment]
Thanks for the sugestion. Will try to run mods with wine and see how it runs.

**Comment by VMGuy23** [comment]
FPS counter is gone, sound is great, works very well, good performance.

**Comment by VMGuy23** [comment]
You need to go into the folder with Funkin.exe before running Wine otherwise it is broken

**Comment by matteoturini** [comment]
Wine is a workaround. Not a solution. You don't know if any mods contain
malware in it's code.

Em dom., 2 de mai. de 2021 às 06:12, VMGuy23 ***@***.***>
escreveu:
