### ISSUE TITLE
Bug Report:  Notes with Changed BPM clump together instead of playing at correct section speed

### ISSUE THREAD

**Issue by mewtek** [FunkinCrew/Funkin#565]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Widows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Play a section with ChangedBPM.

## Please describe your issue. Provide extensive detail and images if possible.
When attempting to make sections with a ChangedBPM from the original, the BPM of the song actually changes, but the section speed does not, causing notes to clump together and become virtually unplayable. 

Section with changed BPM from the chart editor: https://youtu.be/0OhrzUwT_Og
Section with changed BPM in-game: https://youtu.be/qR0gHd8DEyA

**Comment by Zeexel** [comment]
So, turns out I'm just stupid and didn't realize I could change the scroll speed of the song without ruining the timing.

Whoops.
