### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by githubtest453** [FunkinCrew/Funkin#566]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
https://www.newgrounds.com/portal/view/770371
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below
## What version of the game are you using? Look in the bottom left corner of the main menu.
Idk, I never got to see it.
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
It just crashes on Chromebooks. (my device)
## Please describe your issue. Provide extensive detail and images if possible.
It keeps on crashing on Chromebook.

**Comment by lolBoi9696** [comment]
It's not meant for Chromebooks I think
