### ISSUE TITLE
Bug Report: Chrome os/ School computers

### ISSUE THREAD

**Issue by yoouahahahah** [FunkinCrew/Funkin#568]
-Laters version of the game
theres a bug on Chrome Os were you can;t run the game on the website its from. thus crashing the website an nearly crashing my laptop is there a way to get a very lowed verion on the game without it crashing.

**Comment by arceuss** [comment]
you can use the linux version but itll run like ass

**Comment by yoouahahahah** [comment]
> you can use the linux version but itll run like ass

yeah i just find it annoying that school computers are ass cheeks
