### ISSUE TITLE
Audio delay issue when lagging

### ISSUE THREAD

**Issue by Applemunch** [FunkinCrew/Funkin#57]
Whenever you lag while playing a song, the song audio gets delayed, and becomes out-of-sync with the vocals.

**Comment by Applemunch** [comment]
If I could make a suggestion, try to make the song and notes consistently sync up with some sort of internal step/beat variable.

**Comment by gedehari** [comment]
Thought about this too. Maybe make a separate function to sync, and then call tha function every beat/measure.

**Comment by ninjamuffin99** [comment]
right now there miiiight be something like that, but i guess it doesnt work lol
