### ISSUE TITLE
you are swearing in the script 

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#570]
## What is your question?
no swearingplz strike 1

**Comment by frosthead69** [comment]
what

**Comment by droni1234** [comment]
already heared about freedom of speech man???

**Comment by ycod-er** [comment]
no but have you heard of heck????

**Comment by actuallyasmartname** [comment]
There's literally offensive language in one of the splash texts lol https://github.com/ninjamuffin99/Funkin/blob/master/assets/preload/data/introText.txt

**Comment by ycod-er** [comment]
lol

**Comment by prokube** [comment]
*proceeds to rated T on Newgrounds*
