### ISSUE TITLE
Bug Report: Null Object Reference

### ISSUE THREAD

**Issue by thethiny** [FunkinCrew/Funkin#583]
#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

Issue unrelated to cache

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

x64 Win

## What version of the game are you using? Look in the bottom left corner of the main menu.
Current Git Version as of 14/March/2021.

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

Compiling the game's source and launching the game produces "Null Object Reference" Error when trying to access freeplay.

**Comment by itskwartz** [comment]
#146 solves this.

**Comment by lolBoi9696** [comment]
This is a error due to ngio a newgrounds API and it calls something in free play that just crashes the game cuz there aren't any api keys either remove ngio lines from free play or put it in #if Ng

#end

**Comment by thethiny** [comment]
> This is a error due to ngio a newgrounds API and it calls something in free play that just crashes the game cuz there aren't any api keys either remove ngio lines from free play or put it in #if Ng
> 
> #end

Thanks. Also thanks to @itskwartz I haven't gotten a notification for your response.

**Comment by thethiny** [comment]
Wdym not planned bro it was already fixed

**Comment by Lasercar** [comment]
> Wdym not planned bro it was already fixed

status: stale
