### ISSUE TITLE
Bug Report: Lime expects version 7.7.x, but no such version ever exists

### ISSUE THREAD

**Issue by Polytelus** [FunkinCrew/Funkin#584]
When trying to run "lime build linux -debug" or "lime test linux -debug", lime comes with the following error:
```
Warning: Lime version 7.9.0 may not be compatible with OpenFL 9.0.2 (expected version 7.7.*)
Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
Type not found : haxe.Exception
```
However, no such version 7.7.* exists, in fact the lastest 7.*.* is 7.1.2.
What am I doing wrong? I've installed haxe correctly and so did the libs.

My system is running Ubuntu 18.04 LTS and i'm trying to build Funkin-0.2.7.1.

**Comment by Tuxsupa** [comment]
Use haxelib install lime 7.8.0

**Comment by Polytelus** [comment]
So, i've tried to install version 7.8.0 of lime.
Unfortuntately, that did not fix the issue.
```
Warning: Could not find template file: haxe
Warning: Could not find template file: cpp/hxml
Error: Could not process argument export/release/linux/haxe/release.hxml (file not found)
Invalid character: /
```

I've reinstalled every haxelib 3 times already.

**Comment by lolBoi9696** [comment]
Try haxelib install lime? Again or try reinstalling haxe

**Comment by lolBoi9696** [comment]
![Screenshot_20210316-094832.png](https://user-images.githubusercontent.com/76548041/111289162-c9fea280-863c-11eb-85a9-97f8ade7e863.png)

These are ones u should either install inthink

**Comment by TentaRJ** [comment]
Don't install haxe 4.1.5. It doesn't work.

**Comment by Hendicted** [comment]
> Don't install haxe 4.1.5. It doesn't work.

Does for me, what do you mean?

**Comment by lolBoi9696** [comment]
> > Don't install haxe 4.1.5. It doesn't work.
> 
> Does for me, what do you mean?

hes saying haxe 4.1.5 doesnt work for fnf

**Comment by lolBoi9696** [comment]
> > Don't install haxe 4.1.5. It doesn't work.
> 
> Does for me, what do you mean?

also since he said 4.1.5 and above dont work heres a link to a older version https://haxe.org/download/version/4.1.4/

**Comment by TentaRJ** [comment]
I meant to say don't use haxe 4.2.1 but i got my numbers mixed up. Sorry.

Haxe 4.1.5 does work 👍

**Comment by lolBoi9696** [comment]
> I meant to say don't use haxe 4.2.1 but i got my numbers mixed up. Sorry.
> 
> Haxe 4.1.5 does work 👍

oh lol

**Comment by Polytelus** [comment]
Closed this issue as I got it to compile on Linux Mint 20.1. As i'm not using linux anymore, this became unrelevant.
