### ISSUE TITLE
Bug Report: Input system causes players to miss multiple notes all at once if they miss one

### ISSUE THREAD

**Issue by Yoshigobrr** [FunkinCrew/Funkin#585]
I always wanted to talk about this problem because this made songs like M.I.L.F and Spookeez even harder than expected. Whenever I miss any notes, it causes me to not be able to hit any other notes especially on M.I.L.F. I hope this issue is fixed.

**Comment by engineereng** [comment]
Please reformat your bug report using the Bug template found at [bug.md](https://github.com/ninjamuffin99/Funkin/blob/master/.github/ISSUE_TEMPLATE/bug.md). Issues that follow the formats given are much more likely to be fixed.

**Comment by 8bit-coder** [comment]
I believe this is the result of the hit stun, since in the FPS Plus mod, disabling hit stuns makes it so notes are able to be hit right after one is wrong. This might be intended behavior.
