### ISSUE TITLE
Lag on week 3 :(

### ISSUE THREAD

**Issue by Loczek999999999** [FunkinCrew/Funkin#59]
There is some lag at week 3 on Newgrounds! I didn't check the download version yet but i would still fix!!
The rest of the levels have 30-40 fps
but this one drops sometimes to even 8!

**Comment by ninjamuffin99** [comment]
i think mostly this is because of the fading lights in the background. I know for a fact that causes certain performance issues.
I'm trying to decide whether or not to disable that for now for people with lower end hardware to play, or to hold out til i get the little options menu implemented
