### ISSUE TITLE
Enhancement: 

### ISSUE THREAD

**Issue by GStudiosX2** [FunkinCrew/Funkin#592]
## What is your suggestion, and why should it be implemented?

I think you should make stuff like to make modding easier where you can add a certain background to a song also you can put when you want the bf to say hey! and you can do it in like the level file maybe or another txt file or JSON file? And if we have this feature then that will make modding easier and making levels easier to i don't think it will take that long lol try and figure it out but I feel like you kinda need this since your adding modding anyway and i think this should be a feature for week 7 also add where you can add the offsets for the characters in a file so the you don't need to create a switch statement lol and then just grab that file for the character and background and it basically grab all the offsets put it in a array and the 1st value in it will be X and the second value will be Y and maybe it look like this in a file or something for example
```
X:200Y:50
```
Like that and it be useful as then you won't have to manually add them to the code and then it wouldn't take forever to add it also you wouldn't have to keep compiling If you already compiled the file with it once and it will make modding easier for sure please add this as I think this is nesassary for modding and such and I think this is a easy implementation if you want I can try and do it and I send you a pull request for you. Like I said before please add this thanks

**Comment by TentaRJ** [comment]
Just look at guides lol

**Comment by lolBoi9696** [comment]
> Just look at guides lol

im just saying its useful because hes adding mod support to the game anyway

**Comment by prokube** [comment]
FNF Modding plus unlocks hidden settings but yeah having this in vanilla would be pog

**Comment by lolBoi9696** [comment]
> FNF Modding plus unlocks hidden settings but yeah having this in vanilla would be pog

thats different to what im saying i mean the offsets for the backgrounds and characters are set in the code it be kinda pog if there was some sort of way to hook a file for a character to have offsets in there
