### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by GStudiosX2** [FunkinCrew/Funkin#593]
## What is your question?

Is it okay if I create a replica fan game for the game called Friday night practice tbh idk if that names already taken but I'm currently working on it rn and I just want to make sure if I can use the assets and sounds I promise to credit everyone who helped on assets and the sounds that is made in funkin only if you want if I can't use it I guess I have to make my own stuff lol

**Comment by TentaRJ** [comment]
It's open source.

**Comment by lolBoi9696** [comment]
> It's open source.

that doesnt really mean that i can yse the assets

**Comment by TentaRJ** [comment]
[Look at the license](https://github.com/ninjamuffin99/Funkin/blob/master/LICENSE)

**Comment by lolBoi9696** [comment]
> [Look at the license](https://github.com/ninjamuffin99/Funkin/blob/master/LICENSE)

how do i if the licence is fake or not it could say these things but it really is not

**Comment by TentaRJ** [comment]
This is the license for this repository. You can check it yourself.

**Comment by lolBoi9696** [comment]
> This is the license for this repository. You can check it yourself.

u dont know dude it could be a unfinished licence or a licence there trying to come up with a better one idk man i need to really hear this from the creator

**Comment by TentaRJ** [comment]
Talk to him about it then. Mention him. If you do, you are just gonna waste your time because it is the same license that is on the home page of the repository.

If you don't think it is the same license, then prove me wrong.

**Comment by TootNoot** [comment]
ninja muffin has said that he is fine with fangames

**Comment by lolBoi9696** [comment]
> Talk to him about it then. Mention him. If you do, you are just gonna waste your time because it is the same license that is on the home page of the repository.
> 
> If you don't think it is the same license, then prove me wrong.

i saw a commnet somewhere where on a different issue ninja said they working around stuff for the licences so idk

**Comment by lolBoi9696** [comment]
> ninja muffin has said that he is fine with fangames

yeah but all the art and sounds arent made by him so what copyright is for that

**Comment by TootNoot** [comment]
back to what tenta says, there is a license saying that you are allowed to use the assets, the game is open source so really you can use whatevers in the repository. Creators of a public repository set the license themselves and know what they're setting it for. There is no need to bother ninja muffin for something that has already been answered by the license

**Comment by lolBoi9696** [comment]
> back to what tenta says, there is a license saying that you are allowed to use the assets, the game is open source so really you can use whatevers in the repository. Creators of a public repository set the license themselves and know what they're setting it for. There is no need to bother ninja muffin for something that has already been answered by the license

k but i just feel like i really should get approval of ninja really

**Comment by TootNoot** [comment]
The license is your approval.
