### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Lofty207** [FunkinCrew/Funkin#594]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
newgrounds 
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
crome just crome 
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
none 
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
well i have found no way of stoping the bug 
## Please describe your issue. Provide extensive detail and images if possible.
ok first of all when i get into the game it is all fine and then when i try and play week 1 the game just strait up goes into 2 frames then my computer lags out then when i do week 2 it does the same thing but worse because then i cant even move my mouse same thing with week 3 and week 4 is fine i can play week 4 very good 61 frames and then week 5 is the same issue and week 6 is ok as like the week 4 so if there is anyway of stoping this please let me know thks -Lofty

**Comment by TentaRJ** [comment]
computer bad

happens when your computer doesn't have enough resources.
