### ISSUE TITLE
Question: help with compiling Friday Night Funkin switch version (Idk how to mark this so i marked it as a question)

### ISSUE THREAD

**Issue by AntogamerYT** [FunkinCrew/Funkin#597]
When i try to compile the Nintendo Switch version of Friday Night Funkin the batch file can't find "lime-switch", i don't know how to fix because I also tried to install "lime-switch" via the cmd with the command "lime install switch", but it does give me "Error: Failed with error: No such project : lime-switch"

So, can someone help me to fix?
![image](https://user-images.githubusercontent.com/64664639/111390879-c8bc8c80-86b3-11eb-8c12-109a943d7513.png)

**Comment by ninjamuffin99** [comment]
lime-switch is only available if you have access to nintendo switch SDKs! You need to sign an NDA with nintendo and all that fuss. Not publicly available!

**Comment by ScriptHTML** [comment]
@ninjamuffin99 if you already applied for nintendo dev program, then nsp is compiled already? then you just need to publish it.
