### ISSUE TITLE
Question: Where do I determine at which point in a song mom or dad sings, when using parents-christmas sprite?

### ISSUE THREAD

**Issue by Spytonnnnnnnnnnnnnnnnnnnnnnnnn** [FunkinCrew/Funkin#598]
I am fairly new when it comes to programming and modding.
I created a mash-up of one of each parent's song and wanted to use the parents-christmas sprite since it is fitting.
My problem is is that my smooth brain can't figure out how to make them sing their respective parts.
Thanks in advance.

**Comment by justamole** [comment]
press alt amination in section 
![Screenshot 2021-03-16 210146](https://user-images.githubusercontent.com/79595919/111403370-d9143d80-869a-11eb-8610-721588e551ce.png)

**Comment by justamole** [comment]
also if you do this with other characters (such as bf, gf, mom, dad, Esc.) then it will just freeze the animation for the character.

**Comment by ninjamuffin99** [comment]
justamole answered question, so imma close dis!

also yeah ONLY supported with mom/dad christmas animation

**Comment by Spytonnnnnnnnnnnnnnnnnnnnnnnnn** [comment]
thank you

**Comment by justamole** [comment]
oh sh

**Comment by justamole** [comment]
ᶦ ᵏⁿᵒʷ ʸᵒᵘʳ ˢᵉᶜʳᵉᵗˢ ⁿᶦⁿʲᵃᵐᵘᶠᶠ >:⁽
