### ISSUE TITLE
Bug Report: Freeplay leads to black screen

### ISSUE THREAD

**Issue by Penncilk** [FunkinCrew/Funkin#599]
I compiled the game to run, and when I went to click Freeplay, it blackscreened on me, I'm playing this on the Brave Web browser on Windows, and everything else runs well, exept for freeplay. It says this is 0.2.7.1, but it has more features added to it than the normal 0.2.7.1 from compiling it from the source code

**Comment by ActualMandM** [comment]
duplicate of #410, can be fixed locally by merging #412
