### ISSUE TITLE
One frame glitch where arrows appear in incorrect position

### ISSUE THREAD

**Issue by Herschel** [FunkinCrew/Funkin#6]
Sometimes arrows incorrectly flicker for one frame near the arrows at the top of the screen; possibly when an arrow is recycled/respawned, it has one frame where it was in its previous position before it gets set to the bottom of the screen.

**Comment by ninjamuffin99** [comment]
maaaybe fixed it with master@0a4273b , but will test a bit more to make sure its ironed out. Don't wanna jinx myself heheh
