### ISSUE TITLE
What I do wrong?

### ISSUE THREAD

**Issue by akronmna1** [FunkinCrew/Funkin#601]
I compiled the game exactly as instructed and when I go into FreePlay I get a error: Null Object Exception. What am I doing wrong?

**Comment by RGFTheCoder** [comment]
Have you added the blank ApiKeys file?

**Comment by akronmna1** [comment]
Yes.

**Comment by TentaRJ** [comment]
> I compiled the game exactly as instructed and when I go into FreePlay I get a error: Null Object Exception. What am I doing wrong?

The error happens because Freeplay is trying to call the NGio.hx file. You need to comment out each instance of I think 'NGio.pull()'.

**Comment by Jan200101** [comment]
This error was introduced by me by accident in #362
#412 fixes it
