### ISSUE TITLE
seems like the linux build on itch.io is outdated

### ISSUE THREAD

**Issue by Teh404Gal** [FunkinCrew/Funkin#602]
please update the linux build on your itch.io page
for now im going to compile the game
sorry for bothering

**Comment by GenericGaming** [comment]
It's really hard to compile for linux, it's relatively easy to compile for mac as long as you have a mac computer, and it's a pushover to compile for windows, don't worry, i'm sure that linux will be updated when week 7 comes out.

**Comment by foxsouns** [comment]
> 
> 
> It's really hard to compile for linux, 

How so? I find it fairly trivial; just get haxe, haxeflixel, and install the plugins that are listed in the README.md; then just `lime test linux`. i don't see any excuse for ninja, the person who literally said "building for linux is fairly easy" not to build for linux; but whatever.
