### ISSUE TITLE
Bug Report: i don't know if this is a frequent thing but the game has not loaded for me in 3 weeks and i really enjoy this game

### ISSUE THREAD

**Issue by ikuoomi** [FunkinCrew/Funkin#603]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by TentaRJ** [comment]
Please don't have your issues in the titles and fill out the template for the arguments so we know what to do.

**Comment by Salladk-but-no-mo-flaged** [comment]
echo Your game dont load in HaxeFlixel logo?
set /p answer=
if %answer% equ yes goto SuggestedSolution
if %answer% equ no goto UFuckd
:SuggestedSolution
cls
echo Try reloading the page until it reach 100%
:UFuckd
cls
echo IDK the solution
pause
exit

**Comment by Salladk-but-no-mo-flaged** [comment]
`echo hi`

**Comment by Salladk-but-no-mo-flaged** [comment]
###  _***ddd*_
