### ISSUE TITLE
-

### ISSUE THREAD

**Issue by boyangsic** [FunkinCrew/Funkin#604]
-

**Comment by dinkstr** [comment]
You're using Haxe 4.1.5 right? Versions after that tend to have issues compiling.

**Comment by boyangsic** [comment]
yes. i installed 4.1.5.

**Comment by Colep14** [comment]
Which version of lime are you using? I had to downgrade from latest to 7.7.0 to get it to compile.

**Comment by boyangsic** [comment]
Yes. I fixed that bug. But i have error. I modded week,characters,music but it get error. I dont know that error but i know it starts with null
