### ISSUE TITLE
Can't compile because Lime no existy

### ISSUE THREAD

**Issue by Nateaaaaaaaaaaaaaaaaaaaa** [FunkinCrew/Funkin#611]
nathanieldranoff@pop-os:~/Funkin$ lime test linux -debug
Command 'lime' not found, did you mean:
  command 'lie' from deb lie (2.2.2+dfsg-3build1)
  command 'time' from deb time (1.7-25.1build2)
  command 'hime' from deb hime (0.9.10+git20170427+dfsg1-5)
  command 'lame' from deb lame (3.100-3)
Try: sudo apt install <deb name>

**Comment by prokube** [comment]
either `haxe install lime` or `haxelib install lime` i think

**Comment by GenericGaming** [comment]
IT seems you didn't properly install lime onto your computer, there's a guide on the FNF modding discord on what you need to compile the game properly, take it from me, ninjamuffin's guide needs a bit of work.
Here's a link to the fnf modding discord, the info you seek will be in the #modding resources and help section.
https://discord.gg/zxdtqjVdBn

**Comment by TentaRJ** [comment]
'Haxelib run lime setup'

**Comment by Nateaaaaaaaaaaaaaaaaaaaa** [comment]
thanks
