### ISSUE TITLE
Bug Report: Compiling error

### ISSUE THREAD

**Issue by aflacc** [FunkinCrew/Funkin#612]
When I run `lime test html5 -debug` it gives me this error:
`C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/html5/HTML5Window.hx:321: characters 5-26 : lime._internal.backend.html5.HTML5WebGL2RenderContext should be lime.graphics.WebGLRenderContext
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:473: characters 80-91 : Type not found : ObjectClass
source/APIStuff.hx:3: characters 1-6 : Missing ;`

and when i do `lime test windows -debug`

it gives many errors
`C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:143: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES2RenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:144: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGLRenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:150: characters 6-24 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES3RenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:151: characters 6-25 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGL2RenderContext
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:31: characters 3-15 : flixel.math.FlxPoint should be { _inPool : Bool }
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:31: characters 3-15 : ... The field _inPool is not public
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:17: characters 2-53 : error: The field _inPool is not public
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:17: characters 2-53 : ... have: { get: (...) -> { set: (...) -> flixel.math.FlxPoint } }
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:17: characters 2-53 : ... want: { get: (...) -> { set: (...) -> { _inPool } } }
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:70: characters 10-19 : { get : () -> { set : (Float, Float) -> { _inPool : Bool } } } has no field putUnsafe
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/utils/src/openfl/utils/ByteArray.hx:750: characters 3-30 : openfl.utils.ByteArray should be lime.utils._Bytes.LimeBytes
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:473: characters 80-91 : Type not found : ObjectClass
source/APIStuff.hx:3: characters 1-6 : Missing ;`

**Comment by TentaRJ** [comment]
Run 'haxelib' and send back the results

**Comment by K4rakara** [comment]
@aflacc To fix the `C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:473: characters 80-91 : Type not found : ObjectClass` error, go to ``C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx` and replace `ObjectClass` with `Dynamic` every time it appears.

That will fix the issue, but I do believe that the root issue is that you're on Haxe 4.2, but this game can't compile on that version of haxe due to changes that affect the `Flixel` library.

For the `APIStuff.hx` error, you've copy-pasted the contents of `APIStuff.hx` incorrectly.
