### ISSUE TITLE
Bug report :Won't load game:

### ISSUE THREAD

**Issue by G0gys** [FunkinCrew/Funkin#618]
I have only played this game twice and then the game stoped loading. It's gets to like 82% then stops, I've waited for hours and still no reponse.

**Comment by itskwartz** [comment]
Refresh the page + use the issue template next time

**Comment by itskwartz** [comment]
Refresh the page + use the bug report template next time

**Comment by G0gys** [comment]
I have refreshed the page

**Comment by G0gys** [comment]
And I will make sure to use the template next time

**Comment by MarioLuigi124** [comment]
refresh it again
