### ISSUE TITLE
Music and notes not sycing up.

### ISSUE THREAD

**Issue by coolgamedude** [FunkinCrew/Funkin#62]
If you move the game window or you start to lag your music and notes will not sync up. You can fix it if you pause and unpause the game.

**Comment by ElijahZAwesome** [comment]
The timing of the music is dependent on the vocals i believe, and the vocals are cached before you even hit any notes. However the instrumental is cached and played on the first note, which lags the game and causes a desync. NinjaMuffin, pls fix

**Comment by CPPxfnfmodsmaker** [comment]
p
