### ISSUE TITLE
compiling problems

### ISSUE THREAD

**Issue by pumpsix** [FunkinCrew/Funkin#621]
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/NGio.hx:46: characters 17-53 : Warning : Use currentVersion

--(how do i fix this)

**Comment by itskwartz** [comment]
What command did you type in to compile it

**Comment by Snoni** [comment]
> What command did you type in to compile it

i have the same problem and used `lime test windows -debug`

**Comment by co4ekmc** [comment]
> What command did you type in to compile it

He typed "lime test windows" or "lime test windows -debug". And I have this error. My game can't open with this error!

**Comment by VMGuy23** [comment]
its a warning

it shouldnt stop there
