### ISSUE TITLE
So, I wanted to make a custom song/week for the HTML5 port, and it takes me to a softlocked version of the title screen whenever I click on the song. (Don't worry, I made it past the freeplay crash issue)

### ISSUE THREAD

**Issue by IndigoVoidigo** [FunkinCrew/Funkin#638]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
I normally play in itch.io
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Edge

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
x64
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No matter what, I can always reproduce it.
I just click on the song.

## Please describe your issue. Provide extensive detail and images if possible.
https://user-images.githubusercontent.com/78701030/112229476-6b6f9080-8c09-11eb-87ec-17f325ab9299.mp4

**Comment by KurtisCates** [comment]
Damn thats a lot of crap on your task bar
Just use my [Github Wiki WIP](https://github.com/KurtisCates/Friday-Night-Funkin/wiki/How-To-Create-A-Character).

I hope this works
