### ISSUE TITLE
Bug Report: Week 5 Crash when modifying certain data, possible problem with new assets system?

### ISSUE THREAD

**Issue by NerdiestAlpaca** [FunkinCrew/Funkin#642]
So. I compiled a build from this repository. I'm testing out my mod, and since I'm not modding over the Christmas Parents, I went to change the opponents of Cocoa and Eggnog to Dad and Mom, respectively. Cocoa worked without a single problem, but when I moved to Eggnog, it crashed. I then changed the opponent of Eggnog to Dad, which resulted in _that_ working without a problem. I have tried multiple times to change the opponent to Mom using the debug menu, but it once again crashes every time. I don't exactly know what the issue is here, and this is by no means a completely game-breaking bug, but it was definitely not intended so I'm reporting it here.

**Comment by BoyfriendFNF** [comment]
this happens in regular play too
