### ISSUE TITLE
After Glitch?

### ISSUE THREAD

**Issue by Euroex** [FunkinCrew/Funkin#646]
After finishing the song "Thorns" the Spirit has small chance of doing glitch sounds. Idk if thats normal, or just engine just stopped and resumes on the last note.

**Comment by hdboye** [comment]
I thought this was normal?? I have it every time i finish Thorns.

It has something to do with the music looping when the game takes too long to switch back to the story mode menu. I've seen that sometimes when it does take a while to return to the story mode menu, the song restarts. I have no idea why it glitches out on Thorns though. These noises could probably be fixed if the loop for the music was turned off.
