### ISSUE TITLE
Is bf gay

### ISSUE THREAD

**Issue by Windows1Door2Daniel** [FunkinCrew/Funkin#648]
is bf gay?

finaly im not flagged

https://youtu.be/dQw4w9WgXcQ haha random url go play

**Comment by TentaRJ** [comment]
good job on thinking of such an original joke.

and by the way, what is wrong with being gay? why are using it as an insult?

**Comment by VoltrexMaster** [comment]
Not funny, didn't laugh

**Comment by Salladk-but-no-mo-flaged** [comment]
> Not funny, didn't laugh

its not a joke

just a question

**Comment by Salladk-but-no-mo-flaged** [comment]
> > Not funny, didn't laugh
> 
> its not a joke
> 
> just a question

neither a insult

**Comment by Salladk-but-no-mo-flaged** [comment]
https://user-images.githubusercontent.com/81389527/112628697-77697700-8df0-11eb-8fc9-373ca792ac95.mp4

**Comment by ObiDriftKenobi** [comment]
people like you shouldn't have accounts on github.

**Comment by PrincessMtH** [comment]
Fixed by #131

**Comment by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [comment]
hes prolly pan bc pico and gf

**Comment by SilverRoll** [comment]
Based GitHub ????

**Comment by swagmancoolkid** [comment]
yeah 100% gf is actually pico in a dress

**Comment by Windows1Door2Daniel** [comment]
oh i get it

BF is Bisexual

**Comment by nickpythonluajava** [comment]
why does this post exist

**Comment by Windows1Door2Daniel** [comment]
> good job on thinking of such an original joke.
> 
> and by the way, what is wrong with being gay? why are using it as an insult?

LGBT are humans

**Comment by Windows1Door2Daniel** [comment]
Chains: On the first day of Christmas, Payday gang to me, this broken piece of sh*t drill

Hoxton: On the second day of Christmas, Payday gang to me, two years in jail

Chains: And a broken piece of sh*t drill

Twich: On the third day of Christmas, Payday gang to me, Three tires shot!

Hoxton: Two years in jail

Chains: And a broken piece of sh*t drill

Wolf: On the fourth day of Christmas, Payday gang to me, four greedy robers!

Twich: Three tires shot!

Hoxton: Two years in jail

Chains: And a broken piece of sh*t drill wich i hate

Dallas: On the fifth day of Christmas, Payday gang to me, five bullets left

Wolf: Four greedy robers!

Twich: Three tires shot!

Hoxton: Two years in jail

Chains: I hate this broken piece of sh*t drill

Dozer: On the sixth day of christmas, Payday gang to me, Six Dozers charging

Dallas: Five bullets left

Wolf: Four greedy robers!

Twich: Three tires shot!

Hoxton: Two years in jail

Chains: F*ck this broken piece of sh*t drill

Tazer: On the seventh day of christmas, Payday gang to me, seven tazers responding

Dozer: Six Dozers charging

Dallas: Five bullets left. Ammo bag!

Wolf: Four greedy robers!

Twich: F*ck. Three tires shot!

Hoxton: Two years in jail

Chains: And this broken piece of SH*T DRILL! Im serious

S.W.A.T 1: On the eighth day of christmas, Payday gang to me, eigth S.W.A.T.s repeling

Tazer: Seven tazers responding

Dozer: Six Dozers charging

Dallas: Five bullets left. Ammo, ammo!

Wolf: Four greedy robers!

Twich: Three tires shot!

Hoxton: Two f*cking years in jail

Chains: F*ck this broken piece of sh*t drill! Where are we getting this f*cking thing?

S.W.A.T. 2: The nineth day of christmas, Payday gang to me, nine hostages are fleeing

S.W.A.T. 1: Eigth S.W.A.T.s repeling

Tazer: Seven tazers responding

Dozer: Six Dozers charging

Dallas: Five bullets left! Ammo bag, ammo bag!

Wolf: Four greedy robers!

Twich: Three tires shot!

Hoxton: Two years in jail!

Chains: AGAIN, THE F*CK WITH THIS BROKEN PIECE OF SH*T DRILL! I mean seriously

Bain: On the tenth day of christmas, Payday gang to me, ten seconds respond time

S.W.A.T 2: Nine hostages are fleeing

S.W.A.T 1: Eigth S.W.A.T.s repeling

Tazer: Seven tazers responding

Dozer: Six Dozers charging!

Dallas: Five... bullets left!

Wolf: FOUR GREEDY ROBERS!

Twich: WHOA AAAH GAAAAAAAAAAH!

Hoxton: Two years in jail!!

Chains: YO, F*CK THIS, F*CK THIS DRILL, F*CK YOU, F*CK THIS FOOL

Clover: On the eleventh day of christmas, Payday gang to F*CK! Eleven doors to lockpick?!

Bain: Ten seconds respond time

S.W.A.T 2: Nine hostages are fleeing

S.W.A.T 1: Eigth S.W.A.T.s repeling!

Tazer: Seven tazers responding

Dozer: Six Dozers charging!

Dallas: FIVE BULLETS LEFT! AMMO, AMMO!

Wolf: FOUR GREEDY ROBERS!!!!!!!

Twich: THERE IS A F*CKING WALL!!!

Hoxton: TWO YEARS IN JAIL!

Chains: (Cries)

Vlad: On the twelfth day of christmas, Payday gang to me, twelve bags of gold

Clover: Eleven doors to lockpick?!

Bain: Ten seconds respond time

S.W.A.T 2: All hostages gone

S.W.A.T 1: Eigth S.W.A.T.s repeling

Tazer: Seven tazers responding

Dozer: SIX DOZERS CHARGING!!!

Dallas: FIVE BULLETS LEFT!!! IM OUT OF F*CKING AMMO!!!

Wolf: WHERE IS THE GATEWAY!!!!!!!!!!!!!!!!!!!!!!!!!

Twich: AAAAAAAAAAAAAAAAAAH!!!!!!!!!!!! (CRASH!!!)

Payday and GEN SEC police: And a broken piece of sh*t drill
Chains: F*ck my life

Wolf's gun: Bang!!

GEN SEC police: Aaaaah! (CRASH)

Helicopter: RUFURUFURUFURUFURUFU

**Comment by r3mis** [comment]
^ he's 8

**Comment by nickpythonluajava** [comment]
> ^ he's 8
> 
> 

i could tell

**Comment by Windows1Door2Daniel** [comment]
Oh wow how did you know?

You sure a seer

**Comment by r3mis** [comment]
> Oh wow how did you know?
> 
> You sure a seer

Urhh okay weirdo
