### ISSUE TITLE
Bug Report:  hello i´m using windows 10 and i use newgrounds for the game dowloading and not pass the dowload sreen

### ISSUE THREAD

**Issue by martinsamuel34** [FunkinCrew/Funkin#650]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by TentaRJ** [comment]
## Woah buddy!
You are receiving this message because you either:
1. Placed your entire issue in the title
2. Didn't properly use the template as specified for issues
3. Both
### Please fix this problem by editing your issue or by closing it!

**Comment by Salladk-but-no-mo-flaged** [comment]
NewGrounds is only to play the game

Download the game in Itch. io
