### ISSUE TITLE
game literally not opening on windows 10

### ISSUE THREAD

**Issue by Fluttahdidistuttah** [FunkinCrew/Funkin#651]
this is what appears when i try to open it 
![image](https://user-images.githubusercontent.com/81400070/112570757-a5c96100-8db4-11eb-8542-db11613a51c5.png)

**Comment by TentaRJ** [comment]
## Woah buddy!
You are receiving this message because you either:
1. Placed your entire issue in the title
2. Didn't properly use the template as specified for issues
3. Both
### Please fix this problem by editing your issue or by closing it!
