### ISSUE TITLE
Bug Report: In the song "Senpai", a select few of the sustained notes are almost unhitable. (Even when the button is pressed)

### ISSUE THREAD

**Issue by Striker55623** [FunkinCrew/Funkin#655]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (x86)
## What version of the game are you using? Look in the bottom left corner of the main menu.
2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
It happens when the song is played.
## Please describe your issue. Provide extensive detail and images if possible.
To be specific, a long sustained Up note is not able to be hit "Sick". You have to hit the note when it is almost off screen, and even then you have to double tap. I believe it is something wrong with the Senpai-hard.json chart. This issue only occurred after the 2.7.1 update, and not during 2.7.0. A few other charts also run into the same issues, Bopeebo, and I believe Satin-panties have a few sustained notes that are nearly impossible to hit.

**Comment by dum-du-m** [comment]
A fix for the sustain note system has already been merged
