### ISSUE TITLE
Bug Report: Repeatedly pressing Enter during the HaxeFlixel phase of the startup can cause the game to crash.

### ISSUE THREAD

**Issue by Striker55623** [FunkinCrew/Funkin#656]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Window (86)
## What version of the game are you using? Look in the bottom left corner of the main menu.
2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Repeatedly pressing Enter during "HaxeFlixel" on startup.
## Please describe your issue. Provide extensive detail and images if possible.
If you mash the "Enter" key during the "HaxeFlixel" startup screen, the game fades to white and crashes.

**Comment by vyrulow** [comment]
I was able to recreate this consistently on version 2.7.1 on Windows(x86_64). Some side notes - this does not work on the web version, could not get the game to crash by spamming Enter on startup. I have also tried recreating this using other known bound default keys and none of them seem to crash the game either, so it's seemingly only a problem with Enter. Holding down Enter does not cause a crash either, you have to continually press the key over and over and it will go white, and then immediately close itself. I would investigate whatever key listeners are active as the game starts up and perhaps disable them entirely or enable them at a later time until the main menu pops up.
