### ISSUE TITLE
Bug Report: Week 4's M.I.L.F. has an unintentional vocal swap near the end.

### ISSUE THREAD

**Issue by QuantumM3Chanic** [FunkinCrew/Funkin#657]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
itch.io
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Edge
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x64
## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Since this is just a minor issue with the vocals, all that you need to do to see the issue is to go into the editor on MILF and look at sections 62 through 64 of the song.
## Please describe your issue. Provide extensive detail and images if possible.
When playing through the song MILF on normal and hard difficulties [I would assume easy as well, but I haven't checked that yet], just after the drop (sections 62 thru 64) the vocals for the bf and the mom sound like they are swapped with the notes you're trying to play. in other words, you play the held notes of the mom's voice and the mom ends up playing the harder stuff that is sung by the bf. This is just a minor bug I found, and all that would need to be done to fix it is to toggle the "must hit section" box for those three sections of the song chart.

**Comment by devin503** [comment]
The same thing is done with High.

**Comment by prokube** [comment]
> The same thing is done with High.

thank god

yeah ninja said he would fix some tracks by week 7 i think
