### ISSUE TITLE
Build instructions suggestions

### ISSUE THREAD

**Issue by hatoving** [FunkinCrew/Funkin#66]
I know this is kind of a noob question, but how do I build the game?
I know that it uses Haxe, but I seriously didn't learn the language. Am I supposed to downkload a Haxe engine and then build it that way? I tried out the .bat files in the art folder but nohing really happened.

Can someone help me lol

Take care and best regards
hat

**Comment by Polytelus** [comment]
### Not a moderator but, as the girlfriend would say, "here's how you do it":
- Download Haxe and install it according to your operating system:
https://haxe.org/download/

- Run the following commands on a terminal or command prompt:
`haxelib install lime`
`haxelib run lime setup`

Run the batch file that you want (except the switch one) on the art folder and then compile!

**Comment by hatoving** [comment]
> ### Not a moderator but, as the girlfriend would say, "here's how you do it":
> * Download Haxe and install it according to your operating system:
>   https://haxe.org/download/
> * Run the following commands on a terminal or command prompt:
>   `haxelib install lime`
>   `haxelib run lime setup`
> * If it doesn't for you, install the tools as well:
>   `haxelib install lime-tools`
> 
> Run the batch file that you want (except the switch one) on the art folder and then compile!

It almost worked, it threw an error at me saying: "Error: Could not find haxelib "newgrounds", does it need to be installed?"
And it couldn't find "butler". So yeah

**Comment by Polytelus** [comment]
Ah yes, I forgot. You need to also do `haxelib install newgrounds`.
For butler, just ignore it, as it's supposed to push a commit to github.

**Comment by hatoving** [comment]
> Ah yes, I forgot. You need to also do `haxelib install newgrounds`.
> For butler, just ignore it, as it's supposed to push a commit to github.

epic gamer moment i think

It threw this at me:
"Missing HXCPP_VARS
Error: Could not automatically setup MSVC"

**Comment by ninjamuffin99** [comment]
> For butler, just ignore it, as it's supposed to push a commit to github.
Butler is for the Itch.io uploads, it's their commandline tool for uploading. No one should need it hehe
https://itch.io/docs/butler/

**Comment by ninjamuffin99** [comment]
> It threw this at me:
> "Missing HXCPP_VARS
> Error: Could not automatically setup MSVC"
> 
> Just a reminder; I do have Haxe installed, WITH HaxeFlixel, I know the game is run by it.

For this you need to install Visual Studio community or something like that. And make sure you install the 'build tools' its a bit strange. I'll have to write a more comprehensive guide to compiling the game at some point

**Comment by gedehari** [comment]
One thing to add, you probably need to comment newgrounds API thingy in TitleState.hx, as it contains newgrounds API stuffs. The compiler would scream "APIStuff.hx not found" or something like that. I think it's in the .gitignore for a reason lol

**Comment by ElijahZAwesome** [comment]
Also if you build on linux make sure to install the latest source from their github, my solution is in that linked issue #74

**Comment by ThatGeekyWeeb** [comment]
If no one else is doing it already, then I'll make a PR to make it more clear in the README.

**Comment by ninjamuffin99** [comment]
alright I have a quick and dirty build guide in the readme with commit 7d2be49

I'll use this issue as a suggestions page on how to improve it!

**Comment by ThatGeekyWeeb** [comment]
@ninjamuffin99, linux pulls some extra libs from `haxelib`, as well as a basic requirement for `g++`, below commands need to be run as well; Some indication of them should be added to the README
```
haxel run lime setup
haxelib install fixel-addons
haxelib install fixel
haxelib install openfl
```
***
below changes based on Linux distro
Ubuntu: 
```
# apt install g++
```
Arch Linux
```
# pacman -Sy gcc
```
ppl on other distros likely know what there doing and can debug the issue themselves 
***
Also pertaining to #74, the master repo didn't work for me, and using master is a well know bad idea all around, using 1.1.1 fixed my issue, I recommend using it.
***
To wrap up;
Using the master branch is a bad idea, 1.1.1 works well without issue for [Geokureli/Newgrounds](github.com/Geokureli/Newgrounds), but 1.1.3 might also work, idk.. Below can be used to install 1.1.1 on linux
```
wget -O newgrounds.zip https://codeload.github.com/Geokureli/Newgrounds/zip/1.1.1
haxelib install newgrounds.zip
```
Below additional libs are also needed, at least on linux...
```
haxel run lime setup
haxelib install fixel-addons
haxelib install fixel
haxelib install openfl
```
Below is needed only linux
Ubuntu: 
```
# apt install g++
```
Arch Linux
```
# pacman -Sy gcc
```

**Comment by ThatGeekyWeeb** [comment]
It would also be good if someone could put together proper instructions for Windows and MacOS, I only use Linux tho, so I've given all I can, gl, and thx, also the game is great! :)

**Comment by ninjamuffin99** [comment]
Now that I think about it, might be cleaner to have it in the wiki pages of Github, allows other people to edit and modify and all that, and stays out of the way of the README (although will still have links to it in there!)

**Comment by ThatGeekyWeeb** [comment]
not a bad idea tbh

**Comment by hatoving** [comment]
Hi, sorry for not answering for so long! Inhave built the game, it works as expected. Thanks! Should I close this off now?

Take care
-hat

**Comment by kinger956** [comment]
Greetingsto all i have an issue that when i type haxelib install newgrounds in cmdtheysay error: failed with error: blocking 
Pls help me
