### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#663]
## What is your question?
Why is the dad purple? Is he the man behind the slaughter? So many unanswered questions!!!!11

**Comment by Salladk-but-no-mo-flaged** [comment]
maybe its his parents and ancestors are purple too

can be

1. black eyes with red pupil
2. hair with horns
3. purple skin
all gf family life phases
maybe can happen that

**Comment by EmeraldWizardX** [comment]
Maybe the mom and dad adopted the gf

**Comment by devin503** [comment]
I believe Daddy Dearest (and Mommy Must Murder) are both demons.
