### ISSUE TITLE
Bug Report: you can press r in week 6 dialogue and it crashes the game

### ISSUE THREAD

**Issue by jo560hs** [FunkinCrew/Funkin#670]
## If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
you play week 6
when dialogue is on screen press r
## Please describe your issue. Provide extensive detail and images if possible.
the game crashes

**Comment by OPNA2608** [comment]
Duplicate of #313.
