### ISSUE TITLE
Question: HaxeFlixel screen gone?

### ISSUE THREAD

**Issue by OPNA2608** [FunkinCrew/Funkin#673]
## What is your question?

Some time between release 0.2.7.1 and the current master (8057b29f05477783408bcb55bd5b2984d33dd2ef), the HaxeFlixel splash screen & intro jingle stopped appearing for me. Was that an intentional change or did something break on my end? I'm building both versions with Haxe 4.2.1 & all dependencies either on the latest release or a more recent git version that's compatible with 4.2.1, and both versions work fine otherwise. Just curious if I should bisect what commit caused this or if that was a conscious change.

<details>
  <summary>(Edit: Clickme for video recording)</summary>

https://user-images.githubusercontent.com/23431373/112833309-d8b27400-9096-11eb-98c4-bd8beb118943.mp4

</details>

Only patch I'm using is the Newgrounds response fix PR to make Freeplay work again, and a backport of it for 0.2.7.1.

**Comment by TentaRJ** [comment]
This is normal. It has been happening on my build as well. There aren't any undesirable effects.

**Comment by OPNA2608** [comment]
Oki, thanks for clearing that up for me.
