### ISSUE TITLE
Enhancement: Incorporate FPS Plus into official builds

### ISSUE THREAD

**Issue by jbmagination** [FunkinCrew/Funkin#675]
## What is your suggestion, and why should it be implemented?
My suggestion is that [FPS Plus](https://gamebanana.com/gamefiles/13982) be officially incorporated into the game. 

The reason why is because FPS Plus makes numerous changes that would be beneficial for gameplay and mapping. While Monster maybe shouldn't be in Freeplay until it's officially in the game, the other changes are great! 

Plus, it has an options menu (which I'm aware is already being worked on, maybe this can save some time!)

**Comment by duxeyo** [comment]
yes! especially downscroll and HJKL controls.

**Comment by jbmagination** [comment]
Bump. Would be willing to try to do some of this myself!

**Comment by polybiusproxy** [comment]
fps plus is just a mod and i dont think it will be added

**Comment by duxeyo** [comment]
> fps plus is just a mod and i dont think it will be added

you are too late, the main features of fpsplus have already been implemented in the base game.

**Comment by jbmagination** [comment]
*excluding FPS changes (I think)

either way I never expected them to actually do it, but it wouldn't hurt to ask, right?
