### ISSUE TITLE
Compilation error with discord_rpc

### ISSUE THREAD

**Issue by AndrewIdot** [FunkinCrew/Funkin#678]
So, I was trying to compile the current FNF build, when this error showed up: "Error: Could not find haxelib "discord_rpc", does it need to be installed?"
I git installed it 2 times, and I still can't get it to work.

**Comment by biggiel** [comment]
Was reading around a bit, and saw this which might help:

**Other installations you'd need is the additional libraries, a fully updated list will be in Project.xml in the project root. Currently, these are all of the things you need to install:**

Checking in the .XML file, discord-rpc is there, so assuming you didn't install it: use **haxelib install discord-rpc**

**Comment by AndrewIdot** [comment]
Even when git installed, I get this:
"source/Discord.hx:13: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:23: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:28: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:33: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:69: characters 3-13 : Type not found : DiscordRpc"

**Comment by biggiel** [comment]
Yeah, I made a mistake: really don't know what could be going wrong.

**Comment by biggiel** [comment]
Okay, let me ask, have you done the 'git' part? If not, install git-scm, and then:

**haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc**
