### ISSUE TITLE
Bug Report: cpu going mad

### ISSUE THREAD

**Issue by manimaddictedtolinux** [FunkinCrew/Funkin#679]
### If you are playing a downloaded version of the game, what operating system are you using?
Kali Linux(`x64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Ran the game as root, made it worse.
## Please describe your issue. Provide extensive detail and images if possible.

Info: Linux (specifically Kali, debian based) 64-bit
problem: The cpu gets up to 85% usage while playing
Video: https://drive.google.com/file/d/1FvLg22_s6MbxZYs2hx0k8vYae52Ud2-w/view?usp=sharing

**Comment by TentaRJ** [comment]
Computer bad

**Comment by devin503** [comment]
Your video is inaccessible (I'm not about to request access to something I'd only view once), but it's possible you may not have enough memory available. Do you have a swapfile? You can check by running `swapon -show` in a terminal

**Comment by OPNA2608** [comment]
+1 on video being inaccessible. What are your system specs? Watching `htop` while playing, I see at max 16% thread usage during gameplay and short periods of 100% thread usage when the game loads a new song / menu behind a transition.
