### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by sophiam318** [FunkinCrew/Funkin#680]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
i'm playing on https://www.newgrounds.com/portal/view/770371
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
4.8.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
no, i haven't seen anything.
## Please describe your issue. Provide extensive detail and images if possible.
when i click on story mode, or try and open the game, this screen comes up and doesn't let me continue
![Screenshot 2021-03-30 1 54 03 PM](https://user-images.githubusercontent.com/81645075/113034565-3a8ae080-9160-11eb-802f-8c24e5eb1806.png)

**Comment by devin503** [comment]
Are you using a Chromebook? If so, this happens because those kinds of devices usually don't have enough ram to load all the assets and Chrome gives up.
