### ISSUE TITLE
Bug Report: Crashing after HaxeFlixel logo

### ISSUE THREAD

**Issue by SinexProgs** [FunkinCrew/Funkin#683]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Downloaded from itch.io
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Launch the game
2. Start spamming "Enter" button
## Please describe your issue. Provide extensive detail and images if possible.
The game crashes, if you will spam the Enter button while and after HaxeFlixel logo.

https://user-images.githubusercontent.com/52968560/113043948-56759d00-91c7-11eb-85c9-a928aec90193.mp4

**Comment by ahumeniy** [comment]
Seems to be a pretty nasty bug because it freezes my computer for about a minute until the display driver crashes
