### ISSUE TITLE
Many errors when trying to compile the game.

### ISSUE THREAD

**Issue by windows10RHRE** [FunkinCrew/Funkin#686]
I am trying to compile the game, and all of these errors appeared. I made sure that there was a project.xml, that I was running PowerShell in the correct folder, and that I also added the APIStuff.hx and copy-pasting in the code, although I did add it using Windows Notepad.

I think the main cause might be due to me running "haxelib run lime setup flixel" while getting HaxeFlixel, leading to a lot of the libraries being updated, but there were some other errors that don't seem to be related.

![explorer_2021-03-30_19-21-52_LI](https://user-images.githubusercontent.com/36255180/113083135-83f32400-9190-11eb-9acc-38961f047b05.jpg)

**Comment by actuallyasmartname** [comment]
try using the 32 bit version it says 64 bit is not automatically supported or sett HXCPP_MSUC_CUSTOM and manually configure the exe library
