### ISSUE TITLE
gf christmas crash

### ISSUE THREAD

**Issue by justamole** [FunkinCrew/Funkin#689]
so im playing friday night funkin and i want load gf christmas, but i cant... when i try to it crashes my game, even tho she has the assets for it... why? 
for downloaded version i am using 0.2.7 and chrome/newgrounds im using 0.2.7.1

**Comment by CyndaquilDAC** [comment]
She doesn't load any note sprites so it crashes since the game attempts to load them when the match starts.

**Comment by CyndaquilDAC** [comment]
She doesn't load any health icon. ill do a pr

**Comment by CyndaquilDAC** [comment]
#703 here
