### ISSUE TITLE
Week 2 Crash and Week 3 lag

### ISSUE THREAD

**Issue by FFFFAN1014** [FunkinCrew/Funkin#69]
when starting week 2 the game either crashes or freezes and continues with the audio. when playing week 3 music is sometimes out of sync with the game.

**Comment by PoketrainerMS** [comment]
yoo this is #69 noice

**Comment by VMGuy23** [comment]
Is it fixed or not?

**Comment by FuseIsHere813** [comment]
> yoo this is #69 noice

Don't necropost if u have nothing important to say bozo!!
