### ISSUE TITLE
Random questions

### ISSUE THREAD

**Issue by Windows1Door2Daniel** [FunkinCrew/Funkin#690]
How characters have a seizure specialy BF?
what is Monster i know he is a lemon whats more?
is gf adopted?
![Luigi Ballin](https://user-images.githubusercontent.com/81389527/113193745-2ce36280-9215-11eb-83dc-34b13e11c0b3.gif)

**Comment by CaptainGame17** [comment]
?????????????

**Comment by nickpythonluajava** [comment]
- didnt understand question
- monster not a lemon, his head just happens to be shaped like that
- didnt understand question
- gf has parents

- why does this post exist

**Comment by Windows1Door2Daniel** [comment]
monster have a lemon head

but what is his arms, legs. torso


i saw gf is a demon
