### ISSUE TITLE
What is VsDevCmd and MSVC 

### ISSUE THREAD

**Issue by SuperSpinDashGamer39** [FunkinCrew/Funkin#692]
Ok so I try using the command "lime test windows" and this pops up "Warning: Could not find Visual Studio 2017 VsDevCmd"
and also this "Missing HXCPP_VARS Error: Could not automatically setup MSVC"

so Can someone please tell me what's wrong

**Comment by TentaRJ** [comment]
> Ok so I try using the command "lime test windows" and this pops up "Warning: Could not find Visual Studio 2017 VsDevCmd"
> and also this "Missing HXCPP_VARS Error: Could not automatically setup MSVC"
> 
> so Can someone please tell me what's wrong

Did you follow all of the instructions? You should have downloaded all of the Visual Studio packages.

**Comment by SuperSpinDashGamer39** [comment]
in witch verison 2019 or 2017 and what packages should  I download

**Comment by TentaRJ** [comment]
> in witch verison 2019 or 2017 and what packages should I download

2019. And the packages are at the bottom of the [README.md](https://github.com/ninjamuffin99/Funkin/blob/master/README.md)

**Comment by SuperSpinDashGamer39** [comment]
oh ok thanks for the tips man really apricate it

**Comment by SuperSpinDashGamer39** [comment]
but for the clang compiler its says clang compiler 11 is that ok

**Comment by TentaRJ** [comment]
> but for the clang compiler its says clang compiler 11 is that ok

Yeah that should work

**Comment by SuperSpinDashGamer39** [comment]
> > but for the clang compiler its says clang compiler 11 is that ok
> 
> Yeah that should work

it worked thanks man :)

**Comment by TentaRJ** [comment]
> > > but for the clang compiler its says clang compiler 11 is that ok
> > 
> > 
> > Yeah that should work
> 
> it worked thanks man :)

Alright cool. Please close this issue then. :)

**Comment by prokube** [comment]
close it :)

**Comment by CAXAPOK1984** [comment]
close

**Comment by Filename99** [comment]
Guys, they don't know how to close the issue, should we help them?
