### ISSUE TITLE
Help with .zip (Corrupted file)

### ISSUE THREAD

**Issue by Felis14** [FunkinCrew/Funkin#693]
I've tried like 7 times to download the file, between 150Mb to 170 Mb it stops, and if try to unzip it, WinRar says is a corrupted file, ¿What should I do?

**Comment by SuperSpinDashGamer39** [comment]
idk just delete some stuff that happens to me too and I just delete some stuff and it helps

**Comment by TentaRJ** [comment]
> I've tried like 7 times to download the file, between 150Mb to 170 Mb it stops, and if try to unzip it, WinRar says is a corrupted file, ¿What should I do?

Did you download it from the Itch.io page? Make sure it is the legitimate copy.

**Comment by Felis14** [comment]
> idk just delete some stuff that happens to me too and I just delete some stuff and it helps

Some stuff like? Thx for answering

**Comment by Felis14** [comment]
> Did you download it from the Itch.io page? Make sure it is the legitimate copy.

I downloaded it from here, the original game from Itch.io and the build from here, idk if you can download the build from Itch.io. Thx for answering

**Comment by Salladk-but-no-mo-flaged** [comment]
Remeber

you can use your OS File explorer to extract .zip folders
