### ISSUE TITLE
Bug Report:  its about freeplaymode

### ISSUE THREAD

**Issue by sebby09559** [FunkinCrew/Funkin#699]
Free play mod keeps crashing when ever i try to load freeplaymode. Could you update freeplaymode code please because i think the freeplaymode code we have now is not working???

**Comment by gf64** [comment]
You have to replace source/NGio.hx file with this: https://gist.githubusercontent.com/jbmagination/caf9eb6a7ae8b415e8acd02962f851e1/raw/d76486854a7676a0ce16907dfa82bf804b155388/NGio.hx

**Comment by sebby09559** [comment]
thx
