### ISSUE TITLE
Bug Report: Lime is not recognized

### ISSUE THREAD

**Issue by gf64** [FunkinCrew/Funkin#700]
I keep trying to compile the game and if I run `lime test windows` it keeps giving me this:

`lime : The term 'lime' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.`

Please help me! Thank you in advance.

**Comment by Leo40Git** [comment]
Run `haxelib run lime setup`.

**Comment by Kiffolisk** [comment]
haxelib install lime
haxelib run lime setup

**Comment by Hackx2** [comment]
mine is not working

**Comment by JohnDoe3453** [comment]
bro forgot to close this issue
