### ISSUE TITLE
black squares/boxes instead of characters

### ISSUE THREAD

**Issue by wtchysvto** [FunkinCrew/Funkin#706]
So i've tried looking thru others bug reports but didn't seem much helpful.

I'm playing a downloaded version of the game, 64 bit, Windows 10
Version 0.2.7.1
I did try clearing the AppData folder, reinstalling the game, trying 32 bit version but none of this seem to help.
So as it says in the title, there's black boxes/squares instead of characters, but not all of them
Title screen seems normal, but moving on to the levels
![image](https://user-images.githubusercontent.com/81928783/113520051-26e4dd00-9599-11eb-9121-39e03891fd7e.png)

Choosing screen has black squares over all characters
![image](https://user-images.githubusercontent.com/81928783/113520359-36fdbc00-959b-11eb-8607-772aa5ba2fba.png)

Tutorial, week 1, week 3 having black squares instead of bf and gf
![image](https://user-images.githubusercontent.com/81928783/113520318-e6865e80-959a-11eb-8dec-f489ec8c7879.png)

Week 2 completely broken, showing only Spooky kids
![image](https://user-images.githubusercontent.com/81928783/113520089-71fef000-9599-11eb-9249-25eab0e942e1.png)

Week 4, instead, not showing Mom
![image](https://user-images.githubusercontent.com/81928783/113520344-1d5c7480-959b-11eb-9533-51164490dcc2.png)

Week 5 not showing gf and parents
![image](https://user-images.githubusercontent.com/81928783/113520366-411fba80-959b-11eb-91f3-62fc1aea055f.png)

Week 6 completely normal
![image](https://user-images.githubusercontent.com/81928783/113520387-67455a80-959b-11eb-9bed-85e438f03b0b.png)

By the way, sprites in same places don't show when playing with mods

I've seen people with this issue as well but haven't found a solution yet. Does anyone know what to do with this?

**Comment by actuallyasmartname** [comment]
can you replicate this in the browser version? if so, post the console log. if you can't, then try compiling the game manually (see README.md) and there should be a log in the command line if you can replicate it

**Comment by binary-person** [comment]
replicated on chrome 89 on https://ninja-muffin24.itch.io/funkin

console.log (separated with double newlines):
```
source/NGio.hx:38: INIT NOLOGIN

Funkin.js:684 source/NGio.hx:51: CURRENT NG VERSION: v0.2.7.1

Funkin.js:684 source/MusicBeatState.hx:25: reg (x: -200 | y: -200 | w: 1792 | h: 1008)

Funkin.js:684 source/MainMenuState.hx:170: Story Menu Selected

Funkin.js:684 source/StoryMenuState.hx:111: Line 70

Funkin.js:684 source/StoryMenuState.hx:137: Line 96

Funkin.js:684 source/StoryMenuState.hx:170: Line 124

Funkin.js:684 source/StoryMenuState.hx:196: Line 150

Funkin.js:684 source/StoryMenuState.hx:212: Line 165

Funkin.js:684 source/MusicBeatState.hx:25: reg (x: -200 | y: -200 | w: 1792 | h: 1008)

(console.warn) Funkin.js:1970 WebGL: INVALID_VALUE: texImage2D: width or height out of range
texImage2D @ Funkin.js:1970
uploadFromTypedArray @ Funkin.js:2697
hi @ Funkin.js:2697
createRectangleTexture @ Funkin.js:2588
getTexture @ Funkin.js:796
__updateGL @ Funkin.js:2261
__updateGLFromBuffer @ Funkin.js:606
__updateFromBuffer @ Funkin.js:605
__updateShaderBuffer @ Funkin.js:2254
Hb.render @ Funkin.js:2523
Jf.render @ Funkin.js:2538
__renderGL @ Funkin.js:146
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__render @ Funkin.js:2244
__onLimeRender @ Funkin.js:2311
dispatch @ Funkin.js:1935
handleApplicationEvent @ Funkin.js:94
requestAnimationFrame (async)
handleApplicationEvent @ Funkin.js:94
requestAnimationFrame (async)
handleApplicationEvent @ Funkin.js:94
requestAnimationFrame (async)
handleApplicationEvent @ Funkin.js:94
requestAnimationFrame (async)
handleApplicationEvent @ Funkin.js:94
requestAnimationFrame (async)
handleApplicationEvent @ Funkin.js:94
requestAnimationFrame (async)
*truncated*
handleApplicationEvent @ Funkin.js:94

(console.warn) Funkin.js:1970 WebGL: INVALID_VALUE: texImage2D: width or height out of range
texImage2D @ Funkin.js:1970
__uploadFromImage @ Funkin.js:2693
getTexture @ Funkin.js:797
__updateGL @ Funkin.js:2261
__updateGLFromBuffer @ Funkin.js:606
__updateFromBuffer @ Funkin.js:605
__updateShaderBuffer @ Funkin.js:2254
Hb.render @ Funkin.js:2523
Jf.render @ Funkin.js:2538
__renderGL @ Funkin.js:146
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__renderGL @ Funkin.js:201
__render @ Funkin.js:2244
__onLimeRender @ Funkin.js:2311
dispatch @ Funkin.js:1935
handleApplicationEvent @ Funkin.js:94
requestAnimationFrame (async)
handleApplicationEvent @ Funkin.js:94
requestAnimationFrame (async)
handleApplicationEvent @ Funkin.js:94
requestAnimationFrame (async)
handleApplicationEvent @ Funkin.js:94
requestAnimationFrame (async)
*truncated*
handleApplicationEvent @ Funkin.js:94
```

**Comment by actuallyasmartname** [comment]
Funkin.js:1970 WebGL: INVALID_VALUE: texImage2D: width or height out of range

Aha.

**Comment by wtchysvto** [comment]
> Funkin.js:1970 WebGL: INVALID_VALUE: texImage2D: width or height out of range
> 
> Aha.

so, what should i do? cut resolution of sprites or smth?

**Comment by binary-person** [comment]
This is an issue that occurs only on certain GPUs. I don't know how to fix this as I'm not well versed in WebGL things

**Comment by actuallyasmartname** [comment]
What GPU do you use? As @binary-person said, it only happens on certain GPUs.

**Comment by binary-person** [comment]
probably something to do with the max texture size supported.

perhaps check `Max Texture Size` under the blue box named `Textures` here: https://webglreport.com/?v=2

Mine is 4096

**Comment by wtchysvto** [comment]
> What GPU do you use? As @binary-person said, it only happens on certain GPUs.

mobile intel(r) 4 series express chipset family

> probably something to do with the max texture size supported.
> perhaps check `Max Texture Size` under the blue box named `Textures` here: https://webglreport.com/?v=2

![image](https://user-images.githubusercontent.com/81928783/115851735-f1147500-a42f-11eb-9276-efa6e0b5d004.png)

**Comment by binary-person** [comment]
Try going under the webgl 1 tab

**Comment by wtchysvto** [comment]
@binary-person 
![image](https://user-images.githubusercontent.com/81928783/116063979-3f26b400-a68e-11eb-8e7b-7dfd78809b6f.png)
