### ISSUE TITLE
Question: how would i change the yellow bg color in the story mode week selection screen?

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#707]
the yellow bar with the characters on it.
please comment what .hx and what line, as well as how to change the color. tysm.

basically i would like it to look like this
![image](https://user-images.githubusercontent.com/81890168/113527282-0ca40280-958b-11eb-8eea-206540e38537.png)

instead of this
![image](https://user-images.githubusercontent.com/81890168/113527323-2f361b80-958b-11eb-8bae-c3b4e0385f9f.png)

**Comment by Radish4649** [comment]
Pretty sure the color is declared [here](https://github.com/ninjamuffin99/Funkin/blob/faaf064e37d5a150d8aba451d740eeb81bd2e974/source/StoryMenuState.hx#L101) on line 101:

```haxe
var yellowBG:FlxSprite = new FlxSprite(0, 56).makeGraphic(FlxG.width, 400, 0xFFF9CF51);
```
the `0xFFF9CF51` can be changed to whatever color you'd like as long as it's in the same format.

For changing the colors of the sprites, I'm pretty sure the sprites are loaded from [this file.](https://github.com/ninjamuffin99/Funkin/blob/master/assets/preload/images/campaign_menu_UI_characters.png).

**Comment by sexberpoo** [comment]
> Pretty sure the color is declared [here](https://github.com/ninjamuffin99/Funkin/blob/faaf064e37d5a150d8aba451d740eeb81bd2e974/source/StoryMenuState.hx#L101) on line 101:
> 
> ```hx
> var yellowBG:FlxSprite = new FlxSprite(0, 56).makeGraphic(FlxG.width, 400, 0xFFF9CF51);
> ```
> 
> the `0xFFF9CF51` can be changed to whatever color you'd like as long as it's in the same format.
> 
> For changing the colors of the sprites, I'm pretty sure the sprites are loaded from [this file.](https://github.com/ninjamuffin99/Funkin/blob/master/assets/preload/images/campaign_menu_UI_characters.png).

tysmm
