### ISSUE TITLE
None of my leaderboard scores have updated

### ISSUE THREAD

**Issue by Dascober** [FunkinCrew/Funkin#71]
I recently got a ton of high score that would have made it onto the the leaderboards but only one shows up and the rest don't. Does anyone know when the leaderboards refresh?
The only ones that show up:
![Screenshot (353)](https://user-images.githubusercontent.com/75961024/102035171-c2a1d180-3d8d-11eb-915b-27cba0a14f71.png)
![Screenshot (354)](https://user-images.githubusercontent.com/75961024/102035172-c33a6800-3d8d-11eb-852f-4b45d0cbe151.png)

The ones that don't show up:

![Screenshot (347)](https://user-images.githubusercontent.com/75961024/102035039-735ba100-3d8d-11eb-9f29-790fc2bf89a2.png)
![Screenshot (348)](https://user-images.githubusercontent.com/75961024/102035041-73f43780-3d8d-11eb-8bde-da7dd2975e22.png)

![Screenshot (349)](https://user-images.githubusercontent.com/75961024/102035068-8a01f800-3d8d-11eb-9a6d-a696ecf69df2.png)
![Screenshot (350)](https://user-images.githubusercontent.com/75961024/102035069-8a9a8e80-3d8d-11eb-91f7-156fd12aeb77.png)
![Screenshot (351)](https://user-images.githubusercontent.com/75961024/102035098-9ab26e00-3d8d-11eb-91cb-bff76589ca51.png)
![Screenshot (352)](https://user-images.githubusercontent.com/75961024/102035099-9b4b0480-3d8d-11eb-9297-47a0d1abbcd1.png)

**Comment by TechnikTil** [comment]
mbmb

**Comment by EliteMasterEric** [comment]
lol at this taking 4 1/2 years to get fixed
