### ISSUE TITLE
Bug Report: Trouble Compiling FNF

### ISSUE THREAD

**Issue by WhatTheRob** [FunkinCrew/Funkin#711]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
I am playing on my desktop, not on a browser.
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
No browser.
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64
## What version of the game are you using? Look in the bottom left corner of the main menu.
I cannot check because I cannot compile the game but I think it is version 0.2.7.1.
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
type in "lime test windows -debug"
Get error.
## Please describe your issue. Provide extensive detail and images if possible.
I get this error when trying to compile the game:
Error: Called from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 126
Called from CommandLineTools.hx line 641
Called from lime/tools/PlatformTarget.hx line 98
Called from WindowsPlatform.hx line 757
Called from hxp/System.hx line 653
Called from /usr/share/haxe/std/neko/_std/sys/FileSystem.hx line 81
Uncaught exception - std@sys_create_dir

**Comment by Yng-Ducky09** [comment]
Nevermind. I just reinstalled it again and it magically worked.
