### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by SkullzHehe** [FunkinCrew/Funkin#712]
### If you are playing the game in a browser, what site are you playing it from?
Newgrounds.
### If you are playing the game in a browser, what browser are you using?
My Answer: Chrome Browser
### If you are playing a downloaded version of the game, what operating system are you using?
My Answer: None
## What version of the game are you using? Look in the bottom left corner of the main menu.
My Answer: 4.8.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
My Answer: The only step was waiting there.
## Please describe your issue. Provide extensive detail and images if possible.
Screenshot:
![Screenshot 2021-04-05 at 10 54 59 AM](https://user-images.githubusercontent.com/81985581/113608289-372fa300-95ff-11eb-815c-dd14e5d35e08.png)
Okay so, I click on the game:
![image](https://user-images.githubusercontent.com/81985581/113608616-aa391980-95ff-11eb-9a71-8936851c4571.png)
Now its beginning to show the loading screen:
![image](https://user-images.githubusercontent.com/81985581/113608754-ce94f600-95ff-11eb-985d-82e98a6cf893.png)
I let it load:
![image](https://user-images.githubusercontent.com/81985581/113609220-57ac2d00-9600-11eb-9d8d-69c6ac0d70d7.png)
So once it reaches up to around 41-53% the loading screen crashes. I have tried this multiple times and it just won't load in. I have once been able to get to 71% but it still crashed on me. 
![Screenshot 2021-04-05 at 10 54 59 AM](https://user-images.githubusercontent.com/81985581/113608289-372fa300-95ff-11eb-815c-dd14e5d35e08.png)
I'm not sure what the problem could be, but I wish I could play this game since it has a huge rise in popularity, and it's a Rhythm Based game which perked my interest. I hope I did the following steps in using this **Issue Template** correctly. (Side Note: I also tried Itch.io and it did the exact same thing. I can't download the game on my computer since I'm not allowed to download stuff like games, but I can still play them.)

**Comment by actuallyasmartname** [comment]
are you using this on chromebook

**Comment by SkullzHehe** [comment]
> are you using this on chromebook, if so it may be due to ram overflow

Oh I see, thanks for the info mate! I'll try and search more in depth to what the problem could be then.. Probably is my connect, idk..
