### ISSUE TITLE
i cant download the itch version

### ISSUE THREAD

**Issue by TheLupinete** [FunkinCrew/Funkin#72]
when i download the game... it just crashes and uninstall the .exe, wtf

**Comment by gedehari** [comment]
Hi, can you elaborate what happened in detail? i think theres something to do with the antivirus.. not sure though

**Comment by TheLupinete** [comment]
oh idk i use avast no premium

**Comment by gedehari** [comment]
That might be what causing it. Maybe try pausing the antivirus, if nothing works, you can just play the web version. ty
