### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by D3MONSLAY3R101** [FunkinCrew/Funkin#725]
Whenever I try to press enter on Freeplay mode I get this error.
![Capture](https://user-images.githubusercontent.com/54100283/114030275-75161b00-98ce-11eb-9548-f0285b997c31.PNG)

**Comment by TentaRJ** [comment]
## Woah buddy!
You are receiving this message because you either:
1. Placed your entire issue in the title
2. Didn't properly use the template as specified for issues
3. Both
### Please fix this problem by editing your issue or by closing it!
