### ISSUE TITLE
swear wrod

### ISSUE THREAD

**Issue by aflacc** [FunkinCrew/Funkin#731]
fric

**Comment by VoltrexMaster** [comment]
"He spitting fax tho"

**Comment by helpmeiguess** [comment]
ok.

**Comment by supern64** [comment]
crumb

**Comment by prokube** [comment]
swear wrod

**Comment by Salladk-but-no-mo-flaged** [comment]
Last time i said a swear word i got flagged

**Comment by aflacc** [comment]
> crumb

you are a man of culture i see

**Comment by supern64** [comment]
@aflacc I am

**Comment by aflacc** [comment]
> @aflacc I am

not anymore

**Comment by Salladk-but-no-mo-flaged** [comment]
shet

**Comment by supern64** [comment]
> > @aflacc I am
> 
> not anymore

:(

**Comment by aflacc** [comment]
> > > @aflacc I am
> > 
> > 
> > not anymore
> 
> :(

never mind ur cool

**Comment by supern64** [comment]
:)On Apr 15, 2021 23:24, aflac ***@***.***> wrote:



@aflacc I am

not anymore

:(

never mind ur cool

**Comment by supern64** [comment]
@aflacc :)

**Comment by Rudyrue** [comment]
yes

**Comment by EliteMasterEric** [comment]
didn't spell "word" correctly

**Comment by moxie-coder** [comment]
> didn't spell "word" correctly

Miss Thavel wants to know your location
![IMG_6373](https://github.com/FunkinCrew/Funkin/assets/124418090/6c2b245a-f9e7-4eb7-a484-beca3d4008de)
