### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by hehehehehehehehehehehehehehehehehehe** [FunkinCrew/Funkin#732]
im confused, where is, "the root of the project," i dont know where to find it and i want to compile the game

**Comment by 4skinbruh** [comment]
I'm not sure but I think it's project.xml

**Comment by Two-Ai** [comment]
The "project root" is the top-level directory (probably called `Funkin` if you cloned it from GitHub). In other words, the folder that contains `Project.xml`, `README.md` and all the other files and folders.
