### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by helpmeiguess** [FunkinCrew/Funkin#734]
when i run lime test windows, i get this output

~/Funkin-master$ lime test windows
Warning: Lime version 7.9.0 may not be compatible with OpenFL 9.0.2 (expected version 7.7.*)
Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
/home/maddix/discord_rpc/git/discord_rpc/DiscordRpc.hx:4: characters 8-20 : You cannot access the cpp package while targeting neko (for cpp.Function)
source/Discord.hx:4: characters 8-30 : ... referenced here
source/TitleState.hx:4: characters 8-15 : ... referenced here
source/Main.hx:15: characters 37-47 : ... referenced here

im new to this so dont burn me for my stupidity and sorry for no capitalization im lazy

**Comment by helpmeiguess** [comment]
Linux btw

**Comment by actuallyasmartname** [comment]
try lime test linux or lime test ubuntu i dunno

**Comment by supern64** [comment]
I don't think cross-build works on Linux. You'll need to use Windows.
