### ISSUE TITLE
Question: Made a character and added in code and xml, crashes. Anyone know how to fix?

### ISSUE THREAD

**Issue by ExpiredOats** [FunkinCrew/Funkin#736]
Added in the icon, code, xml, character name in character list, and sprite sheet. As soon as I load in character in debug, the game crashes. I've been asking around and so far nothing is really working. Maybe one of you guys would know?

**Comment by Rs232k** [comment]
Where is located your character? Try to paste it in shared folder.

**Comment by ExpiredOats** [comment]
> Where is located your character? Try to paste it in shared folder.

I figured it out, I put the mod through /export instead of directly in assets when you open Funkin Master.
