### ISSUE TITLE
Bug Report: "Copy last" crashes when set to 0

### ISSUE THREAD

**Issue by NickHam13** [FunkinCrew/Funkin#743]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows 10, 64-bit

## What version of the game are you using? Look in the bottom left corner of the main menu.

0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

 In the Section tab of the chart editor, set the little box next to the copy last button to 0, and then press it. Game crashes.

## Please describe your issue. Provide extensive detail and images if possible.

Sorry if this is a dupe, I couldn't find it on the tracker. Title is pretty self explanatory. This is more of a "just don't do that" bug than a "this will accidentally happen during gameplay" bug, but it should still be fixed anyway. The expected behavior (in my head) was that it would copy the current section over itself again, which I now realize as I'm writing this that it would be pointless to do that anyway. But I digress.

**Comment by aflacc** [comment]
dont set it to 0 its just gonna try and copy the currently selected section.

**Comment by NickHam13** [comment]
> 
> 
> dont set it to 0 its just gonna try and copy the currently selected section.

Still needs to be fixed regardless. I lost a considerable amount of progress on a chart I was making.

**Comment by aflacc** [comment]
click load autosave
