### ISSUE TITLE
Bug Report: Character doing opposite animations for left and right inputs (ex. pressing right will trigger the left animation, pressing right when there's no note triggers left miss animation).

### ISSUE THREAD

**Issue by ExpiredOats** [FunkinCrew/Funkin#746]
Could be something in the code, but I just ripped code straight from bf-Pixel. Do I have to add something to the code?

**Comment by Two-Ai** [comment]
You might have use the opposite `flipX` value, or mess with the character flipping code at https://github.com/ninjamuffin99/Funkin/blob/master/source/Character.hx#L502-L522.

**Comment by ExpiredOats** [comment]
> You might have use the opposite `flipX` value, or mess with the character flipping code at https://github.com/ninjamuffin99/Funkin/blob/master/source/Character.hx#L502-L522.

so i did some more testing, when i remove the flipX for my character, it does the right animations for the character but now he's backwards. also tried setting his name to 'bf-___' since i see code that says if the name starts with bf, you dont need to flip, but it ends up crashing the game. since im also kind of new to this whole thing, how does the character flipping code work exactly?

**Comment by ExpiredOats** [comment]
> You might have use the opposite `flipX` value, or mess with the character flipping code at https://github.com/ninjamuffin99/Funkin/blob/master/source/Character.hx#L502-L522.

got it to work, thanks!
