### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Pigswipe** [FunkinCrew/Funkin#749]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Go to the debug (charting) menu via 7 in any song, and select any of the typeable boxes that are restricted to numbers. Press the + button 3 times and the number will jump to -2147483648. Clicking off the box will keep the number as it was. 
If you use this on the speed option, the game doesn't render any notes, and you don't miss anymore. 
If you use this on the BPM option, then it skips the '3, 2, 1, GO/DATE!' and the BPM specific elements (Girlfriend, BF, Opponent, Background elements) will run incredibly fast. 
If you use this on the note length option, then the game crashes, presumably from trying to render a huge note.
I haven't experimented much with it, but it seems to break all elements attached to the number the box uses.
## Please describe your issue. Provide extensive detail and images if possible.
The game can run at a speed and BPM for charts that are not normally possible, and breaks the game.

**Comment by PrincessMtH** [comment]
I cannot seem to replicate this bug. The + button on any number value behaves as expected, no matter how many times it is pressed, even when spamming. Attempts were made both on the latest development version as well as on the latest released version.

**Comment by Pigswipe** [comment]
![image](https://user-images.githubusercontent.com/50407359/114786522-3d82f500-9d4c-11eb-958e-d3ebf1e8eb04.png)
https://user-images.githubusercontent.com/50407359/114786617-6acfa300-9d4c-11eb-9378-f0d2fbcf43aa.mp4
Here is an image of the after effects on the chart, and a video of me reproducing it. I also asked a friend to try to do it on his computer, and he confirmed it works.

**Comment by Pigswipe** [comment]
> Press the + button 3 times
By the plus button, I meant the plus key on the keyboard, sorry.
