### ISSUE TITLE
Question: does anyone know how to make it so a mod has its own save data for scoring

### ISSUE THREAD

**Issue by aflacc** [FunkinCrew/Funkin#754]
adding an extra week will not override your score. for instance, the whitty mod is technically week 7 so any score you get on there will be your score in week 7. Is there a way I can make it so my mod has its own save data that doesn't interfere?

**Comment by Injourn** [comment]
Look for instances of "FlxG.save.data" such as FlxG.save.data.songScores and remove or replace where you see necessary.
