### ISSUE TITLE
source/Character.hx:604: characters 5-14 : Missing ;

### ISSUE THREAD

**Issue by ExpiredOats** [FunkinCrew/Funkin#757]
When trying to build the game, powershell shows this message:
source/Character.hx:604: characters 5-14 : Missing ;
Anyone know how to fix this?

Edit: Managed to fix this error from happening, but the problem now is that my character's up animations refuse to activate. I have it in the code and everything and its only the up animation that's not working. anyone know how to fix?

**Comment by Rs232k** [comment]
Check your xml and character.hx

**Comment by ExpiredOats** [comment]
> Check your xml and character.hx

![Screenshot (9)](https://user-images.githubusercontent.com/82234798/114897948-5684b800-9dd7-11eb-87ab-fa2e720261ad.png)
![Screenshot (11)](https://user-images.githubusercontent.com/82234798/114897966-58e71200-9dd7-11eb-94ff-9b8c14aa359f.png)

**Comment by Rs232k** [comment]
Where playanim idle

**Comment by Rs232k** [comment]
Sign Up wrong
SignUp

**Comment by ExpiredOats** [comment]
> Sing Up wrong
> SingUp

how tf did i miss that? that was pretty stupid on me but thanks for pointing that out, would've still been lost without the help.
