### ISSUE TITLE
Bug Report: Glitchy displaying on i3 window manager (warning: this is a nitpick)

### ISSUE THREAD

**Issue by StratusFearMe21** [FunkinCrew/Funkin#759]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
**None**
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
**N/A**
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
```
██████████████████  ████████   isaacm@isaac-swiftsf31442 
██████████████████  ████████   ------------------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: Swift SF314-42 V1.04 
████████            ████████   Kernel: 5.9.16-1-MANJARO 
████████  ████████  ████████   Uptime: 1 hour, 37 mins 
████████  ████████  ████████   Packages: 1541 (pacman) 
████████  ████████  ████████   Shell: fish 3.2.1 
████████  ████████  ████████   Resolution: 1920x1080 
████████  ████████  ████████   DE: Xfce 4.16 
████████  ████████  ████████   WM: i3 
████████  ████████  ████████   Theme: Materia-dark-compact [GTK2/3] 
████████  ████████  ████████   Icons: Papirus-Dark [GTK2/3] 
████████  ████████  ████████   Terminal: kitty 
                               CPU: AMD Ryzen 7 4700U with Radeon Graphics (8) @ 2.000GHz 
                               GPU: AMD ATI 03:00.0 Renoir 
                               Memory: 2777MiB / 7387MiB 
```
## What version of the game are you using? Look in the bottom left corner of the main menu.
**Latest git commit (could reproduce in 2.7.1 as well)**
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

1. Start the game in an empty workspace with the i3-gaps window manager, and the xfce4-panel on screen
2. Go to Week 6

## Please describe your issue. Provide extensive detail and images if possible.

On Linux there are some people who use tiling window managers instead of traditional Desktop environments, all you need to know is that this means that the window is forced to be a size and aspect ratio that is different from what is hard coded. Usually you can fix this by adding `program specified minimum size: 1280 by 720` as well as `program specified maximum size: 1280 by 1720` to the window properties under the `WM_NORMAL_HINTS` on linux builds. This forces the window into **floating mode** which ensures it's size stays consistent. I would make a pull request but I don't know haxe.

**Game *without* floating mode**
![image](https://user-images.githubusercontent.com/57533634/114805924-e09a3580-9d71-11eb-87f0-ef6fd20d3e9d.png)

**Game *with* floating mode**
![image](https://user-images.githubusercontent.com/57533634/114806113-3078fc80-9d72-11eb-92c3-3dc877065d35.png)

(btw if you can't do this in haxe you can add to the README that for i3 users they should add `for_window[class = "Funkin"] floating enable`to their configs)

**Comment by StratusFearMe21** [comment]
btw these were the commands I used to build
```bash
    cd funkin
    mkdir -p ~/haxelib
    haxelib setup ~/haxelib
    haxelib install lime
    haxelib install openfl
    haxelib install flixel
    haxelib run lime setup flixel
    haxelib run lime setup # typed y
    haxelib install flixel-tools
    haxelib run flixel-tools setup # typed y then 4
    haxelib update flixel
    haxelib update flixel-addons
    lime install newgrounds
    haxelib git polymod https://github.com/larsiusprime/polymod.git
    cat <<EOF > ~/funkin/source/APIStuff.hx
package;

class APIStuff
{
    public static var API:String = "51348:TtzK0rZ8";
    public static var EncKey:String = "5NqKsSVSNKHbF9fPgZPqPg==";
}
EOF
    lime build linux -final
```

**Comment by StratusFearMe21** [comment]
Another thing you can consider is when the app first loads, you can detect if the user is using i3 with this system command `ps -e | grep -m 1 -o -F -e i3` and if the output of it is `i3` then you might display a menu asking if you want to edit there config automatically, and if they say yes you can just add the line `for_window[class = "Funkin"] floating enable` to the bottom of the file located in `~/.config/i3/config`. After this is done run the system command `i3-msg restart`, wait for it to produce an output, then restart the window and it should work from there.

**Comment by KurtisCates** [comment]
On `floating mode` where you can see everything well. This is coming from the unused fullscreen mode. The same effect can be done is you went to `project.xml` and ticked fullscreen to true.

**Comment by StratusFearMe21** [comment]
Oh, intresting. Thanks for the tip!
