### ISSUE TITLE
Bug Report: it will not let me play... For some reason whenever I try to play I try to enter a level and then it just shows a grey screen with a square with    a dead face on it. For some reason I just can't do it and I can't download the app because I don't know if it has a virus or not

### ISSUE THREAD

**Issue by foxykitcat2020** [FunkinCrew/Funkin#762]
it keeps doing this every time I do it

**Comment by DamianBossPL** [comment]
Try following this guide: https://www.youtube.com/watch?v=9dfkMgrjDOw&t=0s
It may be caused because of the free play bug that is shown in the video.

**Comment by Rudyrue** [comment]
are you retarded
the game isn't a bug, literally every youtuber you watch and everyone you know has probably downloaded the .exe and hasn't gotten a single virus

**Comment by RippedGamesOfficial** [comment]
dumbass
