### ISSUE TITLE
Got issues with building the game.

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#766]
Hello!

I have a bit of issues with the coding on the fnf source code. I have completed every step except there is two problems I have.

1. I am not sure where the 'Project Directory' is to build the game.

2. When I try to build the game, it just says the following: 'lime' is not a recognized as an internal or external command, operable progam or batch file.

If you can, please reply if you can help, thank you!

**Comment by trayfellow** [comment]
1. project directory means where you put the folder of the game's source code
    so if you placed it in your desktop just do this :
   -cd desktop
   -cd yourfoldername

2. have you installed lime yet? when installing haxeflixel, make sure to install everything
![image](https://user-images.githubusercontent.com/48515908/114965137-3669fd00-9e9a-11eb-8e08-3c19fe5f18c5.png)


also, when installing one of these it will ask your default ide,

they are: 
[1] FlashDevelop

[2] IntelliJ IDEA

[3] Visual Studio Code

[4] None

i personally prefer picking visual studio code cause i have no idea what the others are lol

**Comment by saudena** [comment]
Thanks a lot trayfellow!

**Comment by trayfellow** [comment]
> Thanks a lot trayfellow!

yw!
