### ISSUE TITLE
(Very small, but still) Bug Report: One note without any sound on Week 1

### ISSUE THREAD

**Issue by SinexProgs** [FunkinCrew/Funkin#770]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Downloaded from itch.io
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Please describe your issue. Provide extensive detail and images if possible.
On week 1 there is a note without any sound, it's appearing on every difficulty of the song.

https://user-images.githubusercontent.com/52968560/115070786-95be2080-9f1f-11eb-895c-c268590d0166.mp4

Yeah, I know that is a so small bug, so it's doesn't deserved a mention, but anyway.

**Comment by Rs232k** [comment]
It's fixed, wait for new versions or build it for yourself.
