### ISSUE TITLE
GF sprite and probably bug

### ISSUE THREAD

**Issue by Windows1Door2Daniel** [FunkinCrew/Funkin#773]
Why GF Xmas have directional sprites? (LEFT DOWN UP RIGTH)

Also at the start of a song everyone put the sprite up

my most powerful weapon:
 https://youtu.be/dQw4w9WgXcQ

**Comment by SinexProgs** [comment]
Xmas GF is a slightly edited regular GF, so it's using the same animations as the regular one, even if player can't see them (cause of devs lazyness, I guess). You can also see the shaking BF sprite from Week 2 in Xmas BF spritesheet.

**Comment by Windows1Door2Daniel** [comment]
oh ok

**Comment by VMGuy23** [comment]
Digital Ocean saved me from that link...
Adverts.

**Comment by nickpythonluajava** [comment]
**ADS**

sometimes you hate em, sometimes you like em
