### ISSUE TITLE
Bug Report: Error "source/(file.hx): characters (something)-(something) : referenced here"

### ISSUE THREAD

**Issue by Bigmancozmo** [FunkinCrew/Funkin#775]
I am trying to make a mod but I am stopped by these errors:
_source/Discord.hx:4: characters 8-30 :     referenced here
source/TitleState.hx:4: characters 8-15 :     referenced here
source/Main.hx:15: characters 37-47 :     referenced here_

I do not know what these errors mean nor why it is saying where it is referenced.

**Comment by DamianBossPL** [comment]
Did you change something in them?

**Comment by Bigmancozmo** [comment]
I didn't change anything in them, but I will try downloading the source again just to make sure I didn't by accident

**Comment by Bigmancozmo** [comment]
No, after downloading the source again and running it, it's still giving the errors (im using mac btw)

**Comment by Bigmancozmo** [comment]
oh wait nvm i had the wrong version of the software
