### ISSUE TITLE
Adding Characters

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#777]
Got another problem :(

When I try to build the game with a new character, it says; "source/HealthIcon.hx:37: characters 3-12 : Missing ;"

Please if you can, send a solution, thanks!

**Comment by DamianBossPL** [comment]
Try following this tutorial:
https://youtu.be/jNwkEJ3-rXA

**Comment by saudena** [comment]
I was using that tutorial but it still won't work :(

**Comment by 4EverNoobys** [comment]
Isn't it clear that it said you're missing a ";"

**Comment by Rs232k** [comment]
You need to add ; to end of line 37.
