### ISSUE TITLE
Bug Report: Unchanging music

### ISSUE THREAD

**Issue by SinexProgs** [FunkinCrew/Funkin#778]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Downloaded from itch.io
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1) Go to any song
2) Disable sound by pressing 0 on numpad
3) Lose
4) Go to Story Mode selection screen
5) Enable sound by pressing 0 on numpad again
(I couldn't reproduce the bug again, but I still remember the steps, that I did. I also recorded the result.)

Or

1) Go to Freeplay Mode selection screen
2) Select any song
3) Get back to menu
## Please describe your issue. Provide extensive detail and images if possible.
Sometimes music in menu doesn't changing to the "Gettin' Freaky" after, for example, the prelisten of the song in Freeplay Mode selection screen. Things became normal after you enter any Week.

https://user-images.githubusercontent.com/52968560/115125195-b86c3a00-9ff0-11eb-9ca7-36035af01bb7.mp4

**Comment by devin503** [comment]
This is _somewhat_ intentional. The game checks to see if there's something already playing, and if not, it plays the Gettin' Freaky music.

Lines 47-50, MainMenuState.hx:
```if (!FlxG.sound.music.playing)
		{
			FlxG.sound.playMusic(Paths.music('freakyMenu'));
		}```

**Comment by SinexProgs** [comment]
> This is _somewhat_ intentional. The game checks to see if there's something already playing, and if not, it plays the Gettin' Freaky music.
> 
> Lines 47-50, MainMenuState.hx:
> 
> ```hx
> if (!FlxG.sound.music.playing)
> 		{
> 			FlxG.sound.playMusic(Paths.music('freakyMenu'));
> 		}```
> ```

But considering that I still had Game Over music playing after exiting from the song, which usually doesn't happen, this is a bug.
