### ISSUE TITLE
source/PlayState.hx:150

### ISSUE THREAD

**Issue by Yakuuu** [FunkinCrew/Funkin#781]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`) prolly, Windows 7 64bit

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1, but I tried 0.2.7 and had the same issue

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Just followed everything written in README.md

## Please describe your issue. Provide extensive detail and images if possible.
'lime test html' works for me, but when I'm trying to use 'lime test windows' It keeps saying
source/PlayState.hx:150: characters 3-39 : Warning : 'FlxCamera.defaultCameras' is deprecated, use 'Flx.Cameras.setDefaultDrawTarget' instead 
And It stops. It doesn't do anything It just stays like that and does absolutely nothing.
![screen](https://user-images.githubusercontent.com/82756080/115145978-d4a1c280-a054-11eb-9666-89062536a457.png)

**Comment by devin503** [comment]
Try waiting a few minutes, if this is your first compile it might take a while.

**Comment by Kiffolisk** [comment]
doesn't seem like an error nor a fatal error. probably you being impatient and stopping the compiler.

**Comment by Yakuuu** [comment]
> doesn't seem like an error nor a fatal error. probably you being impatient and stopping the compiler.
After leaving it running for an hour It didn't do anything. Three warnings appearing, nothing else.

**Comment by Kiffolisk** [comment]
huh. warnings is normal but the compiler stopping automatically after warnings doesn't make sense as it hasn't happened to anybody else as far as i know. does building work instead of testing?

**Comment by VMGuy23** [comment]
Have you made sure to install everything?
