### ISSUE TITLE
you broke newgrounds

### ISSUE THREAD

**Issue by aflacc** [FunkinCrew/Funkin#783]
aaaaaaaaaaaaaaaaaaa

**Comment by Polytelus** [comment]
Rip

**Comment by DillyzThe1** [comment]
lets see if he breaks anything else while he's at it.

**Comment by Polytelus** [comment]
let's see if he can make github's servers die now

**Comment by Polytelus** [comment]
which is mostly gonna happen if he pushes his local repository commits to git :trollface:

**Comment by DillyzThe1** [comment]
wait no you cant do that

**Comment by aflacc** [comment]
"check the newgrounds version of friday night funkin"
sentences said moments before disaster

**Comment by foxsouns** [comment]
The entire internet just went
```
"Yo check out the new FNF update on Newgrounds"
"Okay"
```

**Comment by aflacc** [comment]
shaking and crying rn that he would do such a thing as take down the site hes tweeted bout saying he has hope for it
