### ISSUE TITLE
you sure you wanna keep your Discord Client ID available to everyone...?

### ISSUE THREAD

**Issue by Niilyx** [FunkinCrew/Funkin#784]
Just sayin'

**Comment by devin503** [comment]
Discord client IDs are simply application IDs for Discord. They're functionally similar to message, server, and user IDs in that they identify an application as something. If it had a _token_ on the other hand, then I'd understand having to ask this question.

**Comment by Niilyx** [comment]
@devin503 wouldn't that mean I would be able to mimic Funkin for my game on Discord?

**Comment by devin503** [comment]
> @devin503 wouldn't that mean I would be able to mimic Funkin for my game on Discord?

If you use the client ID in your own application, then technically yes.

**Comment by Niilyx** [comment]
yeah that's what I meant. It's minor really, but I thought I could point it out

**Comment by TentaRJ** [comment]
Client IDs are expendable so dont worry.

What you **don't** wanna share, however, are Discord ID Tokens/Client Secrets. Those are heavily secretive...
