### ISSUE TITLE
Bug Report: Week 7 Story Mode not Loading, shows black screen 

### ISSUE THREAD

**Issue by Freecorn1854** [FunkinCrew/Funkin#786]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

Newgrounds

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

Google Chrome 

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.8

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
By going to week 7 story mode

## Please describe your issue. Provide extensive detail and images if possible.
week 7 shows black screen if you try to play week 7 in story menu, it loads fine in the freeplay menu, maybe it is the cut scenes that are causing the problem?

**Comment by hdboye** [comment]
Wait for the source code to release.

**Comment by notdonxd** [comment]
> Wait for the source code to release.

I don't think that will happen until Week 7 **FULLY releases**.

I mean, that was a **TIMED** exclusive from Newgrounds.
