### ISSUE TITLE
Pls fix the mod folder.

### ISSUE THREAD

**Issue by Euroex** [FunkinCrew/Funkin#787]
The modpack folder in the original fnf file needs to be fixed. I have a file that ISNT B-SIDE, so i don't know how to insert it.

The file is called: furry_night_funkin_mod_f2c71
Assets: images; philly (<Thats a file for the week map "Philly"); Read me Please
Link: https://gamebanana.com/skins/187311
Link for unupdated game in a website: https://hdboye.github.io/FnfModAttempt/page2/furry/
Use this to go to the page with all mods: https://hdboye.github.io/FnfModAttempt/
Download the file and tell me how to insert it ;-;

**Comment by ElixrTyu** [comment]
Oh and download the manual first file, otherwise dont message me B)

**Comment by ElixrTyu** [comment]
UGH, i forgot the new week came out. im using 0.2.7.1

**Comment by ElixrTyu** [comment]
but i SHALL get week 7. . . Hopefully.

**Comment by ElixrTyu** [comment]
@ninjamuffin99 nice name (Cameron Taylor)

**Comment by ElixrTyu** [comment]
**Fix your mod folder for 2.7.1** im not kidding.

**Comment by Hendicted** [comment]
the mod folder does not do anything at the moment, wait until 0.2.8 rolls around

**Comment by ThatGuyW** [comment]
e

**Comment by ElixrTyu** [comment]
oh
