### ISSUE TITLE
aw hel nah they aded tank to frys night fuckin

### ISSUE THREAD

**Issue by aflacc** [FunkinCrew/Funkin#788]

**Comment by ElixrTyu** [comment]
who tank?

**Comment by ElixrTyu** [comment]
i still have week 6 version

**Comment by devin503** [comment]
> i still have week 6 version

week 7 is currently ng exclusive

**Comment by foxsouns** [comment]
> > i still have week 6 version
> 
> week 7 is currently ng exclusive

linux is literally still stuck on week 4

**Comment by Hendicted** [comment]
> > > i still have week 6 version
> > 
> > 
> > week 7 is currently ng exclusive
> 
> linux is literally still stuck on week 4

not really, just stuck on 0.2.7

**Comment by foxsouns** [comment]
> > > > i still have week 6 version
> > > 
> > > 
> > > week 7 is currently ng exclusive
> > 
> > 
> > linux is literally still stuck on week 4
> 
> not really, just stuck on 0.2.7

still annoying having to compile your own, using a bogus APIStuff.hx

**Comment by ElixrTyu** [comment]
> > > > > i still have week 6 version
> > > > 
> > > > 
> > > > week 7 is currently ng exclusive
> > > 
> > > 
> > > linux is literally still stuck on week 4
> > 
> > 
> > not really, just stuck on 0.2.7
> 
> still annoying having to compile your own, using a bogus APIStuff.hx

yea.

**Comment by ElixrTyu** [comment]
> > > > > > i still have week 6 version
> > > > > 
> > > > > 
> > > > > week 7 is currently ng exclusive
> > > > 
> > > > 
> > > > linux is literally still stuck on week 4
> > > 
> > > 
> > > not really, just stuck on 0.2.7
> > 
> > 
> > still annoying having to compile your own, using a bogus APIStuff.hx
> 
> yea.

ngl its still fun using mods for 2.7.1 to do songs for soundcloud. Then i get a repost and over 250 plays already.

**Comment by LexDoesGames** [comment]
Please don't clog up the bug reports with useless topics like this.

**Comment by ElixrTyu** [comment]
> Please don't clog up the bug reports with useless topics like this.

i read your desc and no, i dont know you from scratch, do you work on fnf tho?
