### ISSUE TITLE
Visual inconsistences in "South"

### ISSUE THREAD

**Issue by Squirrel-God** [FunkinCrew/Funkin#79]
When playing South on easy, at the start of the song, the camera will zoom in on the pair as they stand still, menacingly. I think this is a really cool detail that makes the song interesting, and it's a shame that it's ONLY on easy since many people will play normal or hard instead, which means that you sadly will not get to see them do that. Though it is far from urgent, it would be ideal to make the behavior consistent across all difficulties, even if it is purely visual.

**Comment by Catsuki5856** [comment]
i believe it does that for tempo since easy shouldnt have as many notes as the other difficultys
