### ISSUE TITLE
Enhancement: Add a script to the readme for ease of use

### ISSUE THREAD

**Issue by Th3SnowyOwl** [FunkinCrew/Funkin#790]
I am suggest a .sh script to make it easier for gitpod users to set up or compile for mod creation. Anyone have any suggestions on what is could put in this to make it better? You could just put this in the docs as something like "moddev.sh"
[moddev(.sh).txt](https://github.com/ninjamuffin99/Funkin/files/6344336/moddev.sh.txt)

**Comment by notdonxd** [comment]
> I am suggest a .sh script to make it easier for gitpod users to set up or compile for mod creation. Anyone have any suggestions on what is could put in this to make it better? You could just put this in the docs as something like "moddev.sh"
> [moddev(.sh).txt](https://github.com/ninjamuffin99/Funkin/files/6344336/moddev.sh.txt)

You can do it yourself, then make a pull request. I don't think they will add it when this is on "Issues".

**Comment by Th3SnowyOwl** [comment]
oh okay, thanks for the tip. I haven't done this before :D

**Comment by notdonxd** [comment]
> oh okay, thanks for the tip. I haven't done this before :D

No problem.
