### ISSUE TITLE
Bug Report: Hangup on preloader

### ISSUE THREAD

**Issue by KitOdin** [FunkinCrew/Funkin#792]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1(is currently making a mod)
## Please describe your issue. Provide extensive detail and images if possible.
Help, for some reason after compiling the game for the neko build target, it always hangs up on the preloader, dosent even work, it instantly fails to respond on the very first frame of the preloader scene, did i mess up something? or what.

**Comment by PurpleButNotALight** [comment]
why are you trying to build with neko lol. just use windows

**Comment by KitOdin** [comment]
![image](https://user-images.githubusercontent.com/79374666/118191917-5a761b00-b413-11eb-9eef-cd3a08b601ab.png)
this...
yeah i cant get the dependences, even though i have a external hard drive with 311 GB left i still cant change the targets for the sdks with fixed locations, leaving me lacking of a way to build to windows.

**Comment by nickpythonluajava** [comment]
oogh

just get rid of things you dont use or buy an external drive

**Comment by KitOdin** [comment]
i already have a external hard drive i just need to find a way to modify the sdks with fixed locations target.

**Comment by KitOdin** [comment]
if your wondering what i mean well its these 2 duds and i cant change the drive they install too
![image](https://user-images.githubusercontent.com/79374666/118282309-28f56200-b49c-11eb-8cac-a24a7d4f0a2d.png)

**Comment by VMGuy23** [comment]
Why don't you move Windows to the external drive? 28GB is tiny

**Comment by KitOdin** [comment]
i dont want to cause i believe it would brick the pc entirely
