### ISSUE TITLE
Bug Report: Week 7 cutscenes will not load

### ISSUE THREAD

**Issue by SkoomaWhore** [FunkinCrew/Funkin#796]
FNF is finally back up on Newgrounds but everytime i pick through story mode, it'll get through the loading screen and then freeze on a black screen. No matter how many times i refresh this always happens. I hope this is fixed soon

**Comment by byemc** [comment]
I'm having this issue too! macOS 12, Safari 15.5.

**Comment by byemc** [comment]
Found a fix! I open FNF in Firefox and it worked! Probably a Safari issue, so try using Chrome[-based browsers] or Firefox.
