### ISSUE TITLE
Bug Report: So uhh... neither Boyfriend or some of the bosses are there

### ISSUE THREAD

**Issue by TankManGaming** [FunkinCrew/Funkin#807]
So its simple, Boyfriend and some of the bosses are not spawning, [https://www.youtube.com/watch?v=bwRfVqrQugk](url) so yeah, just thought i would report that, also sorry if the link doesn't work.

**Comment by PhantomMoon44** [comment]
Yeah, I'm having the same issue where all the sprites are replaced with black squares including boyfriend and girlfriend. Is that what you're referring to? Because yeah, I'm having that issue too. I don't know how to fix it, but I just wish I could play week 7 without those problems

**Comment by TankManGaming** [comment]
Woops

**Comment by TankManGaming** [comment]
> Yeah, I'm having the same issue where all the sprites are replaced with black squares including boyfriend and girlfriend. Is that what you're referring to? Because yeah, I'm having that issue too. I don't know how to fix it, but I just wish I could play week 7 without those problems

Not the same but i imagine that it comes from the same problem, but yeah playing the new week sucks with these glitches.

**Comment by The-SGPT** [comment]
memory issue, it occurs when too many shit in the server runs at once, causing to run out of memory and not load parts of the sprites, or none at all.
This is a base haxeflixel issue, not exclusive to fnf.

**Comment by TankManGaming** [comment]
> memory issue, it occurs when too many shit in the server runs at once, causing to run out of memory and not load parts of the sprites, or none at all.
> This is a base haxeflixel issue, not exclusive to fnf.

Well thats good to know, thanks,

**Comment by TankManGaming** [comment]
I guess all we can do is wait.

**Comment by PhantomMoon44** [comment]
> memory issue, it occurs when too many shit in the server runs at once, causing to run out of memory and not load parts of the sprites, or none at all.
> This is a base haxeflixel issue, not exclusive to fnf.

Thank you so much for this, I understand now why none of my methods to fix it worked. We just have to wait now.
