### ISSUE TITLE
Bug Report: Game doesnt wanna load in HaxeFlixel logo

### ISSUE THREAD

**Issue by Freddy412** [FunkinCrew/Funkin#812]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

Chrome but i tried Microsoft edge too
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.

The current version with week 7 since it doesnt wanna load in
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I couldnt since i tried everything i could
## Please describe your issue. Provide extensive detail and images if possible.
The HaxeFlixel logo gets stuck on the loading screen and it wont load anymore Higher or Lower 39%
![e](https://user-images.githubusercontent.com/82939915/115532079-1f624b00-a29e-11eb-81f3-b24c204d0dbe.PNG)

**Comment by notdonxd** [comment]
Uhm... Week 7 isn't still commited to the GitHub repository.

And that error happens due to the things the game load. 0.2.8 adds a lot of changes.
Just restart. The cache will do his magic.
