### ISSUE TITLE
Question: Open-source contributions post Week 7.

### ISSUE THREAD

**Issue by foxsouns** [FunkinCrew/Funkin#833]
## What is your question?

Hi! I was wondering if the source code to Week 7 would ever be released, and if the itch.io binaries would be updated. If this will not be the case, I was wondering just how the community would be able to play and build upon FNF as a whole, assuming that all the assets used in W7 would never go public.

**Comment by devin503** [comment]
Week 7 is currently a **timed NG exclusive**, meaning it will be coming to other platforms in the future. This is even shown in the main menu on NG, where the version reads 0.2.8 (Newgrounds exclusive preview).

**Comment by foxsouns** [comment]
Oh, cool. I haven't had access to the Newgrounds release, so I wasn't aware. Time to wait for it to come out haha

**Comment by foxsouns** [comment]
im gonna close this so that i can at least get this one out of the giant flood of issues on this thing.
