### ISSUE TITLE
Bug Report: Issue with downscroll

### ISSUE THREAD

**Issue by newergrounds** [FunkinCrew/Funkin#847]
using downscroll sometimes causes boyfriend to dissapear/flicker. girlfriend also flickers and the notes glitch out
idk how to take screenshots on newgrounds lol

**Comment by Fameroi** [comment]
lmaoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.

**Comment by devin503** [comment]
> lmaoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.

What does this have to do with the bug?
