### ISSUE TITLE
Bug Report: Not loading and freezing while loading

### ISSUE THREAD

**Issue by asdgasgfdasd** [FunkinCrew/Funkin#848]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Newgrounds
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Google Chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
Newgrounds version of week 7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No.
## Please describe your issue. Provide extensive detail and images if possible.
Whenever the game is loading, it will stop loading and freeze and it wont stop. 
<img width="1295" alt="Screen Shot 2021-04-21 at 6 51 07 PM" src="https://user-images.githubusercontent.com/82982112/115630809-ac26fc00-a2d2-11eb-940c-42650b8da916.png">

**Comment by BojayB** [comment]
If you haven't logged into newgrounds or don't have an account, make one and try again. if that doesn't work, keep this open. there will be a solution eventually.
