### ISSUE TITLE
Bug Report: the loading screen keeps getting stuck even i refresh

### ISSUE THREAD

**Issue by dazed666** [FunkinCrew/Funkin#850]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Newgrounds.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify below.
Edge
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_x64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
Latest
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No
## Please describe your issue. Provide extensive detail and images if possible.
I keep getting stuck on the loading screen from time to time even if I refresh it gets stuck on a random percentage

**Comment by BojayB** [comment]
If you're not logged into newgrounds, try logging in. Sorry if this doesn't work but it did for me.
