### ISSUE TITLE
Bug Report: The Number 8 is Missing

### ISSUE THREAD

**Issue by BmanNG** [FunkinCrew/Funkin#852]
![image](https://user-images.githubusercontent.com/82927848/115636431-f06aca00-a2db-11eb-9a5a-dde94ea481c8.png)

the number 8 is missing from EvilSk8er's name lol

**Comment by KurtisCates** [comment]
the 8 is not a character on the font

**Comment by devin503** [comment]
This is a glitch with the Alphabet file.

**Comment by aflacc** [comment]
the alphabet only supports ABCDEFGHIJKLMNOPQRSTUVWXYZ and no other characters like 1234567890, . , / ? ! [ ] : ; |

(theres a reason I didn't include ', " and \ is because the games code would not like that)
