### ISSUE TITLE
Game won't load

### ISSUE THREAD

**Issue by liwwyuwu** [FunkinCrew/Funkin#854]
Once I open the website on Newgrounds in Google and go to Friday Night Funkin on Newgrounds, It loads but stops at 55% Please fix this. 
![image](https://user-images.githubusercontent.com/82987000/115641647-822c0480-a2e7-11eb-8775-8efce87eab18.png)

**Comment by BojayB** [comment]
If you're not logged into Newgrounds, try that.
Otherwise, I have no idea, sorry man.

**Comment by george2781** [comment]
Try refreshing the page if it freezes, this is a very common issue
