### ISSUE TITLE
Bug Report: Whenever i start the game, it freezes at about 40-50%, and ive tried everything from from hard restarting the page to clearing cookies, nothing works.

### ISSUE THREAD

**Issue by JakeDean09** [FunkinCrew/Funkin#857]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
newgrounds
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
playing from newgrounds, downloaded version works fine
## What version of the game are you using? Look in the bottom left corner of the main menu.
cant tell, cant open the game
## Please describe your issue. Provide extensive detail and images if possible.
![newgrounds problem](https://user-images.githubusercontent.com/82988915/115646896-d333fc80-a2d7-11eb-9965-6f2b56961cf2.png)

**Comment by BojayB** [comment]
Are you logged into Newgrounds?
