### ISSUE TITLE
Bug Report: Chart is WAY out of sync with the music

### ISSUE THREAD

**Issue by Lucrayzor** [FunkinCrew/Funkin#859]
### If you are playing the game in a browser, what site are you playing it from?
Tried both Newgrounds and Itchio

### If you are playing the game in a browser, what browser are you using?
Tried both Safari and Chrome(both websites on each too)

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.8 on NG, v0.2.7.1 on itchio

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
it reproduces itself lol

## Please describe your issue. Provide extensive detail and images if possible.
Every single song I play, the arrows appear somewhere around an entire beat sooner than they're supposed to. It butchers my rhythm and forces me to resort to sight-reading. Don't tell me the game's always been like this and everyone just rolls with it...?

**Comment by devin503** [comment]
Try hitting the return key while playing. This may be a lag issue of some sort.

**Comment by Lucrayzor** [comment]
> Try hitting the return key while playing. This may be a lag issue of some sort.

So, pausing you mean? Tried pausing multiple times during a song, no difference at all.

**Comment by devin503** [comment]
Hmm, usually a pause buffer does the trick for me. What song are you
playing? I don't have a Mac myself, but I could try to recreate the issue
on Windows.
