### ISSUE TITLE
Finishing week 3 songs and going back to week 1 freezes the game on the first 4-ish seconds

### ISSUE THREAD

**Issue by sqirradotdev** [FunkinCrew/Funkin#86]
Happens on both story mode and freeplay mode.

Specifications:

Windows 10
Google Chrome
Friday Night Funkin v.0.2.4.1

Steps to reproduce:

1. Play Week 3 songs, either from Story Mode or Freeplay Mode
2. Finish the song or exit immediately
3. Play Week 1 songs, same thing
4. Game starts normally but will freeze after 4 seconds ish.

Screenshots:

Here is the game window and the console window:
![image](https://user-images.githubusercontent.com/10368254/102356493-3d662900-3fe8-11eb-8c96-96519a0afc83.png)

**Comment by gedehari** [comment]
Just checked, this is actually a duplicate of #75 , and then a PR #80 is currently unmerged. Should I close this?

**Comment by gedehari** [comment]
Alright, I will close this
