### ISSUE TITLE
Bug Report: Week 7 has major FPS drop

### ISSUE THREAD

**Issue by woomyyylol** [FunkinCrew/Funkin#863]
On Google Chrome in the website version of Newgrounds, Every other week has 60 fps normally, but Week 7 has a major FPS drop down to 30, and it stays for the rest of the week.

**Comment by BojayB** [comment]
I played earlier on a Chromebook and it did the same thing. If you aren't already, log into newgrounds and refresh the page. That worked for me.

**Comment by Salladk-but-no-mo-flaged** [comment]
In the cutscenes my frame rate drop to 1 fps

**Comment by Mizque** [comment]
Cutscene drops to about 5ish fps, but afterwards it only recovers to 15fps which makes it completely unplayable

**Comment by VMGuy23** [comment]
61fps all the time. Ubuntu 21.04 with AMD Ryzen 3 3200u processor integrated graphics :)

**Comment by Mizque** [comment]
> 61fps all the time. Ubuntu 21.04 with AMD Ryzen 3 3200u processor integrated graphics :)

Yes, because coming here to brag that it's not causing you issues helps with reporting a bug that's causing major performance problems with others.  So helpful, very aid, such useful, much wow.

**Comment by VMGuy23** [comment]
I'm just saying: My PC not great but got good frames. idk whats going on with others pcs
