### ISSUE TITLE
Week 7 makes the game crash (MacOS Safari)

### ISSUE THREAD

**Issue by KinkyCrab** [FunkinCrew/Funkin#868]
I've been trying to play week 7 on Newgrounds, since its the official site, but whenever it actually loads, other weeks seem to work fine, but week 7 makes the screen go dark and crash the game

I tried playing on MacOs, my browser is safari.

This only happens with the new week 7

**Comment by ArchLinus** [comment]
Same on Linux. I checked with htop and I think there's some memory leak, because each time I die the games loads about 500mb on RAM and causes the crash of other programs, included the game itself
