### ISSUE TITLE
Bug Report: It's still naughty.

### ISSUE THREAD

**Issue by BoblyBoy** [FunkinCrew/Funkin#870]
So when you turn of naughtyness off in the game in week 7 when pico shoots the tankmen in the background during the song there is more blood. I do not have a problme with it but it still is a bug

**Comment by prokube** [comment]
yeah and the Stress cutscene doesn't have NEARLY enough beeps and boops

**Comment by Salladk-but-no-mo-flaged** [comment]
The censor option is just to Week 7 i think

Go to the forums and cry like the beep you are
