### ISSUE TITLE
Not everything listed in the building section of README file is necessary to build the game

### ISSUE THREAD

**Issue by despawnedd** [FunkinCrew/Funkin#881]
At the end of the README, it says you need all of the things listed to be installed in order to build the game:

```
MSVC v142 - VS 2019 C++ x64/x86 build tools
Windows SDK (10.0.17763.0)
C++ Profiling tools
C++ CMake tools for windows
C++ ATL for v142 build tools (x86 & x64)
C++ MFC for v142 build tools (x86 & x64)
C++/CLI support for v142 build tools (14.21)
C++ Modules for v142 build tools (x64/x86)
Clang Compiler for Windows
Windows 10 SDK (10.0.17134.0)
Windows 10 SDK (10.0.16299.0)
MSVC v141 - VS 2017 C++ x64/x86 build tools
MSVC v140 - VS 2015 C++ build tools (v14.00)
```

However, this not the case, as I do not have all of that installed:
![image](https://user-images.githubusercontent.com/50424428/115786795-93494400-a3c1-11eb-8a37-e410b03dc29a.png)
![image](https://user-images.githubusercontent.com/50424428/115787027-e28f7480-a3c1-11eb-8125-387c4301e786.png)

but the game builds and runs just fine:
![image](https://user-images.githubusercontent.com/50424428/115787072-f2a75400-a3c1-11eb-8115-10385fcbbcd8.png)

I think only MSVC is required. Not completely sure, though.

**Comment by ninjamuffin99** [comment]
nice nice nice, yeah i did know that most that stuff was not needed, just a few here and there heheh. I should update README to clear out some of that stuff

**Comment by despawnedd** [comment]
I am gonna do a bit more experimenting and see what is actually needed
