### ISSUE TITLE
Question: How to download week 7

### ISSUE THREAD

**Issue by JohnyDawn** [FunkinCrew/Funkin#887]
Hi, I was just asking how exactly do you download week 7. It's been really confusing and I'm not a big programmer. So basically I just need help with downloading week 7. 

Sincerely,
JohnyDawn

**Comment by GabrielPivot** [comment]
Ok, when the version says Newgrounds Exclusive, and when it's newgrounds, it's about the big and good ol flash games and flash videos, right?
There's no way to download week 7 nuff said.

**Comment by PSI-Soft** [comment]
Not know what "Exclusive" means do ya

**Comment by JohnyDawn** [comment]
> Ok, when the version says Newgrounds Exclusive, and when it's newgrounds, it's about the big and good ol flash games and flash videos, right?
> There's no way to download week 7 nuff said.

???????????

**Comment by CaptainGame17** [comment]
you cannot

**Comment by Awfyboy** [comment]
You can't, it's a Newgrounds exclusive. So it's only available online. The itch.io version will be released soon, so wait until that one releases.

**Comment by foxsouns** [comment]
> You can't, it's a Newgrounds exclusive. So it's only available online. The itch.io version will be released soon, so wait until that one releases.

and afaik, the source will fall with it. ninja said on twitter that he'll give the source/itch binaries out if either of these happen
1. funkin on newgrounds becomes the first search on google; or
2. funkin becomes number 1 on newgrounds 

time to wait

**Comment by JohnyDawn** [comment]
ok i guess wait a week

**Comment by aflacc** [comment]
if you google friday night funkin and the newgrounds page is the top result you will be able to downolad it

**Comment by catte-cloud** [comment]
> Hi, I was just asking how exactly do you download week 7. It's been really confusing and I'm not a big programmer. So basically I just need help with downloading week 7.
> 
> Sincerely,
> JohnyDawn

You can't.

**Comment by foxsouns** [comment]
Quite literally: you must wait until Ninja releases the source code/new binaries; else play it on newgrounds.
