### ISSUE TITLE
Bug Report: When using an Xbox One controller over bluetooth, using buttons immediately causes a fail. The buttons work perfectly in menus, but when trying to set controls, pushing the respective buttons responds with [?] in the controls menu. Trying to set another button after setting it to [?] resets it to the default button name.

### ISSUE THREAD

**Issue by whydontyouliketacos** [FunkinCrew/Funkin#889]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by LiDavis386** [comment]
I have this same issue. I'm playing the browser version from Newgrounds in Chrome. Version is v0.2.8 (exclusive Newgrounds preview). The notes controls get mixed up with UI controls in-game, so whenever I press one of the face buttons it responds with UI control actions (i.e. B is mapped as Right in Notes controls & Back in UI controls, Y is mapped to Up on Notes and Reset in UI). My issue now is that I tried remapping the buttons, but whenever I input a new button it shows [?] and I can't turn it back to the default button, so the game is unplayable with Gamepad now. So in my case I suggest adding a Button Reset feature to avoid this situation.

**Comment by JOELwindows7** [comment]
# Workaround
hmm maybe for now, assign `reset` to `BACK` (Microsoft) or `MINUS` (Nintendo) ` or `TOUCHPAD CLICK` (Sony) manually?
