### ISSUE TITLE
Tankman on loading screen?

### ISSUE THREAD

**Issue by ERRORNOTFOUND40** [FunkinCrew/Funkin#893]
Dont know if this is a bug, but when you press 7 on the loading screen it shows tankman with a weird looking microphone next to the actual microphone

![Screenshot 2021-04-23 at 10 06 54 AM](https://user-images.githubusercontent.com/79368519/115883311-a7ba2a80-a41b-11eb-8f97-c62cf23c8c85.png)

**Comment by Salladk-but-no-mo-flaged** [comment]
People that makes creepypastas: Stonks

**Comment by TheDiamondfinderYT** [comment]
I think the "Weird microphone" is what they use to animate the finger
