### ISSUE TITLE
Question: about the mixed " and ' in the code

### ISSUE THREAD

**Issue by ACrazyTown** [FunkinCrew/Funkin#899]
I've noticed that in most source files, there's usually a mix between " and ' for strings and such, I just want to ask if there's a specific reason for this.

**Comment by l0nkG7** [comment]
i'm not sure if it works on Haxe but usually you mix " and ' to prevent messing up strings.
Example: 'Random stuff "lmao" xd' is a single string (Random stuff "lmao" xd)
While "Random stuff "lmao" xd"  has two strings ("Random stuff" and "xd") and lmao will cause an error bc it isn't counted as part of a string.

**Comment by ACrazyTown** [comment]
Yeah I know that, but sometimes on 1 line it's " and on the other it's " so thats qhy i wanted to ask

**Comment by olivertwistor** [comment]
I haven't programmed in Haxe, but I assume that any kind of quotation marks works equally well, like in almost any other programming language. Often it's a matter of style, but it should be consistent. Having worked collaboratively with software projects, I can tell you that it's very hard to maintain a strict and consistent style, especially when it comes to things like quotation marks that have no real impact on the code.

I'm 99 % confident you can just ignore the inconsistencies in the source files.

**Comment by ninjamuffin99** [comment]
absolutely no difference, just my weird muscle memory when typing them!
ALTHOUGH

if i need either ' OR " in a string, I will use the opposite
`'and then the man said "hey boy, get over here"'` double quote within single quotes

`"I'm usin' a bunch'o single quotes, we're goin' crazy wit' them!"` single quotes in double
