### ISSUE TITLE
Bug Report: I'm playing on internet explorer and no matter how many times I refresh the page after it freezes it continues to freeze around 60%. It started only yesterday and I haven't been able to get on since. I tried doing all the things recommended and it still is freezing. I am playing on new grounds. 

### ISSUE THREAD

**Issue by SarahTheCarer** [FunkinCrew/Funkin#904]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by actuallyasmartname** [comment]
God, the title makes me sick.
Probably due to Newgrounds server shit i dunno

**Comment by The-SGPT** [comment]
Please use the description to describe your problem next time.

Anyways, bug is related to newgrounds servers, so its a server side problem, not a game problem.
Localhosting the game works fine, so its the server that's the problem.

**Comment by hAck-3r64** [comment]
Use google chrome.

**Comment by actuallyasmartname** [comment]
> Use google chrome.

Won't always solve the problem. Newground's servers are basically overflowing now

**Comment by hAck-3r64** [comment]
> > Use google chrome.
> 
> Won't always solve the problem. Newground's servers are basically overflowing now

For me I used to use Safari and it would almost never load. When I switched to google chrome it nearly instantly loaded. ¯\_(ツ)_/¯
