### ISSUE TITLE
Bug Report: Every time I try to boot up fnf the loading bar freezes at 70 percent and if I refresh the page the bar gos lower. Also I'm using MacOs and the browser is safari.

### ISSUE THREAD

**Issue by woofysus** [FunkinCrew/Funkin#906]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by actuallyasmartname** [comment]
Newgrounds server stuff probably

**Comment by dummyloser** [comment]
I have the same problem I've refreshed the tab something around 50 times I'm not exaggerating I've searched everywhere but I can't find any answers to fix it anywhere and my friends is working just fine

**Comment by hAck-3r64** [comment]
Don't use safari. I had this problem too, just use google chrome and it basically instantly loads
