### ISSUE TITLE
yo why tankmen be here on title when press 8?

### ISSUE THREAD

**Issue by adechack12** [FunkinCrew/Funkin#908]
why they do takemain leik dhat
why tehy forcnig tiajnkanmen  to do animations?????
![image](https://user-images.githubusercontent.com/68561498/115940435-f5648080-a477-11eb-813b-02cdf0c79bae.png)

**Comment by adechack12** [comment]
HWYYYYYYYYYYYYYYW HWYYYYYYYYW HWW YW HYW YH

**Comment by adechack12** [comment]
oh fuck i closed it.

**Comment by adechack12** [comment]
WHY WH W YYWHY WHY  Y

**Comment by MultiSkittle** [comment]
why is tthat?
