### ISSUE TITLE
Bug Report: When I try to load up the game on newground on my chromebook i

### ISSUE THREAD

**Issue by AnthonyPerez11** [FunkinCrew/Funkin#913]
Its keeps on freezing even if i reload this kept happening all week please help me i want to play friday night funkin my email is 
anthonyjoseperez27@icloud.com

**Comment by hAck-3r64** [comment]
I had this problem too on my Mac. The solution for me was that I was using safari and it basically instantly loads if I use google chrome ._.

**Comment by seanpw19** [comment]
same thing is happening to me
