### ISSUE TITLE
Bug Report: all i want to know is why the game don't answer when i click the arrow down, the problem is this only occurs on friday night funkin,but in other things work the arrow,pls fix this thank you.

### ISSUE THREAD

**Issue by glitch090** [FunkinCrew/Funkin#918]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by glitch090** [comment]
> #### Verifique se há duplicatas ou problemas semelhantes, além de realizar etapas simples de solução de problemas (como limpar cookies, limpar AppData, tentar outro navegador) antes de enviar um problema.
> ### Se você está jogando em um navegador, de qual site está jogando?
> [Newgrounds](https://www.newgrounds.com/portal/view/770371) ou [Itch.io](https://ninja-muffin24.itch.io/funkin) ? Especifique abaixo.
> 
> ### Se você está jogando em um navegador, qual navegador está usando?
> Chrome (ou um navegador baseado em Chromium, ou seja, Edge, Opera, etc.), Firefox ou Safari? Especifique o golpe.
> 
> ### Se você estiver jogando uma versão baixada do jogo, qual sistema operacional está usando?
> Windows ( `x86`), Windows ( `x86_64`), Linux ou macOS? Especifique abaixo.
> 
> ## Qual versão do jogo você está usando? Olhe no canto inferior esquerdo do menu principal.
> ## Você identificou alguma etapa para reproduzir o bug? Em caso afirmativo, descreva-os abaixo. Use imagens, se possível.
> ## Descreva o seu problema. Forneça muitos detalhes e imagens, se possível.

Newgrounds, Chrome, v0.2.8(Newgrounds exclusive preview), i don't have a image but i have a report, when i will select something on menu the arrow works, but when i play week 7 the arrow don't,don't even have a miss animation.In short: the arrow don't answer only in friday nigh funkin but in other games and fuctions works.Thank you to answer

**Comment by myst-rblx** [comment]
idk man must be your computer
