### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by CuteCottonCandyCat** [FunkinCrew/Funkin#920]
Browser: Google (Newgrounds)

OS: Windows

While using DS4 windows, if I press triangle during a song, it kills me as if I had pressed R.
I don't have the triangle key set to R, and it only seems to happen in the browser version of the game, I've played the desktop version of the game without trouble.

**Comment by VMGuy23** [comment]
This doesn't seem like FNF... theres no triangle, only different direction arrows.

**Comment by MarcG2** [comment]
I had the same issue.  Surprisingly, FNF in the browser seems to natively support PS4 controllers.  For now you can disable DS4 and then remap the reset function to something else in the settings menu.

Also please rename this issue to something different so people can find this.  Something like "Triangle triggers reset when using PS4 controller"
