### ISSUE TITLE
Bug Report: Softlock

### ISSUE THREAD

**Issue by hAck-3r64** [FunkinCrew/Funkin#921]
Idk what happened, but after beating week 7 for, like, the 5th time, the kickstarter trailer was playing, and I tried skipping it but it just restarted the trailer. I even tried sitting through the trailer but it still was just in a loop.

**Comment by notdonxd** [comment]
...
Wait until source code or Week 7 is released officially.

**Comment by VMGuy23** [comment]
>FOR LUDUM DARE 47
>
>'STUCK IN A LOOP'

Ah the loop is back as a bug (text taken from https://ninja-muffin24.itch.io/friday-night-funkin)
