### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by PicoriLink205** [FunkinCrew/Funkin#922]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
I'm playing on Newgrounds.
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Google Chrome.
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
I'm using Newgrounds.
## What version of the game are you using? Look in the bottom left corner of the main menu.
V0.2.8
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No.
## Please describe your issue. Provide extensive detail and images if possible.
When you turn off Naughtiness it does nothing.

**Comment by The-SGPT** [comment]
Please wait until the itch release to see what it does.
