### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by ulyxie** [FunkinCrew/Funkin#923]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

playing from compiled source that I compiled.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

None

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Win x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.

v0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

Select Free play

## Please describe your issue. Provide extensive detail and images if possible.

Upon pressing free play, the screen went dark on html5 version and on compiled exe it showed null object reference error
![image](https://user-images.githubusercontent.com/76737930/115975941-47390380-a569-11eb-9e44-1fbc9af448e6.png)

this is the output in console when the game ran in html5 mode (same problem)
![image](https://user-images.githubusercontent.com/76737930/115975953-6899ef80-a569-11eb-9194-d561e0e8e331.png)

**Comment by Heli-o** [comment]
I just hope that I didnt forget to download something.

**Comment by Heli-o** [comment]
Yes, I forgot to download few dependencies on VS. Issue still persists even after downloading all of the dependencies.

**Comment by VMGuy23** [comment]
Did you recompile after downloading the dependencies?

**Comment by Heli-o** [comment]
ofcourse, thats why I reopened the issue. Cause I thought that it would fix after I recompiled it with the dependencies. Tho I wasnt able to find one dependency in VS installer which is C++ profiling tools. The installer just wouldnt find them so that might be the issue.

**Comment by VMGuy23** [comment]
Try removing everything in the output folder and trying again. Double-check for missing dependencies.
