### ISSUE TITLE
Bug Report: R is not rebindable

### ISSUE THREAD

**Issue by cookingboy3** [FunkinCrew/Funkin#925]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Newgrounds

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify below.
Chrome

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
n/a

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.8  (NG Preview)

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Bind any key of your choosing to R
2. Open a level
3. Press R and die because you had the audacity to try and hit a right note

## Please describe your issue. Provide extensive detail and images if possible.
The R key is hard-bound to kill you instantaneously.

**Comment by RaincloudTheDragon** [comment]
The same can be said for 7 having the purpose to bring up the debug menu in-game. If you map your controls over keys with other functions, those functions aren't automatically ignored, overwritten, or moved to different keys. R can be remapped in the UI control settings, this would fix this issue. However, ESC and 7 cannot be changed here at all, so those keys cannot be used to play. Hope this helps.
