### ISSUE TITLE
Hello, there are some problems with the game. The thing is when I try to play one of the weeks. It will not play and it will show a black screen. I hope you will fix it no need to be pressured on lol. And thanks if you fixed it. Nice ass game to play! 

### ISSUE THREAD

**Issue by ValkkRP** [FunkinCrew/Funkin#927]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Salladk-but-no-mo-flaged** [comment]
use the description to put the problem

**Comment by aflacc** [comment]
learn to use the description
