### ISSUE TITLE
Right arrow sometimes registers as a down arrow :/

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [FunkinCrew/Funkin#929]
I originally thought that I just accidentally press the down arrow sometimes (I play with two hands so I don't have to move my middle finger), but I don't think this is true. I recently replayed Satin Panties (or high I cant remember lmao) and all of the right arrows at the beginning registered as down arrows. Please fix this :(

### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

The Newgrounds version

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

Google Chrome (lmao it says blow)

## What version of the game are you using? Look in the bottom left corner of the main menu.

idk, it happened on 4/24/2021

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

play satin panties a lot and eventually it'll happen i think

## Please describe your issue. Provide extensive detail and images if possible.

i did it at the top whoops

i love you pantom arcabe

**Comment by VMGuy23** [comment]
Was Week 7 released? I think thats v0.2.8 if so
