### ISSUE TITLE
Why is the Linux version that old?

### ISSUE THREAD

**Issue by Master811129** [FunkinCrew/Funkin#934]
![image](https://user-images.githubusercontent.com/37829730/116001470-d990e400-a609-11eb-985e-293b5f3a79d6.png)

**Comment by GenericGaming** [comment]
Because it skipped the week 5 update, as far as i'm aware, but it should be on the most current version of the game now

**Comment by ecksemzee** [comment]
Now the linux version isn't there anymore but that doesn't mean FNF can't be ported to Linux. README.md documents on how to compile the game

**Comment by Master811129** [comment]
> Now the Linux version isn't there anymore but that doesn't mean FNF can't be ported to Linux. README.md documents on how to compile the game

what? that means the developers do not "support" Linux anymore? It is so sad. have the developers announced it?

**Comment by ecksemzee** [comment]
> > Now the Linux version isn't there anymore but that doesn't mean FNF can't be ported to Linux. README.md documents on how to compile the game
> > @GenericGaming
> 
> what? that means the developers do not "support" Linux anymore? It is so sad. have the developers announced it?

Developers never said Linux version is discontinued. Also Haxe is cross platform, that means you can compile FNF for linux with ease
