### ISSUE TITLE
whenever i go onto newgrounds and try playing fnf nothing works

### ISSUE THREAD

**Issue by seanpw19** [FunkinCrew/Funkin#935]
idk if its just on chromebook or if its happening on all devices

**Comment by raxeqq** [comment]
> Does it get stuck on loading HaxeFlixel? reload when the bar stops and it'll work eventually.

i have this problem too,even if i refresh,it still freezes on the loading HaveFlixel page

**Comment by VMGuy23** [comment]
Refresh when it freezes again. It takes a few refreshes
