### ISSUE TITLE
FNF crashes when i play any week (minus week 1) [Video error]

### ISSUE THREAD

**Issue by leapacho** [FunkinCrew/Funkin#938]
Sometimes it makes my screen black and freezes my computer or it recovers and gives me this error message
![errorfunkin](https://user-images.githubusercontent.com/53064426/116009078-ebfd2480-a5ed-11eb-8de0-8a322141a33b.PNG)

I tried reinstalling windows, didin't work, updating drivers led me to even more problems, i currently have an older version of NVIDIA's windows 10 drivers because the latest one bugs my screen out so i figured out that it isn't probably my computer.
Also i have a pretty old computer and the windows i have is running on a external hard drive.
I have the version 0.2.7.1 of FNF

System specs:

Windows 10 Pro
AMD Phenom(tm) 9650 Quad-Core Proccesor 2.30 GHz 64 Bits
6 GB of RAM
NVIDIA GeForce GT 730

I think that's all

**Comment by VMGuy23** [comment]
It looks like you need the new driver for the right version of OpenGL

**Comment by leapacho** [comment]
> It looks like you need the new driver for the right version of OpenGL

Whats the right version of the NVIDIA driver i need though? As i said i can't use the latest version because it bugs my screen out and other stuff...

**Comment by VMGuy23** [comment]
Find the latest that says it supports your exact card. If that bugs then find the latest that works

**Comment by leapacho** [comment]
> Find the latest that says it supports your exact card. If that bugs then find the latest that works

Alright i will try that. I still won't close this thread until i fix the problem.

**Comment by leapacho** [comment]
Alright i found out that my graphics card was broken, though thanks for the help! (i completly forgot about this thread)
