### ISSUE TITLE
Bug Report: Lemon demon/monster's left and right arrows are switched

### ISSUE THREAD

**Issue by JaidenTfsAlt** [FunkinCrew/Funkin#943]
Lemon demon/monster's left and right arrows are switched
 
I noticed this when playing week 7, to check if it was just me, I watched a playthrough and the notes were still switched

# What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.8

## Please describe your issue. Provide extensive detail and images if possible.
The left and right arrows are switched and it really bugs me

![Screenshot 2021-04-26 9 34 41 AM](https://user-images.githubusercontent.com/83233150/116111002-73d94200-a673-11eb-8338-77dcf89af9b4.png)
![Screenshot 2021-04-26 9 34 17 AM](https://user-images.githubusercontent.com/83233150/116111032-7cca1380-a673-11eb-9037-38a295e67d39.png)

**Comment by CyndaquilDAC** [comment]
this is intentional

**Comment by MateoGi** [comment]
that's because to look terrifying

**Comment by StreamyGuy** [comment]
This also happened in "Winter Horrorland" during Week 5. It should a bug though, considering the sides that the Monster faces don't match with the left and right sides.
