### ISSUE TITLE
Bug Report: My game is freezing on loading after restarting it and I really want to play it and I can't download it for personal reasons. Is there something I'm doing wrong?

### ISSUE THREAD

**Issue by naiviplus845** [FunkinCrew/Funkin#944]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by naiviplus845** [comment]
ver. 4.9.0 in newgrounds.com, google chrome

**Comment by VMGuy23** [comment]
Keep reloading. When the loading bar stops reload. After a few reloads it will finish and work. Newgrounds glitch with HaxeFlixel
