### ISSUE TITLE
Bug Report: black sprites

### ISSUE THREAD

**Issue by pokestart1212** [FunkinCrew/Funkin#945]
I play with the Edge browser from newgrounds

This error appears when I give story mode or free play, when I select any week (except week 6) that makes the sprites of some characters (boyfriend and girlfriend) and backgrounds appear black.

![image](https://user-images.githubusercontent.com/83244240/116136854-e1e82e00-a6a0-11eb-878a-c5c8d25f5ced.png)

**Comment by VMGuy23** [comment]
On Edge Dev (Ubuntu) I do not have this problem, however, on devices using the self-compiled version, I have the same issue. same sprites missing.
