### ISSUE TITLE
Bug Report: Songs have changed

### ISSUE THREAD

**Issue by VMGuy23** [FunkinCrew/Funkin#948]
I noticed a change in High between v0.2.7.1 and v0.2.8 and I don't think this is supposed to happen. Newgrounds on Edge Dev (ubuntu) on Week 4

**Comment by outofthecoral** [comment]
The charts were updated in v0.2.8, this is intentional.

**Comment by VMGuy23** [comment]
But why did it change?

**Comment by ACrazyTown** [comment]
What do you exactly mean by "change"?

**Comment by VMGuy23** [comment]
I mean, the notes to press are different in 0.2.8 than in 0.2.7.1
although i kinda prefer the newgrounds one now
i know its not a bug so i will close
