### ISSUE TITLE
Several glitches.

### ISSUE THREAD

**Issue by HakuoTan** [FunkinCrew/Funkin#95]
This is on the itch.io version, but whenever i play week 2 (sometimes it happens on week 1), the game completely freezes and i have to restart. The audio continues, but the game itself freezes. 

Theres also a glitch on all weeks; let's say i was playing week 3. I would pass pico, and move onto the next song, but as soon as pico ended, the instrumental for pico would just loop until i restarted philly nice. 

Then theres the newgrounds version. i press enter to play and it crashes. immediately. :o(

**Comment by gedehari** [comment]
This was already fixed in the latest commit cfeaf5cbc64d6bf89cb1313819ca4131cdcb2d66

Still unreleased at the moment, but it's fixed already.
