### ISSUE TITLE
Compiling help: can't install polymod

### ISSUE THREAD

**Issue by Litonfire** [FunkinCrew/Funkin#952]
Hi, for whatever reason polymod doesn't install. can someone pls help?

**Comment by Nk125** [comment]
this isn't yahoo answers xD

and is not related to the base game (the issues here are for it, not for mods)

**Comment by OPNA2608** [comment]
> and is not related to the base game (the issues here are for it, not for mods)

Polymod is a compile dependency for the base game, not a mod.

@Litonfire Please elaborate, "it doesn't install" is too vague. What are you trying to do? What did you try? What error message did you get? Did you follow the README's instructions on how to install polymod?

> 3. Run `haxelib git polymod https://github.com/larsiusprime/polymod.git` to install Polymod.

**Comment by Litonfire** [comment]
nvm figured it out

**Comment by ninjamuffin99** [comment]
please close your issues when you figure them out!
