### ISSUE TITLE
Bug Report: Week 6 opens the console to say that certain animations don't exist

### ISSUE THREAD

**Issue by outofthecoral** [FunkinCrew/Funkin#953]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
I'm using Windows x86_64.
## What version of the game are you using? Look in the bottom left corner of the main menu.
The main menu says v.2.7.1, but more specifically it's the most recent git release.
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Play any song from week 6, but one of the warnings is attached to cutscenes, so for that one it has to be from story mode.
## Please describe your issue. Provide extensive detail and images if possible.
When playing any song from week 6, the console and log automatically open to warn me that note scroll animations don't exist. If week 6 is played from story mode, a fifth warning saying that an animation called "normal" doesn't exist appears once the first text box appears. Everything else plays normally with no issues.
![no animation called](https://user-images.githubusercontent.com/83247263/116165270-7fefee80-a6c9-11eb-8f18-230e6f7b355c.png)

**Comment by leapacho** [comment]
Have you tried re downloading?

**Comment by outofthecoral** [comment]
Yes, multiple times. The issue is still there every time.

**Comment by VMGuy23** [comment]
Have you tried the itch.io version?

**Comment by The-SGPT** [comment]
Looks like ninja didnt disable debug console for that version of the game

**Comment by NotHyper-474** [comment]
Have you built the game yourself? Because that normally only happens when the game is built in debug mode.
