### ISSUE TITLE
no matter what i do, the loading screen wont load

### ISSUE THREAD

**Issue by pigsuperhero** [FunkinCrew/Funkin#955]
please help me, what do I do.

**Comment by Salladk-but-no-mo-flaged** [comment]
reload the page

Week 7 load can be long maybe by the sprites and voices

**Comment by pigsuperhero** [comment]
It doesn't work

**Comment by aflacc** [comment]
Which site are you using to play week 7

**Comment by pigsuperhero** [comment]
newgrounds

**Comment by VMGuy23** [comment]
If its stuck on HaxeFlixel loading, relaod when it gets stuck, repeat until it hits 100% in which it should work

**Comment by pigsuperhero** [comment]
Tried it, It keeps freezing around 70%

**Comment by VMGuy23** [comment]
Reload when it gets to 70

**Comment by pigsuperhero** [comment]
It goes back to zero

**Comment by VMGuy23** [comment]
How do you relaod? F5 should work. What browser are you using

**Comment by pigsuperhero** [comment]
mac

**Comment by VMGuy23** [comment]
What browser? Safari might not work. I recommend Chrome or Edge if not in use

**Comment by pigsuperhero** [comment]
will do.
