### ISSUE TITLE
Debug Animations / Sprites Positioned Incorrectly

### ISSUE THREAD

**Issue by Paper-Tiger-Lily** [FunkinCrew/Funkin#957]
This is hardly an issue that's high-priority, but I noticed that when selecting characters via the debug menu (the one opened with the 7 key), a lot of animations don't function correctly, or the sprites appear at incorrect positions. The positioning issues simply stem from how the sprites are placed: Their anchor point appears to be at the top, not at the bottom, so they clip into the floor sometimes, or float in midair, depending on the sprite. That can create circumstances like these:
![image](https://user-images.githubusercontent.com/83254700/116165908-d6116180-a6ca-11eb-8a78-0c4f7046c420.png)
![BF Levitating](https://user-images.githubusercontent.com/83254700/116165953-ee817c00-a6ca-11eb-8fe8-0c9bfad64360.png)
![image](https://user-images.githubusercontent.com/83254700/116165966-f6412080-a6ca-11eb-8085-d5237ab1c158.png)
Additionally, animations seem to be glitched for the player's character. The animations for the notes themselves last a much shorter time than usual, and idle animations for most characters (with Pico as an exception) don't play. Some characters tend to warp around wildly as well (Pico in particular), likely due to the anchor points interfering with how the sprites display.
Finally, there's a lot wrong with the speaker characters. Pico-speaker just renders a new set of speakers, instead of taking GF's place on the existing set of speakers, and freezes the game if selected as the playable character. Additionally, Pico-speaker doesn't have a set of proper animations for the arrows, and just plays the exact same animations as used in Stress (understandably so, but still). GF, meanwhile, functions normally as an opponent (likely thanks to the tutorial), but causes trouble when selected for the player character, with the same issue: a new set of speakers appearing under her, instead of the player just taking the regular GF's spot on the speakers.
This really isn't that high priority of an issue, but it would be greatly appreciated if it was fixed.

**Comment by VMGuy23** [comment]
Have you noticed that with bf-hoding-gf you can have 3 GFs too? Debug menu needs some fixes so that it works reasonably

**Comment by The-SGPT** [comment]
> The animations for the notes themselves last a much shorter time than usual, and idle animations for most characters
Thats an issue with Character.hx that is easily fixed by replacing the line 527 to `if (!isPlayer)` instead of `if (!curCharacter.startsWith('bf'))`

> sprites appear at incorrect positions
Ninja lazy to fix em, easy to fix by adding some lines.

**Comment by ninjamuffin99** [comment]
its debug, so not an issue, use debug stuff at your own caution
