### ISSUE TITLE
Bug Report: So well I'm on windows 10 on edge browser and i want to say that week 7 doesnt work properly because of the lag (20 FPS) every other chart beside charts from week 7 work properly so please fix this problem because i want to enjoy week 7 too (also freeplay menu is a bit laggy too 4 some reason)

### ISSUE THREAD

**Issue by Relmat** [FunkinCrew/Funkin#962]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by windows10win7posreadywoeskio** [comment]
HOW WOULD-
include the info plez

**Comment by aflacc** [comment]
Could you please maybe not use the Issue title as the description? Also, I don't 100% understand what your saying. 🤔

**Comment by VMGuy23** [comment]
I think that Week 7 is being laggy here, but other weeks are fine. The person wants to enjoy week 7. Week 4 a bit also (note: i do not have this problem, I just tried to make a readable version of it.)

**Comment by actuallyasmartname** [comment]
Please use the description.

**Comment by GithubPerson2021** [comment]
maybe your pc is either
1. too slow to run the game efficiently
2. A school laptop :|
