### ISSUE TITLE
no load the program

### ISSUE THREAD

**Issue by kamikasedoi945** [FunkinCrew/Funkin#963]
i am i a windows 8.1 32x bits, an i playing friday night funking and see a error, the program closes

**Comment by VMGuy23** [comment]
Did you download funkin-windows-64bit.zip or funkin-windows-32bit.zip? You need 32-bit. Also, did you extract the intire folder? The whole folder needs to be extracted (i think) for it to work

**Comment by VMGuy23** [comment]
Also, send a screnshot of error (Win+Shift+S might work on win8, dont know)

**Comment by kamikasedoi945** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/83305417/117186744-25c9ea00-ada9-11eb-890e-b7bb6a8f0625.png)

**Comment by kamikasedoi945** [comment]
I download fnf for 32x

**Comment by VMGuy23** [comment]
Have you unzipped the files? It can't be run from in the zip.

**Comment by ninjamuffin99** [comment]
not descriptive enough
