### ISSUE TITLE
The game keeps dropping frames like a bowling ball

### ISSUE THREAD

**Issue by PocketRen** [FunkinCrew/Funkin#969]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
I'm playing on Newgrounds
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
I use chrome 
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.8 (Newgrounds exclusive preview)
## Please describe your issue. Provide extensive detail and images if possible.
The game is having massive frame drop issues right now. It's dropping to 20 fps during songs, the cutscenes for week 7 were lagging, and the freeplay menu stays at a good ol 11 fps

**Comment by Rudxain** [comment]
Haxe is garbage-collected by default, just like Golang. So my guess is that the game is allocating and "forgetting" objects too frequently.

Related issues: #1237 , #1911
