### ISSUE TITLE
Online version stops loading at 87%

### ISSUE THREAD

**Issue by WolfyRed** [FunkinCrew/Funkin#971]
### If you are playing the game in a browser, what site are you playing it from?
https://www.newgrounds.com/portal/view/770371

### If you are playing the game in a browser, what browser are you using?
Google Chrome

## What version of the game are you using? Look in the bottom left corner of the main menu.
Week 7 / HaxeFlixel 4.9.0

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
The steps to reproduce the bug is load Friday Night Funkin on web browser.
It then loads until it hits `87%`.
![image](https://user-images.githubusercontent.com/66114400/116464067-81402900-a839-11eb-9ed0-e7c4f174aa74.png)

## Please describe your issue. Provide extensive detail and images if possible.
When you load Friday Night Funkin (Week 7) on Newgrounds.com, it will load and stop loading at 87%
*(itch.io build stops at 18% for some reason.)*

**Comment by NotHyper-474** [comment]
Have you tried refreshing the page? It will quickly load to the percentage it stopped at and will continue loading.

**Comment by PurpleButNotALight** [comment]
For some reason the MP4's for week 7 and the kickstarter vide don't like to load. Just refresh a couple times.

**Comment by Salladk-but-no-mo-flaged** [comment]
> For some reason the MP4's for week 7 and the kickstarter video don't like to load. Just refresh a couple times.

is a ogg file

**Comment by VMGuy23** [comment]
OGG is sound. MP4 is video. MP3 is used for sound on web version but OGG on desktop.

**Comment by wellsilver** [comment]
Do you use chromebook?
