### ISSUE TITLE
Bug Report: Missing note in "Winter Horrorland"

### ISSUE THREAD

**Issue by lauyc-c** [FunkinCrew/Funkin#975]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Newgrounds
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify below.
Chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
v0.2.8
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Playing "Winter Horrorland", either in Story Mode or Freeplay.
## Please describe your issue. Provide extensive detail and images if possible.
When the Monster sings "Gonna take a piece of your rabies, and vivisect your mind." for the first time, a note which corresponded to the time when the Monster sings the word "rabies" was missing for both the Monster and the Boyfriend.
![2021-04-29 (7)](https://user-images.githubusercontent.com/77763953/116495815-977ed100-a89b-11eb-89f0-5ead9dde1017.png)
![2021-04-29 (10)](https://user-images.githubusercontent.com/77763953/116495825-9f3e7580-a89b-11eb-958b-1daa41234ac0.png)

**Comment by TheDiamondfinderYT** [comment]
They sometimes remove notes for easier difficulties. If you go on to easy mode, you'll see a LOT of missing notes, while on hard, you'll see none.

**Comment by StreamyGuy** [comment]
I know, but this occurred on Hard Mode of all difficulties.

**Comment by VMGuy23** [comment]
There is an occasional not-done note even in hard mode.

**Comment by prokube** [comment]
speaking of which, "separate you from your eyes" is still fucked up on Monster's side

**Comment by Klanker** [comment]
fr fr
