### ISSUE TITLE
Bug Report: so when i press enter sometimes, and when i try to load the game it does nothing. I use chrome

### ISSUE THREAD

**Issue by MegaManPlayz** [FunkinCrew/Funkin#981]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by actuallyasmartname** [comment]
Can you please use the description and maybe attach a video?

**Comment by MegaManPlayz** [comment]
Ok

**Comment by MegaManPlayz** [comment]
![Screenshot 2021-04-30 4 17 17 PM](https://user-images.githubusercontent.com/83428902/116755126-8fc04900-a9cf-11eb-945d-32173799ba6d.png)
it doesn't work

**Comment by actuallyasmartname** [comment]
Try opening the console via inspect element

**Comment by MegaManPlayz** [comment]
im on chrome and dont know what that is

**Comment by The-SGPT** [comment]
Happens when newgrounds version checker fails.
