### ISSUE TITLE
when i try to get the secret song where the lemon demon sings that he doesn't have an iphone my game freezese 

### ISSUE THREAD

**Issue by traktorist13** [FunkinCrew/Funkin#985]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by nickpythonluajava** [comment]
the json nor the inst or voices are in the game

**Comment by aflacc** [comment]
The whole thing is a joke and was never in the files... what is your iq

**Comment by nickpythonluajava** [comment]
> The whole thing is a joke and was never in the files... what is your iq

yeah i knew
