### ISSUE TITLE
Question: Sprites

### ISSUE THREAD

**Issue by Espliz24** [FunkinCrew/Funkin#986]
## What is your question?
Hey ninjamuffin i was playing in the newgrounds page (because on the friday night funkin' to download the fps don't go up) and the sprites don't charge and i think you can help me. 
Bye
![imagen_2021-04-30_111930](https://user-images.githubusercontent.com/83468906/116730607-ee70cd00-a9a5-11eb-92e1-d5c5bb88af02.png)

**Comment by VMGuy23** [comment]
What browser?

**Comment by marcos10pc** [comment]
same thing.. I using chrome

**Comment by VMGuy23** [comment]
I saw this when using Chrome (Android) with desktop site.

**Comment by The-SGPT** [comment]
Memory issue.... again.
This happens when the game doesnt have enough memory to store sprites

**Comment by Espliz24** [comment]
> Memory issue.... again.
> This happens when the game doesnt have enough memory to store sprites

and what i can do?

**Comment by VMGuy23** [comment]
Get more RAM (and use 64-bit if not already)

**Comment by Espliz24** [comment]
> Get more RAM (and get a 64-bit computer if not already)

i have a windows 7 and my browser is opera gx

**Comment by VMGuy23** [comment]
In System (Control Panel) it should say whether you have 32-bit or 64-bit. Memory under Performance (Task Manager) should say how much RAM you have. Maybe try another browser (e.g. Edge)

**Comment by Espliz24** [comment]
> In System (Control Panel) it should say whether you have 32-bit or 64-bit. Memory under Performance (Task Manager) should say how much RAM you have. Maybe try another browser (e.g. Edge)

i'm using edge and it continues with the black squares

**Comment by VMGuy23** [comment]
How much RAM do you have and is your system 64-bit or 32-bit?

**Comment by Espliz24** [comment]
> How much RAM do you have and is your system 64-bit or 32-bit?

32 bits and 4.00 GB (3.46 GB usable) of ram

**Comment by VMGuy23** [comment]
Probably your system doesn't have enough RAM to keep all the assets loaded. You may have to download. First, try uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/ which might work a bit better because even though still newgrounds, its only fnf. If that not work, try donload

**Comment by Espliz24** [comment]
> Probably your system doesn't have enough RAM to keep all the assets loaded. You may have to download. First, try uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/ which might work a bit better because even though still newgrounds, its only fnf. If that not work, try donload

how i download it?

**Comment by VMGuy23** [comment]
Did you go to the link I sent? Also, if it showed blsck squares, ninjamuffin99.itch.io/funkin for download

**Comment by Espliz24** [comment]
![imagen_2021-05-03_111935](https://user-images.githubusercontent.com/83468906/116909436-71da2a80-ac01-11eb-8203-c24687348d98.png)
the fps don't go up

**Comment by VMGuy23** [comment]
Yeah it just seems your PC that great, nothing I can really do
(also, thats windows 10, not windows 7)

**Comment by Espliz24** [comment]
> Yeah it just seems your PC that great, nothing I can really do
> (also, thats windows 10, not windows 7)

ok thanks

**Comment by Espliz24** [comment]
thank you all for helping me.

bye.
