### ISSUE TITLE
Question: Protecting API Keys

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [FunkinCrew/Funkin#987]
## What is your question?
Directly referencing API keys in source code is not a good idea, as it will appear in compiled javascript, and a relatively experienced person can find them in a few minutes. Have you considered protecting them, or doing something special in the web build?
Have you tried using an obfuscator on the javascript? If I wanted to cause chaos I could very easily make a build that always gives me 69696969 points on a song and put in the correct api keys. I just wanted to make sure you know about this.

**Comment by jbmagination** [comment]
He thought about this:

> I gitignore the API keys for the game, so that no one can nab them and post fake highscores on the leaderboards. But because of that the game doesn't compile without it.
> 
> Just make a file in `/source` and call it `APIStuff.hx`, and copy paste this into it
>
> ```haxe
> package;
> 
> class APIStuff
> {
> 	public static var API:String = "";
> 	public static var EncKey:String = "";
> }
> 
> ```
>
> and you should be good to go there.

**Comment by TheDrawingCoder-Gamer** [comment]
I understand that, but what I am worried about is the compiled javascript. It doesn't matter if he gitignore's it because the apikeys are in the compiled javascript.

**Comment by jbmagination** [comment]
http://www.newgrounds.io/help/encryption/

**Comment by TheDrawingCoder-Gamer** [comment]
`Using encryption is very secure, as long as the end-use can not easily find your encryption key.` I can easily find the encyption key in the javascript on the website, which isn't very hard to download

**Comment by TheDrawingCoder-Gamer** [comment]
`While truly dedicated users could reverse engineer your code and cheat, most people will be too lazy to do so.` this code is way too easy to reverse engineer

**Comment by jbmagination** [comment]
Ah-- I just realized I was stupid and didn't bother to check the Haxe library repository. A simple comparison and yeah, I think I have indeed found the API keys

**Comment by jbmagination** [comment]
Likely a good idea to delete this issue-- the fact that it's still open is just bringing more awareness to it, and it's probably better to just message ninjamuffin99 directly about it

**Comment by TheDrawingCoder-Gamer** [comment]
How would one do so?

**Comment by jbmagination** [comment]
Deleting doesn't appear to be enabled-- so closing it is just a "Close issue" button

**Comment by TheDrawingCoder-Gamer** [comment]
I mean how would one message ninjamuffin

**Comment by jbmagination** [comment]
ninjamuffin99 has an email on their GitHub page! Also Newgrounds is a thing but I bet that's super cluttered

**Comment by TheDrawingCoder-Gamer** [comment]
ok
