### ISSUE TITLE
Bug Report: FNF Newgrounds

### ISSUE THREAD

**Issue by TechnoSkull** [FunkinCrew/Funkin#989]
There is a bug on Newgrounds FNF where if you play any song on any week it gets bass boosted to the point where its not enjoyable.

https://user-images.githubusercontent.com/83478538/116760016-74f2d200-a9d9-11eb-96d0-b385fab8b836.mp4

**Comment by VMGuy23** [comment]
1. Check volume settings on fnf
2. I want this

**Comment by nickpythonluajava** [comment]
maybe try my website
nickputhonluajava.github.io/Funkin
