### ISSUE TITLE
Bug Report: the tracklist is bugged in the storymode menu when compiling the game

### ISSUE THREAD

**Issue by Pinks8n** [FunkinCrew/Funkin#990]
tutorial doesnt show up and neither does the 3rd song of any of the other weeks

**Comment by VMGuy23** [comment]
Same problem here- think its a duplicate

**Comment by VMGuy23** [comment]
Duplicate of #932

**Comment by Pinks8n** [comment]
ty

**Comment by VMGuy23** [comment]
Type `haxelib git openfl https://github.com/openfl/openfl` to fix the issue
