### ISSUE TITLE
Having trouble with background animations. (background animations similar to the crowd in week 5)

### ISSUE THREAD

**Issue by ExpiredOats** [FunkinCrew/Funkin#991]
I already have my spritesheet and code down, but it just refuses to play the animation and just sits there. I'll post code so people can look through and see if any mistakes were made.

						    house = new FlxSprite(835.7, 12.15);
						  house.frames = Paths.getSparrowAtlas('house');
						  house.animation.addByPrefix('idle', "House bop", 24, false);
						  house.antialiasing = true;
						  house.scrollFactor.set(0.9,0.9);
						  house.setGraphicSize(Std.int(house.width * 1));
						  house.updateHitbox();
						  add(house);

                                case 'Marco-House':
				house.animation.play('idle', true);

Hope this helps

**Comment by VMGuy23** [comment]
Why was it closed?
