### ISSUE TITLE
Bug Report: Some of the sprites and backgrounds appear as black boxes

### ISSUE THREAD

**Issue by KaidenPhillips** [FunkinCrew/Funkin#992]
The GF and BF sprites appear as black boxes (except in week 6 and the the week 7 cutscenes)  and as far as I know the spookies background appears as a black box and there's probably more I haven't looked at yet

**Comment by VMGuy23** [comment]
Where? What browser?

**Comment by KaidenPhillips** [comment]
Brave, and on Newgrounds

**Comment by VMGuy23** [comment]
Tried Chrome? Edge? I have this issue but only on Chrome for Android in Desktop Site.

**Comment by KaidenPhillips** [comment]
I have tried Chrome and I'd rather die than use Edge, I have a Chromebook which is a hybrid yet still mainly an Android

**Comment by VMGuy23** [comment]
Try Chrome, then try Edge (I mean, its actually good now)

**Comment by The-SGPT** [comment]
Memory issue caused by browsers, wont get fixed because thats just how it is

**Comment by KaidenPhillips** [comment]
Well shit

**Comment by VMGuy23** [comment]
Thats hy it happened on my 3GB of RAM Android tablet and not my 16GB RAM laptop or my freinds iPad
