### ISSUE TITLE
Bug Report: Week 2 Songs on Newgrounds Are Too Laggy to Play (on Chrome Browser)

### ISSUE THREAD

**Issue by Clankdoom** [FunkinCrew/Funkin#993]
The Week 2 songs on the newgrounds version are too laggy to play. I'm using Google Chrome as a browser, and I noticed that changing the difficulty to easy very slightly boosts the frame rate.

**Comment by VMGuy23** [comment]
What specs? probably caused by slow device

**Comment by Clankdoom** [comment]
I'm using a chromebook to play it.

**Comment by VMGuy23** [comment]
That's why... Chromebooks are naturally slow. Most laptops or PCs will be faster.
They're bad because the software is light

**Comment by Clankdoom** [comment]
Well, guess I can't play those levels. Unless the game makes it onto a
different platform. Thanks for the help!

**Comment by VMGuy23** [comment]
There might be an android app
See if there is and try that

**Comment by Clankdoom** [comment]
I did, but my phone isn't great either so I can't even load any songs...

**Comment by VMGuy23** [comment]
android app on chromebook?
