### ISSUE TITLE
Bug Report: Error while compiling the game

### ISSUE THREAD

**Issue by realdealmess** [FunkinCrew/Funkin#994]
hello, as you know, in the cmd it gave me an error

Here it is:
C:/Users/Usuario/haxelib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/Users/Usuario/haxelib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:150: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\Usuario\Documents\Funkin-master\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

I dont wanna install 22GB of crap.

**Comment by VMGuy23** [comment]
You need to to compile the game.

**Comment by MateoGi** [comment]
how? i install everything, the cmd does n o t h i n g i wait, and a error
appear'd!

**Comment by VMGuy23** [comment]
You need to install the 22GB of stuff. It's needed.

**Comment by blbahuba** [comment]
hello i have the same problem but i install the 22GB stuff and it doesnt work ( error: C:/Users/blbahuba/haxelib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
error: C:/Users/blbahuba/haxelib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access )

**Comment by VMGuy23** [comment]
That's not an error, it will still work with those

**Comment by blbahuba** [comment]
Ok i  dont have these errors anymore but if i type in to the windows powershell "lime test windows - debug" it will just tell me"source/titlestate. Hx:61 :characters 16-28 :Type not found :APIStuff" and then "source /Freeplaystate. Hx :89 :characters 3-6 : Expected, or  )"

**Comment by VMGuy23** [comment]
You need to create APIStuff.hx as mentioned in the build instructions

**Comment by blbahuba** [comment]
I did that

**Comment by blbahuba** [comment]
Well i did it as a txt file

**Comment by blbahuba** [comment]
Because i dont know how to make an hx fe XD

**Comment by VMGuy23** [comment]
Just rename .txt to .hx after making it

**Comment by blbahuba** [comment]
Ok one error down now thw second o e

**Comment by VMGuy23** [comment]
Recompile and send the error again

**Comment by blbahuba** [comment]
Ok here it is "source/Freeplaystate.hx :89  :characters 3-6 :Expected  ,  or  )"

**Comment by VMGuy23** [comment]
What's at line 89 of Freeplaystate.hx?

**Comment by blbahuba** [comment]
I was messing with the code and i forget to put the ending tjink you pur on
the and of your code so im sorry 😂😂😂

Dne po 3. kvě 2021 17:47 uživatel VMGuy23 ***@***.***> napsal:

**Comment by VMGuy23** [comment]
So is it fixed then? If so, close the issue

**Comment by blbahuba** [comment]
Yeah its DONE


Dne po 3. kvě 2021 17:54 uživatel VMGuy23 ***@***.***> napsal:

**Comment by prokube** [comment]
yo Mateo did you figure it out yet

**Comment by MateoGi** [comment]
im gonna delete this, because im using kade engine

>
