### ISSUE TITLE
Bug report: Softlock (?) on login

### ISSUE THREAD

**Issue by kompeigompei** [FunkinCrew/Funkin#995]
First time reporting something like this, hopefully doing this right.
Logging into the game softlocks the game and stays on "Login Successful." Restarting the game is the only way to continue

Steps: Menu -> Options -> Login -> Login on a different tab -> Softlock

[Screen Shot 2021-05-01 at 11 58 51 AM](https://user-images.githubusercontent.com/26257413/116792300-99e85300-aa74-11eb-9f41-d5a9d0ba14a1.png)

**Comment by VMGuy23** [comment]
Have you tried backspace? Enter? Space?

**Comment by antiylemon** [comment]
yea, i tried esc, enter and space
pressed every key on my keyboard lol

**Comment by VMGuy23** [comment]
I got same result, OK button just disappears after Enter but nothing else

**Comment by The-SGPT** [comment]
Fixed in itch.io build to come™

**Comment by antiylemon** [comment]
poggers thank you
