### ISSUE TITLE
Question: How does this happen?

### ISSUE THREAD

**Issue by VMGuy23** [FunkinCrew/Funkin#996]
## What is your question?
Random sites have got week 7. How and why?

**Comment by TheDrawingCoder-Gamer** [comment]
They clone the source of the game which isn't that hard to do. They are just mirrors of newgrounds.

**Comment by TheDrawingCoder-Gamer** [comment]
not source, just the files

**Comment by VMGuy23** [comment]
Nice. How do they do it?

**Comment by VMGuy23** [comment]
I think they just iframe https://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/ or something

**Comment by TheDrawingCoder-Gamer** [comment]
I don't really know, I just know they copy files. Personally i've attempted to download files but couldn't find an automatic way to do it.

**Comment by VMGuy23** [comment]
Going to the link above works perfectly and displays in a similar way to a self-compiled version

**Comment by TheDrawingCoder-Gamer** [comment]
yeah, that's where i grabbed some files, by going through the system
it's basically what would display if you ran `lime test html5'

**Comment by VMGuy23** [comment]
Yeah, except you can't really run "lime test html5" for v0.2.8 yet
